### ISSUE TITLE
use npm install, can not import OrgChartJS

### ISSUE THREAD

**Issue by hileix** [BALKANGraph/OrgChartJS#1]
I look at the source code:

```javascript
var OrgChart = function(b, a) { 
  // ...
}
```
Only declare the OrgChart function, but there is no export.So I can only in HTML file for reference.

**Comment by BALKANGraph** [comment]
You are correct. thanks for reporting this problem

The issue will be addressed with the next version, after few day

**Comment by hileix** [comment]
Thank you very much!

**Comment by BALKANGraph** [comment]
We have added "exports" (not released). But we are interested what are you trying to achieve. Do you want to use OrgChart JS on the server? 

Can you please elaborate more about your use case

**Comment by hileix** [comment]
We want to  use OrgChart JS on frontend, use [React](https://github.com/facebook/react).

In our products, one such function is to display the personnel structure of each department. So we found a lot of open source OrgChart JS, but none of them felt right for our product.Until we found your OrgChart JS.

We bought your OrgChart JS last week, when OrgChart JS was old version, and was not called OrgChart JS.

In the old version of OrgChart Js,we can custom form, but in new version of OrgChart JS, we can not custom form.

We found the new version of orgChart more beautiful, and can custom style.And in OrgChart JS, there are options, methods and events.We think it is very nice designed.

On the official website, we found that many documents were not available, only five API Reference.

We hope you can improve the documents, because we think the new version of orgchart is good and we will continue to use it.

Thank you so much for your hard work!😁😁😁

**Comment by BALKANGraph** [comment]
We are going to wrap OrgChart JS in React component, the development has started

Regarding the Custom Edit Form, actually both versions do support Custom Edit Form

See Custom Edit Form section in [https://balkangraph.com/OrgChartJS/Docs/Edit](https://balkangraph.com/OrgChartJS/Docs/Edit )

API reference will be completed very soon

**Comment by hileix** [comment]
Thank you for your hard work!😁

**Comment by gabrielgugelmin** [comment]
Hi! Any news about this? :D

**Comment by ihd-dev** [comment]
Any updates on this??

**Comment by sargishovnannisyan** [comment]
Hi there,

Planning to use this in app, that potentially becomes big one.
Can you please tell me the status of import issue, because we are planning to combine this with Vue js.

**Comment by gs-dchakraborty** [comment]
Hi,
I also want to install it using npm module and import it. Can you please tell me when this enhancement will be available?

**Comment by drorElgabsi** [comment]
+1

**Comment by caeserbala** [comment]
any update on this we are planning to buy org chart for our project but if react wrapper isn't there hard to propose this library

**Comment by caeserbala** [comment]
I have used postscribe to load JS to resolve this issue 

export class OrgChartReactPage extends React.Component {
     OrgChartUi: any;

    constructor (props) {
        super(props);
    }
    componentDidMount () {
        postscribe('#OrgChart', '<script src="/scripts/orgchart.js"></script>', {
        });
        this.OrgChartUi = new OrgChart(document.getElementById('OrgChartContainer'),
        {
           nodes: [
                { id: 1, name: "Amber McKenzie" },
                { id: 2, pid: 1, name: "Ava Field" },
                { id: 3, pid: 1, name: "Peter Stevens" },
                { id: 4, pid: 2 , name : 'Michel'},
                { id: 5, pid: 2 , name: 'maya'},
                { id: 6, pid: 3 , name: 'chetan' },
                { id: 7, pid: 3 , name : 'singaram'},
                { id: 8, pid: 4 , name: 'hello'},
            ],
     
           
        });
        
    }
    render () {
        return(
            <div id='OrgChart'>
                <div id='OrgChartContainer'></div>
            </div>
        )
}
}

**Comment by ohoffmann** [comment]
OrgChart is not defined - how did you import the class itself?

**Comment by ncmadhan1989** [comment]
> We want to use OrgChart JS on frontend, use [React](https://github.com/facebook/react).
> 
> In our products, one such function is to display the personnel structure of each department. So we found a lot of open source OrgChart JS, but none of them felt right for our product.Until we found your OrgChart JS.
> 
> We bought your OrgChart JS last week, when OrgChart JS was old version, and was not called OrgChart JS.
> 
> In the old version of OrgChart Js,we can custom form, but in new version of OrgChart JS, we can not custom form.
> 
> We found the new version of orgChart more beautiful, and can custom style.And in OrgChart JS, there are options, methods and events.We think it is very nice designed.
> 
> On the official website, we found that many documents were not available, only five API Reference.
> 
> We hope you can improve the documents, because we think the new version of orgchart is good and we will continue to use it.
> 
> Thank you so much for your hard work!😁😁😁

can you share the react snippet,i strucked at some point

**Comment by ZornitsaSerbezova** [comment]
This may be helpful: https://github.com/BALKANGraph/OrgChartJS/issues/111#issuecomment-518160303
