### ISSUE TITLE
pan zoom in mobile devices

### ISSUE THREAD

**Issue by doarsal** [BALKANGraph/OrgChartJS#10]
Is it possible that the organization chart can be controlled by pan zoom from a mobile device ?. In the previous version of GetOrgChat if possible, but not in this new version.

**Comment by BALKANGraph** [comment]
pan/zoom will be implemented in the next version

**Comment by BALKANGraph** [comment]
you can download the latest version
ver 2.8.9  support pan, zoom, pinch is supported
