### ISSUE TITLE
Our data is down to 139 rows but still can't get passed the 200 node limitation. 

### ISSUE THREAD

**Issue by chrisprabhu** [BALKANGraph/OrgChartJS#100]
Hello,

We are attempting to provide a demonstration version of our data before purchasing. We truncated our data to 139 IDs however we still get the error "The evaluation version is limited to 200 nodes! 
See more" Does anyone have any ideas about why this error is still there? 

Thanks for your help,
Chris

**Comment by webcall-me** [comment]
Try to open in a different browser

For example Firefox

**Comment by chrisprabhu** [comment]
I'm not sure what changed but the data finally loaded. Now it works in both Chrome and Firefox.

**Comment by plamen-peshev** [comment]
Great!
