### ISSUE TITLE
Bug or not when using 3 or more assistant tags and  children collapse is enable

### ISSUE THREAD

**Issue by rogeriocc** [BALKANGraph/OrgChartJS#102]
When I have more than 2 wizards in the organization chart and are collapsed, the organization chart is displayed below the line. Would that be normal or is it a problem? Can you remove this indicator that there are more than 2 assistants?

example in: https://jsfiddle.net/rogerioccosta/ty1xkb3p/2/

**Comment by plamen-peshev** [comment]
Addressed in version 4.7.9
