### ISSUE TITLE
Is possible assistant have children?

### ISSUE THREAD

**Issue by rogeriocc** [BALKANGraph/OrgChartJS#103]
Im try to put child inside assistant, but does not work. 
There is a limitation?

**Comment by plamen-peshev** [comment]
Adding a child inside assistant is not supported in the current version

**Comment by rogeriocc** [comment]
> Adding a child inside assistant is not supported in the current version

Do you have plans for such a feature?

**Comment by plamen-peshev** [comment]
This feature will add extra complexity to the layout algorithm
For that reason we do not have plan to add it
However, if more clients request it. we will consider it again

**Comment by ZornitsaSerbezova** [comment]
Now is is supported,
