### ISSUE TITLE
Is there a way to call zoom API programmatically?

### ISSUE THREAD

**Issue by notarnet** [BALKANGraph/OrgChartJS#104]
I need to bind zoom level to a UI range control. Is there a way to use zoom function programmatically?

**Comment by plamen-peshev** [comment]
you can use the zoom method

**Signature**
chart.zoom(delta, center, anim);

**Where:** 
- delta - True for zoom in, false for zoom out or scale number, if scale is > 1 it will zoom in and scale < 1 zoom out.
- center - Array [x, y], where x is x percantege from the width and y is y percentage from the height. (optional)
- anim - true, false (optional)

**Usage:**
chart.zoom(2, [20,20]);

**Comment by notarnet** [comment]
Has the chart a property that contains current zoom level?

**Comment by plamen-peshev** [comment]
try chart.getScale() method
