### ISSUE TITLE
Version 4.7.8: "svg" parameter of onExportStart is undefined

### ISSUE THREAD

**Issue by notarnet** [BALKANGraph/OrgChartJS#105]
In version 4.7.8 the **svg** parameter of **OnExportStart** is undefined. I need the svg DOM element to manipulate before print.

**Comment by plamen-peshev** [comment]
```
chart.on('exportstart', function(sender, args){
   var div = document.createElement('div');
   div.innerHTML = args.content;

   var svg = div.querySelector('svg');

   //your code goes here 

   args.content = div.innerHTML;
});
```

**Comment by notarnet** [comment]
After this edit, it seems that the modified content does not reach the print service. The same code worked in 4.7.4

**Comment by notarnet** [comment]
Your demo has the same problem: 
[ExportStyles](https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/ExportStyles)

**Comment by notarnet** [comment]
Sorry, the problem is only in the PDF preview: the preview does not show the modified content, but the exportPDF method yes.

**Comment by ZornitsaSerbezova** [comment]
Because style is set on exportstart:
```
chart.on('exportstart', function(sender, args){
        args.content += document.getElementById('myStyles').outerHTML;
});
```
