### ISSUE TITLE
Predefined Edit Form

### ISSUE THREAD

**Issue by ManojMistry1969** [BALKANGraph/OrgChartJS#106]
In a predefined template is there a way to disable\hide the "Add New field" link, create drop down lists and disable some some of the fields on the edit form without creating a customised form.

![orgChartEditForm](https://user-images.githubusercontent.com/51441787/59089170-5d9c2e80-8901-11e9-9da3-d21eb2fa66c9.PNG)

**Comment by plamen-peshev** [comment]
The current version does not support requested functionality

We have this feature in our to-do list and will add it in the next version

**Comment by ManojMistry1969** [comment]
Would it be possible to have the edit form styling\html\javascript as shown in the above example so that I can just customise it myself?

**Comment by plamen-peshev** [comment]
yes

**Comment by ManojMistry1969** [comment]
Ok thanks, When do you think you be able to send this to me?

**Comment by plamen-peshev** [comment]
Get the latest version

See "Change the Edit fields in the default Edit form" section from [this ](https://balkangraph.com/OrgChartJS/Docs/Edit) help article
