### ISSUE TITLE
organigram wrapper has fixed height

### ISSUE THREAD

**Issue by jensdegeyter** [BALKANGraph/OrgChartJS#107]
At the moment the organigram wrapper has a fixed height of 700px it would be better if the height equals the max height of the organigram svg on zoom 1. Didn't find anything in the api to make this adjustable or is there some hidden method to modify this? Because now in some situations there is alot of whitespace above and below the organigram.

**Comment by plamen-peshev** [comment]
you can easily control the size of the chart with **width** and **height** attributes  of the wrapper 



```
#tree {
  width: 100%;
  height: 100%;
  }

```


```
<div id="tree"></div>
```

**Comment by jensdegeyter** [comment]
Thanks for the quick response! But I think the height should depend on the max height of the visible organigram and at the moment you can't extract the height of the organigram inside the wrapper it's always centered in the middle

Attached is an example, the organigram is inserted dynamically by the client (it's not always the same organigram) now we have a fixed height of 700px for every organigram (red arrow) but I really want the height of the organigram itself (blue arrow). 

![organigram-size](https://user-images.githubusercontent.com/879796/59099524-951bd280-8923-11e9-9499-7063bd398c0d.jpg)

**Comment by plamen-peshev** [comment]
What would be the expected behavior if the chart is 70000px?

**Comment by jensdegeyter** [comment]
Well good question if the height is 70 000px and the width is only 500px then it wouldn't scale. So I get the the problem but it should be nice if there was a method or property that holds the max height of the svg organigram so we can decide how to visualize the container.

**Comment by plamen-peshev** [comment]
thank you for the suggestion

we have added this feature request in our list and if other customers are interested in this feature we will implement it
