### ISSUE TITLE
IE11: Unable to get property 'p' of undefined or null reference

### ISSUE THREAD

**Issue by wimpie3** [BALKANGraph/OrgChartJS#108]
Latest version gives an error on expanding certain nodes in IE11. Works fine in Chrome and Firefox. The error I get is:

`Unable to get property 'p' of undefined or null reference
File: OrgChart.js, Line: 1, Column: 87506`

As far as I can see my JSON is correct (and I presume it wouldn't render on Chrome either if there was a mistake in it)

**Comment by plamen-peshev** [comment]
Licensed version or Evaluation version?

**Comment by wimpie3** [comment]
The version on Github, I suppose that's the evaluation version?

**Comment by plamen-peshev** [comment]
Correct

I have tried to replicate the issue on IE to no avail

Can you please try to "Restore Advanced Settings" and try again. Tools > Internet Option > Advanced > Restore Advanced Settings

![image](https://user-images.githubusercontent.com/49443821/59271821-3f199880-8c5d-11e9-8000-4794caea1daf.png)

If the above suggestion does not help please provide a demo in jsfiddle we we can see the issue

**Comment by baertschi4** [comment]
I am having the exact same issue with IE11. The browser debugger shows that is is occurring in orgchart.js. Unfortunately, my agency uses IE11 as it's default, so I will need to find a fix before we can use the product. This is the evaluation version. In addition, I have tried adding meta tags to my HTML page to help with possible compatibility issues, to no avail. 
![ie11-js-error-1](https://user-images.githubusercontent.com/21127334/59508631-9d709200-8e7c-11e9-93dd-d03920cacc61.jpg)

![ie11-js-error](https://user-images.githubusercontent.com/21127334/59508616-95185700-8e7c-11e9-9941-523f6ae2e54e.jpg)

**Comment by baertschi4** [comment]
The error occurs when clicking an expand on certain nodes. Possibly the issue is with the onExpCollClick event

**Comment by wimpie3** [comment]
@baertschi4 were you ever able to find a solution to this problem?

**Comment by plamen-peshev** [comment]
we are not able to reproduce the issue

can you send an email to support@balkangraph.com

**Comment by ZornitsaSerbezova** [comment]
Works like a charm for me 

Tested https://balkangraph.com/OrgChartJS/Demos/Tab/BasicUsage

If still doe not work for you feel free to open the issue
