### ISSUE TITLE
Can you have solution for multiple parent node?

### ISSUE THREAD

**Issue by KiranVaghela** [BALKANGraph/OrgChartJS#109]
![download](https://user-images.githubusercontent.com/8098658/59266969-9ec87180-8c66-11e9-91e4-ec83133755a8.png)

We like the tool but be fore purchasing process have you solution of our requirement?

Thanks & Regards,

Kiran Vaghela

**Comment by plamen-peshev** [comment]
See [second parent demo](https://balkangraph.com/OrgChartJS-Demos/MultipleParents)

![image](https://user-images.githubusercontent.com/49443821/59271601-d92d1100-8c5c-11e9-929c-da8d59220242.png)


clear your browser cache before testing

**Comment by KiranVaghela** [comment]
Thank you for replying, and it is good solution but I am expecting like below,



Thanks & Regards, 
Kiran Vaghela 

    On Tuesday, 11 June, 2019, 5:53:56 pm IST, Plamen Peshev <notifications@github.com> wrote:  
 
 
See second parent demo



clear your browser cache before testing

**Comment by ZornitsaSerbezova** [comment]
Now we have Slinks:
https://balkangraph.com/OrgChartJS/Docs/Slink
