### ISSUE TITLE
Alignment of nodes with the same hierarchy

### ISSUE THREAD

**Issue by rogeriocc** [BALKANGraph/OrgChartJS#110]
Is it possible to align the nodes with the same hierarchy, according to the image?

![orgchart](https://user-images.githubusercontent.com/2631583/59290623-623d4b80-8c4f-11e9-9cbb-f6cf6d2584b1.png)

**Comment by plamen-peshev** [comment]
yes, see https://balkangraph.com/OrgChartJS-Demos/Alignment

It requites some extra configuration


![image](https://user-images.githubusercontent.com/49443821/59294414-1e1b6c80-8c8a-11e9-8ca9-9d442c8b9fb2.png)

**Comment by rogeriocc** [comment]
Thanks for the answer!

This will work, we have many nodes and the structure is very large.
We are evaluated API, we are a company of the government of the State of Minas Gerais, Brazil.
Our full orgchart will have more than 10mil nodes.

Sorry for my english!

**Comment by plamen-peshev** [comment]
I'm not sure that there is a library that support 10mil nodes

One solution would be somehow to split the chart into subcharts

**Comment by rogeriocc** [comment]
Yes, let's create sub-charts, for each government order will have a chart. The major problem is the area of health and education (4mil nodes), which includes all schools.
I am trying to negotiate a break in this structure to be more usable, otherwise it is impossible to navigate both graphically and performance.
I am waiting for the final structure because they are restructuring the entire government.

**Comment by rogeriocc** [comment]
It would be very difficult to use the tags to align the nodes,
something like it's done with "assistant" today.
For example: I would place a tag and with some specific parameter align the nodes with this tag.
Just an idea!

**Comment by ZornitsaSerbezova** [comment]
I am closing this issue, but you can open it again if you need some help or have questions.

**Comment by ZornitsaSerbezova** [comment]
Now you can aliign nodes using [subLevels](https://balkangraph.com/OrgChartJS-Demos/SubLevels).
