### ISSUE TITLE
Can't Integrate this with React Please Add support Regarding this issue

### ISSUE THREAD

**Issue by JugalT** [BALKANGraph/OrgChartJS#111]
Unable to use balkan graph with react no support is there regarding this specific issue.
unable to create object of orgchart in react please add support for this . and a proper documentation

**Comment by plamen-peshev** [comment]
The current version does not have wrapper for react, howover you can use OrgChart JS component in react application

**Comment by tomashodek** [comment]
Hi, can you please show an example how can I use OrgChart JS in react? Or at least can anyone tell me how to import OrgChartJS into react to make it usable? I installed OrgChart JS from npm, but I am unable to import it into the component, only thing I get in component from an import is a version.

**Comment by dgaszewski** [comment]
1. Add in index.html reference to script

`<script src="https://balkangraph.com/js/latest/OrgChart.js"></script>`

2.  Create React Component based on class 

3. Create nodes in Component (for example in constructor)

      `this.chart = {
        nodeBinding: {
            field_0: "name"
        },
        nodes: [
            { id: 1, name: "Amggber McKenzie" },
            { id: 2, pid: 1, name: "Ava Field" },
            { id: 3, pid: 1, name: "Peter Stevens" }
        ]
      }; `


4. Generate script tag in the document with OrgChart 

```
  componentDidUpdate() { 
        const s = document.createElement('script');
        s.type = 'text/javascript';
        s.async = true; 
        s.innerHTML = "var chart = new OrgChart(document.getElementById(\"tree\")," + JSON.stringify(this.chart) + ");";
        this.instance.appendChild(s);
      
      }
```
5. Add div in render() with matching id for OrgChart

  ```
    render() {
return <div id="tree" ref={el => (this.instance = el)} />;
}
```

**Comment by ZornitsaSerbezova** [comment]
http://localhost/OrgChartJS/Docs/React
