### ISSUE TITLE
.NET export service

### ISSUE THREAD

**Issue by julsette** [BALKANGraph/OrgChartJS#112]
Hi,
We cannot use NodeJS on our server, could a porting of the export service in .NET or .NET Core be possible?
Thanks

**Comment by webcall-me** [comment]
Why you cannot use NodeJS on your server?

**Comment by julsette** [comment]
We cannot because of server's security policies..

**Comment by ZornitsaSerbezova** [comment]
you can host export service in IIS 

See https://github.com/BALKANGraph/export-service/blob/master/IISNODE.md
