### ISSUE TITLE
CSS Customization not reflected in export

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#113]
Hi Team,

I applies css customization to my nodes.I changed color of my nodes dynamically , when i am exporting to (pdf/svg/png), the updated style is not getting reflected

Thanks
Pavan

**Comment by plamen-peshev** [comment]
You can use the following demo as  starting point https://balkangraph.com/OrgChartJS-Demos/ExportStyles

Clear your browser cache before testing it
