### ISSUE TITLE
Dotted Lines for Multiple Parent

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#114]
Hi Team,

In case of multiple parents , I would like to show the connector as a dotted line.So that it can be differentiated
Please suggest

Thanks
Pavan

**Comment by plamen-peshev** [comment]
Here is a demo: https://jsfiddle.net/87Lmd2w0/2/

![image](https://user-images.githubusercontent.com/49443821/59457151-8c923300-8e20-11e9-8e21-e7dcc5cfa28e.png)
