### ISSUE TITLE
Add/Remove Request redirected to https://au-se-balkangraph.azurewebsites.net/api/OrgChartJS

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#115]
Hi Team,

I am evaluation the trial version of balkan charts.
When i do Add/Remove actions on the Organization chat, The  Request is redirected to https://au-se-balkangraph.azurewebsites.net/api/OrgChartJS . Is this the expected behaviour of trial version ,Please suggest as this would effect the performance

Thanks
Pavan

**Comment by plamen-peshev** [comment]
Licensed version does not request https://au-se-balkangraph.azurewebsites.net/api/OrgChartJS  

And licensed version is 5 times faster compared to the evaluation version
