### ISSUE TITLE
Dotted Line when Add

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#116]
Hi Team,

Is it possible to have a dotted line for new boxes which gets generated when Add is cliked 

Thanks
Pavan

**Comment by plamen-peshev** [comment]
You can add tags on 'add' event handler and style it with css

See the following demo: https://balkangraph.com/OrgChartJS-Demos/DottedLineWhenAdd


```
chart.on('add', function(sender, data){
  data.tags = ['dotted'];
});
```

```
.dotted rect{
    stroke-dasharray: 3;
}
```

**Comment by pavandeekshitha** [comment]
Hi Plamen Peshev,

Appreciate your quick response . I need the connector line which connects the Parent to this Newly generated box as a dotted line.

Thanks
Pavan

**Comment by ZornitsaSerbezova** [comment]
You can change the link template of the newly created nodes:

To add such dotted line you need to add stroke-dasharray="10 , 6" in your dottedLine.link.
The first parameter is the black lines length, and the second parameter is the distance between lines.

OrgChart.templates.dottedLine.link = '<path  stroke-dasharray="10 , 6" stroke="black" stroke-width="10px" fill="none" link-id="[{id}][{child-id}]" d="M{xa},{ya} C{xb},{yb} {xc},{yc} {xd},{yd}">';

I'll close this issue, If you need something else, you can reopen it again or create another one.
