### ISSUE TITLE
Custom HTML not exporting

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#117]
Hi Team,

I am adding custom html like the title at the top and my company logo at the bottom,
This custom html is not getting exported.
Please suggest
License Name: OrgChart JS PREMIUM License 
Thanks
Pavan

**Comment by plamen-peshev** [comment]
Can you please share your OrgChart JS javascript code

**Comment by pavandeekshitha** [comment]
Hi Plamen Peshev

Please find the attached script code.
But could you suggest any examples where in ,I have a header(Title) and footer(Image or some disclaimers) in the Org Chart and which gets exported along with data on any Export options

Thanks
Pavan

**Comment by ZornitsaSerbezova** [comment]
Is this problem solved?

**Comment by pavandeekshitha** [comment]
Yes
