### ISSUE TITLE
Can I make Assistant and Grouping ?

### ISSUE THREAD

**Issue by krisanaalign** [BALKANGraph/OrgChartJS#118]
I try free version. Can I do as picture below? Assistant grouping.
I want to display child node (blue and yellow) with the same parent but separate level not associate.
![chartExam](https://user-images.githubusercontent.com/51896981/59577560-6d302a00-90ee-11e9-9d20-7d023b633231.png)

or something like this. Thank you.
![ChartExam2](https://user-images.githubusercontent.com/51896981/59577693-f0518000-90ee-11e9-9ff5-cb980eb54626.png)

**Comment by plamen-peshev** [comment]
You can with the latest version 4.8.6

![image](https://user-images.githubusercontent.com/49443821/59617840-bce31580-912f-11e9-9215-d7bb2314f60f.png)

https://balkangraph.com/OrgChartJS-Demos/GroupAssistantNodes

**Comment by krisanaalign** [comment]
@plamen-peshev very very thank to you for your help and support. I try it and it's work.
