### ISSUE TITLE
Probably, this is a bug

### ISSUE THREAD

**Issue by christee** [BALKANGraph/OrgChartJS#12]
Set scaleInitial: BALKANGraph.match.boundary, but not working!
Test on [https://jsfiddle.net/BALKANGraph/8p05cmf4/utm_source=website&utm_medium=embed&utm_campaign=8p05cmf4](url) 
Here is my data of nodes
[
            { "id": "01", "pid": "", "name": "01", "title": "" },
            { "id": "j001", "pid": "", "name": "ceo", "title": "asd" },
            { "id": "virtualnode!@#", "pid": "", "orgid": "", "name": "asd", "title": "" },
            { "id": "001", "pid": "j001", "name": "asd", "title": "asd" },
            { "id": "0011", "pid": "j002", "name": "asd", "title": "asd" },
            { "id": "003", "pid": "j001", "name": "asd", "title": "asd" },
            { "id": "004", "pid": "j001", "name": "asd", "title": "asd" },
            { "id": "10", "pid": "004", "name": "10", "title": "" },
            { "id": "107", "pid": "12", "name": "17", "title": "" },
            { "id": "12", "pid": "004", "name": "12", "title": "" },
            { "id": "121", "pid": "001", "name": "121", "title": "" },
            { "id": "131", "pid": "003", "name": "131", "title": "" }
        ]

**Comment by christee** [comment]
I find out where the issue is，my business-id type is string, so i can set id such as "001", "002", orgchart is not treat it as string，am i right？

**Comment by christee** [comment]
fine, i tried anthoer data has the same issue, now i am confused!
here is the data:
[
{ "id": "1", "pid": "", "name": "01", "title": "" },
{ "id": "j001", "pid": "", "name": "ceo", "title": "asd" },
{ "id": "virtualnode!@#", "pid": "", "orgid": "", "name": "asd", "title": "" },
{ "id": "1c", "pid": "j001", "name": "asd", "title": "asd" },
{ "id": "11", "pid": "j002", "name": "asd", "title": "asd" },
{ "id": "3", "pid": "j001", "name": "asd", "title": "asd" },
{ "id": "4", "pid": "j001", "name": "asd", "title": "asd" },
{ "id": "10", "pid": "4", "name": "10", "title": "" },
{ "id": "107", "pid": "12", "name": "17", "title": "" },
{ "id": "12", "pid": "4", "name": "12", "title": "" },
{ "id": "121", "pid": "1c", "name": "121", "title": "" },
{ "id": "131", "pid": "3", "name": "131", "title": "" }
]

**Comment by christee** [comment]
more data！
[
        { "id": "T600", "pid": "", "name": "aa", "title": " " },
        { "id": "T601", "pid": "T600", "name": "bb", "title": " " },
        { "id": "T603", "pid": "T600", "name": "TMcc", "title": " " },
        { "id": "T604_e8ab", "pid": "T600", "name": "sss", "title": " " },
        { "id": "T604", "pid": "T600", "name": "ddd", "title": "988" },
        { "id": "112", "pid": "T604", "name": "112", "title": " " }, 
        { "id": "113", "pid": "T604", "name": "113", "title": " " },
        { "id": "114", "pid": "T604", "name": "114", "title": " " },
        { "id": "115", "pid": "T604", "name": "115", "title": " " },
        { "id": "14", "pid": "T604", "name": "14", "title": " " },
        { "id": "15", "pid": "T604", "name": "15", "title": " " },
        { "id": "16", "pid": "T604", "name": "16", "title": " " },
        { "id": "17", "pid": "T604", "name": "17", "title": " " },
        { "id": "18", "pid": "T604", "name": "18", "title": " " },
        { "id": "19", "pid": "T604", "name": "19", "title": " " },
        { "id": "20", "pid": "T604", "name": "111", "title": " " },
        { "id": "T611", "pid": "T603", "name": "zx", "title": " " },
        { "id": "11", "pid": "T604", "name": "11", "title": " " },
        { "id": "12", "pid": "T604", "name": "12", "title": " " },
        { "id": "T612", "pid": "T603", "name": "ssss", "title": " " },
        { "id": "13", "pid": "T604", "name": "13", "title": " " },
        { "id": "212", "pid": "T612", "name": "212", "title": " " },
        { "id": "T621", "pid": "T611", "name": "1123", "title": " " },
        { "id": "T622", "pid": "T611", "name": "ccx", "title": " " },
        { "id": "T624", "pid": "T612", "name": "zz", "title": " " },
        { "id": "T623", "pid": "T624", "name": "1sd", "title": " " },
        { "id": "T631", "pid": "T622", "name": "dd", "title": " " },
        { "id": "T632", "pid": "T622", "name": "ca", "title": " " }, 
        { "id": "T625", "pid": "T623", "name": "ddd12", "title": " "}
]

**Comment by christee** [comment]
i got a picture

![issue](https://user-images.githubusercontent.com/5858347/51241799-899e2e00-19b9-11e9-837e-7d7ca0c1467f.png)

**Comment by BALKANGraph** [comment]
Thank you for reporting this issue to us 
We where able to replicate it and will be addressed in the next version

**Comment by BALKANGraph** [comment]
The issue has been addressed in version 3.8.0
