### ISSUE TITLE
How to add security on drag 

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#120]
Hi Team,

I am using Balkan graph org chart . Below are our license details
Order Number: 1208af1f2946461bb1f4ec55cc80e792
License Name: OrgChart JS PREMIUM License

We have enabled the drag and drop feature 
Our requirement is  , we need to enforce some security when a user drags, This security logic is dynamic . For Add/Edit/Remove we have respective event handlers but for drag how can i get control over the event, so based on the condition i can return true or false and a message in the drag event .Redraw event is getting fired for Add/Edit/Remove & Drag , so i cannot depend on that event. Please suggest

Thanks
Pavan

**Comment by plamen-peshev** [comment]
Download the latest version 

Use update event

```
        var chart = new OrgChart(document.getElementById("tree"), {
            enableDragDrop: true,
        });

        chart.on('update', function (sender, oldNode, newNode) {
            //your code goes here return true or false
            return false;
        });

        chart.load([
            {id:1},
            {id:2, pid:1},
            {id:3, pid:1}
        ]);
```

**Comment by pavandeekshitha** [comment]
Hi Team,

The Update method also gets called when we remove a box , So how to differentiate if the source is drag or remove.
Please suggest

Thanks
Pavan

**Comment by ZornitsaSerbezova** [comment]
Now the update event is not called on remove.
