### ISSUE TITLE
How to hide, remove or disable the form at right side

### ISSUE THREAD

**Issue by namitgarg** [BALKANGraph/OrgChartJS#122]
Hey when we click on any node , the form for same is how

 in right side, i want to disable that form, if that is not possible can anyone tell me how to hide that
<img width="1432" alt="00000139" src="https://user-images.githubusercontent.com/13060278/59676986-7997ae00-91e6-11e9-8ccb-6ef20d3c8ccd.png">

**Comment by plamen-peshev** [comment]
Set the option nodeMouseClick to OrgChart.action.none

See Node Click Behaviour section from the following  help article https://balkangraph.com/OrgChartJS/Docs/Edit

**Comment by namitgarg** [comment]
Thanks for your quick reply following the link that you provided i got the solution,
 `  var editForm = function () {
  };
  editForm.prototype.init = function (obj) {
  };
`
Then add "editUI: new editForm()" in initial configuration
