### ISSUE TITLE
Box shadows are cut when exporting

### ISSUE THREAD

**Issue by mitkosoft** [BALKANGraph/OrgChartJS#123]
Hi,

A minor issue, but when exporting a tree with box shadows around, the shadows itself are cut on the bottom and right side of the produced file, no matter PDF or image. I'm using "RONY" template currently.

Is there a way to specify/expand exported area?

**Comment by plamen-peshev** [comment]
Tried to reproduce the issue to no avail, see attached

Can you confirm that you are useng the latest version of the export service and OrgChart JS 

[OrgChart - 2019-06-18T191514.333.pdf](https://github.com/BALKANGraph/OrgChartJS/files/3302434/OrgChart.-.2019-06-18T191514.333.pdf)

**Comment by mitkosoft** [comment]
Hi Plamen,

Yes, we are using the latest version. Try to export the tree from this demo: https://jsfiddle.net/mitkosoft/zvdq3g5e/1/

And observe the shadows of right and very bottom boxes. I'm attaching also a PNG:

![OrgChart (1)](https://user-images.githubusercontent.com/16716343/59741476-c70e2c80-9273-11e9-98bc-033f200dabb5.png)

**Comment by plamen-peshev** [comment]
Thanks for the demo

The easiest solution would be to change the template

Add the line: 
`OrgChart.templates.rony.node = '<rect filter="url(#{randId})" x="0" y="0" height="240" width="170" fill="#ffffff" stroke-width="0" rx="5" ry="5"></rect>';`

See https://jsfiddle.net/shg7k3x1/

Not sure if it will work in all cases

**Comment by mitkosoft** [comment]
Hi Plamen,

Thanks for the proposal, but unfortunately this change causes the content to become not centred within the box as you just decrease the size of the box node. 

Is there an option to increase paddings/margins of the main tree container that goes to be exported?

**Comment by ZornitsaSerbezova** [comment]
These definitions are centering the content of the node:
```
OrgChart.templates.rony.img_0 = '<clipPath id="{randId}"><circle cx="85" cy="160" r="60"></circle></clipPath><image preserveAspectRatio="xMidYMid slice" clip-path="url(#{randId})" xlink:href="{val}" x="25" y="100"  width="120" height="120"></image>';
OrgChart.templates.rony.field_0 = '<text width="165" style="font-size: 18px;" fill="#039BE5" x="85" y="40" text-anchor="middle">{val}</text>';
OrgChart.templates.rony.field_1 = '<text width="165" style="font-size: 14px;" fill="#F57C00" x="85" y="60" text-anchor="middle">{val}</text>';
```

**Comment by ZornitsaSerbezova** [comment]
Hi Mitko,

We have added a property **padding**: https://jsfiddle.net/BALKANGraph/6cbo03gr/
