### ISSUE TITLE
PNG Export Issue

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#126]
Hi Team,

I have an issue with exports when the organization chart is big
PDF export is working fine but where as png is exporting partly.
Also svg exported data is right aligned.
How can we make  it be consistent with PDF.Please suggest the required configuration
PNG Export Code
===========
function png(nodeId) {
  morgChart.exportPNG({
    filename: "OrgChart.png", expandChildren: true, nodeId: nodeId
}
==============
Please suggest
[org.pdf](https://github.com/BALKANGraph/OrgChartJS/files/3321424/org.pdf)
![org](https://user-images.githubusercontent.com/38096749/60030282-537b7d80-96c0-11e9-9810-df4c6967e7b8.png)

Please find the attachment.

**Comment by plamen-peshev** [comment]
Can you please share the nodes that you are using for export to PNG

**Comment by pavandeekshitha** [comment]
Hi Plemen.

Please find the attachment

Thanks
Pavan
[respdata.txt](https://github.com/BALKANGraph/OrgChartJS/files/3330054/respdata.txt)

**Comment by pavandeekshitha** [comment]
Hi Plemen,

Any Update on this?

Thanks
Pavan

**Comment by pavandeekshitha** [comment]
Hi Plemen,

Any Update on this?

Thanks
Pavan

**Comment by dyeaple** [comment]
We have the same issue with PNG exports only including the left side of wider org charts. 

Please let us know when this is fixed.

Thank you!

**Comment by ZornitsaSerbezova** [comment]
Hi dyeaple,
We are working on this issue and will let you know when it is fixed.

Regards,
Zornitsa

**Comment by ZornitsaSerbezova** [comment]
Hi, PNG export is fixed in the latest version.
