### ISSUE TITLE
Group within a group

### ISSUE THREAD

**Issue by leng1023** [BALKANGraph/OrgChartJS#128]
Can I group nodes and grouped nodes. More likely it is group within a group.

**Comment by plamen-peshev** [comment]
Can you please be more specific, Why you want this functionality. What is your use case scenario?

**Comment by leng1023** [comment]
![TO](https://user-images.githubusercontent.com/52233186/60692588-4ef96500-9f09-11e9-8324-26870fdb42f9.JPG)

It's like this. It is been grouped by section and employees with same position needed to be in group also. Or is there is any other way to do this kind of chart?

Thank you for replying.

**Comment by ZornitsaSerbezova** [comment]
Hi, leng1023, 
Did you manage to create this chart?
