### ISSUE TITLE
browser opera and microsoft edge not support

### ISSUE THREAD

**Issue by synard1** [BALKANGraph/OrgChartJS#129]
maybe it will get better if can run on all major browser, so far i only test on chrome and firefox working good, but not at opera and microsoft edge

**Comment by plamen-peshev** [comment]
OrgChart JS does support all modern browsers, Chrome, Firefox, Opera, MS Edge, IE, Tor

Can you please test the following demo https://balkangraph.com/OrgChartJS/Demos/BasicUsage on IE or Opera and tell me if it works
