### ISSUE TITLE
How do i recreate the json after a drag and drop?

### ISSUE THREAD

**Issue by eformx** [BALKANGraph/OrgChartJS#13]

**Comment by BALKANGraph** [comment]
If you are asking how to persist how to persist the json structure on the server, you can attach to onUpdate method

Example:

    function update(sender, oldNode, newNode) {
            $.post("@Url.Action("Update")", { id: newNode.id, node: JSON.stringify(newNode) });
        }


Where:
1. oldNode is the dragged node with the old pid, before drag&drop event
2. newNode is  gragged node with the new pid, after drag&drop event

You can cancel Drag&Drop oration by returning false 

See https://github.com/BALKANGraph/OrgChart.Grouping.ASP.NETCore/blob/master/OrgChart.Grouping.ASP.NETCore/Views/Home/Index.cshtml to get started
