### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#130]
Hi Team,

We are using ula template,We would like to have an orange border for the nodes, So using below style  we could get orange border . But the top side border is still in blue colour , how can we change this to orange.Please find the attachment on what we did,Please do the needful.
![ula](https://user-images.githubusercontent.com/38096749/60268464-1c001180-990a-11e9-85d3-0b0bdcf82b3a.png)

[node-id] rect {
      stroke: orange;
    }

**Comment by plamen-peshev** [comment]
[node-id] rect, [node-id] line {
stroke: orange;
}

**Comment by pavandeekshitha** [comment]
Thanks ,It worked

**Comment by v1sp** [comment]
Hi,
We are using ana template to show the hierarchy.
How do I change the colour of the nodes like - 
All Level 1 Items - Colour A
All Level 2 Items - Colour B
All Level 3 Items - Colour C

Something like 
![image](https://user-images.githubusercontent.com/8832982/60661387-b9e76500-9e51-11e9-8e89-968b67490267.png)

Thanks,
Veerendra.

**Comment by plamen-peshev** [comment]
https://jsfiddle.net/BALKANGraph/gfz4rhmt/

```
[level="1"] rect{
  fill: #F57C00 !important;
}

[level="2"] rect{
  fill: #FFCA28 !important;
}
```

![image](https://user-images.githubusercontent.com/49443821/60661905-b9f06080-9e63-11e9-82ad-be764e180155.png)

**Comment by v1sp** [comment]
@plamen-peshev Thank You .. :)

**Comment by v1sp** [comment]
Hi, 
How do we customize the nodeMenu options instead of default one. (CSS) something to look like 
![image](https://user-images.githubusercontent.com/8832982/60716406-37c17400-9f17-11e9-8192-9013f7b61739.png)

Can we use font-awesome icons?

Also, How do we get different nodeMenu items at different Levels.
Eg. The nodeMenus for Level-1 (Manager) 
       1. Add Emp
       2. Edit Emp Details
      The nodeMenus for Level-2 (Emp) 
       1. Edit Emp Details
       2. Update Status.

Thanks,
Veerendra.

**Comment by plamen-peshev** [comment]
https://balkangraph.com/OrgChartJS-Demos/ConditionalNodeMenuItems


```
      var chart = new OrgChart(document.getElementById("tree"), {       
        nodeBinding: {
          field_0: "id",
          field_1: "pid"
        },      
        nodeMenu: {},
        tags:{
            "node menu level 1":{
              	nodeMenu:{
                	add: { text: "Add Emp", icon: '<i class="fas fa-user-plus"></i>' },
                	set_target: { text: "Set Target for Emp", icon: '<i class="fas fa-dot-circle"></i>', onClick: function(){ alert('set target') } }
              	}
            },
            "node menu level 2":{
              	nodeMenu:{
                    edit: { text: "Edit Emp Details", icon: '<i class="fas fa-user-edit"></i>' },
                	update_target_status: { text: "Edit Emp Details", icon: '<i class="fas fa-bullseye"></i>', onClick: function(){ alert('update target') }  }                    
              	}
            }
        }
    });

      chart.load([
        { id: 1, tags: ["node menu level 1"] },
        { id: 2, pid: 1, tags: ["node menu level 2"]  },
        { id: 4, pid: 1, tags: ["node menu level 2"]  }]);
```

![image](https://user-images.githubusercontent.com/49443821/60721581-153f5300-9f37-11e9-9f53-402018496c8c.png)

**Comment by v1sp** [comment]
@plamen-peshev  - That works perfect. Much appreciated.

Thanks,
Veerendra.
