### ISSUE TITLE
Add Parent Node Dynamically

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#131]
Hi Team,

We have a scenario where in the parent node needs to be added dynamically to the chart which should further establish the relation ship with it children.I have tried using chart.addnode option but this node is added but it it not establishing the relationship with its children.
I know we can use chart.load method but it would refresh the entire chart and we would loose the state of the chart(Collapse,Expand,Add new Node etc),Please suggest
=======Initial Nodes
 var nodes = [{ id: 1, pid: 10, name: "Denny Curtis", title: "CEOs sadsdsdsds asdsdsdfs", businessGroup: "GIL", img: "https://balkangraph.com/js/img/2.jpg", freetext: false },
      { id: 2, pid: 1, name: "Ashley Barnett", title: "Sales Manager", businessGroup: "GIL", img: "https://balkangraph.com/js/img/3.jpg", freetext: false },
 =====================
=========new parent node
var par = { id: 10, pid:null, name: "Pavan", title: "CEOs sadsdsdsds asdsdsdfs", businessGroup: "GIL", img: "https://balkangraph.com/js/img/2.jpg", freetext: false };
=================
Thanks
Pavan

**Comment by plamen-peshev** [comment]
Here is a demo https://codepen.io/plamen-peshev/pen/ydpajX

**Comment by pavandeekshitha** [comment]
Hi Plamen,

The use case is a bit different.
In your example assume that for Denny Curtis the pid=4 . Pid-4 is not yet present in the chart.
Now when u click on AddNode and  add “Elliot Patel” whose id is 4 then the relationship should be established between the child (Denny Curtis) and Parent(Elliot Patel).



Thanks
Pavan

**Comment by pavandeekshitha** [comment]
Hi Plemen,

It is working .



Thanks
Pavan

From: Pavan Kumar Gautaraju
Sent: Friday, June 28, 2019 5:44 PM
To: 'BALKANGraph/OrgChartJS'; BALKANGraph/OrgChartJS
Cc: Author
Subject: RE: [BALKANGraph/OrgChartJS] Add Parent Node Dynamically (#131)

Hi Plamen,

The use case is a bit different.
In your example assume that for Denny Curtis the pid=4 . Pid-4 is not yet present in the chart.
Now when u click on AddNode and  add “Elliot Patel” whose id is 4 then the relationship should be established between the child (Denny Curtis) and Parent(Elliot Patel).



Thanks
Pavan
