### ISSUE TITLE
Custom edit form issues

### ISSUE THREAD

**Issue by callmejamie** [BALKANGraph/OrgChartJS#132]
Hi,

I've been trying to implement a custom edit form for my OrgChart but I've been running into some issues. 

If I follow the example given in the documentation and code to instantiate the editForm and the OrgChart object in the same script block, it all works fine. https://balkangraph.com/OrgChartJS/Docs/Edit

But because my application is larger, I had extracted the code to instantiate the editForm into a separate file so it could be reused. And so it's been structured like this.. https://gist.github.com/callmejamie/7af645f7a9db7795781f2f38a2f3ba97

Problem is, when I save the values in the form, the node doesn't update with the new values. I've checked that the `window.chart` object is working and calling the function fires correctly. In fact, after the update, I see the node trigger a "ripple" effect, which means the ripple code is being called. But somehow the node values are just not updating. 

Any help would be appreciated.

**Comment by plamen-peshev** [comment]
you can attach to the "redraw" method to see how many times is called and when

**Comment by callmejamie** [comment]
Sorry.. can you be more specific? Not sure what I'm attaching to the "redraw" method

**Comment by plamen-peshev** [comment]
I have tried to replicate the issue to no avail

If you provide a demo in codepen or jsfiddle we will be able to help

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue, If it is not resolved and you still need help, please feel free to reopen it.

**Comment by E1340870** [comment]
Hi everyone, how did you fix this issue? is it fixed? or not? I have this kind of issue.

**Comment by ZornitsaPesheva** [comment]
[oc.zip](https://github.com/BALKANGraph/OrgChartJS/files/10895910/oc.zip)

**Comment by E1340870** [comment]
thanks @ZornitsaPesheva.
