### ISSUE TITLE
align chart to center

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#133]
Hi Team,

How can i align chart to center. The chart is not fixed ,it is moving based on the data.
I tried using align: BALKANGraph.ORIENTATION, but it is not working
Please suggest

Thanks
Pavan

**Comment by plamen-peshev** [comment]
You want to be centered and all nodes visible?

**Comment by pavandeekshitha** [comment]
Yes

**Comment by pavandeekshitha** [comment]
Chart needs to be centered but for nodes they will scroll

From: Pavan Kumar Gautaraju
Sent: Friday, June 28, 2019 9:03 PM
To: 'BALKANGraph/OrgChartJS'; BALKANGraph/OrgChartJS
Cc: Author
Subject: RE: [BALKANGraph/OrgChartJS] align chart to center (#133)

Yes

**Comment by plamen-peshev** [comment]
So you want particular node to be centered?

**Comment by pavandeekshitha** [comment]
The Starting Node needs to be centered

**Comment by pavandeekshitha** [comment]
I mean the root node

From: Pavan Kumar Gautaraju
Sent: Friday, June 28, 2019 9:30 PM
To: 'BALKANGraph/OrgChartJS'; BALKANGraph/OrgChartJS
Cc: Author
Subject: RE: [BALKANGraph/OrgChartJS] align chart to center (#133)

The Starting Node needs to be centered

**Comment by plamen-peshev** [comment]
In [this](https://codepen.io/plamen-peshev/pen/MMrVBY) demo the root is horizontally centered, do you need to be centered vertically as well?

**Comment by pavandeekshitha** [comment]
Hi Plemen,

Please find the attachment. If you notice the chart is aligned to the right and it is not visible, until we drag it to the left.
I would like to align the chart to the center of the screen.I did not take the latest version.
I am not sure if I take latest version will solve ,but this is the issue

Thanks
Pavan
