### ISSUE TITLE
override editUI

### ISSUE THREAD

**Issue by shaden187** [BALKANGraph/OrgChartJS#134]
can i override editUI, the same as i override the Menu for each template tag ??

**Comment by plamen-peshev** [comment]
yes you can


```
    var editForm = function () {
        ...
    };

    editForm.prototype.init = function (obj) {
        ...
    };

    editForm.prototype.show = function (node) {
        ...
    };

    editForm.prototype.hide = function (showldUpdateTheNode) {
        ...
    };
```
    

```
  var chart = new OrgChart(document.getElementById("tree"), {
            editUI: new editForm(),
            ...
    });
```

you can see Custom Edit Form section [this](https://balkangraph.com/OrgChartJS/Docs/Edit) help article

**Comment by shaden187** [comment]
thanks for your reply, 
i have tested this feature earlier and it worked great, but what i mean is how i can use more than one custom edit form in the same chart, and assign each for different template tags.

**Comment by plamen-peshev** [comment]
you can do something like:

```
    editForm.prototype.show = function (node) {
        if ([node has specific tag])
              show specific edit form
    };

```

**Comment by shaden187** [comment]
i think i didn't get it...
showing another custom edit form (with different binding fields and style) according to a condition inside the "show" function of the original custom editForm ??
can you please explain it more in details

**Comment by plamen-peshev** [comment]
Here is a demo https://codepen.io/plamen-peshev/pen/YoexeJ

**Comment by shaden187** [comment]
Thanks for your help
That is all what i need
