### ISSUE TITLE
Trace an employee's management chain

### ISSUE THREAD

**Issue by liraymond** [BALKANGraph/OrgChartJS#135]
Is there a way to highlight the an searched employee's management chain up to the top node?

**Comment by mporcaro** [comment]
Just to clarify, the functionality we wish to see is when a profile has been clicked on, we'd like to know if the "lines" that connect through to the top node could be highlighted?  This would let us know at a glance how this employee is connected at a glance.

We will provide you with a screenshot of what me mean.

Thanks!

**Comment by mporcaro** [comment]
![Untitled](https://user-images.githubusercontent.com/34243331/60469142-b1144a80-9c29-11e9-852b-436d8a985b0a.png)

Please see the attached image as an example of what we are talking about.  When you click on a profile, tracing the path would be desired.  Then when the profile info is closed, the tracing of the path would be removed.  What would be even cooler is if the rest of the graph was dimmed, while the path that we wish to highlight would remain undimmed.

Thanks for your consideration!

**Comment by plamen-peshev** [comment]
Thanks for the detailed explanation and for the screenshot

Download version 4.8.8

https://balkangraph.com/OrgChartJS-Demos/Highlight

![image](https://user-images.githubusercontent.com/49443821/60507452-e162f400-9cd0-11e9-9f9f-02e361b602f7.png)

**Comment by mporcaro** [comment]
This solution is brilliant.  Can the production script be updated as well?

**Comment by plamen-peshev** [comment]
Yes you can download the latest orgchart.js from your [account ](https://balkangraph.com/console/Login?returnUrl=%2Fconsole%2F)you can download the latest orgchart.js from your account and replace it on your server)and replace it on your server

**Comment by mporcaro** [comment]
That worked, thanks so much!
