### ISSUE TITLE
Assistant tag changing the layout

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#138]
Hi Team,

This is regarding the org chart layout.
I am using BALKANGraph.treeRightOffset.
When i do not use Assistant tag the chart is rendered as mentioned in the documentation.
But when i use assistant tag the layout is changed to BALKANGraph.Normal,that is all the child nodes are rendered horizontally.
Please find attached screen shots.
Please suggest

Thanks
Pavan
![with_assistant](https://user-images.githubusercontent.com/38096749/60671755-6563da00-9e91-11e9-85b7-236929ec775c.png)
![without_assistant](https://user-images.githubusercontent.com/38096749/60671834-a0fea400-9e91-11e9-92b8-b1646b3bfbd4.png)

**Comment by plamen-peshev** [comment]
We where able to reproduce this issue 

Will be addressed in the next version

https://jsfiddle.net/BALKANGraph/14jg9mLc/6/

**Comment by pavandeekshitha** [comment]
Thanks Plemen, When can we expect the next release

**Comment by plamen-peshev** [comment]
In the middle of next week

**Comment by plamen-peshev** [comment]
The issue has been addressed in the latest release

Give it a try and tell me if it works
