### ISSUE TITLE
Group with multiple parent

### ISSUE THREAD

**Issue by leng1023** [BALKANGraph/OrgChartJS#139]
Can this be done? A group with a multiple parent?

**Comment by plamen-peshev** [comment]
Groups inside groups is not supported in the current version, but I'd appreciate if you provide a screenshot that illustrates required layout to have this feature in our to do list for next versions

**Comment by leng1023** [comment]
![group with multiple parents](https://user-images.githubusercontent.com/52233186/60700187-7d873800-9f29-11e9-850a-79e03fb5dca0.JPG)
It's like this. A group that is also reporting to officers in a group. Like the illustration I attached.

**Comment by dyeaple** [comment]
This feature would also be very helpful for us, in addition to allowing a user to be a member of multiple groups (https://github.com/BALKANGraph/OrgChartJS/issues/50). Can you let us know when these features are planned in your roadmap?

**Comment by ZornitsaSerbezova** [comment]
you can use [slink](https://balkangraph.com/OrgChartJS/Docs/Slink) or [clink ](https://balkangraph.com/OrgChartJS/Docs/Clink)
