### ISSUE TITLE
Fields Limitation

### ISSUE THREAD

**Issue by leng1023** [BALKANGraph/OrgChartJS#140]
Hi! How many fields can I create? Can I create more than 20?

**Comment by plamen-peshev** [comment]
There is no limitations on in the fields, you can create millions

**Comment by leng1023** [comment]
Thank you for replying. May I also ask what is the difference between the purchased plugin to the free one?

**Comment by plamen-peshev** [comment]
They are almost the same, the only diff is that the free one will stop working if you are using it on production
