### ISSUE TITLE
view chart xml data without using the export event

### ISSUE THREAD

**Issue by shaden187** [BALKANGraph/OrgChartJS#141]
Hello,
i want to know how i can get the chart xml data without using the export event, and also how to load xml data to a given chart without using the import event.
Thanks

**Comment by plamen-peshev** [comment]
you can use

`chart.exportXML(filename);
`
and
`chart.exportXML("MyOrgChart.svg");`

See [this ](https://balkangraph.com/OrgChartJS-Demos/CheckBoxInMenu)demo

And [API Reference ](https://balkangraph.com/OrgChartJS/Docs/APIReference)

**Comment by shaden187** [comment]
i checked the demo, but i don't want to save the data in a local file, i need to get this data as xml string and save it in my database.

**Comment by shaden187** [comment]
hello,
seems there is no other way to get the xml data without using exportXML method ??

**Comment by plamen-peshev** [comment]
the latest version has getXML and loadXML methods, see [APIReference](https://balkangraph.com/OrgChartJS/Docs/APIReference#loadXML)

**Comment by shaden187** [comment]
great, thanks
if i want to get the data from url and i have the option to get it as svg data, can i use a similar method for the type svg ??

**Comment by plamen-peshev** [comment]
yes, you can

if you are using jquery, something like:

```
       $.get("your url", function (xml) {
            chart.loadXML(xml);
        });
```

**Comment by shaden187** [comment]
will this work if the data in url is svg instead of xml ?? because nothing in the APIReference shows that i can load or import svg data, although the exportSVG is being used.
i used (import/load xml) for loading svg data but it didnt work.

**Comment by plamen-peshev** [comment]
It will not work

**Comment by shaden187** [comment]
you mean that there is no such method as chart.importSVG() ??

**Comment by shaden187** [comment]
any update on how i can use a method to (import or get) SVG data ??
