### ISSUE TITLE
balkan org chart in angular

### ISSUE THREAD

**Issue by aqibch69** [BALKANGraph/OrgChartJS#142]
How can I use this balkangraph org chart to my Angular 8 application?

**Comment by plamen-peshev** [comment]
There are customers that are using OrgChart JS in angular app but we do not have official support for it. The good news is that we have it in our todo list

**Comment by aqibch69** [comment]
Can you please send any sample of angular project as you said your customers are using it ? 
 
Thankyou !

**Comment by jfarooq22** [comment]
I have a sample if you want i can give it to you.

**Comment by wros** [comment]
Hi @aqibch69 

in my case i use NPM and angular 8.1.3.

follow these steps.

1. Import OrgChart from NPM.

2. Add OrgChart.js to scripts section of angular.json:
```
            "scripts": [
              {
                "bundleName": "orgchart",
                "inject": true,
                "input": "./node_modules/@balkangraph/orgchart.js/orgchart.js",
                "lazy": false
              }
            ]
```

3. Include OrgChart type in typings.d.ts:
```declare var OrgChart: any;``` 

4. Create a componente and include a variable for OrgChart
```
export class OrgChartComponent implements OnInit, OnDestroy {
  private OrgChartUi: any;
```
5. In this component initialize OrgChart (_OrgChartContainer_ is a div in the template)

```
ngOnInit() {
  this.OrgChartUi = new OrgChart(document.getElementById('OrgChartContainer'), {...);
}
```

6. If you want to delegate events using the angular context
```
...
onDbClick: (sender, node) => this.onEditNode.apply(this, [sender, node, 'edit']),
...

onNodeReparent(sender, oldNode: OrganizationTree, newNode: OrganizationTree): boolean {
    ...
    return true;
}
```

for me its works

**Comment by ZornitsaSerbezova** [comment]
https://balkangraph.com/OrgChartJS/Docs/Angular

**Comment by ikishanoza** [comment]
any news on node as angular component ?
