### ISSUE TITLE
add (add organization and add emloyee)

### ISSUE THREAD

**Issue by Sadoo-MH** [BALKANGraph/OrgChartJS#143]
Hi,
we are very interested on purchasing orgchart, so i need to demo to my management team, i have done some modification to the template and now am stuck on writing a procedure to do this;
we have the add node menu to add a new node i would like to have seprete adds one to add an organization which has it's own template and tag on my script and one to add the employees which also has it's own template and tagging and am stuck on how to do it so could you please guide me ? and after the add i will try to create the edit form seprate ones between the employees and the organization, 
so basicaly i need 2 add buttons each one when creating will tag the node differently, 
and also another question: is there a way after clicking add that the edit forum will open straight after the add to add the information for this newly created node?
if you need my script i would be happy to share it :)

Many thanks
All the best!

**Comment by plamen-peshev** [comment]
Use https://jsfiddle.net/BALKANGraph/Lr6msd04/ as starting point 

#134 - here you can find how to open diff edit forms for employees and the organization

```
    var addedNodeIdWithTag2 = null;
    var chart = new OrgChart(document.getElementById("tree"), {       
        nodeBinding: {
          field_0: "id",
          field_1: "name"
        },      
        nodeMenu: {
            addWithTag1: { text: "Add New Tag 1 Node", icon: OrgChart.icon.add(24, 24, '#ccc'), onClick: function(nodeId){
              chart.addNode({id: guid(), pid: nodeId, tags: 'tag 1'});
            } },            
            addWithTag2: { text: "Add New Tag 2 Node And Open Edit Form", icon: OrgChart.icon.add(24, 24, '#ccc'), onClick: function(nodeId){            
    					addedNodeIdWithTag2 =  guid();
              chart.addNode({id: addedNodeIdWithTag2, pid: nodeId, tags: 'tag 2'});              
            }  }
        },
        tags:{
            "tag 1":{
              	template: 'ula'
            },
            
            "tag 2":{
              	template: 'ana'
            }
        }
    });  
   
    chart.on('redraw', function(sender){
      if (addedNodeIdWithTag2 != null){
        sender.editUI.show(addedNodeIdWithTag2);
        addedNodeIdWithTag2 = null;
      }
    });
    chart.load([
        { id: 0, tags: ["tag 1"], name: 'name 0' },
        { id: 1, pid: 0, name: 'name 1'  },
        { id: 2, pid: 0, name: 'name 2'  }]);
```

**Comment by Sadoo-MH** [comment]
Hi,
thank you for your responce, but it seems like that when adding the template for the tag is not applied at all, even in your demo when adding on both cases the template is remained the same, am i missing something ? 

many thanks

**Comment by plamen-peshev** [comment]
Added square brackets and now works

https://jsfiddle.net/BALKANGraph/Lr6msd04/

**Comment by Sadoo-MH** [comment]
worked perfectly,
now it's time to try out the edit forms and how to set a password on edit mode :)

many thanks
you are the best!

**Comment by Sadoo-MH** [comment]
Hi,
i have tried to do the edit form with no success, i tried many times   no luck :( wil you be able to help me if i shared my code with you ?
many thanks

**Comment by plamen-peshev** [comment]
Sure, you can create an working demo in js fiddle and explain what is not working

**Comment by Sadoo-MH** [comment]
Hi,
am having a problem creating the demo on Js fiddle can i send it via email ?
you will see there is alot of errors on my code and some procedures are not working like converting position to employee and like the edit form and so on, all of these are still under investigation to see how can i fix them, so could you please just tell me where is the error on my edit forms, am not that expierience on JS had some expierience before and still working on my knowledge level on JS,

many thanks

**Comment by plamen-peshev** [comment]
you can send the demo to support@balkangraph.com

**Comment by Sadoo-MH** [comment]
sent it now many thanks :)

**Comment by Sadoo-MH** [comment]
Hi
Have you seen my demo and found where is my error? 
Many thanks

**Comment by ZornitsaSerbezova** [comment]
Hi, Sadoo-MH,
I hope you have managed to solve your problem, so I will close this issue. Feel free to open it again if needed,
