### ISSUE TITLE
Vue.js implementation

### ISSUE THREAD

**Issue by ha6755ad** [BALKANGraph/OrgChartJS#144]
Hi, I think I should be able to implement this in my vuejs project, however I am getting a "cannot  read property "style" of null" error message in my console when I try to implement the basic starter example. It seems my index.html file is finding the orgchart.js file fine, but the error ref is on orgchart.js line 1. I am hoping there is a brief, even "unofficial" example of how to implement this in a vue.js project.

**Comment by plamen-peshev** [comment]
It looks like that the ORgChart JS cannot find the html element

Make sure that the HTML element is presented in the DOM before initializing the chart

**Comment by ha6755ad** [comment]
Yes. For the benefit of anyone else using Vue, I used a mounted function to fix that. Here is what I did to fix that. 

1. Script tag in the index.html file for my Vue project 
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons' rel="stylesheet">
    <link rel="icon" href="<%= BASE_URL %>favicon.ico">
    <title>company_tribes</title>
    <link rel="stylesheet" href="css/main.css">
    <script src="orgchart.js"></script>
  </head>
  <body>
    <noscript>
      <strong>We're sorry but company_tribes doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    
  </body>
</html>`

2. orgchart.js in the same root folder as index.html (in my case "public")
3. I created a component called "Chart.vue" and here is what's in it
`<template>
  <div>
    <div style="width:100%; height:700px;" id="orgchart"/>
  </div>  
</template>

<script>
    export default{
        mounted(){
             chart: new OrgChart(document.getElementById("orgchart"), {
            nodeBinding: {
                field_0: "name"
            },
            nodes: [
                { id: 1, name: "Amber McKenzie" },
                { id: 2, pid: 1, name: "Ava Field" },
                { id: 3, pid: 1, name: "Peter Stevens" }
            ]
        })}}
    </script>`

**Comment by ha6755ad** [comment]
FBO any Vue users I'll keep posting meaningful progress here. I had to change my layout a little bit so I could access my database API for the data. The mounted function will not give you access to reactive node data. I moved it into a computed property and then called it with mounted. 

```
<script>
import { mapState } from 'vuex'
    export default{
        mounted(){ return {
            getChart
        }
             },
        created() {
        this.$store.dispatch('loadPeople'),
            this.$store.dispatch('loadGroups')
    },
        
        computed: {
            ...mapState(['people']),

        getChart(){
            return{
            chart: new OrgChart(document.getElementById("orgchart"), {
            nodeBinding: {
                field_0: "name"
            },
            nodes: this.people
        })}
        } 
        }
    }
    </script>
```

**Comment by ha6755ad** [comment]
Still working through all of this. There are some interesting quirks to how vue loads the elements in the DOM with this application, however I have made it work. Since I am actively making changes, I will not be posting them all until more problems are worked through, however if you'd like to discuss any projects in the meantime I'm glad to share.

**Comment by webcall-me** [comment]
do you have any progress on this?

**Comment by DanielJomphe** [comment]
Did your Vue.js implementation stabilize, were you able to easily hook into OrgChartJS's apis and event handlers?

**Comment by vimalvraj** [comment]
> Still working through all of this. There are some interesting quirks to how vue loads the elements in the DOM with this application, however I have made it work. Since I am actively making changes, I will not be posting them all until more problems are worked through, however if you'd like to discuss any projects in the meantime I'm glad to share.

Hey, any update on this?

**Comment by ZornitsaSerbezova** [comment]
Hi all,
We have implemented it: https://balkangraph.com/OrgChartJS/Docs/Vuejs
