### ISSUE TITLE
PDF Preview - Landscape view not scaling properly

### ISSUE THREAD

**Issue by Mrcl1450** [BALKANGraph/OrgChartJS#148]
![image](https://user-images.githubusercontent.com/8568899/61133779-05cf8500-a4b6-11e9-9dae-c53e201807b1.png)

It doesn't look like the correct behavior since the portrait view looks like scaling properly.

![image](https://user-images.githubusercontent.com/8568899/61134051-af167b00-a4b6-11e9-9257-7cbb827a91d5.png)

**Comment by plamen-peshev** [comment]
you can change the scale property to 100%

**Comment by Mrcl1450** [comment]
It makes it worse
![image](https://user-images.githubusercontent.com/8568899/61134307-4380dd80-a4b7-11e9-9f02-6a0339e0fda8.png)

**Comment by plamen-peshev** [comment]
What would be the expected layout?

**Comment by Mrcl1450** [comment]
The full chart in 1 page.

**Comment by plamen-peshev** [comment]
In Portrait or Landscape?

**Comment by Mrcl1450** [comment]
Landscape, portrait looks good.

**Comment by plamen-peshev** [comment]
We will ad 'fit to page' option in the next version, now it has fit to page width

**Comment by Mrcl1450** [comment]
Alright. Thank you

**Comment by Mrcl1450** [comment]
It's done?

**Comment by ZornitsaSerbezova** [comment]
No, sorry. :D

**Comment by Mrcl1450** [comment]
Any update on this? 
Thank you.

**Comment by ZornitsaSerbezova** [comment]
Now you can select different scale values to fit to one page:
![image](https://user-images.githubusercontent.com/19305472/86604402-00fcbe80-bfae-11ea-93fd-e163bbd8afcf.png)

**Comment by Mrcl1450** [comment]
Awesome, Thank you.
