### ISSUE TITLE
Windows 10 Touchscreen - No pinch zoom, no xy scroll

### ISSUE THREAD

**Issue by Faisal808** [BALKANGraph/OrgChartJS#149]
Hi,  
I am testing BALKANGraph on windows 10 PC with touch screen, testing was done on Chrome, IE11, Edge and Firefox.

I noticed that pinch to zoom, x-axis scroll and y-axis scroll are not working on touch mode on windows 10.  Is there a way to enable these features? 

We would like your support on this as I am planning to purchase a license, but this is deal breaker for me.

**Comment by plamen-peshev** [comment]
Touch events are working on mobile devices only, if this is a show stopper for you we can add new option called, enableTouchEvents that will force the touch events to work with priority but the other events will not work like mouse scroll

**Comment by Faisal808** [comment]
Thanks plamen for your reply,

I think that could work. Most of the interaction will be done on a touch screen.

Could you please let us know when can we utilize this feature.

**Comment by plamen-peshev** [comment]
now you can use enableTouch: true option in the latest version 4.9.6
