### ISSUE TITLE
set focus to a node

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#154]
Hi Plemen,

Is there a way to set focus to a particular node.
We have a requirement where in we need to clone an existing node ,but when the cloned node is expanded, we will expand the parent node and set focus.
Thanks
Pavan

**Comment by plamen-peshev** [comment]
Here is a demo how to set focus style: https://balkangraph.com/OrgChartJS-Demos/Focus

you can use as starting point to implement your own focus logic

![image](https://user-images.githubusercontent.com/49443821/61450041-e2498600-a95e-11e9-84d2-924f7c5e5a3c.png)

**Comment by pavandeekshitha** [comment]
Thanks
In my case I have a big org chart and  when we add a new node it is adding at the end of the row and is not visible unless I scroll,How can I move the scroll postion automatically or set focus to the newly added node?

Thanks
Pavan

**Comment by mitkosoft** [comment]
@plamen-peshev , is there an option this focus to be on mouseover event, but not on click? I tried with mouseover but doesn't work.

**Comment by ZornitsaSerbezova** [comment]
https://balkangraph.com/OrgChartJS-Demos/CenterOnAdd
