### ISSUE TITLE
when doing search often app freeze

### ISSUE THREAD

**Issue by kksanghi** [BALKANGraph/OrgChartJS#155]
We are loading approx 500 records, when we do search and nodes are not expanded then search functionality is not behaving properly, most of the times it's freezing, not sure why it's happening.

We have rendered two independent cards set 
1. With No Parent
2. With Parent

![image](https://user-images.githubusercontent.com/16228568/61400120-31ef6980-a8ed-11e9-9664-31cd91b06a25.png)

**Comment by plamen-peshev** [comment]
I have tried to reproduce the issue to no avail

Can you please provide a demo where the problem can be observed

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue. If you still have this problem, you can reopen it.
