### ISSUE TITLE
search fields apply dynamically

### ISSUE THREAD

**Issue by kksanghi** [BALKANGraph/OrgChartJS#156]
when we plot chart based on the configuration we need to specify what are the fields we need before hand to search, if not provided it will search based on data set provided.

My requirement is to feed search fields after chart is initialized, which means at run time i should be able to switch the search fields. How we can do this.

**Comment by plamen-peshev** [comment]
`chart.config.searchFields = ['f1', 'f3', etc]`

use the code above

**Comment by kksanghi** [comment]
Thank you it's working
