### ISSUE TITLE
Layout TreeRightOffSet

### ISSUE THREAD

**Issue by Carbo20** [BALKANGraph/OrgChartJS#162]
Hello,

I'm currently triying to test all the possibility your solution offer and i saw Layout like treeRightOffSet works only for the last nodes level. Is there a way to build a vertical graph with more nodes level than the last one ? All level could be vertical for example ?

**Comment by plamen-peshev** [comment]
Can you please try to draw the requested layout and post it here

**Comment by Carbo20** [comment]
![image](https://user-images.githubusercontent.com/11231488/62272950-9a396180-b43c-11e9-914b-7fe78d816b3c.png)

Like this ;)

**Comment by ZornitsaSerbezova** [comment]
you can try with assistant node

**Comment by xibriz** [comment]
I'm also interested in this. The assistant node is not a sustainable solution in my testing.

**Comment by plamen-peshev** [comment]
Try orientation: OrgChart.orientation.left_top

Here is a demo https://jsfiddle.net/BALKANGraph/k5v3srn4/

**Comment by xibriz** [comment]
@plamen-peshev it did not work.

What I have:
![image](https://user-images.githubusercontent.com/6031195/84076884-d3d0e680-a9d6-11ea-8d92-103f701ddf6b.png)

What I want:
![image](https://user-images.githubusercontent.com/6031195/84076982-fc58e080-a9d6-11ea-941c-e0ea11dfc9a3.png)

**Comment by plamen-peshev** [comment]
did you set **orientation: OrgChart.orientation.left_top**?

```
var chart = new OrgChart(document.getElementById("tree"), {    
     **orientation: OrgChart.orientation.left_top**,
     ...
}
```

**Comment by xibriz** [comment]
@plamen-peshev  I tried that, but it did not produce the requested result.

![image](https://user-images.githubusercontent.com/6031195/84121022-e5e27180-aa36-11ea-97e2-e90d40f93a6d.png)

**Comment by plamen-peshev** [comment]
The tree like layout is not supported

We have added this request in our feature consideration list
