### ISSUE TITLE
change root node

### ISSUE THREAD

**Issue by hunter1881** [BALKANGraph/OrgChartJS#163]
Hi is there a possibility to change the tree root node, I mean can I add a new node to an existing tree  and make that new node as a root?

I have tried using the add and update but does not works because an error appear 

                orgChart.add(newRootNode);
                orgChart.update(CurrentrootElement);
                orgChart.draw();

also I have tried using link() method instead of update() but did not work.

**Comment by plamen-peshev** [comment]
https://jsfiddle.net/BALKANGraph/koh1qr05/


```
var chart = new OrgChart(document.getElementById("tree"), {
            nodeBinding: {
                field_0: "id",
                field_1: "pid"
            }
        });    
        
        chart.load([
                { id: 1},
                { id: 2, pid: 1 },
                { id: 3, pid: 1 },
                { id: 4, pid: 1 }
            ]);
        
        document.querySelector('button').addEventListener('click', function(){
        	chart.add({id: 5});
        	chart.draw(OrgChart.action.update, null, function(){    
        		chart.link(2, 5);
          	chart.draw();
        	});               
        });
```
