### ISSUE TITLE
Setting width of groupname

### ISSUE THREAD

**Issue by leng1023** [BALKANGraph/OrgChartJS#164]
How can I resize the width of groupname, I want it to be 2 lines only. Also is there a way to arrange nodes the inside to group? Ex. color green node would be under the white one just to show hierarchy. Thank you so much. ![issue](https://user-images.githubusercontent.com/52233186/61763650-b0c23600-ae08-11e9-86d9-6d007ce18786.JPG)

**Comment by plamen-peshev** [comment]
You can have to change the group template 

See here https://jsfiddle.net/BALKANGraph/9dwmoszt/

**Comment by leng1023** [comment]
Thank you.
