### ISSUE TITLE
DOM object constructor cannot be called as a function. 

### ISSUE THREAD

**Issue by ZHwin** [BALKANGraph/OrgChartJS#166]
![1563950595(1)](https://user-images.githubusercontent.com/29451598/61771354-3dc5b900-ae22-11e9-851f-54e115d418c6.png)
Low version chorme can not work ，The above is the error message，but high version chorme is good

**Comment by plamen-peshev** [comment]
What is the Chrome version you are testing in ?

**Comment by ZHwin** [comment]
> 您测试的 Chrome 版本是什么？

chorme 30

**Comment by ZHwin** [comment]
> What is the Chrome version you are testing in ?

Chrome 30
