### ISSUE TITLE
Exporting large charts based on current user's view

### ISSUE THREAD

**Issue by shaipetel** [BALKANGraph/OrgChartJS#169]
Hi,
In latest version you changed the default export menu to not expand all nodes at once.
When I change it by passing the expand all nodes parameter - I get an "413 payload too large" error.

Can I either fix that error, or perhaps have the export print the current chart's status of opened/closed nodes?

So if the user expanded 1 or 2 nodes and exports to PDF he will get the entire chart as he sees it (with only the nodes he expanded in the export)?

Thanks!

**Comment by plamen-peshev** [comment]
I have tried to replicate the issue with the latest version to no avail

See the following video:
https://1drv.ms/v/s!Ah4WnDCbGi3njfQEUA2QlXlCU3xPsg?e=aRJ8Pk

What is different in you scenario

**Comment by shaipetel** [comment]
I'm not sure, perhaps I need to update my version...
I'll check and update here soon

**Comment by shaipetel** [comment]
Hi @plamen-peshev 
I found what was causing it and I need your assistant to figure it out...

I added the option:
```
      options.collapse = {
        level: 2
        allChildren: true
      };
```
or:
```
      options.collapse = {
        level: 3
        allChildren: true
      };
```

Since I have a requirement to allow the user to set the # of levels that should be opened by default.

when I use this option - it overrides the current user's state of opened/closed nodes and prints the chart with this default settings.

I need to be able to set the default chart first-time load state, but during export I need the chart to respect the current user's view if he closed or opened nodes.

Can you guide me how to achieve that please?

**Comment by shaipetel** [comment]
I fixed it in my code,
changed function OrgChart.server._initStates

changed the statement:
```
if (config.collapse.level)
```
to:
```
if (action != OrgChart.action.exporting &&//ignore collapse settings when exporting
            config.collapse.level)
```

So now it respects this settings for init, but not when exporting.

If you have a better solution without changing the source code please advise,

thanks!
