### ISSUE TITLE
Nodes overlapping 

### ISSUE THREAD

**Issue by jfarooq22** [BALKANGraph/OrgChartJS#170]
I am using the Orgchartjs and my nodes overlap where the node has multiple parents
![overlap](https://user-images.githubusercontent.com/50218643/61929131-12fb7200-af94-11e9-82db-4f46438927bf.PNG)

**Comment by plamen-peshev** [comment]
your parent-children relation is incorrect in your node jsaon object

if you are not able to solve the issue post your json object here

**Comment by jfarooq22** [comment]
Thanks for the help.
