### ISSUE TITLE
Troyan virus found in latest licensed version ZIP

### ISSUE THREAD

**Issue by mitkosoft** [BALKANGraph/OrgChartJS#171]
Hi there,

It seems there is a problem with the latest licensed version's ZIP archive. Our Windows antivirus software reports that there is a virus into the file:

![CXmailJSDIX](https://user-images.githubusercontent.com/16716343/62120544-781fd200-b2ca-11e9-8125-e314a491eba7.jpg)

So we cannot extract and install it.

Could you please check the issue?

Thank you!

**Comment by plamen-peshev** [comment]
It is not possible orgchart.js to contain viruses

Can you try to zip other js file and send it with outlook

**Comment by mitkosoft** [comment]
It looks like we have an internal problem with our mail server. Will close the ticket and will open a new one if needed. Thank you!
