### ISSUE TITLE
Can I make multiple OrgChart?

### ISSUE THREAD

**Issue by cpark0** [BALKANGraph/OrgChartJS#172]
Thank you for open a useful code! Now I try free version. I would like to import/export multi-orgchart.

e.g) 
    Drag&Drop any empty place
    Import/Export multi selected file or merge with current chart

Thank you.

**Comment by plamen-peshev** [comment]
Yes you can

It will require some development from your side

Here is a demo that you can use as starting point:

https://balkangraph.com/OrgChartJS-Demos/ImportFromCSV
