### ISSUE TITLE
drag noeuds 

### ISSUE THREAD

**Issue by jaafarscorpion** [BALKANGraph/OrgChartJS#174]
I have training in Parent and of module and course is node it s user who built ts organization chart
it's possible with this plugin
example
Training is parent 
and i drag and drop module in training

**Comment by plamen-peshev** [comment]
Try [this](https://balkangraph.com/OrgChartJS/Demos/Grouping) demo, you can drag&drop nodes in group nodes

**Comment by jaafarscorpion** [comment]
sorry this [capture ](https://s.nimbusweb.me/share/3151223/usrd3xwkkh717k4rzqlz) I want
drag module in training

**Comment by plamen-peshev** [comment]
use [this demo ](https://balkangraph.com/OrgChartJS-Demos/DragDropItemsToChart)as starting point

**Comment by jaafarscorpion** [comment]
thank you very much but just a question is what can I keep the knots and the noid is vertical as [capture](https://ibb.co/1GNtJNx) and when I move a node, I no longer move to another node

**Comment by jaafarscorpion** [comment]
I still have to remove undefined and keep the knots after drag drop https://jsfiddle.net/jaafar/gb6kn8Lz/
