### ISSUE TITLE
How can i set tags manually?

### ISSUE THREAD

**Issue by yuisister** [BALKANGraph/OrgChartJS#175]
Thank you for open a useful code! Now I try free version. I would like to know is there any way to 
manually create a tag that bind to your Json data?
e,g:
{ id: 7, pid: 3, name: "WTF", title: "dev", unit: "TEMP", group: "Team 2", img: "//balkangraph.com/js/img/2.jpg" },

- i just want to manually add a tags to the "unit". 
Thank you.

**Comment by plamen-peshev** [comment]
Not sure what are you trying to achieve, can you elaborate more

**Comment by yuisister** [comment]
Thank you for your reply.
My Json data is look like this when it loaded:
{ id: 7, pid: 3, name: "WTF", title: "dev", unit: "TEMP", group: "Team 2", img: "//balkangraph.com/js/img/2.jpg" },
i just want to ask is there anyway to set the "unit: TEMP"as a tags like example: 
{ id: 7, pid: 3, name: "WTF", title: "dev", tags: ["TEMP"], group: "Team 2", img: "//balkangraph.com/js/img/2.jpg" },

**Comment by plamen-peshev** [comment]
when?

onload or on button click event

**Comment by yuisister** [comment]
Yes, when onload the website. Sorry for not mention it in the last question.

**Comment by plamen-peshev** [comment]
Here is an example:

```
        var nodes = [{ id: 7, pid: 3, name: "WTF", title: "dev", unit: "TEMP", group: "Team 2", img: "//balkangraph.com/js/img/2.jpg" }];

        for(var i = 0; i < nodes.length; i++){
            nodes[i].tags = [nodes[i].unit]
        }

```

**Comment by yuisister** [comment]
Thank you very much. It work like a charm. I'll close this issue right away :D Thank you.
