### ISSUE TITLE
 Dragged callback event

### ISSUE THREAD

**Issue by ZHwin** [BALKANGraph/OrgChartJS#176]
Drag a node to another node. If the condition is not met, stop dragging. Does it has a dragged callback event?

**Comment by plamen-peshev** [comment]
https://jsfiddle.net/BALKANGraph/okL8jm0u/


```
    var chart = new OrgChart(document.getElementById("tree"), {
        enableDragDrop: true,
        enableSearch: false,

        nodeBinding: {
            field_0: "id",
            field_1: "pid"
        }
    });
    
    chart.on('update',  function update(sender, oldNode, newNode) {
    		if (oldNode.pid != newNode.pid) { //drag&drop
         //if (your condition goes here)
        	return false; //to cancel the operation
        }
    });
    
    chart.load([
            { id: 1 },
            { id: 2, pid: 1 },
            { id: 3, pid: 1 },
            { id: 4, pid: 2 },
            { id: 5, pid: 2 },
            { id: 6, pid: 3 },
            { id: 7, pid: 3 }
        ]);
```

**Comment by ZHwin** [comment]
thank you very much！


------------------ 原始邮件 ------------------
发件人: "Plamen Peshev"<notifications@github.com>;
发送时间: 2019年8月5日(星期一) 晚上8:47
收件人: "BALKANGraph/OrgChartJS"<OrgChartJS@noreply.github.com>;
抄送: "1069495035"<1069495035@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [BALKANGraph/OrgChartJS]  Dragged callback event (#176)




https://jsfiddle.net/BALKANGraph/okL8jm0u/
     var chart = new OrgChart(document.getElementById("tree"), {         enableDragDrop: true,         enableSearch: false,         nodeBinding: {             field_0: "id",             field_1: "pid"         }     });          chart.on('update',  function update(sender, oldNode, newNode) {     		if (oldNode.pid != newNode.pid) { //drag&drop          //if (your condition goes here)         	return false; //to cancel the operation         }     });          chart.load([             { id: 1 },             { id: 2, pid: 1 },             { id: 3, pid: 1 },             { id: 4, pid: 2 },             { id: 5, pid: 2 },             { id: 6, pid: 3 },             { id: 7, pid: 3 }         ]);
