### ISSUE TITLE
How to display multiple organization charts vertically

### ISSUE THREAD

**Issue by ZHwin** [BALKANGraph/OrgChartJS#177]
![1565056825(1)](https://user-images.githubusercontent.com/29451598/62505923-1fec5100-b831-11e9-9d5b-fad3f3fe7f2f.png)
change to
![1565056984](https://user-images.githubusercontent.com/29451598/62506289-a48b9f00-b832-11e9-92ea-5e2028b8983b.png)

**Comment by plamen-peshev** [comment]
the easiest way is to create 3 orgcharts

**Comment by ZHwin** [comment]
But you can't drag between the 3 orgcharts

**Comment by plamen-peshev** [comment]
Requested functionality is not supported in the current version
