### ISSUE TITLE
Uncaught TypeError: Cannot read property 'leftNeighbor' of null

### ISSUE THREAD

**Issue by jason-dowzell** [BALKANGraph/OrgChartJS#179]
I am trying to use dotted lines  - the data works fine when there is no dotted line but as soon as I add spid value the chart does not load and console shows:

Uncaught TypeError: Cannot read property 'leftNeighbor' of null
    at Object.secondLinks (orgchart.js?894783208:1)
    at orgchart.js?894783208:1
    at orgchart.js?894783208:1
    at orgchart.js?894783208:1
    at Object.OrgChart.remote._proceed (orgchart.js?894783208:1)
    at orgchart.js?894783208:1
    at IDBRequest.e.onsuccess (orgchart.js?894783208:1)

I only have a single dotted line/spid value at this stage - is there some special ordering or structuring which is required when using dotted line?

You can see the current example at https://jsfiddle.net/ua7x30o1/

If I remove the SPID then it works fine - https://jsfiddle.net/ua7x30o1/1/

What am I doing wrong or what do I need to change to get this to work?

Thanks

**Comment by plamen-peshev** [comment]
you are adding second link (totted line) from node 265731 to node 265714, both nodes are in the same level

Second parent does not support nodes in one level. It is limitation in the current version

![image](https://user-images.githubusercontent.com/49443821/62694725-8ca44e80-b9dd-11e9-8104-c3836ccd717b.png)

**Comment by jason-dowzell** [comment]
OK thanks for letting me know - is there a way of handling this more gracefully rather than just stopping the chart from loading entirely?

**Comment by ZornitsaSerbezova** [comment]
Now you can use Slinks.
