### ISSUE TITLE
Add Collapse and expand to each children not parent 

### ISSUE THREAD

**Issue by alaa-alhajj** [BALKANGraph/OrgChartJS#180]
I need to add collapse , expand button to each child so that I can collapse one child and still have the other children expanded.

Can I do that??

**Comment by plamen-peshev** [comment]
yes

https://jsfiddle.net/BALKANGraph/q03Ljovr/


![image](https://user-images.githubusercontent.com/49443821/62694022-3c78bc80-b9dc-11e9-8f0a-22bdcd773cbe.png)
