### ISSUE TITLE
disable fields from showing in edit form

### ISSUE THREAD

**Issue by alaa-alhajj** [BALKANGraph/OrgChartJS#181]
How to disable some fields from showing in edit form and also disable assistant option??

**Comment by plamen-peshev** [comment]
If you want to customize the edit from see "Custom Edit Form" section from [this ](https://balkangraph.com/OrgChartJS/Docs/Edit)help article

**Comment by plamen-peshev** [comment]
Get the latest version

See "Change the Edit fields in the default Edit form" section from [this ](https://balkangraph.com/OrgChartJS/Docs/Edit) help article
