### ISSUE TITLE
Export nodes to JSON

### ISSUE THREAD

**Issue by keyboardCommando** [BALKANGraph/OrgChartJS#182]
Hi guys, just wondering if there was a method to get the complete node structure as JSON rather than XML?

**Comment by keyboardCommando** [comment]
Hi guys, just wondering if there was a method to get the complete node structure as JSON rather than XML?

**Comment by plamen-peshev** [comment]
Here is how to get the json object:

`chart.config.nodes`

If you want to get specific node us:

`chart.get(5)`

where 5 is the node id

**Comment by keyboardCommando** [comment]
Thanks, you're awesome!
