### ISSUE TITLE
About webfont icon integration instead if image

### ISSUE THREAD

**Issue by jeneepatel** [BALKANGraph/OrgChartJS#186]
I want to know what are the steps  to include webfont instead of image for orgchart?

**Comment by plamen-peshev** [comment]
See the node menu icons of [this ](https://balkangraph.com/OrgChartJS-Demos/ConditionalNodeMenuItems) example

**Comment by jeneepatel** [comment]
Hi Plamen Peshev, Thanks fir replying. But I want to be font awsome as main node image  with field0 and field 1. How can I add there ? And Moreover, I randomly got this error in js.  
Cannot open database!
orgchart.js:1:42166
OrgChart.idb._open/t.onerror

**Comment by plamen-peshev** [comment]
I have updated the demo: https://jsfiddle.net/BALKANGraph/Lw480rc9/

Are you experiencing the issue in IE?

**Comment by jeneepatel** [comment]
Hi Team,

It is nice to hear from you. I am facing one problem right now. If I do not
mention one field in json object ,still the empty input is showing in side
bar while clicking on that node. Is that any solution not to show empty
field in that sidebar.


Thanks,
Jenee

**Comment by ZornitsaSerbezova** [comment]
You can hide fields, using "field" event. See how at the bottom of this page:
https://balkangraph.com/OrgChartJS/Docs/Edit
