### ISSUE TITLE
disable bulle Grey

### ISSUE THREAD

**Issue by jaafarscorpion** [BALKANGraph/OrgChartJS#187]
hello how disable bulle grey ,she appears on the click

**Comment by plamen-peshev** [comment]
set OrgChart.templates.ana.ripple.color = 'none';

Here is a demo: https://jsfiddle.net/BALKANGraph/0wkmh3sb/

**Comment by jaafarscorpion** [comment]
sorry but it still exists https://ibb.co/GWLJmvn
thank you

**Comment by plamen-peshev** [comment]
I have updated  the demo 

https://jsfiddle.net/BALKANGraph/0wkmh3sb/
