### ISSUE TITLE
wrap text in custom fields

### ISSUE THREAD

**Issue by PhoenixC46** [BALKANGraph/OrgChartJS#188]
This is a great little tool and so easy to get working with our data (pulled from SQL), but i'm having problems with the custom fields.
I can get all the information to appear but the "Interested In" field should only appear on the sidebar which pops-out. This is all working fine but the text is long and i can't get it to use the multiline style and applying a word-wrap to the CSS has no effect.
Can you give any advice how i can show the text as multiline?
Thanks,

**Comment by plamen-peshev** [comment]
In order to achieve requested functionality you can define your own custom edit form, see "Custom Edit Form" section from [this ](https://balkangraph.com/OrgChartJS/Docs/Edit) help article

**Comment by PhoenixC46** [comment]
Hi thanks for the advice but i've already added the fields and they appear where i want, but the text has overflowed and didn't wrap onto the next line so most of it is missing.

For example the text in bold is visible the rest is not:
**This is the text which fits into the single line of text** but the rest of it has spilled outside the page.

How can i change the size or area of the box so all the text fits or apply a word-wrap to the formatting?
Thanks,

**Comment by plamen-peshev** [comment]
The text in the node box or the text in the edit form?

**Comment by PhoenixC46** [comment]
It's the edit form i need to change. We want to list peoples interests/hobbies and some of their text is quite long (400chrs). I don't expect to fit all of it on the edit form but it would be nice to show a few lines instead of just the single line.
Thanks

**Comment by plamen-peshev** [comment]
Instead of changing the built-in edit form, create your won edit form, see "Custom Edit Form" section from [this ](https://balkangraph.com/OrgChartJS/Docs/Edit) help article. with that approach you can create multiline text area, dropdowns, chackboxes etc

**Comment by PhoenixC46** [comment]
ok i've figured out how to build the custom edit form using the example (although i need to figure out how to use the right-hand edit form instead of the pop-up box) but there seems to be a problem using textarea instead of an input which doesn't support multiline text and explains why it wouldn't wrap when using the standard edit form.

I need to change the Input to TextArea but no matter what i try it won't work:
```
<div style="padding: 5px 0 10px 0;">
                <label style="color:#ffffff; width:150px; display:inline-block;" for="Interests">Interests</label>
                <input style="background-color:#FFCA28; width:400px; height:70px;" id="interests" value="" />
            </div>
```

To be replaced with something like:
```
<div style="padding: 5px 0 10px 0;">
                <label style="color:#ffffff; width:150px; display:inline-block;" for="Interests">Interests</label>
                <textarea name="Interests" rows="14" cols="10" wrap="soft" maxlength="40" style="overflow:hidden; resize:none;></textarea>
            </div>
```

**Comment by plamen-peshev** [comment]
Get the latest version

See "Change the Edit fields in the default Edit form" section from [this ](https://balkangraph.com/OrgChartJS/Docs/Edit) help article

**Comment by PhoenixC46** [comment]
Thanks for the information but it's not the node menu (with the 3 dots icon) i want to change, it's the pop-out sidebar (right-hand side) which i need to change from being a single line of text to either multiline or textarea.

**Comment by plamen-peshev** [comment]
![image](https://user-images.githubusercontent.com/49443821/67091638-d5cf0680-f1b5-11e9-88b2-3089afac70d0.png)

In [this ](https://jsfiddle.net/BALKANGraph/z6gpdx7n/?utm_source=website&utm_medium=embed&utm_campaign=z6gpdx7n) demo the text box is replaced with dropdown, use the same logic to replace it with multiline

**Comment by ZornitsaSerbezova** [comment]
Hi, PhoenixC46!
Here is the multiline demo: https://balkangraph.com/OrgChartJS-Demos/CustomField

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue. Feel free to reopen it or open another one.
