### ISSUE TITLE
Nodes limitation

### ISSUE THREAD

**Issue by Kalizo** [BALKANGraph/OrgChartJS#189]
Hello,

OrgChart show me the max nodes limit message

![image](https://user-images.githubusercontent.com/6975506/63344762-79846d80-c351-11e9-99ff-ea07c9b66ed7.png)

while I have not reached the limit...

![image](https://user-images.githubusercontent.com/6975506/63344845-aa64a280-c351-11e9-97fb-26c537096167.png)

Until today I had no problem. How it possible ?

**Comment by plamen-peshev** [comment]
you are using the trial version and your trial period has expired
