### ISSUE TITLE
About Details view

### ISSUE THREAD

**Issue by jeneepatel** [BALKANGraph/OrgChartJS#191]
I am using OrgChart with template isla trial version. I am currently facing one issue with Details View sidebar while clicking on node. In that  details-view, I want one more field description containing multi line text but  it is not showing whole line properly, and even i am not able to scroll right side to see full text.So my some text is getting hide. One more issue with if I add new filed in node binding json, then that field is getting attached with other nodes also,even though I dont want that field in others. I dont want to create new custom edit form. Existing form with multiline  fields.

**Comment by plamen-peshev** [comment]
See "Change the Edit fields in the default Edit form" section from [this ](https://balkangraph.com/OrgChartJS/Docs/Edit) help article
