### ISSUE TITLE
VM1012 orgchart.js:1 Error: <svg> attribute viewBox: Expected number, "-10,-2082.5,NaN,NaN".

### ISSUE THREAD

**Issue by ZHwin** [BALKANGraph/OrgChartJS#193]
VM1012 orgchart.js:1 Error: <svg> attribute viewBox: Expected number, "-10,-2082.5,NaN,NaN".

**Comment by plamen-peshev** [comment]
Please share your OrgChart JS configuration

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue. Please feel free to reopen it again if needed.

**Comment by suvinmanoj** [comment]
Am also having same issue

Am trying to integrate with Angular 8

**Comment by ZornitsaSerbezova** [comment]
Hi suvinmanoj,
Did you try this?: https://balkangraph.com/OrgChartJS/Docs/Angular

**Comment by suvinmanoj** [comment]
yes i tried this but it not working properly

**Comment by ZornitsaSerbezova** [comment]
What is not working in our tutorial?
