### ISSUE TITLE
Menu position when using bootstrap

### ISSUE THREAD

**Issue by coyote9999** [BALKANGraph/OrgChartJS#194]
Hi all!

I want to implement BalkanGraph in a project that use Bootstrap 3.
But when I add boostrap.css, the context menu position is totally wrong. (using drag and drop)

Is there a chance to change Balkans menu class to prevent this issue?

![2019-08-27 13_15_15-Window](https://user-images.githubusercontent.com/15721437/63767237-5b78b900-c8cd-11e9-8bfe-988248be20e6.png)

**Comment by plamen-peshev** [comment]
Can you create a demo in jsfiddle where we can see the issue and eventually fix it

**Comment by ZornitsaSerbezova** [comment]
Hi, I'll close this issue. Please feel free to reopen it if needed,
