### ISSUE TITLE
localstorage has not funcUrl

### ISSUE THREAD

**Issue by ZHwin** [BALKANGraph/OrgChartJS#195]
we use private network
![image](https://user-images.githubusercontent.com/29451598/63771284-736e2e00-c909-11e9-8691-76f4deaaf91c.png)
![image](https://user-images.githubusercontent.com/29451598/63771293-79640f00-c909-11e9-814a-51107e78f6a7.png)
why?

**Comment by plamen-peshev** [comment]
The Trial version does not work in private network

Download licensed version from your [account  ](https://balkangraph.com/console/Login?returnUrl=%2Fconsole%2F)
