### ISSUE TITLE
how can i define and add a new tag to chart and group nodes with that tag??

### ISSUE THREAD

**Issue by 1stgoddeath** [BALKANGraph/OrgChartJS#196]
I can not understand and add or define a new tag to group and display nodes in that tags..
and could i can create new tag template??

**Comment by plamen-peshev** [comment]
Yes you can

Use the following methods 
- addTag	
- removeTag	
- addNodeTag	
- removeNodeTag


See [API Reference](https://balkangraph.com/OrgChartJS/Docs/APIReference) for more info
