### ISSUE TITLE
On click on node level menu for navigation.

### ISSUE THREAD

**Issue by caeserbala** [BALKANGraph/OrgChartJS#198]
Hi Team ,

we have three dot menu at node level to export PDF , images  , add , remove , edit . But my requirement is to navigate to other pages or to create a custom action to run function on click.

like on three dot menu on employee on click need to navigate to employee details pages which contains elaborate details about employee .

Could you kindly work on this one .

**Comment by plamen-peshev** [comment]
Set `nodeMouseClick: BALKANGraph.action.details`

See [this ](https://jsfiddle.net/BALKANGraph/8620dcpr/)demo 


```
       var chart = new OrgChart(document.getElementById("tree"), {
        mouseScrool: OrgChart.action.none,
            nodeMouseClick: BALKANGraph.action.details,
            nodeBinding: {
                field_0: "name",
                field_1: "title"
            },     
            nodes: [
                { id: 1, name: "Amber McKenzie", title: "CEO" },
                { id: 2, pid: 1, name: "Ava Field", title: "IT Manager" },
                { id: 3, pid: 1, name: "Peter Stevens", title: "HR Manager" }
            ]
        });   
```

**Comment by caeserbala** [comment]
our requirement is to navigate to different page  . It would be great if we have generic action without limited naming constrain . right now i guess we have only few like details , add , edit remove . 
could you create so we can have our own custom name for custom action .

**Comment by plamen-peshev** [comment]
Do you want to add new menu item 

![image](https://user-images.githubusercontent.com/49443821/64153147-de9e8f80-ce36-11e9-99e5-87b180dbdcc3.png)

Please try to be more specific what exactly you want to achieve

**Comment by mitkosoft** [comment]
Something like that?
`                            onClick: function (sender, node) {
                                //console.log(sender);
                                location.href = '/index.php?structId=' + node.structId + '&empId=' + node.id;
                            },
`
This will navigate you to a different page (index.php) when you click on some node.

**Comment by vigneshnamachi** [comment]
Hii is there a solution for this top achieve???

**Comment by ZornitsaSerbezova** [comment]
Hi vigneshnamachi,
What wxactly do you need to achieve? Could you show us with screenshots?

**Comment by vigneshnamachi** [comment]
Got the solution from docs itself, Thank you!!

**Comment by vigneshnamachi** [comment]
Hii, How to do css customization for NodeMenuItem

**Comment by ZornitsaSerbezova** [comment]
You can see in this demo here:
https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/CustomTemplateColor

**Comment by vigneshnamachi** [comment]
Yeah but what i want to achieve is OnClick of nodemenu the options (Node menu Items) are poping out from left side but i want to pop out to right side.

**Comment by ZornitsaSerbezova** [comment]
if you'd like the menu to popup from left to right:
https://jsfiddle.net/Lvqhrac5/

if you'd like to move the menu on the left side:
https://jsfiddle.net/g3nL9fpe/

**Comment by vigneshnamachi** [comment]
Thanks a Lot, really helpful @ZornitsaSerbezova

**Comment by vigneshnamachi** [comment]
Hi, 
I want to show the color legends used in the balkangraph, top-right side corner there is menu option instead of menu i want to replace with color legends, how is it possible?

thanks

**Comment by ZornitsaPesheva** [comment]
> Hi,
> I want to show the color legends used in the balkangraph, top-right side corner there is menu option instead of menu i want to replace with color legends, how is it possible?
> 
> thanks

Is this what you need: https://jsfiddle.net/BALKANGraph/nt2bcfe1/

**Comment by vigneshnamachi** [comment]
> > Hi,
> > I want to show the color legends used in the balkangraph, top-right side corner there is menu option instead of menu i want to replace with color legends, how is it possible?
> > thanks
> 
> Is this what you need?: https://jsfiddle.net/BALKANGraph/nt2bcfe1/

Thanks @ZornitsaPesheva
