### ISSUE TITLE
Can this component library implement cross-layer connectivity?

### ISSUE THREAD

**Issue by zxforben** [BALKANGraph/OrgChartJS#199]
Can this component library implement cross-layer connectivity?

![image](https://user-images.githubusercontent.com/5674472/64138511-e444a700-ce2f-11e9-85cb-f3cc95251513.png)

**Comment by plamen-peshev** [comment]
you can use [clinks](https://balkangraph.com/OrgChartJS-Demos/clink) and/or [spids](https://balkangraph.com/OrgChartJS/Demos/MultipleParents) to achieve requested functionality

**Comment by zxforben** [comment]
@plamen-peshev thanks for your advice. I have added clinks into function of new orgchart, but the link didn't display. I think the library version is not the same as yours. Could you give me the latest library. Thanks.

**Comment by plamen-peshev** [comment]
Correct clink was implemented recently

You can download the latest version from https://balkangraph.com/OrgChartJS/Download

**Comment by zxforben** [comment]
okay thanks very much.
