### ISSUE TITLE
Chart is not getting reflected on page refresh

### ISSUE THREAD

**Issue by jeneepatel** [BALKANGraph/OrgChartJS#201]
On first time menu click, chart is displaying successfully. But on refresh page, it is taking too much time  and nothing displayed.
**Zk code :**
<?variable-resolver class="org.zkoss.zkplus.spring.DelegatingVariableResolver" ?>
<?taglib uri="http://www.zkoss.org/dsp/web/core" prefix="c"?>

<zk xmlns="http://www.zkoss.org/2005/zul"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.zkoss.org/2005/zul http://www.hybris.com/schema/cockpitng/zul/zul.xsd"
	xmlns:n="native" xmlns:w="http://www.zkoss.org/2005/zk/client">
	
	<window id="HomePage" border="none" width="100%" height="100%" >
	
	<n:div id="tree"></n:div>
	
	<n:script type="text/javascript">
   	var chart = new OrgChart(document.getElementById("tree"), {
   			template: "isla",
	    	enableDragDrop: false,
	        toolbar: true,
	        menu: {
	            pdf: { text: "Export PDF" },
	            png: { text: "Export PNG" },
	            svg: { text: "Export SVG" },
	            csv: { text: "Export CSV" }
	        },
	        nodeMenu: {
	            details: { text: "Details" },
	            add: { text: "Add New" },
	            edit: { text: "Edit" },
	            remove: { text: "Remove" },
	        },
	        nodeBinding: {
	            field_0: "Title",
	            field_1: "Name",
	            img_0: "img",
	        },
	});
   
	function do_hook( jdata_arg){
		 var json=jq.evalJSON(jdata_arg);
		 for(var i in json.nodesArray){
		 	chart.add(json.nodesArray[i]);
		 }
	     chart.draw(BALKANGraph.action.init);
	     chart.fit();
	  }	
	</n:script>
	
	</window>
</zk>

**Console error:**
VM9096:1 Refused to apply style from 'https://10.121.21.138:9002/backoffice/cng/css/systembar.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

zk.wpd:239 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at b.$supers (zk.wpd:239)
    at bind_ (chart.wpd:1296)
    at bindChildren_ (zk.wpd:431)
    at bind_ (zk.wpd:430)
    at bind_ (TSB-4579.js:12)
    at bindChildren_ (zk.wpd:431)
    at bind_ (zk.wpd:430)
    at bind_ (TSB-4579.js:12)
    at bindChildren_ (zk.wpd:431)
    at bind_ (zk.wpd:430)
$supers @ zk.wpd:239
bind_ @ chart.wpd:1296
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
$supers @ zk.wpd:239
bind_ @ zk.wpd:768
$supers @ zk.wpd:239
bind_ @ zul.tab.wpd:157
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
$supers @ zk.wpd:239
bind_ @ zul.tab.wpd:144
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
$supers @ zk.wpd:239
bind_ @ zul.tab.wpd:5
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
$supers @ zk.wpd:239
bind_ @ zul.box.wpd:3
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
$supers @ zk.wpd:239
bind_ @ zk.wpd:768
$supers @ zk.wpd:239
bind_ @ zul.wnd.wpd:30
bindChildren_ @ zk.wpd:431
bind_ @ zk.wpd:430
bind_ @ TSB-4579.js:12
bind @ zk.wpd:429
replaceChildHTML_ @ zk.wpd:424
replaceHTML @ zk.wpd:422
p @ zk.wpd:496
r @ zk.wpd:495
g @ zk.wpd:487
_zkf @ zk.wpd:488
(anonymous) @ zkex.inp.wpd:65
g @ zk.wpd:487
_zkf @ zk.wpd:488
(anonymous) @ zkex.inp.wpd:65
Show 111 more frames

[Violation] Forced reflow while executing JavaScript took 88ms
[Violation] Forced reflow while executing JavaScript took 46ms

zk.wpd:195 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

**Browser Page error:**
Error code 3: ZK error, after mounting.

Something went wrong while loading the page.
Please try to reload or visit another page. If you are the administrator, try to check your Javascript or Network console.

Orgchart.js is loaded properly (checked in network tab )

**Comment by plamen-peshev** [comment]
According to you logs you should check https://xhr.spec.whatwg.org/. 

https://xhr.spec.whatwg.org/ is not OrgChart JS system
