### ISSUE TITLE
Summary in Exported PDF File

### ISSUE THREAD

**Issue by leng1023** [BALKANGraph/OrgChartJS#203]
We are planning to purchase subscription of balkangraph bit I want to confirm first if this is possible. I want the summary to be incorporated with the exported PDF file. I attached the sample output.
![summary](https://user-images.githubusercontent.com/52233186/64308451-e93e5d80-cfcb-11e9-9b16-49f545876348.JPG)

**Comment by leng1023** [comment]
Hope to hear from you soon, so we can incorporate the subscription fee with our budget this year. Thank you so much.

**Comment by plamen-peshev** [comment]
The requested functionality is supported

In order to create a demo for you we need further information

Do you need A4 PDF , if yes do you need the summary to be on separate page?

**Comment by leng1023** [comment]
Hello, no the summary should be at the top upper left portion of the chart. Thank you.

**Comment by leng1023** [comment]
> 
> 
> The requested functionality is supported
> 
> In order to create a demo for you we need further information
> 
> Do you need A4 PDF , if yes do you need the summary to be on separate page?

How about long bond paper, with the summary on same page.

**Comment by ZornitsaSerbezova** [comment]
you can use [this](https://balkangraph.com/OrgChartJS-Demos/ExportPDFWithLogo) demo as an example
