### ISSUE TITLE
Can't display the chart with below error? Any suggestion?

### ISSUE THREAD

**Issue by zxforben** [BALKANGraph/OrgChartJS#204]
![image](https://user-images.githubusercontent.com/5674472/64578364-be7c4c80-d3b1-11e9-8b07-f20a2a7d025f.png)

**Comment by plamen-peshev** [comment]
Can you please post your OrgChart JS configuration

**Comment by zxforben** [comment]
` $scope.chart = new OrgChart(document.getElementById("tree"), {
                template: "myTemplate",
                enableSearch: false,
                // menu: {
                //     png: {text: "Export PNG"}
                // },
                nodeMenu: {
                    png: {text: "Export PNG"},
                    pdf: {text: "Export PDF"}
                },
                linkBinding: {
                    link_field_0: "percent"
                },
                nodeBinding: {
                    field_0: "name"
                },
                zoom: {
                    speed: 10,
                    smooth: 5
                },
                nodes: nodesContent,
                onExportStart: exportStart,
                onClick: click,
                scaleInitial: 0.6,
                onRedraw: redraw,
                // clinks: clinks
                // mouseScrool: OrgChart.action.none
            });`

**Comment by plamen-peshev** [comment]
Sorry, I want the json data (nodes)

Do you have spids that points to the same level in your json data?

**Comment by zxforben** [comment]
yes, if there are spids that points to the same level , the error will be happened. do you have any method to handle with this ?

**Comment by ZornitsaSerbezova** [comment]
Now you can use **Slinks**:
https://balkangraph.com/OrgChartJS/Docs/Slink

I'll close this issue. If you have any problems or questions, feel free reopen it.
