### ISSUE TITLE
text-overflow ellipsis doesn't work all time

### ISSUE THREAD

**Issue by Kalizo** [BALKANGraph/OrgChartJS#205]
Hello,

I'm using custom template for my orgchart and I have a problem with text-overflow attribute : I'm apply this behavior on multiple element, but one of these doesn't work and I don't understand why.

Width is defined and text-overflow is applied but however :

![image](https://user-images.githubusercontent.com/6975506/64680448-1aaca280-d47e-11e9-971b-a635d032b801.png)

Text element isn't append with title element and text truncated like others texts in the same card...

Someone can help me please ? I wanted to read js code but minified version is unreadable.

**Comment by plamen-peshev** [comment]
Can you post your custom template here

**Comment by Kalizo** [comment]
![image](https://user-images.githubusercontent.com/6975506/64697391-0b8b1c00-d4a1-11e9-8f99-fe06e6af7ba7.png)

Sorry about image, markdown doesn't understand twig concatenation...

**Comment by plamen-peshev** [comment]
Can you share your custom template here?

Thank you for your cooperation

**Comment by Kalizo** [comment]
I can't share all my (confidential) custom template, sorry. Above, my field template that cause problem.

What is the condition for render the <text> tag with the <title> tag and truncated text ? I have the feeling that it isn't match with this code, so it render the original <text> tag without truncated text.

**Comment by Kalizo** [comment]
@plamen-peshev Is it possible for something to conflict with the code that truncates the text tag?

**Comment by ZornitsaSerbezova** [comment]
Did you manage to resolve this issue?

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue, but you can reopen it if needed.
In order to be able to help you, you will need to share your code in jsfiddle or attach a file. Also you can write us an email,
