### ISSUE TITLE
Problem with AJAX data

### ISSUE THREAD

**Issue by tareqhi** [BALKANGraph/OrgChartJS#207]
Hello,
Can I have a working example link for a chart with AJAX Data?

I am working with server-side data. The Ajax query returned with org chart formatted data successfully. I have logged the Ajax output to browser's console. Copied the data & pasted it to  var chart = new OrgChart(document.getElementById('tree'), { *** }); here. Its working fine. Also tried the output in blankgraphs site, its working there.
But when I declare the output like:

success:function(output){
var chart_data = output;
var chart = new OrgChart(document.getElementById('tree'), { chart_data });

Its not working, Plz help me, or send me a working example.

**Comment by plamen-peshev** [comment]
Use [this ](https://github.com/BALKANGraph/OrgChartWebApp) demo as starting point 

The code that you are looking for is 

```
       $.get("@Url.Action("Read")").done(function (response) {
            chart.load(response.nodes);
        });
```

Using jquery

**Comment by tareqhi** [comment]
after ajax call success, i see the error in tags.
in json return, the tags output like: "['Some Tags']"

When it comes to node, the node cant read without the double quotes & its treated as each character as an individual tag.

I'm getting the problem to print the [ and ] brackets in tags. how to manage it?

**Comment by tareqhi** [comment]
@plamen-peshev , Finally following is worked! Booo!

```
success:function(output){
      var data = JSON.parse(output);
      chart.load(data);
}
```

Thanks a lot.
