### ISSUE TITLE
Not working on ie on Local

### ISSUE THREAD

**Issue by MunkhdelgerMorhous** [BALKANGraph/OrgChartJS#208]
There is bug on localStorage.getItem("funcUrl"), Also indexed db not working

**Comment by plamen-peshev** [comment]
The issue has been addressed

Download latest version 5.0.1 and give it a try

**Comment by MunkhdelgerMorhous** [comment]
thanks did just change 3 minutes ago or i tried old ones?

**Comment by plamen-peshev** [comment]
The issue is fixed in versions 5.0.1 and 5.0.2
