### ISSUE TITLE
Custom tags with reloaded data

### ISSUE THREAD

**Issue by rmbienek** [BALKANGraph/OrgChartJS#209]
I am running into an odd behavior. We have multiple small org charts that have the same people between them. We are using a custom tag to allow users to control default collapse status. 
When I load new data, it seems to ignore the custom tags if the same people are in the new data set that were also in the old data set. I tried with only a COLLAPSE tag, and I also tried adding a custom EXPAND tag to those that did not need to be COLLAPSED. No change in result.

Example 1
“Set 1” B has a collapsed child. Click on “set 2” B’s Child should not be collapsed, but is.

Example 2 
Click on “Set 3” all children expanded (which is correct). Click on “Set 2” Child is expanded as I would expect. 

https://jsfiddle.net/rmbienek/upnLxz97/47/

**Comment by plamen-peshev** [comment]
It look like a bug

I have logged it

**Comment by ZornitsaSerbezova** [comment]
Hi rmbienek,
we have removed these oprsions:
```
tags: {
                  "Hide": {
			               		state: OrgChart.COLLAPSE
			        },
                  "Show": {
			            		state: OrgChart.EXPAND
			        }
			        },
```
so I am closing this issue,
