### ISSUE TITLE
[FeatureRequest] MiniMap

### ISSUE THREAD

**Issue by patmuk** [BALKANGraph/OrgChartJS#21]
having a minimap over the expanded tree would be great

**Comment by BALKANGraph** [comment]
Do you want minimap similar to the Overview window below?

![image](https://user-images.githubusercontent.com/43317667/52708709-8e8fd680-2f93-11e9-9430-fccc7661aaae.png)

**Comment by patmuk** [comment]
Yes! This is what I had in mind. Is your screenshot from a work-in-progress?

**Comment by bharathmurthy** [comment]
Is this going to be added anytime soon !? @BALKANGraph

**Comment by ZornitsaSerbezova** [comment]
Now we have Mini map: https://balkangraph.com/OrgChartJS/Docs/APIReference#miniMap
