### ISSUE TITLE
Chart Summary, Export Orientation, Multiple pages upon export

### ISSUE THREAD

**Issue by leng1023** [BALKANGraph/OrgChartJS#210]
Hello how can I put a summary on my chart in upper right section of the page and set the paper orientation to long bond paper landscape. This is for uniformity of the printout of the chart. And also if the chart is to small to read because it is a big organization, is there any way that it will be exported in multiple pages so it can be readable? Hope you can help me. Thank you very much.

**Comment by plamen-peshev** [comment]
Have you tried PDF preview 
1. Open https://balkangraph.com/OrgChartJS/Demos/Exporting
2. On the top right  corner open the menu and select "PDF Preview"
3. You can Change the orientation to landscape, change the page to A4 and add header/footer as summury
