### ISSUE TITLE
How to count?

### ISSUE THREAD

**Issue by tareqhi** [BALKANGraph/OrgChartJS#211]
Dear Dev Team,
I need to count all the data inside a group.

I have used my data to be grouped, but now I want to show the total members of the group besides the group name. (e.g. Devs [4], Marketing [3])

Plz, help me.

**Comment by mitkosoft** [comment]
Probably you are looking for this: https://balkangraph.com/OrgChartJS/Demos/NumberOfChildren

**Comment by tareqhi** [comment]
Hi,
Actually I'm not looking for child count.
I need to count a total inside the group.
I want to show the number besides the group name.

**Comment by ZornitsaSerbezova** [comment]
Hi, **tareqhi**, did you manage to solve this problem?

**Comment by ZornitsaSerbezova** [comment]
Now we have new implementation of groups,
https://balkangraph.com/OrgChartJS/Demos/Grouping
