### ISSUE TITLE
could I resize the rectangle node in the org chart?

### ISSUE THREAD

**Issue by zxforben** [BALKANGraph/OrgChartJS#213]
when I resize the rectangle's width and height, the org chart like below: 
![image](https://user-images.githubusercontent.com/5674472/65117195-469acb80-da1c-11e9-9ec6-7b3262b8d92f.png)
the rectangle isn't in the center position.

**Comment by zxforben** [comment]
so how could i set it in the center position? any suggestions ?

**Comment by plamen-peshev** [comment]
If you want to center specific node you can use [center](https://balkangraph.com/OrgChartJS/Docs/APIReference#center) method

Attach to window.onresize and call center

**Comment by zxforben** [comment]
noted with thanks
