### ISSUE TITLE
Org chart link line can't reach the node if the node is the grandfather of this node, any suggestions?

### ISSUE THREAD

**Issue by zxforben** [BALKANGraph/OrgChartJS#214]
![image](https://user-images.githubusercontent.com/5674472/65210771-d436f380-dace-11e9-9e31-8c3a4ad0b59f.png)

**Comment by zxforben** [comment]
G007 is G004's child node，but it is 公司0002's child，but 公司0002 and G004 are not in the same level? the link sometimes can't reach 公司0002. How can I get rid of this issue? Please suggest. Thanks.

**Comment by ZornitsaSerbezova** [comment]
You can do it with **Slinks** now:
https://balkangraph.com/OrgChartJS/Docs/Slink

I'll close this issue. Should you have any problems, feel free to reopen it.
