### ISSUE TITLE
Group with one element

### ISSUE THREAD

**Issue by perezcoder** [BALKANGraph/OrgChartJS#215]
If I have a group with 2 nodes and remove one node from the group, i lose the template of the group. Can i remain the tamplate on the group?
Another question: i can trigger the Drag and Drop event?

**Comment by plamen-peshev** [comment]
Download the latest version and try

```
    OrgChart.REMOVE_GROUP_IF_HAS_ONE_NODE = false;
    var chart = new OrgChart(document.getElementById("tree"), {
        ...
    });
```

OrgChart.REMOVE_GROUP_IF_HAS_ONE_NODE = false; should solve the issue

**Comment by perezcoder** [comment]
Thank you solved
