### ISSUE TITLE
Is it possible to restrict number of children for a parent (question)

### ISSUE THREAD

**Issue by bharathmurthy** [BALKANGraph/OrgChartJS#216]
Hi There,
First of thanks for producing such great software! I'm trying to figure out if it possible to restrict number of allowed children on a template. I'm looking at these 3 scenarios no children, one child and many children. If this is easily achievable please let me know. 
Thanks in advance 

Cheers
Kumar

**Comment by plamen-peshev** [comment]
you can achieve requested functionality with the nodes structure and pid property

**Comment by bharathmurthy** [comment]
Hi @plamen-peshev ,
Thanks for the response. Can you please elaborate and if possible provide an example JS fiddle? 
Have a good day

Cheers,
Kumar

**Comment by plamen-peshev** [comment]
1 has no children
2 has 2 children
3 has multiple children 

```
ndoes: [
   {id: 0},
   {id: 1, pid: 0},
   {id: 2, pid: 0},
   {id: 3, pid: 0},
   {id: 4, pid: 2},
   {id: 5, pid: 3},
   {id: 6, pid: 3},
   {id: 7, pid: 3},
   {id: 8, pid: 3},
   {id: 9, pid: 3},
]
```
