### ISSUE TITLE
PDF Export - Only exports 1 node if collapse default set

### ISSUE THREAD

**Issue by mporcaro** [BALKANGraph/OrgChartJS#217]
I'm unsure if this is a bug, but when collapse = level 1, and allChildren = true, I am unable to export the pdf correctly.  For example, if the CEO only has 2 nodes maximized, I would expect the export to have 3 nodes.  With the below setup though, I only see 1 node (the CEO).

```
chart = new OrgChart(document.getElementById("tree"), {
        collapse: {
            level: 1,
            allChildren: true
        },
       nodeMenu: {
            pdf: { text: "Export PDF" }
        },
}
```

**Comment by plamen-peshev** [comment]
https://jsfiddle.net/BALKANGraph/kso530qt/

If you export to PDF form the demo above, the PDF should contain one node, it is expected behavior 

Do you want to see other nodes in the PDF doc?

**Comment by mporcaro** [comment]
Interesting, the issue must be with my specific setup.  I will continue to test.

**Comment by mporcaro** [comment]
Ok got it working on my end.  I had to download the latest version, plus clear my browser cache.  Thanks!
