### ISSUE TITLE
Why the chart can't display in today morning? 

### ISSUE THREAD

**Issue by zxforben** [BALKANGraph/OrgChartJS#220]
![image](https://user-images.githubusercontent.com/5674472/65406001-9b6d8600-de10-11e9-99f4-d5c4449f2fe8.png)

**Comment by zxforben** [comment]
is the server is updating or something wrong with that?

**Comment by plamen-peshev** [comment]
try with the latest version 5.0.4 https://balkangraph.com/OrgChartJS/Download

**Comment by zxforben** [comment]
thanks for your advise
