### ISSUE TITLE
Samples doesn't work on firefox

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#221]
The getting started section of the balkangraph web site contains a sample. The result is not shown in firefox. In chrome it works fine.

**Comment by plamen-peshev** [comment]
I have tried [this ](https://jsfiddle.net/BALKANGraph/9rh1ovxf/?utm_source=website&utm_medium=embed&utm_campaign=9rh1ovxf) demo in FF, works well for me

Can you confirm that works for you as well

**Comment by sks4u** [comment]
It may depends on the security adjustments

![firefoxIssue](https://user-images.githubusercontent.com/55696440/65433193-d970a700-de1c-11e9-8f33-0ee141d06302.png)

**Comment by plamen-peshev** [comment]
what is you FF version?

**Comment by sks4u** [comment]
69.0.1 (64-Bit)

**Comment by ZornitsaSerbezova** [comment]
I have tasted it with 70.0.1 (64-Bit) and it works. I'll close this issue, Feel free to reopen it if needed.
