### ISSUE TITLE
how to make nodeMenu dynamic?

### ISSUE THREAD

**Issue by waterfall4289** [BALKANGraph/OrgChartJS#223]
Is it possible to generate nodeMenu dynamically depending on tag. For example, for tag 'A', the nodeMenu would have 3 menu items, for tag 'B', 5 items, etc. 

If not, is it possible to hide or disable a nodeMenu item?

Thank you.

**Comment by plamen-peshev** [comment]
Yes, it is possible

See "Override node menu items for specific node using tags" from [this ](https://balkangraph.com/OrgChartJS/Docs/Menus) help article

**Comment by waterfall4289** [comment]
Thank you plamen-peshev,

Sorry if it's not clear but I meant nodeMenu is dynamic. Django backend returns a list of menu items for each tag and I want to display menu items based on that list.

**Comment by bansalr** [comment]
Plamen, 
I think what we want to do is add menu items individually based on a list from the API. So something like in psuedo-code:


```
for menu_item in list_from_backend:
  nodeMenu.add(text: menu_item['text'], 
                             icon: menu_item['icon'],
                             .....)
```

Basically need to add menu_items individually one by one.

Thanks!

**Comment by plamen-peshev** [comment]
See "Override node menu items for specific node using on show event" from [this ](https://balkangraph.com/OrgChartJS/Docs/Menus) help article

**Comment by bansalr** [comment]
Plamen,

Thank you for the update. We get the following
`
ERROR TypeError: this.chart.dragDropMenuUI.on is not a function (this error fired for all menu types: nodeMenuUI/menuUI/nodeContextMenuUI).
`
We are working with angular (without jquery)

**Comment by plamen-peshev** [comment]
download the latest version

**Comment by bansalr** [comment]
Plamen - 

We are using the latest version of the library.

We sent an email to support with screenshots. 

Thanks!

**Comment by plamen-peshev** [comment]
Can you confirm that the demo above works for you

https://jsfiddle.net/BALKANGraph/mzqjn78g/?utm_source=website&utm_medium=embed&utm_campaign=mzqjn78g

**Comment by bansalr** [comment]
Correction - we were using 4.9 and we tried with 5.0.5 and it works! 

Thank You

**Comment by plamen-peshev** [comment]
Here is our Release history page: https://github.com/BALKANGraph/OrgChartJS/releases

you can follow us
