### ISSUE TITLE
text-overflow="multiline" not working

### ISSUE THREAD

**Issue by callmejamie** [BALKANGraph/OrgChartJS#224]
Hi,

I was trying to get the text-overflow multiline feature on my org chart to work but it just doesn't seem to apply the line breaks to my text. The old version of my library didn't have this feature so I downloaded the latest copy of the OrgChart JS library from the console and added it to my application today. 

But even after setting the width and text-overflow attributes on my text element. It still didn't work! Is there something I'm missing here?

**Comment by callmejamie** [comment]
Ah.. i think I managed to narrow down the issue. It doesn't work when you apply some custom code to the output of your fields

`
OrgChart.templates.ana.field_0 = '{val}';

chart = new OrgChart(document.getElementById("tree"), {
            //some configs in between
            nodeBinding: {
                field_0: function (sender, node) {
                    var displayStr = '';
                    //some logic code here to set the displayStr
    
                    return '<text width="230" text-overflow="multiline" class="field_0 fields" style="font-size: 20px; font-weight: 500" x="125" y="31" text-anchor="middle">' + displayStr + '</text>';
                }
        }
 })
`

**Comment by plamen-peshev** [comment]
Correct, it is limitation 

Multiline and Elipses does not work with function in nodeBinding

**Comment by callmejamie** [comment]
Ok.. thanks.. will see how i can work around it

**Comment by plamen-peshev** [comment]
See "Text overflow with custom binding" section in [this ](https://balkangraph.com/OrgChartJS/Docs/TextOverflow) help article

It is implemented in the latest version
