### ISSUE TITLE
Adding node below a collapsed node

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#225]
If I add a node by using the add method and the parent node of the newly added node is collapsed, the newly added node is shown below the collapsed node. It is the only node, that is shown, even if there are other node below the parent node.

Please find the attached screenshots

I'm starting with four node below the parent node:
![step1](https://user-images.githubusercontent.com/55696440/65697267-ee4a7600-e07a-11e9-9e5a-4b023d27d2b4.png)

I'm collapsing the node:
![step2](https://user-images.githubusercontent.com/55696440/65697368-19cd6080-e07b-11e9-838b-06a4bad53792.png)

I'm adding a new node below the collapsed node an it is shown exclusively. That is a bug in my opinion:
![step3](https://user-images.githubusercontent.com/55696440/65697407-2b166d00-e07b-11e9-89dc-259fa3b97e28.png)

After expanding, all five nodes are shown:
![step4](https://user-images.githubusercontent.com/55696440/65697520-5bf6a200-e07b-11e9-9def-8ebd890860dc.png)

**Comment by plamen-peshev** [comment]
Correct the new node is expanded by design

Tell me if it is a show stopper for you

**Comment by sks4u** [comment]
Sadly, this is a showstopper for us. In our application, the user filters the data source outside of the orgchart. Therefore, we change it programmatically very often. In this case, this behavior misleads this user. 
The needed behavior would be that a collapsed node remains without any children, when I add a node below it.

**Comment by plamen-peshev** [comment]
you can use on add event handler

```
    chart.on("add", function(sender, newNode){
    	sender.add(newNode);
      sender.collapse(newNode.pid, [newNode.id])
  		return false;
    });
```


See https://jsfiddle.net/BALKANGraph/hbwe3Lzc/
