### ISSUE TITLE
Dynamic height of nodes

### ISSUE THREAD

**Issue by grishamjindal** [BALKANGraph/OrgChartJS#23]
Right now, every node has the same height. Is it possible to have a dynamic height of each node based on the content? 

<img width="520" alt="screen shot 2019-03-04 at 3 47 54 am" src="https://user-images.githubusercontent.com/5462773/53702796-de461d00-3e30-11e9-876b-a3769e89636f.png">
Something like this.

**Comment by BALKANGraph** [comment]
It The current version does not support requested functionality

**Comment by grishamjindal** [comment]
Can it be possible in any of the future versions or maybe a workaround? 

We are already using this OrgChart and are planning to continue with it. Tried all sorts of hacks/workaround on our end but nothing seems to work. 

Any kind of help would be much appreciated.

**Comment by BALKANGraph** [comment]
We will implement this feature in one of our following release

**Comment by Dunleavy-Aaron** [comment]
I managed to achieve this using 3 different template heights and tags to switch between them.

**Comment by BALKANGraph** [comment]
Amazing, thank you for sharing

May be this is a kind of workaround until we implement dynamic height/width (elastic nodes)

**Comment by ZornitsaSerbezova** [comment]
You can use this example: https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/ListsInNodes

**Comment by ZornitsaSerbezova** [comment]
We also created this demo: https://balkangraph.com/OrgChartJS-Demos/DynamicHeight
I'll close this issue. Please feel free to reopen it if needed.
