### ISSUE TITLE
Mixed Mode Line Draw Problem wir Children without connected Elements

### ISSUE THREAD

**Issue by hdbrinkmann** [BALKANGraph/OrgChartJS#230]
As you can see in the attached PNGs, the "mixed" Mode does not draw the line between Lüking and "UNBESETZT" (at the very right) correctly. In Tree Mode it works fine.
 
![Mixed Mode](https://user-images.githubusercontent.com/36363606/66216069-0ea2b200-e6c5-11e9-87d0-27395687faf5.png)
![Tree Mode](https://user-images.githubusercontent.com/36363606/66216070-0ea2b200-e6c5-11e9-8dec-6b8f7da71135.png)

**Comment by hdbrinkmann** [comment]
Please note that the red element does not have "children" while all other have.

**Comment by ZornitsaSerbezova** [comment]
Can you share your code?
It doesn't look this way in mine: 
https://jsfiddle.net/BALKANGraph/tyd08rum/
