### ISSUE TITLE
tags for grouping and tags for change color node

### ISSUE THREAD

**Issue by alessandronigro** [BALKANGraph/OrgChartJS#231]
Hi,
if I use the tags field for the group, I can't even use it to change color to specific nodes.
The values ​​of the groups in the tags field are overwritten.

for (var i = 0; i < nodes.length ; i++) {
                        var node = nodes[i];
                       
                        var d1 = new Date('01-01-1900');
                        var d2 = new Date();
                        if (node.nato_il != '' && node.nato_il != null)
                            d1 = new Date(node.nato_il.split("/").reverse().join("-"));

                        if ((d2.getFullYear() - d1.getFullYear()) < 18) { 
                        node.tags = ['nato_il-0'];
                    }
                            if (node.ricorrente == 1)
                                node.tags = ['ricorrente-' + node.ricorrente];

                            if (((d2.getFullYear() - d1.getFullYear()) < 18) && node.ricorrente == 1)
                                   node.tags = ['ricorrente_minorenne-0'];

                    }        
Regards

**Comment by plamen-peshev** [comment]
What you ant to achieve?

**Comment by alessandronigro** [comment]
Hi Plamen,
I resolved in this weekend :), I've seen that tags being an array can have
multiple values
tags = ['group tag', 'specific node tag'], so I could get the desired
result.

Regards Alessandro

Il giorno lun 7 ott 2019 alle ore 08:50 Plamen Peshev <
notifications@github.com> ha scritto:
