### ISSUE TITLE
Org Chart-Cannot set property 'innerHTML' of null

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#238]
Hi Team,

I am using Balkan Graphs ,Org Chart. I am getting the below issue .
I debugged the code and the line "document.getElementById("bg-tests");" is coming as null.
Could you suggest what could be the root cause?if possible i can schedule a zoom meeting,and i can show this.
To Give Additional Information , I need to Render the chart on Add and Edit,These are two different flows.I am creating single object instance of org chart.

core.js:15713 ERROR TypeError: Cannot set property 'innerHTML' of null
    at Function.OrgChart._wrapText (orgchart.js:1)
    at Object.node (orgchart.js:1)
    at orgchart.js:1
    at orgchart.js:1
    at orgchart.js:1
    at Object.OrgChart.local._walk (orgchart.js:1)
    at OrgChart.server._read (orgchart.js:1)
    at OrgChart.server.read (orgchart.js:1)
    at OrgChart._draw (orgchart.js:1)
    at OrgChart.load (orgchart.js:1)

**Comment by plamen-peshev** [comment]
is it possible to create a demo in jsfiddle?

**Comment by pavandeekshitha** [comment]
Hi Plemen,


I have one question on sorting . Can we do sorting dynamically . I mean conditionally turn on and off Sorting?.
We have a requirement wherein we should not have default sorting , but on a button click the sort should be On and when a new node is added to the chart the sort should be turned off.
Please suggest

Thanks
Pavan

**Comment by pavandeekshitha** [comment]
Hi Plemen,

Do you have any update on this?

Thanks
Pavan

From: Pavan Kumar Gautaraju
Sent: Tuesday, October 15, 2019 7:25 PM
To: 'BALKANGraph/OrgChartJS'; BALKANGraph/OrgChartJS
Cc: Author
Subject: RE: [BALKANGraph/OrgChartJS] Org Chart-Cannot set property 'innerHTML' of null (#238)

Hi Plemen,


I have one question on sorting . Can we do sorting dynamically . I mean conditionally turn on and off Sorting?.
We have a requirement wherein we should not have default sorting , but on a button click the sort should be On and when a new node is added to the chart the sort should be turned off.
Please suggest

Thanks
Pavan

**Comment by plamen-peshev** [comment]
you can use orderBy option 

var onButtonClick = function(){
  chart.config.orderBy = ...;
  chart.draw();
}

**Comment by pavandeekshitha** [comment]
If need to turn it off again conditionally and turn it on .how it can be done?

**Comment by pavandeekshitha** [comment]
Hi Team,

What are the supported formats for Export PDF.In your documentation(https://balkangraph.com/OrgChartJS/Docs/APIReference#exportPDF),
I see A4 is supported.
Could you let me know the other supported formats.

Thanks
Pavan

**Comment by pavandeekshitha** [comment]
Hi Team,

Do you have any update on this?

Thanks
Pavan

From: Pavan Kumar Gautaraju
Sent: Wednesday, October 23, 2019 4:55 PM
To: 'BALKANGraph/OrgChartJS'; BALKANGraph/OrgChartJS
Cc: Author
Subject: RE: [BALKANGraph/OrgChartJS] Org Chart-Cannot set property 'innerHTML' of null (#238)

Hi Team,

What are the supported formats for Export PDF.In your documentation(https://balkangraph.com/OrgChartJS/Docs/APIReference#exportPDF),
I see A4 is supported.
Could you let me know the other supported formats.

Thanks
Pavan

**Comment by ZornitsaSerbezova** [comment]
Hi, Pavan,

Please, use Github or our email: support@balkangraph.com to ask your questions.

Regards,
Zornitsa
