### ISSUE TITLE
Conditional Colors are not shown when exporting

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#239]
I defined some conditional colors like described here:
[https://balkangraph.com/OrgChartJS/Demos/ConditionalColor](url)
When I export the orgchart to PDF, the colors are not visible in the exported PDF

**Comment by plamen-peshev** [comment]
See [this](https://balkangraph.com/OrgChartJS-Demos/ExportStyles) demo 

To add css to the exported document use

```
    chart.on('exportstart', function(sender, args){
        args.content += document.getElementById('myStyles').outerHTML;
    });

```

or
```
    chart.on('exportstart', function(sender, args){
        args.content += '<link src... />';
    });
```
