### ISSUE TITLE
Tags on "root" prevent graph from showing

### ISSUE THREAD

**Issue by michal-hruby** [BALKANGraph/OrgChartJS#240]
If parent node and its children uses the same tag and parent node is not first the result graph will not show.
JSON:
`{
                "nodes":[
                    {
                        "name":"Test person 2",
                        "pid":43,
                        "id":46,
                        "tags":[
                            "Test group"
                        ]
                    },
                    {
                        "name":"Test Person 1",
                        "id":43,
                        "tags":[
                            "Test group"
                        ]
                    }
                ],
                "tags":{
                    "Test group":{
                        "template":"lon",
                        "groupName":"Test group",
                        "group":true
                    }
                }
            }`

**Comment by plamen-peshev** [comment]
Thanks for reporting this issue

Addressed in version 5.1.4

See https://jsfiddle.net/BALKANGraph/hkwrufs2/
