### ISSUE TITLE
Fit() method doesn't work

### ISSUE THREAD

**Issue by perezcoder** [BALKANGraph/OrgChartJS#241]
Hi, I'm trying to adjust the zoom of the chart centered in the view. 

My conf is 
scaleInitial: OrgChart.match.boundary,
orientation:OrgChart.orientation.top_left,
align: OrgChart.CENTER

I tried to call fit() method in the event redraw or manually (ie after adding a node) but i have an error  in console. See the attach

![image](https://user-images.githubusercontent.com/10975448/66561965-dbe03a00-eb5a-11e9-96d0-8dfa3d04a2fb.png)

I try also with 
chart.draw(OrgChart.action.init); 
and fit() method but it still doesn't work.

Can you help me? Thanks

**Comment by plamen-peshev** [comment]
Can you create a demo in jsfiddle where we can see the issue

**Comment by ZornitsaSerbezova** [comment]
Hi, perezcoder, I'll close this issue. If you still need it, feel free to reopen it and share your code, using jsfiddle.
