### ISSUE TITLE
Panel node menu button always visible

### ISSUE THREAD

**Issue by perezcoder** [BALKANGraph/OrgChartJS#242]
Hi again. If the node menu is opened I would that it's always visible. In the attached file you can see what i mean
![Cattura](https://user-images.githubusercontent.com/10975448/66563185-85c0c600-eb5d-11e9-8ba1-31425d6b7820.PNG)

**Comment by plamen-peshev** [comment]
The menu position is improved in the latest version

Download version 5.1.5

**Comment by perezcoder** [comment]
Ok thanks it's perfect
