### ISSUE TITLE
Error when add and remove node

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#243]
When I add a node to the orgchart and directly remove it afterwards, I receive an error:

`        
        this.orgChartControl.add(x);
`
`
        this.orgChartControl.remove(x.id);
`

> Cannot read property 'isChildOfGroup' of undefined
TypeError: Cannot read property 'isChildOfGroup' of undefined
    at OrgChart.remove (http://localhost:4200/scripts.js:1:14642)

If I call a draw in between, everything works fine.

`
        this.orgChartControl.add(x);
`
`
        this.orgChartControl.draw();
`
`
        this.orgChartControl.remove(x.id);
`

**Comment by plamen-peshev** [comment]
you can try

```
this.orgChartControl.add(x);
this.orgChartControl.draw(OrgChart.action.update, null, function(){
   this.orgChartControl.remove(x.id);
});
```
