### ISSUE TITLE
Receive error when searching

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#244]
The error occurs for every search phrase. I tried with ‘xxx’:

> TypeError: Cannot read property 'getAttribute' of null
    at l (http://localhost:4200/scripts.js:1:98545)
    at HTMLInputElement.<anonymous> (http://localhost:4200/scripts.js:1:97589

Please find the attached node data to reproduce the error.
[data.zip](https://github.com/BALKANGraph/OrgChartJS/files/3712490/data.zip)

**Comment by ZornitsaSerbezova** [comment]
Hi, it is working for me with this data. I couldn't reproduce the problem: https://jsfiddle.net/BALKANGraph/bdv4qkaz/

**Comment by sks4u** [comment]
Please find the attached file to reproduce the issue.

[4PLANOrganisation.zip](https://github.com/BALKANGraph/OrgChartJS/files/3818923/4PLANOrganisation.zip)

**Comment by ZornitsaSerbezova** [comment]
It works for me and I don't get any errors.
![image](https://user-images.githubusercontent.com/19305472/68524351-96846900-02ce-11ea-8a78-3ca6c09d57d1.png)
