### ISSUE TITLE
Can't show picture when transferring Pdf

### ISSUE THREAD

**Issue by MuharremT** [BALKANGraph/OrgChartJS#247]
I use Trial Edition OrgChart JS 5.2.0 .  When export pdf, some image not showing in pdf file

![1](https://user-images.githubusercontent.com/56206060/66945447-bf129d80-f057-11e9-9686-a6092c30f30d.png)
.
Thanks,

**Comment by plamen-peshev** [comment]
Make sure that your images are accessible via ajax

To test replace url1 in [this ](https://jsfiddle.net/BALKANGraph/cb27pdvt/) demo

**Comment by MuharremT** [comment]
Thank you for your help and support.
I have tested and Cors Enabled.
Also , Sometimes all pictures showed in pdf document and sometimes some pictures didn't show in pdf document

**Comment by plamen-peshev** [comment]
Can you create an example in jsfiddle where we can see the issue
