### ISSUE TITLE
scroll bar in detail view?

### ISSUE THREAD

**Issue by mi0o** [BALKANGraph/OrgChartJS#248]
Hi with smaller resolution I dont see all fileds in detailed view and there is no scrollbar. is it possible to manage this somehow? 

![image](https://user-images.githubusercontent.com/7822505/66991325-1f412800-f0c8-11e9-9cf6-d9377d949426.png)

tahanks

**Comment by plamen-peshev** [comment]
I have tried to replicate the issue you described 

See https://jsfiddle.net/BALKANGraph/61hcov7z/


![image](https://user-images.githubusercontent.com/49443821/67080367-c774f080-f19d-11e9-9d9a-e9a6e9c0aead.png)

What is different in you case

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue, Feel free to reopen it if needed.
