### ISSUE TITLE
Toolbar İcon change

### ISSUE THREAD

**Issue by MuharremT** [BALKANGraph/OrgChartJS#249]
Hi,
How to change toolbar icon? 
Zoom icon
fit icon
layout icon

Have a nice day

**Comment by plamen-peshev** [comment]
Get the latest version 5.2.2
And change:
 - OrgChart.toolbarUI.expandAllIcon
 - OrgChart.toolbarUI.fitIcon
 - OrgChart.toolbarUI.zoomInIcon
 - OrgChart.toolbarUI.zoomOutIcon
 - OrgChart.toolbarUI.layoutIcon


Clear your browse cache and open https://balkangraph.com/OrgChartJS-Demos/ToolbarIcons

**Comment by MuharremT** [comment]
Thanks.
