### ISSUE TITLE
Angular components as nodes

### ISSUE THREAD

**Issue by notarnet** [BALKANGraph/OrgChartJS#25]
Hi,
I'm trying to integrate your library in our enterprise appllication. This application is written in Angular and we want to use custom angular components as nodes in the graph. Is there a way to do this?

**Comment by Ademking** [comment]
@notarnet same here.. i want to integrated it with angular.. did you find a solution ? Thanks

**Comment by notarnet** [comment]
I tried to insert an angular component inside a svg and is possible:
[Stackblitz example](https://stackblitz.com/edit/angular-component-in-svg)

But I can't use the same technique to customize a BalkanGraph node.

**Comment by Ademking** [comment]
@notarnet thank you again ❤️ if i found anything useful i will share it with you

**Comment by notarnet** [comment]
@BALKANGraph  My company is evaluating to buy this library; is the angular nodes approach possible?

**Comment by BALKANGraph** [comment]
@notarnet We have “Angular” in our todo list and will implement it in one of the following releases. In the meantime you can use OrgChart JS as pure javascript library. [Here ](https://github.com/BALKANGraph/OrgChartJS/issues/42)is our roadmap.

**Comment by ZornitsaSerbezova** [comment]
This may be helpful: https://github.com/BALKANGraph/OrgChartJS/issues/142#issuecomment-516674462

**Comment by ikishanoza** [comment]
any news on node as angular component ? @ZornitsaSerbezova  what u have mentioned in above comment is just to add orgchart in angular app not "node as angular component" .. any news on that ?

**Comment by ZornitsaSerbezova** [comment]
We don't have node as Angular component.

**Comment by ikishanoza** [comment]
any plans in future release ?

**Comment by ZornitsaSerbezova** [comment]
not soon
