### ISSUE TITLE
CSS Customization not reflected in export SVG

### ISSUE THREAD

**Issue by MuharremT** [BALKANGraph/OrgChartJS#250]
Hi,

I applies css customization to my nodes.I changed color of my nodes dynamically , when i am exporting to SVG, the updated style is not getting reflected

have a nice day

**Comment by perezcoder** [comment]
You have to attach the <style> tag into the tag <svg> in the event onexportstart

**Comment by plamen-peshev** [comment]
See [this ](https://balkangraph.com/OrgChartJS-Demos/ExportStyles) demo

you can add the styles in export start event handler

**Comment by perezcoder** [comment]
Also you can try with this:

chart.on('exportstart', function(sender, args){
    var style = '<style>*{padding: 20px}</style>';
    args.content = args.content.replace('</svg>', style + '</svg>');
})

**Comment by MuharremT** [comment]
Your works only export Pdf,
but I export svg file.  I get the above error message , when export svg file
args is null 
![Capture](https://user-images.githubusercontent.com/56206060/67081418-c6dd5980-f19f-11e9-9973-fc2f2a9aab0d.JPG)

**Comment by ZornitsaSerbezova** [comment]
With the latest version the issue is fixed.
