### ISSUE TITLE
Restoring Org Chart View

### ISSUE THREAD

**Issue by bansalr** [BALKANGraph/OrgChartJS#252]
We are displaying an org chart with several levels and about 40-50 nodes. The user can zoom and pan the org chart as needed.

At one point the user can click on a node and navigate to another page. When he clicks back we display the org chart and want to restore the view.

We can restore the zoom level but cannot display the org chart to where the user had panned in. Is there a way we can figure out what node the Org Chart was centered on and call center again?

If not then is there another way to restore the org chart view?

Thank You!

**Comment by plamen-peshev** [comment]
The current version does not support it 

But it sounds like an interesting feature, we will add it in one of the following releases

**Comment by bansalr** [comment]
Ok, thanks. I think all that is needed is a call to get the current node the org chart is centered on.

To restore we can simply call center which is already in the API.

**Comment by bansalr** [comment]
Hi Plamen - Any updates on this?

**Comment by Dunleavy-Aaron** [comment]
This would be great if we could save the state of the chart and reload it once they get back to the page.

**Comment by ZornitsaSerbezova** [comment]
Now you can save state with the latest version (7.5.23):
https://balkangraph.com/OrgChartJS/Docs/APIReference#state

I'll close this issue. Feel free to reopen it or open another one if needed.
