### ISSUE TITLE
Add label to spids and CSS customization

### ISSUE THREAD

**Issue by acaravia** [BALKANGraph/OrgChartJS#253]
Is there a way to add a label to spids link like you would to regular link via linkBinding? Additionally, can you change the link label location and other attributes (i.e. font, color)?

**Comment by acaravia** [comment]
Also running into an issue of where spids overlay on each other and so unable to correctly discern which nodes they actually link to (see example below). It appears all the top nodes are linked across the next level when only some are This kind of goes along with my initial question, can we customize spids dynamically.  

Example 1 (All Expanded)
![image](https://user-images.githubusercontent.com/16963221/67454487-19bf7280-f5df-11e9-8bc0-2c2dc22b8209.png)

Example 2 (
![image](https://user-images.githubusercontent.com/16963221/67454609-ae29d500-f5df-11e9-8e45-4a6fefbc19f4.png)

**Comment by ZornitsaSerbezova** [comment]
You can try with **Slinks** now:
https://balkangraph.com/OrgChartJS/Docs/Slink
