### ISSUE TITLE
Add multiple nodes at once

### ISSUE THREAD

**Issue by poploock** [BALKANGraph/OrgChartJS#254]
hi
when i add multiple node in for with addNode method into child node, chart is not displayed correctly
[OrgChart-addon.zip](https://github.com/BALKANGraph/OrgChartJS/files/3766846/OrgChart-addon.zip)

**Comment by ZornitsaSerbezova** [comment]
Hi, you need to use **add** method to add the nodes and then draw to draw the chart.
Here is an example:
https://jsfiddle.net/BALKANGraph/wkhd9f43/
