### ISSUE TITLE
Horizontal + vertical layout

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#255]
Hi Team,
Is it possible to create the attached chart. I have highlighted the problem section 
If this is not possible can user edit the exported pdf and arrange the layout ?
Please suggest
Thanks
Pavan
![hor_vert](https://user-images.githubusercontent.com/38096749/67573952-25ce4000-f757-11e9-8e18-fca523167606.png)

**Comment by ZornitsaSerbezova** [comment]
Hi Pavan,
You could export the vertical part with  layout: OrgChart.treeRightOffset and then change the layout and export the horizontal part on another page. 
It is not possible to rearrange the nodes in the PDF.

**Comment by chloesun** [comment]
I'm facing the same issue, is this possible to assign a different layout to a group/tag?

**Comment by ZornitsaSerbezova** [comment]
Layout is assigned to the whole OrgChart.

**Comment by ZornitsaSerbezova** [comment]
https://github.com/BALKANGraph/OrgChartJS/releases/tag/7.6.12
