### ISSUE TITLE
unable to create Custom link svg

### ISSUE THREAD

**Issue by bharathmurthy** [BALKANGraph/OrgChartJS#256]
Hi There,
I have been working with your library for past month now and its been a great experience. We are considering on buying the license soon! I have been trying to create a custom link to look something like this
![image](https://user-images.githubusercontent.com/11144479/67663312-501f3800-f9b9-11e9-83a4-52ea5b53cd44.png)
But I'm not able to tweak the bezier curve in d="M{xa},{ya} C{xb},{yb} {xc},{yc} {xd},{yd}" how can I manipulate/add to xa ya etc. to manipulate the bezier curve ?

**Comment by ZornitsaSerbezova** [comment]
Hi **bharathmurthy**,
What exactly do you want to create? The balloon or the curved line?

**Comment by bharathmurthy** [comment]
Hi @ZornitsaSerbezova ,
Thanks for asking. Not the Balloon just the curved line.

**Comment by ZornitsaSerbezova** [comment]
Hi bharathmurthy,
We don't support such type of curved lines, but will add it in our to do list for feature releases.
