### ISSUE TITLE
Change cursor while dragging

### ISSUE THREAD

**Issue by mrossini109** [BALKANGraph/OrgChartJS#259]
Hi all,

i am looking for a way to change my cursor during the drag&drop event.

So, i've the "drop" event like this:

```javascript
chart.on('drop', function (sender, draggedNodeId, destinationId) {
  if (iNeedToDisableDragNdrop) {
     document.body.style.cursor = 'no-drop';
     return false;
  }
});
```

but my cursor wont change DURING the operation, just after i release the click. In addition i've no idea how to return to style "auto" with this method.

Thanks in advance,
Marco.

**Comment by ZornitsaSerbezova** [comment]
Hi,

We have added .drag-over class that may be helpfull for you: https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/DragDropOver

**Comment by ZornitsaPesheva** [comment]
I'll close this issue as it looks solved.
