### ISSUE TITLE
Add option to deactivate bouncing

### ISSUE THREAD

**Issue by wimpie3** [BALKANGraph/OrgChartJS#26]
On a very large chart, the bouncing effect when you drag a chart off screen can be unpleasant because the chart returns too far to the center. Please add an option to deactivate the bounce.

**Comment by BALKANGraph** [comment]
Other client requested an option to disable bounce effect so we will implement it in the next version

**Comment by ZornitsaSerbezova** [comment]
It was implemented

See https://balkangraph.com/OrgChartJS/Docs/APIReference#sticky

```
    var chart = new OrgChart(document.getElementById("tree"), {
       sticky: false
        ...
    });
```
