### ISSUE TITLE
Adding a feature

### ISSUE THREAD

**Issue by GrandDelta** [BALKANGraph/OrgChartJS#262]
Hello, I have a professional liscence that I bought and I greatly appreciate your framework. I have been working on it for a few months and I have a feature that is not present on your frameworks that blocks me for my work. It is about being able to add people to a person who is "assistant" and to be able to unfold as for the classic people. Would it be possible to add this feature?

You can contact me at the email address: tino.feraud@granddelta.fr

Regards,

Lionel FRANCOIS,

Habitat of the Grand Delta, 3 rue Martin Luther King, 84000, Avignon

**Comment by plamen-peshev** [comment]
I have tried to add node under assistant node and it works for me 

Tested [here ](https://balkangraph.com/OrgChartJS/Demos/Assistant)



![image](https://user-images.githubusercontent.com/49443821/69048824-1a450080-0a07-11ea-8180-cfeefb0d36f8.png)
