### ISSUE TITLE
JavaScript error when resizing window after destroying the chart

### ISSUE THREAD

**Issue by mpschaeuble** [BALKANGraph/OrgChartJS#263]
After destroying a chart using the destroy method, the following javascript error occurs when the browser window is resized:
`
OrgChart.js:1 Uncaught TypeError: Cannot read property 'getAttribute' of null
    at OrgChart._resizeHandler (OrgChart.js:1)
    at r (OrgChart.js:1)
    at n (OrgChart.js:1)
`
I suppose the resize handler is not unregistered when destroying the chart.

I created a small jsfiddle to reproduce the issue: https://jsfiddle.net/tqe9vfao/

**Comment by plamen-peshev** [comment]
We have fixed the issue in the latest version  6.0.5
