### ISSUE TITLE
Hover on Node to see extra details

### ISSUE THREAD

**Issue by v1sp** [BALKANGraph/OrgChartJS#264]
Hi
We have a professional License.
How do I show extra details in a POPUP when I hover on a particular node? 
For ex On the node I am showing Username/Photo/ID and when I hover on this node - I should show a small POPUP showing his other details like Phone/Address/Department.. etc -  Something like below

![a](https://user-images.githubusercontent.com/8832982/68580676-c36f8200-046e-11ea-914c-6365a808bfaa.png)

Please suggest.

Regards,
Veerendra.

**Comment by plamen-peshev** [comment]
See https://balkangraph.com/OrgChartJS-Demos/Tooltip
![image](https://user-images.githubusercontent.com/49443821/69048641-a3a80300-0a06-11ea-8b05-14a9e09c02c1.png)
