### ISSUE TITLE
Customize default link and its text

### ISSUE THREAD

**Issue by khalilTN** [BALKANGraph/OrgChartJS#265]
Hi,

Is it possible to customize link text (Size, color, ...)
When a parent has only one child, the link text is on top of the link, so it become unclear. (please see the picture)
![68582252-9759fe00-047a-11ea-9e5e-52b5084454a4](https://user-images.githubusercontent.com/9549132/68582331-c3757f00-047a-11ea-86ba-fb5182a430b2.png)

How can i deal with this ?

Thanks

**Comment by Mrcl1450** [comment]
You can with a custom template
`BALKANGraph.slinkTemplates.customTemplate.label =
                '<text dominant-baseline="middle" fill="#000000" font-size="22" style="font-family: Calibri,Candara,Segoe,Segoe UI,Optima,Arial,sans-serif;" alignment-baseline="middle" text-anchor="end" x="{x}" y="{y}">{val}</text>';
            BALKANGraph.slinkTemplates.customTemplate.labelPosition = 'end';
            BALKANGraph.slinkTemplates.customTemplate.link =
                '<path stroke-linejoin="round" stroke="#000000" stroke-width="1px" fill="none" d="{d}" marker-end="url(#arrowSlink)" />';
            BALKANGraph.slinkTemplates.customTemplate.defs =
                '<marker id="arrowSlink" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse">' +
                    '<path fill="#000000" d="M 0 0 L 10 5 L 0 10 z" />' +
                '</marker>';`

**Comment by khalilTN** [comment]
Thanks, it's resolved
