### ISSUE TITLE
Tag fill when using myTemplate

### ISSUE THREAD

**Issue by limpkinm** [BALKANGraph/OrgChartJS#266]
Hi,

I am playing with creating a custom template and have come up with the following code so far, as per your website, what I want to now do is change the fill colour of the rectangle for the ana template.

Please can you advise what the syntax is for changing the fill colour of the rectangle/node?  As you can see the text colour I have figured out, as per below…

OrgChart.templates.myTemplate = Object.assign({}, OrgChart.templates.ana);

OrgChart.templates.myTemplate.field_0 = '<text class="field_0"  style="font-size: 20px;" fill="#141011" x="125" y="25" text-anchor="middle">{val}</text>';

Many thanks

Mark

**Comment by ZornitsaSerbezova** [comment]
You can change the fill color using css:

[node-id] rect {
    fill: #016e25;
}

https://balkangraph.com/OrgChartJS/Docs/CSSCustomization

**Comment by limpkinm** [comment]
Hi,

Thanks for your reply, however I am using Groups and therefore using this logic below changes both the groups and all nodes within the group.

I am also using a custom template, all I simply want to do is have some nodes one colour and other nodes a different, within groups.

I am able to do so with the fields by using the following code:

OrgChart.templates.myTemplate.field_0 = '<text class="field_0"  style="font-size: 20px;" fill="#141011" x="125" y="25" text-anchor="middle">{val}</text>';

I now want to apply the same logic to nodes within this template, I have tried something like this:

OrgChart.templates.myTemplate.node  = '<rect fill="#016e25"></rect>';

But this fails?  Can you advise on how I change the fill colour for nodes within my custom template whilst also considering that fact that I am using Groups and am also using the ana template for all other nodes.

Thanks

Mark

**Comment by ZornitsaSerbezova** [comment]
Hi Mark,
Here is an example for you:
OrgChart.templates.myTemplate.node = 
                '<rect fill="red" x="0" y="0" height="120" width="250" stroke-width="1" stroke="#aeaeae" rx="5" ry="5"></rect>';
