### ISSUE TITLE
Apply a specific layout for a sub tree

### ISSUE THREAD

**Issue by khalilTN** [BALKANGraph/OrgChartJS#268]
Hi,

Is it possible to apply a specific layout for sub tree.
Actually my layout is "TreeLeftOffset".
When a node have only one child, i want to have a normal vertical link between them.
Please see the image below
![image](https://user-images.githubusercontent.com/9549132/68667963-73b0b980-0547-11ea-9cfd-9231c8fb63df.png)

Thanks in advance

**Comment by khalilTN** [comment]
Applying layout to sub trees is very helpful, so that we may have many layouts in the same organigram

**Comment by plamen-peshev** [comment]
The current version does not support requested functionality

I have added you request in our todo list
