### ISSUE TITLE
slinks can't work correctly 

### ISSUE THREAD

**Issue by zxforben** [BALKANGraph/OrgChartJS#269]
![image](https://user-images.githubusercontent.com/5674472/68819377-ce225500-06c2-11ea-809b-8eef205ce18f.png)

![image](https://user-images.githubusercontent.com/5674472/68819421-e5614280-06c2-11ea-9676-5919de04bb74.png)
![image](https://user-images.githubusercontent.com/5674472/68819451-fdd15d00-06c2-11ea-986e-bf26a7ee6e0d.png)

**Comment by zxforben** [comment]
[dist2.zip](https://github.com/BALKANGraph/OrgChartJS/files/3844225/dist2.zip)

**Comment by plamen-peshev** [comment]
What exactly is the issue
In the file you sent, dist2.zip there are many html files
Please provide step by step instructions on how to reproduce the problem

**Comment by zxforben** [comment]
sorry , please use the pwc.html as the issue reproduced. I have created three clinks, but there are only 2 link displayed. and the direction is not correct. node 55 should point to 86 and 88, but as now  it is only point to 88.

**Comment by plamen-peshev** [comment]
there is a typo in you script

replace              
{"**form**": 87, "to": 49, "label": "20%", "template": "myTemplate1"}

with 
{"**form**": 87, "to": 49, "label": "20%", "template": "myTemplate1"}


you can change the direction with template, see yellow slink https://balkangraph.com/OrgChartJS/Demos/MultipleParents

**Comment by zxforben** [comment]
okay , I will try later.

**Comment by zxforben** [comment]
I have a question about direction. 

I used same from and different to , and I used the same template,  why the direction is not the same from my from point.

let me take the above as example:

`        slinks: [
            {"from": 55, "to": 86, "label": "a", "template": "myTemplate1"},
            {"from": 55, "to": 88, "label": "b", "template": "myTemplate1"},
            {"from": 87, "to": 49, "label": "20%", "template": "myTemplate1"}
        ]`

The from is same 55 and the template is same myTemplate, but the direction is not the same?

I think it is should the same direction . Could you help to clarify this?

**Comment by zxforben** [comment]
![image](https://user-images.githubusercontent.com/5674472/69401788-f51aff80-0d30-11ea-8848-078bf79449ae.png)

**Comment by zxforben** [comment]
@plamen-peshev  please find the example also on above page.

**Comment by ZornitsaSerbezova** [comment]
Hi zxforben, 
Could you, please, post a link with this example in jsfiddle?

**Comment by zxforben** [comment]
[https://jsfiddle.net/zxforben/a62kxd7g/](url)

**Comment by zxforben** [comment]
@ZornitsaSerbezova update the example

**Comment by zxforben** [comment]
![image](https://user-images.githubusercontent.com/5674472/69405298-3c59be00-0d3a-11ea-90c1-fe356903431e.png)
same from same template , why not from the same node?

**Comment by zxforben** [comment]
why the arrow for from 1 to 0 is point to 0 , it is point 1. This is incorrect.

**Comment by ZornitsaSerbezova** [comment]
HI zxforben,
At this point you need to use different templates for different directions. We will address this issue for future updates.

**Comment by zxforben** [comment]
@ZornitsaSerbezova but how can I know use which template? Because it is no rule for that. Please advise.

**Comment by plamen-peshev** [comment]
The issue has been addressed 

Get version 6.0.8

**Comment by zxforben** [comment]
thanks for your help
