### ISSUE TITLE
Make boxes draggable

### ISSUE THREAD

**Issue by wimpie3** [BALKANGraph/OrgChartJS#27]
The chart can be dragged on the screen by clicking on the background and dragging the chart around. However, this does not work when you start dragging on a box instead of on the background. This can be very disturbing when you are zoomed in on a chart.

**Comment by BALKANGraph** [comment]
You can disable node drag&drop by setting **enableDragDrop** to **false**

**Comment by wimpie3** [comment]
I NEED drag and drop, so I don't want to disable it. I ALSO want to use drag & drop when people start dragging on boxes instead of the background.

**Comment by BALKANGraph** [comment]
Sorry but is not clear for me, what you'd expect to happen when you drag a node?

**Comment by wimpie3** [comment]
When you put your mouse on the background and drag, the entire graph moves. That is perfect. However, when you drag your mouse on a node/box, the graph does not move at all. When you're zoomed in completely and you see nothing but nodes/boxes on the screen, and drag your mouse, there is no way to move the entire graph. The drag function does not work on boxes.

**Comment by BALKANGraph** [comment]
What you'd expect to happen when you drag a node? Are you expecting when you drag a node to drag the chart as well?

**Comment by wimpie3** [comment]
Exactly.

**Comment by BALKANGraph** [comment]
Yes but in that case you will never reach the target node on node drag&drop, the chart will move

**Comment by wimpie3** [comment]
'reach the target node'? What do you mean? You can click on the +/- to open the target node, right? A click is not the same as a drag.

**Comment by ZornitsaSerbezova** [comment]
Hi wimpie3,

We have added a pan option:
`nodeMouseClick: OrgChart.action.pan`

Here is an example for you: 
https://jsfiddle.net/BALKANGraph/yqm4duhe/
