### ISSUE TITLE
Auto Height an Width for Node

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#270]
Hi Team,

Any Update on whether the Nodes can be set to auto width & height.The Elastic Nodes

Thanks
Pavan

**Comment by ZornitsaSerbezova** [comment]
Hi Pavan,
We are working on this option and it will be added to one of the next releases,

**Comment by pushpender98** [comment]
Is this done?

**Comment by ZornitsaSerbezova** [comment]
We have created demo for auto height: https://balkangraph.com/OrgChartJS-Demos/DynamicHeight

**Comment by ZornitsaSerbezova** [comment]
width: https://balkangraph.com/OrgChartJS-Demos/DynamicWidth
