### ISSUE TITLE
One row of data in the group

### ISSUE THREAD

**Issue by 545867454** [BALKANGraph/OrgChartJS#272]
Hi Team!
       I want a row in the data to display a row，What properties need to be set?Where to set?

![2JP26YW25O3C YF5J)VUQR](https://user-images.githubusercontent.com/25147732/69114847-8dab4880-0ac1-11ea-8834-e8150228ce92.png)

**Comment by ZornitsaSerbezova** [comment]
We have added this functionality in our to do list.

**Comment by plamen-peshev** [comment]
Implemented in version 6.0.6

if you are using group_grey template set columns=1 and the group will have only one column


`    OrgChart.templates.group_grey.columns = 1;
   `

https://balkangraph.com/OrgChartJS/Demos/Grouping

**Comment by 545867454** [comment]
thank you very much

**Comment by 545867454** [comment]
Thank you,But I still have a question。How to cancel the grouped retract button?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Plamen Peshev"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月21日(星期四) 晚上8:09
收件人:&nbsp;"BALKANGraph/OrgChartJS"<OrgChartJS@noreply.github.com&gt;;
抄送:&nbsp;"飞云1∮"<545867454@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题： &nbsp;回复：[BALKANGraph / OrgChartJS]组中的一行数据（＃272）




在版本6.0.6中实现
 
如果您使用的是group_grey模板，请设置column = 1，并且该组将只有一列
 
   OrgChart.templates.group_grey.columns = 1;
 
https://balkangraph.com/OrgChartJS/Demos/Grouping
  
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by 545867454** [comment]
Can I provide a property document for setting grouping?

**Comment by 545867454** [comment]
Can you provide a properties file to set up groupings?

**Comment by ZornitsaSerbezova** [comment]
These are the group properties:
 Devs: {
                group: true,
                groupName: "Dev Team",
                groupState: OrgChart.EXPAND,
                template: "group_grey"
}

You can hide the grouped retract button with CSS.

**Comment by 545867454** [comment]
![image](https://user-images.githubusercontent.com/25147732/69609857-76da9800-1065-11ea-82fb-d0dd73e53901.png)
Groups and buttons are both g tags. Based on what css gets?
I tried jq $ ("polyline"). Parent (). Css ("display", "none"); to make the buttons disappear, but the buttons will still be displayed after the organization chart is zoomed

**Comment by ZornitsaSerbezova** [comment]
Hi,
You can use this selector:

```
[control-maxmin-id]{
  display: none;
}
```

You could also hide the button this way:

```
OrgChart.MINIMIZE = "";
OrgChart.MAXIMIZE = "";
```

Regards,
Zornitsa

**Comment by 545867454** [comment]
OK，
Thank you
