### ISSUE TITLE
font-styles

### ISSUE THREAD

**Issue by Kingziqiang** [BALKANGraph/OrgChartJS#274]
How to make the width and height of the node adaptive according to the font, how to make the Chinese font vertical display

**Comment by ZornitsaSerbezova** [comment]
Hi, Kingziqiang, 
We have added the functionality of auto width and height of the node to our to do list for one of the feature releases.

**Comment by Kingziqiang** [comment]
Hi, ZornitsaSerbezova，
If too many words overflow, how to deal with the overflow problem？

Thank you for your help

**Comment by ZornitsaSerbezova** [comment]
Here is the documentation for Text Overflow:
https://balkangraph.com/OrgChartJS/Docs/TextOverflow
