### ISSUE TITLE
How aling line from group to node

### ISSUE THREAD

**Issue by Tonix21ab** [BALKANGraph/OrgChartJS#275]
Hi, 
I've got an issue about using a group and a node; the problem is that the connection between the two is not linear as shown in the img.
This happen just between group-node, not between node-node.
How can I align it?
![Cattura](https://user-images.githubusercontent.com/34035441/69224432-d6740780-0b7c-11ea-8262-4b511e4bd3fc.PNG)

**Comment by plamen-peshev** [comment]
Can you create a demo in jsfiddle were we can see the issue

**Comment by ZornitsaSerbezova** [comment]
Tonix21ab, did you manage to fix this issue? Can I close it?
