### ISSUE TITLE
How to implement load on demand

### ISSUE THREAD

**Issue by Kingziqiang** [BALKANGraph/OrgChartJS#276]
Hi, ZornitsaSerbezova,
How do you dynamically load child nodes when the organizational tree is very large. or 
is there a way where i can pass nodeId and redraw the chart only showing nodeId as a parent and all child below him?

thank you @ZornitsaSerbezova

**Comment by ZornitsaSerbezova** [comment]
Hi, Kingziqiang

OrgChart JS works well with thousands of nodes without load on demand, adding load on demand means adding extra complexity to your project.

You can see in this demo how to set node as a root:
https://balkangraph.com/OrgChartJS-Demos/SetNodeAsRoot

Regards,
Zornitsa
