### ISSUE TITLE
Align text with links

### ISSUE THREAD

**Issue by Mrcl1450** [BALKANGraph/OrgChartJS#278]
Hello,
I want to suggest making use of textPath for link_field_0 and labels if possible so the text can be aligned and rotate depending on links.

This would help a lot with diagonal links.

**Comment by plamen-peshev** [comment]
Can you please send an image with the label alignments

**Comment by Mrcl1450** [comment]
Here's a example 
![image](https://user-images.githubusercontent.com/8568899/69615223-6fe36380-102c-11ea-9a0a-faf7a6031b21.png)

**Comment by ZornitsaSerbezova** [comment]
Hi Mrcl1450,
Is this what you want?
![Untitled](https://user-images.githubusercontent.com/19305472/69793478-339d3800-11d1-11ea-9a87-726d8b268111.png)

**Comment by Mrcl1450** [comment]
Hi, yes that would help.

**Comment by ZornitsaSerbezova** [comment]
Here we have created a demo for particular link label alignment: https://balkangraph.com/OrgChartJS-Demos/ClinkLabel

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue as it is old and inactive. Feel free to reopen it, if needed.
