### ISSUE TITLE
Information from field with foreignobject is not export

### ISSUE THREAD

**Issue by Dunleavy-Aaron** [BALKANGraph/OrgChartJS#28]
Hi,
I am having an issue with exporting charts with foreignobject  data.

https://jsfiddle.net/aaron_dunleavy/7qmkztb2/7/

Thanks,

**Comment by BALKANGraph** [comment]
I have tried to replicate the issue to no avail

Can you download the latest version and try again

If you experience the same issue with the latest version, please provide your OrgChart JS configuration and the foreignobject

**Comment by Dunleavy-Aaron** [comment]
Hi I will try. Did the fiddle not show the same result?

Asron

**Comment by ZornitsaSerbezova** [comment]
Fiddle is working okay.
