### ISSUE TITLE
draggable clink,slink to another node

### ISSUE THREAD

**Issue by lodossDev** [BALKANGraph/OrgChartJS#280]
is it possible to show a demo that you can drag a clink/slink from one node to another?

**Comment by ZornitsaSerbezova** [comment]
Hi, lodossDev,

We have added a demo for you:
https://balkangraph.com/OrgChartJS-Demos/DraggableClinks

**Comment by lodossDev** [comment]
Hi guys, thanks for the demo, I am also wondering if something like in this video can be be done as a native feature in your product:

https://www.youtube.com/watch?v=173YD4o8-Fo

So more around the nice drag and drop around relationship links show a nice visualisation of the path between the nodes.

**Comment by ZornitsaPesheva** [comment]
implemented Can't open the youtube video, but should be the same
https://balkan.app/OrgChartJS/Docs/Menus#circle
