### ISSUE TITLE
Line Issue

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#281]
![Line_issue](https://user-images.githubusercontent.com/38096749/69607611-95339a00-104b-11ea-9c9f-48830255ad97.png)
Hi Team,

When ever the chart has multiple assistants like the attached. The Connector from the Parent to theChild Node is slightly bending.
Please find the attachment. I have highlighted the issue.
Please let me know if you have any questions

Thanks
Pavan

**Comment by ZornitsaSerbezova** [comment]
Hi, pavandeekshitha,
As I can see, you have a child under your assistant. OrgChart JS do not support officially child under assistant, but it may work in some cases.

Regards,
Zornitsa
