### ISSUE TITLE
group node as a container and relate child nodes to a specific parent node in the group

### ISSUE THREAD

**Issue by lodossDev** [BALKANGraph/OrgChartJS#282]
Hi is it possible to group nodes as a container? So the idea is that, you can have multiple people in the group, but any childs are directly related to the parent in the group node, so something like this:

![image](https://user-images.githubusercontent.com/1792489/69667549-1ad43b80-1086-11ea-985a-b4c454d7cfb0.png)

The idea is, child nodes are directly relating to the individual in the parent node, which is in a group.

**Comment by ZornitsaSerbezova** [comment]
Hi, lodossDev,
At this stage we do not support such option.

Regards,
Zornitsa

**Comment by lodossDev** [comment]
Hi, thanks for the feedback I am wondering if you guys would consider this as a feature for the roadmap or something?

**Comment by ZornitsaSerbezova** [comment]
we have added this feature request to our consideration list

**Comment by ZornitsaSerbezova** [comment]
Now we have complete new implementation of [grous](https://balkangraph.com/OrgChartJS/Demos/Grouping) with much more functionalities. I'll close this isuue. Fill free to reopen it if needed,

**Comment by MuharremTopuz** [comment]
Hi,
Can we do this now?
Can you share sample code.
Regards,
Thanks for your help.
