### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by mi0o** [BALKANGraph/OrgChartJS#284]
Hello,
I notice that something has changed in export. 
in the main menu use export to PNG like this > 	menu: {png: { text: "Export PNG" }},

But few days ago it exported exactly what I have had on the screen. Now it export default structure - what I see when I refresh the web.  First line for example. why?

**Comment by mi0o** [comment]
Hello,
any ideas?

**Comment by ZornitsaSerbezova** [comment]
The issue is addressed in the new version.
