### ISSUE TITLE
Node Menus with no item should not show nodeMenuButton

### ISSUE THREAD

**Issue by cheng93** [BALKANGraph/OrgChartJS#285]
https://jsfiddle.net/3cjhwofe/1/

Example is modified version of one found at https://balkangraph.com/OrgChartJS/Docs/NodeMenuItem with tags

In my case we have three scenarios
* Default config which has `nodeMenu: null`
  * which I expect would not show `nodeMenuButton` for all nodes unless specified
* `overrideMenu` tag
  * This should show `nodeMenuButton` for nodes with that tag
    * **I think this is causing the `nodeMenuButton` to be shown on all tags**
* A last attempt with `noMenu` tag, which has `nodeMenu: null`

**Comment by ZornitsaSerbezova** [comment]
Hi cheng93, 

You can use this CSS to hide the menu:

```
.noMenu [control-node-menu-id] circle {
       visibility: hidden;
}
```

**Comment by cheng93** [comment]
css worked thanks.

Could not use template as node already had a template.

Unless there is an ability to compose templates together? @ZornitsaSerbezova

**Comment by ZornitsaSerbezova** [comment]
> 
> Unless there is an ability to compose templates together? @ZornitsaSerbezova

**Comment by cheng93** [comment]
@ZornitsaSerbezova 

What I meant was we had something like
```json
{
  "tags": {
    "a": { "template": "aTemplate" },
    "b": { "template": "bTemplate"}
  },
  "nodes": [ { "id": 1, "tags": [ "a", "b" ] } ]
}

**Comment by ZornitsaSerbezova** [comment]
No, click on the **Edit in JSfiddle** button here and see the code:

https://balkangraph.com/OrgChartJS-Demos/RemoveNodeMenu

**Comment by cheng93** [comment]
https://jsfiddle.net/yg7x8vtj/

Here is an example

composing two of our own custom templates does not work
  * notice how `Glenn Bell` has `["noMenu", "another"]` tags which point to two different templates

None the less, this issue is resolved 😀

**Comment by ZornitsaSerbezova** [comment]
Is it that you are trying to achieve:
https://jsfiddle.net/BALKANGraph/xgwhoa7f/6/

**Comment by cheng93** [comment]
indeed, but that does not feel very nice, the more combinations we want, the more templates we would have to define.

Maybe something for the future
