### ISSUE TITLE
Seperate each SLINKS strokes

### ISSUE THREAD

**Issue by jhongcarlos** [BALKANGraph/OrgChartJS#286]
Hi, I want my slinks to have seperate path so the label won't mix up when I put the labelPosition at 'start'. What I did for an alternative is is set the labelPosition in 'middle'. Can you help me out in here?

I want it to look like this:
![p](https://user-images.githubusercontent.com/40976678/70023936-e277b480-15d3-11ea-92e0-ccfd7329bb9a.png)

What I currently have:
![image](https://user-images.githubusercontent.com/40976678/70023992-fde2bf80-15d3-11ea-95b6-5f95390e249d.png)
(I have to set the orientation to default because if the orientation is left, some labels are missing.

**Comment by jhongcarlos** [comment]
<img width="786" alt="Untitled" src="https://user-images.githubusercontent.com/40976678/70025280-87e05780-15d7-11ea-8581-1ccf506c4759.png">
This is what it looks like when the orientation is left, notice that one label is missing

**Comment by ZornitsaSerbezova** [comment]
can you create demo in jsfiddle

**Comment by jhongcarlos** [comment]
Here
https://jsfiddle.net/u5febxoa/2/

**Comment by jhongcarlos** [comment]
I adjusted the levelSeperation to 50 and this what happened:
![image](https://user-images.githubusercontent.com/40976678/70102746-04c10f00-1674-11ea-8396-d5bf6f6da3ba.png)

**Comment by plamen-peshev** [comment]
Thanks for reporting this issue

It is fixed in the latest version  6.1.91
