### ISSUE TITLE
Https Compatible Report Server

### ISSUE THREAD

**Issue by pavandeekshitha** [BALKANGraph/OrgChartJS#289]
Hi Team,

Could you please give me the Https Compatible report server code ,since i need to host this over https.
The Report Server which i downloaded from https://github.com/BALKANGraph/export-service ,in app.js the code is related to http.
Need this urgently .We are using Premier License

Thanks
Pavan

**Comment by plamen-peshev** [comment]
Now the export service can be used under http and https

Download the latest version of the export-service
