### ISSUE TITLE
In google chrome the zoom is very slow, in firefox works well

### ISSUE THREAD

**Issue by doarsal** [BALKANGraph/OrgChartJS#29]
In google chrome the zoom is very slow, in firefox works well.

With few nodes it works fine, but with 500 the zoom is very slow

**Comment by BALKANGraph** [comment]
Thank you for reporting this issue

Will try to replicate it and eventually fix it

Will keep you updated

**Comment by BALKANGraph** [comment]
The issue has been addressed

**Comment by doarsal** [comment]
The zoom already works excellent, thank you very much, but when zooming down the texts disappear or lose the original format.

http://servidoricam3.com/orgBugs/org1.png
http://servidoricam3.com/orgBugs/org2.png
http://servidoricam3.com/orgBugs/org3.png

**Comment by mpschaeuble** [comment]
Can you please make sure the new release is also accessible via npm? Thanks!

**Comment by BALKANGraph** [comment]
@doarsal please download the latest version from the website

**Comment by BALKANGraph** [comment]
@mpschaeuble now it is the latest version
