### ISSUE TITLE
Add event not triggered

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#292]
I tried to implement the workaround from Issue #225. But the event is not triggered when I add a node. I have attached an example. Please note that I add the node with the method "add" of the orgchart.
[onAddEventIssue.zip](https://github.com/BALKANGraph/OrgChartJS/files/3932591/onAddEventIssue.zip)

**Comment by ZornitsaSerbezova** [comment]
Hi sks4u, 
Here is how you should do it:

`  console.log('before add');
              **addNodeF(newItem);**
              console.log('after add');
            }
          }
        },
        nodeBinding: {
          field_0: 'title',
          field_1: 'subtitle',
          field_2: 'upperLeftText',
          field_3: 'upperRightText',
          field_4: 'lowerLeftText',
          field_5: 'lowerRightText',
        },
        nodes: nodes
      }

      );

    **function addNodeF(node){
      chart.addNode(node);   
      return chart.collapse(node.pid, [node.id]);
    }**
`

Here is an example how **on add** is userd:

https://balkangraph.com/OrgChartJS-Demos/CenterOnAdd

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue, but feel free to reopen it explaining what is the problem if needed.
