### ISSUE TITLE
[bug] Comparisons instead of Assignments

### ISSUE THREAD

**Issue by ZackHJ** [BALKANGraph/OrgChartJS#293]
There are 3 instances where I believe should be assignments(=), instead they are comparisons(==).
In v6.1.3, the problematic lines are 5520, 5525, 5566.
All 3 instances are the same, here's the code for references.
`node.isAssistant == false;   //root cannot be assistant`

**Comment by ZornitsaSerbezova** [comment]
See this: https://github.com/BALKANGraph/OrgChartJS/releases/tag/6.0.4

**Comment by plamen-peshev** [comment]
Thank you very much for reporting this issue to us

We have fixed it and released new version 6.1.7
