### ISSUE TITLE
Scrollbars are visible when they are not needed

### ISSUE THREAD

**Issue by ZackHJ** [BALKANGraph/OrgChartJS#294]
If you set `showXScroll` or `showYScroll` to `OrgChart.scroll.visible`, the scroll bar will always present even when they are not needed (the chart fits in the screen). 
Can you change the `overflow-x` and `overflow-y` to `auto` instead of `scroll` ? Or provide an option to set it?
I believe the locations that the changes should happen are in line 8924 and 9118 (v.6.1.3)
Thanks

**Comment by ZornitsaSerbezova** [comment]
Hi Zack,

We have added this in our to do list.

**Comment by ZackHJ** [comment]
> Hi Zack,
> 
> We have added this in our to do list.

Any updates on this issue ?

**Comment by ZornitsaSerbezova** [comment]
Hi Zack, 

It turned out that the problem is complex, so we'll continue working on it.

**Comment by ZornitsaSerbezova** [comment]
Now it is fixed.

**Comment by ZornitsaSerbezova** [comment]
I am closing this isuue, but feel free to reopen it if needed.

**Comment by nbpro** [comment]
@ZornitsaSerbezova what is the fix version. can you also pass commit id

**Comment by ZornitsaSerbezova** [comment]
https://github.com/BALKANGraph/OrgChartJS/releases/tag/6.2.58
You could be able to use the latest verion also.
