### ISSUE TITLE
Mixed SLINKS label

### ISSUE THREAD

**Issue by jhongcarlos** [BALKANGraph/OrgChartJS#295]
Hi, when I set the label position to "start" `OrgChart.slinkTemplates.affiliations.labelPosition = 'start';` the slinks with same "to" or destination will get its labels mixed up (see image below) 
![image](https://user-images.githubusercontent.com/40976678/70484481-eb620c00-1b26-11ea-97f9-5fb51a3cc91b.png)

**Comment by plamen-peshev** [comment]
you can use "middle" for specific link instead of "start"

**Comment by ZornitsaSerbezova** [comment]
Hi jhongcarlos,
Is this issue resolved?

**Comment by jhongcarlos** [comment]
Hi BalkaNGraph/OrgChartJS,

This is not resolved, it does not meet my desired result.

**Comment by ZornitsaSerbezova** [comment]
You can try to move the labesl as here: https://balkan.app/OrgChartJS-Demos/ClinkLabel

**Comment by ZornitsaPesheva** [comment]
Hi John,
I think this resolve your issue. If not, please feel free to reopen this issue.
https://jsfiddle.net/guqoL637/1/
