### ISSUE TITLE
Multiple Parents with the column 'spids' don't work anymore

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#296]
We have used this function to display dotted lines for multiple parents. In the latest version these lines are no longer displayed.

**Comment by plamen-peshev** [comment]
There are breacking changes in version [6.0.1 ](https://github.com/BALKANGraph/OrgChartJS/releases/tag/6.0.1)

We have removed spids and replaced it with [slinks](https://balkangraph.com/OrgChartJS/Docs/Slink)
