### ISSUE TITLE
ask how to optimize balkan 

### ISSUE THREAD

**Issue by marsStudio** [BALKANGraph/OrgChartJS#298]
hi dear,

i want to ask about how to optimize view on balkan , i have 2000+ data i want show all of data in diagram, but the process slowly, question is how to optimize it to appear lighter ?,can you share tips and trick about it?, i develop my own view diagram system on laravel

**Comment by plamen-peshev** [comment]
Can you create a demo in js fiddle where we can see the issue, thus we will be able to provide a solution

**Comment by marsStudio** [comment]
hi plamen,
can we communicate via email ?, our team was contact support balkan (polina) to ask about the topic.

**Comment by ZornitsaSerbezova** [comment]
Hi,
Yes, we can.  We have answered to the email also, so I'll close this issue.
