### ISSUE TITLE
Problem running on iframe

### ISSUE THREAD

**Issue by scalgaro** [BALKANGraph/OrgChartJS#299]
Hello!
I have problems running the chart on iframe. The code works fine running directly but when I try inside an iframe the chart stays blank without JS error. 
![image](https://user-images.githubusercontent.com/19540774/71362727-a94cb780-2575-11ea-9efc-60f36fc0f5c2.png)

**Comment by ZornitsaSerbezova** [comment]
Hi scalgaro,

Here is an example with iframe: https://jsfiddle.net/BALKANGraph/0gr5twsd/

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue. Feel free to reopen it if needed.
