### ISSUE TITLE
Allow multiple lines for the group titles

### ISSUE THREAD

**Issue by wimpie3** [BALKANGraph/OrgChartJS#30]
Open the example on https://balkangraph.com/OrgChartJS/Demos/Grouping

Look at "HR team". I'd like to replace that label with "Human Resources team" but that won't work since that line is too long to fit.

Please add the possibility to have group titles that can span multiple lines.

**Comment by BALKANGraph** [comment]
Added 

In version 4.1.6 you can set multi-line or ellipsis for group names

**Comment by wimpie3** [comment]
Current version is 4.1.2... so I'll just have to wait 4 more versions? :-)

**Comment by BALKANGraph** [comment]
The latest version is 4.1.6

https://balkangraph.com/OrgChartJS/Download

**Comment by wimpie3** [comment]
OK thanks, seems Github is not up to date (https://github.com/BALKANGraph/OrgChartJS/releases)
