### ISSUE TITLE
How to add nodeMouseClick event to custom edit panel with "React"

### ISSUE THREAD

**Issue by PTOAKKY** [BALKANGraph/OrgChartJS#300]
from this : https://github.com/BALKANGraph/OrgChartJS/issues/111

but i can't add nodeMouseClick event (it not triggered)

Best regards,

**Comment by plamen-peshev** [comment]
you can use [click ](https://balkangraph.com/OrgChartJS/Docs/APIReference#click) event

**Comment by PTOAKKY** [comment]
> you can use [click ](https://balkangraph.com/OrgChartJS/Docs/APIReference#click) event

can you show me for some example in react ? 

sorry, i'm newbie.

Best regards,

**Comment by PTOAKKY** [comment]
> you can use [click ](https://balkangraph.com/OrgChartJS/Docs/APIReference#click) event

thanks.

Best regards,

**Comment by PTOAKKY** [comment]
> you can use [click ](https://balkangraph.com/OrgChartJS/Docs/APIReference#click) event

thanks Sir. but i can't call state in react file right?

**Comment by plamen-peshev** [comment]
It looks like that "this.state" is null

**Comment by PTOAKKY** [comment]
> It looks like that "this.state" is null

But I Have set state at constructor AND componentDidMount.

Can you help me for some sample ? 

Best regards,

**Comment by ZornitsaSerbezova** [comment]
Here is how I use on click:
`
import React, { Component } from 'react';

import OrgChart from '@balkangraph/orgchart.js/orgchart';

export default class extends Component {

    shouldComponentUpdate() {
        return false;
    }

    componentDidMount() {
        this.chart = new OrgChart(this.refs.tree , {
            nodes: this.props.nodes,

            nodeBinding: {
                field_0: "name",
                field_1: "title"
            }
        });
        
        this.chart.on('click', function (sender, node) {
            alert("alert");
         });  

        this.chart.load(this.props.nodes);
    }

    render() {
        return (
            <div id="tree" ref="tree"></div>
        );
    }
}
`

How do I setup the project: http://localhost/OrgChartJS/Docs/React

**Comment by PTOAKKY** [comment]
> Here is how I use on click:
> https://github.com/ZornitsaSerbezova/React/blob/master/src/chart.js

thank you, but i can't call state in react.

TypeError: Cannot read property 'test' of undefined

ps. test is my variable state name.

Can you show me how to call state value in click event method?

Best regards,

**Comment by ZornitsaSerbezova** [comment]
Hi PTOAKKY,

Try to save **this** before using **state**.
You can see again my example: https://github.com/ZornitsaSerbezova/React/blob/master/src/chart.js

**Comment by PTOAKKY** [comment]
> Hi PTOAKKY,
> 
> Try to save **this** before using **state**.
> I have edited my example: https://github.com/ZornitsaSerbezova/React/blob/master/src/chart.js

It's Work. Thank you. but, i have new Question.

How to change Size of chart?

I changed height in style of app.js to 50% but in same resault. (i didn't need scrollbar on the right) 
![Capture](https://user-images.githubusercontent.com/59352415/73055766-1aa6bf80-3ec0-11ea-8c9f-f084b86ee1d3.PNG)

**reference**
from your example: https://github.com/ZornitsaSerbezova/React/blob/master/src/chart.js
AND https://balkangraph.com/OrgChartJS/Docs/React

**Comment by ZornitsaSerbezova** [comment]
Why do you have scrollbar? I don't have one in my example in GitHub.
![react](https://user-images.githubusercontent.com/19305472/73061805-a827e680-3ea3-11ea-9972-0ee76d07b672.png)

**Comment by PTOAKKY** [comment]
i try to test on Display Resolution on 1366x768 and 1920x1080 with your example code from github.

result : 
1366x768 -> I have Scroll Bar
1920x1080 -> I haven't Scroll Bar 

1366x768 : 
![Capture - 1366x768](https://user-images.githubusercontent.com/59352415/73149533-5033ee80-40f4-11ea-93c8-28c5510176f7.PNG)

1920x1080 : 
![Capture - 1920x1080](https://user-images.githubusercontent.com/59352415/73149538-52964880-40f4-11ea-8a91-feaf5a2e2520.PNG)

**Comment by ZornitsaSerbezova** [comment]
![responsive](https://user-images.githubusercontent.com/19305472/73159853-2973b900-40f0-11ea-85d2-1435a09246cc.png)

**Comment by ZornitsaSerbezova** [comment]
![responsive](https://user-images.githubusercontent.com/19305472/73159916-56c06700-40f0-11ea-95b0-aaa92714f58a.png)

**Comment by ZornitsaSerbezova** [comment]
It is not from the OrgChart or the resolution. Check the elements. 

![responsive](https://user-images.githubusercontent.com/19305472/73159982-79eb1680-40f0-11ea-858c-9dfaf9441e2d.png)

**Comment by PTOAKKY** [comment]
it's Ok now. I replace element from style height: 100% to 100vh

thank you

Best regards,
