### ISSUE TITLE
different color on border or node background?

### ISSUE THREAD

**Issue by troy96wang** [BALKANGraph/OrgChartJS#301]
Is it possible to use different color to either border or node background based on gender if I use this framework to display family tree?
Thanks a lot

**Comment by ZornitsaSerbezova** [comment]
Yes, it is possible. You can see [this demo](https://balkangraph.com/OrgChartJS/Demos/ConditionalColor). Instead of "title", you can set "gender". The field will not be visible in nodes, if you don't set it in nodeBinding.

**Comment by troy96wang** [comment]
Thanks for your answer. I tried to alter node border (line) color but no luck. Would you please instruct me how to do it?

**Comment by plamen-peshev** [comment]
I have created a demo for you https://jsfiddle.net/BALKANGraph/xqL8wofp/

**Comment by troy96wang** [comment]
thanks for instruction.
I tried to change node corner radius like this (from your demo) but doesn't work:
.node.QA rect {
    fill: #F57C00;    
    rx: 10px;
    ry: 10px;
}

FYI: I just purchase your framework yesterday (Professional)

**Comment by ZornitsaSerbezova** [comment]
You need to change it here:
OrgChart.templates.ana.node = '<rect x="0" y="0" height="120" width="250" fill="#039BE5" stroke-width="5" stroke="#333" **rx="5" ry="5"**></rect>';

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue. Feel free to reopen it if needed.
