### ISSUE TITLE
BALKANGraph is not defined?

### ISSUE THREAD

**Issue by karmalet** [BALKANGraph/OrgChartJS#302]
Hi
When I try to use BALKANGraph.orientation.top_left, it throws an error: Uncaught ReferenceError: BALKANGraph is not defined
It was working well before in January 6. Is it related with the latest update?

**Comment by ZornitsaSerbezova** [comment]
Hi karmalet,

Please use **OrgChart** instead of **BALKANGraph**

**Comment by karmalet** [comment]
Oh, it works now. thank you so much.
