### ISSUE TITLE
Typescript Definition

### ISSUE THREAD

**Issue by hdcolelia** [BALKANGraph/OrgChartJS#304]
I have an issue with the typescript definition. The problem is the name of "options" interface. I think that the name of this interface should be more specific; i mean, could be named "OrgChartOptions" or something like that.. 
All this is in order to avoid confussion because the name "options" is too generic.

I can chnge it in "node_modules\@balkangraph\orgchart.js\orgchart.d.ts" but i will be nice if you change it for further versiones.

Thanks..

**Comment by ZornitsaSerbezova** [comment]
Hi hdcolelia,

We have changed oprions to OrgChartOptions.

**Comment by hdcolelia** [comment]
Thanks.
