### ISSUE TITLE
Please add feature to enable automatic scroll right-left while dragging a node across a wide org chart

### ISSUE THREAD

**Issue by dyeaple** [BALKANGraph/OrgChartJS#305]
Hi,

We have a large org chart with over 200 nodes. 

The organization organized into teams rather than the typical hierarchy, so many of the nodes don't have a Parent ID (pid), but each team has a manager and subordinates. The result is a very wide org chart that requires the x-Scroll and can only be viewed in segments as shown in the attached screenshot. 

The drag and drop feature in OrgchartJS is used to add new nodes to the org chart.

When a new user is added, the user's node is placed on the far right side of the org chart so it can be dragged to the left to establish the reporting relationship.

The problem is that the very wide org chart doesn't scroll to the right when dragging the node all the way to the left hand side of the window.

The request is to add a feature for very wide org charts that will automatically scroll a very wide org chart to the left when dragging a node to the far right hand side of the screen, and scrolling to the right when dragging a node to the far left hand side of the screen.

![image](https://user-images.githubusercontent.com/48760157/72732723-4cd4bc00-3b64-11ea-80ea-425f1358a759.png)

**Comment by ZornitsaSerbezova** [comment]
HI dyeaple,

As far I understand, you'd like when a node is added to the right hand side, the orgchart to scroll to the left hand side. But in this case, you will not be able to see the added node, and you will not be sure if the node is added correctly. Also the scroll may happen very fast or very slow. 
Also you can use **chart.center(nideId)** and **sticky: true** to center a node.
You can see a demo here: https://balkangraph.com/OrgChartJS-Demos/Center

**Comment by dyeaple** [comment]
Hi Zornitsa,

Thank you for your reply! 

We do use the Chart.Center feature, which is helpful. However, as you can see in the attached video, the nodes are very small as the chart is very wide (notice that the x scroll bar at the bottom is all the way to the right and only a segment of the full org chart is displayed). 

If I center the chart with the Chart.Center feature it's not possible to see any of the text on the nodes because they are so small.

As I demonstrate in the attached video, I would like to move a node much further to the left in the org chart. To keep the text size readable, I don't want to use the Chart.Center feature to display the whole org chart.

As I drag the node to the left, it would be ideal if the org chart scrolls slowly to the right when I get to the extreme left hand side of the screen. I could then navigate to the node that I would like to place the node I am dragging. 

Please let me know if this explanation helps.

Thank you!

David Yeaple
![Drag node to left](https://user-images.githubusercontent.com/48760157/72811858-7c4ffb00-3c2e-11ea-8f9c-a7d048161fbe.gif)

**Comment by ZornitsaSerbezova** [comment]
So you'd like when you reach the left end (the beginning), the chart to scroll automatically to the right (the end)? Then you will continue to search for the right place to drop the node?
Actually Chart.Center(id) is centering a node. It is not showing the whole chart. I.e. with it you can tell the chart to center a node that is in the right end of the chart.

**Comment by dyeaple** [comment]
Hi Zornitsa,

Thanks again for your reply!

Yes, when I drag a node to the far left side screen, it would be great if the chart would automatically scroll to the right.

Similarly, when I drag a node to the far right hand side of the screen, it would be ideal if the chart would automatically scroll to the left.

If the node that is being dragged is moved away from the far right hand side or far left hand side, the automatic scrolling would stop.

This feature will allow the user to view the nodes as they scroll by and then stop the scrolling to drop the node that's being dragged onto the desired node to create the reporting relationship.

Again, thank you for your help!

**Comment by ZornitsaSerbezova** [comment]
Hi dyeaple,

Now I understand what do you ask for. 
We have logged your request and it will be implemented in one of the future releases.

Regards,
Zornitsa

**Comment by dyeaple** [comment]
Thank you so much Zornitsa!

We really appreciate your help!

Sincerely,
 
David Yeaple
VP of Business Development & Product Management
SnapEval, LLC | dyeaple@SnapEval.com | 585.414.5000 or 585.905.3565
 
To instantly schedule a call or meeting, click to access my calendar.
 
3-ways to instantly get your FREE 10-user SnapEval account:
SnapEval® for ADP Workforce Now®: https://apps.adp.com/apps/209526
SnapEval® for RUN Powered by ADP®: https://apps.adp.com/apps/209522
SnapEval® for non-ADP customers: https://www.SnapEval.com

**Comment by plamen-peshev** [comment]
requested feature is added in the latest version 6.5.2

[Video](https://www.youtube.com/watch?v=_Smm107yCZE)

**Comment by dyeaple** [comment]
Hi Plamen,

 

Thank you for letting us know about this update! I'll have our team install
it this week. I know that our users will be very happy about this new
feature.

 

Thank you again!

 

Sincerely,

 

David Yeaple

VP of Business Development & Product Management

SnapEval, LLC | dyeaple@SnapEval.com <mailto:dyeaple@SnapEval.com>  |
585.414.5000 or 585.905.3565

 

To instantly schedule a call or meeting, click to access my calendar
<https://t.sidekickopen79.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-F
fhMynW4Y9jV42BpyQjW56dRpz6hd6c6102?te=W3R5hFj4cm2zwW3_SMKM3T1k87W1JzCRv4cNDS
bW1JxwY51LwvP9f3zfPwm04&si=7000000001775251&pi=0e27d222-398b-4679-8d27-7f038
92d6f53> .

 

  

 

3-ways to instantly get your FREE 10-user SnapEval account:

*	SnapEvalR for ADP Workforce NowR: https://apps.adp.com/apps/209526
<https://t.sidekickopen79.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-F
fhMynW4Y9jV42BpyQjW56dRpz6hd6c6102?te=W3R5hFj4cm2zwW3zfPTB1JwH0MW1JxwY51Lvdz
RW4cgtCR24Vhf-0&si=7000000001775251&pi=d71fca25-1eaa-47c6-9960-de3c83604ead>

*	SnapEvalR for RUN Powered by ADPR: https://apps.adp.com/apps/209522
<https://t.sidekickopen79.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-F
fhMynW4Y9jV42BpyQjW56dRpz6hd6c6102?te=W3R5hFj4cm2zwW3zfPTB1JwH0MW1JxwY51Lvdz
RW4cgtCR24VhfW0&si=7000000001775251&pi=d71fca25-1eaa-47c6-9960-de3c83604ead>

*	SnapEvalR for non-ADP customers: https://www.SnapEval.com
<https://t.sidekickopen79.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-F
fhMynW4Y9jV42BpyQjW56dRpz6hd6c6102?te=W3R5hFj4cm2zwW4mKLS-4cMNGvW3KbspT1JxwY
51V3&si=7000000001775251&pi=d71fca25-1eaa-47c6-9960-de3c83604ead> 

 

 <https://www.facebook.com/snapeval/>
<https://t.sidekickopen79.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-F
fhMynW4Y9jV42BpyQjW56dRpz6hd6c6102?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY
5W1Lw3rh45LM6yW1LDKYp45NqKy348R2&si=7000000001775251&pi=0e27d222-398b-4679-8
d27-7f03892d6f53>
<https://t.sidekickopen79.com/s1t/c/5/f18dQhb0S7lM8dDMPbW2n0x6l2B9nMJN7t5X-F
fhMynW4Y9jV42BpyQjW56dRpz6hd6c6102?te=W3R5hFj4cm2zwW4fQ47l4fGCmnW3Fbt5S4cMNG
vf3KbspTV3&si=7000000001775251&pi=0e27d222-398b-4679-8d27-7f03892d6f53>
