### ISSUE TITLE
Custom slinks not working after I bought the product

### ISSUE THREAD

**Issue by jhongcarlos** [BALKANGraph/OrgChartJS#306]
Everything is working fine before I bought this product. But when I purchased it, my custom slinks are not working anymore.

`OrgChart.slinkTemplates.affiliations = Object.assign({}, OrgChart.slinkTemplates.orange);
OrgChart.slinkTemplates.affiliations.link = '<path  marker-start="url(#arrowSlinkOrange)" marker-end="url(#dotSlinkOrange)" stroke-linejoin="round" stroke="#000" stroke-width="1" fill="none" d="{d}" />';`

it shows me this error:
`Uncaught TypeError: Cannot read property 'defs' of undefined
    at Array.<anonymous> (orgchart.js:1)
    at Object.publish (orgchart.js:1)
    at orgchart.js:1
    at orgchart.js:1
    at orgchart.js:1
    at Object.OrgChart.local._walk (orgchart.js:1)
    at OrgChart.server._read (orgchart.js:1)
    at OrgChart.server.read (orgchart.js:1)
    at OrgChart._draw (orgchart.js:1)
`
All help will be appreciated, thank you.

**Comment by plamen-peshev** [comment]
Probably you were using old version

Can you create a demo in jsfiddle with the problematic code

**Comment by jhongcarlos** [comment]
Here:
https://jsfiddle.net/v2afmyn8/

**Comment by jhongcarlos** [comment]
I entered my IP address and downloaded the "Licensed OrgChart JS" and the SLINKS stops working but in free version, it is working. How to update my licensed orgchart to the latest version?
![image](https://user-images.githubusercontent.com/40976678/73144220-6fc01c80-40de-11ea-8df2-98041fb6b9ab.png)

**Comment by plamen-peshev** [comment]
You sent us an email that the problem has been solved and we will close this issue
