### ISSUE TITLE
Incorrect position of the main node 

### ISSUE THREAD

**Issue by rogeriocc** [BALKANGraph/OrgChartJS#307]
Incorrect position of the main node using Group Assistent nodes and Assistent out of group at the same time.

![wrong_position_main_node](https://user-images.githubusercontent.com/2631583/73095238-e4b60b00-3ec0-11ea-88b1-2a9dfe9ef787.png)

**Comment by plamen-peshev** [comment]
The issue is fixed in version 6.1.998
