### ISSUE TITLE
How to Custom icon in menu / node menu.

### ISSUE THREAD

**Issue by PTOAKKY** [BALKANGraph/OrgChartJS#308]
Can i custom icon?.

![how to custom icon](https://user-images.githubusercontent.com/59352415/73235049-55aa3b00-41bf-11ea-888a-ac666dd055c1.PNG)

Best Regards,

**Comment by ZornitsaSerbezova** [comment]
Yes, you can. See these examples:

https://github.com/ZornitsaSerbezova/ActiveDirectory/blob/master/ActiveDirectory/Views/Home/OrgChart.cshtml - for SVG icons

https://balkangraph.com/OrgChartJS-Demos/HtmlElementIcon - HTML element icon
