### ISSUE TITLE
How to custimize the rect fill of *just* the group templates?

### ISSUE THREAD

**Issue by rvanacke** [BALKANGraph/OrgChartJS#309]
Is there a simple way to change the background color/fill of the rect of just the group template?  I am ideally trying to use the 'luba' template but as there is no matching luba group template, I am trying to modify the 'group_grey' template to have the same look and feel as 'luba' but I've been unable to change the background color of the grouping box/rect without having it affect the nodes as well.

Is there a simple way to modify just the background of the grouping box while preserving the node design for the rest of the tree?

**Comment by ZornitsaSerbezova** [comment]
Hi rvanacke,

I have created a demo for you: http://jsfiddle.net/BALKANGraph/7caw50hk/

**Comment by rvanacke** [comment]
This is fantastic - and much easier than I was trying to make it.  I appreciate the support and quick response on this!
