### ISSUE TITLE
Collapsing nodes on load causes centering of chart when out of bounds

### ISSUE THREAD

**Issue by zehkaiser** [BALKANGraph/OrgChartJS#31]
When I load my org chart with nodes in a state of BALKANGraph.COLLAPSE it causes the graph behavior to be weird. If you drag too far past the bounds of the graph it will force it to recenter instead of pulling back to the boundary.

    orgchart = new OrgChart(document.getElementById("tree"), {
        scaleInitial: 1,
        scaleMax: 2,
        template: "mila",
        nodeBinding: {
            field_0: "name"
        },
        onClick: function (sender, node) {
            nodeClicked(sender, node);
            return false; //cancel nodeMouseClickBehaviour action
        },
        nodes: treeData,
        orientation: BALKANGraph.orientation.top,
        mouseScroolBehaviour: BALKANGraph.action.zoom,
        tags: {
            "hidePanel": {
                state: BALKANGraph.COLLAPSE
            },
            "user": {
                template: "ana"
            }
        }
    });

Removing the state from the "hidePanel" tag will cause the graph to behave normally.

**Comment by BALKANGraph** [comment]
I have tried to replicate the issue to no avail

Can you please check if the [this demo](https://jsfiddle.net/BALKANGraph/d98o4h36/5/) works for you

**Comment by zehkaiser** [comment]
I actually just downloaded the latest release and it has resolved the issue. I'll request the latest paid version and verify it is also fixed there.

**Comment by BALKANGraph** [comment]
It is fixed in the latest paid version
