### ISSUE TITLE
PDF Preview – Need a way to customize the form.

### ISSUE THREAD

**Issue by joce007** [BALKANGraph/OrgChartJS#310]
I am looking for a way to customize the PDF Preview UI in a similar fashion than the Custom EditForm: https://balkangraph.com/OrgChartJS/Docs/Edit.  For a better user experience, it would be great to have the possibility to control what to display in terms of parameters, buttons and also the look and feel.

I didn’t find any documentation or ways of doing it so far.  Is this something possible to enhance short term?  Our team is currently evaluating this library, it is a really great but without this capability, it would prevent us from buying a license.

**Comment by ZornitsaSerbezova** [comment]
Hi joce007,

Is this view that you need to customize?:

![pdf](https://user-images.githubusercontent.com/19305472/73435911-3abc0000-4352-11ea-8dfa-7a55b1322aeb.png)

**Comment by joce007** [comment]
Hi ZornitsaSerbezova,

Yes, this is the view that our team needs to customize.  Basically, we need a way to customize the headers and footers using a user friendly approach.  For example, we are planning of providing pre-defined templates that could be customized via images/logos and title/text injection.  Another thing to be able to customize is the way margins are presented.  Ideally, having four separated fields instead of one would clearly indicate their role / position.  We also need to create the view in multiple languages, our clients need to support both English and French language, so having the ability to customize the labels is essential.  Finally, the general layout and look and feel of how to present the information.  

I wish this gives you a better understanding of what we are trying to achieve!

Thanks!

**Comment by ZornitsaSerbezova** [comment]
Hi joce007,

Here is the list of things that you may localize:

OrgChart.loc.ppdfCmdTitle = 'PDF Preview';
OrgChart.loc.ppdfSave = 'Save';
OrgChart.loc.ppdfCancel = 'Cancel';
OrgChart.loc.ppdfFormat = 'Format';
OrgChart.loc.ppdfFitToDrwaing = 'Fit';
OrgChart.loc.ppdfFitToDrwaing2Levels = 'Fit (2 Levels Page)';
OrgChart.loc.ppdfA4 = 'A4';
OrgChart.loc.ppdfA3 = 'A3';
OrgChart.loc.ppdfA2 = 'A2';
OrgChart.loc.ppdfA1 = 'A1';
OrgChart.loc.ppdfA42Levels = 'A4 (2 Levels Page)';
OrgChart.loc.ppdfA32Levels = 'A3 (2 Levels Page)';
OrgChart.loc.ppdfA22Levels = 'A2 (2 Levels Page)';
OrgChart.loc.ppdfA12Levels = 'A1 (2 Levels Page)';
OrgChart.loc.ppdfLayout = 'Layout';
OrgChart.loc.ppdfPortrait = 'Portrait';
OrgChart.loc.ppdfLandscape = 'Landscape';
OrgChart.loc.ppdfFittopagewidth = 'Fit to page width';
OrgChart.loc.ppdfMargin = 'Margin';
OrgChart.loc.ppdfHeader = 'Header';
OrgChart.loc.ppdfFooter = 'Footer';
OrgChart.loc.ppdfScale = 'Scale';

Here is an example of how we can do this: https://jsfiddle.net/BALKANGraph/c9a7yf1e/

Also you could change everything you want.
If you would like us to send you the code for the PDF Preview, please write us an email to support@balkangraph.com.

Regards,
Zornitsa

**Comment by joce007** [comment]
Hi Zornitsa, 

This is great for localization.  

You are saying that everything else could be changed, I am happy to ear that but still not sure how to do it.  Would it be possible to build such a customize view and add it under the demo page ?  

As you suggested, I've sent an email to support@balkangraph.com to get the code for the PDF Preview.

Thanks!

**Comment by plamen-peshev** [comment]
We have created a demo for you

[pdf-preview-cusomization.zip](https://github.com/BALKANGraph/OrgChartJS/files/4139885/pdf-preview-cusomization.zip)

Basically you have t override OrgChart.pdfPrevUI.show function

![image](https://user-images.githubusercontent.com/49443821/73548008-bd26eb80-4448-11ea-8bba-402f3abcd354.png)

**Comment by joce007** [comment]
Awesome! With the provided sample, it was simple to customize our view. This was the missing part I need to make it works.  I would strongly recommend adding this example as a reference in your DEMO section: https://balkangraph.com/OrgChartJS-Demos

**Comment by ZornitsaSerbezova** [comment]
added in demos: https://balkangraph.com/OrgChartJS-Demos/PdfPreviewTemplates
