### ISSUE TITLE
Nodes limits

### ISSUE THREAD

**Issue by kradydal** [BALKANGraph/OrgChartJS#312]
We're testing your library and when a number of nodes are over 150, the graph disappears. What can cause this effect? Are there any limits?

**Comment by ZornitsaSerbezova** [comment]
Hi kradydal, 

For the free version the limit is 200 nodes.
If your nodes are < 200, please create an example in jsfiddle, so we take a look at this issue.

**Comment by kradydal** [comment]
It occurs that the problem is on the Chrome browser. Everything works fine on Firefox and Safari.

**Comment by ZornitsaSerbezova** [comment]
Anyway, please create an example :)

**Comment by kradydal** [comment]
[demo_2.zip](https://github.com/BALKANGraph/OrgChartJS/files/4134946/demo_2.zip)
Here is our demo app.

**Comment by kradydal** [comment]
https://jsfiddle.net/hvdt04c6/ here is our code

**Comment by ZornitsaSerbezova** [comment]
Hi kradydal,

In your chart you have a lot of nodes under assistants. Please note that we **don't** support nodes under assistants.  You need to change your data, removing these cases.


Regards,
Zornitsa

**Comment by kradydal** [comment]
Zornitsa, thanks for your help.
