### ISSUE TITLE
How to set Border width & color of Node Menu ?

### ISSUE THREAD

**Issue by PTOAKKY** [BALKANGraph/OrgChartJS#313]
1. Can i set Border width & color of Node Menu ?
2. Can i Change Menu Tabs Background Color & Font Color ?

![how to custom icon - Copy](https://user-images.githubusercontent.com/59352415/73517838-44676580-442f-11ea-82bc-c006db03ee28.PNG)

**Comment by ZornitsaSerbezova** [comment]
Hi PTOAKKY,

We have added a class **chart-menu**, so you can select it and make these changes. Please download **latest version**.
