### ISSUE TITLE
Image with local path 

### ISSUE THREAD

**Issue by yuujin** [BALKANGraph/OrgChartJS#314]
Hi,

I want to use OrgCharts with local image, but when I write the path nothing is showing.

`
var chart = new OrgChart(document.getElementById("tree"), {
             template: "ula",
            enableDragDrop: true,

            nodeMenu: {
                edit: { text: "Edit" },
                add: { text: "Add" },
                remove: { text: "Remove" }
            },
          nodeBinding: {
            field_0: "name",
            field_1: "title",
            img_0: "img",
            field_number_children: "field_number_children"
        },
        nodes: [
            { id: 1, name: "Denny Curtis", title: "CEO", img: "C:\Users\folder\folder\img.jpg" }
        ]
}`

**Comment by ZornitsaSerbezova** [comment]
Hi yuujin,

The right path is this: "C:/Users/folder/folder/img.jpg"

**Comment by yuujin** [comment]
ZornitsaSerbezova,

Thanks for your answer,

I try 
`{ id: 1, name: "Denny Curtis", title: "CEO", img: "C:/Users/folder/folder/img.jpg" }`

It's doesn't work too.

I create a folder in my web site repo, and it's work, like this : 
`{ id: 1, name: "Denny Curtis", title: "CEO", img: "img/img.jpg" }`

But after I want find in the LAN.
