### ISSUE TITLE
Show img from local network

### ISSUE THREAD

**Issue by yuujin** [BALKANGraph/OrgChartJS#315]
Hello,

How can show a picture in local network for img_0 ? 

I try 
` { id: 1, name: "Denny Curtis", title: "CEO", img: "//folder/folder/img/picture.jpg" },`

But it's not working

Thanks.

**Comment by ZornitsaSerbezova** [comment]
Hi yuujin,

This is a correct UNC path: 
\\<computer name>\<shared directory>\...
