### ISSUE TITLE
Distinguish between mouse single click and double click

### ISSUE THREAD

**Issue by Jags-tech** [BALKANGraph/OrgChartJS#316]
I have the below requirement for mouse single click and double click as follows:
    Single click: To display the Details window and change the color of the node clicked
    Double click: Perform a search on the node to display the children of that node. 

**Code is as below:**
var chart = new OrgChart(document.getElementById("tree"), {
     ...
     nodeMouseClick: OrgChart.action.details,  //this displays the details pane
    ...
 });  
sercoChart.on('click', function (sender, node) {
....code to change the color of the clicked node
});

sercoChart.on('dbclick', function (sender, node) {
....code to make the AJAX call to get child nodes and populate
});

The issue is whenever i do double click on the mouse, it calls the single click method too. So on double click, it displays the details pane and bring up the children for the node. 
**How to avoid invoking single click function and just calling double click function.**

**Comment by ZornitsaSerbezova** [comment]
Hi Jags,
I have answered to your email.

**Comment by Jags-tech** [comment]
Serco Business

Yes, Got it. Thank you Zornitsa.

Jagadish("Jags") Puttaswamy, (PMP, CSM, ITILv3)
Enterprise Apps, Corporate Services
Phone: 703-263-6152

**Comment by Jags-tech** [comment]
Hi Zornitsa,
Updating the code as in demo worked well, except with one caveat.

The demo code replaced this “`nodeMouseClick: OrgChart.action.details`” with “`nodeMouseClick: OrgChart.action.none`” which stopped displaying the details pane on node mouse click.
If I revert this property, the problem exist.   
Is there a way to display the details plane on invoke of this function “`sercoChart.on('click', function (sender, node)`…” ? instead of this nodeMouseClick property.

Thanks
Jags

**Comment by ZornitsaSerbezova** [comment]
I have answered to your email again.
Here the example: https://jsfiddle.net/BALKANGraph/m8uwzs32/
