### ISSUE TITLE
Save the Change in Database

### ISSUE THREAD

**Issue by Esky580** [BALKANGraph/OrgChartJS#317]
Hello,

i bought the full version a few days ago and i am very satisfied until now !

I have tried to add an item from the right side of the demo version and this change will be inserted directly in the database using php. Unfortunately since monday i try to save this change somehow with a save and cancel button if an item was added "wrong" by drag and drop. 
Thereby it should also recognize the father-ID and enter this also immediately.

This example is my initial situation: https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/DragDropItemsToChart

Is this realizable if yes how ?

**Comment by ZornitsaSerbezova** [comment]
I am copying my answer from the email: 

var chart = new OrgChart(...);
        
         chart.on('add', function (sender, node) {
             check if the item is added wrong 
             and return false to cancel the operation 
         });  

         chart.load(...);
