### ISSUE TITLE
Setting up on-premise Export-Service using HTTPS

### ISSUE THREAD

**Issue by joce007** [BALKANGraph/OrgChartJS#318]
Hi,

I am currently evaluating the OrgChartJS library including the export-service. It is an awesome tool including the export-service and we are looking for buying licenses. Therefore, I have a hard time setting the export-service to support HTTPS requests.  And this is a mandatory requirement before buying licences.  

The original post of the issue could be found export-service project but no answers yet: https://github.com/BALKANGraph/export-service/issues/3 

Please, any advice or help to set this up would be helpful.
Thanks!

**Comment by plamen-peshev** [comment]
The issue has been addressed and now you can host the service under https without http binding 

The default export servile is under https https://balkangraph.com/export/index.html

What is the error you are receiving?

**Comment by Esky580** [comment]
@plamen-peshev  can you answer to my question pls?
#317

**Comment by ZornitsaSerbezova** [comment]
Esky580, answered.

**Comment by joce007** [comment]
@plamen-peshev I don't have any problem with the default export service.  I need to deployed the service on-premise but how to activate HTTPS as a standalone NodeJs App without hosting it under IIS via IISNode ?  I start the app from a command-line.  It only listen on HTTP port 1337 by default.  How could I also enable listening on a different port with HTTPS activated ?

**Comment by ZornitsaPesheva** [comment]
> @plamen-peshev I don't have any problem with the default export service. I need to deployed the service on-premise but how to activate HTTPS as a standalone NodeJs App without hosting it under IIS via IISNode ? I start the app from a command-line. It only listen on HTTP port 1337 by default. How could I also enable listening on a different port with HTTPS activated ?

hi Jocelin,

Do you still have this problem?

**Comment by ZornitsaPesheva** [comment]
I'll close this issue as it looks inactive, Feel free to reopen it or open another one if needed.
