### ISSUE TITLE
PNG mode issues

### ISSUE THREAD

**Issue by wimpie3** [BALKANGraph/OrgChartJS#32]
- Font not respected (uses the standard Times New Roman)
- Images missing in the PNG

**Comment by BALKANGraph** [comment]
- change the template - OrgChart.templates.ula.defs += '<style >text {font-family: Courier;}</style>' see https://jsfiddle.net/BALKANGraph/91ap8tz6/

- you should use images with absolute URL and visible to your Export Server

**Comment by wimpie3** [comment]
- I've changed the template but the PNG doesn't seem to work with Google Fonts
- Despite using absolute URL's, images don't show

**Comment by BALKANGraph** [comment]
- did you added the link to the Google font in OrgChart.templates.ula.defs?
- Are you using your own export service hosted on your machine? Please provide a link to one image for a test

**Comment by ZornitsaSerbezova** [comment]
I am closing this issue. You could open it again, if needed.
