### ISSUE TITLE
Different orientation for different levels

### ISSUE THREAD

**Issue by PrateekRanjanSingh** [BALKANGraph/OrgChartJS#320]
I tried to implement different orientation for different levels. 
For eg. - I want the nodes till level 2 to have a Orgchart.orientation.top and after level 2, I want the nodes to have Orgchart.orientation.left so that after level 2 the nodes are shown vertically and expand horizontally like it happens in Orgchart.orientation.left.
I tried doing it using tags but it is not working. 
Following is the code I have been trying to implement.
`var chart = new OrgChart(document.getElementById("tree"),{
mouseScrool: Orgchart.action.none,
orientation :OrgChart.orientation.top,
template: "base",
tags: {
"test":{
orientation : Orgchart.orientation.left
}
},
nodes:[
{id: "1"},
{id:"2",pid:"1"},
{id:"3",pid:"1"},
{id:"4",pid:"2", tags: ["test"]},
{id:"5",pid:"2", tags: ["test"]},
{id:"6",pid:"3", tags: ["test"]},
{id:"7",pid:"3", tags: ["test"]},
{id:"8",pid:"7", tags: ["test"]},
{id:"9",pid:"7", tags: ["test"]},
]
});`

**Comment by ZornitsaSerbezova** [comment]
Hi PrateekRanjanSingh,

Currently we don't support different orientations for different levels, but it is in our to do list for future updates.

**Comment by ZornitsaSerbezova** [comment]
With the new OrgChart JS version (7.1.1) you can have different orientations in the chart.
