### ISSUE TITLE
Possible : LazyLoading AJAX

### ISSUE THREAD

**Issue by herivola** [BALKANGraph/OrgChartJS#321]
Hello,

With your library, can we use a button to load by AJAX for more data : For example, more hierarchy collaborator nodes ?

Thanks for your answer. 

Your product is very good.

Herivola.

**Comment by ZornitsaSerbezova** [comment]
Hi herivola,

With our library you don't need such function.
We have clients using the product with 30k nodes, thanks to the **lazyLoading** option. 

Lazy loading defers loading of non-critical nodes at page load time. Instead, these non-critical nodes are loaded at the moment of need.

Default value: true
Code example:

```
    var chart = new OrgChart(document.getElementById("tree"), {
       lazyLoading: true,
        ...
    });
    
```

**Comment by herivola** [comment]
Thanks you very much for this informations ! 

:)
