### ISSUE TITLE
How to create OrgChart JS using SQL Server database and ASP.NET c# ( Web Forms) 

### ISSUE THREAD

**Issue by uumi95** [BALKANGraph/OrgChartJS#322]
can i integrate your library in a project asp.net Web Forms using sql server data ?
I created a web forms and I added the file js, ms the side of file aspx.cs I do not know how to link the nodes with my database

**this is my source code webform.aspx**

#<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="testProjet.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta name="viewport" content="width=device-width" />
    <title> OrgChart</title>
    <script src="OrgChart.js"></script>
     <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
     <style>
        html, body {
            width: 100%;
            height: 100%;
            padding: 0;
            margin: 0;
            overflow: hidden;
        }

        #tree {
            width: 100%;
            height: 100%;
        }

        .field_0 {
            font-family: Impact;
        }
    </style>
</head>
<body>
    

        
        
            
            <div id="tree"></div>
            <script>

                var chart = new OrgChart(document.getElementById("tree"), {
                    template: "diva",
                    //template: "olivia",
                    layout: OrgChart.mixed,
            nodeBinding: {

                field_0: "name"
            },
            menu: {
                pdf: { text: "Export PDF" },
                png: { text: "Export PNG" },
                svg: { text: "Export SVG" },
                csv: { text: "Export CSV" }
            },
            nodeBinding: {
                field_0: "name",
                field_1: "title",
                img_0: "img"
            },
            nodeContextMenu: {
                edit: { text: "Edit", icon: OrgChart.icon.edit(18, 18, '#039BE5') },
                add: { text: "Add", icon: OrgChart.icon.add(18, 18, '#FF8304') }
            },
            dragDropMenu: {
                addInGroup: { text: "Add in group" },
                addAsChild: { text: "Add as child" }
            },
            nodeMenu: {
                details: { text: "Details" },
                edit: { text: "Edit" },
                add: { text: "Add" },
                remove: { text: "Remove" }
            },
            nodes: [
                

                { id: 1, },
                { id: 2, pid: 1, },
                { id: 3, pid: 1,},
                { id: 4, pid: 1, },

                { id: 5, pid: 3,},
                { id: 6, pid: 3, },
                { id: 7, pid: 3, }

            ]
        });
                document.getElementById("selectTemplate").addEventListener("change", function () {
                    chart.config.template = this.value;
                    chart.draw();
        });

            
    </script>
            <select style="position: absolute;right: 90px;top: 30px;color: #7a7a7a;font-size: 14px;padding: 10px;background-color: #F57C00;color: #ffffff;width: 100px;z-index:2;" id="selectTemplate">
        <option>luba</option>
        <option>olivia</option>
        <option>derek</option>
        <option>diva</option>
        <option>mila</option>
        <option>polina</option>
        <option>mery</option>
        <option>rony</option>
        <option>belinda</option>
        <option>ula</option>
        <option>ana</option>
        <option>isla</option>
        <option>deborah</option>
    </select>
      
    
</body>
</html>

**webform.aspx.cs**

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using testProjet.DAL;

namespace testProjet
{
    public partial class WebForm1 : System.Web.UI.Page
    {
       
        SqlConnection conn = new SqlConnection("Data Source=OUMAIMA-PC\\SQLEXPRESS;Initial Catalog=AGIRH;Integrated Security=True");
        protected void Page_Load(object sender, EventArgs e)
        {
           // GetData();
        }
        private DataTable GetData()

        {
            DataTable dt = new DataTable();
            
            string cmd = "select UO, UO_RATTACHEMENT from UNITE_ORG";

            SqlDataAdapter adp = new SqlDataAdapter(cmd, conn);

            adp.Fill(dt);

            return dt;
        }

    }
}

**Comment by plamen-peshev** [comment]
We have created a demo fro you 

See https://github.com/plamen-peshev/OrgChartWebForms 

In the demo we are using WebMethod and Session object instead of MS SQL

you have to replace the Session object with your MS SQL data access layer

**Comment by uumi95** [comment]
do I only need to add the sessionState configuration in web.config?
`<sessionstate mode="SQLServer" timeout="20" allowcustomsqldatabase="true" 
sqlconnectionstring="Data Source=Server;Initial Catalog=tablename;
User ID=UserID;Password=Password;" cookieless="false">`

**Here is the result of the project:**
![orgchart](https://user-images.githubusercontent.com/38526134/74662453-3b4df680-519a-11ea-8ee1-4d7deab5ba07.png)

**how should i link my database ?**

**Comment by plamen-peshev** [comment]
Instead of sessions you can use your MS SQL database for storing the data

**Comment by uumi95** [comment]
can you show me an example please ?
I tried a lot of solutions but it doesn't work

**Comment by uumi95** [comment]
hey, i read my data, with ajax now i need to convert to nodes
![image](https://user-images.githubusercontent.com/38526134/75139538-2cf96080-56ed-11ea-8c55-0ebd10895975.png)

**Comment by plamen-peshev** [comment]
hey 
you can use `chart.load(nodes)` in your "success" ajax handler

**Comment by uumi95** [comment]
> hey
> you can use `chart.load(nodes)` in your "success" ajax handler

always without result
