### ISSUE TITLE
orgchart.d.ts is incomplete

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#323]
orgchart.d.ts is incomplete. Several entries are missing in orgchart.d.ts.
Examples:
`

OrgChart.orientation.bottom
OrgChart.treeLeftOffset
OrgChart.treeRightOffset
OrgChart.mixed
OrgChart.tree
OrgChart.COLLAPSE
OrgChart.COLLAPSE_PARENT_NEIGHBORS
OrgChart.COLLAPSE_SUB_CHILDRENS
OrgChart.icon
`

**Comment by sks4u** [comment]
also
`
OrgChart.slinkTemplates
`
When creating an OrgChart the following is missing:
`const orgChartControl = new OrgChart(...)`
`orgChartControl.config`
`orgChartControl.config`
`orgChartControl.on`
`orgChartControl.exportCSV`
I can use a workaround by converting it to any, but that is not the point of TypeScript.

**Comment by ZornitsaSerbezova** [comment]
Thank you, sks4u!
I have added all except orgChartControl, because I couldn't find it in the source.

**Comment by mpschaeuble** [comment]
OrgChart.templates seems to be missing, too.

**Comment by ZornitsaSerbezova** [comment]
Thank you, mpschaeuble!
We have added templates.

**Comment by fr34kyn01535** [comment]
The following things are still missing..

- [ ] sender.getBGNode()
- [ ] options.onExpCollClick
- [ ] OrgChart.menuUI
- [ ] OrgChart._guid
- [ ] chart.on('redraw')
- [ ] chart.on('drop')
- [ ] OrgChart.REMOVE_GROUP_IF_HAS_ONE_NODE
- [ ] OrgChart.MINIMIZE
- [ ] OrgChart.MAXIMIZE

**Comment by ZornitsaSerbezova** [comment]
Hi fr34kyn01535,
We have added these in .d.ts file.

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue, but feel free to reopen it if needed.
