### ISSUE TITLE
Department Design

### ISSUE THREAD

**Issue by javad1005** [BALKANGraph/OrgChartJS#324]
Hi
I have a problem
I want to implement the Department Node like the second image
can you help me
![myDesign](https://user-images.githubusercontent.com/60432873/74600216-4bcf7580-50a3-11ea-8dd2-1fbd5c0c8c30.jpg)
![Target](https://user-images.githubusercontent.com/60432873/74600228-64d82680-50a3-11ea-8055-a769feb7f291.jpg)

**Comment by ZornitsaSerbezova** [comment]
Hi javad1005,

If you mean the size of the node, you can see this example:
https://jsfiddle.net/BALKANGraph/3cpoh67r/

**Comment by javad1005** [comment]
dear ZornitsaSerbezova , thanks for your help. but my problem is not the size of the node! in fact, the problem is that when I add a department node,the distance(line) between children nodes and the department node , is depended on department side node, but I want the department node to be exactly on top of its children.
![chart](https://user-images.githubusercontent.com/60432873/74658025-ab627980-51a6-11ea-87dc-6bbcbec76d81.jpg)

**Comment by ZornitsaSerbezova** [comment]
Hi javad1005,

We have created a demo for you: https://balkangraph.com/OrgChartJS-Demos/CustomNodeSize
