### ISSUE TITLE
Read Data

### ISSUE THREAD

**Issue by uumi95** [BALKANGraph/OrgChartJS#327]
hello!
i need to read my data from this requet , i use MVC asp.net, Entity :
```
SELECT SALARIE.MATRICULE, LIEU, UO, UO_RATTACHEMENT, PHOTO.PHOTO, SALARIE.NOM, SALARIE.PRENOM
from SALARIE, UNITE_ORG, PHOTO
where SALARIE.LIEU= UNITE_ORG.UO
```

Thank u !

**Comment by ZornitsaSerbezova** [comment]
Hi uumi95,
You can use Entity Framework and our example for MVC: https://github.com/BALKANGraph/OrgChartWebApp
