### ISSUE TITLE
Customize templates

### ISSUE THREAD

**Issue by sujasuji** [BALKANGraph/OrgChartJS#329]
How to customize predefined templates in angular. As mentioned in documentation, it is throwing error.

**Comment by ZornitsaSerbezova** [comment]
Hi sujasuji,
The issue is fixed. Please download the latest version of OrgChart JS - 6.2.59.

**Comment by sujasuji** [comment]
> Hi sujasuji,
> The issue is fixed. Please download the latest version of OrgChart JS - 6.2.59.

How to install latest version using npm?

**Comment by ZornitsaSerbezova** [comment]
May be you can just reinstall it using the same command: npm i @balkangraph/orgchart.js
Actually it is enough to download the [package ](https://balkangraph.com/OrgChartJS/Download/DownloadEvaluate) and replace only the orgchart.d.ts file in your project.

**Comment by sujasuji** [comment]
Is it possible to use bootstrap or any style library for customizing nodes?

**Comment by ZornitsaSerbezova** [comment]
Hi sujasuji, 
for customizing nodes you need to use our documentation: https://balkangraph.com/OrgChartJS/Docs/CreatingCustomTemplate

**Comment by sujasuji** [comment]
Yes i am following documentation but am not able to use other html elements like div, span and styling libraries like bootstrap.. 
Does orgchart supports above requirements?

**Comment by plamen-peshev** [comment]
Yes you can use bootstrap

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue, but feel free to reoen it if needed, explaining what is the problem with an example.
