### ISSUE TITLE
Multiline group labels not rendering correct on IE

### ISSUE THREAD

**Issue by wimpie3** [BALKANGraph/OrgChartJS#33]
Multiline group labels are not rendering correct on IE (working fine in Chrome). The location if the second line seems to be wrong in IE.

**Comment by BALKANGraph** [comment]
I have tried to replicate, see https://1drv.ms/u/s!Ah4WnDCbGi3njepnNNYl-CBxRFNWUQ

What is different in your case?

**Comment by wimpie3** [comment]
We are using IE11.

**Comment by wimpie3** [comment]
It seems the y-coordinate of the second <tspan text-anchor> is too low, making the second line appear too low in IE11.

**Comment by BALKANGraph** [comment]
Can you please make sure that you are using Edge or IE user agent

![image](https://user-images.githubusercontent.com/43317667/54627066-3b6ddf80-4a7b-11e9-82ca-ace9f39da663.png)

**Comment by wimpie3** [comment]
Yes I'm using Edge mode in IE11. This is what goes wrong:
![image](https://user-images.githubusercontent.com/559680/54679334-4a9a6f00-4b07-11e9-94cb-54f8ff976ee9.png)

**Comment by wimpie3** [comment]
Bug still present in the latest version, unfortunately...

**Comment by plamen-peshev** [comment]
Provide a demo where we can see the issue. and eventually fix it

**Comment by wimpie3** [comment]
Can't provide a demo since JSFiddle does not support IE, but the problem is linked to having **line-height: 160%;**  in the **body**. Apparently IE uses this line height in the SVG and Chrome doesn't. I'm currently trying to find a way around this but if you have another solution, feel free.

**Comment by wimpie3** [comment]
Update: setting line-height to a px value instead of %, resolves the problem. I've added **svg {line-height;50px;}** and the problem is resolved.

**Comment by plamen-peshev** [comment]
Great!
