### ISSUE TITLE
children nodes custom placement

### ISSUE THREAD

**Issue by Michele-91** [BALKANGraph/OrgChartJS#332]
Hi,
I am trying to replicate what I see in https://balkangraph.com/OrgChartJS-Demos/ConditionalColor.
In this example, the children of Janae Barrett are placed next to each other, whereas the children of Lexie Cole are placed on top of each other. What is the option I can use to tell OrgChart to place the children of a certain node differently like that? I can't find anything in this regard in the documentation.

Thank you in advance.

**Comment by ZornitsaSerbezova** [comment]
Hi Michele,

This view is coming from the layout OrgChart.mixed You can see the layouts here: https://balkangraph.com/OrgChartJS/Docs/Layout


Regards,
zornitsa

**Comment by Michele-91** [comment]
Thank you for your quick reply.
Is there a way to instruct the OrgChart when the new child node will be added vertically, and when horizontally compared to its siblings?

**Comment by ZornitsaSerbezova** [comment]
No, this is automatically calculated,

**Comment by Michele-91** [comment]
alright, thank you!
