### ISSUE TITLE
Can't show images when transferring OrgChart in Pdf, PNG

### ISSUE THREAD

**Issue by uumi95** [BALKANGraph/OrgChartJS#333]
Hi !
I have images in binary format, I found a solution to display them, but when I import in pdf the images not display.
The solution is to display the images in a web page and assign the address of this page to 'img' as this code shows:
` public JsonResult Read()
        {
            
                             var nodes = (from s in entities.AGENT
                         from u in entities.UNITE_ORG
                         from f in entities.PHOTO
                         where s.MATRICULE ==  u.RESPONSABLE && f.MATRICULE==s.MATRICULE
                         select new NodeModel() { 
                             id= u.UO,
                             pid= u.UO_RATTACHEMENT,
                             responsable = u.RESPONSABLE,
                             matricule = s.MATRICULE,
                             nom= s.NOM,
                             prenom= s.PRENOM,
                              img= "http://localhost:26752/WebForm1.aspx?matricule=",

                             poste = u.POSTE,
                             
        });
           
            return Json(new { nodes = nodes }, JsonRequestBehavior.AllowGet);
        }`

What i should do to show pictures when transferring in PDF,PNG?

**Comment by ZornitsaSerbezova** [comment]
Hi uumi95,

I guess you are using the default (our) export service. In order the images to be exported, you need to upload them on a web service.
If you still would like to use local images, you will need to install your own [export service.](https://github.com/BALKANGraph/export-service)

**Comment by ZornitsaSerbezova** [comment]
Hi uumi95,
I gess that you have managed to solve your problem, so I'll close this issue. Feel free to reopen it if needed.
