### ISSUE TITLE
The trial has expired or 200 nodes limit was reached how it is solve

### ISSUE THREAD

**Issue by SaqlainMustafa** [BALKANGraph/OrgChartJS#334]
i want to increase nodes it is possible ?

**Comment by ZornitsaSerbezova** [comment]
Hi SaqlainMustafa,

You will need to purchase a license for the product from our [store](https://balkangraph.com/OrgChartJS/Store).

**Comment by SaqlainMustafa** [comment]
ok in old version of organization chart the front view of nodes is not good like all node are open defaults.
i want to apply nodes open onclick and default open just CEO of organization

**Comment by ZornitsaSerbezova** [comment]
HI SaqlainMustafa,

To collapse all nodes except the CEO, you can use this option:
`  
collapse: {
        level: 1
},`

**Comment by SaqlainMustafa** [comment]
HI sir thank for your reply

sir can You tell me some detail about like a small demo

**Comment by ZornitsaSerbezova** [comment]
Hi SaqlainMustafa,
Here is a small demo for you: https://jsfiddle.net/BALKANGraph/7gLr8c3w/

**Comment by SaqlainMustafa** [comment]
THANKS

**Comment by SaqlainMustafa** [comment]
SIR Can u tell me how to apply this code in old JS version i want to open just first layer under ceo and all other hide in first layer

**Comment by SaqlainMustafa** [comment]
Sir for example i have 205 nodes but default all nodes are open  i want to adjust this like new version page open  but in new version add maximum 200 nodes how to set nodes like new version library when we click 1 nodes then other nodes to open in my old library

**Comment by ZornitsaSerbezova** [comment]
Hi SaqlainMustafa
You can use these options only with the new version.
You will need to purchase a license for the product from our store.
https://balkangraph.com/OrgChartJS/Store

**Comment by SaqlainMustafa** [comment]
Ok
