### ISSUE TITLE
Save version of org chart

### ISSUE THREAD

**Issue by uumi95** [BALKANGraph/OrgChartJS#335]
how to save version of organization chart , to use it when i want ?
i want to use DropDoun select to load different charts

**Comment by ZornitsaSerbezova** [comment]
Hi uumi95,
You can load as many different charts as you need, but you have to get the data from your "server" side. So if you need to save the chart, you have to save it in your data,

For more help, you can see our examples:
[How to create OrgChart JS using MS SQL database and ASP.NET MVC](https://github.com/BALKANGraph/OrgChartWebApp)
[Select from drop down menu and loading different charts.](https://balkangraph.com/OrgChartJS-Demos/SelectBetweenCharts)

**Comment by ZornitsaSerbezova** [comment]
Now you can save state with the latest version (7.5.23):
https://balkangraph.com/OrgChartJS/Docs/APIReference#state
