### ISSUE TITLE
custom field with textarea element, cannot see the value corresponding tothe field

### ISSUE THREAD

**Issue by zhousheng1114** [BALKANGraph/OrgChartJS#336]
# custom field 
`OrgChart.templates.myTemplate.field_0 = '<textarea style="font-size: 24px; white-space:pre-wrap;" fill="#ffffff" x="100" y="90" text-anchor="middle">{val}</textarea>'`

# render result
![20200401172823584](https://user-images.githubusercontent.com/30176131/78121828-73558400-743e-11ea-8f81-d24d6a0b78e8.jpg)

# source code
textarea element is already exist in dom
![image](https://user-images.githubusercontent.com/30176131/78121454-fde9b380-743d-11ea-9933-9062b727b88c.png)

by the way,how to display multiple lines text in a node

**Comment by ZornitsaSerbezova** [comment]
Hi zhousheng1114,

Here is the documentation about multiline: [https://balkangraph.com/OrgChartJS/Docs/TextOverflow](https://balkangraph.com/OrgChartJS/Docs/TextOverflow)

Regards,
Zornitsa

**Comment by zhousheng1114** [comment]
thank you for your reply.i have read this part of document.and i encountered a new problem，as shown in below
![360截图20200401195152856](https://user-images.githubusercontent.com/30176131/78134168-47dc9480-7452-11ea-90a6-959b281e0d7c.jpg)

seems to no warp at consecutive characters

**Comment by ZornitsaSerbezova** [comment]
We don't support long words as this one yet,

**Comment by zhousheng1114** [comment]
All right！Thank you.
