### ISSUE TITLE
CSS Customization not work when export with css file

### ISSUE THREAD

**Issue by rogeriocc** [BALKANGraph/OrgChartJS#337]
I'm trying to load css file using as explained, but it doesn't work:

  chart.on ('exportstart', function (sender, args) {
     args.content + = '<link src="http://localhost/test/assets/css/orgchart.css" />';
   });

Am I doing something wrong?

**Comment by ZornitsaSerbezova** [comment]
Hi rogeriocc,

Do you mean as in this demo, because here we don't use external file?
https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/ExportStyles


Regards,
Zornitsa

**Comment by rogeriocc** [comment]
Hi Zornitsa,

This way it works correctly, however, I would have to leave the CSS in the same orgchart JS file, and as I have a lot of customization of css for many different legends, variations of nodes, etc., it is not cool, my file will be very big.
The ideal would be to be able to add the css of a sternum file, I tried in several ways but I couldn't.

Regards,
Rogério

**Comment by ZornitsaSerbezova** [comment]
Hi rogeriocc,

Could you try this:
args.content += '<link href="path to the css file" rel="stylesheet">';

**Comment by rogeriocc** [comment]
Hi Zornista,

I tried it, but it didn't work, compressed the CSS and put it directly in the .JS file and used it as mentioned in your example, it's not how I would like it, but it's working for now.

args.content + = document.getElementById ('myStyles'). outerHTML;

Regards,
Rogério

**Comment by ZornitsaSerbezova** [comment]
Hi rogeriocc,

In order to be able to export css from external file, this file also need to be accessible outside, because the export service needs to have access to it.

**Comment by rogeriocc** [comment]
Hi Zornista,

I understand, our organization chart is not yet in production, we are taking longer than expected due to internal problems.
At https://balkangraph.com/console/, is there a possibility to set up an export service, in which case would it resolve or would it still only work when it is in the publicly accessible part?

Thank you for the patience!

**Comment by ZornitsaSerbezova** [comment]
Hi rogeriocc,
You could also install your own export service: https://github.com/BALKANGraph/export-service
