### ISSUE TITLE
Second Parent: Dottet line possible?

### ISSUE THREAD

**Issue by hdbrinkmann** [BALKANGraph/OrgChartJS#34]
...I am evaluating OrgChartJS and am trying to use the 2nd Parent like this "spids: [12983]". It works fine, How can I change the line-type from the orange line used by default to a dottet line?

I appreciate your help,
Dirk

**Comment by BALKANGraph** [comment]
Created a demo for you:

https://balkangraph.com/js/demos/change-second-link-style.html
