### ISSUE TITLE
Is it possible to use multiple chart layout/theme/orientation?

### ISSUE THREAD

**Issue by rhalp10** [BALKANGraph/OrgChartJS#342]
Is it possible to use multiple layouts and attain this kind of chart? and use HTML in one of the nodes ?
![image](https://user-images.githubusercontent.com/13925864/78593674-97b7c300-7879-11ea-9fe0-e78800ab9cf2.png)

**Comment by rhalp10** [comment]
It's possible to use multiple layouts themes. I use this snippet on the demo it's called "[Alignment](https://balkangraph.com/OrgChartJS-Demos/Alignment)".

so far this is the best I could do and on my issue, https://jsfiddle.net/051hpqtf/

On Hierarchy style from 1 parent to many children. 
This layout is easy. 
 #1 ![image](https://user-images.githubusercontent.com/13925864/78612710-99df4900-789c-11ea-9432-bcaed6a8595f.png)

But when creating an inverted layout of #1 like this, you cant easily produce it, you have to group them so basically it still looks like #1.
#2 ![image](https://user-images.githubusercontent.com/13925864/78612749-b24f6380-789c-11ea-988c-4310e07f91dc.png)

Then what if you wanted to merge the layout #1, #2 to look like this.
#3 ![image](https://user-images.githubusercontent.com/13925864/78613100-81bbf980-789d-11ea-8b33-fdee876000ee.png)
Is there any way to do it?

**Comment by ZornitsaSerbezova** [comment]
Hi rhalp10,

Here in **Link text field** section we have an example about HTML fields:
https://balkangraph.com/OrgChartJS/Docs/Fields

About the layouts - OrgChart doesn't support different layouts in one chart.


Regards,
Zornitsa

**Comment by rhalp10** [comment]
@ZornitsaSerbezova  Ok, Thanks.

**Comment by ZornitsaSerbezova** [comment]
https://github.com/BALKANGraph/OrgChartJS/releases/tag/7.6.12
