### ISSUE TITLE
Assistant with children.

### ISSUE THREAD

**Issue by rogeriocc** [BALKANGraph/OrgChartJS#345]
Hello, how are you?

I had already requested the functionality of placing child nodes in the assistant a little less than a year ago, I would like to ask again, it would be very interesting that it was possible to place child nodes in the assistant, many organizations use this way in the organizational structure.

I believe that you would reach more customers with the possibility of this functionality.

Please analyze this possibility with affection, we need it very much here! =)

Sorry for my English!

Kind regards,
Rogerio

**Comment by plamen-peshev** [comment]
In the latest version 6.2.64 children under assistant is supported



![image](https://user-images.githubusercontent.com/49443821/79108158-6742be00-7d7e-11ea-907f-0f3477df1d6d.png)

**Comment by rogeriocc** [comment]
Plamen-peshev,
Thanks for the feedback, this feature helps a lot !!!
I know it is a complex job, but now for a more correct display, it would be interesting to stay as below, for example, where the assistant's child nodes are not aligned with the other nodes, but push them down and also that the alignment the root node is aligned.
Is it possible in future versions to do so?

Today it looks like this: [https://jsfiddle.net/rogerioccosta/9bLs704z/1/](url)

Could look something like:

![assistant_option](https://user-images.githubusercontent.com/2631583/79255025-01c4ff00-7e5c-11ea-97f5-5a03c0fa7756.png)

Sorry for my English.

**Comment by ZornitsaPesheva** [comment]
I was able to achieve what you need: https://jsfiddle.net/rkwnmq1e/

**Comment by ZornitsaPesheva** [comment]
I'll close this issue as it looks inactive,  Feel free to reopen it if needed.

**Comment by ZornitsaPesheva** [comment]
Implemennted in 8.02.19
Thank you for your patience.
