### ISSUE TITLE
Support for auto height nodes

### ISSUE THREAD

**Issue by miftah1991** [BALKANGraph/OrgChartJS#346]
we have implemented this chart but doesn't work for us as balkangraph not support auto height nodes.

**Comment by plamen-peshev** [comment]
As work around you can use [this ](https://balkangraph.com/OrgChartJS-Demos/ListsInNodes) approach 

The current version does not support auto height, we are doing our best to add it in one of the future releases

**Comment by miftah1991** [comment]
@plamen-peshev  Thanks BALKANGraph team your support is highly appreciated.
