### ISSUE TITLE
Edit UI

### ISSUE THREAD

**Issue by burakkkara** [BALKANGraph/OrgChartJS#347]
We are using your product in React, and we want to customize and override editUi component. I found  a couple of demo that shows how to do this using js and html, however, that solution is not applicable in our use cases since we are developping in React. Is there any way that we can pass a functional component to the editUI object. For instance;
`orgChart = new OrgChart(chart.current, {
            ...props,
            /*
            editUI: Demo() or
            editUI: new Demo() or
            editUI: <Demo/>
            */
        });`
like in one of these 3 ways.
Demo is
`const Demo =() => {
       return(
           <div>Demo</div>
            );
}`

**Comment by ZornitsaSerbezova** [comment]
Hi Burak,

You could get an example for editing the editUI from **Custom Edit Form** section on our **docs** page: https://balkangraph.com/OrgChartJS/Docs/Edit
This is the example: https://jsfiddle.net/BALKANGraph/vpz1rfmt/?utm_source=website&utm_medium=embed&utm_campaign=vpz1rfmt

We don't have examples for React,
