### ISSUE TITLE
Change Chart Nodes Content Base On Ajax

### ISSUE THREAD

**Issue by rhalp10** [BALKANGraph/OrgChartJS#349]
Hello, I have a problem with this, when clicking a dropdown or button it should get the nodes on the chart base on year. I implemented this chart on SharePoint.

In [Method 1](https://gist.github.com/rhalp10/ddd1aa31a99d74b3326e1b7d89141f33) - It really gets the nodes per year but the nodes of the year are merging because of `chart.add()`  I tried to use `chart.draw(OrgChart.action.init)` to redraw the chart but still has the value of the old year.

[Method 2](https://gist.github.com/rhalp10/75977694578bd18c30dfd14bbc6dd95b) - I tried to make a blank array as container name `var data =[]` and use `data.push({...});` to push the new nodes in array . but didn't load the content. even I got data on the console. 
![image](https://user-images.githubusercontent.com/13925864/79807707-4beb3a80-839e-11ea-926e-f7b29eb6823e.png)
it only gives me `It's lonely, here add your first node` 

Method 2 is working, it's really weird to make it work is when inspecting the page, the content will appear correctly base on year but it always loads the `It's lonely, here add your first node`.

**Comment by plamen-peshev** [comment]
Make sure that you have only one instance of the chart and call chart.load method

chart.load([your filtered json data from your server])

**Comment by rhalp10** [comment]
@plamen-peshev   yes and I resorted to used `chart.load()` then this what I got. every time I load the data this is what its look like 
![ezgif-3-75e67a3f56ef](https://user-images.githubusercontent.com/13925864/79890790-96b69200-8432-11ea-8762-50a2e993e5d7.gif)
I have to resize the browser in order to show the chart content.
but if I declare a static data the chart instantly shows unlike the ajax.
```
var data = [{  id: 4,
                        Name: "NameHere",
                        Title: "CEO, Admin",
                        Profile: "https://vetri.global/wp-content/themes/vetri/images/avatar_default.png"
                    }];
```

**Comment by plamen-peshev** [comment]
See [this](https://balkangraph.com/OrgChartJS-Demos/SelectBetweenCharts) demo

What is different in you case

**Comment by rhalp10** [comment]
I follow that demo, but in my case, The chart thinks the data is empty if I populated it using ajax.
as you can see on this [preview](https://user-images.githubusercontent.com/13925864/79890790-96b69200-8432-11ea-8762-50a2e993e5d7.gif), the chart will load and the data will appear by resizing the browser.

**Comment by ZornitsaSerbezova** [comment]
What is different in your code? Could you edit [this ](https://balkangraph.com/OrgChartJS-Demos/SelectBetweenCharts)demo to get the same error as in your code?

**Comment by rhalp10** [comment]
> What is different in your code? Could you edit [this ](https://balkangraph.com/OrgChartJS-Demos/SelectBetweenCharts)demo to get the same error as in your code?

ok, sorry for the late reply I've busy these past few days, I fix this issue. I'm gonna post it here soon.

**Comment by ZornitsaSerbezova** [comment]
Hi rhalp10,

I'll close this issue, but it will be good if you post your solution.

**Comment by rhalp10** [comment]
To fix this issue I just add **`async: false,`** in my ajax call. Every time the dropdown change value by year it will call
 the **`dataNodes(chart,yearID)`** function and grab the chart data content.
```
  function dataNodes(chart,yearID) {
      var  data = [];
      requestUri = "/_api/lists/getbytitle('chart_person')/items?$filter=Year eq " + yearID + "";
      $.ajax({
          async: false,
          url: requestUri,
          type: "GET",
          headers: {
              "ACCEPT": "application/json;odata=verbose"
          },
          success: function(idata) {

              var items = idata.d.results;
              for (var i = 0; i < items.length; i++) {
                    var iTag = items[i].Tags;
                    var gTags = iTag.split(",");
                   data.push({
                       id: items[i].ID,
                       pid: items[i].PID,                      
                       tags: gTags,
                       Name: items[i].PName,
                       Title: items[i].Title,
                       Profile: items[i].Image
                  });
               
              }
              chart.load(data);
              

          },
          error: function() {
              alertify.error('Field to load chart');
          }
      });
  }
```
Sorry for super late posting my solution.
