### ISSUE TITLE
PDF Export Issue

### ISSUE THREAD

**Issue by hdbrinkmann** [BALKANGraph/OrgChartJS#35]
I created a first Orgchart using OrgChartJS. There seems to be a problem with PDF Export. Please use the attached HTML File, open the Node "Ebbi, Stefan" and the nodes below. Then use "PDF Export". 

On my computer (Macbook Mojave, Chrome Browser) nothing will be exported. CSV works fine and sometimes I get PDF exports, but it seems not to be working every time.

[4PLANOrgChart.html.zip](https://github.com/BALKANGraph/OrgChartJS/files/2975336/4PLANOrgChart.html.zip)

**Comment by BALKANGraph** [comment]
It was an issue in the export server

Now it is fixed

**Comment by hdbrinkmann** [comment]
Great, thank you. Do I need to update the Orgchart.js file on my server?

**Comment by BALKANGraph** [comment]
No

If you host Export Service on your own server you should update it

**Comment by hdbrinkmann** [comment]
Currently I am using your export Server. However, if I wanted to run my own Export Server how would I set it up? I found the article in your documentation but I don't know what software to install on the Server. :-)

**Comment by hdbrinkmann** [comment]
Ok, thank you very much!

**Comment by hdbrinkmann** [comment]
The bug is back, I cant export to PDF today (CSV works fine). :(

**Comment by shaipetel** [comment]
Just got a call from a client, export to PDF/PNG returns an error 400 (Bad Request).

Error in the console reads: "POST https://balkangraph.com/export/png 400 (Bad Request)" and there is no indication to the user at all (button just doesn't do anything).

Could you comment on this, if there is a bug in the server again? Or could this be specific to my view/data?

Please advise.

**Comment by plamen-peshev** [comment]
There is no issue with the export service, you can test [here ](https://balkangraph.com/OrgChartJS/Demos/Exporting)

I would suggest you to install export service on your server

**Comment by shaipetel** [comment]
So, we started getting error 400 on the same graph without any change on our code or data.
How can we debug or diagnose this?

**Comment by plamen-peshev** [comment]
option 1: update to the latest version of OrgChart JS
option 2: create a demo in jsfiddle where we can see the issue

**Comment by shaipetel** [comment]
upgrading to latest version worked. thanks!

**Comment by M-Mzoughi** [comment]
I have the same bug, I can't export to PDF yesterday and today  :(

**Comment by M-Mzoughi** [comment]
![6](https://user-images.githubusercontent.com/70006749/91219010-3f933780-e71a-11ea-8c86-50688d34ccaa.png)

**Comment by ZornitsaSerbezova** [comment]
Hi M-Mzoughi,

These days we did update the export functionality and made lot of test, so that could have been the reason. 
Could you try again if it works?
