### ISSUE TITLE
Alignment issues when collapsed nodes have group assistants as children

### ISSUE THREAD

**Issue by remosiegwart** [BALKANGraph/OrgChartJS#350]
We are heavily using group assistants in our org chart. Unfortunately, there seems to be an issue with the alignment of collapsed nodes when they have group assistants as children. In this case the nodes are not being separated evenly anymore:

![2020-04-24_122846](https://user-images.githubusercontent.com/2592249/80203637-c11d7080-8627-11ea-8875-803af534a432.png)

I've been able to reproduce this in the following fiddle based on your group assistant demo: https://jsfiddle.net/4j9odnq8/1/

Any help would be appreciated. Thanks!

**Comment by plamen-peshev** [comment]
The issue is fixed in version 6.2.68

**Comment by remosiegwart** [comment]
Great, thank you very much for the prompt fix! The alignment issue indeed seems to be fixed now!

Unfortunately, we can't update to version 6.2.68 as it looks like the new version breaks our custom expand/collapse behavior. We use the same custom expand/collapse behavior as in your demo here (reproducible in the demo, when you try to expand a child node): https://balkangraph.com/OrgChartJS-Demos/15kNodesCustomExpandCollapse

Does it have to be rewritten or is this another bug?

**Comment by plamen-peshev** [comment]
"custom expand/collapse behavior" is fixed in version 6.3.2

**Comment by remosiegwart** [comment]
Thanks for letting me know about the new version 6.3.2. I've tested the alignment issues in the new version 6.3.2 thoroughly, but unfortunately I think this issue hasn't been properly fixed yet. The org chart is being initialized correctly, but as soon as you call `chart.draw()` the nodes are not being separated evenly anymore (same issue as displayed in screenshot above).

You should be able to reproduce this easily in the following fiddle, where i call `chart.draw()` 5 seconds after the chart has been loaded: https://jsfiddle.net/0mtq4wab/

But the same also applies every time when you e.g. resize the window, export the chart, etc.

Would be great, if you could have a look at it again, thanks!

**Comment by plamen-peshev** [comment]
Thank you for reporting this issue again 

Fixed in version 6.3.3

**Comment by remosiegwart** [comment]
Thanks for the prompt fix! It's working like a charm now!
