### ISSUE TITLE
Rearrange nodes within a level in the editor

### ISSUE THREAD

**Issue by DavePCoder** [BALKANGraph/OrgChartJS#351]
I can easily drag and drop nodes across the chart, but with a level i can't see a way to re-arrange the order of the sub-ordinates.  Is there a way to do this interactively, or am i forced to edit the source data.  For example on your basic usage chart at:
https://balkangraph.com/OrgChartJS/Demos/BasicUsage

How can i move Caden Ellison to be on the left and Ashley Barnett to be on the right.  I couldn't see an API command for it either?

**Comment by ZornitsaSerbezova** [comment]
Hi Dave,
We have created a demo foe changing the order with Drag and Drop: https://balkangraph.com/OrgChartJS-Demos/ChengeNodesOrder
To change it in the editor, you just need to change the value of myOrderId,

**Comment by DavePCoder** [comment]
Excellent - thank you.  I'll try and combine it with other examples so you can also still move things under a node as well as rearrange within a level.
