### ISSUE TITLE
Changing element on the same level has an incorrect update event

### ISSUE THREAD

**Issue by vhunyad** [BALKANGraph/OrgChartJS#352]
Situation: node1->group1(node2,node3)
Problem1:
If I drag node2 out of the group and drop still under node1 but separately (add as child), update event is fired, but still shows the unchanged tags. I can not catch the change via events. The same happens in the opposite direction, so it seems that if the parent does not change, the event data is incorrect.
Problem2:
In these cases even updateTags is not fired at all, however on your demo page it seems always firing.
https://balkangraph.com/OrgChartJS-Demos/EventHandlers

**Comment by ZornitsaSerbezova** [comment]
Hi vhunyad,
Could you send us a video screen record with the exact steps that you are doing?

**Comment by vhunyad** [comment]
https://drive.google.com/file/d/1IVv_vS_jBpvEAvI5THfCADnl1DQ4e-o_/view
When your remove node3 from the group and assign it as a child to the same parent, the update event is fired, but the old and new node is exactly the same. So there is no way to realise the change.

**Comment by vhunyad** [comment]
One more example: in the above case the group disappears because of the 2 members, but if there are 3 members in the group and we only remove one, than the group remains. That version need to be checked as well.

**Comment by ZornitsaSerbezova** [comment]
Tags are changing. Here you can see the tags: 
1-after adding
2-after grouping
3-after adding one node as child of node 1
![image](https://user-images.githubusercontent.com/19305472/80507728-d411a700-897f-11ea-9ff2-61c2b49f9b41.png)

**Comment by ZornitsaSerbezova** [comment]
> One more example: in the above case the group disappears because of the 2 members, but if there are 3 members in the group and we only remove one, than the group remains. That version need to be checked as well.

There is a cons REMOVE_GROUP_IF_HAS_ONE_NODE, that is set to true by default.

**Comment by vhunyad** [comment]
Thanks for the quick answer. What can I have misconfigured if I experience that the old node and the new node is the same? Here you can see the console, where I have the old and new node logged. The new still has the tags.
![image](https://user-images.githubusercontent.com/17292468/80517376-4638ba80-8985-11ea-899e-034b09654f0d.png)

**Comment by vhunyad** [comment]
Additional info: when I check the same situation at redraw, it already changed. So I am thinking about checking changes at redraw as a workaround.

**Comment by ZornitsaSerbezova** [comment]
This is on "update":

Creating group:
![image](https://user-images.githubusercontent.com/19305472/80520017-8736cc00-8991-11ea-9b22-3bcd52bd8f24.png)

Adding the third node:
![image](https://user-images.githubusercontent.com/19305472/80520200-c6fdb380-8991-11ea-839f-b133cc953e39.png)

Adding as a child of Node 1 outside of the group:
![image](https://user-images.githubusercontent.com/19305472/80520346-f6142500-8991-11ea-8ebb-ebc12e21cc9c.png)

**Comment by vhunyad** [comment]
Thanks. What can i have misconfigured? Can it be because of loading from DB? I am using a setup from loading from DB, not a clean sheet approach.

**Comment by ZornitsaSerbezova** [comment]
No, it doesn't matter, but you could try to create a simple example with hardcoded data.
You could use my code as starting point:
`      var chart = new OrgChart(document.getElementById("tree"), {
        enableDragDrop: true,
        nodeBinding: {
            field_0: "name"
        },
       nodeMenu: {
         add: {text: "add"},
         edit: {text: "edit"}
       },
       dragDropMenu: {
            addInGroup: { text: "Add in group" },
            addAsChild: { text: "Add as child" }
        },
    });

    nodes = [
      { id: 1, name: "node 1" }
        ];

        chart.on('update', function (sender, oldNode, newNode) {
            console.log(nodes);
        });  

        chart.load(nodes);`

**Comment by vhunyad** [comment]
Thanks, actually you proved my point, because you use the external nodes variable, not the newNode variable in the update event. Here is your code, I only added the newNode to the console.log. 
![image](https://user-images.githubusercontent.com/17292468/80530464-535fa480-8999-11ea-8e8e-c732fb089176.png)
