### ISSUE TITLE
How i can modify the Fields windows that appears when i click in a node

### ISSUE THREAD

**Issue by redleon00** [BALKANGraph/OrgChartJS#353]
Hi, im trying to find the way to modify the Fields windows that appears when i click in a node (i don't know if somebody understand me).
I want to do this, when i click some node i want to show in the auxliar frame a field information but the data is so long and can't see completly. Please see in the image in the link above.
[https://ibb.co/dGWCcF8](url)

**Comment by ZornitsaSerbezova** [comment]
Hi redleon00,
Here we have a demo that is showing you how to create multiline field: https://balkangraph.com/OrgChartJS-Demos/CustomField

**Comment by redleon00** [comment]
Excellent !! .. worked perfectly!! Thank u ZornitsaSerbezova
