### ISSUE TITLE
Slinks of hidden nodes

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#354]
I have an issue with Slinks.  If the child is not visible because the tree is not expanded up to it, then no dotted line is displayed.
![DottedLinesExpanded](https://user-images.githubusercontent.com/55696440/80682838-8aca7000-8ac3-11ea-9781-dc3a9f5f55c3.PNG)
If I now collapse the node, the following is displayed:
![DottedLinesColapsed](https://user-images.githubusercontent.com/55696440/80682863-93bb4180-8ac3-11ea-9550-3a6948eaec73.PNG)

I would like to implement now that the child is shown under its second parent in this case.
![DottedLinesCollapsed2](https://user-images.githubusercontent.com/55696440/80683081-e72d8f80-8ac3-11ea-9d05-c1c262b84bdc.png)

Do you have an idea how I can implement this?

**Comment by ZornitsaSerbezova** [comment]
Hi sks4u,
Could you try this solution?
https://github.com/ZornitsaSerbezova/issues/blob/master/354.html

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue, but feel free to reopen it explainig what is the problem if needed.
