### ISSUE TITLE
Custom expand/collapse behavior not working anymore

### ISSUE THREAD

**Issue by remosiegwart** [BALKANGraph/OrgChartJS#355]
We use the same custom expand/collapse behavior as in your demo here: https://balkangraph.com/OrgChartJS-Demos/15kNodesCustomExpandCollapse

Unfortunately, it doesn't seem to be working anymore since version 6.2.68. A click on a child node doesn't expand the node, but hides all other nodes of the graph.

The issue is also reproduceable in the following fiddle: https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/15kNodesCustomExpandCollapse

Any help would be appreciated, thanks!

**Comment by ZornitsaSerbezova** [comment]
Hi remosiegwart,

We have fixed this issue in the current version (6.2.68).

Regards,
Zornitsa

**Comment by remosiegwart** [comment]
Thanks for letting me know about the new version 6.3.2. The custom expand/collapse behavior indeed seems to be fixed now. But unfortunately, it looks like the new version has broken the regular expanding/collapsing of nodes that have group assistants as children.

You can reproduce this in your demo here, when you collapse/expand the root node (Denny Curtis): https://balkangraph.com/OrgChartJS/Demos/Assistant

![2020-05-12_145017](https://user-images.githubusercontent.com/2592249/81693540-5a3deb00-9460-11ea-9572-c2e72e7a8b0e.png)

![2020-05-12_145140](https://user-images.githubusercontent.com/2592249/81693592-6de95180-9460-11ea-9dd6-dd2c6d646d0c.png)

**Comment by plamen-peshev** [comment]
Fixed in version 6.3.5

**Comment by remosiegwart** [comment]
Great, it's working again! Thanks for the prompt fix!
