### ISSUE TITLE
Property 'collapse' does not work

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#357]
The tree is initially fully expanded, even though I set the 'collapse' property:

var chart = new OrgChart(document.getElementById('tree'), {
collapse: {
        level: 2,
        allChildren: true
      },
...

**Comment by ZornitsaSerbezova** [comment]
Could you give us an jsfiddle example, because I couldn't reproduce the problem?

**Comment by sks4u** [comment]
Unfortunately I cannot reproduce the problem in 'jsfiddle'. But I have created a sample program in Angular where you can observe the problem. I have created a typescript class for the 'collapse' option, as you can see here:
![OrgchartCollapseOptions](https://user-images.githubusercontent.com/55696440/83539940-f86d2000-a4f7-11ea-9a1e-864283d1961a.PNG)
Nevertheless the tree is displayed fully expanded
[org-chart-sample.zip](https://github.com/BALKANGraph/OrgChartJS/files/4718183/org-chart-sample.zip)

**Comment by ZornitsaSerbezova** [comment]
Hi sks4u,
I couldn't run your project, but I have tried this way and it works in angular:
```
var chart = new OrgChart(document.getElementById('tree'), {
                  nodeBinding: {
                    field_0: "name",
                    field_1: "title",
                    img_0: "img"
                  },
                  collapse: {
                    level: 2,
                    allChildren: true
                    },
                });
```

**Comment by sks4u** [comment]
Why can't you run my project? I'm afraid that will be necessary to find the source of the issue.

**Comment by ZornitsaSerbezova** [comment]
This is the error that I get:
```
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
Require stack:
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\index.js    
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\commands\serve-impl.js
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js  
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "C:\Users\user\AppData\Local\Temp\ng-tslCRO\angular-errors.log" for further details.
```

**Comment by ZornitsaSerbezova** [comment]
Hi sks4u,
Did you manage to solve this issue?

**Comment by ZornitsaSerbezova** [comment]
I have found that if you remove this line from **orgchart.component.ts** the collapse works.
`this.orgChartConfig = <OrgChartOptions>(<any>this.orgChartControl).config;`
May be you are overwriting something there.

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue as it looks inactive.
