### ISSUE TITLE
OrgChart js Functionality 

### ISSUE THREAD

**Issue by akashasnani** [BALKANGraph/OrgChartJS#36]
I m using Org chart Js for Assign , Add , update ,Delete employee Hierarchy  Using Handlers Event ,

Now i want to add Drop and Drag functionality in Orgchart js but i could not find a specific event For Handling Drop and Drag Event  .

So Please help me for this  .

**Comment by BALKANGraph** [comment]
You can use onUpdate method, see https://jsfiddle.net/gh/get/library/pure/BALKANGraph/Demos/tree/master/OrgChart/EventHandlers
