### ISSUE TITLE
Is it possible to highlight a clicked node?

### ISSUE THREAD

**Issue by enniob** [BALKANGraph/OrgChartJS#360]
I need to be able to add a border around the selected node when the user click and persist the border until the user click on the node again. Is this possible to do?

**Comment by ZornitsaSerbezova** [comment]
Hi enniob,
You could use these demos as starting point:
https://balkangraph.com/OrgChartJS-Demos/SingleAndDoubleClickOnNode
https://balkangraph.com/OrgChartJS-Demos/CustomTemplateSquare
https://balkangraph.com/OrgChartJS-Demos/SelectNodesWithCtrlClick

Regards,
Zornitsa
