### ISSUE TITLE
Show node in collapsed group

### ISSUE THREAD

**Issue by lindsoe** [BALKANGraph/OrgChartJS#361]
By default a collapsed group of nodes shows an empty card and the group name. Would it by possible to show the first node in a group, when the group is collapsed.

**Comment by ZornitsaSerbezova** [comment]
Hi lindsoe,

OrgChart JS don't support such option.

**Comment by ZornitsaSerbezova** [comment]
Hi lindsoe,

In the new version of OrgChart JS we have new implementation of groups. You should be able to achieve what you need witrh it.
I'll close this issue, because it is not relevant anymore.
