### ISSUE TITLE
Can save node information to DB?

### ISSUE THREAD

**Issue by WebDeveloper970903** [BALKANGraph/OrgChartJS#362]
Hi thanks for this opportunity.
I am a web developer and want to know details.
What I want to know is 
1. can save node information to DB and load it so that draw chart with that?
2. can I make each node to be updated?
   for example I want to change roll and name by double clicking node.
Please let me know kindly.
Thanks again.

**Comment by ZornitsaSerbezova** [comment]
Hi WebDeveloper970903, 

1. Here we have a demo on how to use OrgChart JS with ASP .NET: 
MVC - https://github.com/BALKANGraph/OrgChartWebApp
Webforms - https://github.com/plamen-peshev/OrgChartWebForms

2. You can update orgchart nodes by "Edit" option from the nodeMenu. This is the default update option, but you could do it other ways also, including double click. 
Here we have a demo on how to set single and double click on a node:
https://balkangraph.com/OrgChartJS-Demos/SingleAndDoubleClickOnNode

Regards,
Zornitsa

**Comment by WebDeveloper970903** [comment]
Thanks
