### ISSUE TITLE
drag issue when parent is dragged onto child

### ISSUE THREAD

**Issue by davitCB** [BALKANGraph/OrgChartJS#363]
when I drag parent onto child node the part of the tree disappears, can I fix this?

**Comment by davitCB** [comment]
I added recursive check for all children and returned false from update function, and it seems solved the issue, but I guess you should add that check in the library

**Comment by ZornitsaSerbezova** [comment]
HI davitCB,

We have this in our to do list and it will be added in one of the future updates.

**Comment by ZornitsaSerbezova** [comment]
Fixed in the new version.
