### ISSUE TITLE
Resize OrgChart

### ISSUE THREAD

**Issue by enniob** [BALKANGraph/OrgChartJS#364]
What is the best way to resize the OrgChart when the user resize the screen? Right now I'm calling the fit function but it zooms in really close, and when I call the zoom function to zoom out I have 2 animations going the fit and zoom out. 

Is there a function that would just reinitialize the OrgChart and set the default size?

**Comment by enniob** [comment]
Also after resizing the screen it adds a scroll bar and I do have setup the property

```
      showXScroll: OrgChart.none,
      showYScroll: OrgChart.none,
```
Any way to remove the scroll bar?

**Comment by plamen-peshev** [comment]
I have tried to replicate the issue with the scrollbars to no avail, see
[this](https://github.com/BALKANGraph/OrgChartJS/files/4661212/record_000031_New.zip) video

You can destroy the chart using **destroy** function and load it again

**Comment by enniob** [comment]
@plamen-peshev thanks for the reply. Here is what I see.

When I first load my OrgChart it loads fine.
![image](https://user-images.githubusercontent.com/5282211/82680804-ce278280-9c1a-11ea-9629-bce0fee74990.png)

but after I resize the screen I see this.

![image](https://user-images.githubusercontent.com/5282211/82680849-e0a1bc00-9c1a-11ea-945a-c6a8c27972b1.png)

This is the code I have.

```
    var chart = new OrgChart(document.getElementById("utoChart"), {
      nodeBinding: {
          field_0: "name"
      },
      nodes: [
          { id: 1, name: "Amber McKenzie" },
          { id: 2, pid: 1, name: "Ava Field" },
          { id: 3, pid: 1, name: "Peter Stevens" }
      ]
    });
```

**Comment by ZornitsaSerbezova** [comment]
Hi enniob, 

Could you please create us an example in jsfiddle with this issue, as we are unable to replicate it.

**Comment by enniob** [comment]
@ZornitsaSerbezova I will make a jsfiddle here.

Could it be the version of the orgchart.js I have?

**Comment by ZornitsaSerbezova** [comment]
What is your version?

**Comment by enniob** [comment]
The version is 5.0.2

**Comment by plamen-peshev** [comment]
Please upgrade to the latest version 6.4.0 and tell us if it is fixed

**Comment by enniob** [comment]
@plamen-peshev that issue is fixed in the latest version. thank you
