### ISSUE TITLE
Capture when Group is expanding/collapsing

### ISSUE THREAD

**Issue by lindsoe** [BALKANGraph/OrgChartJS#365]
Is there an event that is triggered, when Group is expanding/collapsing. I have tried the group-event, but it did not work.

**Comment by plamen-peshev** [comment]
you can use expcollclick event:

```
         var chart = new OrgChart(...);
        
         chart.on('expcollclick', function (sender, action, id, ids) {
            // your code goes here 
            // return false; to cancel the operation
         });  

         chart.load(...);
```

See more: https://balkangraph.com/OrgChartJS/Docs/APIReference#expcollclick
