### ISSUE TITLE
I want to put html tag in the menu field

### ISSUE THREAD

**Issue by koeve** [BALKANGraph/OrgChartJS#366]
![image](https://user-images.githubusercontent.com/41276476/82851992-84051080-9f3c-11ea-8fe5-401d1a28f2cc.png)

I'd like to put html tags in the news section.
What should I do?
I'd appreciate it if you could let me know.

**Comment by ZornitsaSerbezova** [comment]
Hi koeve,

I have created an example for you: https://jsfiddle.net/BALKANGraph/ygqkmtnf/
