### ISSUE TITLE
Customise SLINK template

### ISSUE THREAD

**Issue by jason-dowzell** [BALKANGraph/OrgChartJS#367]
In this issue (https://github.com/BALKANGraph/OrgChartJS/issues/297) there is an example of how to customise the SLINK template - I can successfully change the colour of the node line using this but not the arrow, dot and so on

Is there a documented list of options we can use to customise the slink node connectors?

We need to be able to use a custom colour for the line itself, arrow, dot to any HEX colour value and also make the line dotted

**Comment by plamen-peshev** [comment]
you have to create custom template for the slink. Here is an example where the arrow is red, the dot is blue and the line is dotted green:

```
   OrgChart.slinkTemplates.myTemplate = Object.assign({}, OrgChart.slinkTemplates.yellow);
    OrgChart.slinkTemplates.myTemplate.link = '<path stroke-dasharray="4, 2"  marker-start="url(#arrowSlinkYellow)" marker-end="url(#dotSlinkYellow)" stroke-linejoin="round" stroke="#00FF00" stroke-width="2" fill="none" d="{d}" />';   
    OrgChart.slinkTemplates.myTemplate.defs = '<marker id="arrowSlinkYellow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path fill="#FF0000" d="M 0 0 L 10 5 L 0 10 z" /></marker><marker id="dotSlinkYellow" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="5" markerHeight="5"> <circle cx="5" cy="5" r="5" fill="#0000ff" /></marker>';
```

https://jsfiddle.net/BALKANGraph/jbpyxkre/

![image](https://user-images.githubusercontent.com/49443821/83118776-7c2da380-a0d7-11ea-89bd-b59fb51f0d42.png)

**Comment by jason-dowzell** [comment]
Got it, thank you!
