### ISSUE TITLE
exception when resizing the window 

### ISSUE THREAD

**Issue by davitCB** [BALKANGraph/OrgChartJS#369]
when my devtools are open, and I am resizing the size of dvtools window (from right to left)  getting exeption

orgchart.js:1 Error: <svg> attribute viewBox: Expected number, "…9.5840817496912,NaN,NaN".

**Comment by ZornitsaSerbezova** [comment]
Hi davitCB,

We couldn't reproduce the issue. Could you please create an example in jsfiddle with it?

**Comment by davitCB** [comment]
try when scaleInitial: 1, option is set, I guess this is the reason for this issue

**Comment by ZornitsaSerbezova** [comment]
I have tried, but still don't get any errors.
Please try to reproduce the error in jsfiddle.

**Comment by ZornitsaSerbezova** [comment]
Hi davitCB,

I'll close this issue, because it looks inactive, but you can feel free to reopen it if needed.
