### ISSUE TITLE
New "expand all" Button issue

### ISSUE THREAD

**Issue by hdbrinkmann** [BALKANGraph/OrgChartJS#37]
The latest OrgChartJS Version offers a new button that expands all nodes (at least I did not recognize it earlier). 

This is cool, but within a large Orgchart the user needs to close a lot of nodes after (inadvertently) clicking the button. Is there a chance to go back to the state prior to the click, for example by clicking again?

**Comment by BALKANGraph** [comment]
I have logged your request for future consideration

**Comment by mpschaeuble** [comment]
@hdbrinkmann Where did you find the "expand all" button? Is there an API call to do this? I wasn't able to find anything related in the docs.

**Comment by hdbrinkmann** [comment]
Sorry for my late respone - i was offiste. The new button is in the latest version and in the demo here: https://balkangraph.com/OrgChartJS/Demos/BasicUsage
