### ISSUE TITLE
Property 'get' does not exist on type 'chart'

### ISSUE THREAD

**Issue by binhdotx** [BALKANGraph/OrgChartJS#370]
I am using this library in an Angular 9 component. When I try to add a custom save function like the code below. I am getting the error that "Property 'get' does not exist on type 'chart'".

this.saveButton.addEventListener("click", function () {
     var node = chart.get(that.nodeId);
     node.name = that.nameInput.value;
     node.title = that.titleInput.value;

     chart.updateNode(node);
    that.hide();
});

I don't see a get() function exposed in the orgchart.d.ts file.

**Comment by ZornitsaSerbezova** [comment]
We have added get() in the latest vertion (6.6.2)
