### ISSUE TITLE
Is it possible to change the chart container height?

### ISSUE THREAD

**Issue by enniob** [BALKANGraph/OrgChartJS#371]
I have a basic chart that I'm using with a bootstrap layout, but once the chart is initialized the code changes the height of the chart container to a fixed height (700px) and if I resize the browser the height container is fixed to 700px and I cannot change it. 

Is it possible to change the height of the chart container? 

Here is a jsfiddle with the default setup and if you inspect the the ```<div id="tree">``` you will see that the inline style is added. 

https://jsfiddle.net/ebozzetti/gyfr2aw3/

If I add a new class to the tree div to force the height to be 100% the chart does not load.

Here is the demo with the #tree with the height to be 100%
https://jsfiddle.net/ebozzetti/gyfr2aw3/2/

Any idea on how to fix this? otherwise when the user resize the browser the chart goes offscreen since the chart container still thinks the height is 700px.

Thanks,

**Comment by ZornitsaSerbezova** [comment]
Hi enniob,

Here is an example for you: https://jsfiddle.net/cg6qh5vL/

**Comment by pushpender98** [comment]
I have tried this solution, but it don't work.

**Comment by ZornitsaSerbezova** [comment]
Hi pushpender98,

Could you please isolate an example, explaining what is not working?

**Comment by pushpender98** [comment]
ya sure, I will share a example soon.

**Comment by ZornitsaSerbezova** [comment]
Hi Pushpender,
Did you manage to solve this issue?

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue as it looks inactive, but you can feel free to reopen it if needed.
