### ISSUE TITLE
Error while using the search

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#372]
When I type a text into the search box and press 'Enter' an error occurs. I have attached a movie of the problem and a sample project to reproduce.

[OC1Search.zip](https://github.com/BALKANGraph/OrgChartJS/files/4718235/OC1Search.zip)

[org-chart-sample.zip](https://github.com/BALKANGraph/OrgChartJS/files/4718231/org-chart-sample.zip)

**Comment by plamen-peshev** [comment]
can you test with the latest version 6.5.3

hope is fixed
