### ISSUE TITLE
expanded/collapsed state

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#375]
I need to know at runtime whether a node is collapsed or expanded. I would like to get this information from the property nodes of the orgchart. But this property is not documented and not included in the typescript definition file. Would you suggest another way or can I use the nodes property?

**Comment by ZornitsaSerbezova** [comment]
Hi sks4u,

Now you can use **collapsed** propertie from the [node collection.](https://balkangraph.com/OrgChartJS/Docs/NodeAPI).

**Comment by plamen-peshev** [comment]
We have added State functionality in the latest release

https://github.com/BALKANGraph/OrgChartJS/releases/tag/7.5.0
