### ISSUE TITLE
gradient color for each card in hierarchy

### ISSUE THREAD

**Issue by kksanghi** [BALKANGraph/OrgChartJS#376]
I was trying to implemented heat map pattern in Org Chart. What's the efficient way to have percentage defined in data set and apply background color based on the percentage value.

Keeping in mind that we don't want to create new template for each and every node.

**Comment by ZornitsaSerbezova** [comment]
Hi kksanghi,

We will implenet such fuctionality in the next version.

**Comment by ZornitsaPesheva** [comment]
I have created a demo for this: https://balkan.app/OrgChartJS-Demos/HeatMap.html
