### ISSUE TITLE
open current node and close others

### ISSUE THREAD

**Issue by kksanghi** [BALKANGraph/OrgChartJS#377]
do we have a way to close all other nodes except the one which user is trying to open ?

**Comment by ZornitsaSerbezova** [comment]
So you'd like to collapse all other nodes on the same level that are not childrens on the same parent?

**Comment by kksanghi** [comment]
Yes you are correct.

**Comment by ZornitsaSerbezova** [comment]
Hi kksanghi,

We have created a demo for you: https://balkangraph.com/OrgChartJS-Demos/CollapseNeighborsOnExpand
