### ISSUE TITLE
org chart template writing conditions

### ISSUE THREAD

**Issue by kksanghi** [BALKANGraph/OrgChartJS#378]
When we defined Org Chart Template  as Example
`<text width="145" text-overflow="multiline" class="field_1" style="font-size: 14px;" fill="#afafaf" x="100" y="60">{val}</text>`

Is there any possibility that we can use {val} to determine conditions to change any properties.
`<text width="145" class="{val} > 0 ? 'cls-1' : 'cls-2' "   fill="#afafaf" x="100" y="60">{val}</text>`

**Comment by ZornitsaSerbezova** [comment]
Could you explain what exacly are you trying to do?
You could use some screenshots if possible.

**Comment by ZornitsaSerbezova** [comment]
Hi kksanghi,
I am closing this issue, because it looks inactive, but you could feel free to reopen it if needed.
