### ISSUE TITLE
defined template for multiple fields instead single field

### ISSUE THREAD

**Issue by kksanghi** [BALKANGraph/OrgChartJS#379]
today we have an option to defined template for each field using 
`window.OrgChart.templates.ula.fieldName = template`

now this template have limitation since we can use only one field value here.

Is there any possibility so that we can create template using group of fields. Like
`window.OrgChart.templates.ula.GroupName = 'template {GroupName.Property1} -- {GroupName.Property2}`

**Comment by ZornitsaSerbezova** [comment]
Hi kksanghi,
This is the way to define a field in the node template:
` window.OrgChart.templates.ula.fieldName = template`

To define several fields we use this:
```
window.OrgChart.templates.ula.fieldName1 = field1
window.OrgChart.templates.ula.fieldName2 = field2
...
```
Here is the documentation of creatting a template:
https://balkangraph.com/OrgChartJS/Docs/CreatingCustomTemplate
