### ISSUE TITLE
Closing groups vs closing nodes

### ISSUE THREAD

**Issue by wimpie3** [BALKANGraph/OrgChartJS#38]
We can collapse nodes by using

sender.collapse(id, ids)

However, when GROUPS are open they stay open, even when the nodes are collapsed.

Could you add an API method to close groups?

**Comment by wimpie3** [comment]
No, that's not what I mean. In your example the entire HR team group disappears from the chart when you click on the button. I'd like to have a method where the group name stays visible, but not its contents (the same as collapsing a group by clicking on the < icon).

**Comment by ZornitsaSerbezova** [comment]
you can use **minimize** and **maximize** methods 

See https://jsfiddle.net/BALKANGraph/sd9xrwfg/
