### ISSUE TITLE
Missing 2 levels page format options in the PDF Preview since 6.6.2

### ISSUE THREAD

**Issue by Marika273** [BALKANGraph/OrgChartJS#380]
Hi,

Since version 6.6.2, there are 5 format options missing from the PDF Preview. These options were usefull so I am wondering if this was intended or not.
They are the 2 levels page options shown here:
![image](https://user-images.githubusercontent.com/61164477/84430697-158ca780-abf8-11ea-9356-d6b4772c7ae8.png)

Now, what we see is this:
![image](https://user-images.githubusercontent.com/61164477/84430849-4e2c8100-abf8-11ea-89ff-c6b0a1413a77.png)

We can also see it in the demo here: https://balkangraph.com/OrgChartJS-Demos/PdfPreviewTemplates.

Thanks,
Marika.

**Comment by ZornitsaSerbezova** [comment]
Hi Marika273,

We have removed the option for "2 levels on page" on purpose.
Now we have removed it from the demo also. 
Thank you for reporting it.


Regards,
Zornitsa
