### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by pm4698** [BALKANGraph/OrgChartJS#381]
Hello there, 

I started using orgchart to see how it works. I used this example/theme:
https://balkangraph.com/OrgChartJS-Demos/CustomTemplateCool.html

and i was wondering if there is a feature to align text content to center. So, name is inside the first text and using that example it has a predefined position (x and y). How can i do this to be generated dynamically? I saw that we can use text-overflow="multiline" if text uses 2 lines but if i know that node width is 140px how can i check text's width and horizontally align it to the node?

Thank you in advance

**Comment by ZornitsaSerbezova** [comment]
Hi pm4698,

You could you something like this to change the value of **x**:
` OrgChart.templates.cool.name = '<text  style="font-size: 18px;" fill="#afafaf" x=' + 150 + ' y="30">{val}</text>';`

Multiline is calculating authomatically.

**Comment by pm4698** [comment]
So, if i use your example, it actually starts from x=150 but what i am looking for is for the x to be dynamically calculated in order for the element to be always horizontally centrally aligned. So, what i could do is something like this (if my box has width 240px):
`OrgChart.templates.cool.name = '<text style="font-size: 18px;" fill="#afafaf" x=' + (240-this.style.width)/2 + ' y="30">{val}</text>';`

but i can't get the width of current element somehow. Any ideas?

Really appreciate your fast response

**Comment by ZornitsaSerbezova** [comment]
The width of the node (main rectangle) is 310, the width of the image is 80 and it starts from 10, so you need to substract 100 (80 + 2x10) from 310. So the width of the field should be 210.
You could see these values in the code or in the console.

**Comment by pm4698** [comment]
Ok, 

Width of the rectangle is 290px. What i need is for every node to check Name's text width and then set the X in order for the text to be centrally horizontally aligned. This is what i need. How to dynamically set the X of the text inside the rectangle to by calculated depending on the text's width

**Comment by pm4698** [comment]
I think i got it. I set up x=150 and then i added these parameters inside text:
`text-overflow="multiline" text-anchor="middle"`

Problem solved! Thank you very much for the prompt response and guidance which led to the solution!
