### ISSUE TITLE
Save data to database

### ISSUE THREAD

**Issue by pm4698** [BALKANGraph/OrgChartJS#382]
Hello there, 

I started using orgchart to see how it works. I used this example/theme:
https://balkangraph.com/OrgChartJS-Demos/CustomTemplateCool.html

What i need is when someone drags/drops elements then data is automatically being saved to a database. I know how to send/save data using ajax but i don't know if there is a ready function/suggested way to loop through all nodes and get information like id and order to save it to an array and use it through ajax.

Thank you in advance

**Comment by ZornitsaSerbezova** [comment]
You can see here our example for ASP.NET MVC:
https://github.com/BALKANGraph/OrgChartWebApp

**Comment by pm4698** [comment]
Ok, i use PHP and i am loading data from database and its working like a charm. What i need is when performing drag/drop to drop data through ajax and save the new order into my database.

From your example i saw this:

` chart.on('update', function (sender, oldNode, newNode) {
            $.post("@Url.Action("UpdateNode")", newNode)
                .done(function () {
                    sender.updateNode(newNode);
                });
            return false;
        });`

Is there a parameter in the orgchart to be something like: chart.on ('dragdrop'......) ? Also, if not using .NET can you provide an example of how to loop all nodes to save data into arrays? like old node array and new node array?

**Comment by ZornitsaSerbezova** [comment]
hi pm4698,

**Drag and drop** is triggering the **update** event, so you ca use it to save your data.

**Comment by pm4698** [comment]
Thanks for the info. So the on update event holds 3 variables: sender, oldNode, newNode. These variables are global? Can you provide a jQuery/Javascript loop example where we loop through all nodes to get new and old Nodes?

**Comment by ZornitsaSerbezova** [comment]
When you drag and drop a node, you don't need the all nodes data. You just need the **newNode**  and you have to save the data in the function of this event. 
```
chart.on('update', function (sender, oldNode, newNode) {
          // find the id of the newNode in the database and save the data
        });
```

**Comment by pm4698** [comment]
So can you tell me within a line what is what?
Per example:
sender: node's id
oldNode: node's old parent id
newNode: node's new parent id

Thank you in advance

**Comment by ZornitsaSerbezova** [comment]
Where is this from?

**Comment by pm4698** [comment]
`chart.on('update', function (sender, oldNode, newNode) { // find the id of the newNode in the database and save the data });`

The above event has 3 variables:sender, oldNode and newNode. What is each of this 3 variables?for a node which is the sender, which ia the oldNode and which the newNode?

**Comment by ZornitsaSerbezova** [comment]
sender is the chart (OrgChart object)
oldNode - the node data before moving (old paren id)
newNode - the node data after moving (new parent id)

**Comment by pm4698** [comment]
So sender is lets say object's id, oldNode is object's previous pid and newNode is object's new pid?

**Comment by ZornitsaSerbezova** [comment]
No, to understand better , you can di this:
``` 
        chart.on('update', function (sender, oldNode, newNode) { 
            console.log(sender);
            console.log(oldNode);
            console.log(newNode);
        });
```

**Comment by pm4698** [comment]
Thank you very much for your assistance! I used console.dir to check sender, oldNode and newNode and eventually moving object's id is newNode.id and new parent is newNode.pid. I use these 2 variables to update my database and its working like a charm!

Many thanks!
