### ISSUE TITLE
Flickering is happening

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#383]
Hi 

I have already shared a video regarding this on mail and the issue was somewhat fixed in 6.4.0.

But this is started again, issue is no scrolling horizontally or vertically there is some kind of flickering. 
Please have a look over that part asap.

**Comment by plamen-peshev** [comment]
Can you try with the latest version, hope it is fixed

**Comment by pushpender98** [comment]
Hi @plamen-peshev 

Yeah this issue is coming at the latest version also. Now it is coming in horizontal view

**Comment by pushpender98** [comment]
Hi 

Its also comes sometimes in vertically, but no idea how

**Comment by pushpender98** [comment]
Any update to this one @plamen-peshev @ZornitsaSerbezova

**Comment by pushpender98** [comment]
This issue is coming in the latest library too.

**Comment by pushpender98** [comment]
Hi any update on this one?

**Comment by pushpender98** [comment]
any update??

**Comment by ZornitsaSerbezova** [comment]
Just have answered to your email. We need an isolated example with the issue.

**Comment by pushpender98** [comment]
Hi @ZornitsaSerbezova 

Yeah, shared a exapmle through email :)

**Comment by ZornitsaSerbezova** [comment]
Yes, thank you. We are workinhg on this.

**Comment by pushpender98** [comment]
Is the issue is complex, if yes then how much time will it take?

**Comment by pushpender98** [comment]
Any update to this issue @ZornitsaSerbezova @plamen-peshev

**Comment by ZornitsaSerbezova** [comment]
Fixed in 7.1.92

**Comment by pushpender98** [comment]
I will check and update the issue.

**Comment by pushpender98** [comment]
This issue is still occurring sometimes

**Comment by pushpender98** [comment]
Hello there 

Any update?

**Comment by plamen-peshev** [comment]
we fixed the issue in version 7.5.25

**Comment by pushpender98** [comment]
Thanks very much for the fix.
