### ISSUE TITLE
orgChartJs use in vue，body style setting user-select:none issues

### ISSUE THREAD

**Issue by btredback** [BALKANGraph/OrgChartJS#384]
Question：In vue environment，use orgChartJs，when click background to move chart，body style always setting [user-select:none] ，this caused other table cant select text
![image](https://user-images.githubusercontent.com/9562928/85016850-22337180-b19d-11ea-8bc5-9d5edf03cb88.png)

Request：how to prevent or hanld this method，or is it my use problem in vue？

my config like this 

this.chart = new OrgChart(domEl, {
          template: 'myTemplate',
          nodes: x,   
          collapse: {
            level: 2,
            allChildren: true
          },
          nodeBinding: {
            field_0: "name",
            field_1: "id",
            //img_0: "img"
          },
          orientation: OrgChart.orientation.left,
          toolbar: {
            layout: false,
            zoom: true,
            fit: true,
            expandAll: false,
            fullScreen: false
          }
        });

**Comment by ZornitsaSerbezova** [comment]
Hi btredback,

What do you mean by "other table cant select text"? What are you trying to do when moving the chart?

**Comment by btredback** [comment]
> Hi btredback,
> 
> What do you mean by "other table cant select text"? What are you trying to do when moving the chart?
Hi ZornitsaSerbezova，
thanks to answer.
my OrgChart as vue component used in a el-tab-pane page，when setting [user-select:none] and jump to other tab page，this style cause page table column text can not selected .

**Comment by ZornitsaSerbezova** [comment]
Hi btredback,
Do you still have this issue?
Is this the module that you use?: https://www.npmjs.com/package/el-tab-pane-ext

**Comment by btredback** [comment]
> Hi btredback,
> Do you still have this issue?
> Is this the module that you use?: https://www.npmjs.com/package/el-tab-pane-ext

oh, thanks , i modified style after leaving page to solving this problem. use this module: https://element.eleme.cn/2.0/#/en-US/component/tabs
