### ISSUE TITLE
Collapse and expand feature related

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#385]
Hi

I have initially used the
`collapse = 
  	{ level: 2,
      allChildren: true
  	}
  }`

and started expanding the nodes below.

So If I add some new node Data and redraw the chart by chart.load(); then the expanded node are also been reset.

Is there any way to handle this?

**Comment by plamen-peshev** [comment]
you can replace chart.load with 

```
    chart.config.nodes = json;
    chart.draw(false, OrgChart.action.update);
```

**Comment by pushpender98** [comment]
Thanks for the help

**Comment by pushpender98** [comment]
This is throwing error @plamen-peshev

**Comment by pushpender98** [comment]
Hi @ZornitsaSerbezova  or @plamen-peshev 

Any thing related to this one?

**Comment by plamen-peshev** [comment]
also you can use addNode method
`
chart.addNode({id: 10, pid: 5})`

Created a demo for you: https://jsfiddle.net/BALKANGraph/o6f2c3xq/14/

**Comment by plamen-peshev** [comment]
instead of     

```
    chart.config.nodes = json;
    chart.draw(false, OrgChart.action.update);

```
try with 

```
    chart.config.nodes = json;
    chart.draw(OrgChart.action.update);
```
