### ISSUE TITLE
How to resize org chart dynamic?

### ISSUE THREAD

**Issue by enniob** [BALKANGraph/OrgChartJS#386]
I currently have the org chart displayed on the entire screen, but when the user click on a node I need to open a side panel or a bottom panel. 

Once the bottom panel is open it takes 1/3 of screen bottom part, so I need to resize the org chart so it display on the other 2/3.  I do have a css code that will resize the org chart div to the correct size, but the org chart never resizes to the correct size, and it gets cut out at the bottom and the user needs to drag or zoom out. 

After adding the new CSS class to the org chart div I call the function ```this.chart.draw(OrgChart.action.init);``` to draw the chart again, but nothing happens. 

Is there a way to resize the chart so it fits the new DIV size?

I also try calling the ```this.chart.destroy();``` and calling my org chart init function but it does not seem to work.

**Comment by ZornitsaSerbezova** [comment]
Hi enniob,
Did you try chart.fit()?

**Comment by enniob** [comment]
@ZornitsaSerbezova yes, but still have the same issue. 

So here is something interesting. I just notices that after I open the bottom panel and I click on the org chart it does resize to the correct size, but I have to click on the org chart.

**Comment by ZornitsaSerbezova** [comment]
Could you please create an example in jsfiddle?

**Comment by enniob** [comment]
@ZornitsaSerbezova do you have a started sample using Angular and OrgChart and I can make a jsfiddle.

**Comment by ZornitsaSerbezova** [comment]
Hi Ennio,
[Here ](https://balkangraph.com/OrgChartJS/Docs/Angular)we have a document on how to start an Angular project with OrgChart, but it would be better to isolate an example in jsfiddle or an html file.

**Comment by enniob** [comment]
@ZornitsaSerbezova sorry, I guess it was a late night working on it and I was looking at the wrong function :). I also made a jsfiddle and it is working as it is supposed too. :)

Here is the link.
https://jsfiddle.net/ebozzetti/fxrhk0qw/24/
