### ISSUE TITLE
Export Related Question

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#387]
Hi 

I want to know that is there any possibility for detecting : 

- The internet goes down.
-  Export is interpreted in between

If yes please suggest some ways.

I am also curios to know, weather we can expand the nodes in upward direction also?
If yes please suggest

**Comment by plamen-peshev** [comment]
Why you need to detect the internet connection and how it is related to the OrgChart JS

Regarding your second question you can use orientation option https://balkangraph.com/OrgChartJS-Demos/Orientation

**Comment by pushpender98** [comment]
Actually, if the export is interpreted somehow, due to internet issue, then I need to throw some exception. So for that I need to confirm weather the export is successful or not.

Regarding the second question, I don't want the orientation. I want to know that if I click on any specific node then it should expand upwards, to its parent node. Not to its children.

**Comment by ZornitsaSerbezova** [comment]
Hi Pushpender,

You could read the answers on [this ](https://stackoverflow.com/questions/189430/detect-the-internet-connection-is-offline)question.

The feature to expand upward will be implemented in the next version, but you will need to change the data structure, as the implementation will require specific data structure.

**Comment by pushpender98** [comment]
Okay @ZornitsaSerbezova . Thanks for a quick answer. I will wait till then
