### ISSUE TITLE
close search bar through api

### ISSUE THREAD

**Issue by kksanghi** [BALKANGraph/OrgChartJS#388]
![image](https://user-images.githubusercontent.com/16228568/85163488-867b3180-b280-11ea-9d24-f710937320a2.png)

How we can close this search appearance through API method

**Comment by ZornitsaSerbezova** [comment]
You want to close the search on mouse moving out?

**Comment by kksanghi** [comment]
Let's assume we have button one page says "Close Org Chart Search bar" when we hit on this we wanted to close the search bar

**Comment by plamen-peshev** [comment]
you can use searchUI show hide methods
```

    chart.on("init", function(){    
    	chart.searchUI.show();
    })
    document.getElementById("Hide_search_result").addEventListener("click", function(){
    	chart.searchUI.hide();
    })
```

See this demo https://jsfiddle.net/BALKANGraph/2m09hnLs/9/

**Comment by kksanghi** [comment]
this is great appreciated !
