### ISSUE TITLE
Org Chart not getting displayed on https site

### ISSUE THREAD

**Issue by nehac131288** [BALKANGraph/OrgChartJS#390]
I am implementing org chart in out application & it is now hosted on https site. When deployed on http site,it gets displayed.But when testing on https site,the chart is not loaded/displayed. Can you pls guide me what steps shall I follow to get it working.Thanks in advance.

**Comment by ZornitsaSerbezova** [comment]
Hi nehac131288,
OrgChart Js is working by default on https. You could see our website for example. You shoul be looking for the problem somewere else.
Do you use the lisensed version?

Regards,
Zornitsa

**Comment by nehac131288** [comment]
No,I am using trial version for testing now.I am getting this message in console in chrome:
Access to XMLHttpRequest at 'https://easia-balkangraph.azurewebsites.net/api/OrgChartJS' from origin 'https://talentcomp2.unitysuite.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by ZornitsaSerbezova** [comment]
Could you please try if it is working with very simple chart (you could use our [base example](https://balkangraph.com/OrgChartJS/Docs/GettingStarted))?

If this is still not working, could you give us your domain, where the chart is hosted?
https://talentcomp2.unitysuite.com/ does not open anything (empty page).

**Comment by nehac131288** [comment]
Hi, The chart is displayed now.I have minimized the no of nodes to 200 (earlier it was 700) .But the problem I am facing now is 
First time when I switch from vertical(top) to a Horizontal(left) view I see a blank screen. When double click component appears.
 I think component appears but it is miss place when double click it appears.Please help.

**Comment by ZornitsaSerbezova** [comment]
Please give us a link to the orgchart page to be able to investigave the issue.

**Comment by nehac131288** [comment]
https://talentcomp2.unitysuite.com/LogiDemo/CHRG/aspx/Signin.aspx
Username: eric.sidle@chargepoint.com
first pwd: admin
second pwd: Renu1234
There will be Sys Admin menu under which will be the "View Organization Chart" submenu. Please go to it & change vertical to horizontal orientation & check.The chart disappears OR the screen gets blank & appears on double click. TIA

**Comment by ZornitsaSerbezova** [comment]
Hi nehac131288,

The problem is that the chart is hiding when you change the orientation.
could you try to change this code:
```
            document.querySelector('#orientation').addEventListener('change', function () {
                chart.config.orientation = parseInt(this.value);
                chart.draw();
            });
```
to this one:
```
       document.querySelector('#orientation').addEventListener('change', function () {
                chart.config.orientation = parseInt(this.value);
                chart.draw(OrgChart.action.update, null, function(){
			chart.center(5)	
		});
       });
```
where 5 is your centered node id

**Comment by nehac131288** [comment]
chart.center(5)	 is giving me error.Cannot set property 'groupState' of undefined. I think it has other parameter as options which is not supplied.But I tried from google supplying that isn't working as well. Its just when I change it to Horizontal,I want the chart to be not in center but atleast at the view (not hidden). Please reply asap. Can you pls change the script itself & check once?

**Comment by nehac131288** [comment]
Great..Thanks a ton..!!! It is working fine now..!!
