### ISSUE TITLE
Possibilty to have a bag of unasigned nodes 

### ISSUE THREAD

**Issue by alanvallejodev** [BALKANGraph/OrgChartJS#391]
Hi,

I was just wondering if the possibilty to have a bag of unasigned nodes exists?

If exists, is it possible to place it in a specific corner?

I think it would be a good feature.

Thanks for your time.

**Comment by ZornitsaSerbezova** [comment]
Hi alanvallejodev,

If you mean that you want to see a list of nodes that are not in the chart,
you could check these demos here:
https://balkangraph.com/OrgChartJS-Demos/DragDropItemsToChartFromArray - list of data items to drag and drop in the chart
https://balkangraph.com/OrgChartJS-Demos/SetNodeAsRoot - root nodes

**Comment by alanvallejodev** [comment]
Thanks for your quick response.
