### ISSUE TITLE
Very slow in IE and Org chart is not rendering properly

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#392]
Hi @plamen-peshev  or @ZornitsaSerbezova 

When we shift from top-down to left top in IE, then there is some issues in UI for org chart.
This might be due to slow speed of Org chart in the IE. Please look into it.
![image](https://user-images.githubusercontent.com/36353150/85878569-8b972e00-b7f6-11ea-8bc4-6d77d4902ff8.png)

**Comment by pushpender98** [comment]
Your Demo link : https://balkangraph.com/OrgChartJS-Demos/15kNodesCustomExpandCollapse

Throwing error at every browser

**Comment by ZornitsaSerbezova** [comment]
Pleaee review your data, as this issue is caused by irregular data and relations.
15k demo is fixed.

**Comment by pushpender98** [comment]
Ya it okay now
