### ISSUE TITLE
IE > Expanding of node is not working properly

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#393]
Hi 

Expanding is giving this error in IE only while expanding. 
![image](https://user-images.githubusercontent.com/36353150/85929510-1fd6c300-b8d3-11ea-9192-e69e814a466b.png)

I have done my code like this.
![image](https://user-images.githubusercontent.com/36353150/85929526-3e3cbe80-b8d3-11ea-877f-25c7ee80b9a4.png)

This error is coming when I have multiple nodes which are expandable at the same level. If I expand 2 of them and try to expand the 3rd one then only this error, occurs.

Please help me.

**Comment by ZornitsaSerbezova** [comment]
Hi Pushpender,

Could you please try to reproduce this issue on one of our [demos](https://balkangraph.com/OrgChartJS-Demos/)?

**Comment by pushpender98** [comment]
This issue is coming in the trail version, but fixed after buying the library.
