### ISSUE TITLE
Scrolling need to be fixed.

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#394]
As this is an new update for the scrolling part.

Can we make the Org chart like that we can give the scrolling to any div we want?

As of now, the scrolling is based on the parent div, I think as much as I debugged.
PLease look to the attached image.
![image](https://user-images.githubusercontent.com/36353150/85993248-a85c7d00-ba13-11ea-96d6-ae05dbbf48c7.png)

Apart from this,  there is a huge sensitivity issue for Apple mighty mouse reported by one of my teammate. When he scrolls then the he directly lands to another part of the org chart.

**Comment by ZornitsaSerbezova** [comment]
To increase or decrease sroll sensitivity change OrgChart.scroll.smooth and OrgChart.scroll.speed constants, the default values are:
```
    OrgChart.scroll.smooth = 12;
    OrgChart.scroll.speed = 12; 
```

**Comment by pushpender98** [comment]
Hi @ZornitsaSerbezova 
The sensitivity is working fine for windows, but have high in only in mac, so can we do something specific to mac

**Comment by plamen-peshev** [comment]
To set sensitivity for specific browser 


```

    OrgChart.scroll.safari = {
        smooth: 12,
        speed: 500
    };
    OrgChart.scroll.ie = { smooth: 12, speed: 200 };
    OrgChart.scroll.edge = { smooth: 12, speed: 200 };
    OrgChart.scroll.chrome = { smooth: 12, speed: 200 };
    OrgChart.scroll.firefox = { smooth: 12, speed: 200 };
    OrgChart.scroll.opera = { smooth: 12, speed: 200 };
```

**Comment by pushpender98** [comment]
Thanks @plamen-peshev
