### ISSUE TITLE
Export Avatar Image Issue

### ISSUE THREAD

**Issue by kksanghi** [BALKANGraph/OrgChartJS#395]
Today when we render the Org Chart, We have Specified Image Path as "/Img/SomeImage.png" this works, but when we export we are not seeing those image.

![image](https://user-images.githubusercontent.com/16228568/86083083-f080ab80-bab6-11ea-8f36-6a240fddb2d4.png)

But if i am trying to provide Image Path as "https://externalWebsite/SomeImage.Png" it works, what's the issue,

We had this issue with Latest Version Not With the Prior Version

**Comment by plamen-peshev** [comment]
Correct, you need to set the absolute URL

**Comment by pushpender98** [comment]
This issue was also faced by me to, this is due to the unpublic of the URL, so we need to make the URL public, so that the export server can fetch
