### ISSUE TITLE
Problem with Zoom

### ISSUE THREAD

**Issue by vpma2580** [BALKANGraph/OrgChartJS#396]
Hello,
First of all, thanks for this good library.
But I found some issues while using this library.
When I first see the chart, some specific links are showing but after zoom in, the links disappear even connected node is still showing. After zoom out, the links shows again.
Looking forward to hearing from you.

**Comment by ZornitsaSerbezova** [comment]
Hi vpma2580,
Could you send us some example in jsfiddle with this issue?

**Comment by vpma2580** [comment]
thanks for your reply.
![Screenshot_2020-07-02_15-47-11](https://user-images.githubusercontent.com/44001573/86403269-5d44a300-bc7b-11ea-916d-4dd870e3f8fc.png)
![Screenshot_2020-07-02_15-46-51](https://user-images.githubusercontent.com/44001573/86403275-5e75d000-bc7b-11ea-9d2d-b086aae4b3cd.png)
Please check node 3TR6G.

**Comment by ZornitsaSerbezova** [comment]
Hi vpma2580,
If you'd like to always see the link, you could try to use **lazyLoading: false** option.
```
    var chart = new OrgChart(document.getElementById("tree"), {
        lazyLoading: false,
        ...
    });
```

**Comment by ZornitsaSerbezova** [comment]
I will close this as it is fixed and also you are gong to yse slinks.
