### ISSUE TITLE
Problem with slinks

### ISSUE THREAD

**Issue by vpma2580** [BALKANGraph/OrgChartJS#397]
Hello,
https://jsfiddle.net/rwxzyou0/
I tried to use slinks but it has problem with exporting, searching and etc.
I can see a specific error at console. As I google, it said it was fixed with latest version but still problem.
Looking forward to hearing from you

**Comment by ZornitsaSerbezova** [comment]
Could you give me istruction how to reproduse the error, because I don't get one? I get only wranings.
![Untitled](https://user-images.githubusercontent.com/19305472/86353654-46e51a00-bc70-11ea-9a7d-a4def8f0ae89.png)

**Comment by vpma2580** [comment]
Thanks for your reply.
Can you try to search with BANKSTRT?

**Comment by ZornitsaSerbezova** [comment]
I have tried, but still don't get any errors.
![bank](https://user-images.githubusercontent.com/19305472/86461379-98ee7400-bd32-11ea-99b8-81d81b8ebad2.png)

**Comment by vpma2580** [comment]
After search, if you click dropdown list, it will show error.
and also if you try scaleInitial: OrgChart.match.boundary, it will show error.

**Comment by vpma2580** [comment]
lazyLoading: false,
I tried to add this at this jsfiddle, it shows error

**Comment by ZornitsaSerbezova** [comment]
> After search, if you click dropdown list, it will show error.
> and also if you try scaleInitial: OrgChart.match.boundary, it will show error.


We were able to reproduse the issue and we will try fix it soon.

**Comment by vpma2580** [comment]
thanks, Looking forward to hearing good news asap.

**Comment by plamen-peshev** [comment]
We have investigated the issue

you have multiple trees in the same chart. In the current version slinks are not supported if fromnode and tonade have different roots, the root node has to be the same for fromnode and tonode

**Comment by vpma2580** [comment]
Thanks, but is it difficult to allow different root for fromnode and tonode with slinks?
if it is not difficult, how long will it take to implement?
I am much interested in this library and i love slinks so much.

**Comment by ZornitsaSerbezova** [comment]
Hi vpma2580,

We need to investigate if we could implement it.

**Comment by ZornitsaSerbezova** [comment]
We have created a demo in how to create hidden root if you need slinks between chart with different roots.

**Comment by ZornitsaSerbezova** [comment]
Hi vpma2580,
Do this demo resolve your problem?
