### ISSUE TITLE
el precio es en dolares ?

### ISSUE THREAD

**Issue by jorgelt87** [BALKANGraph/OrgChartJS#398]
soy de argentina y es un proyecto meno que quiero hacer  y la consulta si es en dolares

**Comment by ZornitsaSerbezova** [comment]
Hi jorgelt87,

Please write in English.
Could you give us more details on what exactly do you need?

Regards,
Zornitsa

**Comment by jorgelt87** [comment]
Hi, how are you? My name is Jorge from Argentina. I wanted to consult. I only have 10 nodes only. Is it necessary to pay? Is the price in dollars?

**Comment by ZornitsaSerbezova** [comment]
Hi jorgelt87,

We don't offer OrgChart JS for free. You need to purchase the product from our [store](https://balkangraph.com/OrgChartJS/Store). The prices are in dollars.

**Comment by ZornitsaSerbezova** [comment]
Hi jorgelt87,

I'll close this issue, because it is answered, but feel free to reopen it if needed.


Regards,
Zornitsa
