### ISSUE TITLE
Safari and Apple devices bug in the foreignobject 

### ISSUE THREAD

**Issue by vingeek-dev** [BALKANGraph/OrgChartJS#399]
Hi,
We have found a new bug in the Org Chart library, we have reproduced it in this jsfiddle: 
[https://jsfiddle.net/pzm40dew](https://jsfiddle.net/pzm40dew)

### The case 
When there are nodes that contains custom HTML elements (inserted into a foreignobject) if there is a parent element that has a '**position: relative**' and a child element that has '**position: absolute**' the child element is moved to svg root container (in the left top) and not in his own parent element. This is an example, but there are more CSS rules which create other issues such as opacity(if you set a different value when you hover the element). 
**This problem only occurs on Safari browser (on mac) and Apple mobile devices (all browser).**

### The issue 

<img width="1187" alt="mac" src="https://user-images.githubusercontent.com/1867200/86484530-b33a4900-bd56-11ea-883a-5b719b10ca1f.png">
 
### Expected result

![windows](https://user-images.githubusercontent.com/1867200/86484615-e41a7e00-bd56-11ea-960b-4cacea79c346.png)

In our implementation we have different HTML elements with more CSS rules that break the chart.

Thanks

**Comment by ZornitsaSerbezova** [comment]
Hi Vincenzo,

Thank you for the good report.
We will take a look at this issue when we have the opportunity.


Regards,
Zornitsa

**Comment by plamen-peshev** [comment]
Tested [this Code demo ](https://code.balkan.app/org-chart-js/node-html-fields#JS)in Safari v 13.1.3 and it works perfectly fine

**Comment by ZornitsaPesheva** [comment]
I am closing this issue as inactive and because of lack of information.
