### ISSUE TITLE
Horizontal chart

### ISSUE THREAD

**Issue by kezern** [BALKANGraph/OrgChartJS#4]
I'm testing this library for building organization charts. I would like to create an horizontal chart from left to right instead of vertical.
Does anybody knows how to do that?
Best regards.

**Comment by BALKANGraph** [comment]
OrgChart JS does support horizontal layout. Please review [Orientation ](https://balkangraph.com/OrgChartJS/Docs/Layout)section from this documentation page

Let me know if you have more questions
