### ISSUE TITLE
nodeMenu only when the node has childs

### ISSUE THREAD

**Issue by mitkosoft** [BALKANGraph/OrgChartJS#40]
Hi,

Is there an option/method/property to specify nodeMenu to be visible only when the node has a child(s)? I would like to avoid this menu to be displayed into all child boxes, but only into the parent node. Like: when I have a team with a team lead and a couple of employees below him, the menu to be visible only into team lead's box.

**Comment by mininglink** [comment]
I Have just implemented various conditional menus, using the built in functionality

you can set the menu via tags,  https://balkangraph.com/OrgChartJS/Docs/NodeMenuItem

then you can just add the correct tags to the applicable menus

:)
