### ISSUE TITLE
No margin and padding on the svg

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#402]
Hi

I have already discussed this on mail, can we make the svg export configurable at the client side itself, that there will be more padding from all side of the views.

Its an enhancement by the way.

**Comment by plamen-peshev** [comment]
Thanks for your good suggestion. We will add it in out feature consideration list.

**Comment by pushpender98** [comment]
Can u provide this in the latest releases?

**Comment by ZornitsaSerbezova** [comment]
We could implement this functionality if other customers also ask for it.

**Comment by ZornitsaSerbezova** [comment]
Hi Pushpender,

Option **padding** is added in the latest version: https://balkangraph.com/OrgChartJS-Demos/Padding

**Comment by pushpender98** [comment]
Thanks
