### ISSUE TITLE
Add customize line for custom field

### ISSUE THREAD

**Issue by erbaafidotama** [BALKANGraph/OrgChartJS#403]
Helloo..
Sorry im newbie.
How to add line javascript in react code?
This line:
`OrgChart.templates.ana.field_0 = '<text class="field_0"  style="font-size: 20px;" fill="#ffffff" x="125" y="30" text-anchor="middle">{val}</text>';
        OrgChart.templates.ana.field_1 = '<text class="field_1"  style="font-size: 14px;" fill="#ffffff" x="125" y="50" text-anchor="middle">{val}</text>';
        OrgChart.templates.ana.field_2 = '<text class="field_2"  style="font-size: 14px;" fill="#ffffff" x="125" y="70" text-anchor="middle">{val}</text>';
        OrgChart.templates.ana.field_3 = '<text class="field_3"  style="font-size: 14px;" fill="#ffffff" x="125" y="90" text-anchor="middle">{val}</text>';`

And this is my react code:
`import React, { Component } from 'react';
            import OrgChart from './mychart';

            export default class HierarchyViewer extends Component {

              render() {
                  const dataHierarchy = [
                    { id: "1", name: "Amber McKenzie", title: "CEO", phone: "878 108 255", email: "amber.mcKenzie@gmail.com" },
                    { id: "2", pid: "1", name: "Ava Field", title: "IT Manager", phone: "554 484 126", email: "ava.field@live.com" },
                    { id: "3", pid: "1", name: "Peter Stevens", title: "HR Manager", phone: "897 112 444"  }
                ]

                const nodeBinding= {
                    field_0: "name",
                    field_1: "title",
                    field_2: "phone",
                    field_3: "email"
                }

                const template = "ana"
                return (
                           <div style={{height: '100%'}}>

                           <OrgChart template={template} nodes={dataHierarchy} nodeBinding={nodeBinding} />

                  </div>
                );
              }
            }`

Thanks

**Comment by ZornitsaSerbezova** [comment]
Hi erbaafidotama,
This is the way i do it:
```
import React, { Component } from 'react';
          //   import OrgChart from '@balkangraph/orgchart.js/orgchart';
import OrgChart from 'orgchart1';
            export default class extends Component {

                shouldComponentUpdate() {
                    return false;
                }

                componentDidMount() {
                    OrgChart.templates.ana.field_0 = '<text class="field_0" style="font-size: 20px;" fill="#ffffff" x="125" y="30" text-anchor="middle">{val}</text>'; OrgChart.templates.ana.field_1 = '<text class="field_1" style="font-size: 14px;" fill="#ffffff" x="125" y="50" text-anchor="middle">{val}</text>'; OrgChart.templates.ana.field_2 = '<text class="field_2" style="font-size: 14px;" fill="#ffffff" x="125" y="70" text-anchor="middle">{val}</text>'; OrgChart.templates.ana.field_3 = '<text class="field_3" style="font-size: 14px;" fill="#ffffff" x="125" y="90" text-anchor="middle">{val}</text>';
                    this.chart = new OrgChart(this.refs.tree , {
                        nodes: this.props.nodes,

                        nodeBinding: {
                            field_0: "name",
                            field_1: "title"
                        }
                    });
        
                }

                render() {
                    return (
                         <div id="tree" ref="tree"></div>
                    );
                }
            }
```

**Comment by erbaafidotama** [comment]
Wooow. Thanks
