### ISSUE TITLE
onClick event does not work in 7.1.1

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#404]
as you can see here:
https://jsfiddle.net/285d3wry/

**Comment by ZornitsaSerbezova** [comment]
Hi sks4u,
We have removed these options.
Please use it this way:

```
         var chart = new OrgChart(...);
        
         chart.on('click', function (sender, args) {
            // your code goes here 
            // return false; to cancel the operation
         });  

         chart.load(...);
```

**Comment by sks4u** [comment]
Where did you document these braking chages? In 6.3.4 this still worked. And I did not find anything in the release list. Are all events affected?

**Comment by ZornitsaSerbezova** [comment]
Actually, we removed these options from the documentation long time ago.
We removed them from the script in version 7.0.1
