### ISSUE TITLE
collapsed property of node model does not work

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#406]
see https://jsfiddle.net/285d3wry/2/

**Comment by ZornitsaSerbezova** [comment]
It doesn't work for root, becose the root can not be collapsed.

**Comment by sks4u** [comment]
So why is it not just false? Then I don't need special treatment for root nodes, especially when I get them with getNode using the id.

**Comment by ZornitsaSerbezova** [comment]
As I just answered you to the other question, it's because of the performance.
