### ISSUE TITLE
node model initialisation

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#407]
Many properties of the node model are undefiened as long as they are not yet initialized. Now I wonder when they will be initialized. Is there a point in time when I can be sure that all properties are initialized or will each property be initialized at a different time?
 
There seem to be some properties that can take the value undefined again after they are initialized (e.g. parent). Can you please help me to understand the concept?

**Comment by ZornitsaSerbezova** [comment]
Hi sks4u,

The main idea is to have as little as possible initialized prpperties, so that the chart will not be slow with large ammaount of nodes.

**Comment by sks4u** [comment]
But then I have to know when each property is initialized and deinitialized again. Otherwise I cannot use this. For example, when is the property "collapsed" initialized? As I have already learned, it is not for root nodes. But how is it with non root nodes? Is it there allways true or false? Or just if the node is visible?

**Comment by ZornitsaSerbezova** [comment]
You don't you check with if (!node.collapsed) or if (node.collapsed == undefined)?

**Comment by sks4u** [comment]
Does undefiened always mean false? For all the properties? For example, the documentation of the proterty 'isAssistant' says:

_if the node is assistant is true if not false if the node is not initialized is undefined_. 

That doesn't sound to me like "undefined = false"

**Comment by ZornitsaSerbezova** [comment]
Undefined is not equal to false, but If the property is undefined, (!node.property) returns true.

**Comment by sks4u** [comment]
But what do I do if e.g. the property 'collapsed' is undifined, but I need to know whether the node has collapsed or not?

**Comment by ZornitsaSerbezova** [comment]
I am not sure if I understand the problem, but the property can not be undefined if the node is collapsed.

**Comment by sks4u** [comment]
But when exactly can it becomes undefined? One case I already know, namely when it is a root node. Are there other cases?

**Comment by sks4u** [comment]
I have found that for a node that is collapsed but whose parent is not collapsed, the value of the 'collapsed' property is true.

For a node that is collapsed but whose parent is collapsed, the value of the 'collapsed' property is undefined.

So it is not possible for me to go through the tree and evaluate this property for each node, because I do not know what to assume for 'collapsed' if its value is undefined.

What I need is an explanation of all cases where this value becomes undefined and how I can determine the value for each case.

I would be very grateful for your help.

**Comment by ZornitsaSerbezova** [comment]
Hi sks4u,
Did you manage to sole this issue?

**Comment by sks4u** [comment]
No it isn't. I am still waiting for an answer from you.

**Comment by ZornitsaSerbezova** [comment]
So the answer of the question is:
A property will be initialized, when it is used. There is no point of time that all properties will be initialized. 

"For a node that is collapsed but whose parent is collapsed, the value of the 'collapsed' property is undefined." - This is not right, The node is undefined, because the node is not collapsed. Its parent is collapsed, that 's why the node is not visible, but the nose itself is not collapsed.

**Comment by ZornitsaPesheva** [comment]
I'll close this issue as it looks inactive. Feel free to reopen it with a particular question if you need.
