### ISSUE TITLE
Rendering issues on certain zoom levels

### ISSUE THREAD

**Issue by mpschaeuble** [BALKANGraph/OrgChartJS#41]
With the latest version, node rendering gets corrupted on certain zoom levels:
![image](https://user-images.githubusercontent.com/18322360/54545040-23299200-49a1-11e9-9020-0b5cb902a379.png)

Tested on Google Chrome.

**Comment by BALKANGraph** [comment]
Released a new version to fix it 4.1.9

We are implementing a new feature "Different fields according to the zoom level". When the chart is zoomed out the text becomes unreadable and the developer will be able to define less text fields for zoomed out charts. The feature is not completed, this is why you sow the glitch

If you are interested in this feature see: https://jsfiddle.net/BALKANGraph/gjdLz056/
