### ISSUE TITLE
Can I use selection in edit form???

### ISSUE THREAD

**Issue by ooo2003003v2** [BALKANGraph/OrgChartJS#411]
hello there. I am creating a custom template for my project. I am trying to use selection for my edit form but I can find a way to do that. Any idea how to change the textbox to selection box?

**Comment by ZornitsaSerbezova** [comment]
Hi ooo2003003v2,

We have an example for this here:  https://jsfiddle.net/BALKANGraph/z6gpdx7n/

**Comment by ooo2003003v2** [comment]
Thank you.
