### ISSUE TITLE
use org chart js with smartadmin .net core template

### ISSUE THREAD

**Issue by mostafashabanelbanna** [BALKANGraph/OrgChartJS#412]
i want to use org chart inside my project which built with [smartadmin template](https://smartadmin-core.azurewebsites.net/).

when i tried to test org chart stand alone it works fine, but when i try to apply it in the project it doesn't work

**Comment by ZornitsaSerbezova** [comment]
Hi Mostafa,

OrgChart JS is a plane javascript, runs on any server that supports HTML, works in all modern browsers and uses SVG for the graphics rendering.
