### ISSUE TITLE
change message when nodes are not available

### ISSUE THREAD

**Issue by kksanghi** [BALKANGraph/OrgChartJS#413]
How to change this message

![image](https://user-images.githubusercontent.com/16228568/88018145-b8640a00-cb44-11ea-8fa6-72928182e576.png)

**Comment by ZornitsaSerbezova** [comment]
Hi Krishna,

You need to set this const before the definition of the chart:
`OrgChart.RES.IT_IS_LONELY_HERE_LINK = "It's lonely here, add your first node";`

**Comment by kksanghi** [comment]
thanks it's working
