### ISSUE TITLE
onExpCollClick

### ISSUE THREAD

**Issue by mi0o** [BALKANGraph/OrgChartJS#414]
Hello is onExpCollClick ore something inside my code deprecated? because my code stoped working .

Thanks 
		
       onExpCollClick: function (sender, action, id, ids) {
                    if (action == OrgChart.EXPAND) {
                        var node = sender.getBGNode(id);
                        var expandids = [];
                        if (node.children.length == 1 && node.childrenIds.length > 1) {
                            for (var i = 0; i < node.children[0].childrenIds.length; i++) {
                                expandids.push(node.children[0].childrenIds[i]);
                            }
                        }
                        sender.expand(id, ids, function () {
                            if (node.parent) {
                                for (var i = 0; i < node.parent.childrenIds.length; i++) {
                                    if (node.parent.childrenIds[i] != node.id) {
                                        expandids.push(node.parent.childrenIds[i]);
                                    }
                                }
                            }
                            sender.collapse(id, expandids, function () {
                            sender.center(id);
                           
                            });
                        });
                        return false;

                    }
                    if (action == OrgChart.COLLAPSE) {
                        var node = sender.getBGNode(id);
                        if (node.parent) {
                            sender.collapse(id, ids, function () {
                                sender.expand(id, node.parent.collapsedChildrenIds);

                            });
                            return false;
                        }
                    }
                },

**Comment by ZornitsaSerbezova** [comment]
Hi mi0o,

As the events in the options are deprecated, please use this definition of the event:

```
 var chart = new OrgChart(...);
        
         chart.on('expcollclick', function (sender, collapsing, id, ids) {
            // your code goes here 
            // return false; to cancel the operation
         });  

  chart.load(...);
 ````
Also please take a look here for the other changes: https://github.com/BALKANGraph/OrgChartJS/releases

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue. Please feel free to reopen it if needed.
