### ISSUE TITLE
Drag and drop compatibility with IE 11

### ISSUE THREAD

**Issue by Abhi8909** [BALKANGraph/OrgChartJS#415]
I have just upgraded my Balkan graph org chart library from 3.x.x to the latest version i.e.(7.1.3). The drag and drop functionality in IE seems to be not working but working fine chrome.
As with the version updated, my app is not behaving as with the previous version in IE.

Is there any way we can make it work drag and drop functionality in IE 11.

**Comment by ZornitsaSerbezova** [comment]
Fixed. Thank you for reporting it!
