### ISSUE TITLE
show all node at the same level in horizontal  direction instead of vertical 

### ISSUE THREAD

**Issue by nbpro** [BALKANGraph/OrgChartJS#417]
![balkan_graph](https://user-images.githubusercontent.com/3526202/88522776-7dfedf00-d014-11ea-9d15-9a06b822354a.png)
Hi @plamen-peshev ,

Is it possible to have a horizontal view of all the nodes at the same level ?
A Manager has 3 direct reportees and all of them are shown vertically, that creates a confusion.
Is there any way to align all the nodes at same level horizontally instead of vertically positing ?

@gs-nkumar

**Comment by ZornitsaSerbezova** [comment]
Hi nbpro,
Is this what you need?: https://jsfiddle.net/BALKANGraph/8fxuc4kb/

**Comment by ZornitsaSerbezova** [comment]
HI nbpro,
I'll close this issue as we answered to your email.
