### ISSUE TITLE
[question] Can it be used in LAN environment？

### ISSUE THREAD

**Issue by btredback** [BALKANGraph/OrgChartJS#419]
i can see OrgChartJS used will requests the URL[ https://kr-balkangraph.azurewebsites.net/api/OrgChartJS]，if want to use in LAN environment，can it display and using？

**Comment by ZornitsaSerbezova** [comment]
Hi btredback,

The licensed versions of OrgChart JS don't make any requests. You can use them without internet connection.

**Comment by btredback** [comment]
> Hi btredback,
> 
> The licensed versions of OrgChart JS don't make any requests. You can use them without internet connection.

Thanks, i try it
