### ISSUE TITLE
Roadmap | BALKANGraph

### ISSUE THREAD

**Issue by BALKANGraph** [BALKANGraph/OrgChartJS#42]
# Roadmap | BALKANGraph

The following represents BALKANGraph‘s current view of its product development cycle and future directions.

## [New feature] - Different fields according to the zoom level
When the chart is zoomed out the text becomes unreadable, with this enhancement developers will be able to define less text fields for zoomed out charts. See beta https://jsfiddle.net/BALKANGraph/gjdLz056/ 

## [New feature] - Organization Unit Views
Use case: 

1. On initial load the user will see “Companies” view
1. When user clicks Company node will see all “Departments” from the clicked company and “Companies” view will disappear
1. When the user clicks Department node the user will see all “Employees” from clicked department and “Departments” will disappear 
1. Etc..

The views will be configurable.

## [New product] - OrgChart Cloud for developers
1.	OrgChart Cloud can be used as serverless service and/or deployed on-premise.
2.	OrgChart Cloud will have an option to be shared and embedded in blogs.
3.	OrgChart Cloud API will be used for CRUD operations such as add node, remove node etc.
4.	The integration of OrgChart Cloud into client’s application will be for less than a minute.

## [New Sub Products] JavaScript Wrappers
1.	Angular wrapper
2.	React wrapper

## [New product] - GetOrgChart for HRs
Shutting down the current GetOrgChart library and create HRM system based on OrgChart Cloud, hosted under http://GetOrgChart.com

If you have idea how we could improve our product and service please write a comment

![OrgChart](https://balkangraph.com/content/img/logo1.jpg)

**Comment by hdbrinkmann** [comment]
Does "Shutting down the current GetOrgChart library" mean that the current OrgChart.js Module(from Balkangraph.com) will be discontinued?

**Comment by BALKANGraph** [comment]
No, the current OrgChart.js module will not be discontinued, we are not going to discontinue anything that is hosted under https://balkangraph.com 

There is 8 years old product, called GetOrgChart hosted under http://getorgchart.com

**Comment by scriptk1d** [comment]
Hi, I'm working in a big enterprise project(angular 8) and we are currently evaluating the use of your library. Is there already news concerning your planned angular integration?

**Comment by bansalr** [comment]
We are using OrgChart with Angular quite successfully.

**Comment by hdbrinkmann** [comment]
Our Dev-Team successfully integrated OrgChart.js in our Angular Application. However, I will double check if there are any open issues.

**Comment by lodossDev** [comment]
Is it possible to make OrgChart compatible with Salesforce Lightning Web Components:

The problem is around the locker service:
https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/security_code.htm

**Comment by plamen-peshev** [comment]
Thanks for the good suggestion 

We will add something similar to https://www.youtube.com/watch?v=173YD4o8-Fo in one of the next releases

**Comment by lodossDev** [comment]
any ideas what will be available in next release?

**Comment by ikishanoza** [comment]
we are using this with angular. Quite good but here are a few things that I can suggest.
1. Allow the user to move the node in canvas(not drag/drop) so the user can focus on specific nodes.
2. Dynamic templates are good but we need to change svg's for that can't we add directly div, span or even directly angular components? it will wider the scope of modifying node (html/css developer will come into picture :) )

**Comment by nbpro** [comment]
We are using org chart with angular, we have written our own wrapper over chart charts and fully customised it for our need, so far no such issues. We have our  own export service hosted on aws. yeah within salesforces we have some performance issues.

**Comment by Shubham994** [comment]
Is balkan graph provides scrollbar feature in search box?
can anyone help me regarding above issue, which I need to use in my application.

**Comment by ZornitsaSerbezova** [comment]
@Shubham994 
You can define your own search result. Here is a demo: https://balkangraph.com/OrgChartJS-Demos/SearchResultInTable

**Comment by gs-dchakraborty** [comment]
Using Balkangraph with Angular 8 , has anyone faced any issue while adding multiple nodes & then calling map.draw() method. For me the layout is completely out of the place after any action performed on the nodes via my custom event handlers.

**Comment by ZornitsaSerbezova** [comment]
> Using Balkangraph with Angular 8 , has anyone faced any issue while adding multiple nodes & then calling map.draw() method. For me the layout is completely out of the place after any action performed on the nodes via my custom event handlers.

I am using version 10, but it should be the same. It is working okay. You can try with brand new project: https://balkan.app/OrgChartJS/Docs/Angular

**Comment by VVariychuk** [comment]
Hey! Tell me how can I customize the colors to fit my needs or change the shape of the buttons + -
