### ISSUE TITLE
How to minimize children nodes of Group

### ISSUE THREAD

**Issue by MVSJES** [BALKANGraph/OrgChartJS#420]
modified from balkangraph.com Doc Minimize/Maximize Node 
https://jsfiddle.net/BALKANGraph/7ndeaxpz/

How to have children of Sales Group startup minimized?
 "minimize 1" and "minimize 2" nodes should start up minimized
Search or click on expand will show "minimize 1" and "minimze 2"
Thank you!

    <script>
 
        window.onload = function () {
    btnMinimize =
             '<svg fill="#aeaeae" x="498" y="17" height="24" width="24" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"' +
                 'viewBox="0 0 485 485" style="enable-background:new 0 0 485 485;" xml:space="preserve">' +
                '<path d="M0,0v485h485V0H0z M455,455H30V30h425V455z"/>' +
                '<polygon points="311.683,349.411 205.12,242.5 311.683,135.589 290.435,114.411 162.762,242.5 290.435,370.589     "/>' +
             '</svg>';
         btnMaximize =
             '<svg fill="#aeaeae" x="198" y="47" height="24" width="24" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"' +
                 'viewBox="0 0 485 485" style="enable-background:new 0 0 485 485;" xml:space="preserve">' +
                 '<path d="M0,0v485h485V0H0z M455,455H30V30h425V455z"/>' +
                 '<polygon points="194.565,370.589 322.237,242.5 194.565,114.411 173.317,135.589 279.88,242.5 173.317,349.411    "/>' +
             '</svg>';
 
         OrgChart.templates.group.min = Object.assign({}, OrgChart.templates.group);
         OrgChart.templates.group.min.name = '<text width="230" text-overflow="multiline" style="font-size: 24px;" fill="#aeaeae" x="125" y="65" text-anchor="middle">{val}</text>';
         OrgChart.templates.group.minBtn = btnMinimize +
             '<rect data-btn-min="{val}" x="498" y="17" height="24" width="24" fill="red" fill-opacity="0" opastroke-width="1" stroke="#aeaeae"></rect>';
         OrgChart.templates.group.min.maxBtn = btnMaximize +
             '<rect data-btn-max="{val}" x="198" y="47" height="24" width="24" fill="red" fill-opacity="0" opastroke-width="1" stroke="#aeaeae"></rect>';
         var chart = new OrgChart(document.getElementById("tree"), {
             enableSearch: false,
             mouseScrool: OrgChart.action.none,
             nodeBinding: {
                 name: "groupName",
                 field_0: "name",
                 field_1: "title",
                 img_0: "img",
                 minBtn: "id",
                 maxBtn: "id"
             },
             tags: {
                 "kcoi":{min:true},
                 "node-with-subtrees": {
                     min: true,
                     template: "group",
                     subTreeConfig: {
                         siblingSeparation: 3,
                         columns: 2
                     }
                 }
             }
             });
 
             nodes = [
                 {id: 0, title: "CEO", name: "Denny Curtis", img: "https://cdn.balkan.app/shared/2.jpg" },
                 {id: 1, pid: 0, tags: ["node-with-subtrees"], groupName: "Sales"},
                 {id: 2, stpid: 1, name: "Bret Fraser", title: "Sales", img: "https://cdn.balkan.app/shared/13.jpg"},
                 {id: 3, stpid: 1, name: "Steff Haley", title: "Sales", img: "https://cdn.balkan.app/shared/14.jpg"},
                 {id: 4, stpid: 1, name: "Ashley Barnett", title: "Sales", img: "https://cdn.balkan.app/shared/3.jpg"},
                 {id: 5, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},
                 {id: 6,   pid: 1,tags:["kcoi"], name: "minimize 1", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},
                 {id: 7,   pid: 1,tags:["kcoi"], name: "minimize 2", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},
             ];
 
 
             chart.on('redraw', (sender) => {
                 let minBtns = document.querySelectorAll('*[data-btn-min]');
 
                 minBtns.forEach(btn => {
                     btn.addEventListener('click', (e) => {
                         e.preventDefault();
                         e.stopPropagation();
                         chart.minimize(btn.getAttribute('data-btn-min'));
                     });
                 });
 
                 let maxBtns = document.querySelectorAll('*[data-btn-max]');
 
                 maxBtns.forEach(btn => {
                     btn.addEventListener('click', (e) => {
                         e.preventDefault();
                         e.stopPropagation();
                         chart.maximize(btn.getAttribute('data-btn-max'));
                     });
                 });
 
             });
 
             chart.load(nodes);
 };
    </script>`

**Comment by ZornitsaSerbezova** [comment]
Hi MVSJES,

To be able to minimize a node, you should have a **min** template for it.
Please see the first the example here: https://balkangraph.com/OrgChartJS/Docs/MinMax

**Comment by MVSJES** [comment]
Hi ZornitsaSerbezova,
Sorry, I asked wrong question.
I should ask how to minimize groups?
min:true did not work
We want to have all groups minimized at startup.
We have many groups in production.
This worked great with orgchart.js v6.6.2 in production

**Comment by ZornitsaSerbezova** [comment]
Is this what you need?: https://jsfiddle.net/BALKANGraph/mbx92yzt/

**Comment by MVSJES** [comment]
Yes.  Thank You, ZornitsaSerbezova!
This will help guide updates from v6.6.2 to v7 with groups.

**Comment by MVSJES** [comment]
Hi ZornitsaSerbezova,
Follow up question.
What is the equivalent in v7 for v6: OrgChart.templates.group_lacoe.expandCollapseSize = 30;   
With many groups and each group is automatically generated with 30 nodes.
v7 group expanded is showing 30 nodes horizontally 
Attached image shows how v6.6.2 displays the expanded group with 30 nodes
![group nodes](https://user-images.githubusercontent.com/69023860/89095795-24851000-d386-11ea-892e-df93d2881377.jpg)

nodes = [                                                                                                 
    {id: 0, title: "CEO", name: "Denny Curtis", img: "https://cdn.balkan.app/shared/2.jpg" },             
    {id: 1, pid: 0, tags: ."node-with-subtrees"^, groupName: "Sales1"},                                   
    {id: 2, stpid: 1, name: "Bret Fraser", title: "Sales", img: "https://cdn.balkan.app/shared/13.jpg"},  
    {id: 3, stpid: 1, name: "Steff Haley", title: "Sales", img: "https://cdn.balkan.app/shared/14.jpg"},  
    {id: 4, stpid: 1, name: "Ashley Barnett", title: "Sales", img: "https://cdn.balkan.app/shared/3.jpg"},
    {id: 5, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},  
    {id:15, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},  
    {id:25, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},  
    {id:35, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},  
    {id:45, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},  
    {id:55, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},  
    {id:65, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},  
    {id:75, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},  
    {id:85, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},  
    {id:95, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},  
    {id:05, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},  
    {id: 51, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"}, 
    {id: 52, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"}, 
    {id: 53, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"}, 
    {id: 54, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"}, 
    {id: 55, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"}, 
    {id: 56, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"}, 
    {id: 57, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"}, 
    {id: 58, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"}, 
    {id: 59, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"}, 
    {id: 50, stpid: 1, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"}, 
    {id: 6, pid: 0, tags: ."node-with-subtrees"^, groupName: "Sales2"},                                   
    {id: 7, stpid: 6, name: "minimize 1", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},    
    {id: 8, stpid: 6, name: "minimize 2", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg"},    
];

**Comment by MVSJES** [comment]
![group nodes toolbar](https://user-images.githubusercontent.com/69023860/89110861-f7774280-d403-11ea-8a6e-36549c8f3821.jpg)

Toolbar layout have no effect to nodes in group.

**Comment by ZornitsaSerbezova** [comment]
Hi MVSJES,

expandCollapseSize is not related to the number of nodes in the group. 
You could see in this demo how tow to set the number of rows: https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/Grouping


With the toolbar you could change the layout of the main chart.
You could see in the example here how you could change the layout of the subtrees: 
https://balkangraph.com/OrgChartJS/Docs/SubTrees

**Comment by MVSJES** [comment]
Thank You, ZornitsaSerbezova!
