### ISSUE TITLE
menu of the chart

### ISSUE THREAD

**Issue by MLEKMAD** [BALKANGraph/OrgChartJS#422]
Hi,
I want to export the chart to PDF, instead of the menu, is it possible to export using a button? can I change the menu icon because it is not visible ? 
![image](https://user-images.githubusercontent.com/50893696/89659490-e2008d80-d8c7-11ea-8982-d88dd7e8c6b7.png)
Thank you.

**Comment by ZornitsaSerbezova** [comment]
Hi MLEKMAD,

Here we have a demo for exporting using a button: https://balkangraph.com/OrgChartJS-Demos/ExportImportMethods

You need to add this in the configuration to have a menu icon:
```
 menu: {
            pdf: { text: "Export PDF" },
            png: { text: "Export PNG" },
            svg: { text: "Export SVG" },
            csv: { text: "Export CSV" }
        },
```
Here is the documentations: https://balkangraph.com/OrgChartJS/Docs/Menus

**Comment by MLEKMAD** [comment]
The problem of the exportPDF method occur too when I try to export using a button, I tried to store the chart in state but the error is still there.
Any idea how to do the analogy between the demos and the  actual react app because i guess there are some differences.
Thank you!

**Comment by ZornitsaSerbezova** [comment]
Hi MLEKMAD,
What is the error that you get?

**Comment by MLEKMAD** [comment]
I used the this.exportPDF instead of this.chart.exportPDF, btw i want to export using a button instead of a menu so I added an id to the button and an event listener like this : 
![image](https://user-images.githubusercontent.com/50893696/90014476-09c46c80-dc9f-11ea-94c5-c30e950099db.png)
And it keeps retutning this error:
![image](https://user-images.githubusercontent.com/50893696/90014207-91f64200-dc9e-11ea-83fc-f86f298e777c.png)
Thank u

**Comment by ZornitsaSerbezova** [comment]
In this case you need to use it this way:
```
document.getElementById("btn").addEventListener("click", function () {                
                chart.exportPDF({
                    header: 'my header goes here',
                    footer: 'my footer goes here',
                    format: 'A4',
                    margin: [60, 20, 60, 20]
                });
            });
```

**Comment by MLEKMAD** [comment]
I tried it but it doesnt recognize chart,
the button is in an other component and the code : ` document.getElementById("btn").addEventListener("click", function () {                
      this.chart.exportPDF({
          header: 'my header goes here',
          footer: 'my footer goes here',
          format: 'A4',
          margin: [60, 20, 60, 20]
      });
  });`
is in the component where I define the chart
im really stuck because the menu is invisible 
![image](https://user-images.githubusercontent.com/50893696/90025663-49468500-dcae-11ea-91ae-c4a00e1c2ed8.png)
so I need a button to do export the chart .
Thank u.

**Comment by ZornitsaSerbezova** [comment]
So, if the problem is that you don't see the menu button, you just need to make it visible.
Did you define it in the chat configuration?:
```
menu: {
            pdf: { text: "Export PDF" },
            png: { text: "Export PNG" },
            svg: { text: "Export SVG" },
            csv: { text: "Export CSV" }
        },
```
Here is the documentation about the menus: https://balkangraph.com/OrgChartJS/Docs/Menus

**Comment by MLEKMAD** [comment]
Its not that I dont see it, its there but its color is the same as the background, i tried changing the color of the background but it look  bad.
and in my case its better if I have a button instead of a menu cuz i already have the main menu

**Comment by ZornitsaSerbezova** [comment]
Here is how you cane change the menu icon: https://balkangraph.com/OrgChartJS-Demos/MenuIcon
and how to change the position: https://balkangraph.com/OrgChartJS-Demos/MenuPosition

**Comment by MLEKMAD** [comment]
Thanks a lot.
