### ISSUE TITLE
set Header of the exported file

### ISSUE THREAD

**Issue by MLEKMAD** [BALKANGraph/OrgChartJS#423]
Hello,
How can I set the Header and Footer of the exported file? I am using ReactJs.
Thank you!

**Comment by ZornitsaSerbezova** [comment]
Yes, you can see how to do it in this demo: https://balkangraph.com/OrgChartJS-Demos/A4ExportTitle

**Comment by MLEKMAD** [comment]
An error occurred when I try to use the function 
![image](https://user-images.githubusercontent.com/50893696/89662425-fb0b3d80-d8cb-11ea-926d-ee27edaa17a0.png)

**Comment by ZornitsaSerbezova** [comment]
Hi MLEKMAD,

In **React** you have to use **this.exportPDF** instead of this.chart.exportPDF
```
                                onClick: function () {
                                    this.exportPDF({
                                        header: 'my header goes here',
                                        footer: 'my footer goes here',
                                        format: 'A4',
                                        margin: [60, 20, 60, 20]
                                    });
                                }
```

**Comment by MLEKMAD** [comment]
Thank you, it worked.
