### ISSUE TITLE
Orgchart with Angular - Any custom data is not working

### ISSUE THREAD

**Issue by kalyanmdev** [BALKANGraph/OrgChartJS#424]
I have downloaded your free trial version of Orgchar.js. I have successfully integrated with my Angular application. But, when I change the data inside "nodes" array or "chart.load", the web page shows up empty. When I mentioned data, anything other than provided in the https://balkangraph.com/OrgChartJS/Docs/Angular sample.

I have simply added a new node apart from the ones given in the sample.
 For ex: 
                    { id: 1, name: "Denny Curtis", title: "CEO", img: "https://cdn.balkan.app/shared/2.jpg" },
                    { id: 2, pid: 1, name: "Ashley Barnett", title: "Sales Manager", img: "https://cdn.balkan.app/shared/3.jpg" },
                    { id: 3, pid: 1, name: "Caden Ellison", title: "Dev Manager", img: "https://cdn.balkan.app/shared/4.jpg" },
                    { id: 4, pid: 2, name: "Elliot Patel", title: "Sales", img: "https://cdn.balkan.app/shared/5.jpg" },
                    { id: 5, pid: 2, name: "Lynn Hussain", title: "Sales", img: "https://cdn.balkan.app/shared/6.jpg" },
                    { id: 6, pid: 3, name: "Tanner May", title: "Developer", img: "https://cdn.balkan.app/shared/7.jpg" },
                    { id: 7, pid: 3, name: "Fran Parsons", title: "Developer", img: "https://cdn.balkan.app/shared/8.jpg" }

To the above data, I have simply added, let's say the following line. 
{ id: 8, pid: 3, name: "Frank Robinson", title: "Developer", img: "https://cdn.balkan.app/shared/8.jpg" }

And the page comes up empty and no console errors. Any slight modification apart from the provided sample data is not working. 

We need help, if this integration works, our firm is interested in purchasing an enterprise license. Please help.

Thank you!

**Comment by ZornitsaSerbezova** [comment]
Hi kalyanmdev,

Please check for any syntax errors in the data.
Did you put a comma at the end of this line?:
`{ id: 7, pid: 3, name: "Fran Parsons", title: "Developer", img: "https://cdn.balkan.app/shared/8.jpg" }`

If you still have a problem, we could make an TeamViewer session to resolve it.

**Comment by kalyanmdev** [comment]
Hi ZornitsaSerbezova,

Thank you for your response. I did not put any comma at the end of the line. And Yes, we still need help. I would love to do a Team Viewer session. Please let me know what would be the best time that works for you. FYI: I work on EST time zone. Looking forward to the team viewer session details.

Thank you!

**Comment by ZornitsaSerbezova** [comment]
Hi kalyanmdev,
Please write us an email to support@balkangraph.com

**Comment by kalyanmdev** [comment]
Hi ZornitsaSerbezova,

Thanks for your response. I have sent an email with details. Looking forward to hearing back from you.

Thanks!

**Comment by ZornitsaSerbezova** [comment]
Hi kalyanmdev,

As far as I know the issue is fixed.

**Comment by kalyanmdev** [comment]
Yes. The issue has been fixed. Thanks for your support.
