### ISSUE TITLE
PDF Preview Issue - Urgent 

### ISSUE THREAD

**Issue by chenxu7601257** [BALKANGraph/OrgChartJS#426]
**Bug Description:** 
When previewing the organization chart in PDF, **_set the scale to 20% and the layout to portrait_**, then a complete organization chart will be divided into multiple pages. For example, the following case will be divided into two pages, but some of the organization chart will be disappeared, not found on these two pages. 
![image](https://user-images.githubusercontent.com/19574070/89883306-8ea97a80-dbfa-11ea-9af1-6db98d4dc12c.png)
![image](https://user-images.githubusercontent.com/19574070/89883349-9d902d00-dbfa-11ea-9c38-7bbaa48e640c.png)

**The complete organization chart looks like below,** 
![image](https://user-images.githubusercontent.com/19574070/89883413-b4368400-dbfa-11ea-9495-4beb66b84243.png)

Through the picture below, we clearly see that the highlight part has disappeared, not on the first page nor on the second page. 
Due to the delay in solving this problem, we receive various complaints every day. 
![image](https://user-images.githubusercontent.com/19574070/89883707-18594800-dbfb-11ea-9816-fd42739c8ccb.png)

**I hope everyone can help solve the problem or provide some solutions, thank you very much!**

**Comment by plamen-peshev** [comment]
We are working on the issue you reported

**Comment by plamen-peshev** [comment]
We have addressed the issue in the latest version: 

Here is a demo: [test.zip](https://github.com/BALKANGraph/OrgChartJS/files/5061998/test.zip)

**Comment by chenxu7601257** [comment]
> We have addressed the issue in the latest version:
> 
> Here is a demo: [test.zip](https://github.com/BALKANGraph/OrgChartJS/files/5061998/test.zip)

Thanks Plamen
We downloaded test.zip and encountered the warning message that is "**The trail has expired or 200 nodes limit was reached!**" (Please see below screenshot). 

Would it be possible to provide the latest version 7.1.98 of orgchart.js. We will have a try and provide feedback as soon as possible. Really appreciated! 
![image](https://user-images.githubusercontent.com/19574070/90008099-6d19c300-dcce-11ea-944b-cab9a209830d.png)

**Comment by ZornitsaSerbezova** [comment]
Hi chenxu7601257,

You could download the licensed version from your account.

**Comment by chenxu7601257** [comment]
> Hi chenxu7601257,
> 
> You could download the licensed version from your account.

It works. Really appreciated!!

**Comment by chenxu7601257** [comment]
@ZornitsaSerbezova With the new version library, we found two critical issue which not existing before. Please refer to the detail as below.  Issue 1:  can’t display the whole chart with latest version library, if change to the old one , display successfully. Like below. 
![image](https://user-images.githubusercontent.com/19574070/90521733-778bff00-e19d-11ea-88da-09b45b8c8479.png)
![image](https://user-images.githubusercontent.com/19574070/90521762-7fe43a00-e19d-11ea-9b7e-a657c969991f.png)

Issue 2:
With new version library 
Can’t trigger redraw event with new version library.

With old version library:
![image](https://user-images.githubusercontent.com/19574070/90521932-ae621500-e19d-11ea-92cd-ab1142626cf5.png)


Because of this,  the chart display can’t display correctly. This is very CRITICAL, Would you please help to  fixed this ASAP. Thanks very much.

**Comment by ZornitsaPesheva** [comment]
HI Jacob,
Are these problems resolved now? Can I close the issue?

**Comment by ZornitsaPesheva** [comment]
I am closing this issue as inactive.
