### ISSUE TITLE
Urgent-The line connecting between two nodes cannot be displayed correctly when we preview PDF

### ISSUE THREAD

**Issue by chenxu7601257** [BALKANGraph/OrgChartJS#427]
Our clients encountered another problem during use. Please refer to the following picture for details. We hope that your team could solve it in time. Due to this bug of orgchart, they cannot print the orgchart yet, which brings inconvenience to clients. 

Below is the complete graph, we could see that the line between two nodes displayed correctly. 
![image](https://user-images.githubusercontent.com/19574070/90086004-eefc0180-dd4b-11ea-92a3-62b0df35a182.png)

However, no matter the layout is portrait or landscape, no matter what scale it is, the line cannot be displayed correctly when we preview PDF. Please refer to below screenshot for better understanding. We've addressed the issue to your team months ago via email. 
![image](https://user-images.githubusercontent.com/19574070/90086095-32567000-dd4c-11ea-8925-477303767b87.png)

Hope it can attract your attention! 
Could you please advise when will it be solved, we can communicate with our clients well, thank you!

**Comment by ZornitsaSerbezova** [comment]
Hi Jacob,

For resolving the issue link we have added an option padding on export and preview.
Here is the demo:  https://balkangraph.com/OrgChartJS-Demos/Padding
