### ISSUE TITLE
can i load 15000+ users ?

### ISSUE THREAD

**Issue by sunsoftny** [BALKANGraph/OrgChartJS#43]
Dear sir,

* I put 15k+ users in BALKANGraph but can't view and browser also hanging.
* I checked JS fiddle also put my data 15k+ users but can't view properly so kindly please check my problem give me solution 

Thanking you

**Comment by BALKANGraph** [comment]
Please have a look at our demo: https://balkangraph.com/OrgChartJS/Demos/15kNodesCustomExpandCollapse

You can use it as starting point to develop your own solution
