### ISSUE TITLE
Is there any way to remove arrows on clinks and slinks?

### ISSUE THREAD

**Issue by NyashaZiwewe** [BALKANGraph/OrgChartJS#430]
I want to make my links non-directional. Is there any way to remove the arrows

**Comment by ZornitsaSerbezova** [comment]
Hi NyashaZiwewe,
Here is how you can do it:

        OrgChart.slinkTemplates.myTemplate = Object.assign({}, OrgChart.slinkTemplates.yellow);
        OrgChart.slinkTemplates.myTemplate.link = '<path stroke-dasharray="4, 2" stroke-linejoin="round" stroke="#FFCA28" stroke-width="2" fill="none" d="{d}" />';
        OrgChart.clinkTemplates.myTemplate = Object.assign({}, OrgChart.clinkTemplates.yellow);
        OrgChart.clinkTemplates.myTemplate.link = '<path stroke="#FFCA28" stroke-width="2" fill="none" d="{d}" />';

**Comment by NyashaZiwewe** [comment]
@ZornitsaSerbezova thank you so much. Let me try it out

**Comment by NyashaZiwewe** [comment]
@ZornitsaSerbezova here is my code, I am not sure where i am lost

   <script src="https://balkangraph.com/js/latest/OrgChart.js"></script>

<div id="tree"></div>
    <script>
    // OrgChart.slinkTemplates.olivia = Object.assign({}, OrgChart.slinkTemplates.yellow);
    // OrgChart.slinkTemplates.olivia.link = '<path stroke-dasharray="4, 2" stroke-linejoin="round" stroke="#FFCA28" stroke-width="2" fill="none" d="{d}" />';
    OrgChart.clinkTemplates.olivia = Object.assign({}, OrgChart.clinkTemplates.yellow);
    OrgChart.clinkTemplates.olivia.link = '<path stroke="#FFCA28" stroke-width="2" fill="none" d="{d}" />';

window.onload = function () {
    var chart = new OrgChart(document.getElementById('tree'), {
        template: 'olivia',
        orientation: OrgChart.orientation.top,
        clinks: [
            {from: 4, to: 0 }, 
            {from: 4, to: 5 },
            {from: 2, to: 6 },
        ]             
    });

    chart.load([
            { id: 0},
            { id: 1, pid: 0 },
            { id: 2, pid: 0 },
            { id: 3, pid: 1 },
            { id: 4, pid: 2 },
            { id: 5, pid: 1 },
            { id: 6, pid: 2 }
        ]);
};

    </script>

**Comment by ZornitsaSerbezova** [comment]
Hi NyashaZiwewe,

Could you please create an example in jsfiddle with your code, because here instead of 
` OrgChart.slinkTemplates.myTemplate.link = '<path stroke-dasharray="4, 2" stroke-linejoin="round" stroke="#FFCA28" stroke-width="2" fill="none" d="{d}" />';`
It looks like this:
`OrgChart.slinkTemplates.olivia.link = ''; `

**Comment by NyashaZiwewe** [comment]
@ZornitsaSerbezova thank you so much. You have saved my life. I finally found my mistake is using your code, I was misplacing myTemplate. i thought its the whole template whilst it is directly applied to cLinks

Here is my working code

        clinks: [
            {from: 4, to: 0, label: 'text'}, 
            {from: 4, to: 5, template: 'blue', label: '4 reports to 3' },
            {from: 2, to: 6, template: 'myTemplate', label: 'lorem ipsum' },
        ]

![image](https://user-images.githubusercontent.com/53811529/91814581-a2ae2e00-ec34-11ea-94ed-f96b6551f6af.png)
