### ISSUE TITLE
Is there a way to make the Organizational Chart FIXED ?

### ISSUE THREAD

**Issue by MLEKMAD** [BALKANGraph/OrgChartJS#431]
Hi,
I am wondering if there is a way to fix the chart. idk why but even if I did `scaleInitial: OrgChart.match.boundary,` The chart first fits the screen and then it gets bigger
![image](https://user-images.githubusercontent.com/50893696/90620022-db4c1180-e209-11ea-9d22-f1b951d0975e.png)
Thank you.

**Comment by ZornitsaSerbezova** [comment]
Hi MLEKMAD,

Could you please isolate an example in jsfiddle or in an HTML file with this issue?
