### ISSUE TITLE
How to set tooltip in item of Node?

### ISSUE THREAD

**Issue by PTOAKKY** [BALKANGraph/OrgChartJS#433]
how to set tooltip like this when text  was ellipsis. (this example from https://jsfiddle.net/mrgb9njd/).

![Hover proplem](https://user-images.githubusercontent.com/59352415/90871911-03806f80-e3c6-11ea-879b-7adff05e6f8a.PNG)

**Comment by ZornitsaSerbezova** [comment]
Hi PTOAKKY,

We have created a demo for you:  https://balkangraph.com/OrgChartJS-Demos/TooltipOnField
