### ISSUE TITLE
Drag or scrolling related issue

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#434]
Hi @ZornitsaSerbezova @plamen-peshev 

The scrolling or dragging is not working fine in IPAD and we are facing a lot of issues. Please check it once.

**Comment by ZornitsaSerbezova** [comment]
I have answered to your email.

**Comment by pushpender98** [comment]
HI @Zornitsa Serbezova

Software version: 13.3.1
Browser: Safari

Please look into this on priority.

Settings we have done:-
For responsive devices, we have given mouseScrool value to none and for desktop it is scrollable.

Tried all the other properties, but didn’t work.

**Comment by pushpender98** [comment]
Any update over this :)

**Comment by ZornitsaSerbezova** [comment]
fixed

**Comment by pushpender98** [comment]
Yeah thanks you
