### ISSUE TITLE
How to set custom onClick action

### ISSUE THREAD

**Issue by NovaBG03** [BALKANGraph/OrgChartJS#437]
I want when I click on the node of the tree not to display the default view on the right but to execute some other logic

**Comment by ZornitsaSerbezova** [comment]
Hi NovaBG03,

Here we have a demo on how to use single or double click: https://balkangraph.com/OrgChartJS-Demos/SingleAndDoubleClickOnNode

**Comment by NovaBG03** [comment]
Thank you! I just needed to add `nodeMouseClick: OrgChart.action.none` in the options object when creating `new OrgChart`.

Btw I just saw that you are Bulgarian company. That's so cool. Аз също съм българин. 🇧🇬 💯
