### ISSUE TITLE
How to avoid showing custom Edit Form when click on the group node ?

### ISSUE THREAD

**Issue by nlonguit** [BALKANGraph/OrgChartJS#439]
I built a custom Edit Form based on the Doc: https://balkangraph.com/OrgChartJS/Docs/Edit
It's working just fine when clicking on node. But after i group the nodes inside group, click on Group layout still show the custom Edit UI which it should not. How to do we prevent it or how do we make another custom edit UI for group node?
![image](https://user-images.githubusercontent.com/11536790/92305398-265b7800-efb1-11ea-95cb-ec6314b3086d.png)

**Comment by ZornitsaSerbezova** [comment]
Hi nlonguit,
We have created a demo for you: https://balkangraph.com/OrgChartJS-Demos/Disabl%D0%B5DetailsOnGroup

**Comment by nlonguit** [comment]
Thanks Zornitsa,
Based on your demo, i get the way to prevent custom Edit Form show up when click on group. But it's not the same code. Here is my code:

```
editUI.prototype.show = function (nodeId) {
 let node = orgChart.get(nodeId);
  console.log('node.stChildrenIds@', node);
  if (!node){
     return false;
  }
}
```
I thought maybe i am not using the latest version of Orgchart.js so that i downloaded latest version on web site. But i got this error with latest version and didn't know how to fix:

```
orgchart.js:1 Uncaught TypeError: Cannot read property 'scaleLessThen' of undefined
    at Function.OrgChart.t (orgchart.js:1)
    at Object.node (orgchart.js:1)
    at orgchart.js:1
    at orgchart.js:1
    at orgchart.js:1
    at Object.OrgChart.remote._proceed (orgchart.js:1)
    at orgchart.js:1
    at XMLHttpRequest.n.onload (orgchart.js:1)
```

**Comment by ZornitsaSerbezova** [comment]
Hi nlonguit,

If you have used version below 7 you could see here what are the changes in version 7: https://github.com/BALKANGraph/OrgChartJS/releases/tag/7.0.1

Here you can see how to make groups in version 7:  https://balkangraph.com/OrgChartJS/Docs/SubTrees
Look for **Group nodes** in this docs page. Here is the example: https://jsfiddle.net/BALKANGraph/z025a6ny/
