### ISSUE TITLE
Grouping issue 

### ISSUE THREAD

**Issue by hdbrinkmann** [BALKANGraph/OrgChartJS#44]
[4PLANOrgChart.html.zip](https://github.com/BALKANGraph/OrgChartJS/files/2982735/4PLANOrgChart.html.zip)
I have a problem with grouping. Please use the attached file, open "Haeger, Max" and then "Müller, Bruno". You will see a lot of "Azubi". Drag "Azubi, Axel" (very bottom) over "Azubi, Andreas" (right side above Axel). The Menu appears. Choose "Add in Group" -> nothing happens. Choose "Add as Child" -> a Group is created. Then drag "Azubi, Andrea" (at the left) over "Azubi, Andreas", the same Menu Problem. When you choose "Add as Child" after trying "Add in Group" the Group and its content disappears.

**Comment by BALKANGraph** [comment]
Thanks for the detailed explanation and for the zip file

I was able to reproduce it

Until we fix the issue as quick workaround you can set BALKANGraph.LAZY_LOADING_FACTOR = 5000;

Tell me if it helps

**Comment by hdbrinkmann** [comment]
It helps :-)

**Comment by ZornitsaSerbezova** [comment]
Fixed
