### ISSUE TITLE
How to avoid showing the tags "sub_level 0" when drawing sublevel tree?

### ISSUE THREAD

**Issue by zhangxinlu16** [BALKANGraph/OrgChartJS#440]
I want to keep their hierarchical relationship when drawing the sublevel tree diagram, but I don't want to show 'sub level 0'. How should I adjust?
![image](https://user-images.githubusercontent.com/16523572/92586655-24532b00-f2c9-11ea-8a41-c630c7aa8a70.png)

**Comment by ZornitsaSerbezova** [comment]
Hi zhangxinlu16,

Here we have a demo on hiding tags: https://balkangraph.com/OrgChartJS-Demos/HideFieldNamesAndTags
