### ISSUE TITLE
Sublevel can't work with tooltip?

### ISSUE THREAD

**Issue by zhangxinlu16** [BALKANGraph/OrgChartJS#441]
When I want to add tooltip to the sublevel diagram, it can't run. When I remove the tags of sub_level, it can run, but it can't show the hierarchical relationship. It will be displayed on the same layer

**Comment by plamen-peshev** [comment]
Modified the demo to work with sub levels and tooltips

See test.zip below

[test.zip](https://github.com/BALKANGraph/OrgChartJS/files/5207672/test.zip)
