### ISSUE TITLE
cpu 90% if zoom quickly

### ISSUE THREAD

**Issue by tenadolanter** [BALKANGraph/OrgChartJS#443]
cpu 90% if zoom quickly， version  7.4.31

**Comment by tenadolanter** [comment]
anyone else？

**Comment by plamen-peshev** [comment]
I have tried to reproduce the issue to no avail

Can you try to control the Scroll sensitivity, see "Scroll sensitivity" section from [this ](https://balkangraph.com/OrgChartJS/Docs/Navigation) help article

**Comment by vvlasovv** [comment]
@tenadolanter, @plamen-peshev I can confirm that animated zoom with mousewheel (mouseScrool: OrgChart.action.zoom) works slow and loads the CPU under certain conditions. By the moment I cannot provide a stable reproducible example as there are many factors that may affect the performance.
Zooming programmatically without animation works fast and smooth on our setup.
`chart.zoom(Math.pow(scaleFactor, zoom - zoomPrevious), null, false);`

**Comment by ZornitsaPesheva** [comment]
Hi! Does anybody still have this issue?
