### ISSUE TITLE
The ExpanCollapseToLevel  in the official demo report errors,how to resolve?thanks 

### ISSUE THREAD

**Issue by xinrulianhua** [BALKANGraph/OrgChartJS#446]
[https://balkangraph.com/OrgChartJS-Demos/ExpanCollapseToLevel](url)

**Comment by ZornitsaSerbezova** [comment]
Hi xinrulianhua,

Thanks for reporting this issue. We will try to resolve it soon.

**Comment by ZornitsaSerbezova** [comment]
We have fixed the demo.
