### ISSUE TITLE
Click on a node fires "drag" event

### ISSUE THREAD

**Issue by vvlasovv** [BALKANGraph/OrgChartJS#447]
It would be good to make "drag" event more precise. Currently "grab & move" on a node fires only "drag" event, but clicking a node fires both "drag" and "click" events.

A simple example on how to reproduce:

`chart.on('drag', function () {
    console.log('drag');
});`
`chart.on('click', function () {
    console.log('click');
});`

Chrome 85.0.4183.83, macOS 10.15.6, @balkangraph/orgchart.js@7.4.31

**Comment by ZornitsaSerbezova** [comment]
Hi vvlasovv,

We were able to reproduce the issue and will try to find a solution.

**Comment by plamen-peshev** [comment]
The enhancement is implemented in the latest version 7.4.32

See [this ](https://jsfiddle.net/BALKANGraph/2hm04671/) demo - clear browser cache before testing 

Also you can control the behavior by setting OrgChart.FIRE_DRAG_NOT_CLICK_IF_MOVE const, it is in pixels with default value 3px
