### ISSUE TITLE
How to add event listener to new added field?

### ISSUE THREAD

**Issue by Vitao18** [BALKANGraph/OrgChartJS#448]
Hey there,  first of all, thanks for the great work!

I'm running into an issue right now and I don't seem to find it anywhere else
How can I listen to click to a field that I added?
E.g: 
```
nodeBinding: {
   field_0: 'title',
    field_1: 'name',
    viewNode: 'viewNode',
    addNode: 'addNode',
    buttonMore: 'buttonMore',
    img_0: 'avatar',
}
```
How could I add an onClick event to my avatar, for example?

**Comment by ZornitsaSerbezova** [comment]
Hi Victor,

Here we have a demo on how to use on field click: https://balkangraph.com/OrgChartJS-Demos/ShowIdOnFieldClick

**Comment by Vitao18** [comment]
Thanks @ZornitsaSerbezova 
Got it working
