### ISSUE TITLE
Nodes being overlayed by another

### ISSUE THREAD

**Issue by Vitao18** [BALKANGraph/OrgChartJS#449]
Hi there,

I'm trying to render a tree dynamically making a request to fetch nodes lazily but I get a problem that two siblings nodes are being overlayed one by the other

![image](https://user-images.githubusercontent.com/14141039/93125347-643b5900-f6a1-11ea-9370-52afa0438f99.png)

Is there anything that I'm doing wrong here?

**Comment by ZornitsaSerbezova** [comment]
Hi Victor,

You don't need to do that. You can load the whole chart at once. OrgChart JS uses Lazy loading and works very well with very large amount of nodes.

**Comment by Vitao18** [comment]
Thanks @ZornitsaSerbezova
We managed to do it without loading the three again, just adding nodes one by one

In fact, we want to do it that way because the tree will look different based on some search inputted by the user
