### ISSUE TITLE
Error getting attribute

### ISSUE THREAD

**Issue by phelippe** [BALKANGraph/OrgChartJS#45]
Hi, I'm having a bug when I bind some specific attr.  See "JobGrade". If I change to another attr (integer) to test, it works fine.

https://jsfiddle.net/phelippem/pf8hLtkd/1/

**Comment by BALKANGraph** [comment]
Remove rect svg element from the text fields and add them in the template.node.

Some calculations are performed with the text fields for text wrapping and if there is a rect element the chart could not work as expected
