### ISSUE TITLE
Binary tree move to the RIGHT or LEFT

### ISSUE THREAD

**Issue by fiberson** [BALKANGraph/OrgChartJS#450]
Hey. I have qusetion. I have a table and in table we have some user and actions (move to Right or Left), how can i connect the action in the code for balkan graph js? Sorry for bad english btw, i'm russian. Here is screenshot
![screenshot](https://user-images.githubusercontent.com/54566317/93200973-31549c00-f759-11ea-8f7b-2522d4256faa.PNG)

**Comment by ZornitsaSerbezova** [comment]
Hi fiberson,

Could you try to explain the issue in more details? You could use Google translate form Russian to English.

**Comment by fiberson** [comment]
I took yours and used the Binary Template. I want to understand how I can make left and right distributions by clicking on buttons. I have attached the screenshot above. I have made a regular table where users go, there are 2 buttons on the right - one to the right, the other to the left. I saw in your script a mention of adding left and right, but I can't figure out how I can do it on the button.
Here is Laravel referals.blade.php

@extends('layouts.app')

@section('content')
    
    <div class="bg-image overflow-hidden" style="background-image: url('/assets/media/photos/photo3@2x.jpg');">
        <div class="bg-primary-dark-op">
            <div class="content content-narrow content-full">
                <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center mt-5 mb-2 text-center text-sm-left">
                    <div class="flex-sm-fill">
                        <h1 class="font-w600 text-white mb-0 invisible" data-toggle="appear">Plutus - Рефералы</h1>
                        <h2 class="h4 font-w400 text-white-75 mb-0 invisible" data-toggle="appear" data-timeout="250">Таблица Ваших рефералов</h2>
                        <p class="h3 bg-primary font-w400 text-white-75 mb-0 invisible" data-toggle="appear" data-timeout="250">Кол-во Ваших рефералов: 53</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
 

<form action="#" method="POST" enctype="multipart/form-data">
						@csrf
						@method('PUT')
<div class="block">
    <div class="block-header">
        <h3 class="block-title">Бинарная система <small>с сортировкой/поиском/экспортом</small></h3>
    </div>
    <div class="block-content block-content-full">
        
        <table class="table table-bordered table-striped table-vcenter js-dataTable-buttons">
            <thead>
                <tr>
                    <th class="text-center" style="width: 80px;">ID</th>
                    <th>Name</th>
                    <th class="d-none d-sm-table-cell" style="width: 30%;">Email</th>
                    <th class="d-none d-sm-table-cell" style="width: 15%;">Пакет</th>
                    <th class="text-center" style="width: 15%">Распределить</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="text-center font-size-sm">1</td>
                    <td class="font-w600 font-size-sm">
                        <a href="#">Brian Stevens</a>
                    </td>
                    <td class="d-none d-sm-table-cell font-size-sm">
                        client1<em class="text-muted">@example.com</em>
                    </td>
                    <td class="d-none d-sm-table-cell">
                        <span class="badge badge-success">VIP</span>
                    </td>
                    <td>
                        <a class="btn btn-primary" style="color:#fff" href="javascript:void(0)">Налево</a>
                        <a class="btn btn-primary" style="color:#fff" onclick="sender">Направо</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
</form>



<script src="/assets/js/orgchart.js"></script>
<div class="block">
<div class="block-header">
    <h3 class="block-title">Динамическая таблица <small>в разработке</small></h3>
</div>
<div id="tree" style="width:100%;height:500px;"></div>

<script>

window.onload = function () {

    OrgChart.templates.binary = Object.assign({}, OrgChart.templates.ana);
    OrgChart.templates.binary.size = [50, 50];
    OrgChart.templates.binary.node = '<circle cx="25" cy="25" r="25" fill="#039BE5"></circle>';
    OrgChart.templates.binary.plus = '';
    OrgChart.templates.binary.minus = '';
    OrgChart.templates.binary.field_0 = '<text fill="#ffffff" x="25" y="30" text-anchor="middle">{val}</text>';
    OrgChart.templates.binary.link = '<path stroke="#aeaeae" stroke-width="1px" fill="none" d="M{xa},{ya} C{xb},{yb} {xc},{yc} {xd},{yd}"/>';
    OrgChart.templates.binary.svg = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="display:block;" width="{w}" height="{h}" viewBox="{viewBox}">{content}</svg>';

    OrgChart.templates.empty = Object.assign({}, OrgChart.templates.binary);
    OrgChart.templates.empty.node = '';
    OrgChart.templates.empty.size = [50, 50];
    OrgChart.templates.empty.link = '';

    var chart;


    chart = new OrgChart(document.getElementById('tree'), {
        template: 'ula',
        levelSeparation: 40,
        enableSearch: true,
        nodeMouseClick: OrgChart.action.expandCollapse,
        tags: {
            empty: { template: 'empty' }
        },
        nodeBinding: {
            field_0: 'id',
            field_1: 'name',
            img_0: 'photo',
        }
    });

    chart.on('ready', function (sender, tree) {
        var nodes = tree.nodes;
        for (var id in nodes) {
            var node = nodes[id];
            if (node.parent && node.parent.children.length == 1) {
                var siblingNode = new OrgChart.node(node.id + 'sibling', node.parent.id,  ['empty'], 'empty');
                if (node.leg == 1) { //add left
                    node.parent.children.push(siblingNode);
                } else { //add right
                    node.parent.children.splice(0, 0, siblingNode);
                }
                siblingNode.parent = node.parent;
                nodes[siblingNode.id] = siblingNode;
            }
        }
    });
    
    chart.load([
        { id: {{ $root_node->id }}, name: "{{ $root_node->name }}(Вы)", photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Vladimir_Putin_%282017-07-08%29.jpg/250px-Vladimir_Putin_%282017-07-08%29.jpg", plan: "{{ $root_node->package->price() }}"},
        @foreach($referrals as $referral)
            { id: {{ $referral->id }}, pid: {{ $referral->binary_referrer_id }}, name: "{{ $referral->name }}", leg: {{ $referral->binary_leg }} },
        @endforeach
    ]);
}

</script>

@endsection

**Comment by fiberson** [comment]
I took yours and used the Binary Template. I want to understand how I can make left and right distributions by clicking on buttons. I have attached the screenshot above. I have made a regular table where users go, there are 2 buttons on the right - one to the right, the other to the left. I saw in your script a mention of adding left and right, but I can't figure out how I can do it on the button.

**Comment by ZornitsaSerbezova** [comment]
Hi fiberson,

In our script we add an "empty" node on left or right only if the node doesn't have sibling. In the other cases the nodes are ordering automatically from left to right. 
Is that what you need?

**Comment by fiberson** [comment]
How can i add node to left side (for example) depends on some node param(leg)?

**Comment by ZornitsaSerbezova** [comment]
You could try using orderBy option together with the empty node : https://balkangraph.com/OrgChartJS/Docs/APIReference#orderBy

**Comment by ZornitsaSerbezova** [comment]
Hi fiberson, did you solve your problem?

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue, as it looks inactive.
Feel free to reopen it if needed.
