### ISSUE TITLE
There is a bug in using Firefox that  when dragged node moves to the edge of another node, the whole svg moves. you may try it.

### ISSUE THREAD

**Issue by xinrulianhua** [BALKANGraph/OrgChartJS#451]
![1](https://user-images.githubusercontent.com/13449342/93204733-2ade1880-f789-11ea-90e6-1598da7c7ec5.png)
![2](https://user-images.githubusercontent.com/13449342/93204741-2d407280-f789-11ea-89e0-40c92f99b74a.png)

**Comment by ZornitsaSerbezova** [comment]
Hi xinrulianhua,

We have reproduced the issue and will try to fix it soon.

**Comment by ZornitsaPesheva** [comment]
Could you check if this issue is fixed?
