### ISSUE TITLE
Display expand button even without children

### ISSUE THREAD

**Issue by Vitao18** [BALKANGraph/OrgChartJS#452]
Hi there,

Is there a way to display the expand button when there are no children associated pid associated to the id of the node?

**Comment by ZornitsaSerbezova** [comment]
Hi Victor,

Here we have an example on how to add expand button: https://jsfiddle.net/BALKANGraph/oj4hdbL8/

**Comment by Vitao18** [comment]
Thanks for the support @ZornitsaSerbezova
