### ISSUE TITLE
How to create Costume Template in Vue js

### ISSUE THREAD

**Issue by tarang19** [BALKANGraph/OrgChartJS#453]
Can any one tell me how to create Costume Template in Vue js (Royal Family template)

**Comment by ZornitsaSerbezova** [comment]
Hi tarang19,

We have sent you email with demos.

**Comment by ZornitsaSerbezova** [comment]
Hi Tarang,
Did you manage to create your template?

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue, as it looks inactive.
Feel free to reopen it if needed.
