### ISSUE TITLE
Removing node with assistant does not work

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#454]
You can reproduce it here: [https://jsfiddle.net/m8sg7huq/](https://jsfiddle.net/m8sg7huq/)
Please click on 'RemoveNode' button.

**Comment by ZornitsaSerbezova** [comment]
Thank you for reporting this issue.

**Comment by ZornitsaSerbezova** [comment]
Here is the resolution for your issue: https://jsfiddle.net/yxcq4ubr/1/

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue, because it looks resolved, but you can feel free to reopen it if needed.
