### ISSUE TITLE
Image does not get export to pdf

### ISSUE THREAD

**Issue by nehac131288** [BALKANGraph/OrgChartJS#456]
We have purchased orgchart js license.I am exporting images in my code to pdf. But the image does not get displayed.Images are not taken from any path but downloaded after taking the id from database.

**Comment by ZornitsaSerbezova** [comment]
In order images to be exported, the export service need to have access to these images. The easiest way is to make images public.
You could also install your own [export service](https://github.com/BALKANGraph/export-service).

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue as it looks like the question is answered, but you can feel free to reopen it if needed.
