### ISSUE TITLE
Dynamically assign id when changing orientation

### ISSUE THREAD

**Issue by nehac131288** [BALKANGraph/OrgChartJS#457]
For Now,we hardcode the id as chart.center('1') in js for changing orientation -Horizontal & Vertical..Can we dynamically provide value of id as in my code I will be passing empno from codebehind which will vary for every company on every site.

**Comment by ZornitsaSerbezova** [comment]
You want like to dynamically change the value of the node that you'd like to center? 
Could you give us more detailed information with screenshots of what exactly want to achieve?

**Comment by nehac131288** [comment]
Yes,dynamically change the value of the node that you'd like to center.

**Comment by ZornitsaSerbezova** [comment]
So you could say chart.center(id).

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue, as it is answered, but can feel free to reopen it if needed.
