### ISSUE TITLE
Add new issue

### ISSUE THREAD

**Issue by hdbrinkmann** [BALKANGraph/OrgChartJS#46]
I am trying to add a new Element under "Tanner May" on your demo website https://balkangraph.com/OrgChartJS/Demos/BasicUsage 

I an add a new Element, but cant save any data using the "Edit" menu. 

I also tried to upload an image for the new element which did not work either, may be same problem...

I also tried to change the Name of Mr. Tanner using the "Edit" Menu, didn't work either. 

MacOS Mojave, Chrome

**Comment by phelippe** [comment]
Works nice for me. Have you tried the node menu, edit node option ?

**Comment by hdbrinkmann** [comment]
Found my mistake - data won't be saved unless I use the arrow at the top right to close the dialog
