### ISSUE TITLE
show difference layout with difference number of children

### ISSUE THREAD

**Issue by tenadolanter** [BALKANGraph/OrgChartJS#460]
The  node has children more than 8,  the layout show be `OrgChart.tree`, otherwise ,  the layout show be `OrgChart.treeLeftOffset` or `OrgChart.treeRightOffset`.

so is there any solutions? thanks!

**Comment by ZornitsaSerbezova** [comment]
Hi Tenado,

Here is the demo: https://balkangraph.com/OrgChartJS-Demos/ChengeLayout

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue as it is answered. Feel free to reopen it if needed,
