### ISSUE TITLE
Calling the function 'expand' clears the whole view

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#462]
You can reproduce it here:

[https://jsfiddle.net/nu2pveqz/2/](https://jsfiddle.net/nu2pveqz/2/)

Please click on the "ExpandNode" button

**Comment by ZornitsaSerbezova** [comment]
4 in  chart.expand(4, [5]);   should be already expanded node. This is the node that you don't want to change its position on the screen.

**Comment by sks4u** [comment]
My problem is that I am not able to determine whether a node is collapsed or expanded. See #407, so I cannot avoid this error.

**Comment by ZornitsaSerbezova** [comment]
You can try to look in the parents above which one will return **true** for node.collapsed and then expand it.

**Comment by ZornitsaPesheva** [comment]
Now thisd issue is fixed.
https://jsfiddle.net/BALKANGraph/mpb1txuc/
