### ISSUE TITLE
Behaviour of 'updateNode'

### ISSUE THREAD

**Issue by sks4u** [BALKANGraph/OrgChartJS#463]
Please reproduce the issue here:
[https://jsfiddle.net/d148mfew/](https://jsfiddle.net/d148mfew/)

Please expand the node 'Lynn Hussain'
Click on 'transferNode'
The node 'Elliot Patel' is inserted in a collapsed state.

Restart the sample. 
Please expand the nodes 'Lynn Hussain' and 'Ashley Barnett'.
Click on 'transferNode'.
The node 'Elliot Patel' is inserted in a expanded state.

This behavior is really confusing. Especially because I use updateNode instead of update

**Comment by plamen-peshev** [comment]
It is expected behavior, if the node is colapased and you transfer it it will be colapased again 

See https://jsfiddle.net/BALKANGraph/cry9nx73/

         chart.updateNode(elliot, function(){
                	chart.expand(5, [4])
                });
