### ISSUE TITLE
Show another field instead of id on search bar

### ISSUE THREAD

**Issue by Vitao18** [BALKANGraph/OrgChartJS#464]
Hi there,

Is there any way to show another field in the search bar results instead of the id property?

**Comment by ZornitsaSerbezova** [comment]
Hi Victor,

Here we have a demo on how to customize the search button and result: 
https://balkangraph.com/OrgChartJS-Demos/SearchResultInTable

You need to change the  **OrgChart.searchUI.createItem fuction.**

**Comment by Vitao18** [comment]
Thanks one more time @ZornitsaSerbezova 
That solved my problem
