### ISSUE TITLE
Building double sided family trees

### ISSUE THREAD

**Issue by martin255165** [BALKANGraph/OrgChartJS#465]
Hi,

I work on a company that are developing a webservice for tracing genetic diseases and need to create family trees of blood relatives on both the maternal and paternal side. The demo graph of the british royal family looked very promising as a template for how such a family tree could be implemented but when I tried to create a sample tree of my own it failed to display all the nodes in the tree. The tree I am trying to create looks something like this:

[https://drive.google.com/file/d/1JrotmzLe9w4W7QPNqECtreKf0nwKsDMF/view?usp=sharing](https://drive.google.com/file/d/1JrotmzLe9w4W7QPNqECtreKf0nwKsDMF/view?usp=sharing)

The first patient you find is the index patient and from that person you trace all his/hers blood relatives. In a real world family tree there can be several instances of certain nodes such as siblings, children and parents siblings. When I tried to create this diagram with OrgChart JS the index patient node and its child nodes wasn&#39;t rendered. Instead there were 2 separate graphs, one for the maternal side and one for the paternal side. It looks like this:

[https://drive.google.com/file/d/1_xrh9ZsvMaZu8tXPQLSI915CIQQds9zR/view?usp=sharing](https://drive.google.com/file/d/1_xrh9ZsvMaZu8tXPQLSI915CIQQds9zR/view?usp=sharing)

Is it possible to create a graph looking like the upper graph above with OrgChart.js? Could you for instance implement the maternal and paternal side as subtrees or mother and father as partners to the index patient?

My code for rendering the chart looks like this:
`var chart = new OrgChart(document.getElementById(&quot;orgchart&quot;), {

    nodeBinding: {  
        field\_0: 'name'  
    },  
    nodes: [
        { id: 1, name: 'MaternalGrandMother' },  
        { id: 2, pid: 1, tags: ['partner'], name: 'MaternalGrandFather' },  
        { id: 3, pid: 1, ppid: 2, name: 'MaternalParentsSibling' },  
        { id: 4, pid: 3, name: 'MaternalCousin' },  
        { id: 5, pid: 1, ppid: 2, name: 'Mother' },  
        { id: 6, name: 'PaternalGrandMother' },  
        { id: 7, pid: 6, tags: ['partner'], name: 'PaternalGrandFather' },  
        { id: 8, pid: 6, ppid: 7, name: 'PaternalParentsSibling' },  
        { id: 9, pid: 8, name: 'PaternalCousin' },  
        { id: 10, pid: 6, ppid: 7, name: 'Father' },  
        { id: 11, pid: 5, ppid: 10, name: 'Indexpatient' },  
        { id: 12, pid: 5, ppid: 10, name: 'Sibling' },  
        { id: 13, pid: 5, name: 'MaternalHalfSibling' },  
        { id: 14, pid: 13, name: 'MaternalHalfSiblingsChild' },  
        { id: 15, pid: 10, name: 'PaternalHalfSibling' },  
        { id: 16, pid: 15, name: 'PaternalHalfSiblingsChild' },  
        { id: 17, pid: 11, name: 'Child' },  
        { id: 18, pid: 17, name: 'GrandChild' },  
    ]`

**Comment by ZornitsaSerbezova** [comment]
Hi Martin,

With OrgChart JS In order one node to have Father and Mother, one of them should be partner of the other, In your case you’d like **Father** and **Mother** to be “parents" of the **Indexpatient**, but non of them is partner of the other.

**Comment by martin255165** [comment]
Hi Zornitsa,

The problem is that both Mother and Father use pid and ppid to connect them to their respective parents. In the examples i have seen of the use of partner, the partner can only be connected to one person, the one they are partnered with. When I try to set Mother or Father as partner even more nodes isn't rendered. If I remove the connection between the index patients and father but keeps it between the index and mother  the index aptient and it's subnodes are rendered properly. Could I 
implement the paternal side as a subtree of the index patient?

**Comment by ZornitsaSerbezova** [comment]
How do you imagine the visualization with a subtree?

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue as it looks inactive. Feel free to reopen it if needed.
