### ISSUE TITLE
Change size of image displayed in circle format?

### ISSUE THREAD

**Issue by kkmaier** [BALKANGraph/OrgChartJS#466]
Is there a way to display a smaller image on a chart using the circle format?

**Comment by ZornitsaSerbezova** [comment]
Could you show us with screenshots what exactly would you like to do?

**Comment by kkmaier** [comment]
I have attached a screenshot of the chart. As you can see, the images with
a white background look good, but those with colored backgrounds do not
look professional.

Thanks,

Karl


*Karl K. Maier*
Director of Customer Satisfaction
713.927.6182
karlmaier@abunden.com
www.abunden.com

<https://t.sidekickopen76.com/s1t/c/5/f18dQhb0S7kF8cFJvGVt3mWS59hl3kW7_k2841CXdp3MPwTPjvLX8XW2bzNLx99wQTL101?te=W3R5hFj4cm2zwW4mKLS-3z7-GnW3H4SZs3Fbt5S0&si=8000000003411254&pi=38b2b9e3-f297-437f-ca5a-f199c708eeda>
*We make the pie bigger*

Stay connected with Karl on
<https://t.sidekickopen76.com/s1t/c/5/f18dQhb0S7kF8cFJvGVt3mWS59hl3kW7_k2841CXdp3MPwTPjvLX8XW2bzNLx99wQTL101?te=W3R5hFj4cm2zwW4mKLS-3ZWVWBW3K2-zv1JxwY5W1Lyz993XV0ZlF3XZ_8fmMlX1&si=8000000003411254&pi=38b2b9e3-f297-437f-ca5a-f199c708eeda>

www.linkedin.com/in/karlkmaier

2950 North Loop West, Suite 500, Houston, TX 77092

**Comment by ZornitsaSerbezova** [comment]
Hi kkmaier,

Could you please add the screenshot in a github comment, because you are answering to a question in git hub via email and I can't see the attachment.

**Comment by kkmaier** [comment]
![Screen Shot 2020-10-06 at 7 57 04 AM](https://user-images.githubusercontent.com/65906765/95209617-2fa65300-07b0-11eb-8955-ef64b6b121c1.png)

Here is a screenshot.

Thanks!

**Comment by ZornitsaSerbezova** [comment]
You need to reduce the radius of the circle here:
`  OrgChart.templates.myTemplate.img_0 = ... '<circle cx="100" cy="150" r="40"></circle>'...`

**Comment by kkmaier** [comment]
Currently, the chart does not have an imp_0 line of code.
When I add either of the following lines of code, the image size is reduced, but the image is a rectangle.
OrgChart.templates.growsTemplate.img_0 = '<image preserveAspectRatio="xMidYMid slice" xlink:href="{val}" x="10" y="0" width="40" height="40"></image>';
OrgChart.templates.growsTemplate.img_0 = '<clipPath id="ulaImg">' + '<circle cx="40" cy="40" r="20"></circle>' + '</clipPath>' + '<image preserveAspectRatio="xMidYMid slice" xlink:href="{val}" cx="40" cy="40" r="20"></image>';
Any suggestions on how to code this line to show a smaller, round image in the same location?

**Comment by kkmaier** [comment]
Here is sample data and code:
https://jsfiddle.net/kkmaier/91e7wzh8/26/#&togetherjs=f7BR4td2xu

**Comment by ZornitsaSerbezova** [comment]
I have edited the images for you: https://jsfiddle.net/BALKANGraph/wLbkth1f/

**Comment by kkmaier** [comment]
Perfect. Thanks you!
