### ISSUE TITLE
Add custom button in nodes

### ISSUE THREAD

**Issue by zabuzapr** [BALKANGraph/OrgChartJS#467]
Hi everyone, im new using balkangraph

i'd like to add a button inside node, but not every nodes, just a couple nodes only.
in a sample i've got from balkan demos. the button showed in every nodes. while i'm just need the button show for a couple nodes only. 

![image](https://user-images.githubusercontent.com/71513345/94777159-2e120f00-03ed-11eb-9ce1-a6db0d1cc476.png)
 
can you show me or explain to me how to get this done? or what method to define which node where button wil be shown?.

thanks, really appreciate

**Comment by ZornitsaSerbezova** [comment]
Hi zabuzapr,

You need to define another template only for the nodes that will have a button.
 OrgChart.templates.btnTemplate = Object.assign({}, OrgChart.templates.ana);
 OrgChart.templates.btnTemplate.field_0 =
Here is the documentation for Multiple templates in a chart: https://balkangraph.com/OrgChartJS/Docs/MultipleTemplates

**Comment by zabuzapr** [comment]
Hai Zornitsa, thanks for gave me some feedback 

i've tried to create new template but, the button show

![image](https://user-images.githubusercontent.com/71513345/94790366-5d7e4700-0400-11eb-8bc3-8d08eee76eb9.png)

this is my nodes, in the first id i gave tags : ["test"]

nodes = [
        { id: 1, "Employee Name": "Denny Curtis", Title: "CEO", Photo: "https://cdn.balkan.app/shared/2.jpg", tags: ["test"] },
        { id: 2, pid: 1, "Employee Name": "Ashley Barnett", Title: "Sales Manager", Photo: "https://cdn.balkan.app/shared/3.jpg" },
        { id: 3, pid: 1, "Employee Name": "Caden Ellison", Title: "Dev Manager", Photo: "https://cdn.balkan.app/shared/4.jpg" },
        { id: 4, pid: 2, "Employee Name": "Elliot Patel", Title: "Sales", Photo: "https://cdn.balkan.app/shared/5.jpg" },
        { id: 5, pid: 2, "Employee Name": "Lynn Hussain", Title: "Sales", Photo: "https://cdn.balkan.app/shared/6.jpg" },
        { id: 6, pid: 3, "Employee Name": "Tanner May", Title: "Developer", Photo: "https://cdn.balkan.app/shared/7.jpg" },
        { id: 7, pid: 3, "Employee Name": "Fran Parsons", Title: "Developer", Photo: "https://cdn.balkan.app/shared/8.jpg" },
        { id: 8, pid: 3, "Employee Name": "Chudnovsky", Title: "Co Developer", Photo: "https://cdn.balkan.app/shared/8.jpg", tags: ['partner'] },
        { id: 9, pid: 1, "Employee Name": "Henry Stones", Title: "Assistant Developer", Photo: "https://cdn.balkan.app/shared/8.jpg", tags: ['assistant'] },
        {id: 11, pid: 7},
        {id: 12, stpid: 11, "Employee Name": "Denny Curtis", Title: "CEO", Photo: "https://cdn.balkan.app/shared/2.jpg" },
        {id: 13, stpid: 11, "Employee Name": "Denny Curtis", Title: "CEO", Photo: "https://cdn.balkan.app/shared/2.jpg" },
        {id: 14, stpid: 11, "Employee Name": "Denny Curtis", Title: "CEO", Photo: "https://cdn.balkan.app/shared/2.jpg" },
        {id: 15, stpid: 11, "Employee Name": "Denny Curtis", Title: "CEO", Photo: "https://cdn.balkan.app/shared/2.jpg" }
    ];

this is  where i called and define the tags

![image](https://user-images.githubusercontent.com/71513345/94790878-1ba1d080-0401-11eb-8e0b-9b333e9fa4ba.png)

and this is where i tried to create a button element based on my template "test" tags 

![image](https://user-images.githubusercontent.com/71513345/94790986-3f651680-0401-11eb-953e-6f850e1cecbe.png)

can you point me where did i wrong? thanks

**Comment by ZornitsaSerbezova** [comment]
zabuzapr,

Which of our demos you are using for the button creation?

**Comment by zabuzapr** [comment]
this one, 

https://balkangraph.com/OrgChartJS-Demos/ButtonInNodes

**Comment by ZornitsaSerbezova** [comment]
I have changed the demo: https://jsfiddle.net/BALKANGraph/fLzsnmjo/

**Comment by zabuzapr** [comment]
it worked !

in the first time i'm a little confused about define my tags. now it works.

thanks for your help
