### ISSUE TITLE
Function Shows Up In Edit Field

### ISSUE THREAD

**Issue by itachi3stax** [BALKANGraph/OrgChartJS#468]
When creating a clickable link in a node field, the function shows up when editing the node.

![editfield](https://user-images.githubusercontent.com/67665964/95000143-27ad9f80-0573-11eb-96c4-8c10aa923630.png)

**Comment by ZornitsaSerbezova** [comment]
Hi itachi3stax,
You could hide the field: https://jsfiddle.net/BALKANGraph/3h05kdo8/
or you can show the hyperlink: https://balkangraph.com/OrgChartJS-Demos/HyperlinkInDetails

**Comment by itachi3stax** [comment]
But how do you hide the field, if the field is a function.

`nodeBinding: {
        field_0: "name",
        field_1: function (sender, node) {
          var data = sender.get(node.id);
          var name = data["name"];
          var link = data["link"];
          return '<a class="btn btn-sm btn-primary" target="_blank" onclick="getJobDescriptionOption('+node.id+')">Options</a>'
        }
      },`

**Comment by ZornitsaSerbezova** [comment]
```
        chart.editUI.on('field', function(sender, args){
            if (String(args.name).includes('function')){
                		return false;
            }
	    });
```

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue as it is answered. Feel free to reopen it if needed.
