### ISSUE TITLE
Creating Custom Template (Size based predifend templates)

### ISSUE THREAD

**Issue by zabuzapr** [BALKANGraph/OrgChartJS#469]
Hi, 

i'd like to create a node with different size but using same template as another nodes. in this case i use predefined template "ula",
but when i'm trying to adjust a node with different size (based on demo on https://balkangraph.com/OrgChartJS-Demos/CustomNodeSize). it replace the ula style too from the nodes that has a different size 

![image](https://user-images.githubusercontent.com/71513345/95036256-8c8f0400-06f1-11eb-8ab9-bc3a230f4186.png)

![image](https://user-images.githubusercontent.com/71513345/95036407-0aeba600-06f2-11eb-9361-5f16e9be7cee.png)

i need to change or specify the size of one node using globalized template like "ula". could help me or explain to me? 

thanks

**Comment by ZornitsaSerbezova** [comment]
To create the same design as Ula, you need to have the ula node declaration:
`'<rect x="0" y="0" height="{h}" width="{w}" fill="#ffffff" stroke-width="1" stroke="#aeaeae"></rect><line x1="0" y1="0" x2="250" y2="0" stroke-width="2" stroke="#039BE5"></line>';`

**Comment by zabuzapr** [comment]
Hi,

it worked now, thanks zornitsa
