### ISSUE TITLE
Question about exporting ways

### ISSUE THREAD

**Issue by phelippe** [BALKANGraph/OrgChartJS#47]
Is there any way to export the file to a base64 or blob instead of a file itself for further use?

In my case, I want to build a print page and the chart needs to be shown in the middle with other data.

**Comment by BALKANGraph** [comment]
Yes 

```
        onExportEnd: function (sender, type, filename, content) {
              var myBlobForFurtherUse = new Blob([content]);
              alert(myBlobForFurtherUse);
              return false;
        },
        menu:{
        	svg: {text: "Export Blob For Further Use"}
        },
```

See https://jsfiddle.net/BALKANGraph/e9480psc/

**Comment by Sher-V** [comment]
Is there a way to export as svg (base64) and render it as an image on the same page?

**Comment by Sher-V** [comment]
After converting it to base64 it is not possible to render this. 
![image](https://user-images.githubusercontent.com/43819353/106308177-5c0b4100-6271-11eb-95eb-6199f5785266.png)
After converting to blob and creating an object url of it I get an error as well.
![image](https://user-images.githubusercontent.com/43819353/106308294-89f08580-6271-11eb-965b-40fa3a2f34b2.png)

**Comment by ZornitsaSerbezova** [comment]
Hi Sher,
Is this from our example or you can post your?

**Comment by Sher-V** [comment]
@ZornitsaSerbezova https://jsfiddle.net/pb31ad6s/ this is my example.
Clicking on export ppt I trigger exporting to svg first and trying to render this on  the page as an image before the export button and I get the error in the console and svg is broken as well.
Seems like foreign objects break svg export.

**Comment by ZornitsaSerbezova** [comment]
Could you please create an example without using frameworks?

**Comment by Sher-V** [comment]
@ZornitsaSerbezova  sure, here is it.
https://jsfiddle.net/pb31ad6s/
Plain and simple, trying to export to svg, encode  to base64, and render this image on the page, svg is broken.

**Comment by ZornitsaSerbezova** [comment]
Are you triyng to make export to PPT, because I still don't understand why are you doing this?

You can see in this demo that SVG export works with foreignobject: https://jsfiddle.net/jfsxkerd/

**Comment by Sher-V** [comment]
@ZornitsaSerbezova , then img tag  inside foreignobject does not work, the text in  the button does not make sense.  
I made   an example without further exporting to ppt.

**Comment by Sher-V** [comment]
@ZornitsaSerbezova also as you can see in my example the result svg file is broken.
![image](https://user-images.githubusercontent.com/43819353/106583731-76d20400-6556-11eb-94a9-6f5a5cd4286c.png)

**Comment by Sher-V** [comment]
@ZornitsaSerbezova I spent some time on research and found out the issue.
When you export an svg you use _innerHTML_ method to retrieve the svg content and that what gives an error with img tag.
It simple removes the closing slash for _img_ and that gives an error after creating a blob and saving this file.
I created a simple example (code is simplified but taken from your source code) which reproduces the error I get in your code and you can see that svg is broken.
https://jsfiddle.net/10Ljgrv7/2/
One of the possible solutions in this case would be to replace the innerHTML method you have to _new XMLSerializer().serializeToString(node)_ 
Also  I created another jsfiddle for you to let you fully understand the problem. 
You can see in alert the result of innerHTM without closing slash for _img tag_.
Tell me if you need some more description of a problem, thanks for reading.

**Comment by ZornitsaSerbezova** [comment]
Thank you for the detailed information.
We have added this issue in out list and will think about it.

**Comment by Sher-V** [comment]
@ZornitsaSerbezova also what I noticed is whether you return true or false from "exportend" event function nothing happens.
I am not  sure which behavior you expected but in pdf  Export on getting false value you cancel downloading of a file, here you don`t.
According to your docs it should cancel the operation.
![Docs](https://user-images.githubusercontent.com/43819353/106916477-4639c800-6718-11eb-85f0-c4c15bc83358.png)
Here is a jsfiddle.  https://jsfiddle.net/s5uob7y8/

**Comment by ZornitsaSerbezova** [comment]
We have fixed that.
