### ISSUE TITLE
Multiple layout in one view 

### ISSUE THREAD

**Issue by zabuzapr** [BALKANGraph/OrgChartJS#470]
hi, is it possible to have 2 different layouts in one view?

![image](https://user-images.githubusercontent.com/71513345/95040582-4b512100-06fe-11eb-9026-d572edaf2f55.png)

 in assistant node. i'd like to use a horizontal layout. while others use treeRightOffset layout

**Comment by ZornitsaSerbezova** [comment]
This can be achieved using [subtrees](https://balkangraph.com/OrgChartJS/Docs/SubTrees). 
Here is a simple example for subtrees with different layouts: https://jsfiddle.net/BALKANGraph/kesfgp5a/
and here is an visualization with invisible group, showing you how to "hide" the using of subtrees: https://jsfiddle.net/BALKANGraph/uezs2qg5/

**Comment by ZornitsaSerbezova** [comment]
I'll close the issue as it is answered.

**Comment by ZornitsaSerbezova** [comment]
https://github.com/BALKANGraph/OrgChartJS/releases/tag/7.6.12

**Comment by zabuzapr** [comment]
Thanks for your support

Pada tanggal Jum, 4 Des 2020 15:48, ZornitsaSerbezova <
notifications@github.com> menulis:
