### ISSUE TITLE
Chart redraw after save from edit form 

### ISSUE THREAD

**Issue by zabuzapr** [BALKANGraph/OrgChartJS#473]
Hi,

i'm using draggable edit form so the users can change the node's size. it can be big, small, or mid. because the name field of the graph sometimes could be very long or just really short. 

when i tried to save the data. it update only the value to the node (field). but the size of the node wasn't change automatically. is there a way i can do that? like redraw or refresh or recall the chart again after i clicked save?

this is my jsfiddle btw 
https://jsfiddle.net/zabuzapr/e6o2afch/24/  

i need to change the size of the nodes "Deputy Of Coordination, Regional Development and Urban Planning" into bigger to contain the value more properly.

thanks, really apreciate

**Comment by ZornitsaSerbezova** [comment]
Hi zabuzapr

In order to change the size of the node, you need to have already created [template ](https://balkangraph.com/OrgChartJS/Docs/CreatingCustomTemplate)with another size and change the current template with it on [update](https://balkangraph.com/OrgChartJS/Docs/APIReference#updateEvent).

**Comment by zabuzapr** [comment]
yes i did. 

in my jsfiddle. i'v created the template when the tags changes into "big","small",  or "mid".  

can i reload the chart to retrieve new tag (from small changes to big) from database after i save?

**Comment by ZornitsaSerbezova** [comment]
You just need to change the tag no update. Something like this:
```
        var chart = new OrgChart(...);
        
        chart.on('update', function (sender, oldNode, newNode) {
            newNode.tags = ["big"]
            // return false; to cancel the operation
        });  

        chart.load(...);
```

**Comment by zabuzapr** [comment]
thanks, i'll look in to it
