### ISSUE TITLE
Two sublevel is coming on same level

### ISSUE THREAD

**Issue by Rohit07071985** [BALKANGraph/OrgChartJS#474]
Hi have created different sublevel like B1,B2,B3,B4,F1,F2,L1 but B3 and F1 is coming on same level.

attached screen

shot and code file.

Below is the code 

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sub levels - OrgChart JS | BALKANGraph</title>
    <style id="myStyles">
        html, body {
    margin: 0px;
    padding: 0px;
    width: 100%;
    height: 100%;
    font-family: Helvetica;
    overflow: hidden;
}

#tree {
    width: 100%;
    height: 100%;
}

    </style>

</head>
<body>
    <script src="https://balkangraph.com/js/latest/OrgChart.js"></script>

<div id="tree"></div>
    <script>
    

window.onload = function () {
    OrgChart.templates.noMenuTemplate = Object.assign({}, OrgChart.templates.luba);
 OrgChart.templates.noMenuTemplate.nodeMenuButton =  '';
 
    var chart = new OrgChart(document.getElementById("tree"), {
         template: 'base',
		 enableSearch: false,
		 scaleInitial:1,
		 mouseScrool: OrgChart.action.none,
		
		 
		menu: {
            svg: { text: "Export SVG" }
           
       },
	   showYScroll: OrgChart.scroll.visible,
         nodeBinding: {
             field_0:  function(sender, node){
                 return sender.get(node.id).tags[2];
             },
             field_1: function(sender, node){
                 return sender.get(node.id).tags[3];
				 },
         },
         tags: {
             "B1": {
                subLevels: 0,
             },
             "B2": {
             subLevels: 1,
             },
             "B3": {
             subLevels: 2,
             },
             "B4": {
             subLevels: 3,
             },
			  "F1": {
            subLevels: 4,
             },
             "F2": {
             subLevels: 5,
             },
             "L1": {
             subLevels: 6,
             },
             "no menu": {
                 template: "noMenuTemplate"
             }
         },
         nodes: [
             { id: 1, tags: ["", "no menu", "2TRG"] },
			 { id: 2,pid: 1, tags: ["", "no menu", "2TCG", ""] },
			 { id: 3, pid: 2,tags: ["", "no menu", "2GCG*", ""] },
			 { id: 4, pid: 3,tags: ["", "no menu", "2TAG", ""] },
			 { id: 5, pid: 4,tags: ["", "no menu", "2ACI", ""] },
			 { id: 6, pid: 5,tags: ["B1", "no menu", "5BIS", "B1"] },
			 { id: 7, pid: 6,tags: ["partner","no menu", "9BIS", "B1"] },
			 { id: 8, pid: 6,tags: ["B2", "no menu", "5ISI", "B2"] },
			 { id: 9, pid: 6,tags: ["B2", "no menu", "5LHG*", "B2"] },
			 { id: 10, pid: 6,tags: ["B2", "no menu", "5SNG*", "B2"] },
			 { id: 11, pid: 8,tags: ["B3", "no menu", "5GNA*", "B3"] },
			 { id: 12, pid: 11,tags: ["B4", "no menu", "6COM*", "B4"] },
			 { id: 13, pid: 10,tags: ["B3", "no menu", "6COM*", "B3"] },
			 { id: 14, pid: 6,tags: ["F1", "no menu", "5BPI", "F1"] },
        	 { id: 15, pid: 14,tags: ["F2", "no menu", "6PAL", "F2"] },
     		 { id: 16, pid: 14,tags: ["L1", "no menu", "5LAG*", "L1"] }
			
			 
            
         ]
     });
 };
 
    </script>
</body>
</html>

**Comment by MuharremTopuz** [comment]
Hi,
I have the same problem.
Do you intend to fix this problem in the soon?.
Have a nice day.

**Comment by ZornitsaSerbezova** [comment]
Hi Rohit and Muharrem,

We understood your point, but this is the way sublevels works, You can compare the sublevel of siblings only.

**Comment by MuharremTopuz** [comment]
Hi,
Do you think there is a solution to this?
Have a nice day.
Best Regards

**Comment by ZornitsaSerbezova** [comment]
Hi Muharrem,

You could create an empty node above to increase the size of the level distance or on the same level where the other node that you compare with has a parent.

**Comment by ZornitsaSerbezova** [comment]
Hi Muharrem,
Did you resolve your issue?
