### ISSUE TITLE
Can we create the node structure in HTML?

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#475]
Hi Sir

I want to create node structure in HTML instead of SVG, is it possible?

For ex: https://balkangraph.com/OrgChartJS-Demos/CustomTemplateWhite

I want to create this structure using HTML and CSS, please provide a way for this.

**Comment by ZornitsaSerbezova** [comment]
Hi Pushpender,
We don't support node structure in HTML only, but you can have foreignobject in the nodes:
https://jsfiddle.net/BALKANGraph/6uapb1yz/
