### ISSUE TITLE
Can the height of nodes can be dynamic?

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#477]
Hi 

I want that cards should have dynamic heights, So is it possible?

**Comment by ZornitsaSerbezova** [comment]
Hi Pushpender,

The required functionality is not supported.

**Comment by pushpender98** [comment]
Is there any planning to do so?

**Comment by zabuzapr** [comment]
Hi pushpender98

do you mind node size? 

i have an issue about maintain the size of the node. in my case i have a short and a long name (field value). but i need the node to have a different size based on the value size (not all node becomes big with short value).

it solved by using several templates. like bigTemplate and smallTemplate. so the user when add a new node(or new organization) have to choose what size the node will have.

**Comment by pushpender98** [comment]
Okay, But I don't want to manage a lot of templates at my end.

Thanks for the suggestion here, @zabuzapr

**Comment by ZornitsaSerbezova** [comment]
We are not going to do it soon.

**Comment by ZornitsaSerbezova** [comment]
https://balkangraph.com/OrgChartJS-Demos/DynamicHeight
