### ISSUE TITLE
Top left should start from the top and left of div

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#478]
Hi 

I was going through orientation and tried TOP-LEFT.
![image](https://user-images.githubusercontent.com/36353150/96557938-9b241080-12d8-11eb-87ca-a2ecb03b7cd2.png)

In this, the chart is starting from center, but it should start from top and left side of the div.
Please suggest what I need to do?

**Comment by ZornitsaSerbezova** [comment]
You could use chart.fit();

    document.querySelector('#orientation').addEventListener('change', function(){
        chart.setOrientation(parseInt(this.value));
        chart.fit();

**Comment by pushpender98** [comment]
tried it, but not working.

Please see want can be done here.

**Comment by ZornitsaSerbezova** [comment]
What is not working?: 
https://jsfiddle.net/BALKANGraph/0tup5ero/

**Comment by pushpender98** [comment]
I will send you guys a mail regarding this with a video attached.

**Comment by ZornitsaSerbezova** [comment]
You could try using this option: align: OrgChart.ORIENTATION,

**Comment by ZornitsaPesheva** [comment]
I'll cloce this issue as it looks inactive. Feel free to reopen it if needed.
