### ISSUE TITLE
Expand collapse to level demo not working 

### ISSUE THREAD

**Issue by zabuzapr** [BALKANGraph/OrgChartJS#479]
Hi, 

when i tried the demo about expand collapse to level, it's not working. but in the console browser there some kind of error about indexof property 

![image](https://user-images.githubusercontent.com/71513345/96667872-155d9f00-1384-11eb-9412-059ad66a826d.png)

my browser is Google Chrome Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by ZornitsaSerbezova** [comment]
Hi zabuzapr,

This is known issue and we will try to fix it when we have the opportunity to do that.

**Comment by zabuzapr** [comment]
thanks zornitsa

**Comment by ZornitsaSerbezova** [comment]
We have fixed the demo: https://balkangraph.com/OrgChartJS-Demos/ExpanCollapseToLevel

**Comment by zabuzapr** [comment]
Thanks zornitsa, it really help

Pada tanggal Rab, 11 Nov 2020 20:43, ZornitsaSerbezova <
notifications@github.com> menulis:
