### ISSUE TITLE
Center not working?

### ISSUE THREAD

**Issue by wimpie3** [BALKANGraph/OrgChartJS#48]
I'm using:
onExpCollClick: function (sender, action, id) {chart.center(id);}

but the chart does not move when a node is clicked... it stays where it is and doesn't center.

**Comment by BALKANGraph** [comment]
Use onExpCollClick: function (sender, action, id) {chart.center(id); **return false;**}

See https://balkangraph.com/OrgChartJS/Demos/15kNodesCustomExpandCollapse

**Comment by wimpie3** [comment]
Groups are not opening when I add **return false**

**Comment by ZornitsaSerbezova** [comment]
Here is an example of how to center using onExpCollClick:
https://balkangraph.com/OrgChartJS-Demos/Center
