### ISSUE TITLE
Export Bug

### ISSUE THREAD

**Issue by Mrcl1450** [BALKANGraph/OrgChartJS#480]
Hey,
There's a problem with slinks when hiding nodes and trying to export the chart.

I was trying to hide the last node to hide that last part and print in 2 separate pages
![image](https://user-images.githubusercontent.com/8568899/96884447-6c916b80-1479-11eb-814e-39e96ffc9f4e.png)
![image](https://user-images.githubusercontent.com/8568899/96884629-9e0a3700-1479-11eb-8059-71b31e0e90ce.png)

But the slinks went off from they are originally. 
In the pdf preview or image export the slinks move down to the end when it should be way up.

![image](https://user-images.githubusercontent.com/8568899/96885521-939c6d00-147a-11eb-9296-f2e7eae457fc.png)

Works fine if nothing it's hidden.

**Comment by ZornitsaSerbezova** [comment]
Hi Marcelo,
Could you please create an jsfiddle example?

**Comment by Mrcl1450** [comment]
https://jsfiddle.net/ca5qt1Lw/

**Comment by ZornitsaSerbezova** [comment]
I have exported this image from your jsfiddle example. Could you show me where is the problem on it?
![OrgChart](https://user-images.githubusercontent.com/19305472/96997697-ec333f00-153a-11eb-8ab5-5f0c8c4062f3.png)

**Comment by Mrcl1450** [comment]
![image](https://user-images.githubusercontent.com/8568899/96998064-c69e3980-152a-11eb-96cd-04cb1e0c332c.png)
Hide the last one from the 2nd row.

**Comment by ZornitsaSerbezova** [comment]
Oh, you mean to collapse. May be this is the issue:
![image](https://user-images.githubusercontent.com/19305472/96998584-5ac4cc80-153c-11eb-9ac8-cd311b35f2a6.png)

**Comment by Mrcl1450** [comment]
The slinks are present in the charts but in the correct position in the top nodes.
![image](https://user-images.githubusercontent.com/8568899/96999221-bf782b00-152c-11eb-82db-98c08bef47e0.png)
Whatever in the export they move down.

**Comment by ZornitsaSerbezova** [comment]
Ya, that's right. Thank you for reporting this issue. We will try to fix it soon.

**Comment by Mrcl1450** [comment]
Np, Thanks.

**Comment by ZornitsaPesheva** [comment]
the issue has been addressed in the latest version (8.11.10)

you can clear your browser cache and test: 
https://code.balkan.app/result/slink-out-of-position-when-generating-the-pdf
https://jsfiddle.net/BALKANGraph/023nfsd8/

get the latest version from here: https://orgchartjs.balkan.app/
