### ISSUE TITLE
Is there a way to auto size nodes based on field content?

### ISSUE THREAD

**Issue by daekadog** [BALKANGraph/OrgChartJS#481]
For example I have an Org Chart which has 2 fields
Role Name and Assigned Users

The "Role name" e.g. "Plumber" fits without problem

But the "Assigned Users" field may have up to say 10 people listed
e.g. Mary Jones, Fred Nirk, Bob Vance and so and so on as I say it may have 10 or so

Is there a way to auto size the node to fit all this in as needed.

**Or alternatively** do you have an example using onmouseover and onmouseout on field to show a popup div to display the full contents next to the node

See pic
![balkan-graph-on-hover](https://user-images.githubusercontent.com/4590960/97100640-9c46aa80-16e9-11eb-95d0-2862207582bb.png)

Thanks in advance

Pat

**Comment by ZornitsaSerbezova** [comment]
Hi daekadog,
We don't support auto size nodes, but you could create such hover popup,
We have demos that can help you with that.
This demo is showing how to create such popup on node click:  https://balkangraph.com/OrgChartJS-Demos/CustomTemplateTooltip
This one is showing a popup on node hover: https://balkangraph.com/OrgChartJS-Demos/Tooltip
And this one is showing a tooltip on a field hover: https://balkangraph.com/OrgChartJS-Demos/TooltipOnField

**Comment by ZornitsaSerbezova** [comment]
we have creted this demo: https://balkangraph.com/OrgChartJS-Demos/DynamicHeight
