### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#482]
Hi 

I am getting a error and not able to find the root cause.
![image](https://user-images.githubusercontent.com/36353150/97144329-41b15b00-178a-11eb-8956-bccc7422e21f.png)

Code: 
![image](https://user-images.githubusercontent.com/36353150/97144347-4970ff80-178a-11eb-9af1-0c0ecbed4720.png)
![image](https://user-images.githubusercontent.com/36353150/97144370-52fa6780-178a-11eb-8d60-9d5190d739e1.png)

When I was trying to draw the chart, then this error is occuring.

**Comment by ZornitsaSerbezova** [comment]
Hi Pushpender,

Could you please isolate the issue in jsfiddle example?
