### ISSUE TITLE
Update orgchart.d.ts

### ISSUE THREAD

**Issue by Draco62** [BALKANGraph/OrgChartJS#487]
Hello,
Not all features are accessible with Angular. The orgchart.d.ts file is not up to date.

In the documentation, the draw method accepts 3 parameters (action, param and callback) or in the d.ts only action is possible.

cordially

**Comment by ZornitsaSerbezova** [comment]
Yes, I am sorry,, that's right. We will try to update it soon.

**Comment by ZornitsaSerbezova** [comment]
Hi Draco62,

We have updated the .d.ts file. Please check if you still have any issues.

**Comment by Draco62** [comment]
Thanks for your feedback.
But you haven't modified the draw () method (line 1448).
A parameter is declared while the documentation indicates that there are 3 (https://balkangraph.com/OrgChartJS/Docs/APIReference#draw)

**Comment by ZornitsaSerbezova** [comment]
We have modified the draw method.

**Comment by Draco62** [comment]
Thanks
