### ISSUE TITLE
Adding parent to node with "partner" tag

### ISSUE THREAD

**Issue by vonklauz** [BALKANGraph/OrgChartJS#488]
Hello. I'm creating a family tree, but more complex than the example on your site. I faced a problem -  when i adding spouse(Jane) to one of ancestors (John), i cannot add parents to Jane. Because "pid" property of Jane's node has already taken the id value of John's node.

Could you tell, is there any way to solve the problem? Thank you!

![image](https://user-images.githubusercontent.com/33288376/99440387-911d1e00-2927-11eb-97f6-6dbbca505390.png)

**Comment by ZornitsaSerbezova** [comment]
Hi vonklauz,

OrgChart JS don't support such functionality. A node can have only one pid.

**Comment by gdemonie** [comment]
How about using ppid?

**Comment by ZornitsaSerbezova** [comment]
Hi gdemonie,

ppid is used for parent partner id. It says who is the partner of the father for example, i.e. mother.
In the above screenshot, you can say that Jane is a ppid for Michael and then Michael will become a child of both: John ad Jane.
Actually, you ca create such view, showing the parents of Jane, using subtrees, but it will became very complicated for a whole tree. You ca see how the "[First look](https://balkangraph.com/OrgChartJS/Demos/FirstLook)" demo is made. (expand above)

**Comment by matrunchyk** [comment]
@ZornitsaSerbezova would you please give an example of how it can be achieved using a subtree?

This is a very critical feature for our company and it's blocking us from moving forward with the library.
Thank you in advance!

@gdemonie @vonklauz have you guys solved it?

**Comment by ZornitsaSerbezova** [comment]
@matrunchyk could you please give us a screenshot of what exactly you want to achieve?

**Comment by vonklauz** [comment]
@matrunchyk 

Orgchart was great solution for creating family tree of single surname. But for more complex tree i had to use another library - https://github.com/BasicPrimitives (i hope, balkangraph  will not resent me for posting the link here :) ). This applies not only to the family tree, but also to any other diagram where the partner node may need parent nodes.

**Comment by ZornitsaSerbezova** [comment]
https://balkangraph.com/OrgChartJS-Demos/FamilyTree

**Comment by matrunchyk** [comment]
@vonklauz thank you for the reply, will take a look!

@ZornitsaSerbezova I'm afraid, that this setup won't work for us in this case?

![image](https://user-images.githubusercontent.com/2089828/106448313-44a7a000-648b-11eb-8d85-d2973ba30e14.png)

**Comment by ZornitsaSerbezova** [comment]
We can offer you the above link, but the exact picture is not possible.
