### ISSUE TITLE
Side window menu...

### ISSUE THREAD

**Issue by misakuna** [BALKANGraph/OrgChartJS#489]
Hello,

First, I wanna say that I love this library.
I have two questions that I need help with:

1. The side window menu that opens when clicking on a node. How can I disable that?
2. I have added buttons to my nodes, however, they do not work when on my iPhone. Any thoughts to why that might be?

Thanks,
James

**Comment by ZornitsaSerbezova** [comment]
Hi misakuna,

1. To disable the menu, you need to set this: nodeMouseClick: OrgChart.action.none
2. Are they working on other mobile devices?

**Comment by ZornitsaSerbezova** [comment]
I'll close the issue as it is inactive.
