### ISSUE TITLE
Is this ready to use and how to use this?

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#490]
Hi 

I was going through some of the new releases, and seen this

![image](https://user-images.githubusercontent.com/36353150/99756494-4cee7100-2b13-11eb-94ac-635eaada61a8.png)

Is it ready to use?

**Comment by ZornitsaSerbezova** [comment]
Yes,
 You need to set it to true before the declaration of the chart.

```
 OrgChart.FIXED_POSITION_ON_CLICK = true;
 var chart = new OrgChart(document.getElementById("orgchart"), {
 …
     });
```

**Comment by pushpender98** [comment]
thanks
