### ISSUE TITLE
In mozilla the scrolling is very slow

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#493]
In Mozilla browser, I was just trying to scroll the graph, and It was very slow. 

So Can I change the scrolling sensitivity for the mozilla browser only?

If yes, please let me know how?

**Comment by ZornitsaSerbezova** [comment]
Could you test here: https://balkangraph.com/OrgChartJS/Demos/Scrollbars

**Comment by pushpender98** [comment]
Hi @ZornitsaSerbezova 

This is working fine, but When I try the plugin with large no. of employee then there is slightly issue with the scrolling.

Can you provide me a link with huge no of employee?

**Comment by ZornitsaSerbezova** [comment]
I don't have such demo. Could you create an example in jsfiddle?

**Comment by pushpender98** [comment]
Just to know, is there any way to change the sensitivity of mouse device?

**Comment by ZornitsaSerbezova** [comment]
We have this for zoom only:
```
        var chart = new OrgChart(document.getElementById("tree"), {
            zoom: {
                speed: 130,
                smooth: 10
            },
            ...
        }); 
    
```

**Comment by ZornitsaSerbezova** [comment]
Did you resolve this isuue?
