### ISSUE TITLE
Can I make some field to "Select Options" and binding data from my database

### ISSUE THREAD

**Issue by oatyongyut** [BALKANGraph/OrgChartJS#494]
Hi

I need to binding data like a employees list to the field on add new chart page

for example as my attached

I need to change Employee Name field to "Select options" and binding data from my db or setup autocomplete to it

![image](https://user-images.githubusercontent.com/30170930/100583956-03293600-331e-11eb-93b1-7413558b2fff.png)

**Comment by ZornitsaSerbezova** [comment]
Hi oatyongyut,

If you'd like to put this select in the edit/detail filed, we have a demo for that: https://jsfiddle.net/BALKANGraph/z6gpdx7n/

**Comment by oatyongyut** [comment]
Hi Sir

Thank you so much

Digitally Yours,
Yongyut Pudwong
Software Development Manager
Manao Software
