### ISSUE TITLE
Export images to PDF

### ISSUE THREAD

**Issue by Aleksandr1705** [BALKANGraph/OrgChartJS#495]
Image does not export to pdf like in https://github.com/BALKANGraph/OrgChartJS/issues/456. Export-service works as example, but in our case we show images employees from special folder structure on portal. We want to use only our http-server for this function. Can this be done?

**Comment by ZornitsaSerbezova** [comment]
So, you have installed export service on your server and you still can't export images?
In this case you need to give access to the images of your export service.

**Comment by Aleksandr1705** [comment]
How i can properly give access to the images?01.12.2020, 19:52, "ZornitsaSerbezova" <notifications@github.com>:
So, you have installed export service on your server and you still can't export images?
In this case you need to give access to the images of your export service.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- С уважением,Александр Алмосов

**Comment by ZornitsaSerbezova** [comment]
You need to be able to browse the images from a browser of your OrgChart server.
You may need to ask your network administrators for help.

**Comment by Aleksandr1705** [comment]
Where i can find browser of my OrgChart server? In documentation https://github.com/BALKANGraph/export-service/blob/master/README.md i can't find it. 

Our configuration:
We have web-portal on apache server with images folder of employees:
/var/www/html/portal/assets/img/{id}/photo.png
I can access image from browser: https://portal-url/assets/img/{id}/photo.png
OrgChart configured to get images from this url. It normally shows it. But not export to pdf.

We installed OrgChart server on this server with access as http://portal-url:1337
Where we specify path to images on OrgChart server?

**Comment by ZornitsaSerbezova** [comment]
As I know the issue is fixed.
