### ISSUE TITLE
Example of using OrgChart JS in custom viz for Power BI

### ISSUE THREAD

**Issue by henryyyleung** [BALKANGraph/OrgChartJS#496]
Hi

Do you have any samples of using OrgChart JS type script library to build custom visual for Power BI?  I look at the tutorial of building custom viz in Power BI and it uses visual studio, and d3.  Given your bundle contains a typescript library so I wonder if this is possible.

Thanks.

Henry

**Comment by ZornitsaSerbezova** [comment]
Hi henryyyleung,
We don't have any samples for Power BI, but It is plain javascript and as it has .d,ts declaration file, you can use it with TypScrips.
it works on every browser that runs javascript.

**Comment by henryyyleung** [comment]
Thanks.  I develop my custom vis in VS code and the way I install the trial version is through npm.  If I purchase the professional version, should I simply download the js and ts file and overwrite them?  or there is a specific npm I can use to update my trial version to official one.

**Comment by henryyyleung** [comment]
The reason I ask is that the version between npm and the standalone is different.

**Comment by ZornitsaSerbezova** [comment]
After downlowding the licensed version, you will need to change the filie as follows:

Delete: **"undefined"!=typeof module&&(module.exports=OrgChart)** form **orgchart.js**
And add at end of the both files (**orgchart,js** and **orgchart.d.ts**): **export default OrgChart**

**Comment by henryyyleung** [comment]
will different version # cause an error?  The only I am using in vs code installed through NPM has a version of 7.6.25 while the latest version download will be 7.6.32

**Comment by ZornitsaSerbezova** [comment]
No, it shouldn't be a problem

**Comment by henryyyleung** [comment]
Hi.  is it possible to enable and use the export PDF feature in a custom viz within Power BI?  I can enable the menu for download but seems like it won't generate any  PDF.

**Comment by plamen-peshev** [comment]
Yes it is possible

Make sure the you have connection to https://balkangraph.com/export/index.html from Power BI

**Comment by henryyyleung** [comment]
Hi

In my Power BI visual.ts i have enabled the pdf export in the constructor.
```
 this.chart = new OrgChart(target, {
            enableSearch: false,
            menu: {pdf:{text: "Export PDF"}},
            nodeBinding: {field_0: "name"},
            template: "olivia",
            nodes: [],
            levelSeparation: 200,
            siblingSeparation: 300,
            subtreeSeparation: 300
```
I can see the menu in the power BI card but when I click on export it shows a flashing 3 dots but no PDF dialog is popped up.  Could you please advise if I've missed anything?

![Capture1](https://user-images.githubusercontent.com/75922447/105316527-f0cfc800-5bfb-11eb-9e20-c9b561e59227.PNG)

**Comment by plamen-peshev** [comment]
Do you have access to https://balkangraph.com/export/index.html  from Power BI server?

**Comment by henryyyleung** [comment]
Hi 
I am using your library to be included into a Power BI custom control.  This custom control will be then be used inside a Power BI dashboard desktop app and hence I am not sure if your code will work inside a desktop app.  Is there any workaround?

> OrgChart._downloadFile = function(t, e, r, i) {
    var a = new Blob([e],{
        type: t
    });
    if (1 == i) {
        var n = URL.createObjectURL(a);
        window.open(n, "_blank").focus()
    } else if (navigator.msSaveBlob)
        navigator.msSaveBlob(a, r);
    else {
        var o = document.createElement("a");
        if (void 0 !== o.download) {
            n = URL.createObjectURL(a);
            o.setAttribute("href", n),
            o.setAttribute("download", r),
            o.style.visibility = "hidden",
            document.body.appendChild(o),
            o.click(),
            document.body.removeChild(o)
        }
    }
}

**Comment by henryyyleung** [comment]
I look into the chrome developer tool -> network.  It is able to access the link and did send the data for the pdf generation.  I guess the library is unable to launch a new tab page from within Power BI web.  

https://community.powerbi.com/t5/Developer/Hyperlink-not-clickable-with-custom-visual/m-p/39446

Appreciate if there is any workaround.  Thanks.

**Comment by henryyyleung** [comment]
More update. It doesn't work in Chrome but seems working in IE 11

**Comment by ZornitsaSerbezova** [comment]
Is your project public?

**Comment by henryyyleung** [comment]
No.  Private project.

**Comment by henryyyleung** [comment]
Close.  Thanks.
