### ISSUE TITLE
how to redo if one node is deleted

### ISSUE THREAD

**Issue by howard730423** [BALKANGraph/OrgChartJS#497]
is there any function that can restore the deletion? or any suggestion? the confirm dialog is not enough to avoid.

**Comment by ZornitsaSerbezova** [comment]
Hi, you could save the deletion operations and undo them when needed, It's up to you how will do the logic. Actually the JS don't delete anything. OrgChart JS will do whatever you say.

**Comment by howard730423** [comment]
understood. thanks for your help.
