### ISSUE TITLE
is there a way to remove all clinks in typescript?

### ISSUE THREAD

**Issue by henryyyleung** [BALKANGraph/OrgChartJS#498]
Hi

As above.  is there is quick way / approach to remove all clinks?  Thanks.

**Comment by ZornitsaSerbezova** [comment]
chart.config.clinks = []; 
        chart.draw();

**Comment by henryyyleung** [comment]
Thanks.  I try but I can't find the config property defined in the orgchart.d.ts file.  I can only find addClink and removeClink..  Do I miss anything here?

**Comment by ZornitsaSerbezova** [comment]
I have added it to the latest version.

**Comment by henryyyleung** [comment]
Thanks.
