### ISSUE TITLE
Multiple parents

### ISSUE THREAD

**Issue by ghanjiboy** [BALKANGraph/OrgChartJS#5]
I am trying to use Balkangraph to create a family tree - I see the Royal family example, however I am looking to not have to hard code the connections (for marriage or multiple parents, etc). Is there an easier way to do this?

**Comment by BALKANGraph** [comment]
You can [groups ](https://balkangraph.com/OrgChartJS/Docs/Grouping)for families

**Comment by ghanjiboy** [comment]
Thank you, I thought of that too, but it didnt seem like a group can have children. So lets say we have group that has 2 people, Jack and Mary.  Can Jack and Mary have a set of children?  Like the attached picture?
<img width="1008" alt="sample" src="https://user-images.githubusercontent.com/1289510/50656710-167ccc80-0f62-11e9-80d4-74350126e040.png">

**Comment by BALKANGraph** [comment]
Here is a demo with groups: https://balkangraph.com/OrgChartJS/Demos/RoyalFamilyTreeGroups

**Comment by ghanjiboy** [comment]
Wow, thank you so much for putting this together, its a great representation of what I am looking to do and I could see others benefiting.    In the demo provided, its hard to see that Prince Harry came from Charles and DIana - looking at the diagram, its conceivable that either Harry or Meghan came from Charles and DIana.  Is there a way to draw a connection from Charles/Diana directly to Harry while still maintaining them as a family where they will have offspring of their own?

**Comment by BALKANGraph** [comment]
you can play with linkAdjuster, template property

Example:
```
    OrgChart.templates.MyTemplate.linkAdjuster =
        {
            fromX: 65,
            fromY: 0,
            toX: 0,
            toY: 0
        };
```
