### ISSUE TITLE
Feature Request: Allow membership in multiple groups for a node

### ISSUE THREAD

**Issue by dyeaple** [BALKANGraph/OrgChartJS#50]
Hi, 

In our application we allow users to be members of multiple groups. For example, a user could be a member of a department group, a job function group, and a team group. 

It would be great to be able to display these multiple group memberships for a user visually in OrgChartJS. 

To accomplish this in OrgChartJS, I suggest that a user's node would be replicated in each group that the user is a member of.

**Comment by CoStiC** [comment]
Hello,

Is it possible to :
- create groups of groups? 
- create an "assistant" of a person into a group? ( tags: ["HRs", "assistant"] )

I tried in JSFiddle, but there is no result...

**Comment by BALKANGraph** [comment]
- create groups of groups?- not possible in the current version
- create an "assistant" of a person into a group? ( tags: ["HRs", "assistant"] ) - what will be the expected layout?

**Comment by CoStiC** [comment]
1) ok thank you. 
2) the expected layout would have been to have an assistant of a person who is in a group. For example, a HR director in the group HRs has an assistant. I thought the assistant had to have 2 tags "HRs" and "assistant" to be in the same group. 
I hope this is clear enough ;)

**Comment by BALKANGraph** [comment]
the current version does not have it

we have in our todo list orgchart in orgchart node, that will meet your requirement

**Comment by CoStiC** [comment]
Very well, thank you for your time.

**Comment by dyeaple** [comment]
Hello, 

Just checking in to see if this enhancement to allow users to be members of multiple groups will be added to OrgChartJS soon. 

It would be very helpful for us. 

Please let us know. 

Thank you!

**Comment by ZornitsaSerbezova** [comment]
Hi dyeaple,

You can create a logic, that adds additional users, which are copies of the real ones. 

You can use this demo as starting point:
https://balkangraph.com/OrgChartJS/Demos/NumberOfChildren

Regards,
Zornitsa
