### ISSUE TITLE
Update count also on removing the nodes while collapsing

### ISSUE THREAD

**Issue by pluthra004** [BALKANGraph/OrgChartJS#501]
In our case, we are showing children count also while collapsing the nodes but when we are removing any node then the count is not updating.

![image](https://user-images.githubusercontent.com/70584816/102873936-c60d1b00-4467-11eb-9e37-234bb0d2d671.png)

![image](https://user-images.githubusercontent.com/70584816/102873905-bab9ef80-4467-11eb-821f-100a1c0fdad3.png)

**Comment by ZornitsaSerbezova** [comment]
I don't remember, did you manage to resolve this issue?
