### ISSUE TITLE
Node as a container and relate child nodes to a specific parent node in the group

### ISSUE THREAD

**Issue by MuharremTopuz** [BALKANGraph/OrgChartJS#503]
Hi,
İs it possible to group nodes as a container? So the idea is that, you can have multiple people in the group, but any childs are directly related to the parent in the group node, so something like this:
The idea is, child nodes are directly relating to the individual in the parent node, which is in a group.
Thanks for your help
Best Regards.

![image](https://user-images.githubusercontent.com/58817833/103993865-47beb180-51a7-11eb-9153-dec90706d61f.png)

**Comment by ZornitsaSerbezova** [comment]
Hi Muharrem,
You can do something like this: https://jsfiddle.net/jre49t2n/1/

**Comment by SmileYzn** [comment]
@ZornitsaPesheva Did you can reupload this jsfiddle?

**Comment by SmileYzn** [comment]
Mano thanks 🙏

Nice plugin

Em sáb., 3 de mai. de 2025, 02:18, ZornitsaPesheva ***@***.***>
escreveu:
