### ISSUE TITLE
Need a feature

### ISSUE THREAD

**Issue by abdulrehmansiddiqui** [BALKANGraph/OrgChartJS#504]
<img width="675" alt="Screen Shot 2021-01-24 at 4 24 55 PM" src="https://user-images.githubusercontent.com/34935108/105630171-f37f2700-5e60-11eb-9a98-e98ce2eddf4b.png">
I want to display one more Field in the Deborah template example (Name on the Top Center),(Title on the Left Bottom), and (Number on the Right Bottom)

**Comment by ZornitsaSerbezova** [comment]
Hi Abdul,

I have created a demo for you: https://jsfiddle.net/4xy9a2ro/2/
