### ISSUE TITLE
How can I stack boxes automatically when there is more than 4  in a line

### ISSUE THREAD

**Issue by Sher-V** [BALKANGraph/OrgChartJS#505]
I want nodes to become looking like trees if their root has more than 4 children.
Is there a way to accomplish this?

**Comment by ZornitsaSerbezova** [comment]
So you have #1, but you'd like #2?
Are all these children of the root, because you can't have children in different branches.

**Comment by Sher-V** [comment]
@ZornitsaSerbezova yes, I have #1, but I want #2.
Is there some way to stack boxes to reduce the width if some node has for example more than 4 children?

**Comment by ZornitsaSerbezova** [comment]
Hi Sher,

May be there is solution to your problem, but we will have to charge you extra for it.
Please write us to support@balkangraph.com
