### ISSUE TITLE
Is there a way to dynamically change the levelSeparation and the dimension of boxes in Typescript in VS Code

### ISSUE THREAD

**Issue by henryyyleung** [BALKANGraph/OrgChartJS#506]
Hi 

I try to do:
 this.chart.config.levelSeparation = xxx;
 this.chart.draw();

Seems this doesn't pick up the changes.  Any hints?  

I would also want to provide end user the flexiblity change the size of boxes and font size in clink dynamically.  Is there also a way to do it?

Thanks

**Comment by plamen-peshev** [comment]
Can you try with

chart._layoutConfigs.base.levelSeparation = xxx;
chart.draw();

**Comment by henryyyleung** [comment]
Hi

Property _layoutConfigs does not exist on type Orgchart

**Comment by ZornitsaSerbezova** [comment]
I have added it to the latest version.

**Comment by henryyyleung** [comment]
Hi.  I try but seems it doesn't take the new parameter when drawing.

Should I be changing the base config or another config?

this is what I put under the Constructor of the custom viz power bi
this.chart = new OrgChart(target, {
            enableSearch: false,
            menu: {pdf:{text: "Export PDF"}},
            nodeBinding: {field_0: "name"},
            template: "olivia",
            nodes: [...],
            levelSeparation: 200,
            siblingSeparation: 200,
            subtreeSeparation: 100,
        })

This is what I put under the update event...
this.chart._layoutConfigs.base.levelSeparation = 1000;
this.chart.draw();

**Comment by ZornitsaSerbezova** [comment]
No, it works like a charm here: https://jsfiddle.net/denjsaxw/
It looks like the problem is in your project.

**Comment by henryyyleung** [comment]
Thanks it works after I restart my project.

Just wonder if there is a similar way to adjust the dimension of node and the font size of clink dynamically?  ie.  User can modify the parameters and use chart.draw() ?

**Comment by ZornitsaSerbezova** [comment]
For the node size, you can use different templates. Even you can create template dynamically.
Clinks also can be changed dynalically. 
It depends on what exactly do you need.

**Comment by henryyyleung** [comment]
Could you please advise the syntax for changing the font size of a clink
dynamically?  Simialr to what you have shown me on the levelseparation?

**Comment by ZornitsaSerbezova** [comment]
I have created a demo for you: https://jsfiddle.net/wd48se3b/11/

**Comment by henryyyleung** [comment]
Thanks.
