### ISSUE TITLE
Installed Licensed Version 

### ISSUE THREAD

**Issue by ikishanoza** [BALKANGraph/OrgChartJS#508]
We have purchased the balkan graph. I can access the console and downloaded Licensed OrgChart JS folder.

I am not sure how to use that in my code. I mean what are the changes that I need to done on code side. I have checked the doc but there is no specific document on that so can you please guide me with the detail steps here please ?

Thanks

**Comment by ZornitsaSerbezova** [comment]
If you are not using the NPM, you just need to replace the trial js file with the licensed one.
For NPM click [here](https://github.com/BALKANGraph/OrgChartJS/issues/496#issuecomment-755186863).

**Comment by ikishanoza** [comment]
I am getting "File '/Users/kishan/Desktop/getstarted/alexa-admin/src/assets/OrgChartJS/orgchart.d.ts' is not a module.ts" when I use it locally.

**Comment by ikishanoza** [comment]
![Screenshot 2021-01-27 at 11 46 58 PM](https://user-images.githubusercontent.com/18045135/106035292-f5174c00-60f9-11eb-8ec3-93e4c908e450.png)
I try to find but there is no such line.

**Comment by ZornitsaSerbezova** [comment]
You need to make these changes: 
Delete: "undefined"!=typeof module&&(module.exports=OrgChart) form orgchart.js
And add at end of the both files (orgchart,js and orgchart.d.ts): export default OrgChart;
