### ISSUE TITLE
How to export orgchart with font awesome icons?

### ISSUE THREAD

**Issue by harisriharan** [BALKANGraph/OrgChartJS#510]
I have used foreignobject to render our own HTML content in the chart with font awesome icon. In export, font awesome icons doesn't work. 

Is there way to solve this problem? Thanks!

**Comment by ZornitsaSerbezova** [comment]
You can see in his demo how to add font awesome icons to the exported content. : https://balkangraph.com/OrgChartJS-Demos/ExportStyles
