### ISSUE TITLE
Subtrees connected by child partners

### ISSUE THREAD

**Issue by Alexi5** [BALKANGraph/OrgChartJS#511]
Hello,

Is there a way to connect children of two different subtrees?

**Comment by ZornitsaSerbezova** [comment]
Hi Alexis!

Do you mean this?: https://jsfiddle.net/9d1nx8k0/1/

**Comment by Alexi5** [comment]
Hi! Yes, I'm looking for something like that. 

Can the curved line be customized? 
And is it possible to add a child node that belongs to both subtrees (ex one parent from each of those subtrees)?

Thanks!

**Comment by ZornitsaSerbezova** [comment]
The C link can be customized.
It is not possible to add child of both subrees as parents.
If you you trying to create family tree you could look at this approach: https://balkangraph.com/OrgChartJS-Demos/FamilyTree

**Comment by Alexi5** [comment]
Ok great!

Since there's no way to add children of different subtrees, I'm going to use the expand/collapse functionality to show different trees. Do you know if there is an example of that?

**Comment by ZornitsaSerbezova** [comment]
Could you show us with a screenshot what exactly do you mean?

**Comment by Alexi5** [comment]
Sure thing

If I have a tree that looks like this. Then when I click "Harvey Bishop" it will expand to a different tree
<img width="1019" alt="Screen Shot 2021-02-08 at 9 22 56 AM" src="https://user-images.githubusercontent.com/15223146/107240853-014fb300-69f0-11eb-8b19-7b90dad72698.png">

This will be the new tree that is expanded. Its hidden until we click on a descendent of that tree
<img width="627" alt="Screen Shot 2021-02-08 at 9 26 16 AM" src="https://user-images.githubusercontent.com/15223146/107240857-03b20d00-69f0-11eb-9004-f1bfa076ec2d.png">

**Comment by ZornitsaSerbezova** [comment]
Here is how you can add a button for loading the seciond chart: https://jsfiddle.net/BALKANGraph/oj4hdbL8/

**Comment by Alexi5** [comment]
Great, thank you!
