### ISSUE TITLE
Struggling to connect two nodes in a family tree example

### ISSUE THREAD

**Issue by courious-dev** [BALKANGraph/OrgChartJS#512]
Hi BalkanGraph team.

I am trying to your your library to create a family tree [similar to your example](https://balkangraph.com/OrgChartJS/Demos/RoyalFamilyTree)

Unfortunately I can't figure out how to connect two branches of the tree together. For example here is [what I currently have](https://jsfiddle.net/qkze219s/):
![t1](https://user-images.githubusercontent.com/78669417/107134264-4b784d80-68a5-11eb-8403-e300dac0b935.jpg)

In this example, I want to connect **node 4** and **node 7** and create a child of that connection and get something like this:
![img_1](https://user-images.githubusercontent.com/78669417/107134286-867a8100-68a5-11eb-81e5-68a82d40513b.jpg)

---------------
Is there any way for me to achieve this?

**Comment by ZornitsaSerbezova** [comment]
This is not supported by OrgChart JS.
You can see this approach instead: https://balkangraph.com/OrgChartJS-Demos/FamilyTree
