### ISSUE TITLE
Multiple nodes in single node.

### ISSUE THREAD

**Issue by Shubham994** [BALKANGraph/OrgChartJS#515]
I want to ask is there any features to add multiple nodes inside the single node. If it is there please provide the JS Fiddle link for that or code related to that.

**Comment by ZornitsaSerbezova** [comment]
subtrees: https://balkangraph.com/OrgChartJS/Docs/SubTrees
demo: https://jsfiddle.net/BALKANGraph/z025a6ny/

**Comment by Shubham994** [comment]
Thanks zornitsa.

One more thing I want to know is can we have scroll bar in search box?
If we have lots of records then while searching alphabets then scrollbar is not showing in search box.

**Comment by ZornitsaSerbezova** [comment]
You can define your own search result. Here is a demo: https://balkangraph.com/OrgChartJS-Demos/SearchResultInTable

**Comment by Shubham994** [comment]
Hi,
That above link I have checked and need some more clarification. My concern is, if we have thousands of records of same name then if we are going to search by starting alphabets of those name that time we need scrollbar in searchbar.

Please check below image for the reference.

https://user-images.githubusercontent.com/63347370/107494342-ae732880-6bb4-11eb-8588-879849b37553.png

**Comment by ZornitsaSerbezova** [comment]
You can have whatever you need in the search result.
You need to predefine **OrgChart.searchUI.createInputField** and **OrgChart.searchUI.createItem**

**Comment by Shubham994** [comment]
All above things i got it,
But how can I get the scrollbar if i have more records for search.

The concern is about the scrollbar, need scrollbar in search box.

**Comment by ZornitsaSerbezova** [comment]
May be something like here: https://stackoverflow.com/questions/2836827/how-do-you-add-a-scroll-bar-to-a-div
