### ISSUE TITLE
Create child nodes inside the parent node.

### ISSUE THREAD

**Issue by Shubham994** [BALKANGraph/OrgChartJS#517]
What my concern is  these 03, 04, 05 boxes dynamic like in the json add column which will have these grades valued as comma separated string, now if there are 3 comma separated grades in that column then 3 boxes will appear,  of 2 then 2 boxes.

Please let me know if any solutions is there for my concern.

Check below image for the reference.

https://user-images.githubusercontent.com/63347370/107489877-29394500-6baf-11eb-9f8b-9155440a248c.jpeg

**Comment by ZornitsaSerbezova** [comment]
You will need to define differrent tempplates for all the different count of childrens.
You can use max/min functionality depending of how you'd like these boxes to appear,
https://balkangraph.com/OrgChartJS/Docs/MinMax
