### ISSUE TITLE
Arabic Text alignment issue in export

### ISSUE THREAD

**Issue by nouchutm** [BALKANGraph/OrgChartJS#518]
Hi Team,

As communicated over the chat i have implimneted below code

**OrgChart.templates.dynamic.field_0 = '<g class="my-text" transform="translate(0, 0)">' +
      '<text width="230" text-overflow="multiline" style="font-size: 18px;" fill="#fff" x="125" y="95" text-anchor="middle">{val}</text>' + 
    '</g>';
and then set the translate of thet g
allNodeFields[j].setAttribute('transform','translate(0,' + (heightMinus - 30) + ')');**

While export the map, the aligmnet shown as earlier, the above slution not affect on the export.

Regards
Noushad

**Comment by ZornitsaSerbezova** [comment]
Could you please post an isolated jsfiddle with the issue?

**Comment by nouchutm** [comment]
Hi 

I found your grouping node sample middle aligned, Can you able to provide option to right and left aligned including text
 I have tried to add text in feild_0 and tried to set X and Y, but its OK. the export not working.

Please check Directors node.

Kindly provide alignment left, right ,middle  and custome instead redraw function option. Please check my sample from below link

https://jsfiddle.net/nouchutm/5azos186/43/

**Comment by ZornitsaSerbezova** [comment]
Could you please post screenshots of how is it now and how would you like it, because I can't understand the issue?

**Comment by nouchutm** [comment]
Hi @ZornitsaSerbezova 

![image](https://user-images.githubusercontent.com/45586881/107918800-c287a300-6f83-11eb-961c-0dcc31c8573e.png)

In above image you can see Directors highlated in right side of the group.

After export please see below image, its not showing the text. 

![image](https://user-images.githubusercontent.com/45586881/107918995-11353d00-6f84-11eb-96ad-0b1e78151750.png)

Sorry I could not upload my prodution data.

**Comment by ZornitsaSerbezova** [comment]
I have created a demo of what I think you are trying to achieve: https://jsfiddle.net/cg1hp7ja/1/
