### ISSUE TITLE
node in side node

### ISSUE THREAD

**Issue by shaileshkachhara** [BALKANGraph/OrgChartJS#519]
how to make one note inside another.

**Comment by ZornitsaSerbezova** [comment]
You need to use subtrees: https://balkangraph.com/OrgChartJS/Docs/SubTrees
https://jsfiddle.net/eu2c9gqv/3/

**Comment by shaileshkachhara** [comment]
Dear @ZornitsaSerbezova thanks for reply but my requirement is making box inside node, how can we achieve this. thanks

**Comment by ZornitsaSerbezova** [comment]
Could you please show us a screenshot of what you need?

**Comment by shaileshkachhara** [comment]
![image](https://user-images.githubusercontent.com/78866583/107645996-74cb1c00-6c9f-11eb-8b9e-31e219a89ecd.png)
this type of node i want

**Comment by ZornitsaSerbezova** [comment]
The easiest way to achieve this is to use different templates.
Also it depends on what exactly you'd like to happen when you click on these numbers and how you'd expect to looks the result like.
