### ISSUE TITLE
Help needed (Edit Mode) new element and connection line, new Field and spids

### ISSUE THREAD

**Issue by hdbrinkmann** [BALKANGraph/OrgChartJS#52]
[4PLANOrgChart.html.zip](https://github.com/BALKANGraph/OrgChartJS/files/2999516/4PLANOrgChart.html.zip)
I have some questions...

1. I am using the "spids" with a 2nd parent ID for "dottet line" connections, how can I hide it in the edit form?
2. When I add a new Element under the top element (Lüking), the connection line is not drawn as exptected, what can I do?
3. Is there a way to remove the "add new field" option in edit mode?

Help would be appreciated! :)

And... I tried to use char-data for id and pid, this did not work. Do these fields to be numbers or missed I something?

**Comment by BALKANGraph** [comment]
You can use custom edit form, see **Custom Edit Form** section from the  [Edit](https://balkangraph.com/OrgChartJS/Docs/Edit) help article, the built-in edit form is not customization 

The id an pids could be numbers or strings, what issue are you facing? If you thing that it is a bug can you please post your configuration code

**Comment by hdbrinkmann** [comment]
The OrgChart did not render. Most probably it was a data problem on my side - I will double check this and come back if necessary. 

Have you been able to reproduce the 2nd issue in my list?

Thank you!

**Comment by BALKANGraph** [comment]
I'm not able to replicate the second issue

Can you post a demo?

**Comment by hdbrinkmann** [comment]
Did you use the file attached to the initial post?

**Comment by BALKANGraph** [comment]
Now I see it 👍 and was able to replicate, thank you for reporting it

Will fix the issue in the next version, expected at the end of this week or in the beginning of the next

**Comment by BALKANGraph** [comment]
The second issue is fixed in the latest release 4.5.0

Test here https://balkangraph.com/js/exp/52.html
