### ISSUE TITLE
nodeBinding custome names

### ISSUE THREAD

**Issue by b00y0h** [BALKANGraph/OrgChartJS#520]
I have this data being passed to my chart
![image](https://user-images.githubusercontent.com/942414/107567541-cf874980-6bb3-11eb-9e67-90de4a8f47b4.png)

and it's showing up like this when clicking on a node:
![image](https://user-images.githubusercontent.com/942414/107567627-ecbc1800-6bb3-11eb-82f3-f22297e0284a.png)

I know it's gotta be something with the nodeBindings but can't for the life of me figure out how to show `name` as "Page Name", `field_2` as "sourceUrl", and not show "field_1" in the details at all (because it's actually being replicated as a tag)

This is what I have for nodeBindings:
`      nodeBinding: {
        field_0: "name",
        sourceUrl: "field_2",
      },`

url of referenced page: https://stleo-programs-sitemap.netlify.app/

**Comment by ZornitsaSerbezova** [comment]
You need to change **name** in the data to **"Page Name"**.
