### ISSUE TITLE
Offset Layout Bug

### ISSUE THREAD

**Issue by njstevensdev** [BALKANGraph/OrgChartJS#522]
When using left or right offset layout, extra unnecessary lines are generated and displayed. Attached is a screenshot.
![offsetLayoutBug](https://user-images.githubusercontent.com/77856023/107651722-d5ca0400-6c4d-11eb-96ab-277e32724e34.png)

Here is an example in JSFiddle: https://jsfiddle.net/njstevensdev/txckm39v/

**Comment by ZornitsaSerbezova** [comment]
Are you using the trial version, because it is limitet to 200 nodes?

**Comment by ZornitsaSerbezova** [comment]
You could try to decrease this value: OrgChart.MAX_DEPTH = 200; You need to use it before the chart declaration.

**Comment by njstevensdev** [comment]
Issue was the trial version. Thanks.
