### ISSUE TITLE
using both click and dbclick

### ISSUE THREAD

**Issue by PeterEFrancis** [BALKANGraph/OrgChartJS#523]
A double click event also fires two click events.

When using `nodeMouseDbClick: OrgChart.action.edit`, I would expect a single click on a node to open the view UI sidebar and a double click on a node to open the edit UI sidebar, but a double click registers a click event so opens up the view UI  before quickly closing it and opening the edit UI. There should be a way to kill the click event that is fired so the view UI doesn't open first.

**Comment by ZornitsaSerbezova** [comment]
I have created a demo for you:
https://jsfiddle.net/0aqmfrv2/5/
