### ISSUE TITLE
Cant find chart.editUI.on on angular 8

### ISSUE THREAD

**Issue by PatrickMkupa** [BALKANGraph/OrgChartJS#524]
Hi 
I`m working on angular and I need to customize the detail section of my org chart but a I cannot find this method "chart.editUI.on" more especially the editUI. Can someone please help me with a work around or a solution
<img width="572" alt="Screenshot 2021-02-17 at 10 21 08" src="https://user-images.githubusercontent.com/11071063/108175844-e674f100-7109-11eb-8340-f910eca8171d.png">

**Comment by ZornitsaSerbezova** [comment]
Hi Patrik,

I guess you are not using it the right way.
![image](https://user-images.githubusercontent.com/19305472/108186853-8a649980-7116-11eb-837f-c634410f49e6.png)

**Comment by PatrickMkupa** [comment]
Thanks Let me update

**Comment by PatrickMkupa** [comment]
I see the edit ui is inside can you  please show me an example to do this 
   chart.editUI.on('field', function(sender, args){
});


> Hi Patrik,
> 
> I guess you are not using it the right way.
> ![image](https://user-images.githubusercontent.com/19305472/108186853-8a649980-7116-11eb-837f-c634410f49e6.png)
> 
> Or if you have an old version, please update.

**Comment by ZornitsaSerbezova** [comment]
Could you please show me an example of how you'd like to use it?

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue as it looks inactive.
