### ISSUE TITLE
Mixing Partner and Assistant together deletes all childs

### ISSUE THREAD

**Issue by Jippy23** [BALKANGraph/OrgChartJS#525]
Hello there.

So I'm trying to make a custom partner group connected to the root node and it's working fine. But as soon as I add an assistant, everything down just disappears.

This issue is easly replicable with this code from the demos : 

`OrgChart.templates.partnerTemplate = Object.assign({}, OrgChart.templates.ana);
OrgChart.templates.partnerTemplate.size = [60,60];
var chart = new OrgChart(document.getElementById("tree"), {
    nodeBinding: {
        field_0: "name"
    },
    tags: {            
        partnerTemplate:{
            template: "partnerTemplate"
        }
    },
    nodes: [
        { id: 1 },
        { id: 2, pid: 1 },
        { id: 3, pid: 1 },
        { id: 4, pid: 1 },
        { id: 5, pid: 1, tags: ['partner', 'partnerTemplate']},					
        { id: 6, pid: 1, tags: ['partner', 'partnerTemplate']},
        { id: 7, pid: 1, tags: ['partner', 'partnerTemplate']},
        { id: 8, pid: 1, tags: ['partner', 'partnerTemplate']},
        { id: 9, pid: 1, tags: ['partner', 'partnerTemplate']},
        { id: 10, pid: 1, tags: ['partner', 'partnerTemplate']},
        { id: 11, pid: 1, tags: ['assistant']}
    ]
});`

Is there any way this could work?

**Comment by ZornitsaSerbezova** [comment]
Hi Jean,

We don't support node having parner and assistant at the same time.

**Comment by Jippy23** [comment]
Alright, I'll try to do it on my own. Thanks.
