### ISSUE TITLE
How i Can Remove Function text from SideMenu just need to show the name

### ISSUE THREAD

**Issue by arexiniti** [BALKANGraph/OrgChartJS#527]
![Capture](https://user-images.githubusercontent.com/79073817/108985798-e4330980-76aa-11eb-9032-d729ada62f19.PNG)

**Comment by ZornitsaSerbezova** [comment]
https://balkan.app/OrgChartJS-Demos/EditCustomField

**Comment by arexiniti** [comment]
im using React 
library "@balkangraph/orgchart.js": "^7.7.15", 
still the same not any change
![Captu1re](https://user-images.githubusercontent.com/79073817/109122121-91685900-7761-11eb-9918-bb4652800874.PNG)
![Capture](https://user-images.githubusercontent.com/79073817/109122125-92998600-7761-11eb-9473-266586c4fe11.PNG)


> https://balkan.app/OrgChartJS-Demos/EditCustomField

**Comment by ZornitsaSerbezova** [comment]
You can try using the debugger to find where the issue is.
