### ISSUE TITLE
How do I make description field text wrap?

### ISSUE THREAD

**Issue by wadelyman** [BALKANGraph/OrgChartJS#528]
How do I make it so long description text doesn't cut out of the frame?

**Comment by ZornitsaSerbezova** [comment]
Hi Wade,

Here id the documentation about text wrapping: https://balkan.app/OrgChartJS/Docs/TextOverflow

If this doc can't help you, please give us an jsfiddle example of the issue.

**Comment by wadelyman** [comment]
https://jsfiddle.net/#&togetherjs=cd8Sdo2EDu Here's an example. 2 problems: The description text obscures the title so I would like it if the description appeared only when the object is clicked, and the description of the text cuts off in the opened window. Thanks for the support

**Comment by ZornitsaSerbezova** [comment]
Could you try to post it again, as there is some problem with thw link?
