### ISSUE TITLE
Mouse scroll sensitivity 

### ISSUE THREAD

**Issue by mininglink** [BALKANGraph/OrgChartJS#53]
There seems to be to much sensitivity on mouse wheel, if you scroll just a little it changes a lot

is there a built in way to minimise the sensitivity ? maybe divide the zoom level ?

**Comment by mininglink** [comment]
I have managed to build a hack that turns on/off the scroll 

inside the function BALKANGraph.toolbarUI.prototype.init 

I have added the following code, you obviously will need to code it in in your own style, where i am using our own frame work to add the elements and buttons

on load, the mouse zoom is enabled, then each click of the mouse icon toggles the scroll functionality on/off, this is probably the best way to stop the crazy fast in out zooming, but allowing the functionality

a way to change the speed would be great as well longer term

![image](https://user-images.githubusercontent.com/3881064/54913749-2c85a200-4f3f-11e9-9853-1e31519962c0.png)

![image](https://user-images.githubusercontent.com/3881064/54913791-4de68e00-4f3f-11e9-95b2-000366699fd9.png)

![image](https://user-images.githubusercontent.com/3881064/54913967-aa49ad80-4f3f-11e9-87ec-4e8e7d5d18c4.png)

**Comment by BALKANGraph** [comment]
I'm happy to inform you that now you can control the zoom sensitivity 

```
        var chart = new OrgChart(document.getElementById("tree"), {
            zoom: {
                speed: 50,
                smooth: 10
            },
         ...
        });
```

You can test here https://balkangraph.com/js/exp/53.html

**Comment by mininglink** [comment]
Excellent, thanks

works well, ill check it out soon

**Comment by Abdulpgr** [comment]
Can you help me achieving this functionality, I want these buttons on my chart but dont know exactly how to do this
![image](https://user-images.githubusercontent.com/25702715/57688181-46e21f00-7656-11e9-9667-effd801d7403.png)

**Comment by mininglink** [comment]
I Hacked the chart itself, however, you could do this, easily using the built in API

Just add your own toolbox container adjacent to the chart, which ever side, add some icons/buttons with event listeners to the API functions that do functions

this chart has a great API that allows taking control of all of these items

**Comment by diallokolla** [comment]
Bonjour pouvons Utiliser ce DEMO  https://balkangraph.com/OrgChartJS/Demos/Tab/BasicUsage  de façon gratuite sans avoir ce message       The trial has expired or 200 nodes limit was reached!
See more
merci pour votre reponse

**Comment by ZornitsaSerbezova** [comment]
**diallokolla**, you need to buy licensed version of OrgChartJS.

**Comment by plamen-peshev** [comment]
@Abdulpgr, In the latest version you can override the following properties


```
    OrgChart.toolbarUI.expandAllIcon 
    OrgChart.toolbarUI.fitIcon 
    OrgChart.toolbarUI.zoomInIcon 
    OrgChart.toolbarUI.zoomOutIcon 
    OrgChart.toolbarUI.layoutIcon
    
```

See [this ](https://balkangraph.com/OrgChartJS-Demos/ToolbarIcons) demo
