### ISSUE TITLE
Limit of nodes?

### ISSUE THREAD

**Issue by vonklauz** [BALKANGraph/OrgChartJS#530]
Hello, i built a family tree with 200 nodes. But when I add more nodes to the existing 200, the tree stops showing on the site. But on the local server everything works correctly, there are no errors in the logs. So my question is, are there any limits for nodes in the family tree?
Thank you!

**Comment by ZornitsaSerbezova** [comment]
Hi vonklauz,

Are you using the trial version? 
Because the trial version is limited to up to 200 nodes.
