### ISSUE TITLE
I want to make a different parent node for department objects that does not include the same bindings as the children.

### ISSUE THREAD

**Issue by wadelyman** [BALKANGraph/OrgChartJS#531]
I want to make a chart that has department heads as parent objects without the bindings of their children. For example a a department head object "Human Resources" would have a number of people attached to it "Bob" and "Jane". When you clicked on Human Resources object it would contain "description" field that describes the department function, while when you clicked on Bob or Jane they would contain "Name" and "Title" and "Story" but not "description".

**Comment by ZornitsaSerbezova** [comment]
Hey Wade,

Could you please post a screenshots of how do you imagine the nodes structure of what you want?

**Comment by wadelyman** [comment]
![image](https://user-images.githubusercontent.com/20669280/109669831-82f2b680-7b40-11eb-8b1d-1004735429ed.png)

**Comment by wadelyman** [comment]
![image](https://user-images.githubusercontent.com/20669280/109670610-496e7b00-7b41-11eb-9f55-fff498b447ff.png)

**Comment by ZornitsaSerbezova** [comment]
So these grey rectangles will appear when you click on the node?

**Comment by wadelyman** [comment]
yes

**Comment by ZornitsaSerbezova** [comment]
And they both have to be visible at the same time?

**Comment by wadelyman** [comment]
No that was just to show what happens when you click on them.

**Comment by ZornitsaSerbezova** [comment]
So it looks like opening details form. You need details to have your UI?

**Comment by wadelyman** [comment]
Not really, I’m just poking for a way for parent nodes to have different
bindings than child nodes.

**Comment by ZornitsaSerbezova** [comment]
You can have differend templates and idifferend fields in these templates,

**Comment by wadelyman** [comment]
Great! Could you show me a simple example via js fiddle by any chance?

**Comment by ZornitsaSerbezova** [comment]
I have created a simple exampe for you: https://jsfiddle.net/31jt4e7x/5/

**Comment by wadelyman** [comment]
Thank you very much, but In this example, both of the nodes have the same fields, and the same bindings. I'm looking for one where there are different types of nodes with different types of bindings/fields. For example, as in the image I provided,  parent node could have "department" and "summary" while the child node could have "name" "title" and "description"

**Comment by ZornitsaSerbezova** [comment]
There are not the same. As you can see in the data, the parent have **department** and the child have **name**
        { id: 1, departnemt: "HR", tags: ["department"] },
        { id: 2, pid: 1, name: "Ashley Barnett" },
nodeBinding are common, but works different for both nodes.

**Comment by wadelyman** [comment]
But department label is present in the child modal window, despite the fact that it isn't contained in the data object. That's the problem I'm getting at that I'm trying to resolve. If a field object isn't relevant to the node, I don't want it to appear in the window that appears when I click the node. I understand that it needs to be there for "binding" purposes, but is there a way to disappear the field on the condition that it isn't in the data for a node.

**Comment by ZornitsaSerbezova** [comment]
Here is a demo on how to hide a field: https://jsfiddle.net/BALKANGraph/3h05kdo8/

**Comment by wadelyman** [comment]
I know about that, I checked your documentation. What I want to do is hide
a field on the condition of weather or not it has been filled in.... I
don’t want to hide it for all nodes... just the nodes that it isn’t
relevant to. Does that make sense?

**Comment by ZornitsaSerbezova** [comment]
That's what I am saying. You can do this
https://jsfiddle.net/w5josy1a/18/ - I am hiding "deparment" foeld for the employee in this example.

**Comment by ZornitsaPesheva** [comment]
I'll close this issue as it looks inactive. Feel free to reopen it if needed.
