### ISSUE TITLE
Trigger download PDF via desktop visualisation app such as Tableau

### ISSUE THREAD

**Issue by henryyyleung** [BALKANGraph/OrgChartJS#532]
Hi team

We are working on a project to test how we can integrate orgChartJS as a Tableau extension.   

It seems working so far as Tableau will point to orgchartjs library hosted on the webserver, with the only exception of PDF export.  

I did some debugging and realised this tableau extension is able to post the data to the exportPDF url and is able to receive the blob after the post.  However, because this is not a browser it wont' be able to launch window.open or download the blob object.  I manage to create the a href=blob:http://...... on the vis.  I can click on it but it prompts me to choose an application rather than launch the browser to download by default.   Note that if I create a href that points to a site (eg. google), Tableau is able to launch browser properly.

Could you please give me any hints on how I can use the exportPDF feature in this case?

Thanks.

**Comment by plamen-peshev** [comment]
If Tableau is not a browser what it is?

**Comment by henryyyleung** [comment]
This is a deskop app but they allow loading a webapp inside..  Similar
concept as an embedded iframe but not on browser but a desktop app

**Comment by plamen-peshev** [comment]
BALKAN OrgChartJS has very rich API, it can download the pdf in different ways

For example you can attach to "exportend" event and examine args

        chart.on('exportend', function (sender, args) {
            // your code goes here 
         });

**Comment by henryyyleung** [comment]
Close.
