### ISSUE TITLE
Upgrade leads to unwanted error

### ISSUE THREAD

**Issue by kksanghi** [BALKANGraph/OrgChartJS#534]
Using latest version 7.7.25 / 7.6.27 when we upgraded this then we apply several fixes, However i am getting strange issue which is

![image](https://user-images.githubusercontent.com/16228568/110525947-3a885980-813b-11eb-9dbe-68748b1c35ca.png)

I am not able to understand why it's causing this issue, After doing some research i tried to remove orphan records and it's working 

Any suggestion would be appreciated

**Comment by ZornitsaSerbezova** [comment]
Could you please post an isolated jsfiddle example with this issue?

**Comment by ZornitsaPesheva** [comment]
I'll close this issue as it looks inactive. Feel free to reopen it if needed.
