### ISSUE TITLE
How to translate field labels in edit form?

### ISSUE THREAD

**Issue by savilaj** [BALKANGraph/OrgChartJS#535]
How to translate field labels in edit form?

**Comment by ZornitsaSerbezova** [comment]
The field labels are actually the field in your data. So you see what you have in your data.

**Comment by savilaj** [comment]
> The field labels are actually the property names in your data. So you see what you have in your data and you can change the property names as you want

for example, the name of the field is "FullName" but in edit form, the label must show "Nombre completo" in Spanish.
In nodeBinding i have:
field_0: "FullName"
and show in edit form "FullName" how field label

**Comment by ZornitsaSerbezova** [comment]
You can just change the name of the field to  "Nombre completo" and also in nodeBinding:
field_0:  "Nombre completo" 

You could also use the "field" event and change the name there.
Read section "Change the Edit fields in the default Edit form" in the [Edit ](https://balkan.app/OrgChartJS/Docs/Edit)doc page

**Comment by ZornitsaSerbezova** [comment]
It's up to you how you will do it and depens on how you change these languages.

**Comment by ZornitsaPesheva** [comment]
I'll close this issue as it looks inactive. Feel free to reopen it if needed.
