### ISSUE TITLE
How to change length of node links

### ISSUE THREAD

**Issue by sreejitrozario** [BALKANGraph/OrgChartJS#537]
Hi

I need to change the length of the node links as they are overflowing into my template.
Here is a screen shot of the issue.
![image](https://user-images.githubusercontent.com/23395416/111685787-56cc7a80-884e-11eb-9d4e-93c8fcde665b.png)

Also, here is the fiddle
https://jsfiddle.net/sreejitrozario/5Lyh87qp/

**Comment by plamen-peshev** [comment]
Add

```
OrgChart.templates.topLvlTemplate.linkAdjuster = {
        fromX: 0,
        fromY: -20,
        toX: 0,
        toY: 0
};
```

See https://jsfiddle.net/b2qt7z91/

**Comment by sreejitrozario** [comment]
Thank You for the help

**Comment by sreejitrozario** [comment]
> Add
> 
> ```
> OrgChart.templates.topLvlTemplate.linkAdjuster = {
>         fromX: 0,
>         fromY: -20,
>         toX: 0,
>         toY: 0
> };
> ```
> 
> See https://jsfiddle.net/b2qt7z91/

@plamen-peshev Your suggestion is working well, but for mixed layout, I am facing a small issue. Please suggest.
![image](https://user-images.githubusercontent.com/23395416/111902091-9e772000-8a61-11eb-8795-43f502dde96a.png)

https://jsfiddle.net/sreejitrozario/4x6kvryo/

**Comment by ZornitsaSerbezova** [comment]
Hey Sreejit,

Your template was not made the right way. That's why you have the ptoblem with the link.
I have edited it for you and now you shouldn't have any issues:

https://jsfiddle.net/BALKANGraph/6qf1h8ko/6/

**Comment by sreejitrozario** [comment]
Thank you @ZornitsaSerbezova for the help. I am checking out your edit.

**Comment by ZornitsaPesheva** [comment]
I'll close this issue as it looks that it is resolved.
