### ISSUE TITLE
Mixed Layout help needed

### ISSUE THREAD

**Issue by sreejitrozario** [BALKANGraph/OrgChartJS#538]
Hi,

I need to make layout orientation like this
![image](https://user-images.githubusercontent.com/23395416/111962731-ae9e0680-8b18-11eb-81e0-2d61212452f0.png)

 I am unable to get the desired result with mixed layout. (If I remove the group nodes I get the proper layout , but I need to have the group nodes also). 
 
 Pretty sure, I am doing something wrong.

https://jsfiddle.net/sreejitrozario/yh4ospvn/

**Comment by sreejitrozario** [comment]
I need to make the first two rows (topLvlTemplate) horizontal & anything below it (midLvlTemplate) vertical.

**Comment by ZornitsaSerbezova** [comment]
Hi Sreejit,

Here we have a demo on how you can use different layouts in one chart:
https://balkan.app/OrgChartJS-Demos/LayoutsEvent

BTW we liked your template. Do you allow us to add it [here](https://github.com/plamen-peshev/orgchartjs-templates )?

**Comment by sreejitrozario** [comment]
@ZornitsaSerbezova Thank you for the suggestion. :smile: 
I will try to implement the example into my template. 

But  I did notice that in your example vertical stacking does not work even if one of the sibling nodes has a child.
My template however needs vertical stacking even if one of  sibling nodes has a child.

![image](https://user-images.githubusercontent.com/23395416/112057015-bee8cc80-8b7e-11eb-80ac-862370c05a76.png)


As for letting you add the template to the list, I will have to ask my clients about it. Will inform you.

**Comment by ZornitsaSerbezova** [comment]
> But I did notice that in your example vertical stacking does not work even if one of the sibling nodes has a child.
> My template however needs vertical stacking even if one of sibling nodes has a child.

That's right. This is the way the tree layout works.

**Comment by ZornitsaSerbezova** [comment]
Hey Sreejit, did you ask your clients about the template? :)

**Comment by sreejitrozario** [comment]
Hi @ZornitsaSerbezova . I had asked my client, they have not yet given me the permission
