### ISSUE TITLE
SVG export is breaking in edge

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#539]
Hi Guys 

I am using the 7.5.25 version of the library, and find out a bug after exporting the file as a SVG.

What is the bug? 

- I have tried to export a org chart in chrome 
- Then I tried to open that in edge, IE and mozilla and find out the images are breaking
- Its working fine in chrome.

Is this a bug of library, but not sure. Please do check the attached file.

**Comment by pushpender98** [comment]
Link to the export file: https://drive.google.com/file/d/1Z8uoRKmqL8OoKx6ErAqxrm-ZMwkJ86kY/view?usp=sharing

**Comment by ZornitsaSerbezova** [comment]
Hi Pushpender,

I have tried to reproduce your issue with this demo: https://balkan.app/OrgChartJS/Demos/Exporting
The images are there and look good, but thay are opening little but slower in the other browsers, than in chrome.

**Comment by ZornitsaSerbezova** [comment]
> Link to the export file: https://drive.google.com/file/d/1Z8uoRKmqL8OoKx6ErAqxrm-ZMwkJ86kY/view?usp=sharing

I can't see images in your file in any browser.
