### ISSUE TITLE
Z-index issue

### ISSUE THREAD

**Issue by YWJ1999** [BALKANGraph/OrgChartJS#540]
Hi guys,

I am trying to hide the three custom buttons that I created on my own behind the edit form. In my code, I have tried adding z-index to the .bgEditForm class with "z-index= 3" and  myExport id with "z-index = 1" based on the screenshot below.

![Screenshot (92)](https://user-images.githubusercontent.com/46043763/112272803-9adcd680-8cb7-11eb-8a28-cf4f2dd75f00.png)
![Screenshot (93)](https://user-images.githubusercontent.com/46043763/112272862-aa5c1f80-8cb7-11eb-816e-6c346d8fe6b6.png)

When I tried to preview my code, the three buttons that I created on my own still display in front of the edit form.

![Screenshot (91)](https://user-images.githubusercontent.com/46043763/112273124-f5763280-8cb7-11eb-948c-71911b607696.png)

Appreciate your help if you can guide me on how to solve it.

Thanks & Best Regards

P.S I have attached the sample code below 
https://jsfiddle.net/WJYEW/j3vdtoa5/11/

**Comment by ZornitsaSerbezova** [comment]
I am not shure if this is what you are trying to do, because I just have removed the z-index definitions and moved the button:
By default the details/edit is on top.
https://jsfiddle.net/86ncjsaw/

**Comment by ZornitsaPesheva** [comment]
I'll close this issue as it looks that it is resolved.
