### ISSUE TITLE
Sublevel Link line can't be customized

### ISSUE THREAD

**Issue by wadelyman** [BALKANGraph/OrgChartJS#542]
https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/SubLevels 
Here's one of yours. I want to make the sublevel links rounded and I want to make them thicker. How can I do this?

**Comment by ZornitsaSerbezova** [comment]
Hi Wade,

Now I know what is the solution :)
    OrgChart.templates.subLevel.link = '<path stroke-linejoin="round" stroke="#aeaeae" stroke-width="1px" fill="none" d="{rounded}" />';

https://jsfiddle.net/Lsmy7pu9/1/

**Comment by wadelyman** [comment]
https://jsfiddle.net/fg46c1dk/ Look at what happens when you try to change the thickness though...

**Comment by ZornitsaSerbezova** [comment]
That's because you need to change the link of the luba template also:
https://jsfiddle.net/3m5prsav/

**Comment by ZornitsaPesheva** [comment]
I'll close this issue as it looks that it is resolved.
