### ISSUE TITLE
Node Menu open/close hook

### ISSUE THREAD

**Issue by RichuJohn** [BALKANGraph/OrgChartJS#543]
Is there any way to know if a user clicked the node menu button to open the menu

![image](https://user-images.githubusercontent.com/14192990/112586966-d068f780-8e50-11eb-8d3d-3bb75f0cbdb8.png)

I would like to do some operations when user clicks on the node menu icon. How can we hook into that event?

Thanks

**Comment by ZornitsaSerbezova** [comment]
Hi Richu,

You could create your own event. You need to use our "redraw" event, and in it you will have to select the button ad attach an click event on it.

**Comment by RichuJohn** [comment]
Thanks @ZornitsaSerbezova, it worked perfectly. For those who are looking for something similar, this is what I did.

The template for the node menu is defined as 

```
OrgChart.templates.generic.nodeMenuButton =
      '<g style="cursor:pointer;pointer-events:bounding-box" transform="matrix(1,0,0,1,236,30)" control-node-menu-id="{id}" class="ellipses"><rect fill="#000000" fill-opacity="0" width="30" height="63" x="-13" y="-22"></rect><circle cx="0" cy="0" r="2" fill="#A0A8B5" class="menuButton"></circle><circle cx="0" cy="7" r="2" fill="#A0A8B5" class="menuButton"></circle><circle cx="0" cy="14" r="2" fill="#A0A8B5" class="menuButton"></circle></g>';
```
where I have inherited template from OrgChart.templates.rony


and in the redraw event handler for OrgChart instance,

```
let nodes = document.querySelectorAll("[control-node-menu-id]");
      for (let i = 0; i < nodes.length; i++) {
        let node = nodes[i];
        node.onclick = function(ev) {
          let parent = ev.target;
          while (!parent.hasAttribute("control-node-menu-id")) {
            parent = parent.parentNode;
          }
          let nodeId = parent.getAttribute("control-node-menu-id");
          
          // do what you need with the node id for which node menu was opened
         
        };
      }
```
