### ISSUE TITLE
Trial version question

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#544]
Hello team,

May i know what happens if we use the trial version for > 30 days?
https://balkan.app/OrgChartJS/Pricing

What would be the impact? We will not be able to load our charts? Is it possible to extend the trial? 

Thank you!

**Comment by ZornitsaSerbezova** [comment]
The chart will stop loading. We can extend your trial, but you need to write to support@balkan.app

**Comment by yingying96** [comment]
Noted thank!
