### ISSUE TITLE
Minimap issue

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#545]
When we try to use minimap by setting it to true, it will display this ReferenceError: drawnNodes is not defined error.
We are using React.
```

  componentDidMount() {
    this.chart = new OrgChart(this.divRef.current, {
      miniMap: true,
      enableSearch: false,
      collapse: {
        level: 2,
      },
      toolbar: {
        zoom: true,
      },
      template: 'ula',
      menu: {
        pdf: { text: 'Export PDF' },
        png: { text: 'Export PNG' },
        csv: { text: 'Export CSV' },
      },
      nodes: this.props.nodes,
      nodeBinding: {
        field_0: 'name',
        field_1: 'title',
        img_0: 'img',
      },
      slinks: this.props.slinks,
    });
  }
```

**Comment by ZornitsaSerbezova** [comment]
It is fixed in the latest version.

**Comment by yingying96** [comment]
I see. So may i know how do i get the fix? Thanks!

**Comment by ZornitsaSerbezova** [comment]
you will need to get the latest version. Are you using the trial or the licensed version?

**Comment by yingying96** [comment]
Im using the trial before deciding whether we should buy the licensed version

**Comment by yingying96** [comment]
Noted. If i'm no longer using the trial, how can i get the fix?

**Comment by ZornitsaSerbezova** [comment]
You will know this when you become a customer. :)
