### ISSUE TITLE
nodeContextMenuDetails queries

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#547]
Realized that there isn't much info on nodeContextMenuDetails
Can i confirm if the nodeContextMenuDetails refers to the menu that is displayed when we click on the nodes?
1. How can we add more fields in details without them displaying on the node?
2. Can we disable this details?

**Comment by ZornitsaSerbezova** [comment]
Where did you get this details from?
Do you mean nodeContextMenu?

**Comment by yingying96** [comment]
I mean the details pane that appears when we click on each node.

**Comment by ZornitsaSerbezova** [comment]
1. All the data in the node is apperaing in tyhe details by default.
2. You can use this option to disable deails:
```
    var chart = new OrgChart(document.getElementById("tree"), {
            nodeMouseClick: OrgChart.action.none,
            ...
    });
```

**Comment by yingying96** [comment]
Noted thanks!
