### ISSUE TITLE
Disable zoom

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#548]
Hi,

Is it possible to disable zoom? 
I tried zoom: null but it didn't work in react.

Thanks!

**Comment by ZornitsaSerbezova** [comment]
You could try with [mouseScrool: OrgChart.action.none](https://balkan.app/OrgChartJS/Docs/APIReference#mouseScrool)

**Comment by yingying96** [comment]
Works for me. Thanks!
