### ISSUE TITLE
Unable to change the size of the chart

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#549]
Hi Support,

I'm still looking through the UI changes and it seems like the size of the chart is always at 700px.

`<div id="tree" style="overflow: hidden;position: relative;height: 700px;">`

Is it possible for it to adjust and fit according to the nodes displayed? Or how can we change the size of the chart in react?

Thanks!

**Comment by ZornitsaSerbezova** [comment]
Please be sure that you have the div with the desired size before initializing the chart, To be sure of the size, you could remove the chart and check the size of the div changing its color.

**Comment by yingying96** [comment]
Managed to set style in react using style={{ height: '465px' }}

Thanks!
