### ISSUE TITLE
Question about layouts

### ISSUE THREAD

**Issue by vmgm87** [BALKANGraph/OrgChartJS#55]
Hello,

I recently downloaded orgchartJS for free to test it locally, I was trying to use the layout treeRightOffset but nothing happened... it seems only tree layout works.

![image](https://user-images.githubusercontent.com/36521421/54940377-3a600680-4ef0-11e9-8c8f-eebf0cd634d7.png)

Thanks in advance,
regards
VG

**Comment by BALKANGraph** [comment]
Can you test the following demo: https://jsfiddle.net/BALKANGraph/tw1s0hjm/?utm_source=website&utm_medium=embed&utm_campaign=tw1s0hjm

and let me know if it works for you

**Comment by vmgm87** [comment]
Hello,

I just use the the reference in the demo (<script src="
https://balkangraph.com/js/latest/OrgChart.js"></script>) instead of my
local reference to the js and it worked, is that mean that I downloaded the
wrong one and there is an updated version?

Thanks,
Regards,
Vannia

**Comment by BALKANGraph** [comment]
probably you have old version of the OrgChart JS

download the latest version and try again
