### ISSUE TITLE
Set zoom level

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#550]
Hi Team, 

May i know if it is possible to set zoom level for the nodes?

Thanks!

**Comment by ZornitsaSerbezova** [comment]
You can use chart.zoom(): https://balkan.app/OrgChartJS/Docs/APIReference#zoomM

**Comment by yingying96** [comment]
if scale is > 1 it will zoom in and scale < 1 zoom out.

Apologies, i realized that when i try e.g.  this.chart.zoom(-5, [20, 20]); it doesn't zoom out.
Zoom in works fine for me in react though.

**Comment by ZornitsaSerbezova** [comment]
try this.chart.zoom(0.5, [20, 20]);  :)
