### ISSUE TITLE
Format for response data

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#552]
Hi Support,

The left screenshot is the response rendered by our API and the one on the right is the sample response that works.

I would like to check whether the chart should still load based on the response returned on the left?
I'm thinking whether the comma highlighted on the right is required? 

![image](https://user-images.githubusercontent.com/19566726/114967702-84393200-9ea7-11eb-8037-d3850c25022c.png)

**Comment by ZornitsaSerbezova** [comment]
Hi,

You can remove these commas, as you don't need them, and check if it works.
