### ISSUE TITLE
OrgChart.toolbarUI.zoomInIcon

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#554]
May i check if the following still works in react?

    OrgChart.toolbarUI.expandAllIcon,
    OrgChart.toolbarUI.fitIcon,
    OrgChart.toolbarUI.zoomInIcon, 
    OrgChart.toolbarUI.zoomOutIcon,
    OrgChart.toolbarUI.layoutIcon,

Thanks!

Reference: https://github.com/BALKANGraph/OrgChartJS/issues/53

**Comment by ZornitsaSerbezova** [comment]
It looks like they are working.
![image](https://user-images.githubusercontent.com/19305472/115557096-09fb1a00-a2ba-11eb-9c25-168d68eee7c0.png)
![image](https://user-images.githubusercontent.com/19305472/115557142-18e1cc80-a2ba-11eb-9a6d-10413343dc79.png)

**Comment by yingying96** [comment]
expandAllIcon didn't work for me. I'm thinking whether it is possible under toolbar? 

![image](https://user-images.githubusercontent.com/19566726/115558765-a2f35a80-a2e5-11eb-8d98-2f29b30589a8.png)

**Comment by ZornitsaSerbezova** [comment]
Is it underlined?

**Comment by yingying96** [comment]
Nope not underlined.

**Comment by yingying96** [comment]
Managed to get this working by researching the past issues. Turns out we need as well. 

https://balkan.app/OrgChartJS-Demos/ToolbarIcons

            toolbar: {
                layout: true,
                zoom: true,
                fit: true,
                expandAll: true
            },

Thanks for the help!
