### ISSUE TITLE
Export org chart image not updated

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#555]
Hi team,

![image](https://user-images.githubusercontent.com/19566726/115571034-31b9a480-a2f1-11eb-80cd-b6ae8a0c1da0.png)

When we use  useEffect in react to update the org chart img, it works on the UI. However, seems like the org chart export isn't able to retrieve data from our img URL. Image from the repository will work but not our img URL.

**Comment by ZornitsaSerbezova** [comment]
To be able to export images with the defalt export service, they need to be public. 
The other option is to use your own [export service](https://github.com/BALKANGraph/export-service).

**Comment by yingying96** [comment]
Noted with thanks, will explore.
