### ISSUE TITLE
replaceAll function is causing issue

### ISSUE THREAD

**Issue by aliasghar113** [BALKANGraph/OrgChartJS#559]
orgchart.js is adding a replaceAll function to String.prototype, which is causing issues to my application. orgChart's replaceAll function doesnt handle special character and has very specific functionality.

Since string does have a more robust replaceAll, can you remove this function or use a different name?

![image](https://user-images.githubusercontent.com/83038284/115780071-5871ec80-a37e-11eb-9b29-655ac8fa6fe4.png)

**Comment by ZornitsaSerbezova** [comment]
Could you tell us where your replaceAll function come from? Could it be changed?

**Comment by aliasghar113** [comment]
Its the native JS string.replaceAll function that we are using. That works fine even if you have any regex reserved characters. OrgChart's implementation is failing gor regex reserved characters .

**Comment by ZornitsaSerbezova** [comment]
We have changed the code, so you will be able to use the native JS string.replaceAll function. Could you download the latest version and test it?

**Comment by aliasghar113** [comment]
We have tested the updated code and it is working fine. Thanks for fixing it quickly.
