### ISSUE TITLE
404 error on export 

### ISSUE THREAD

**Issue by rogeriocc** [BALKANGraph/OrgChartJS#56]
Is generating 404 error when exporting, in the Balkangraph page below is also generating the same error.

https://balkangraph.com/OrgChartJS/Docs/Exporting

**Comment by BALKANGraph** [comment]
thanks for reporting

now it works

**Comment by rogeriocc** [comment]
Testing here is still not working on:
https://balkangraph.com/OrgChartJS/Docs/Exporting
In the pages of Demo it works
https://balkangraph.com/OrgChartJS/Demos/Exporting
In my api test project it also does not export
http://aapthomologa.prodemge.gov.br/organograma/orgao/1500
All return 404 error.

**Comment by BALKANGraph** [comment]
Sorry it looks like there is a CORS issue

Will update you when is solved

**Comment by rogeriocc** [comment]
Thanx for your reply!

**Comment by BALKANGraph** [comment]
We have fixed the cors issue, now it works

**Comment by rogeriocc** [comment]
Vou could do a test on my development site, there I could not make it work.
On your website, I noticed that it was corrected!
http://aapthomologa.prodemge.gov.br/organograma/orgao/1500

Thank you!
