### ISSUE TITLE
How to achieve conditional rendering of nodes in Balkangraph?

### ISSUE THREAD

**Issue by vigneshnamachi** [BALKANGraph/OrgChartJS#560]
Like if I have admin node (top node) i want to display all the sub nodes, if am an sub node then should not show the admin node. Is it possible to achieve?

**Comment by ZornitsaSerbezova** [comment]
Most probably it is possible, but could you explain in steps and screenshots what are you trying to do?

**Comment by vigneshnamachi** [comment]
Explanation:
1. If I logged in as admin (Master Node) user, then I should be able to view all the nodes.
2. If I logged in as subnode (Partner Node) user, then I should be able to view only the related nodes and should not be able to view admin (Master Node)

**Comment by ZornitsaSerbezova** [comment]
You can load whatever you want. You can load "admin" data, or "user" data (nodes). It could be the backend part that will define what to send for "admin" or "user" data for the chart. Or you can copy the main data (nodes) in different array and modify them however you need.

**Comment by vigneshnamachi** [comment]
Yeah I got that, basically now I want to do CSS customization based on the node either its admin or user

**Comment by vigneshnamachi** [comment]
How to display none the drawer onclick of node and override my custom Drawer without editUI

**Comment by ZornitsaSerbezova** [comment]
> Yeah I got that, basically now I want to do CSS customization based on the node status.
> Example:
> 
> 1. If the user status is approved and that status as passed to user node, then I should be able to customize the node

It would be easier if you use different templates and change the template when you need.



> How to display none the drawer onclick of node and override my custom Drawer without editUI

You can use the click event: 
https://balkan.app/OrgChartJS-Demos/SingleAndDoubleClickOnNode.html

**Comment by vigneshnamachi** [comment]
Hi, is possible to get the selected node details on click of nodemenu button in the node?? Actually, i want to get the details of the particular node while click on the node menu icon

**Comment by vigneshnamachi** [comment]
How can i change the color of ula template top line stroke based status from backend, basically if the status is approved then i need to show green color on the node line  stroke if status is pending then  need to show orange color of the line. Is it possible ?

Thanks in advance

**Comment by ZornitsaSerbezova** [comment]
Yes, it is possible. You can define different templates, and use them based on a tag value.
Here is a demo of changed ula template: https://balkan.app/OrgChartJS-Demos/CustomTemplateDisco.html

Here is the original code of the ula template:
```
OrgChart.templates.ula.node = '<rect x="0" y="0" height="{h}" width="{w}" fill="#ffffff" stroke-width="1" stroke="#aeaeae"></rect><line x1="0" y1="0" x2="250" y2="0" stroke-width="2" stroke="#039BE5"></line>';
```

 stroke="#039BE5"

**Comment by vigneshnamachi** [comment]
Perfect Thanks!!!!

**Comment by ZornitsaPesheva** [comment]
Could you [isolate](https://code.balkan.app/orgchartjs/getting-started#JS) an example where it is not working?

**Comment by vigneshnamachi** [comment]
'<text class="title" style="font-size: 20px;" font-weight: 600;"  data-text-overflow="ellipsis"  fill="#1C1EC8" x="115" y="30" text-anchor="middle">{val}</text>';

am trying to do like this but not able to achieve that.. but in documentation without  **data-text-overflow="ellipsis"**  its happening

**Comment by ZornitsaPesheva** [comment]
You don't have **data-width**
https://balkan.app/OrgChartJS/Docs/TextOverflow

**Comment by vigneshnamachi** [comment]
If i add "data-width="220" property, am getting

"Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at Function.OrgChart.wrapText (orgchart.js?a042:1:204763)
    at Object.node (orgchart.js?a042:1:184435)
    at eval (orgchart.js?a042:1:6393)
    at eval (orgchart.js?a042:1:122239)
    at eval (orgchart.js?a042:1:123103)
    at Object.OrgChart.local._setPositions (orgchart.js?a042:1:100536)
    at OrgChart.server._read (orgchart.js?a042:1:122683)
    at eval (orgchart.js?a042:1:121961)
    at Object.OrgChart.state._get (orgchart.js?a042:1:250894)
    at OrgChart.server.read (orgchart.js?a042:1:121267)"

**Comment by ZornitsaPesheva** [comment]
Because you have some error in your code... see: 
this
style="font-size: 20px;" font-weight: 600;"
sould be
style="font-size: 20px; font-weight: 600;"

Use mine code
