### ISSUE TITLE
Open link in nodemenu

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#561]
Instead of details, is it possible to change it to open up a sample link e.g. www.facebook.com?

        nodeMenu: {
            details: { text: "Details" },
            edit: { text: "Edit" },
            add: { text: "Add" },
            remove: { text: "Remove" }
        },

Thanks!

**Comment by yingying96** [comment]
Apologies, is there a sample on how we can do windows.open for different nodes in react?
  
componentDidMount() {
    function profileHandler(nodeId) {
      window.open('https://google.com/', 'width=340px, height=670px, top=50px, left=50px'),
    };

    this.chart = new OrgChart(this.divRef.current, {
      enableSearch: true,
      // nodeMouseClick: OrgChart.action.none,
      mouseScrool: OrgChart.action.none,
      // miniMap: true,
      nodeMenu: {
        profile: {
          text: 'Profile',
          // onClick: window.open('https://google.com', 'width=340px, height=670px, top=50px, left=50px'),
        },
      },

**Comment by ZornitsaSerbezova** [comment]
We don't have Recat developers, but OrgChart.js should work in any js framework without issues.

**Comment by yingying96** [comment]
Is it possible to
