### ISSUE TITLE
Click on URL from details menu

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#562]
May i know if it's possible to click on the details in the details menu on the right to go to another URL?

Managed to do this for each node and referencing the api doc, but not sure how do we do it for the details menu
    this.chart.on('click', (sender, node) => {
      console.log('yes', sender);
      console.log('yes', node.id);
      window.open('www.google.com');
    });

![image](https://user-images.githubusercontent.com/19566726/116093379-2f808d00-a6d9-11eb-8ebe-c9af4b7c834d.png)

**Comment by yingying96** [comment]
Managed to get it partially working by following this example. https://balkan.app/OrgChartJS-Demos/HyperlinkInDetails.html

But for some reason when the text in the name field becomes undefined. How do i get the text back?


    this.chart.editUI.on('field', (sender, args) => {
      console.log('yes', sender);
      console.log('yes', args);
      if (args.type === 'details' && args.name === 'name') {
        const txt = args.field.querySelector('input');
        const txtVal = txt.value;
        console.log(txtVal);
        if (txt) {
          const node = this.chart.get(sender.node.id);
          const a = document.createElement('a');
          const linkText = document.createTextNode(node.page);
          a.appendChild(linkText);
          a.title = 'Click to go to CONNECT profile';
          a.href = 'https://google.com';
          a.target = '_blank';
          console.log(a);

          const parent = args.field.querySelector('div');
          const br = document.createElement('br');
          parent.appendChild(br);
          txt.remove();
        }
      }
    });

**Comment by yingying96** [comment]
I was able to create a button on the node by following the past demos. 

    OrgChart.templates.ula.node += '<g class="svg-btn"><rect  x="133" y="42" width="50" height="31" ></rect>'
    + '<text style="font-size: 9px;" x="183" y="62" text-anchor="middle">More information</text></g>';

Is there anything similar for the details menu after we click on the node?

**Comment by ZornitsaSerbezova** [comment]
> Managed to get it partially working by following this example. https://balkan.app/OrgChartJS-Demos/HyperlinkInDetails.html
> 
> But for some reason when the text in the name field becomes undefined. How do i get the text back? Thanks!
> 
> ```
> this.chart.editUI.on('field', (sender, args) => {
>   console.log('yes', sender);
>   console.log('yes', args);
>   if (args.type === 'details' && args.name === 'name') {
>     const txt = args.field.querySelector('input');
>     const txtVal = txt.value;
>     console.log(txtVal);
>     if (txt) {
>       const node = this.chart.get(sender.node.id);
>       const a = document.createElement('a');
>       const linkText = document.createTextNode(node.page);
>       a.appendChild(linkText);
>       a.title = 'Click to go to CONNECT profile';
>       a.href = 'https://google.com';
>       a.target = '_blank';
>       console.log(a);
> 
>       const parent = args.field.querySelector('div');
>       const br = document.createElement('br');
>       parent.appendChild(br);
>       txt.remove();
>     }
>   }
> });
> ```

Could you create an jsfiddle with your issue, explaining what do you expect and what is happening instead?




> I was able to create a button on the node by following the past demos.
> 
> ```
> OrgChart.templates.ula.node += '<g class="svg-btn"><rect  x="133" y="42" width="50" height="31" ></rect>'
> + '<text style="font-size: 9px;" x="183" y="62" text-anchor="middle">More information</text></g>';
> ```
> 
> Is there anything similar for the details menu after we click on the node?

Following the demo for the hyperlink, you can create a button the same way.

**Comment by yingying96** [comment]
Trying to set up the fiddle, but doesn't seem to be working - https://jsfiddle.net/mason_yy/ur6e7dbk/1/
I will continue to try.

In the meantime, the main thing we want to achieve is to be able to click on URL from the details menu.
Currently based on the sample, we can create a button and put the URL on the node by doing something like this.

OrgChart.templates.ula.node += '<g class="svg-btn"><rect  x="133" y="42" width="50" height="31" ></rect>'
+ '<text style="font-size: 9px;" x="183" y="62" text-anchor="middle">More information</text></g>';

I'm thinking if we can do it on the details menu instead? Would that be possible?
OrgChart.templates.ula**.details menu?**

**Comment by ZornitsaSerbezova** [comment]
We need a jsfiddle in plain JavaScript without frameworks.

About the button: As I wrote in the comment above, you could create a button the same way we create the hyperlink.
https://balkan.app/OrgChartJS-Demos/HyperlinkInDetails.html

Instead of this: var a = document.createElement('a'); 
you wil have this var btn = document.createElement("button");
and so on

**Comment by yingying96** [comment]
Thanks. Managed to get it working in react by referring to the demo.
I had a careless mistake with the undefined issue because i was referring to 'node.page' instead of 'node.id'. node.page is not defined in my case. 

Here's what works for me in react. 

```

    this.chart.editUI.on('field', (sender, args) => {
      if (args.type === 'details' && args.name === 'name') {
        const txt = args.field.querySelector('input');
        if (txt) {
          const node = this.chart.get(sender.node.id);
          const a = document.createElement('a');
          const linkText = document.createTextNode(node.name);
          const rootURL = '/people/';
          a.appendChild(linkText);
          a.title = 'Click to go to CONNECT profile';
          a.target = '_blank';
          a.href = rootURL.concat(node.id);
          // a.text = 'Test
          const parent = args.field.querySelector('div');
          const br = document.createElement('br');
          parent.appendChild(br);
          parent.appendChild(a);
          txt.remove();
        }
      }
    });
```

**Comment by ZornitsaPesheva** [comment]
**chart.editUI.on('field'.**. is deprecated now
Here is a hew example: https://code.balkan.app/org-chart-js/email-and-hyperlink-in-edit(details)#JS
