### ISSUE TITLE
Change the transparency level of the details menu

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#563]
Hi Team,

Wondering if it's possible to change the transparency level of the details menu? 

Right now if you view the details menu, u can see that it's partially transparent.

![image](https://user-images.githubusercontent.com/19566726/116225192-1ed92100-a784-11eb-83ce-73ad2a20e9d2.png)

Thanks!

**Comment by ZornitsaSerbezova** [comment]
Yes, you can:
.edit-wrapper {
  opacity: 1 !important;
}
