### ISSUE TITLE
If I set multiline for text, how to make them vertical middle?

### ISSUE THREAD

**Issue by liang-combase** [BALKANGraph/OrgChartJS#564]
I give every node text a y value to make text in vertical mid, but if the text has multiple line, other lines will fill the bottom of the first line. Can I set the text always vertical mid regardless how many lines of text?

**Comment by ZornitsaSerbezova** [comment]
You can see is this demo how to do this: https://balkan.app/OrgChartJS-Demos/DynamicHeight.html
