### ISSUE TITLE
nodes should be placed in a row but they are placed in column

### ISSUE THREAD

**Issue by San4ez-mc** [BALKANGraph/OrgChartJS#565]
http://prntscr.com/12e4av6
http://prntscr.com/12e4ibs

my data 
[{"id":"d_118","\u041d\u0430\u0437\u0432\u0430":"\u0412\u0456\u0434\u0434\u0456\u043b \u0440\u043e\u0431\u043e\u0442\u0438 \u0437 \u043a\u043b\u0456\u0454\u043d\u0442\u0430\u043c\u0438","pid":"94","tags":["node-with-subtrees"],"textWhenTheNodeIsMimized":"\u0412\u0456\u0434\u0434\u0456\u043b \u0440\u043e\u0431\u043e\u0442\u0438 \u0437 \u043a\u043b\u0456\u0454\u043d\u0442\u0430\u043c\u0438","textWhenTheNodeIsMaximized":"\u0412\u0456\u0434\u0434\u0456\u043b \u0440\u043e\u0431\u043e\u0442\u0438 \u0437 \u043a\u043b\u0456\u0454\u043d\u0442\u0430\u043c\u0438"},{"id":"d_97","\u041d\u0430\u0437\u0432\u0430":"\u041c\u0430\u0440\u043a\u0435\u0442\u0438\u043d\u0433","pid":"93","tags":["node-with-subtrees"],"textWhenTheNodeIsMimized":"\u041c\u0430\u0440\u043a\u0435\u0442\u0438\u043d\u0433","textWhenTheNodeIsMaximized":"\u041c\u0430\u0440\u043a\u0435\u0442\u0438\u043d\u0433"},{"id":"d_117","\u041d\u0430\u0437\u0432\u0430":"\u0412\u0456\u0434\u0434\u0456\u043b \u043f\u0440\u043e\u0434\u0430\u0436","pid":"93","tags":["node-with-subtrees"],"textWhenTheNodeIsMimized":"\u0412\u0456\u0434\u0434\u0456\u043b \u043f\u0440\u043e\u0434\u0430\u0436","textWhenTheNodeIsMaximized":"\u0412\u0456\u0434\u0434\u0456\u043b \u043f\u0440\u043e\u0434\u0430\u0436"},{"id":"d_119","\u041d\u0430\u0437\u0432\u0430":"\u0406\u0422 production","pid":"94","tags":["node-with-subtrees"],"textWhenTheNodeIsMimized":"\u0406\u0422 production","textWhenTheNodeIsMaximized":"\u0406\u0422 production"},{"id":"99","\u0406\u043c'\u044f":"\u041e\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440 \u041c\u0430\u0446\u0443\u043a","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0420\u041e\u041f","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","stpid":"d_117"},{"id":"100","\u0406\u043c'\u044f":"\u041e\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440 \u041c\u0430\u0446\u0443\u043a","\u041f\u043e\u0441\u0430\u0434\u0430":"\u043c\u0435\u043d\u0435\u0434\u0436\u0435\u0440 \u0437 \u043f\u0440\u043e\u0434\u0430\u0436\u0443","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"99"},{"id":"100_1","\u0406\u043c'\u044f":"\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0456 \u043f\u043e\u0448\u0443\u043a\u0443...","\u041f\u043e\u0441\u0430\u0434\u0430":"\u043c\u0435\u043d\u0435\u0434\u0436\u0435\u0440 \u0437 \u043f\u0440\u043e\u0434\u0430\u0436\u0443","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"99"},{"id":"100_2","\u0406\u043c'\u044f":"\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0456 \u043f\u043e\u0448\u0443\u043a\u0443...","\u041f\u043e\u0441\u0430\u0434\u0430":"\u043c\u0435\u043d\u0435\u0434\u0436\u0435\u0440 \u0437 \u043f\u0440\u043e\u0434\u0430\u0436\u0443","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"99"},{"id":"96","\u0406\u043c'\u044f":"\u042f\u0440\u0438\u043d\u0430 \u0421\u0432\u0456\u0434\u0440\u0430\u043a","\u041f\u043e\u0441\u0430\u0434\u0430":"SMM \u0441\u043f\u0435\u0446\u0456\u0430\u043b\u0456\u0441\u0442","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"95"},{"id":"91","\u0406\u043c'\u044f":"\u041e\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440 \u041c\u0430\u0446\u0443\u043a","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0412\u043b\u0430\u0441\u043d\u0438\u043a","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg"},{"id":"98","\u0406\u043c'\u044f":"\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0456 \u043f\u043e\u0448\u0443\u043a\u0443...","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0421\u043f\u0435\u0446\u0456\u0430\u043b\u0456\u0441\u0442 \u043f\u043e \u0432\u0456\u0434\u0435\u043e\u043f\u0440\u043e\u0434\u0430\u043a\u0448\u0438\u043d\u0443","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"95"},{"id":"101","\u0406\u043c'\u044f":"\u041e\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440 \u041c\u0430\u0446\u0443\u043a","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0421\u0442\u0430\u0440\u0448\u0438\u0439 \u043a\u043b\u0456\u0454\u043d\u0442 \u043c\u0435\u043d\u0435\u0434\u0436\u0435\u0440","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","stpid":"d_118"},{"id":"97","\u0406\u043c'\u044f":"\u0406\u0433\u043e\u0440 \u0424\u0443\u043d\u0434\u0438\u0433\u0430","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0422\u0440\u0430\u0444\u0456\u043a\u043e\u043b\u043e\u0433","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"95"},{"id":"95","\u0406\u043c'\u044f":"\u0406\u0433\u043e\u0440 \u0424\u0443\u043d\u0434\u0438\u0433\u0430","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0414\u0438\u0440\u0435\u043a\u0442\u043e\u0440 \u043f\u043e \u043c\u0430\u0440\u043a\u0435\u0442\u0438\u043d\u0433\u0443","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","stpid":"d_97"},{"id":"94","\u0406\u043c'\u044f":"\u041e\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440 \u041c\u0430\u0446\u0443\u043a","\u041f\u043e\u0441\u0430\u0434\u0430":"\u041e\u043f\u0435\u0440\u0430\u0446\u0456\u0439\u043d\u0438\u0439 \u0434\u0438\u0440\u0435\u043a\u0442\u043e\u0440","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"92"},{"id":"93","\u0406\u043c'\u044f":"\u041e\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440 \u041c\u0430\u0446\u0443\u043a","\u041f\u043e\u0441\u0430\u0434\u0430":"\u041a\u043e\u043c\u0435\u0440\u0446\u0456\u0439\u043d\u0438\u0439 \u0434\u0438\u0440\u0435\u043a\u0442\u043e\u0440","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"92"},{"id":"92","\u0406\u043c'\u044f":"\u041e\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440 \u041c\u0430\u0446\u0443\u043a","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0413\u0435\u043d\u0435\u0440\u0430\u043b\u044c\u043d\u0438\u0439 \u0434\u0438\u0440\u0435\u043a\u0442\u043e\u0440","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"91"},{"id":"102","\u0406\u043c'\u044f":"\u041e\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u0440 \u041c\u0430\u0446\u0443\u043a","\u041f\u043e\u0441\u0430\u0434\u0430":"\u041a\u043b\u0456\u0454\u043d\u0442 \u043c\u0435\u043d\u0435\u0434\u0436\u0435\u0440","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"101"},{"id":"103","\u0406\u043c'\u044f":"\u0410\u043d\u043d\u0430 \u0410\u043d\u043d\u0430","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0424\u0456\u043d\u0430\u043d\u0441\u0438\u0441\u0442","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"101"},{"id":"103_1","\u0406\u043c'\u044f":"\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0456 \u043f\u043e\u0448\u0443\u043a\u0443...","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0424\u0456\u043d\u0430\u043d\u0441\u0438\u0441\u0442","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"101"},{"id":"104","\u0406\u043c'\u044f":"\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0456 \u043f\u043e\u0448\u0443\u043a\u0443...","\u041f\u043e\u0441\u0430\u0434\u0430":"Team lead","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","stpid":"d_119"},{"id":"105","\u0406\u043c'\u044f":"\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0456 \u043f\u043e\u0448\u0443\u043a\u0443...","\u041f\u043e\u0441\u0430\u0434\u0430":"php \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u0456\u0441\u0442","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"104"},{"id":"105_1","\u0406\u043c'\u044f":"\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0456 \u043f\u043e\u0448\u0443\u043a\u0443...","\u041f\u043e\u0441\u0430\u0434\u0430":"php \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u0456\u0441\u0442","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"104"},{"id":"105_2","\u0406\u043c'\u044f":"\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0456 \u043f\u043e\u0448\u0443\u043a\u0443...","\u041f\u043e\u0441\u0430\u0434\u0430":"php \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u0456\u0441\u0442","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"104"},{"id":"106","\u0406\u043c'\u044f":"\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0456 \u043f\u043e\u0448\u0443\u043a\u0443...","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0412\u0435\u0440\u0441\u0442\u0430\u043b\u044c\u0449\u0438\u043a","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"104"},{"id":"106_1","\u0406\u043c'\u044f":"\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0456 \u043f\u043e\u0448\u0443\u043a\u0443...","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0412\u0435\u0440\u0441\u0442\u0430\u043b\u044c\u0449\u0438\u043a","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"104"},{"id":"107","\u0406\u043c'\u044f":"\u0410\u043b\u0438\u043d\u0430 \u041a\u043e\u043d\u043e\u043d\u0435\u043d\u043a\u043e","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0414\u0438\u0437\u0430\u0439\u043d\u0435\u0440","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"94"},{"id":"108","\u0406\u043c'\u044f":"\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0456 \u043f\u043e\u0448\u0443\u043a\u0443...","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0424\u0406\u043d\u0430\u043d\u0441\u043e\u0432\u0438\u0439 \u0434\u0438\u0440\u0435\u043a\u0442\u043e\u0440","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"92"},{"id":"109","\u0406\u043c'\u044f":"\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0456 \u043f\u043e\u0448\u0443\u043a\u0443...","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0411\u0443\u0445\u0433\u0430\u043b\u0442\u0435\u0440","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"92"},{"id":"110","\u0406\u043c'\u044f":"\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0456 \u043f\u043e\u0448\u0443\u043a\u0443...","\u041f\u043e\u0441\u0430\u0434\u0430":"\u042e\u0440\u0438\u0441\u0442","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"92"},{"id":"144","\u0406\u043c'\u044f":"\u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0456 \u043f\u043e\u0448\u0443\u043a\u0443...","\u041f\u043e\u0441\u0430\u0434\u0430":"\u0420\u0435\u043a\u0440\u0443\u0442\u0456\u0432,HR","img":"https:\/\/app.fineko.space\/\/icons\/fineko\/positions.svg","pid":"94"}]

my code

 OrgChart.templates.group.min = Object.assign({}, OrgChart.templates.group);
                OrgChart.templates.group.min.textFieldWhenTheNodeIsMimized = '<text width="230" style="font-size: 18px;" fill="#aeaeae" x="{cw}" y="60" text-anchor="middle">{val}</text>'

                OrgChart.templates.group.textFieldWhenTheNodeIsMaximized = '<text width="230" style="font-size: 18px;" fill="#039BE5" x="{cw}" y="35" text-anchor="middle">{val}</text>'
                OrgChart.templates.ana.link = '<path stroke-linejoin="round" stroke="#aeaeae" stroke-width="1px" fill="none" d="{edge}" />';

                ////

                let chart = new OrgChart(document.getElementById("org_chart"), {
                    template: "diva",
                    layout: OrgChart.mixed,
                    nodeMouseClick: OrgChart.action.none,
                    enableSearch: false,
                    nodeBinding: {
                        img_0: "img",
                        field_0: "Ім'я",
                        field_1: "Посада",
                        textFieldWhenTheNodeIsMimized: "textWhenTheNodeIsMimized",
                        textFieldWhenTheNodeIsMaximized: "textWhenTheNodeIsMaximized"
                    },
                    nodes: data,
                    // nodes: nodes_,
                    nodeMenu: {
                        edit: {text: "Редагувати"},
                        add: {text: "Додати"},
                        remove: {text: "Видалити"},
                    },
                    tags: {
                        "node-with-subtrees": {
                            template: "group"
                        }
                    }
                });

                chart.nodeMenuUI.on('show', function (sender, args) {
                    let node = chart.getNode(args.firstNodeId);
                    if (node.min && node.templateName == "group") {
                        args.menu = {
                            myMenuItemMax: {
                                text: "Розгорнути",
                                icon: OrgChart.icon.add(16, 16, "#ccc"),
                                onClick: function (id) {
                                    chart.maximize(id)
                                }
                            },
                            myMenuItemDummy: {
                                text: "Dummy menu option",
                                icon: OrgChart.icon.details(16, 16, "#ccc"),
                                onClick: function (id) {
                                    alert("you can add option to expand the nodes in a sub tree, print, remove, edit etc")
                                }
                            }
                        }
                    } else if (!node.min && node.templateName == "group") {
                        args.menu = {
                            myMenuItemMin: {
                                text: "Згорнути",
                                icon: OrgChart.icon.add(16, 16, "#ccc"),
                                onClick: function (id) {
                                    chart.minimize(id)
                                }
                            },
                            myMenuItemDummy: {
                                text: "Dummy menu option",
                                icon: OrgChart.icon.details(16, 16, "#ccc"),
                                onClick: function (id) {
                                    alert("you can add option to expand the nodes in a sub tree, print, remove, edit etc")
                                }
                            }
                        }
                    } else {
                        args.menu = {
                            instruction: {
                                text: "Посадова інструкція",
                                icon: position_instruction_icon,
                                onClick: function (id) {
                                    //todo зробити перевірку на позицію де кілька людей
                                    window.open('/instruction/job/' + id);
                                }
                            },
                            edit: {text: "Редагувати"},
                            add: {text: "Додати"},
                            remove: {text: "Видалити"},
                        }
                    }

**Comment by San4ez-mc** [comment]
is it because it is 4th level ? 
http://prntscr.com/12e4lre

**Comment by ZornitsaSerbezova** [comment]
That's because you have **layout: OrgChart.mixed**

**Comment by ZornitsaPesheva** [comment]
I'll close this issue as it looks that the question is answered.
