### ISSUE TITLE
SLinks cannot join sub trees and nodes

### ISSUE THREAD

**Issue by J-Nagle** [BALKANGraph/OrgChartJS#566]
The latest version of OrgChartJS fails to connect sub tress and nodes when using the second link component. This is similar to #179 and #227 in that it causes this error:

```
OrgChart.js:1 Uncaught TypeError: Cannot read property 'leftNeighbor' of null
    at e (OrgChart.js:1)
    at OrgChart._slinks (OrgChart.js:1)
    at Array.<anonymous> (OrgChart.js:1)
    at Object.publish (OrgChart.js:1)
    at OrgChart.js:1
    at OrgChart.js:1
    at OrgChart.js:1
    at Object.OrgChart.remote._proceed (OrgChart.js:1)
    at Object.OrgChart.remote._setPositions (OrgChart.js:1)
    at OrgChart.server._read (OrgChart.js:1)
```

Under the same conditions, curved links / CLinks do not have this issue. Additionally, SLinks can join similar item types without issue, meaning sub tress can use SLinks to connect to one another, as can nodes.

Examples
[CLinks working between sub tress and nodes](https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/FamilyTree)
[**SLinks breaking between sub tress and nodes**](https://jsfiddle.net/2vg7kfup/)
[SLinks working between sub tress](https://jsfiddle.net/2vg7kfup/1/)
[SLinks working between nodss](https://jsfiddle.net/2vg7kfup/2/)

**Comment by ZornitsaSerbezova** [comment]
Did this worked in the previous versions?

**Comment by J-Nagle** [comment]
Sorry, I don't know. I have not used previous versions of OrgChartJS.

**Comment by ZornitsaSerbezova** [comment]
Yes, I am asking, because you are talking about the latest version, but this is not supported in OrgChart JS.

**Comment by J-Nagle** [comment]
Whether it's a regression or not, shouldn't second links work like curved links? I want to have a link between items, but I would rather it use straight lines instead of curved ones. Judging by OrgChart JS' existing functionality, this lack of support doesn't seem intentional, or is otherwise unexpected and  undesirable. Another user also required straight links instead of curved ones in https://github.com/BALKANGraph/OrgChartJS/issues/227#issuecomment-538973693.

**Comment by ZornitsaSerbezova** [comment]
Here is how you can make the clinks straight: https://balkan.app/OrgChartJS-Demos/straightClinks.html
`OrgChart.CLINK_CURVE = 0;`

**Comment by J-Nagle** [comment]
Thank you very much! I see that option in the documentation now. It wasn't obvious to me reducing that value to zero would make the curve straight.  This is a suitable workaround. I appreciate your help!
