### ISSUE TITLE
Not Working when built the complete application with docker

### ISSUE THREAD

**Issue by jash281098** [BALKANGraph/OrgChartJS#568]
I am using this library to create a chart. It is working locally [https://jsfiddle.net/jash28/rkLz52df/6/](url) but when I build the application with docker it shows blank page. Request you to address the problem, if there is in my code.

**Comment by ZornitsaSerbezova** [comment]
Hi Jash,

As we discussed on email, it is because of the trial limit of the nodes. There is nothing specific for docker.
