### ISSUE TITLE
Render org chart container based on browser size

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#569]
Hi team,

Currently i have fixed the container to 700px but would like to know whether it is possible to render the chart based on browser size? Because we also have corporate ipads and it might be too rigid to fix it at 700px.

Thanks!

**Comment by ZornitsaSerbezova** [comment]
You can use CSS media to set the size or the tree div for the different devices. If this does not resolve the issue, please explain with screenshots how would you like the chart to look like.

**Comment by yingying96** [comment]
I see. Is there an example that we can reference to?
