### ISSUE TITLE
Issue using different exportUrl

### ISSUE THREAD

**Issue by vmgm87** [BALKANGraph/OrgChartJS#57]
Hi I am starting using balkangraph js locally and was trying to export to pdf and png using different exportUrl but I keep receiving error 405 or error 403, should I need to update exporturl in JS as well? or which are the correct steps?

Thanks,
VG

**Comment by BALKANGraph** [comment]
Did you deploy export server on your server?

**Comment by vmgm87** [comment]
No I didn't where can I get the export service?
Thanks!
VG

**Comment by BALKANGraph** [comment]
Now you should be able to export from localhost without changing exporturl

**Comment by vmgm87** [comment]
Hello,
But if I want to change exportUrl, will be necessary export service? how can I get it?

Thanks!
VG

**Comment by BALKANGraph** [comment]
You have to buy a license

From your BALKANGraph account you will be able to download the export service and install it on your server
