### ISSUE TITLE
TypeError: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#570]
When we first load the org chart, it will throw this error.
Upon subsequent load, it will not show this error anymore. The issue can be replicated whenever we clear the browser cache 

![image](https://user-images.githubusercontent.com/19566726/117741989-4e813200-b236-11eb-9675-17d331ec8732.png)

![image](https://user-images.githubusercontent.com/19566726/117742122-9902ae80-b236-11eb-8cc9-4c5a6b879127.png)

**Comment by yingying96** [comment]
Looks like it's due to the zoom at the end. Removing the zoom will solve the issue but i'm not sure if there is a better way to use zoom?

```
    this.chart = new OrgChart(this.divRef.current, {
      enableSearch: true,
      // nodeMouseClick: OrgChart.action.none,
      mouseScrool: OrgChart.action.none,
      // miniMap: true,
      collapse: {
        level: 3,
        allChildren: true,
      },
      toolbar: {
        layout: true,
        zoom: true,
        fit: true,
        expandAll: true,
      },
      template: 'ula',
      menu: {
        csv: { text: 'Export CSV' },
      },
      nodes: this.props.nodes,
      nodeBinding: {
        field_0: 'name',
        field_1: 'title',
        img_0: 'img',
      },
    });
    this.chart.zoom(0.8, [50, 10]);
```

**Comment by ZornitsaSerbezova** [comment]
I have tried, but couldn't reproduce your error. Could you please isolate the issue in an running jsfiddle or html file?
