### ISSUE TITLE
Partner Child

### ISSUE THREAD

**Issue by darkwind77** [BALKANGraph/OrgChartJS#571]
In the Royal Family example, is there a way to add a Partner only child?

https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/RoyalFamilyTree

**Comment by ZornitsaSerbezova** [comment]
We don't support children under partner.

**Comment by darkwind77** [comment]
Ah. Too bad.

Is there support in adding HTML to fields, such as title? I've tried but only <a> works and I'm having trouble customizing it (CSS).

Thank you!

**Comment by ZornitsaSerbezova** [comment]
Here is an example for title: https://balkan.app/OrgChartJS-Demos/TooltipOnField.html
How to add html you can read in "Node HTML fields" section in this doc page: https://balkan.app/OrgChartJS/Docs/Fields

**Comment by darkwind77** [comment]
Thank you very much.

Somehow, I missed this.

**Comment by darkwind77** [comment]
I'm trying this:
```
OrgChart.templates.ana.website = '<text style="font-size: 10px;" x="20" y="130" text-anchor="middle">{val}</text>';
```
```
nodeBinding: {
    website: "website",
},
```
Note: There are other fields.
```
chart.on('website', function(sender, args){
    var name = args.data["website"];
    var link = args.data["weblink"];
    args.value = '<a target="_blank" href="' + link + '">' + name +  '</a>';
});
```
```
chart.load([          
    { 
        website: 'Web',
        weblink: 'https://google.com',
    },
]);
```

But `{val}` only returns `Web`.
Also, I was trying to add fontawesome icons to `website` but the chart halts loading on where the fontawesome icon is.

**Comment by ZornitsaSerbezova** [comment]
"chart.on('website', function(sender, args){
"

You can not put "website" here. This should be the name of the event, i.e. "field" in this case.

**Comment by darkwind77** [comment]
I tried that but the value of every other field I have, such as name, title and even img became "Web"

**Comment by ZornitsaSerbezova** [comment]
Could you please create a jsfiddle example to show me your code?

**Comment by darkwind77** [comment]
Here you go. You can see that every field changed to "Web".
https://jsfiddle.net/fk2p4rqn/

I'm able to get the link function using `<foreignobject>` but I don't think that's the nest way to approach this.

What I'm trying to do is add a link under the title (perhaps add more later). Also, I'm wanting to use a fontawesome icon instead of the word "Web", but when I try to replace it, the graph stops loading where the fontawesome icon is.

**Comment by ZornitsaSerbezova** [comment]
I have edited your example: https://jsfiddle.net/bjcq2y67/1/
Here are the changes:
1) remove this from nodebinding, because otherwise you will have two fields one over another: 
` web: "website",`
2) add condition to work on only "title" fileld:
`    chart.on('field', function(sender, args){
    		if (args.name == "title") {
                var name = args.data["website"];
                var link = args.data["weblink"];
                args.value = '<a target="_blank" href="' + link + '">' + name +  '</a>';
        }

    });`

**Comment by darkwind77** [comment]
Ah. Thank you very much.

Will now figure out how to make fontawesome work instead of `'+ name +'`

**Comment by ZornitsaSerbezova** [comment]
https://balkan.app/OrgChartJS-Demos/FontAwsome.html
