### ISSUE TITLE
Add a custom button (or any element) and assign click event

### ISSUE THREAD

**Issue by x2gboye** [BALKANGraph/OrgChartJS#572]
Is there a way to add any arbitrary element (like a button) to a node template and add a click event handler to that button?  I see I can add custom menu items to handle this use case, but I'm wondering if i can add my own button instead.  If so is there any documentation for that, or examples?

**Comment by x2gboye** [comment]
Just as a follow up, I guess what i need to do is create a custom svg element within the node's <g> element, and then within the node's click callback function, just see if that custom element is the target that was clicked, then do stuff.  I guess what i'm looking for is a way to add additional markup to the node's <g> element.  Any help is appreciated.

**Comment by ZornitsaSerbezova** [comment]
Hi Greg,

Here we have a demo for a custom button: https://balkan.app/OrgChartJS-Demos/ButtonInNodes.html

**Comment by x2gboye** [comment]
Thanks!
