### ISSUE TITLE
Export to PDF or Image - Is there a way to incorporate custom css into the export?

### ISSUE THREAD

**Issue by daekadog** [BALKANGraph/OrgChartJS#573]
My orgchart uses some classes to color nodes within the orgchart however when it exports to pdf or image those colors are lost (see pic).
It seems it doesn't know anything about those classes when rendering for export.

Is there a way to incorporate custom css into the export?

See pic for better explanation
![image](https://user-images.githubusercontent.com/4590960/119314231-dd229400-bcb7-11eb-857a-4c316808ee2d.png)

**Comment by ZornitsaSerbezova** [comment]
Here we have a demo on how to export styles: https://balkan.app/OrgChartJS-Demos/ExportStyles.html

**Comment by daekadog** [comment]
Thank you for that, works perfectly
