### ISSUE TITLE
Issue with combination of special char ("$&") for Node Fields

### ISSUE THREAD

**Issue by pathakvipul71** [BALKANGraph/OrgChartJS#575]
Hi, 
I have 1 field for org chart node. If I edit this field and enter "$&", on node its gets rendered as "{val}amp;". I am applying css to this field as below:

```
OrgChart.templates.ula.field_0 = 
'<text width="230" text-overflow="ellipsis" style="font-size: 1.2rem; font-weight:bold;" fill="#333" x="10" y="25" text-anchor="left" `class="field_0">{val}</text>';`
```

I see the same issue with demo available on jsfiddle. There on entering  "$&", I see "{val}". 
https://jsfiddle.net/fmzces3d/87/

Seems to have some issue with JS special characters. Please let me know if any solution for this.

**Comment by ZornitsaSerbezova** [comment]
We have fixed this issue, Please download the latest version (7.9.07) or use Ctrl+F5 for jsfiddle.
