### ISSUE TITLE
control-node-menu-id Not show on group node

### ISSUE THREAD

**Issue by daekadog** [BALKANGraph/OrgChartJS#576]
For some reason the control node menu is not being show on group nodes.
I have tried everything and have looked through almost all of your demos to see what I am doing wrong but can't find the solution.

Is there some setting that would prevent the menu not showing on group nodes

**Comment by ZornitsaSerbezova** [comment]
You mean you'd like to have details on group click?

**Comment by daekadog** [comment]
See pic
![image](https://user-images.githubusercontent.com/4590960/119839571-9cd94500-bf47-11eb-8d60-db83cb114589.png)

**Comment by daekadog** [comment]
Menu is showing on other nodes but not the group nodes

**Comment by daekadog** [comment]
Don't worry I found the culprit in my code, for some reason I had set the nodeMenuButton = '' WHY I DON'T KNOW
Thanks Guys
