### ISSUE TITLE
Expand all children and collapse neighbors when clicked with OrgChart.VERSION="6.6.2"

### ISSUE THREAD

**Issue by MVSJES** [BALKANGraph/OrgChartJS#577]
Hi,
We are at 6.6.2 in production. 
Does OrgChart.JS 6.6.2 support expanding all children of clicked Node and collapsing neighbors?  Please advise how?  Thank you!

**Comment by plamen-peshev** [comment]
If you have expandCollapse method, the method was added in version 7.5.27

Here is a demo: https://balkan.app/OrgChartJS-Demos/CollapseNeighborsOnExpand.html
