### ISSUE TITLE
Question on filtering org chart based on values

### ISSUE THREAD

**Issue by yingying96** [BALKANGraph/OrgChartJS#578]
Hi team,

May i know we can filter the org chart to display based on values e.g. country?
If we filter based on country e.g. United States, it will display only nodes that have country as united states.

Thanks!

id | first name | last name | email | title | supervisor id | Tags | Business | Country | Region
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | Brian | Moynihan | brian.t.moynihan@bofa.com | Chairman &amp; Chief Executive Officer | 0 | C - Suite | &nbsp; | UNITED STATES | Global

**Comment by ZornitsaSerbezova** [comment]
You can do this in the backend and send to the frondend only the data that you need to load.

**Comment by yingying96** [comment]
Got it thanks!
