### ISSUE TITLE
Does not show the worker's name in the search engine

### ISSUE THREAD

**Issue by doarsal** [BALKANGraph/OrgChartJS#58]
Does not show the worker's name in the search engine

https://imgur.com/pIe1BJR

**Comment by hdbrinkmann** [comment]
Same Problem in my OrgChart, only the ID is shown, open attached HTML to check.
[4PLANOrganistion.html.zip](https://github.com/BALKANGraph/OrgChartJS/files/3038216/4PLANOrganistion.html.zip)

**Comment by BALKANGraph** [comment]
The issue is addressed in the latest version 4.5.0

Test here https://balkangraph.com/js/exp/58.html

**Comment by doarsal** [comment]
Access to XMLHttpRequest at 'https://us-n-c-balkangraph.azurewebsites.net/api/OrgChartJS' from origin 'http://app.ti.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Error while calling Web API

Cross-Origin Read Blocking (CORB) blocked cross-origin response https://us-n-c-balkangraph.azurewebsites.net/api/OrgChartJS with MIME type text/plain. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by doarsal** [comment]
Offline not found    :(

GET https://balkangraph.com/js/latest/OrgChart.js net::ERR_INTERNET_DISCONNECTED

**Comment by BALKANGraph** [comment]
The evaluation version does not work offline

Please download licensed version from the [CONSOLE](https://balkangraph.com/console/Login?returnUrl=%2Fconsole%2F)
