### ISSUE TITLE
Cannot customize modal section

### ISSUE THREAD

**Issue by SusmitaSaha12** [BALKANGraph/OrgChartJS#582]
I downloaded your this Js file from https://balkangraph.com/js/latest/OrgChart.js which satisfies our project need much. But to fully implement as per our requirement we need to Customize the modal section that opens up on clicking of each nodes. 

We need to turn of the tag and ppid section from showing it to users. But I am unable to do so and can't find the specific code portion which do so. 

Request your help urgently so that I can correctly implement my project requirement.

**Comment by ZornitsaPesheva** [comment]
For the modal windows you can use these both demos as starting point:
https://balkan.app/OrgChartJS-Demos/ShowIdOnNodeClick.html
https://balkan.app/OrgChartJS-Demos/PopupOnFieldClick.html#

Here is how to hide the tags:
https://balkan.app/OrgChartJS-Demos/HideFieldNamesAndTags.html
The same way you can hide the ppid

Feel free to ask for help, sending your jsfiddle, if you are still unable to do something by yourself.

**Comment by SusmitaSaha12** [comment]
I cannot hide ppid field plz help me

**Comment by ZornitsaPesheva** [comment]
I have created a demo for you: https://jsfiddle.net/5gwa7scp/1/

**Comment by SusmitaSaha12** [comment]
I write
chart.on('click', function(sender, node){
        alert('clicked node id: ' + node.id);
        });

but it showing result undefined

**Comment by SusmitaSaha12** [comment]
I write
chart.on('click', function(sender, node){
alert('clicked node id: ' + node.name);
});

but it showing result undefined plz  help me 
thank you for previous helping

**Comment by ZornitsaPesheva** [comment]
give me your jsfiddle

**Comment by SusmitaSaha12** [comment]
window.onload = function () {
    OrgChart.templates.family_template = Object.assign({}, OrgChart.templates.ana);
    OrgChart.templates.family_template.size = [86, 86];
    OrgChart.templates.family_template.plus = "";
    OrgChart.templates.family_template.minus = "";
    OrgChart.templates.family_template.rippleRadius = 40;
    OrgChart.templates.family_template.name = '<text style="font-size: 12px;" fill="#000000" x="43" y="100" text-anchor="middle">{val}</text>';
    OrgChart.templates.family_template.title = '<text style="font-size: 12px;" fill="#aeaeae" x="43" y="115" text-anchor="middle">{val}</text>';
   OrgChart.templates.family_template.img = '<clipPath id="{randId}"><circle cx="43" cy="43" r="38.5"></circle></clipPath></circle><image preserveAspectRatio="xMidYMid slice" clip-path="url(#{randId})" xlink:href="{val}" x="3" y="3"  width="80" height="80"></image>';
    OrgChart.templates.family_template.node = '<circle stroke-width="3" fill="none" stroke="#aeaeae" cx="43" cy="43" r="41.5"></circle>';
    OrgChart.templates.family_template.defs = '<g transform="matrix(0.05,0,0,0.05,-13,-15.5)" id="baby"><circle cx="260" cy="310" r="200" fill="#ffffff"></circle><path fill="#aeaeae" d="m468.64 268.32h-13.591c-18.432-89.348-95.612-157.432-189.139-161.798-.501-.185-1.015-.348-1.545-.482-18.363-4.622-31.188-22.595-31.188-43.707 0-17.828 14.468-32.333 32.252-32.333 12.573 0 22.802 10.258 22.802 22.866 0 8.284 6.716 15 15 15s15-6.716 15-15c0-29.15-23.687-52.866-52.802-52.866-34.326 0-62.252 27.962-62.252 62.333 0 17.876 5.828 34.443 15.769 47.432-80.698 15.127-144.725 78.25-161.291 158.555h-13.591c-24.103 0-43.712 19.596-43.712 43.683 0 24.086 19.609 43.682 43.712 43.682h14.692c20.935 89.871 101.582 157.018 197.596 157.018s176.66-67.148 197.596-157.018h14.692c24.103 0 43.712-19.596 43.712-43.682 0-24.087-19.609-43.683-43.712-43.683zm-265.054 55.257c-8.284-.024-14.981-6.758-14.958-15.043.007-2.337-.708-13.999-15.481-14.041-.026 0-.053 0-.08 0-14.697 0-15.475 11.62-15.481 13.953-.023 8.284-6.75 15.007-15.043 14.957-8.284-.024-14.98-6.759-14.957-15.043.038-13.322 5.349-25.101 14.955-33.166 8.223-6.904 19.065-10.702 30.543-10.702h.148c11.534.033 22.412 3.896 30.63 10.876 9.559 8.12 14.803 19.928 14.765 33.25-.023 8.27-6.735 14.957-14.999 14.957-.013.002-.027.002-.042.002zm52.766 129.374c-26.485 0-48.033-21.533-48.033-48.002 0-8.284 6.716-15 15-15s15 6.716 15 15c0 9.926 8.089 18.002 18.033 18.002s18.033-8.076 18.033-18.002c0-8.284 6.716-15 15-15s15 6.716 15 15c-.001 26.469-21.548 48.002-48.033 48.002zm113.765-129.374c-.015 0-.029 0-.044 0-8.284-.024-14.98-6.759-14.957-15.043.016-5.445-1.993-9.263-6.14-11.673-5.407-3.142-13.27-3.165-18.695-.053-4.161 2.387-6.191 6.193-6.207 11.638-.023 8.27-6.735 14.957-14.999 14.957-.015 0-.029 0-.043 0-8.284-.024-14.981-6.758-14.958-15.043.046-16.149 7.802-29.845 21.281-37.576 14.814-8.497 33.929-8.443 48.695.138 13.434 7.807 21.112 21.547 21.066 37.696-.023 8.271-6.735 14.959-14.999 14.959z"/> </g>';
    //OrgChart.templates.family_template_blue = Object.assign({}, OrgChart.templates.family_template);
    //OrgChart.templates.family_template_blue.node = '<circle stroke-width="3" fill="none" stroke="#039BE5" cx="43" cy="43" r="41.5"></circle>';

    var chart = new OrgChart(document.getElementById("tree"), {
        template: "family_template",
        enableSearch: false,
        siblingSeparation: 100,
        nodeBinding: {
            //field_0: 'id',
            name: "Name",
            title: "title",
            img: "img",
        },
        /*tags: {
            blue: {
                template: "family_template_blue"
            }
        },*/	
    });

    /*chart.on('render-link', function(sender, args){
        if (args.cnode.ppid != undefined){
            args.html += '<use xlink:href="#baby" x="'+ args.p.xa +'" y="'+ args.p.ya +'"/>';
        }
		
    });*/
	chart.on('click', function(sender, node){
        alert('clicked node id: ' + node.id );
        });
	

    chart.load([          
            { id: 1, tags: ["red"], Name: "King George", img: "img_avatar.png",info: "Planning and coordination of the overall Division’s work program and operation, <br/>including program management finance/budget management, <br/>human resources management, and general office administration"},
            { id: 2, pid: 1, tags: ["partner"], Name: "Queen Elizabeth", title: "The Queen Mother", img: "https://cdn.balkan.app/shared/f2.png" },
            { id: 3, pid: 1, tags: ["red"],  ppid: 2, Name: "Queen Elizabeth II", img: "https://cdn.balkan.app/shared/f5.png"},
            { id: 4, pid: 3, tags: ["left-partner"], Name: "Prince Philip", title: "Duke of Edinburgh", img: "https://cdn.balkan.app/shared/f3.png"},
            { id: 5, pid: 1, ppid: 2, Name: "Princess Margaret", img: "https://cdn.balkan.app/shared/f6.png"},
            { id: 6, pid: 3,tags: ["blue"], ppid: 4, Name: "Charles", title: "Prince of Wales", img: "https://cdn.balkan.app/shared/f8.png"},
            { id: 7, pid: 6, tags: ["partner"] , Name: "Diana", title: "Princess of Wales", img: "https://cdn.balkan.app/shared/f9.png"},
            { id: 8, pid: 6, tags: ["partner"], Name: "Camila", title: "Duchess of Cornwall", img: "https://cdn.balkan.app/shared/f7.png" },
            { id: 9, pid: 3, ppid: 4 , Name: "Anne", title: "Princess Royal", img: "https://cdn.balkan.app/shared/f10.png"},
            { id: 10, pid: 3, ppid: 4 , Name: "Prince Andrew", title: "Duke of York", img: "https://cdn.balkan.app/shared/f11.png"},
            { id: 11, pid: 3, ppid: 4, Name: "Prince Edward", title: "Earl of Wessex", img: "https://cdn.balkan.app/shared/f12.png"},
            { id: 12, pid: 6, ppid: 7, tags: ["blue"], Name: "Prince William", title: "Duch of Cambridge", img: "https://cdn.balkan.app/shared/f14.png"},
            { id: 13, pid: 6, ppid: 7, tags: ["blue"], Name: "Prince Harry", img: "https://cdn.balkan.app/shared/f15.png"},
            { id: 14, pid: 12, tags: ["left-partner"], Name: "Catherine", title: "Duchess of Cambridge", img: "https://cdn.balkan.app/shared/f13.png"},
            { id: 15, pid: 13, tags: ["right-partner"], Name: "Meghan Markle", img: "https://cdn.balkan.app/shared/f16.png"},
            { id: 16, pid: 12, ppid: 14, tags: ["blue"], Name: "Prince George of Cambridge", img: "https://cdn.balkan.app/shared/f17.png"},
            { id: 17, pid: 13, ppid: 15, tags: ["blue"], Name: "Prince Charlotte of Cambridge", img: "https://cdn.balkan.app/shared/f18.png"},
            //{ id: 18, pid: 12, ppid: 14, tags: ["blue"], name: "Prince Louis of Cambridge", img: "https://cdn.balkan.app/shared/f19.png"},
			//{ id: 19, pid: 12, ppid: 14, tags: ["blue"], name: "Princes loka", img: "https://www.w3schools.com/howto/img_avatar.png"}
        ]);
		
	 chart.editUI.on('field', function(sender, args){
            if (args.name == 'ppid'){
                		return false;
            }
	    });
	
};

**Comment by SusmitaSaha12** [comment]
i want to show node id & name in alert box but i cannot  solve is always show me undefined

**Comment by ZornitsaPesheva** [comment]
This code should be before chart.load(nodes)

```
 chart.editUI.on('field', function(sender, args){
        if (args.name == 'ppid'){
            		return false;
        }
    });
```

**Comment by SusmitaSaha12** [comment]
THANK YOU SO MUCH FOR ALL OF YOUR  HELP

**Comment by SusmitaSaha12** [comment]
Hi ,

While using the js and doing a bit of customization as per my project need and requirement, i am stuck in a situation where-in i need to show the details of each member of the tree in a separate page-- Upon clicking on each member the details against the same will be shown in an inner page. 

I can navigate to the inner page with the details. But the problem is, all the data is getting appended with url while url re-direction. Data includes, the id, name, biography etc. So the url is becoming abnormally lengthy and also the same is leading towards the chance of data tampering via interception.

I would earnestly request your kind help and intervention here so that i can proceed further and complete my project as per requirements.

Regards

**Comment by ZornitsaPesheva** [comment]
Could you give us an example of how you do that? You can write to support@balkan.app

**Comment by SusmitaSaha12** [comment]
[tree.zip](https://github.com/BALKANGraph/OrgChartJS/files/6775848/tree.zip)

**Comment by ZornitsaPesheva** [comment]
Here is how you can do it:

[tree.zip](https://github.com/BALKANGraph/OrgChartJS/files/6776410/tree.zip)

**Comment by SusmitaSaha12** [comment]
I want to show individual node details  (ex :name ,title,img) of the tree  in a separate page.i send all of data using url .But the problem is, all the data is getting appended with url while url re-direction. Data includes, the id, name, biography etc. So the url is becoming abnormally lengthy (ex: file:///G:/susmita/HTML/abc/New%20folder/tree/ss.html?King%20George%20img_avatar.png)and also the same is leading towards the chance of data tampering via interception.


tree.html node click event to go another page

    chart.on('click', function(sender, args){    
					var data = sender.get(args.node.id);
					//name send to another page
					var b=data.Name;
					var s=data.img;
					console.log(b);
					//const url = 'ss.html?' + encodeURIComponent(b) +' '+ encodeURIComponent(s);
					const url = 'ss.html?' + b +' '+ s;
					document.location.href = url;	
					
				}); 



ss.html  individual node details show another page

      window.onload = function () {
    var url = document.location.href,
        params = url.split('?')[1].split('&'),
        data = {}, tmp; 
    for (var i = 0, l = params.length; i < l; i++) {
         tmp = params[i].split('%20');
         data[tmp[0]] = tmp[1];
    }
	document.write(tmp[0]+" "+tmp[1]+"<br/><p>welcome to my world</p>" );
	document.write('<IMG "STYLE="position:absolute TOP:200px LEFT:300px" SRC="' + tmp[2] + '">');
	
}

**Comment by ZornitsaPesheva** [comment]
Isn't my code doing that? What is wrong with it?

**Comment by SusmitaSaha12** [comment]
yes but i donot want to show data in url

**Comment by ZornitsaPesheva** [comment]
So how can you pass the data in URL, but not showing it? I don't know if this is possible.
Why don't you use localStorage?

**Comment by SusmitaSaha12** [comment]
THANK YOU for helping.

but i have some another quarry .
In your inbuild js file there is a modal .But i want to customize another modal ,i can open another modal 
so there is one problem i cannot close that modal please help me.

tree.html
  
      <!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Royal Family Tree - Demos | BALKAN OrgChartJS</title>
    <style>
        html, body {
			margin: 0px;
			padding: 0px;
			width: 100%;
			height: 100%;
			font-family: Helvetica;
			overflow: hidden;
		}

		#tree {
			width: 100%;
			height: 100%;
		}
		
		#popup {
			border: 2px solid red;
			position: absolute;
			top: 30%;
			left: 40%;
			display: none;
			padding: 20px;
			background-color:gray;
			transform: translate(-50%, -50%);
		}
		
	</style>
</head>
<body>
    <script src="https://balkangraph.com/js/latest/OrgChart.js"></script>

	<div id="tree"></div>
	<div id="popup"></div>

    <script>
			window.onload = function () {
				OrgChart.templates.family_template = Object.assign({}, OrgChart.templates.ana);
				OrgChart.templates.family_template.size = [86, 86];
				OrgChart.templates.family_template.plus = "";
				OrgChart.templates.family_template.minus = "";
				OrgChart.templates.family_template.rippleRadius = 40;
				OrgChart.templates.family_template.name = '<text style="font-size: 12px;" fill="#000000" x="43" y="100" text-anchor="middle">{val}</text>';
				OrgChart.templates.family_template.title = '<text style="font-size: 12px;" fill="#aeaeae" x="43" y="115" text-anchor="middle">{val}</text>';
			    OrgChart.templates.family_template.img = '<clipPath id="{randId}"><circle cx="43" cy="43" r="38.5"></circle></clipPath></circle><image preserveAspectRatio="xMidYMid slice" clip-path="url(#{randId})" xlink:href="{val}" x="3" y="3"  width="80" height="80"></image>';
				OrgChart.templates.family_template.node = '<circle stroke-width="3" fill="none" stroke="#aeaeae" cx="43" cy="43" r="41.5"></circle>';
				OrgChart.templates.family_template.defs = '<g transform="matrix(0.05,0,0,0.05,-13,-15.5)" id="baby"><circle cx="260" cy="310" r="200" fill="#ffffff"></circle><path fill="#aeaeae" d="m468.64 268.32h-13.591c-18.432-89.348-95.612-157.432-189.139-161.798-.501-.185-1.015-.348-1.545-.482-18.363-4.622-31.188-22.595-31.188-43.707 0-17.828 14.468-32.333 32.252-32.333 12.573 0 22.802 10.258 22.802 22.866 0 8.284 6.716 15 15 15s15-6.716 15-15c0-29.15-23.687-52.866-52.802-52.866-34.326 0-62.252 27.962-62.252 62.333 0 17.876 5.828 34.443 15.769 47.432-80.698 15.127-144.725 78.25-161.291 158.555h-13.591c-24.103 0-43.712 19.596-43.712 43.683 0 24.086 19.609 43.682 43.712 43.682h14.692c20.935 89.871 101.582 157.018 197.596 157.018s176.66-67.148 197.596-157.018h14.692c24.103 0 43.712-19.596 43.712-43.682 0-24.087-19.609-43.683-43.712-43.683zm-265.054 55.257c-8.284-.024-14.981-6.758-14.958-15.043.007-2.337-.708-13.999-15.481-14.041-.026 0-.053 0-.08 0-14.697 0-15.475 11.62-15.481 13.953-.023 8.284-6.75 15.007-15.043 14.957-8.284-.024-14.98-6.759-14.957-15.043.038-13.322 5.349-25.101 14.955-33.166 8.223-6.904 19.065-10.702 30.543-10.702h.148c11.534.033 22.412 3.896 30.63 10.876 9.559 8.12 14.803 19.928 14.765 33.25-.023 8.27-6.735 14.957-14.999 14.957-.013.002-.027.002-.042.002zm52.766 129.374c-26.485 0-48.033-21.533-48.033-48.002 0-8.284 6.716-15 15-15s15 6.716 15 15c0 9.926 8.089 18.002 18.033 18.002s18.033-8.076 18.033-18.002c0-8.284 6.716-15 15-15s15 6.716 15 15c-.001 26.469-21.548 48.002-48.033 48.002zm113.765-129.374c-.015 0-.029 0-.044 0-8.284-.024-14.98-6.759-14.957-15.043.016-5.445-1.993-9.263-6.14-11.673-5.407-3.142-13.27-3.165-18.695-.053-4.161 2.387-6.191 6.193-6.207 11.638-.023 8.27-6.735 14.957-14.999 14.957-.015 0-.029 0-.043 0-8.284-.024-14.981-6.758-14.958-15.043.046-16.149 7.802-29.845 21.281-37.576 14.814-8.497 33.929-8.443 48.695.138 13.434 7.807 21.112 21.547 21.066 37.696-.023 8.271-6.735 14.959-14.999 14.959z"/> </g>';
				
				var chart = new OrgChart(document.getElementById("tree"), {
					template: "family_template",
					enableSearch: false,
					siblingSeparation: 100,
					nodeBinding: {
						name: "Name",
						title: "title",
						img: "img",
					},	
				});

				chart.on('render-link', function(sender, args){
					if (args.cnode.ppid != undefined){
						args.html += '<use xlink:href="#baby" x="'+ args.p.xa +'" y="'+ args.p.ya +'"/>';
					}
					
				});
				
		
				chart.on('click', function(sender, args){    
					var data = sender.get(args.node.id);
					popup.style.display = 'block';
					popup.innerHTML = "Name="+data.Name+"<br/> Title="+ data.title+"<br/> Info="+data.info+"<br/><br/> Profile Image= <br/> "+"<img src="+data.img+" width=\'200px\' height=\'200px\'>";
					
					
					
				}); 
	
	
	
	
	
	

				chart.load([          
					{ id: 1, tags: ["red"], Name: "King George", img: "img_avatar.png",info: "Planning and coordination of the overall Division’s work program and operation, <br/>including program management finance/budget management, <br/>human resources management, and general office administration"},
					{ id: 2, pid: 1, tags: ["partner"], Name: "Queen Elizabeth", title: "The Queen Mother", img: "https://cdn.balkan.app/shared/f2.png" },
					{ id: 3, pid: 1, tags: ["red"],  ppid: 2, Name: "Queen Elizabeth II", img: "https://cdn.balkan.app/shared/f5.png"},
					{ id: 4, pid: 3, tags: ["left-partner"], Name: "Prince Philip", title: "Duke of Edinburgh", img: "https://cdn.balkan.app/shared/f3.png"},
					{ id: 5, pid: 1, ppid: 2, Name: "Princess Margaret", img: "https://cdn.balkan.app/shared/f6.png"},
					{ id: 6, pid: 3,tags: ["blue"], ppid: 4, Name: "Charles", title: "Prince of Wales", img: "https://cdn.balkan.app/shared/f8.png"},
					{ id: 7, pid: 6, tags: ["partner"] , Name: "Diana", title: "Princess of Wales", img: "https://cdn.balkan.app/shared/f9.png"},
					{ id: 8, pid: 6, tags: ["partner"], Name: "Camila", title: "Duchess of Cornwall", img: "https://cdn.balkan.app/shared/f7.png" },
					{ id: 9, pid: 3, ppid: 4 , Name: "Anne", title: "Princess Royal", img: "https://cdn.balkan.app/shared/f10.png"},
					{ id: 10, pid: 3, ppid: 4 , Name: "Prince Andrew", title: "Duke of York", img: "https://cdn.balkan.app/shared/f11.png"},
					{ id: 11, pid: 3, ppid: 4, Name: "Prince Edward", title: "Earl of Wessex", img: "https://cdn.balkan.app/shared/f12.png"},
					{ id: 12, pid: 6, ppid: 7, tags: ["blue"], Name: "Prince William", title: "Duch of Cambridge", img: "https://cdn.balkan.app/shared/f14.png"},
					{ id: 13, pid: 6, ppid: 7, tags: ["blue"], Name: "Prince Harry", img: "https://cdn.balkan.app/shared/f15.png"},
					{ id: 14, pid: 12, tags: ["left-partner"], Name: "Catherine", title: "Duchess of Cambridge", img: "https://cdn.balkan.app/shared/f13.png"},
					{ id: 15, pid: 13, tags: ["right-partner"], Name: "Meghan Markle", img: "https://cdn.balkan.app/shared/f16.png"},
					{ id: 16, pid: 12, ppid: 14, tags: ["blue"], Name: "Prince George of Cambridge", img: "https://cdn.balkan.app/shared/f17.png"},
					{ id: 17, pid: 13, ppid: 15, tags: ["blue"], Name: "Prince Charlotte of Cambridge", img: "https://cdn.balkan.app/shared/f18.png"},
					//{ id: 18, pid: 12, ppid: 14, tags: ["blue"], name: "Prince Louis of Cambridge", img: "https://cdn.balkan.app/shared/f19.png"},
					//{ id: 19, pid: 12, ppid: 14, tags: ["blue"], name: "Princes loka", img: "https://www.w3schools.com/howto/img_avatar.png"}
				]);
		
	
			};
    </script>
</body>
</html>

**Comment by ZornitsaPesheva** [comment]
> In your inbuild js file there is a modal 
Where is this modal?

**Comment by SusmitaSaha12** [comment]
(https://user-images.githubusercontent.com/47620287/124776765-540ca700-df5d-11eb-811d-a97733c78348.jpg)

here is your modal

but i want 
(https://user-images.githubusercontent.com/47620287/124777122-9b933300-df5d-11eb-8d85-0df85aafcef2.jpg)
 this type modal 

there is one problem  i cannot close that (https://user-images.githubusercontent.com/47620287/124777122-9b933300-df5d-11eb-8d85-0df85aafcef2.jpg) modal

**Comment by ZornitsaPesheva** [comment]
This one is on a fiels click (Title): https://balkan.app/OrgChartJS-Demos/PopupOnFieldClick.html
But you can open the same on a node click: https://balkan.app/OrgChartJS-Demos/ShowIdOnNodeClick.html

**Comment by SusmitaSaha12** [comment]
how can i do on node click event show popup???

**Comment by SusmitaSaha12** [comment]
https://balkan.app/OrgChartJS-Demos/CustomDetailsVew.html   is not working

**Comment by ZornitsaPesheva** [comment]
Our site is not working, but we will fix it soon.

**Comment by SusmitaSaha12** [comment]
ok thank you

**Comment by ZornitsaPesheva** [comment]
it's working now

**Comment by ZornitsaPesheva** [comment]
https://jsfiddle.net/rcb3g5mh/

**Comment by ZornitsaPesheva** [comment]
https://jsfiddle.net/rcb3g5mh/1/

**Comment by SusmitaSaha12** [comment]
Thank you so much

**Comment by ZornitsaPesheva** [comment]
I'll close this. Feel free to open another issue if you need.
