### ISSUE TITLE
Some Beginner Questions

### ISSUE THREAD

**Issue by jkrische** [BALKANGraph/OrgChartJS#584]
I am previewing Balkan orgchart vs Google Charts.  We already have a working solution with the latter, but it has weaknesses due to the way Google's system works.  Here are some specific points of concern with the Balkan library that I'm having trouble answering on my own by reading the Docs:

1. Can the text I pass to a node contain CSS and/or html tags?  For example, suppose I wish to pass to the node a block of text that contains a mixture of raw text, a `<ul>` list, plus more text with `<br>` tags between lines, and maybe a `<span>` on part of the text to apply specific formatting to just that span... is this possible?

2. Can node collapse/expand be disabled entirely?  In this project, the chart must always be shown in its entirety and the user should not be able to collapse nor expand the tree at all.  Possible?

3. Can a node have dynamic height?  I will be passing in blocks of text of indeterminant length taken from a DB lookup; some could be quite long.  Can the node auto-size to fit the passed content?

**Comment by ZornitsaPesheva** [comment]
Hi jkrische,

1. If you'd like to add html to the field, yes you can do this: Read **Node HTML fields** here: https://balkan.app/OrgChartJS/Docs/Fields
2. Collapse/expand can be disabled: https://jsfiddle.net/BALKANGraph/fomzL3yc/
3. Here is an example for dynamic height: https://balkan.app/OrgChartJS-Demos/DynamicHeight.html

Feel free also to write us on support@balkan.app if you have any further questions.
