### ISSUE TITLE
How to change size of search bar of the library

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#585]
Hi Guys 

I want to change the size of the search icon of the library, is there any way of doing it? 

I also want to place few things in the org chart, any way to do that too?

**Comment by ZornitsaPesheva** [comment]
Hi Pushpender,

You can change the icon, following this demo: https://balkan.app/OrgChartJS-Demos/SearchResultInTable.html

**Comment by ZornitsaPesheva** [comment]
Can we close this issue?
