### ISSUE TITLE
Search Box Customization

### ISSUE THREAD

**Issue by MuharremTopuz** [BALKANGraph/OrgChartJS#588]
Hi,
How can I make the search box as below
![search](https://user-images.githubusercontent.com/58817833/128026312-d56f1c46-ae3e-49a7-89da-a3bfe39b14b8.JPG)
Have a nice day.
Best Regards

**Comment by ZornitsaPesheva** [comment]
Here is how you can customize the search box: https://balkan.app/OrgChartJS-Demos/SearchResultInTable.html
