### ISSUE TITLE
Issue with Zoom and pan org chart

### ISSUE THREAD

**Issue by pathakvipul71** [BALKANGraph/OrgChartJS#589]
Hi Team, I am facing one issue while using org chart. Below are the steps:

Zoom-in the org chart node (using mouse scroll wheel) and then update its content form outside event like dragging any UI component and dropping it one of the nodes. While re-drawing chart, zoom gets reset to default. I need to retain old zoom state. I am able to produce the same issue on button click in below fiddler location:

https://jsfiddle.net/uLvy0dxb/

**Comment by ZornitsaPesheva** [comment]
Your definition is bad,
You can't have this in the chart definition:
```            
let nodes = [
                    { id: 1, name: "Denny Curtis", title: "CEO" },
                    { id: 2, pid: 1, name: "Ashley Barnett", title: "Sales Manager" },
                    { id: 3, pid: 1, name: "Caden Ellison", title: "Dev Manager" },
                    { id: 4, pid: 2, name: "Lynn Hussain", title: "Sales" },
                    { id: 5, pid: 3, name: "Tanner May", title: "Developer" }
                ];
            
                chart.load(nodes);

```

We do it this way:
```
        var chart = new OrgChart(document.getElementById("orgchart"), {
            nodeBinding: {
                field_0: "name"
            },
            nodes: [
                { id: 1, name: "Amber McKenzie" },
                { id: 2, pid: 1, name: "Ava Field" },
                { id: 3, pid: 1, name: "Peter Stevens" }
            ]
        });
```

or this way:
```
        var chart = new OrgChart(document.getElementById("orgchart"), {
            nodeBinding: {
                field_0: "name"
            },
        });

            var nodes = [
                { id: 1, name: "Amber McKenzie" },
                { id: 2, pid: 1, name: "Ava Field" },
                { id: 3, pid: 1, name: "Peter Stevens" }
            ];
        chart.load(nodes);

```

**Comment by ZornitsaPesheva** [comment]
Here is how to udate nodes: https://jsfiddle.net/3djvhckL/

**Comment by pathakvipul71** [comment]
The JS fiddler link shared above is using chart.Update() method but for my case, I need to update complete nodes object from external event. So I cannot use this method. I am using react-hooks to maintain state of nodes and its fields. And in case of nodes state update, my chart will get re-render. Above code snippets does not work for my requirement.

**Comment by ZornitsaPesheva** [comment]
So you need the same zoom on the next chart.load()? You can try to get chart.config.zoom and set it on load, but I am not sure if this could be that easy as there is also scale that may be changed.

**Comment by pathakvipul71** [comment]
Can you please share the fields I should try to update to retain zoom?

**Comment by ZornitsaPesheva** [comment]
You could use the state option: https://balkan.app/OrgChartJS/Docs/APIReference#state
Here is a demo: https://balkan.app/OrgChartJS-Demos/State.html?StateForMyOrgChart-scale=1&StateForMyOrgChart-x=-235&StateForMyOrgChart-y=-172&StateForMyOrgChart-exp=1*2*4*5*3*6&StateForMyOrgChart-min=&StateForMyOrgChart-adjustify=0*0

**Comment by pathakvipul71** [comment]
Yes, I have started making use of it. I am working on fixing my issue with state values.
