### ISSUE TITLE
Update single node prperties (question)

### ISSUE THREAD

**Issue by hdbrinkmann** [BALKANGraph/OrgChartJS#59]
[4PLANOrgChart.html.zip](https://github.com/BALKANGraph/OrgChartJS/files/3022126/4PLANOrgChart.html.zip)
I am using the "childcount" function to show this value in the "LOWER_RIGHT" Field of my orgchart (code in Line 230-245 of the attached file). 
I want to update this value after the user moved an element to a new parent. The onupdate event allows me to identify both old and new parent, I need to update the childcount (LOWER_RIGHT Field) in these elements. 
How can I update the LOWER_RIGHT field in this two node-elements? the update functions seems to require all attributes of the node, do I have to set all attributes? If so, how can I determine pid etc. of the moved nodes' old and new parent? 
Thank you for you support.

**Comment by BALKANGraph** [comment]
[4PLANOrgChart.zip](https://github.com/BALKANGraph/OrgChartJS/files/3051082/4PLANOrgChart.zip)

I have modified your code, now LOWER_RIGHT is calculated on drag&drop

In one of the following versions children count will be calculated by OrgChart JS and will look like:

    nodeBinding: {
            field_0: "TITLE",
            field_1: "SUBTITLE",
            field_2: "UPPER_LEFT",
            field_3: "UPPER_RIGHT",
            field_4: "LOWER_LEFT",
            field_5: function(sender, node){
                return node.childrenCount;
            }
        },

in the current version node.childrenCount is not implemented
