### ISSUE TITLE
How to add ellipses after 2 lines? 

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#590]
Hi I want to add multiline ellipses after 2 lines here, https://jsfiddle.net/pushpender98/f4Lm1h9b/

**Comment by ZornitsaPesheva** [comment]
There is no such opsion, but we could implement it.

**Comment by pushpender98** [comment]
PLease provide something

**Comment by ZornitsaPesheva** [comment]
We have added this functionality to our to do list.

**Comment by pushpender98** [comment]
WE need this functionality sooner, is it possible to priorities it?

**Comment by ZornitsaPesheva** [comment]
We will try to do it soom.

**Comment by pushpender98** [comment]
Any update

**Comment by ZornitsaPesheva** [comment]
We aren't implemented this yet.

**Comment by ZornitsaPesheva** [comment]
Hi Pushpender.
We have implemented this in version 7.10.40
https://balkan.app/OrgChartJS/Docs/TextOverflow
