### ISSUE TITLE
Error: <svg> attribute viewBox: Expected number, "NaN,NaN,481,700"

### ISSUE THREAD

**Issue by NyashaZiwewe** [BALKANGraph/OrgChartJS#591]
I am not sure where the problem is. I have commented out all node values

**Comment by ZornitsaPesheva** [comment]
Do you use a licenesed version?

**Comment by NyashaZiwewe** [comment]
No i m still trying the product

**Comment by ZornitsaPesheva** [comment]
Could you try to reproduce the issue in jsfiddle?

**Comment by NyashaZiwewe** [comment]
![image](https://user-images.githubusercontent.com/53811529/129886739-de583099-c5ce-4c2e-ac62-dc11173249d9.png)

**Comment by NyashaZiwewe** [comment]
I am seeing this even when i copy examples from https://balkan.app/OrgChartJS/Demos/Basic

**Comment by ZornitsaPesheva** [comment]
It looks like your trial is expired and you need to purchase a license.

**Comment by NyashaZiwewe** [comment]
Noted. Thank you

**Comment by murtazayucal** [comment]
hi ,solved your problem ? @NyashaZiwewe
