### ISSUE TITLE
OrgChart override standard Array

### ISSUE THREAD

**Issue by vingeek-dev** [BALKANGraph/OrgChartJS#593]
Hi,
we have a problem with other libraries imported in my project, because OrgChart is overriding standard Array. 
From OrgChart library code:

`
(Array.prototype.has = function (t) {
 for (var e = 0; e < this.length; e++) if (this[e] == t) return !0;
 return !1;
 })`

After OrgChart is loaded all arrays are overridden. How to avoid this?

We encountered this problem also in latest version.

Thanks

**Comment by gmaggiodev** [comment]
I found the same problem. You should define the property "has" in this way:

```javascript
Object.defineProperty(Array.prototype, 'has',{
  value: function (t) { for (var e = 0; e < this.length; e++) if (this[e] == t) return !0; return !1; },
  writable: true,
  configurable: true,
  enumerable: false
});
```

**Comment by ZornitsaPesheva** [comment]
Hi Vincenzo and Gianluca,

We have changed the "has" function as you suggested,
Thank you very much!

**Comment by vingeek-dev** [comment]
> Hi Vincenzo and Gianluca,
> 
> We have changed the "has" function as you suggested,
> Thank you very much!

Hi Zornitsa, is possible to have info about the release of this bug fix?

Thanks,
Vincenzo.

**Comment by ZornitsaPesheva** [comment]
It is releaset in version 7.10.43. There are no other changes in it.
The current one is 7.10.44. There is changed only the new nodeCircleMenu functionality.

**Comment by vingeek-dev** [comment]
Hi Zornitsa, now it works perfectly. 😄 

Thanks,
Vincenzo.
