### ISSUE TITLE
Multiple input links

### ISSUE THREAD

**Issue by sreejitrozario** [BALKANGraph/OrgChartJS#594]
Hi,
I want to create a process chart like this.
![image](https://user-images.githubusercontent.com/23395416/132989764-dda06151-18ab-463a-9446-c822405222ea.png)

I am facing issue in two places.
1) **Each Node can have multiple input & multiple output.**
2) The text on top of the links needs to appear **on Click/Hover** (We can not show the data permanent because as you see, the screen will be too much crowded.).

Please suggest a solution for it.
I did look into **c-links**, but the problem is that if two nodes are at same level then the nodes are linked from input to input (provided I did it right). https://jsfiddle.net/xab8gmq4/
I need to somehow have make the nodes connect (input to output) even if they are on same level.

**Comment by ZornitsaPesheva** [comment]
Hi  
sreejitrozario,

We don't have possibility to do these multiple inputs and outputs with our library,

**Comment by gtato** [comment]
I kinda have the same problem. I am trying to create my family tree, but I can't put my grandparents from my mom and dad and then have mom and dad be partners cause my dad pid is either mom or grandma (and ppid grandpa) but there is no way to create a partner link which is not a parent. I think that makes the family tree option quite unusable.

**Comment by ZornitsaPesheva** [comment]
Hi Genc,

We are now working on a new library called FamilyTree.js
Please follow us on [Facebook ](https://www.facebook.com/BALKAN.App.Inc)and [LinkedIn ](https://www.linkedin.com/company/balkanapp/)for the release.

**Comment by ZornitsaPesheva** [comment]
Here we have some beta of the library. Please test:
https://www.npmjs.com/package/@balkangraph/familytree.js
