### ISSUE TITLE
Issue with multiline 

### ISSUE THREAD

**Issue by pushpender98** [BALKANGraph/OrgChartJS#597]
![image](https://user-images.githubusercontent.com/36353150/134172665-c6946bdb-a887-4ecb-8385-362edf19532f.png)
 
If have only one line then it should be center aligned vertically

**Comment by ZornitsaPesheva** [comment]
Here is a demo on how to align vertically: https://balkan.app/OrgChartJS-Demos/VerticalCentering.html

**Comment by pushpender98** [comment]
Is it possible using CSS?

**Comment by pushpender98** [comment]
[data-n-id] text:nth-of-type(3) tspan:nth-of-type(1) {
 baseline-shift: 10px;
}

[data-n-id] text:nth-of-type(3) tspan:nth-of-type(2) {
 baseline-shift: 10px;
}

[data-n-id] text:nth-of-type(3) tspan:only-child {
 baseline-shift: 0px;
}


this works for me and its a generic one
