### ISSUE TITLE
Is there a limit to node level?

### ISSUE THREAD

**Issue by antman89** [BALKANGraph/OrgChartJS#6]
May I know is there a limit to number of levels of nodes? 
Currently it stuck at Level 101.

![image](https://user-images.githubusercontent.com/38718341/50680788-f0c7f400-1043-11e9-80fc-a3cebb0bbfd8.png)

when it reached its maximum level it will show the link to nowhere.

Thanks.

**Comment by ZornitsaSerbezova** [comment]
In the licensed version there is no limit.
