### ISSUE TITLE
Getting error while updating the node.

### ISSUE THREAD

**Issue by kvkaranverma** [BALKANGraph/OrgChartJS#602]
`var nodeData = {firstField: "HR/ADMIN",
id: "9_7",
onContextMenu: "OrgMenu.show(this,IdBitPattern.reuse(1473),7,event);",
photoId: 128,
pid: "9_2",
secondField: "Responsibilities as now",
tags: ['mainTemplate'],
thirdField: "HR Coordinator"}`

Hi, I was trying to update the node with `chart.updateNode(nodeData)`, after updating the tags. But I'm getting the error. 
![image](https://user-images.githubusercontent.com/42038789/136781952-daeec8fa-4307-407d-b4c0-14371c46a74e.png)
![image](https://user-images.githubusercontent.com/42038789/136782009-9d666758-caac-4a36-9ae8-e6961a0ac0a0.png)
In the first attachment, it is throwing the error while parsing JSON.

I was not able to reproduce in JS fiddle, if there is any possibility to connect and see the issue.

**Comment by ZornitsaPesheva** [comment]
Thank you for informing us
I'm canceling the meeteng.
