### ISSUE TITLE
Wrong result when maximize a node.

### ISSUE THREAD

**Issue by peteblackbone** [BALKANGraph/OrgChartJS#603]
![image](https://user-images.githubusercontent.com/41714800/137478907-dc94ee25-789f-4671-a228-7da961ff07e9.png)

https://jsfiddle.net/pm154w9g/
I'm trying to render chart in tree layout, but got error on rendering. please check! sorry for my bad english.

**Comment by ZornitsaPesheva** [comment]
Fixed in 8.06.01
