### ISSUE TITLE
Collapse allChildren not working

### ISSUE THREAD

**Issue by itlvlup** [BALKANGraph/OrgChartJS#604]
Dear,

Follow your exemple :
var chart = new OrgChart(document.getElementById("tree"), { 
            collapse: {
                level: 2,
                allChildren: true
            },
            ...
        });
Only level 2 are collapse, not their children.

Even on your website.

**Comment by ZornitsaPesheva** [comment]
fixed
Pleaee download the lates version(8)

**Comment by itlvlup** [comment]
Nice it work! thank a lot
