### ISSUE TITLE
orgchart based on database

### ISSUE THREAD

**Issue by rafthh** [BALKANGraph/OrgChartJS#606]
i just need show the orgchart with this plugin, i have problem when im getting data and add the node.. the orgchart wasnt show. 
im new right here, accidentally press enter then this issue was opened.

i already have get the data JSON like : 

> [ {"id":"1","name":"Alex","title":"Big Boss"},{"id":"1","name":"Jess","title":"Boss"}, {"id":"2","pid":"1","name":"Thomas","title":"Executive"}, {"id":"3","pid":"2","name":"Jack","title":"Foreman"} ]

my case is, there is dropdown option.. so each option will show the diff orgchart. and one of the option will return the data like that. So my code is, im already instance the orgchart js like

```
var chart = new OrgChart(document.getElementById("orgchart"), {
        enableDragDrop: true,
        mouseScrool: OrgChart.action.none,
           nodeBinding: {
            field_0: "name",
            field_1: "title"
        }
    });
```

if select one of option and click the button search will show the some orgchart

```
$('#search-button').on('click', function() {
            if ($('#department').val() != '') {
                var departemen = $('#department').val();
                $.ajax({
                    url: "{{route('SO.getOrgChart') }}",
                    method: "GET",
                    data: {
                        department: department
                    },
                    success: function(data) {
                        $test = JSON_parse(data);
                        chart.addNode($test);
                        chart.draw();
                    },
                    dataType:"json"
                });
            }
        });
```

the feature is when choose another department n click button search, the orgchart will be changed. im literally new, my project is using framework laravel 7.

**Comment by ZornitsaPesheva** [comment]
Hi rafthh,
I couldn't understand what exactly is the issue.
You get error on chart.add()?
Please try to reproduce the issue in jsfiddle or in an simple html file.
Was it working before and just stopped? If it was working, then your trial may have expired.

**Comment by rafthh** [comment]
> Please note that you have one **departemen** without "t" at the end.

aah yah thanks, and update i got this error on console

> 
![image](https://user-images.githubusercontent.com/92699348/138034740-ba35b844-4a61-4870-8857-143528c2ca53.png)
