### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by riza-wartek** [BALKANGraph/OrgChartJS#607]
I'm having an issue of `Access to XMLHttpRequest at 'https://se-asia-balkangraph.azurewebsites.net/api/OrgChartJS' from origin 'http://alritio-dev.azurewebsites.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`, take a look at picture below

![image](https://user-images.githubusercontent.com/90178615/137768415-153f7406-f4d2-4616-b68a-ae12b7a5fdc9.png)

Even tho I've set the website to `http://alritio-dev.azurewebsites.net` like picture below:
![image](https://user-images.githubusercontent.com/90178615/137768655-6fe53c1e-8286-4e7e-9e20-0317c19f9331.png)

What should I do?

**Comment by riza-wartek** [comment]
is it indeed the trial version, where can I get the licensed version? My invoice number 1000003465

**Comment by riza-wartek** [comment]
i dont find any link from the console page
![image](https://user-images.githubusercontent.com/90178615/137850664-7cca7af2-d647-4c59-8da4-de69f688a437.png)

**Comment by ZornitsaPesheva** [comment]
Your It looks like your account is expired and you need to renew it if you need to download a newer version than the one you have used until now.

**Comment by riza-wartek** [comment]
When can I get the version that I'm using right now?
