### ISSUE TITLE
chart.center() => showing all the hidden(unexpanded) nodes.

### ISSUE THREAD

**Issue by tyagivishal009** [BALKANGraph/OrgChartJS#614]
The function chart.center() apart from focusing on the top node, this function is also showing all the hidden(unexpanded) nodes, moreover whenever we pass an id of a particular node, it renders the entire top hierarchy of that particular node in its bottom.

My requirement: - I need a function which can return an id of a top most node in the chart, no matter where we click on the hierarchy of the nodes it should always return me the top most node i.e the node which is the parent of all the nodes.

**Comment by tyagivishal009** [comment]
[https://jsfiddle.net/t28ybp7j/1/]
 Here is the demo link

**How to reproduce the issue**:-First click on the "set as root 8" button, then click on the "Make 8 center" button, it will expand the entire chart.

**Expected Output**: - It should focus on the node whose id has been passed as a parameter in chart.center() function without expanding the entire chart, moreover it should also place that particular node in the center.

**Comment by ZornitsaPesheva** [comment]
Please try this example: https://jsfiddle.net/j0s5bmwL/1/

**Comment by tyagivishal009** [comment]
https://jsfiddle.net/t28ybp7j/1/

**Comment by ZornitsaPesheva** [comment]
The example that I gave you do exactly what you want, I think, or not?

**Comment by ZornitsaPesheva** [comment]
you can try chart.center(parent_id) in click event;
You need these:
https://balkan.app/OrgChartJS/Docs/APIReference#click
https://balkan.app/OrgChartJS/Docs/NodeAPI

**Comment by tyagivishal009** [comment]
thanks
