### ISSUE TITLE
Changing the root node, not creating the chart.

### ISSUE THREAD

**Issue by kvkaranverma** [BALKANGraph/OrgChartJS#615]
I have requirement, in that I have to change the root node. That not has not been expanded yet, but it's data exist in the chart. And now if I change the root node, and call the `chart.draw()` method. It doesn't draw the chart. Chart will be empty in this scenario.

**Comment by ZornitsaPesheva** [comment]
It looks like this is a bug and we will try to fix it soon.

**Comment by ZornitsaPesheva** [comment]
Hi Karan,
Now you can expand directly any node. Please download 8.0.22

**Comment by kvkaranverma** [comment]
Hi @ZornitsaPesheva, I have licensed version of Balkan library, and I'm using that version. But I'm facing the same issue.

**Comment by ZornitsaPesheva** [comment]
https://jsfiddle.net/BALKANGraph/jbxkof0m/

**Comment by kvkaranverma** [comment]
On clicking of button, it is not setting up the root node, it is just navigating me to that node, and again clicking on button chart is empty.
Please take this issue on priority. As it's been a month, and we are stuck on this, because of this issue.

**Comment by kvkaranverma** [comment]
Also, I have the licensed version of balkan library, is the newer version is automatically updated when I download file from the balkan console or the code that is on github is different?
Because if I use github code it seems to be different, and is not working correctly as it worked with the code taken from balkan console after logging in to there site.

**Comment by ZornitsaPesheva** [comment]
PLease try this example: https://jsfiddle.net/j0s5bmwL/1/

**Comment by kvkaranverma** [comment]
It worked, but the latest licensed version is still at 8.00.17. It doesn't contain the latest code.

**Comment by ZornitsaPesheva** [comment]
Please try Ctrl+F5, as I just have checked and the latest licensed version is this: 8.00.34

**Comment by kvkaranverma** [comment]
version is updated but facing the same issue. It comes as an empty screen

**Comment by ZornitsaPesheva** [comment]
> version is updated but facing the same issue. It comes as an empty screen

In our example?

**Comment by kvkaranverma** [comment]
In the example we cant use the licensed version. It is working fine with the normal version.

**Comment by ZornitsaPesheva** [comment]
Both version should work thesame way,
Could you try alert(Orgchart.VERSION)

**Comment by kvkaranverma** [comment]
Version is 8.00.34, still it is not drawing chart for the non expanded node set as root node.

**Comment by ZornitsaPesheva** [comment]
I just have downloaded the latest source code (You have Premium license I think) amd tested this eample with it and it work fine:
https://jsfiddle.net/j0s5bmwL/1/

**Comment by kvkaranverma** [comment]
Thanks, it worked. :)

But now I'm facing one more challenge in this. It is not updating that tags of the nodes correctly (If a particular node has a different tag). Could you please look into this on priority.

**Comment by ZornitsaPesheva** [comment]
It looks like tags are the same here: https://jsfiddle.net/BALKANGraph/cuzo3gdr/
Could you show us what you mean?

**Comment by kvkaranverma** [comment]
Thanks, for taking up this issue on priority, it is working fine now. :)
