### ISSUE TITLE
NaN error is coming

### ISSUE THREAD

**Issue by kvkaranverma** [BALKANGraph/OrgChartJS#616]
Here is link of the JS fiddle link of the error in the console. https://jsfiddle.net/e0n9vghf/

**Comment by kvkaranverma** [comment]
I don't know how it is coming. This error is coming in my code. Then I had verified the demos of the balkan chart, it is also throwing errors. This fiddle link is taken from the balkan chart.

**Comment by ZornitsaPesheva** [comment]
I don't get error in this jsfiddle
