### ISSUE TITLE
Export with PDF, PNG, SVG not working

### ISSUE THREAD

**Issue by Jason-15** [BALKANGraph/OrgChartJS#617]
When we try an export with PDF we get back a 15 byte file that cannot be opened. This was only happening when the export was done with more than 303 nodes. But now it's downright not working at all

**Comment by ZornitsaPesheva** [comment]
Hi Jason,
Do you use a licensed version?

**Comment by Jason-15** [comment]
Yes i do.

**Comment by ZornitsaPesheva** [comment]
Can you please isolate the issue, and send it to support@balkan.app?
