### ISSUE TITLE
Lines overlapping with two roots nodes and dynamic node height.

### ISSUE THREAD

**Issue by vingeek-dev** [BALKANGraph/OrgChartJS#619]
Hi,
We have found a new bug in the OrgChart library(latest version), we have reproduced it in this jsfiddle:
https://jsfiddle.net/bhLecaws/1/

**The case**

We have a chart with two roots, one of which has a child node of type 'assistant'.
We need to resize the height of a node if a certain condition is met. To do this, a new template is created at runtime and associated with the node to be modified.
**To do this, click the Resize Node button on top left.**

**The issue**

When the node is assigned the new height, an overlap problem occurs between the connecting lines.

![asd](https://user-images.githubusercontent.com/1867200/140495838-117837a8-32a7-4668-a8ee-65c2860a412e.png)

**Expected result**

The chart display is correct (i.e. no overlapping lines).

![Untitled-1](https://user-images.githubusercontent.com/1867200/140505927-348c2253-e525-44f8-855d-6071077a796b.png)

Thanks

**Comment by ZornitsaPesheva** [comment]
Hi Vincenzo,
We will check this issue when we can.

As a workaround you can put both trees in invisible nodes as subtrees and this way they will not overlap.

**Comment by vingeek-dev** [comment]
Hi Zornitsa,
thanks for your reply.

I tried to follow your advice and managed to make the example work.
https://jsfiddle.net/zpe2vs3h

Unfortunately, in our case we have very complex data structures and therefore it would be a bit complicated to apply this workaround in all cases.
We will try this temporary solution but we are still waiting for the bug to be fixed.

Thank you,
Vincenzo.

**Comment by vingeek-dev** [comment]
Hi Zornitsa, is possible to have info about the release of this bug fix?

Thanks,
Vincenzo.

**Comment by ZornitsaPesheva** [comment]
Hi Vincenzo,
This issue is still not fixed.

**Comment by vingeek-dev** [comment]
Hi,
are there any updates about this? 
@ZornitsaPesheva

**Comment by ZornitsaPesheva** [comment]
Fixed in 8.06.01
