### ISSUE TITLE
getViewBox returning NaN results

### ISSUE THREAD

**Issue by jkrische** [BALKANGraph/OrgChartJS#622]
The situation:
We are paid licensees of orgchart.  We have a bootstrap 4 carousel that generates the orgchart SVG on the carousel "slid" event, which then places the generated SVG into the carousel pane.  When we do this in a page that is not hosted in an iframe, it always works normally, with no errors.  However, when this page is hosted in an iframe, we occasionally get this error:

`Error: <svg> attribute viewBox: Expected number, "-143,-55,NaN,NaN".`

When this happens, the SVG does not display.  The particular numbers within the error change but the NaN's on the end of the line are always the same.  I pretty-printed orgchart.js so that I could more easily spot the function generating the error, and this is what I found:

```
Uncaught SyntaxError: Unexpected token N in JSON at position 10
    at JSON.parse (<anonymous>)
    at Function.OrgChart._getViewBox (orgchart_pretty.js:4270)
    at OrgChart.getViewBox (orgchart_pretty.js:221)
    at orgchart_pretty.js:154
    at orgchart_pretty.js:2712
    at orgchart_pretty.js:2731
    at Object.OrgChart.local._setPositions (orgchart_pretty.js:2181)
    at OrgChart.server._read (orgchart_pretty.js:2722)
    at orgchart_pretty.js:2709
    at Object.OrgChart.state._get (orgchart_pretty.js:5150)
```
    
line 4268--4270 of this pretty-printed version contains the following:
```
OrgChart._getViewBox = function(t) {
	var e = null;
	return t ? (e = (e = "[" + (e = t.getAttribute("viewBox")) + "]").replace(/\ /g, ","), e = JSON.parse(e)) : null
}
```

I have no idea why it would be returning NaN results in this case and am hoping you can help.  It's obviously attempting to get the dimensions of an object that may not be visible yet; perhaps the function is merely out of sync and triggering too early.   

This is a complex project and I don't think I'll be able to recreate it in a simple Fiddle, but I would be happy to do a screen sharing session on Google Meet with the orgchart devs.

**Comment by ZornitsaPesheva** [comment]
Hi jkrische!
Please be sure that you have given sizes on all the chart divs before initialization.
If you still are unable to manage this issue, please ask on support@balkan.app for a screen sharing session.

**Comment by jkrische** [comment]
Hrm, that will be a challenge given that this is a responsive design with lots of fluid-sized divs, but we will try.
