### ISSUE TITLE
how change node key json

### ISSUE THREAD

**Issue by amir3164** [BALKANGraph/OrgChartJS#623]
hi this JSON object
[
{ 'idorg':'1', 'parent':'null', 'name': 'Bo Miao', 'title': 'department manager' },
{'idorg':'2', 'parent':'1','name': 'Su Miao', 'title': 'department manager'},
{ 'idorg':'3', 'parent':'1','name': 'Yu Jie', 'title': 'department manager' },
{ 'idorg':'4', 'parent':'1','name': 'Yu Li', 'title': 'department manager' },

    ]

i use idorgwith parent
i want create chart with idorgand parent or change  id  with idorg  and  pid with parent

**Comment by ZornitsaPesheva** [comment]
Hi,

Here you can reasd how to do this: https://stackoverflow.com/questions/13391579/how-to-rename-json-key/44887315

**Comment by amir3164** [comment]
i want dont rename iam change 
   OrgChart.PID = "parent";
        OrgChart.idorg= "id1";

**Comment by ZornitsaPesheva** [comment]
id and pid are mandadtiory property manes. They can't have other names,
