### ISSUE TITLE
How to create partner's partner like ex wife or husband?

### ISSUE THREAD

**Issue by hkmsadek** [BALKANGraph/OrgChartJS#624]
Hi there, I am trying to draw relationship between partner's partner. For example, Mom's partner is Dad and Dad's may have one or more ex partners. How do we do this?

Here I want to add dad's ex wife... 

How can I do this?
https://user-images.githubusercontent.com/26408759/145704414-6e13ad1b-31e7-4fcd-9c05-a5768070d48e.png

`
![Screenshot 2021-12-12 at 1 35 45 pm](https://user-images.githubusercontent.com/26408759/145704414-6e13ad1b-31e7-4fcd-9c05-a5768070d48e.png)
`

**Comment by ZornitsaPesheva** [comment]
Please take a look at our Family Tree JS: https://balkan.app/FamilyTreeJS/Docs/GettingStarted
