### ISSUE TITLE
'Mode' classes overrides others css rules and scrollbars

### ISSUE THREAD

**Issue by vingeek-dev** [BALKANGraph/OrgChartJS#628]
Hi,
since version 8.00.01 and the implementation of the '**mode**', we have noticed that a class (with the name of the chosen mode) is added to the element that will contain the chart.

![image](https://user-images.githubusercontent.com/1867200/146541177-9d7ac529-ec21-4ec2-ae2b-b8cbe198bd95.png)

This class is too generic because, for example, having the name '**light**' overrides the light class which is already specified by our css framework.

This obviously happens because a style tag is added inside the svg element.

![image](https://user-images.githubusercontent.com/1867200/146541126-faa566a1-13bc-4190-a948-6d13ce1c12e7.png)

Would it be possible to add a prefix to the class (e.g. 'ba-light') so that it does not affect the whole page?

By the way, this also creates problems on the scrollbars of the whole page as the following css rules are present in the style:

`::-webkit-scrollbar{
    width:15px
}
.dark ::-webkit-scrollbar-track{
    background:#1e1e1e;
    border-left:1px solid #333
}
.dark ::-webkit-scrollbar-thumb{
    background:#424242
}
.dark ::-webkit-scrollbar-thumb:hover{
    background:#4f4f4f
}
.dark ::-webkit-scrollbar-thumb:active{
    background:#5e5e5e
}
.light ::-webkit-scrollbar-track{
    background:#fff;
    border-left:1px solid #ddd
}
.light ::-webkit-scrollbar-thumb{
    background:#c1c1c1
}
.light ::-webkit-scrollbar-thumb:hover{
    background:#929292
}
.light ::-webkit-scrollbar-thumb:active{
    background:#666
}`

Thanks

**Comment by plamen-peshev** [comment]
you are right

we added "boc-" prefix to all css styles in tha latest version 8.01.00, boc stands for balkan org chart

**Comment by vingeek-dev** [comment]
Hi Plamen,
we verified it with latest version and now it works.

Thanks,
Vincenzo.
