### ISSUE TITLE
Intermediate nodes?

### ISSUE THREAD

**Issue by vmgm87** [BALKANGraph/OrgChartJS#63]
Hello,

Is possible to add a node without information between two nodes that are in different levels to make sure a node is in corresponding level? for example if there are two nodes under the node root one director and the other one is not director is a manager but is under the root(this is directly under the root but it should be in level 3 because of its position not it level 2 next to the director).

Thanks!
VG

**Comment by BALKANGraph** [comment]
I'm not sure what you want to achieve, can you draw an image and send it

**Comment by vmgm87** [comment]
Hello, can level property be set to a node?
In attached image for example I have the root that can be a vp, a sub manager is under the vp and also the director is under vp and they both are in level one, however a submanager in the image should be in level 3 (under the level of managers) even if this submanager directly reports to vp (should be where the dotted circle is) please let me know if this can be possible?

thank you in advance!
VG
![levelExample](https://user-images.githubusercontent.com/36521421/55732817-e0743c00-59d9-11e9-973e-f057367fce7a.PNG)

**Comment by vmgm87** [comment]
Hello @BALKANGraph  team,
Do yo have any additional questions about what i am asking?
Thanks!
VG

**Comment by plamen-peshev** [comment]
Yes, you can add an empty node 

Here is a demo: https://balkangraph.com/OrgChartJS-Demos/EmptyNode

![image](https://user-images.githubusercontent.com/49443821/56476769-b3c62700-64a5-11e9-929e-4e199d6acb54.png)

**Comment by vmgm87** [comment]
Good morning @plamen-peshev 
Thank you for you reply, I was trying to click on "edit in JSFiddle" option in the above demo but it doesn't work, so I can not see how an empty node is created, can you please share with me that part, how to create an empty node?
Thanks again!
Regards,
VG

**Comment by plamen-peshev** [comment]
Clear your browse cache and open again https://balkangraph.com/OrgChartJS-Demos/EmptyNode 

JSFiggle will work

**Comment by vmgm87** [comment]
Thanks! @plamen-peshev  it worked!...I'll try to test this :)
Regards,
VG
