### ISSUE TITLE
Collapse all to 1 line

### ISSUE THREAD

**Issue by fiberson** [BALKANGraph/OrgChartJS#630]
Good afternoon. I apologize in advance for my English.
I am using the paid version, I have an affiliate tree multilevel. I need it to initially display all collapsed to 1st line when entering. How do I do it?
Sorry for that, but here is my Laravel blade file (https://codepen.io/fiberson/pen/JjrOwdV)
I just need a parameter that will cause me to minimize the affiliate tree to 1 line automatically when I enter the page.

**Comment by ZornitsaPesheva** [comment]
Here is how to collapse all nodes initially:

```
var chart = new OrgChart(document.getElementById("tree"), { 
            collapse: {
                level: 2,
                allChildren: true
            },
            ...
        });
```
