### ISSUE TITLE
node circle menu

### ISSUE THREAD

**Issue by hashir921** [BALKANGraph/OrgChartJS#631]
Node circle menu is not working on the Family Tree JS

**Comment by ZornitsaPesheva** [comment]
Hi hashir921,

This is known issue.
I will remove it from the doc page for now.

**Comment by hashir921** [comment]
I need the circle menu for my project

**Comment by ZornitsaPesheva** [comment]
Hi, we have added circle menu in Family Tree JS: https://code.balkan.app/family-tree-js/circle-menu#JS
Also you already could write to our Family Tree gitHub page next time : https://github.com/BALKANGraph/FamilyTreeJS/issues
