### ISSUE TITLE
Template group didnt work when load json

### ISSUE THREAD

**Issue by rijalrubio** [BALKANGraph/OrgChartJS#632]
i have predefined template like this :

```
OrgChart.templates.group.min = Object.assign({}, OrgChart.templates.group);
    OrgChart.templates.group.min.name = '<text data-width="230" data-text-overflow="multiline" style="font-size: 24px;" fill="#aeaeae" x="125" y="65" text-anchor="middle">{val}</text>';
    
    var chart = new OrgChart(document.getElementById("tree"), {
        lazyLoading: true,
        layout: OrgChart.treeRightOffset,
        enableDragDrop: false,
        mouseScrool: OrgChart.action.none,
        nodeMouseClick: OrgChart.action.none,
        collapse: {
            level: 2,
            allChildren: true
        },
        nodeBinding: {
            name: "groupName",
            field_0: "name",
            field_1: "title"
        },
        tags: {
            "node-with-subtrees": {
                min: true,
                template: "group",
                subTreeConfig: {
                    siblingSeparation: 3,
                    columns: 2
                }
            }
        }
    });            
            chart.on('click', function (sender, args) {
                if (args.node.min) {
                    sender.maximize(args.node.id);
                }
                else {
                    sender.minimize(args.node.id);
                }
                return false;
        });
```

my schema is : 
user need to choose which diagrams to display, so there is a dropdown menu and after choosing menu and then user need press the button to show the diagram. the button will return some json.

the problem is : 
after load the json, template of grouping wont appear. but when im loading normally, without my schema, the template will work ### properly. 

screenshot :

**without schema, template work properly** 

> ![Screenshot_1](https://user-images.githubusercontent.com/90442047/148889953-3d518894-17e5-4457-9edd-d2b5e99ab37b.png)
> ![Screenshot_2](https://user-images.githubusercontent.com/90442047/148889965-ec6a757c-90cd-48ce-a260-f27d7b234308.png) 

**With the schema, template cant work properly** 

> ![Screenshot_3](https://user-images.githubusercontent.com/90442047/148889979-21ea90b5-cb2e-46b1-b4e9-3457a93fb79d.png)
> ![Screenshot_4](https://user-images.githubusercontent.com/90442047/148889976-758564b8-3bc6-45b1-ae48-dcf18c4e9d66.png)

**Comment by ZornitsaPesheva** [comment]
Hi, could you reproduce the issue in the link below, because it looks like I don't understand what is it:
https://jsfiddle.net/0mhaufrz/

**Comment by rijalrubio** [comment]
Im sorry for my bad english and explanation what is my problem.
Im not similar reproduce the issue with jsfiddle, im not really trying reproduce so approxiately like this at : [link](https://jsfiddle.net/fn2qL0w7/3/)

What i mean with schema is my issue .. the template cant work properly and what i mean without the schema is when the nodes on javascript.. it will work properly like my screenshot.

And then.. my button for trigger the chart is like :

```
$('#query-button').on('click', function() {
            if ($('#department').val() != '') {
                var department = $('#department').val();
                $.ajax({
                    url: "{{route('org.getchart') }}",
                    method: "GET",
                    data: {
                        department: department
                    },
                    success: function(data) {

                        const test = JSON.parse(JSON.stringify(data));

                        chart.load(test);
                    },
                    dataType: "json"
                });
            }
        });
```
when button triggered (load data), the template cant work properly

**Comment by ZornitsaPesheva** [comment]
It never minds where you get the data from.
It should work the same way if the data is hardcoded.
As it works here: https://jsfiddle.net/uLn9e0pz/
Just the nodes had to be declared before the load.
Pleaed if you still have this issue, try to reproduse it in jsfiddle with hardcodded data,

**Comment by ZornitsaPesheva** [comment]
Yes, "tags": "[\"node-with-subtrees\"]", will not work, if you have "node-with-subtrees" in the configuration.

**Comment by rijalrubio** [comment]
so how to use that configuration? 
i put the tag on there because i want to use the configuration

**Comment by ZornitsaPesheva** [comment]
Sorry, I have edited my comment. I didn't nottice that I need to add escape symbols

**Comment by rijalrubio** [comment]
aah i see, so how i can get the true return value? 
Im already try input the backslash before double quotes but still get the wrong return value.

> ![image](https://user-images.githubusercontent.com/90442047/149645697-b829a84e-a6e4-41e6-aa12-2b5994906d4f.png)

> ![image](https://user-images.githubusercontent.com/90442047/149645730-aac8365d-dfae-438b-9d22-0e9ad872df7c.png)

**Comment by plamen-peshev** [comment]
try replacing 
'tags' => "[\"node-with-subtree\"]" with 'tags' => '["node-with-subtree"]'

**Comment by rijalrubio** [comment]
already try that and still didnt work

> ![image](https://user-images.githubusercontent.com/90442047/149736260-31e2ae6d-f1c7-4f14-938c-96a3c61ee760.png)

**Comment by plamen-peshev** [comment]
which framework are you using?

**Comment by rijalrubio** [comment]
laravel

**Comment by plamen-peshev** [comment]
can you try escaping single quote, something like 

'tags' => "[\'node-with-subtree\']"

**Comment by rijalrubio** [comment]
yes i do, but still didnt work

> ![image](https://user-images.githubusercontent.com/90442047/150051531-a0f1a041-3b25-4599-929e-8fee348212dc.png)

**Comment by ZornitsaPesheva** [comment]
For the "group" template, youshould have this:
```t
ags: {
        "node-with-subtrees": {
            template: "group"
        }
    }
```

**Comment by rijalrubio** [comment]
> For the "group" template, youshould have this:
> 
> ```
> tags: {
>         "node-with-subtrees": {
>             template: "group"
>         }
>     }
> ```

i dont get it... about where i should have that code
i already instance that on predefined template


> i have predefined template like this :
> 
> ```
> OrgChart.templates.group.min = Object.assign({}, OrgChart.templates.group);
>     OrgChart.templates.group.min.name = '<text data-width="230" data-text-overflow="multiline" style="font-size: 24px;" fill="#aeaeae" x="125" y="65" text-anchor="middle">{val}</text>';
>     
>     var chart = new OrgChart(document.getElementById("tree"), {
>         lazyLoading: true,
>         layout: OrgChart.treeRightOffset,
>         enableDragDrop: false,
>         mouseScrool: OrgChart.action.none,
>         nodeMouseClick: OrgChart.action.none,
>         collapse: {
>             level: 2,
>             allChildren: true
>         },
>         nodeBinding: {
>             name: "groupName",
>             field_0: "name",
>             field_1: "title"
>         },
>         tags: {
>             "node-with-subtrees": {
>                 min: true,
>                 template: "group",
>                 subTreeConfig: {
>                     siblingSeparation: 3,
>                     columns: 2
>                 }
>             }
>         }
>     });

**Comment by ZornitsaPesheva** [comment]
This is your code:
https://code.balkan.app/org-chart-js/632#JS
What is not working in youe case?

**Comment by rijalrubio** [comment]
> This is your code: https://code.balkan.app/org-chart-js/632#JS What is not working in youe case? To make maximizing to work, you should add the rest of the code from here: https://code.balkan.app/org-chart-js/group-template#JS

when im load the data from json, the "group" template wasnt work. on my json im already add tags for "group" template like tags: ['node-with-subtrees'].

**Comment by plamen-peshev** [comment]
I have tested (this)[https://code.balkan.app/org-chart-js/632#JS] code demo and it works like chart for me

Can you please test it on your side and confirm that it works as you expected, if not you can modify the code save and sand back here

**Comment by rijalrubio** [comment]
> ```
>         $collection->push(['id'=> "0", 'nama'=>'Denny Curtis', 'jabatan'=> 'CEO']);
>         $collection->push(['id'=> '1', 'pid'=>'0', 'tags'=> '["node-with-subtrees"]', 'groupName'=> 'Sales']);
>         $collection->push(['id' => '2', 'stpid'=> '1', 'nama' => 'Bret Fraser', 'jabatan' => 'Sales']);
>         $collection->push(['id' => '3', 'stpid'=> '1', 'nama' => 'Steff Haley', 'jabatan' => 'Sales']);
>         $collection->push(['id' => '4', 'stpid'=> '1', 'nama' => 'Ashley Barnett', 'jabatan' => 'Sales']);
>         $collection->push(['id' => '5', 'stpid'=> '1', 'nama' => 'Elliot Patel', 'jabatan' => 'Sales']);       
>         return response()->json($collection);
> ```

already fixed! pushing value for tags should be array like :
`'tags'=> ['node-with-subtrees']`

I'm sorry, its my fault. thanks for the response!
