### ISSUE TITLE
Dynamic Width for only certain Tags

### ISSUE THREAD

**Issue by jkrische** [BALKANGraph/OrgChartJS#633]
Using your example here:
https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/DynamicWidth

How would one apply this technique to only nodes that have a certain tag?

For example, in my diagram, the root node has the tag "primary".  All other nodes are children of this node.

I want the tagged Primary node to be dynamic-width, but not any other nodes.  How would I do that?

I would assume the "magic" is in this line:
var allNodesRect = document.querySelectorAll('[data-n-id] rect');

...wherein we merely need to change the query selector target, but I have no idea what that selector would look like.

**Comment by ZornitsaPesheva** [comment]
Should be something like this... just change the condition as you need it
https://jsfiddle.net/o5vu6t3c/1/

**Comment by jkrische** [comment]
Thanks Z, you're the best.
