### ISSUE TITLE
toolbar orientation?

### ISSUE THREAD

**Issue by jkrische** [BALKANGraph/OrgChartJS#636]
Is there a way to have the toolbar run horizontally instead of vertically?

As shown:
![horizontal_toolbar](https://user-images.githubusercontent.com/82238101/152439951-de72a6cf-ee47-4d87-9948-e1c72c5c09dd.png)

**Comment by ZornitsaPesheva** [comment]
I have crested a demo for you: https://code.balkan.app/org-chart-js/toolbar-rotate#CSS
