### ISSUE TITLE
Links persist on empty root node inside a group

### ISSUE THREAD

**Issue by apouliquen** [BALKANGraph/OrgChartJS#637]
Hello.
We have bought your Orgchart.js library and so far are quite satisfied with it.
However, we are encountering a small issue: we have many groups and when trying to have some root nodes on different levels, we have chosen to use the method you suggested in some other issues, which is, to add invisible/nodes as root of nodes that need to be lower than others. The issue is that the links between the invisible node and its children are not being removed, even when using 
    OrgChart.templates.root.link = '';

I have created a balkan.code demo to illustrate the issue: https://code.balkan.app/first-level-root-inside-a-subtree

**Comment by ZornitsaPesheva** [comment]
Hi,
The links that should be hidden, belong the the children of the root, not at the root itself.
But as you are using sublevels, you need to do hide the sulbelel template link.
But as you are using the sublevels for other nodes also, you need to hide only these links with CSS:
```
[data-l-id="[8][9_sub_level_index_0]"],
[data-l-id="[8][7_sub_level_index_0]"]
{
    display: none !important;
}
```

**Comment by apouliquen** [comment]
I understand. But since I'm building the chart dynamically, it would be difficult to add this css part for the needed children. I noticed that removing the sublevel for the children of the hidden root could help, but that would mean adding an empty node for each sub-level between the child and its parent (for example, if I have one child at sub-1 and one at sub-2)
Is there really no other way to remove/hide the sublevel links other than CSS?

**Comment by ZornitsaPesheva** [comment]
You can achieve this using the "rebder=link" event.
We have created a demo for you: https://code.balkan.app/org-chart-js/sublevels-link-visibility#JS

**Comment by apouliquen** [comment]
This solution is perfect thank you very much!
