### ISSUE TITLE
Tree layout problems when nodes have different height.

### ISSUE THREAD

**Issue by vingeek-dev** [BALKANGraph/OrgChartJS#639]
Hi,
We have found a new bug in the OrgChart library(latest version), we have reproduced it in this jsfiddle:
https://jsfiddle.net/kreqo263

When there is a chart with '**tree**' layout specified, if some nodes have **different height**(a different **tag** with other dimensions) the chart doesn't work as expected infact the **nodes** are **overlaid**.

![image](https://user-images.githubusercontent.com/1867200/155733056-238febfb-a57c-45ef-aa50-4d5ce251c831.png)

Thanks

**Comment by vingeek-dev** [comment]
Hi,
are there any updates about this? 
@ZornitsaPesheva

**Comment by ZornitsaPesheva** [comment]
Sorry, we are busy on a project now, but soon we will try to start working on all these issues,

**Comment by ZornitsaPesheva** [comment]
Fixed in 8.06.01
