### ISSUE TITLE
Orgchart empty when pid not in scope

### ISSUE THREAD

**Issue by hdbrinkmann** [BALKANGraph/OrgChartJS#64]
In my scenario, orgcharts can be dynamically created by filtering external data, for example due to user rights. The Orgchart remains empty if the top node has a parent that is not in the scope of the data I sent into the nodes-array. Every node with a pid that is not an id in the current node array must be created as top level node. 
Example: User has rights to see all employees in HR. Head of HR is id "HRHEAD", his pid is "CEO", but "CEO" is not in the nodes array. 
Is there a chance to solve this problem in the orgchart control or the script I use to display the orgchart?

**Comment by BALKANGraph** [comment]
Retested functionality has been implemented in the latest release

Test here: https://balkangraph.com/js/exp/64.html

**Comment by hdbrinkmann** [comment]
Works as expected, thank you very much!
