### ISSUE TITLE
Error while exporting pdf from Org chart

### ISSUE THREAD

**Issue by deepaksemwal** [BALKANGraph/OrgChartJS#641]
getting error while trying to export pdf file from org chart. It gives error on following line in js file:
var blob = new Blob([content], { type: t});
Error: SCRIPT5022: InvalidStateError

**Comment by ZornitsaPesheva** [comment]
Please isolate your issue here: https://code.balkan.app/orgchartjs/exporting#JS

**Comment by ZornitsaPesheva** [comment]
I will close this issue as it looks inactive. Please feel free to reopen it with an example if needed.
