### ISSUE TITLE
Using Angular Components for Custom Edit UI?

### ISSUE THREAD

**Issue by HCyberViper** [BALKANGraph/OrgChartJS#642]
I was hoping to get some help with custom template for edit ui for angular using angular components.
I forked a stackblitz example I found which seemed to be trying to do exactly what I am trying to do.
https://stackblitz.com/edit/angular-ivy-ha7sgu?file=src/app/orgchart/orgchart.component.ts
I have angular component `app-detail` which I would like to use as my edit ui but I could not figure out how to do so. 
I looked into angular injecting and dynamic component but could not figure out how to use these angular concepts in the orgchart.
How can I use my own angular components for the edit ui?

**Comment by ZornitsaPesheva** [comment]
Here is how you can add your custom element in our Edit UI: https://balkan.app/OrgChartJS/Docs/Edit#addElements

**Comment by HCyberViper** [comment]
hello,
Thank you for the reply!
The link you have provided is the one I looked at while trying to make my own components in the stackblitz link provided above, and it appears that to add custom 'elements' you have to create them one buy one but I would like to separate creating individual elements and use angular components and have more control of directives, services, etc..
So the problem I am still facing is how to create angular component instead of creating single elements using balkan orgchart in angular.

**Comment by ZornitsaPesheva** [comment]
Here is how you can add your own custom menu: https://balkan.app/OrgChartJS/Docs/Edit#custom
You can also have your own edit/details buttons and your own popups:
https://balkan.app/OrgChartJS-Demos/PopupOnFieldClick.html - popup on field click
https://balkan.app/OrgChartJS-Demos/ButtonInNodes.html - add a button

**Comment by HCyberViper** [comment]
I was wondering if you had angular examples that work with angular approach where it uses angular components and directives using what balkan documentations provide within stackblitz instead of just javascript examples. 
If there are no examples that can be provided in angular I will continue to work on what I have in angular and close this issue. 
Hopefully someone in Balkan or the community may have an suggestion/example in the future.

**Comment by ZornitsaPesheva** [comment]
Hi, we have changed the function form **anim** to **animate** and added it to TS.
