### ISSUE TITLE
Node Menu Circle Button Incorrect Type in Typescript/Angular and menu Circle Click Bug?

### ISSUE THREAD

**Issue by HCyberViper** [BALKANGraph/OrgChartJS#643]
Hello, I have two questions I was hoping to get some answers/guide for:

1.
I wanted to make custom node menu into a circle just as shown in 
https://code.balkan.app/org-chart-js/custom-node-circle-menu#JS
and 
https://balkan.app/OrgChartJS/Docs/Menus#circle
in **angular** however the examples above will provide an error in **angular (line 13 of stackblitz)** because **nodeCircleMenuButton** is _expecting string type_ but you assigned with an _object_. 
How can I make this work in my stackblitz angular sample?

https://stackblitz.com/edit/angular-ivy-ttunek?file=src/app/orgchart/orgchart.component.ts

2.
And a similar question to this is adding custom template from https://balkan.app/OrgChartJS/Docs/CreatingCustomTemplate is also providing error saying that field_0 and field_1 does not exist in _type template_.
https://stackblitz.com/edit/angular-ivy-nbgib1?file=src/app/orgchart/orgchart.component.ts
How can I make my fields customizable if the orgchart.d.ts does not have any of my custom fields? I would like to add more fields to nodes.

**Comment by HCyberViper** [comment]
i was able to some what have a working approach for question 2 for simple addition of multiple fields by changing this example snippet 
```
     OrgChart.templates.myTemplate.field_0 = '<text style="font-size: 24px;" fill="#ffffff" x="100" y="90" text-anchor="middle">{val}</text>';
```
to
```
     OrgChart.templates.myTemplate['field_0'] = '<text style="font-size: 24px;" fill="#ffffff" x="100" y="90" text-anchor="middle">{val}</text>';
```
for angular to not give an error and to show multiple individual fields on the node. I have not yet tested out if other example and custom attributes will work.

**Comment by ZornitsaPesheva** [comment]
We have fixed these issues.
Please use the latest version - 8.02.38

and declare the fields this way: **OrgChart.templates['olivia']['field_0'] =**

**Comment by HCyberViper** [comment]
@ZornitsaPesheva 
Sorry I had to open this again but after failing to make the circle menu functions to work I found that 
https://balkan.app/OrgChartJS/Docs/Menus#circle
https://code.balkan.app/org-chart-js/node-circle-menu#JS
will not work in angular. 
I checked the `orgchart.d.ts` file after doing `npm i @balkangraph/orgchart.js` and if appears that under `interface circleMenuUI`, the `on` property does not have click as an option for `type`.

Am I maybe not following the example correctly? or maybe a mistake/bug?

The stackblitz sample shows the error: https://stackblitz.com/edit/angular-ivy-hjmcre?file=src/app/orgchart/orgchart.component.ts

![image](https://user-images.githubusercontent.com/53593899/158016351-5ce6b0d5-4750-4780-942c-54b37ffa2239.png)

**Comment by HCyberViper** [comment]
@ZornitsaPesheva 
Sorry I had to open this again but after failing to make the circle menu functions to work I found that 
https://balkan.app/OrgChartJS/Docs/Menus#circle
https://code.balkan.app/org-chart-js/node-circle-menu#JS
will not work in angular. 
I checked the `orgchart.d.ts` file after doing `npm i @balkangraph/orgchart.js` and if appears that under `interface circleMenuUI`, the `on` property does not have click as an option for `type`.

Am I maybe not following the example correctly? or maybe a mistake/bug?

The stackblitz sample shows the error: https://stackblitz.com/edit/angular-ivy-hjmcre?file=src/app/orgchart/orgchart.component.ts

![image](https://user-images.githubusercontent.com/53593899/158016351-5ce6b0d5-4750-4780-942c-54b37ffa2239.png)

**Comment by ZornitsaPesheva** [comment]
I have added "click" in on of circleMenuUI.
I am not sure if you can use onclick

**Comment by HCyberViper** [comment]
Sorry, so to use the `click `in `on `of `circlemenuui`, I will have to npm install balkan to update?

> I am not sure if you can use onclick

After checking `orgchart.d.ts`, I am confused. I had assumed that onclick was possible to use as 
`nodeCircleMenu?: OrgChart.menu,` is of type `OrgChart.menu` and 
```
    interface menu  {
        [key: string]: {
            text: string,
            icon?: string,
            onClick?: Function,
            color?: string,
            draggable?: boolean
        }
    }
```
contains `onClick` as one of its property option but when adding a function to onClick it does not appear to be calling the function to show alert. (lines 99-102). 
So I wanted to confirm if this the expected behavior for not be able to add function to `onClick`?

**Comment by ZornitsaPesheva** [comment]
You need to download the latest version, yes.

I have checked, but it appears, that you can't use onClick in the configuration.
We will create another type for nodeCircleMenu as it is different from the other menus.
