### ISSUE TITLE
Export to Word Document and Excel  (not csv)

### ISSUE THREAD

**Issue by syahmimokhtar** [BALKANGraph/OrgChartJS#644]
Hye, this org chart library is great. I really looking forward for this library for having an export option of chart into word document
(.doc,.docx) and excel (.xls/.xlsx). Is there a plan for this in the future?

**Comment by ZornitsaPesheva** [comment]
Here is our Exporting doc page: https://balkan.app/OrgChartJS/Docs/Exporting
You can export to PDF, PNG or SVG and import to .doc,.docx

Can you show us some similar product that is exporting to (.doc,.docx) and excel (.xls/.xlsx)?

**Comment by ZornitsaPesheva** [comment]
I will close this issue as it looks inactive. Please feel free to reopen it if needed.
