### ISSUE TITLE
Export Server Availability

### ISSUE THREAD

**Issue by cklee75** [BALKANGraph/OrgChartJS#645]
Would like to check what is the availability/uptime for BALKAN OrgChartJS's export server https://balkan.app/export?
Any plan to change export PDF and PNG at client side?

Thanks.

**Comment by ZornitsaPesheva** [comment]
You can use your own export service: https://github.com/BALKANGraph/export-service

**Comment by cklee75** [comment]
Thanks for your comment. I am aware of this export service. However, my project is using serverless architecture, where does not want to host a backend service. It would be great if BALKAN OrgChartJS's export server has high availability / uptime (like > 99%) or has plan to export PDF and PNG at client side soon.

Thanks.

**Comment by ZornitsaPesheva** [comment]
BALKAN OrgChartJS's export server has high availability / uptime (like > 99%)
