### ISSUE TITLE
Migration to Vue 3

### ISSUE THREAD

**Issue by Gabvo94** [BALKANGraph/OrgChartJS#646]
Hello,

We are upgrading to Vue 3. Could you give me insights on a migration to Vue 3 with Balkan? Can you maybe adapt your [example](https://balkan.app/OrgChartJS/Docs/Vuejs) on how to use it with vue to the vue 3 composition api?

Thank you!

**Comment by ZornitsaPesheva** [comment]
We have updated the documentation:
https://balkan.app/OrgChartJS/Docs/Vuejs
