### ISSUE TITLE
OrgChart does not have multiple layouts in one chart.

### ISSUE THREAD

**Issue by syahmimokhtar** [BALKANGraph/OrgChartJS#647]
Hello can orgchart perform multiple layouts in one particular chart? hoping for this to be implemented in the future!

**Comment by ZornitsaPesheva** [comment]
Hi Muhammad,
Org Chart JS can have multiple layouts: https://code.balkan.app/Preview/org-chart-js/different-layouts

**Comment by syahmimokhtar** [comment]
Thanks! can i see more of these from the docs, is there any?

**Comment by ZornitsaPesheva** [comment]
You can see all the the [API](https://balkan.app/OrgChartJS/API/classes/OrgChart): https://balkan.app/OrgChartJS/API/classes/OrgChart#events
