### ISSUE TITLE
How to show Search Bar on Hover?

### ISSUE THREAD

**Issue by HCyberViper** [BALKANGraph/OrgChartJS#648]
Hello, I was looking at some examples from https://github.com/plamen-peshev/orgchartjs-templates and I wanted to try to also add the showing of the search bar on hover instead of using the default search bar that shows full width from the examples in your website.
I tried to inspect the source code for one of the example templates, https://stackblitz.com/edit/web-platform-yxuvnf?file=script.js but could not figure out how the show search on hover and positioning was done. How can this be achieved? It does not seem like there is an example in your website on how this can be done?

**Comment by ZornitsaPesheva** [comment]
It looks like these examples uses an old Org Chart JS version.
Here is an example with the old search UI that you can use with the new version of Org Chart JS:
https://code.balkan.app/Preview/org-chart-js/old-search-ui

**Comment by HCyberViper** [comment]
Thank you for the example! 

Sorry but I was wondering if the old version had 
`OrgChart.events.publish`,
`OrgChart.attr`,
`OrgChart._search.search(...)`,
` OrgChart._getFistImgField(...)`?
I wanted to understand the code and how to use the example you have provided but I was getting errors that the mentioned methods do not exist in OrgChart for version 8.2.56

here is stackblitz where I was able to get the example you have provided to show but encounter errors that certain methods do not exist:
https://stackblitz.com/edit/typescript-matajt?file=index.ts
![image](https://user-images.githubusercontent.com/53593899/159131671-087c8778-e78c-4bb9-9c2f-ae3a6dce30c3.png)
