### ISSUE TITLE
search input fields is showing the entire div instead of showing name and image

### ISSUE THREAD

**Issue by jallad13** [BALKANGraph/OrgChartJS#649]
as described in the title, the search input field is not showing the name and image of the employee. 
It is showing the value of the div instead
![image](https://user-images.githubusercontent.com/50027914/159696759-6ed9ab10-624c-4a08-81e5-29901ded7c6b.png)

**Comment by jallad13** [comment]
thanks in advance

**Comment by ZornitsaPesheva** [comment]
Could you please isolate the issue in Code?
https://code.balkan.app/orgchartjs/getting-started#JS

**Comment by jallad13** [comment]
i can copy past html/js code here

**Comment by jallad13** [comment]
I'm using ajax call

**Comment by ZornitsaPesheva** [comment]
You can use hardcoded data instead.
You can get your data with this:
console.log(chart.config.nodes)

**Comment by jallad13** [comment]
i solved, the problem was caused because i was following the instruction:
https://balkan.app/OrgChartJS/Docs/Npm
when i do not follow that, it works fine

**Comment by ZornitsaPesheva** [comment]
You need to follow this only if you use the licensed version and NPM installation.
