### ISSUE TITLE
Dotted line (spids) path Problem

### ISSUE THREAD

**Issue by hdbrinkmann** [BALKANGraph/OrgChartJS#65]
![Dottet_line_path_problem](https://user-images.githubusercontent.com/36363606/55476434-d5ef2680-5616-11e9-8c13-bb38c51b2fdf.png)
As you can see in the attached file, the dotted line (spid) does not use a correct path. I decreased the height of the node-element, maybe that causes the problem

**Comment by BALKANGraph** [comment]
The issue has been addressed in the latest release 4.5.0

See: https://balkangraph.com/js/exp/65.html

Please confirm that it works well in your project

**Comment by hdbrinkmann** [comment]
Works perfect! :)
