### ISSUE TITLE
Template variables

### ISSUE THREAD

**Issue by otasyn** [BALKANGraph/OrgChartJS#650]
In templates, I know that you can use `{val}` in what seems like any template property.  I've also noticed that on some, you seen to be able to use `{x}`, `{y}`, and a few others.  However, they don't always seem to work.  I can't find any documentation on which variables are available and where they can be used.  Could you please tell me what is available and where it's available or point me to some documentation that explains this?

**Comment by ZornitsaPesheva** [comment]
We don't have documentation for this.
{val} is the field value form node data.
Where did you get {x} and {y} form?

**Comment by otasyn** [comment]
Sorry, I guess I meant `{w}` and `{h}`.

In the source for 'ana' on [this page](https://balkan.app/OrgChartJS/Docs/PredefinedTemplates), I can also see:
`{viewBox}`
`{content}`
`{rounded}`
`{xa}`
`{ya}`
`{xb}`
`{yb}`
`{xc}`
`{yc}`
`{xd}`
`{yd}`
`{xe}`
`{ye}`
`{id}`
`{p}`
`{randId}`

I've tried `{w}`, `{h}`, and `{randId}` before, and they don't always work.

**Comment by ZornitsaPesheva** [comment]
{viewBox} - the visible part of the tree div element 

{content} - the svg content in the chart

{rounded} - used internally to make the link corners rounded

Used internally for the links drawing:
{xa}
{ya}
{xb}
{yb}
{xc}
{yc}
{xd}
{yd}
{xe}
{ye}

{id} - node ID
{p} - note sure, but you can't use it
{randId} - some randomID of the nodes, used internally
