### ISSUE TITLE
CSP style-src 'self'

### ISSUE THREAD

**Issue by okaluhina** [BALKANGraph/OrgChartJS#651]
Hello, our security policies require us to use the Content-Security-Policy header with "style-src 'self'". But orgchart.js contains quite a bit of inline styling, which cases fail with "Refused to apply inline style".

Is there a chance that would be addressed now or in the future to avoid use of 'unsafe-inline', 'unsafe-hashes' ?

![image](https://user-images.githubusercontent.com/46973932/160546101-4e5ecd36-10b8-4372-a8a2-e7f4204ae2fa.png)

**Comment by ZornitsaPesheva** [comment]
Do I understand right that you need to remove all inline style properties?

**Comment by okaluhina** [comment]
Yes

**Comment by ZornitsaPesheva** [comment]
I don't think you can remove all, but you can remove some.
For example in templates, you can see where we use inline style and you can move it in CSS:
https://balkan.app/OrgChartJS/Docs/CreatingCustomTemplate
