### ISSUE TITLE
Cannot create property 'w' on string '*_mirror'

### ISSUE THREAD

**Issue by alerubis** [BALKANGraph/OrgChartJS#654]
The example below throws `Cannot create property 'w' on string 'CHILD_1_mirror'` error when loaded into an Angular project 

```typescript
var chart = new OrgChart(document.getElementById("tree"), {
    enableSearch: false,
    enableDragDrop: true,    
    mouseScrool: OrgChart.none,
    tags: {
        "assistant": {
            template: "ula"
        },
        "group": {
            template: "group"
	}
    },
    nodeBinding: {
        field_0: "name"
    }
});

chart.load([
    { id: "ROOT", name: "Root" },
    { id: "GROUP", pid: "ROOT", tags: ["group"], name: "Group" },
    { id: "INNER_GROUP", stpid: "GROUP", tags: ["group"], name: "Inner group" },
    { id: "CHILD_1", pid: "INNER_GROUP", tags: ["group", "assistant"], name: "Child 1" },
    { id: "CHILD_2", stpid: "CHILD_1", name: "Child 2" },
]);
```

We are using the last version of Balkan Enterprise (Version: 8.02.68).

The error is thrown at line 13527, cause _m (mirror node?) has a string value (the node id) while the code expects it to be an object.
By reading the source code we found that the error may be at line 7077.
Here mirror node is set to `= mnode.id;`, while we think it should be set to `= mnode;`

**Please note that the code works in javascript, but throws error in typescript.**

**Comment by ZornitsaPesheva** [comment]
Hi Alessio,

I couldn't reproduce the issue:
https://stackblitz.com/edit/angular-ivy-bierfj?file=src%2Fapp%2Forgchart%2Forgchart.component.ts

**Comment by alerubis** [comment]
I also can't reproduce the issue on the free version.

The error occurs by using licensed edition after the steps at https://balkan.app/OrgChartJS/Docs/Npm or by using the source code.

I reproduced the issue on a stackblitz, but it includes the orgchart.js source code so i should not post it here.

Is there any place / mail address i can send you privately the stackblitz link?

**Comment by ZornitsaPesheva** [comment]
Please send your licensed files to support@balkan.app, with the link to this gitHub issue.
