### ISSUE TITLE
How to get Image content from a chart export

### ISSUE THREAD

**Issue by BharathK88** [BALKANGraph/OrgChartJS#655]
I have a requirement to get image content. I do not want to export into a PNG file, I just need to the base64 encoded content. Please help

**Comment by ZornitsaPesheva** [comment]
Here is an example: https://jsfiddle.net/ygczwfa6/

**Comment by BharathK88** [comment]
@ZornitsaPesheva , Thanks for your response. I am able to see Image data but rendering that as an image is not working. Even in the jsfiddle example you have shared, image data is not rendered into a proper image. Can you please check.

**Comment by ZornitsaPesheva** [comment]
I have created a simple example for you: https://code.balkan.app/org-chart-js/get-the-image-as-base64-on-export#JS

**Comment by BharathK88** [comment]
Thanks @ZornitsaPesheva . This example is working. However I need to get image content of chart on completion of load of chart or at least on a button click.  I do not want to use Menu option of OrgChart to export the content.
Is it possible to make first example work where we have external button.

**Comment by ZornitsaPesheva** [comment]
I have changed the example: https://code.balkan.app/org-chart-js/get-the-image-as-base64-on-export#CSS

**Comment by BharathK88** [comment]
Thanks again @ZornitsaPesheva. This will solve my problem. May I know is there any Chart.on events which will let me know the completion of rendering of chart. So that I can export the image automatically instead of a button click.
