### ISSUE TITLE
OrgChart#getSvg() has wrong type

### ISSUE THREAD

**Issue by otasyn** [BALKANGraph/OrgChartJS#656]
https://github.com/BALKANGraph/OrgChartJS/blob/faa84a5342b61178d9bbf083e43be9f300445db5/orgchart.d.ts#L253

`OrgChart#getSvg()` currently lists the type as `SVGAElement`.  That means it would be an SVG `a` element.  The type should be `SVGSVGElement`.  The main difference is that certain fields are not available in `SVGAElement`, such `viewBox`.  The source code is using `getElementById('svg')` which is definitely an `SVGSVGElement`.

**Comment by ZornitsaPesheva** [comment]
Could you give is some simple example here that uses this, so we can test?
https://code.balkan.app/orgchartjs/getting-started#JS

**Comment by ZornitsaPesheva** [comment]
I'll close the issue as it looks inactive. Feel free to reopen it if needed.
