### ISSUE TITLE
Render issue

### ISSUE THREAD

**Issue by vProtas** [BALKANGraph/OrgChartJS#657]
The chart is not added to the dom while the parent container is out of sight.
It can be reproduced for the version 8.02.71

**Comment by ZornitsaPesheva** [comment]
Please isolate the issue in Code:
https://code.balkan.app/orgchartjs/getting-started#JS

**Comment by vProtas** [comment]
@ZornitsaPesheva is my example clear?

**Comment by ZornitsaPesheva** [comment]
We have resolved the issue in the [latest ](https://orgchartjs.balkan.app/JS/ReleaseNotes/8.02.73)version.

Here is an example of how you can use the LAZY_LOADING constant to load the chart while the parent container is out of sight:
https://code.balkan.app/org-chart-js/oninit-is-not-called#JS

**Comment by vProtas** [comment]
@ZornitsaPesheva thank you for your feedback. But I faced with one more issue using the lates version, looks like it not possible to call load after onInit

**Comment by ZornitsaPesheva** [comment]
onInit should be called before chart.load()

Could you please isolate the issue here?: 
https://code.balkan.app/orgchartjs/getting-started#JS

**Comment by vProtas** [comment]
@ZornitsaPesheva 

> onInit should be called before chart.load()
I'm sorry but is it described anywhere?

**Comment by ZornitsaPesheva** [comment]
Good question :)
will check and write you again.

**Comment by ZornitsaPesheva** [comment]
I have added that in TS definition
