### ISSUE TITLE
 Error: <svg> attribute viewBox: Expected number, "NaN,NaN,640,1067".

### ISSUE THREAD

**Issue by murtazayucal** [BALKANGraph/OrgChartJS#658]
Hi , I'm using orgchart, I'm installing it on tomcat server, it opens fine on some computers, but on some I get this error please help.

![Ekran Alıntısı](https://user-images.githubusercontent.com/23107306/164461146-3b3b9ae9-f794-4c12-b0b4-08e260de7098.JPG)

**Comment by ZornitsaPesheva** [comment]
Hi [murtaza](https://github.com/murtazayucal),

Do you use the licensed version?

**Comment by murtazayucal** [comment]
I haven't bought a license yet, I'm developing an angular-based application, it's still in testing phase, I'm running it on tomcat while testing. 5 6 people can use it together, but it gives an error for some people, is it necessary to buy a license?

**Comment by ZornitsaPesheva** [comment]
It looks like your trial is expired. You need to purchase a license.

**Comment by murtazayucal** [comment]
What is the reason for opening on my own computer and some computers ? We were going to make the purchase when the product was finished, our tests are not finished yet.

**Comment by ZornitsaPesheva** [comment]
> What is the reason for opening on my own computer and some computers ? We were going to make the purchase when the product was finished, our tests are not finished yet.

That's the way the trial works. Please write us on email: support@balkan.app

**Comment by murtazayucal** [comment]
hello , we bought Enterprise licence but we are using js file , take error like this "Duplicate identifier 'OrgChart'."

**Comment by murtazayucal** [comment]
can you sending js file using documentation for angular  ?

**Comment by plamen-peshev** [comment]
If it works with the Trial Edition it will work with the Licensed Edition as well

Can you please send us a link to a page where we can see the issue, alternatively you can write us an email to support@balkan.app to schedule Teams call

**Comment by murtazayucal** [comment]
I developed a project using balkanchart version 8.0.29, but after purchasing the license, the version sent to me was 8.03.06, when I changed the version I used in the project, I got an error, was the problem due to the version change, what is your opinion?

**Comment by ZornitsaPesheva** [comment]
I just have tested the source code of the 8.03.06 enterprise version with Angular and it works okay.

Please be sure that you have done this:
1. Download the licensed version from YOUR account
2. Delete this part from orgchart.js:
```
if (typeof(module) != "undefined"){
    module.exports = OrgChart;
}

```
3.Add this at the end of both files: (.js and .d.ts):
```
export default OrgChart
```
