### ISSUE TITLE
If there is no sub level to child node it is displaying in vertical manner

### ISSUE THREAD

**Issue by bhushanarigelaopenmortgage** [BALKANGraph/OrgChartJS#659]
Hi, We are facing an issue with the chart. When there are sub-level to the child node it is displayed in vertical order instead of tree presentation.

Can you guys please help me to resolve this issue?
![Tree](https://user-images.githubusercontent.com/104372019/165109277-67f3de36-72e4-4006-b948-dcbfe2fd8766.png)
![Vertical](https://user-images.githubusercontent.com/104372019/165109282-09983d8d-9dd6-4b16-92bf-bc57372c6a2b.png)

**Comment by ZornitsaPesheva** [comment]
This is because you have set OrgChart.mixed layout in you configuration, If you remove it, it will display in normal layout,
Here is the documentation page: https://balkan.app/OrgChartJS/Docs/Layout
