### ISSUE TITLE
Level property in Node or group?

### ISSUE THREAD

**Issue by vmgm87** [BALKANGraph/OrgChartJS#66]
Is there a "Level" property in a node? to place it in an specific level ? 

Thanks!
regardsm
VG

**Comment by BALKANGraph** [comment]
If you want to display the level of the node

Here is the code:

```
    <script>
        var chart = new OrgChart(document.getElementById("tree"), {
            template: "luba",
            nodeBinding: {
                field_0: "name",
                field_1: function(sender, node){                  
                	return `Level ${node.level}`;
                }
            },
            nodes: [
                { id: 1, name: "Amber McKenzie" },
                { id: 2, pid: 1, name: "Ava Field" },
                { id: 3, pid: 1, name: "Peter Stevens" }
            ]
        });
    </script>
```


![image](https://user-images.githubusercontent.com/43317667/55675997-28a93680-58d4-11e9-9ed9-ff44d8037d68.png)

**Comment by viniciusaab** [comment]
Is it possible to set a node level? How this could be done?

**Comment by ZornitsaSerbezova** [comment]
> Is it possible to set a node level? How this could be done?

OrgChart JS still doesn't support such functionality.

**Comment by ZornitsaSerbezova** [comment]
The tree structure depends of the id and parent id relation
