### ISSUE TITLE
 Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')

### ISSUE THREAD

**Issue by ManjuJain-aviso** [BALKANGraph/OrgChartJS#661]
when we are using the data-width attribute received undefined reading getAttribute 

OrgChart.templates.Test.field_0 =
    '<text  data-width ="130"  data-text-overflow="ellipsis" style="font-size: 14px; flex-grow: 0; font-family: "OpenSans"; font-weight: 600; font-stretch: normal; font-style: normal; line-height: normal; letter-spacing: 0.25px; text-align: left; color: #404255;" x="125" y="25" text-anchor="middle">{val}</text>';

<img width="860" alt="Screenshot 2022-05-09 at 9 48 53 PM" src="https://user-images.githubusercontent.com/103415750/167453989-32b03814-354a-4425-8867-02f64c5ac1bb.png">

**Comment by ZornitsaPesheva** [comment]
Here is the definition:
```
 OrgChart.templates.ana.field_0 = 
        `<text data-width="130" data-text-overflow="ellipsis" 
        style="font-size: 18px; flex-grow: 0; 
        font-family: OpenSans; font-weight: 600; 
        font-stretch: normal; font-style: normal; line-height: normal; 
        letter-spacing: 0.25px; text-align: left; color: #404255;" 
        fill="#ffffff" x="125" y="25" text-anchor="middle">{val}</text>`;
```
