### ISSUE TITLE
Angular cannot use OrgChart.wrapText function

### ISSUE THREAD

**Issue by leonlin716** [BALKANGraph/OrgChartJS#663]
import OrgChart from '@balkangraph/orgchart.js';
....
call OrgChart.wrapText throw
Property 'wrapText' does not exist on type 'typeof OrgChart'.ts(2339)

**Comment by ZornitsaPesheva** [comment]
Could you please show us the example where we use that function?

**Comment by leonlin716** [comment]
@ZornitsaPesheva 
https://balkan.app/OrgChartJS/Docs/TextOverflow

In some cases we change a field using the "field" event. In these cases we will also need the method OrgChart.wrapText to solve the problem with text overflow.

**Comment by ZornitsaPesheva** [comment]
added. Please download the latest version: 8.03.05
