### ISSUE TITLE
nodes exceeds 22, throw error 'Maximum call stack size exceeded'

### ISSUE THREAD

**Issue by huwenyue-web** [BALKANGraph/OrgChartJS#665]
Hello, I have a problem now.
I use OrgChartJS in react projects.When the total number of nodes exceeds 22, the error "Maximum call stack size exceeded" will be reported,but I saw the  maximum number of nodes written in the introduction document is 100000.
Excuse me, what's going on？

Many thanks
![微信截图_20220601152915](https://user-images.githubusercontent.com/106652413/171351128-d7959c5d-036f-4b74-8ab8-6ce545e5c029.png)

**Comment by ZornitsaPesheva** [comment]
Please isolate the issue here: https://code.balkan.app/orgchartjs/getting-started#JS

**Comment by huwenyue-web** [comment]
hello,I have isolated the issue at :https://code.balkan.app/orgchartjs/getting-started#JS


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BALKANGraph/OrgChartJS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月1日(星期三) 下午3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BALKANGraph/OrgChartJS] nodes exceeds 22, throw error 'Maximum call stack size exceeded' (Issue #665)





 
Please isolate the issue here: https://code.balkan.app/orgchartjs/getting-started#JS

**Comment by ZornitsaPesheva** [comment]
We don't speak Chinese.
You need to save your code and post the link here.

**Comment by ZornitsaPesheva** [comment]
I'll close this issue as it looks inactive.
