### ISSUE TITLE
Use the group node to traverse and delete the subtree node and group node to obtain data exceptions

### ISSUE THREAD

**Issue by yizhilaji** [BALKANGraph/OrgChartJS#666]
![error](https://user-images.githubusercontent.com/95121693/173080478-c1ffa3c1-43e0-4702-a4ac-4e44aa002189.png)
The first is to comment out the deletion method, and the second is not to comment out the deletion method

**Comment by yizhilaji** [comment]
![error2](https://user-images.githubusercontent.com/95121693/173081153-f27c6d26-fa01-408c-962c-c67875279b24.png)
This is the case when deleting

**Comment by ZornitsaPesheva** [comment]
What you need is not the default behavior of the deletion. 
I have created an example on how to do it:
https://code.balkan.app/org-chart-js/delete-a-node-with-the-subtrees#JS

**Comment by yizhilaji** [comment]
> 您需要的不是删除的默认行为。 我已经创建了一个如何做到这一点的例子： [https ://code.balkan.app/org-chart-js/delete-a-node-with-the-subtrees#JS](https://code.balkan.app/org-chart-js/delete-a-node-with-the-subtrees#JS)

The problem has been solved. Thank you very much for your help
