### ISSUE TITLE
Change ratio of image in EditFormUI

### ISSUE THREAD

**Issue by witk44** [BALKANGraph/OrgChartJS#667]
Hello I am working with OrgChartJs to create an emplyee structure within a company and I have noticed that the nodes themselves clip the images how i like using preserveAspectRatio="xMidYMid slice". However, when the edit form is displayed the images are warped and the ratio of the image is changed to fit the circle. I was wondering if there was a way to get the editUI image to display exactly like it does on the node that it is displaying the edit form for. Any help would be greatly appreciated, thank you!

**Comment by plamen-peshev** [comment]
you can change the edit form image with css only, here is the selector

```
.boc-edit-form-avatar img{
}
```

**Comment by plamen-peshev** [comment]
Don't set height AND width. Use one or the other and the correct aspect ratio will be maintained.
```

.boc-edit-form-avatar img{
height:initial!important;
width: initial!important;
max-height: 64px;
max-width: 64px;
}
```

Let me know if it helps

**Comment by witk44** [comment]
This works in terms of keeping the image ratio however it made the image incredibly small, so i set the max-height and max-width to incredibly large numbers to see if the image would be contained within the circle and it is not. I'm having touble getting both to work i suppose, i can either have the ratio preserved or the image contained/fill the editUI image circle. I'm assuming if we are editing the css there is no simple fix for this in the html such as OrgChart.editUI.img = '<clipPath id="{randId}"><circle cx="90" cy="160" r="60"></circle></clipPath>'
    + '<image preserveAspectRatio="xMidYMid slice" clip-path="url(#{randId})" xlink:href="{val}" x="30" y="100" width="120" height="120"></image>';
    like you can for a node.

**Comment by witk44** [comment]
I realize the sytax above is wrong its just github was trying to actually create an image from that quote.

**Comment by witk44** [comment]
.boc-edit-form-avatar img{
    object-fit: cover !important;
    }
This did the trick! Thank you for your help!
