### ISSUE TITLE
Trouble with the PDF and PNG exporting

### ISSUE THREAD

**Issue by IHOKCR** [BALKANGraph/OrgChartJS#67]
Hello, I tried several times today the PDF and PNG export for the same chart, even on your DEMOS/Exporting and usually there are no action/file created. Sometimes (rarely) it works, but many times not. Tested on several PCs, different networks on Chrome, IE, Firefox.
Last days/week it didn't work at all for me and for our developers neither.
What are the conditions to run it please?
Thanks for check

**Comment by BALKANGraph** [comment]
We have fixed the issue and release new version

You can try now

**Comment by hdbrinkmann** [comment]
...I just tried: PDF Export now creates File that can not be opened (MacOs Mojave, both Safari and Chrome). :(

**Comment by IHOKCR** [comment]
Hi, I just tried it also and it doesn't work at all now, neither PDF, neither PNG. Isn't it some service which is going down? The SVG and CSV exports immediately create files, but PDF, PNG doesn't start anything.

**Comment by BALKANGraph** [comment]
I must admit that the export service has some issues, it uses chromium and from time to time chromium is not responsive

We are trying to isolate the issue and eventually to fix it

**Comment by JpPamplona** [comment]
Hi!
I am having two issues with exporting to pdf!
First is: I have images with https, and, when I try to export, i receive a message about CORS policy 

> Access to XMLHttpRequest at 'https://balkangraph.com/export/pdf' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

And second is, when I put the images without https and I export the chart, it works, but the images does not appear in the pdf.

 Do you know how can I fix this?

**Comment by BALKANGraph** [comment]
@JpPamplona allow cors policy for static files 

Set Access-Control-Allow-Origin header to *

for iis

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
 <system.webServer>
   <httpProtocol>
     <customHeaders>
       <add name="Access-Control-Allow-Origin" value="*" />
     </customHeaders>
   </httpProtocol>
 </system.webServer>
</configuration>
```
