### ISSUE TITLE
Search Result OnClick

### ISSUE THREAD

**Issue by witk44** [BALKANGraph/OrgChartJS#670]
Is there any doccumentation or a place to find how OrgChart handles a click of a search result. By default org chart centers/expands the node that is clicked in the search results table. However I would like for the onclick to do more than just this but have been unable to find any documentation or functions regarding the onclick of a search result and how to modify this.

**Comment by ZornitsaPesheva** [comment]
Please check if this example can help:
https://code.balkan.app/Preview/org-chart-js/highlight-searched-node

**Comment by witk44** [comment]
Yes this helped very much thank you!
