### ISSUE TITLE
How to change Node PID after the table is build?

### ISSUE THREAD

**Issue by witk44** [BALKANGraph/OrgChartJS#671]
I know there is a drag and drop feature that allows for nodes to be moved after the chart has been loaded but I was wondering if there was a way to chnage pid of a node without using the drag and drop, something like changing it from the edit form for example or another way that doesnt inolve dragging an dropping the node

**Comment by ZornitsaPesheva** [comment]
Yes, you can do this: 
````
var chart = new OrgChart(document.getElementById("tree"), {
    mouseScrool: OrgChart.action.none,
    nodeBinding: {
        field_0: "name"
    },
     editForm: {
            elements: [
                { type: 'textbox', label: 'Parent', binding: 'pid'},
            ]
        },
    nodes: [
        { id: 1, name: "Amber McKenzie" },
        { id: 2, pid: 1, name: "Ava Field" },
        { id: 3, pid: 1, name: "Peter Stevens" }
    ]
});
````

And try to change the pid of id 3 from 1 to 2 from the edit form

**Comment by ZornitsaPesheva** [comment]
We have created this example for you:
Pease test the button of Peter Stevens
https://code.balkan.app/org-chart-js/change-pid#JS
