### ISSUE TITLE
Disable Node Menu Just For One Node

### ISSUE THREAD

**Issue by ninjadev118** [BALKANGraph/OrgChartJS#672]
Can I disable the edit menu but just for the parent/root node? Thank you.

**Comment by ZornitsaPesheva** [comment]
How would you like to disable it?

**Comment by ninjadev118** [comment]
> How would you like to disable it?

Just disable so that access the node menu for the parent node. Is there a way out of the box to do this or is hiding it in CSS the only option? Thanks.

**Comment by ZornitsaPesheva** [comment]
So you want to not have a mode menu for the root?
Here is an example for hiding the button:
https://balkan.app/OrgChartJS-Demos/RemoveNodeMenu.html
