### ISSUE TITLE
Graphic bug on chart lines

### ISSUE THREAD

**Issue by ITDKillerIT** [BALKANGraph/OrgChartJS#674]
When the chart is full rendered and I zoom out, I can see some strange node lines that are not connected to any node (you can see them in the image below, between the red lines I drew).
Am I doing something wrong or is this a visual bug?
Thanks in advance
![chart](https://user-images.githubusercontent.com/51192004/177509951-19c5e346-6740-4932-9f99-812baa7b4e22.png)

**Comment by ZornitsaPesheva** [comment]
It looks like something is wrong with the data.
If you are using the licensed version, please try if this could solve the issue: OrgChart.MAX_DEPTH = 100000
If this is not fixating the issue, please send your data to support@balkan.app and we could check.

**Comment by ITDKillerIT** [comment]
That does not seems to have fixed it. What do you mean by data? What should I send?
Thanks

**Comment by ZornitsaPesheva** [comment]
I meant the JSOM data that you load in the chart.
chart.load(data)

**Comment by ZornitsaPesheva** [comment]
This issue was solved by email.
