### ISSUE TITLE
Drag and drop form a outside component 

### ISSUE THREAD

**Issue by GRBegur** [BALKANGraph/OrgChartJS#675]
I have a scenario where there are two component, one is the org chart tree and another is a container of cards. lets say i have drag and drop event on these two , is there a possibility that i can drag card from right container to left container (org chart) and make it interact with org chart cards. Please help me out on this

Example link : https://stackblitz.com/edit/angular-ivy-3nd6ld?file=src/app/app.component.html

![image](https://user-images.githubusercontent.com/26024262/178891999-eccb76ca-d053-46bf-a83f-ce438a125e52.png)

**Comment by ZornitsaPesheva** [comment]
Here is an example of how to do that:
https://balkan.app/OrgChartJS-Demos/DragDropItemsToChartFromAnotherElement.html

**Comment by GRBegur** [comment]
Thanks a lot i was looking for the same thing
