### ISSUE TITLE
OrgChartImportFromCSV and tags

### ISSUE THREAD

**Issue by dklopfer2** [BALKANGraph/OrgChartJS#676]
I'm not able to reproduce the assistant tag using the OrgChartImportFormCSV.sln example.

I've added the tag to the index.cshtml file  and I updated the OrgChart.csv file and the chart is no different when rendered.
What am I missing????

 **function init(links, nodes) {**
            chart = new OrgChart(document.getElementById("tree"), {
                enableDragDrop: true,
                nodeMouseClickBehaviour: OrgChart.action.edit,
                nodeBinding: {
                    field_0: "name"
                },
                **tags: {
                    "assistant": {
                        template: "ula"
                    }
                },**

OrgChart.csv
id,name,tags,pid,
1,Rudy Doyle,,
**2,Alexis Lewis fsd,assistant	,1**
3,Aiden Dixon,,1
4,sdg,,2
5,new node,,3

**Comment by dklopfer2** [comment]
Sorry in delay, 

Nope.  Did not work provided I made the change in the correct place.    I made it in orgchart.js changing OrgChart.STRING_TAGS != 1  to OrgChart.STRING_TAGS = false  

![Capture](https://user-images.githubusercontent.com/109626593/180317716-703813e6-4a0a-438a-9c53-3a9ae2dc5328.JPG)

**Comment by ZornitsaPesheva** [comment]
No, you don't have to change the orgchart.js file..
You need to do this:
`OrgChart.STRING_TAGS = false
 var chart = new OrgChart(document.getElementById("tree"), {
       ...
        });
`
