### ISSUE TITLE
Template y tag dinámico

### ISSUE THREAD

**Issue by karolMora5** [BALKANGraph/OrgChartJS#677]
¿Cómo añadir un tag y template dinámico?
Quiero cambiar el color de los nodos dependiendo del tag, teniendo un objeto con los colores. Se esta trabajando en ANGULAR

---Cambio de color para el nodo---
    let color = '#ffffff'
    OrgChart.templates.myTemplate = Object.assign({}, OrgChart.templates.ula);
    OrgChart.templates.myTemplate.node =`
    <rect x="0" y="0" height="120" width="250" fill="#ffffff" stroke-width="1" stroke="#aeaeae"></rect>
    <line x1="0" y1="0" x2="250" y2="0" stroke-width="2" stroke="${color}"></line>`;

---Resultado que quiero obtener----
![image](https://user-images.githubusercontent.com/109739750/180217164-047c822a-0aeb-4591-a5ec-8f2b9b1f4a92.png)

**Comment by ZornitsaPesheva** [comment]
Here is an example of how you can do this:
https://code.balkan.app/org-chart-js/conditional-color#JS
