### ISSUE TITLE
Add an array of objects after chart data is loaded 

### ISSUE THREAD

**Issue by GRBegur** [BALKANGraph/OrgChartJS#678]
I have a scenario where i need to add additional array of data 

so lets say initially i use chart.load()
and then i do an API call to get more data, as per docs i see there is a possibility called chart.add() which takes a single object and not an array so is there any way an array of objects be supplied, for adding new nodes.

**Comment by ZornitsaPesheva** [comment]
You can iterate the array and add the nodes this way:
```
for (let i = 0; i;<array.lengt h; i++) {
    chart.add(nodes[i]);
}
chart.draw();

**Comment by GRBegur** [comment]
yes yes, that can definitely be done .
I was asking whether there was any method which would take an array of objects 

There was something like chart.draw(action, actionParams, callback)
this action had an option called ==insert==
but didnt know what it would do as there was no info regarding that 
![image](https://user-images.githubusercontent.com/26024262/180924900-e641b821-18cb-4631-abdd-c9cc2a15f378.png)

**Comment by ZornitsaPesheva** [comment]
Here is how you can add multiple nodes:
https://code.balkan.app/org-chart-js/add-multiple-nodes#JS
