### ISSUE TITLE
Assistant nodes have same level of child nodes

### ISSUE THREAD

**Issue by vingeek-dev** [BALKANGraph/OrgChartJS#679]
Hi!
We are trying to create a chart with assistant nodes that have their tree before the child nodes of the root node.
https://jsfiddle.net/rhL5bn2j

**The case**

We would like the tree of the assistant node(s) to be showed before the direct child nodes.

**Actual Result**

![image](https://user-images.githubusercontent.com/1867200/182111312-f2d4170d-148c-4674-8449-02457fab0094.png)

**Expected result**

![image](https://user-images.githubusercontent.com/1867200/182113611-6ed82333-f32d-41ea-a6d5-51910aa829a3.png)

There are any possibility to draw the chart in this mode?

Thanks

**Comment by ZornitsaPesheva** [comment]
I have created this example for you:
https://code.balkan.app/org-chart-js/assistant-children-above-regular-children#JS

**Comment by vingeek-dev** [comment]
Is there no way to be able to do this with the nodes one has available? Without having to resort to hidden nodes/groups?

**Comment by ZornitsaPesheva** [comment]
This is the other way:
https://code.balkan.app/org-chart-js/assistant-children-above-regular-children-with-sublevels#JS

**Comment by vingeek-dev** [comment]
> This is the other way: https://code.balkan.app/org-chart-js/assistant-children-above-regular-children-with-sublevels#JS

![image](https://user-images.githubusercontent.com/1867200/182349497-3cbf697e-b550-4412-a9bf-4ad1b71264d0.png)

Unfortunately, this is also not a solution, if you add a node in the assistant tree, the result is the same.

**Comment by ZornitsaPesheva** [comment]
You can create a logic that change the children sublevel to +1 when you add another child under the assistant.

**Comment by vingeek-dev** [comment]
Unfortunately, this cannot be a solution for us. We have data structures and assistant nodes grafted for N levels. 
Having to update the sublevel at each expansion (which in our case is dynamic).

Do you think this option/improvement may be available in the future?

**Comment by ZornitsaPesheva** [comment]
In this case you can return to the previous way and add the subtrees dynamically.
I have changed the example: https://code.balkan.app/org-chart-js/assistant-children-above-regular-children#JS

**Comment by ZornitsaPesheva** [comment]
This is implemented in 8.07.00
You need to use OrgChart.VERTICAL_CHILDREN_ASSISTANT = true;
