### ISSUE TITLE
Image within nodes reload on any operation

### ISSUE THREAD

**Issue by GRBegur** [BALKANGraph/OrgChartJS#680]
The scenario can be viewed as a video here : https://drive.google.com/file/d/1KZrDWcuH7-aPQIxpmil1_paGnEHCdSH0/view?usp=drivesdk

when ever i scroll across the page or drag and drop, images within nodes are reloaded. Can this be prevented and if images loaded once be preserved.
I did use lazyloading : false  , but still it persisted 
So please help me out with this

**Comment by ZornitsaPesheva** [comment]
You could try to play with this constant:
OrgChart.IMAGES_THRESHOLD = 100;

**Comment by GRBegur** [comment]
I did try with various values , but its the same , image reloads every time i do something , zoom , move around, drag drop, anything.

**Comment by ZornitsaPesheva** [comment]
Please isolate the issue in Code: https://code.balkan.app/orgchartjs/getting-started#JS

**Comment by GRBegur** [comment]
i found the issue 
if i use this URL https://cdn.balkan.app/shared/2.jpg , image does not reload every time
but if i use any other URL to load image it reloads

**Comment by ZornitsaPesheva** [comment]
Can you give us an image link example that reloads?

**Comment by GRBegur** [comment]
ok, i narrowed down to why this is happening, its due to redrawing of nodes every time some operation is performed.

So can we limit redrawing of chart to only when new nodes are introduced and not on zoom or scrolling through chart 

you can use this to see the number of redraws : https://stackblitz.com/edit/angular-ivy-usgxlq?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

**Comment by ZornitsaPesheva** [comment]
The reloading is not the issue. You can see in your example that the images are not reloading.
PLease create an example with your images.

**Comment by GRBegur** [comment]
I cannot use the image URL in example as its an organizations api which cannot be made public. we under the process of buying you application for our use.

**Comment by GRBegur** [comment]
when nodes are redrawn , images are reloaded by making a call to that URL , which results in such scenario

**Comment by ZornitsaPesheva** [comment]
Most probably the reason is the way you are loading the images.
Maybe you have some logic that slows down the image loading.
Please if you are unable to find the issue, write us to support@balkan.app. We can try to find the issue in a call.

**Comment by GRBegur** [comment]
Definitely, thanks for the help . I will write to the above mentioned mail id

**Comment by charlie447** [comment]
In my case, the image within a node will flash a little bit whenever I drag/move/operate the chart. But I found out that is because I opened the **DevTool** and set the **Disable cache** to yes. So when the chart redrawn, the image will reload from the URL instead of loading from cache. So the images flash. 

![Image](https://github.com/user-attachments/assets/b030edc2-b2fc-4c70-91f4-891d33473774)

**Comment by ZornitsaPesheva** [comment]
Thank you for reporting this.
We have tested and it looks like when the DevTool is closed, it works okay
