### ISSUE TITLE
Toggle Search Bar

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [BALKANGraph/OrgChartJS#681]
Hi I want to toggle(hide/show) search bar on button click on v8.4.4,
I tried something like this:

**_show condition_**
chart.config.enableSearch = true;
chart.draw();

_**hide condition**_
chart.config.enableSearch = false;
chart.draw();

but it's not working, so do you guys have any demo regarding this?

**Comment by ZornitsaPesheva** [comment]
you can use CSS

```
        let search = document.getElementsByClassName('boc-search')[0];
        if (search.style.display == '') {
            search.style.display = 'none';
        } else {
            search.style.display = ''
        }
```

**Comment by vyshnavmk-lumel** [comment]
Hi @ZornitsaPesheva Thanks for the replay, that's one possible solution, but the issue with that one is when we update @balkangraph/orgchart.js version it might cause issue, previously in version 7.9.19, search bar have different selector.
Is there is any other way to achieve similar result?

**Comment by ZornitsaPesheva** [comment]
The chart.config is only for the chart object.
The search and miniMap are not parts (properties) of of the chart object.

**Comment by vyshnavmk-lumel** [comment]
@ZornitsaPesheva Just want to verify this, if we are trying to update non-chart property currently there are no API available for that, So one possible option is access it from DOM and toggle the visibility.

**Comment by ZornitsaPesheva** [comment]
You can use this to hide it 
`search.parentElement.removeChild(search);`
and alternatively to show it
and you can create your own toggle function,
