### ISSUE TITLE
get visibleNodeIds from chart object in typescript

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [BALKANGraph/OrgChartJS#682]
Hi, 
I was trying to get visibleNodeIds from chart object,
but that property was not in type definition file so it was throwing error.
I' m currently using typecast to accessing it like below:

_**const chart = new OrgChart(container, options);
chart.visibleNodeIds**_ // throws error

**_const chartObj : any = chart ;
chartObj.visibleNodeIds_** // works fine

Can we add it in type definition file?

**Comment by ZornitsaPesheva** [comment]
added

**Comment by vyshnavmk-lumel** [comment]
@ZornitsaPesheva Thanks it works well now,
 Any one trying to access `chartObj.visibleNodeIds`  immediately after chart render will get value `undefined`,
 so do something like this in order to get visiblenodeIds
 
```
let visibleNodeIds;
 const chartObj= new OrgChart(chartContainer, chartOptions);
setTimeout(() => {
  visibleNodeIds = chartObj.visibleNodeIds;
}, 200);
```
