### ISSUE TITLE
Styles not being applied on export 

### ISSUE THREAD

**Issue by GRBegur** [BALKANGraph/OrgChartJS#683]
While exporting to PDF or PNG , style specified are not being applied after export
i did try out the following approach but still its not working, 
I am building this in angular
![image](https://user-images.githubusercontent.com/26024262/185147154-8330ec02-b191-46d4-a046-6adf31df7aa3.png)

**Comment by ZornitsaPesheva** [comment]
Please isolate the issue, changing this example: https://code.balkan.app/org-chart-js/how-to-export-styles#JS
