### ISSUE TITLE
Nodes with children in the form of such a tree

### ISSUE THREAD

**Issue by ovolvenkov** [BALKANGraph/OrgChartJS#684]
Tell me please, is it possible to arrange the nodes in the form of such a tree, if these nodes have subtrees.
I want to get tree like this: 
![2022-08-18_12-06](https://user-images.githubusercontent.com/54061574/185403819-64e0cbcc-10f7-4f76-be71-2bc39dc73783.png)
But these nodes have subtrees and they are laid out horizontally.

**Comment by ZornitsaPesheva** [comment]
You can try to use [subtrees](https://balkan.app/OrgChartJS/Docs/SubTrees) and add the real nodes in hidden nodes
https://code.balkan.app/org-chart-js/orgchart.tree-with-subtrees#JS

**Comment by ovolvenkov** [comment]
Thanks for the answer,
![2022-08-22_12-40](https://user-images.githubusercontent.com/54061574/185902436-02603a14-af6a-48b4-81a2-ee4fadc62971.png)
 Please tell me if there are other solutions to this problem, since when expanding the node, there is a problem with displaying links ?

**Comment by homko** [comment]
Hi, the same situation. InvisibleGroup displays incorrectly. And add tags to many items not easy way for the big structure.

In our case, we need to build a structure with a horizontal tree orientation for the company department level and the vertical tree orientation for the subdepartments\teams\subteams\team members levels. 

If it is possible to implement that idea?  
Thanks in advance!

**Comment by ZornitsaPesheva** [comment]
@ovolvenkov , I have changed the example: https://code.balkan.app/org-chart-js/orgchart.tree-with-subtrees#JS

**Comment by ZornitsaPesheva** [comment]
> Hi, the same situation. InvisibleGroup displays incorrectly. And add tags to many items not easy way for the big structure.
> 
> In our case, we need to build a structure with a horizontal tree orientation for the company department level and the vertical tree orientation for the subdepartments\teams\subteams\team members levels.
> 
> If it is possible to implement that idea? Thanks in advance!

Please isolate the issue in code examples and screenshots.

**Comment by ovolvenkov** [comment]
@ZornitsaPesheva, Thanks, this option is working but not suitable for us, since we have dynamic data and hidden nodes can have a different number of nodes, and connections in neighboring nodes are not displayed correctly (highlighted in the image). Can you please tell me if there are any other options suitable for dynamic data?
![2022-08-25_21-58](https://user-images.githubusercontent.com/54061574/186758174-eeaf0085-a67a-4f18-aa19-a20da66cc923.png)

**Comment by ZornitsaPesheva** [comment]
Here we have a example of how you ca do it better, but the code is much more complicated:
https://balkan.app/OrgChartJS/Demos/SmartLayout
![image](https://user-images.githubusercontent.com/19305472/186919915-bb997f9c-8301-4ba6-8d0c-56e35cc75c64.png)
