### ISSUE TITLE
Search field

### ISSUE THREAD

**Issue by ovolvenkov** [BALKANGraph/OrgChartJS#686]
I have a question regarding the "Search field".
I will need to render a separate subtree on a separate page with information on a separate subtree, but by default the "Search field" works on incoming data.
I would like to search through all data that will not be displayed in the current tree.
I would like the search to work based on data from the main tree, and when a node is found, go to a page with full information and indicate the card of the found site.
Can you please tell me if there are any solutions to this problem?

**Comment by ZornitsaPesheva** [comment]
So you need to load the found node and its children only?

**Comment by ovolvenkov** [comment]
I need to switch to another tree that has complete information and show the found element.

**Comment by ovolvenkov** [comment]
> So you need to load the found node and its children only?

I need to switch to another tree that has complete information and show the found element.

**Comment by ZornitsaPesheva** [comment]
I have created this example for you: https://code.balkan.app/org-chart-js/load-another-tree-on-search#JS
