### ISSUE TITLE
Navigate from minimap

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [BALKANGraph/OrgChartJS#687]
Hi, I was wondering if there is any way I can navigate from the minimap

![image](https://user-images.githubusercontent.com/105709887/186205194-ec06d99e-684b-4d22-bdbf-a056ba6452ac.png)

As you can see in the image, the minimap highlights which part of the graph I'm currently looking at, so If I want to move to a different part of the graph from minimap, can I do that?

**Comment by ovolvenkov** [comment]
Yes, I am also interested in this ability

**Comment by ZornitsaPesheva** [comment]
We are developing this functionality right now.

**Comment by ZornitsaPesheva** [comment]
We have implemented this in 8.06.00

**Comment by vyshnavmk-lumel** [comment]
@ZornitsaPesheva Thanks for the update
