### ISSUE TITLE
The trial has expired or 200 nodes limit was reached!

### ISSUE THREAD

**Issue by yizhilaji** [BALKANGraph/OrgChartJS#688]
![image](https://user-images.githubusercontent.com/95121693/189033646-e030ca18-3d50-43bc-8bdb-24955e3796fe.png)
What is the reason for this problem?

**Comment by ZornitsaPesheva** [comment]
Do you have a license?

**Comment by yizhilaji** [comment]
> 执照吗
No

**Comment by yizhilaji** [comment]
> 
I can't get into the official website

**Comment by ZornitsaPesheva** [comment]
The site was down, but now it works again.

**Comment by yizhilaji** [comment]
> The site was down, but now it works again.

thank you
