### ISSUE TITLE
Slink problems: broken chart or lines crossing nodes

### ISSUE THREAD

**Issue by vingeek-dev** [BALKANGraph/OrgChartJS#689]
Hi!
We are trying to create a chart with assistant nodes and multiple slinks but with the attached example the chart goes into error.
**There are two types of error.**

The **first one**, if you **add the first slink the chart is broken**

![image](https://user-images.githubusercontent.com/1867200/189129862-58e3f802-d36e-4d7d-9703-daea5679b3c9.png)

The second issue is reproduced when you **add the second slink** that show the **line that cross the nodes**.

![image](https://user-images.githubusercontent.com/1867200/189130216-12fdc297-1781-4573-a753-cbcec329c2c9.png)

https://jsfiddle.net/6c5bqw0g/

Can you take a look at it?

Thanks

**Comment by vingeek-dev** [comment]
@ZornitsaPesheva no info about this bug?

**Comment by ZornitsaPesheva** [comment]
I don't know, but it looks like the issue is resolved, because I can't reproduce it now:
![image](https://user-images.githubusercontent.com/19305472/192735985-62efdc42-7661-40ff-9e60-1d4e0663bc39.png)
