### ISSUE TITLE
Custom pid

### ISSUE THREAD

**Issue by mininglink** [BALKANGraph/OrgChartJS#69]
Hi Team

can we set a custom PID at init

currently we remove pid and that makes the node the  top parent, and i see in a recent question you can also drop a new pid in that does not exist, and it will create a second top level

can we just specify what the top parent is , this would also allow us to redraw the org chart with any node being to top parent

I haven't tried to implement yet, but its something thats been on the back of my mind for a while

**Comment by BALKANGraph** [comment]
good suggestion 

in the next version will add 
```
var new OrgChart(elem, {
...
  roots: [5, 29]
});
```

where 5 and 29 are ids of nodes

**Comment by plamen-peshev** [comment]
Version 4.5.7 support requested functionality

See demo - https://balkangraph.com/OrgChartJS-Demos/SetNodeAsRoot



![image](https://user-images.githubusercontent.com/49443821/56493139-cfa5e900-64f6-11e9-99fa-908b11a992a9.png)
