### ISSUE TITLE
Focused node

### ISSUE THREAD

**Issue by ovolvenkov** [BALKANGraph/OrgChartJS#690]

**Comment by ovolvenkov** [comment]
Good afternoon! This approach of adding focus to an element does not work for me. https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/Focus.
Can you tell me if there is another way to add focus to a specific node, so that later this focus can be used for keyboard navigation?

**Comment by ZornitsaPesheva** [comment]
Here is the doc page for keyboard navigation: https://balkan.app/OrgChartJS/Docs/KeyNavigation
You can see how we focus in the examples there.

**Comment by ovolvenkov** [comment]
Thank you! Yes, I have seen this opportunity. But I want to add focus in the code, after which the keyboard navigation should work from the selected element. Can you tell me how to add focus to an element in the code?

**Comment by ovolvenkov** [comment]
Hi, @ZornitsaPesheva. Do we have the opportunity to add focus to an appropriate element in the code?

**Comment by ZornitsaPesheva** [comment]
You can do this: https://jsfiddle.net/9rjgqwdo/

**Comment by ovolvenkov** [comment]
@ZornitsaPesheva Thanks, but I'm trying to add focus in this way, the focus appears, but immediately switches on the root node. Could this be related to the "enable KeyNavigation: true" parameter passed to the config?

**Comment by ZornitsaPesheva** [comment]
We have created this for you:
https://code.balkan.app/preview/org-chart-js/focus-node#JS

You need to download the latest version.

**Comment by ovolvenkov** [comment]
Thanks a lot for that idea. But we still have problems defining the focus depending on events. For instance, one more case when we need to focus on elements is the following: 
* When we show the structure element according to user search result
* When we want to add focus when specific nodes collapse
How can we solve that problem with a focused state?
Thanks in advance.

**Comment by ZornitsaPesheva** [comment]
Here is how you can do it:
https://code.balkan.app/org-chart-js/center-and-focus-on-search-click#JS

**Comment by ovolvenkov** [comment]
> Here is how you can do it: https://code.balkan.app/org-chart-js/center-and-focus-on-search-click#JS

Thanks this is exactly what I need!
