### ISSUE TITLE
field onclick event is not working in salesforce LWC

### ISSUE THREAD

**Issue by yuvrajnimje** [BALKANGraph/OrgChartJS#692]
adding an icon as field and when user clicks on it it should call a function but due to some reason it is not working
and if we use href inside anchor tag then it is redirecting to that link when user user click on button

chart.on('field', function (sender, args) {
            if (args.name == "taskIcon") {
                args.value = '<a onclick="testFunc();" href="javascript:void(0);"><image preserveAspectRatio="xMidYMid slice" xlink:href="{val}" x="10" y="90" width="20" height="20"></image></a>'.replace('{val}', args.data.taskIcon);
            }
        });

testFunc = function () {
            alert('second --- calling outside js method ');
        }

onclick of icon it should call testFunc but it is not doing anything

![Screenshot (133)](https://user-images.githubusercontent.com/92856342/190171367-4ad66e39-3a48-43ec-b20c-a34bb23e90fc.png)

**Comment by ZornitsaPesheva** [comment]
Here is how you can use click event on e field:
https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/ShowIdOnFieldClick

**Comment by yuvrajnimje** [comment]
var filedElements = document.querySelectorAll('.field_0');
 **OR**
 var filedElements = this.template.querySelectorAll(".field_0");
 
 This are not returning anything in LWC Salesforce
 they return undefined or return proxy and show following error
 
![Screenshot (135)](https://user-images.githubusercontent.com/92856342/190612857-8bb0c82b-65d6-470c-b1e7-527d0c15a7ab.png)

 Do we have any other way?

**Comment by yuvrajnimje** [comment]
Thanks For the reply
issue is resolved...
