### ISSUE TITLE
Duplicated ID break the chart

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [BALKANGraph/OrgChartJS#693]
Using duplicated value in the ID field break the chart

https://jsfiddle.net/vyshnav4u/8m6sLtjx/1/

Another valid scenario: using string for ID(eg; place name as ID)
https://jsfiddle.net/m9ob4u7c/

Currently, if we give duplicated ID, it is not properly handled, based on the different scenario charts is behaving differently, does this behavior is excepted? Should we handle this from our side by making ID unique, or is this a bug?

**Comment by ZornitsaPesheva** [comment]
You can not use duplicate Ids in Org Chart JS.
