### ISSUE TITLE
how to show tooltip when user hover on any field or image in salesforce LWC

### ISSUE THREAD

**Issue by yuvrajnimje** [BALKANGraph/OrgChartJS#694]
I have tried with following example but not working 

[https://balkan.app/OrgChartJS-Demos/TooltipMutilineOnMouseover.html](url)

I have also tried with below way but getting error like  [e.getBoundingClientRect is not a function]

![Screenshot (136)](https://user-images.githubusercontent.com/92856342/191472379-8f70ee21-1aad-4194-9153-fdc0b0fa0e29.png)

**Comment by ZornitsaPesheva** [comment]
You can try with these examples:
https://code.balkan.app/org-chart-js/simple-tooltip-on-a-field-hover
https://code.balkan.app/Preview/org-chart-js/tooltip-on-a-field-hover
https://code.balkan.app/Preview/org-chart-js/css-tooltip-on-a-field-hover
https://code.balkan.app/Preview/display-tooltip-in-the-correct-position

**Comment by yuvrajnimje** [comment]
Thanks Its working
