### ISSUE TITLE
Highlighted path to the node with focus

### ISSUE THREAD

**Issue by ovolvenkov** [BALKANGraph/OrgChartJS#696]
Please tell me if there are ways to highlight the path to the active node when used for focus "chart._keyNavigationActiveNodeId = nodeId;". 
![2022-09-23_12-32](https://user-images.githubusercontent.com/54061574/191942679-2ec2c2d8-556b-48f0-9883-3738b4cdb52b.png)

**Comment by ZornitsaPesheva** [comment]
You can try to use the code from this example: https://balkan.app/OrgChartJS-Demos/HighlightLeafToRoot.html

**Comment by ovolvenkov** [comment]
Thank you, but this option is not suitable for us, as we want to avoid using tags, and there is also an issue with overlapping links, links follow the same path for all nodes
![image_2022_09_22T15_31_42_959Z](https://user-images.githubusercontent.com/54061574/191958436-36bda19b-4606-4a98-8cbf-8616ee8d4108.png)

**Comment by ZornitsaPesheva** [comment]
You can set tags dynamically.
And the links are on the same level for all nodes. That's the normal behavior, if I understand your issue well.
Can you show us in a screenshot what would you expect?

**Comment by ovolvenkov** [comment]
Good afternoon! I'm trying to implement this feature based on your approach, but I get an error when clicking on one of the nodes:
"orgchart.js:1 Uncaught TypeError: Cannot assign to read only property '23' of object '[object Array]'
     at OrgChart.update(orgchart.js:1:1)
     at OrgChart.updateNode(orgchart.js:1:1)
     at highlight(addInitHandlers.ts:61:1)
     at Array.<anonymous> (addInitHandlers.ts:85:1)
     at Object.publish(orgchart.js:1:1)
     at OrgChart._nodeClickHandler(orgchart.js:1:1)
     at OrgChart._globalClickHandler(orgchart.js:1:1)
     at SVGSVGElement.r(orgchart.js:1:1)
     at SVGSVGElement.o(orgchart.js:1:1)"
![2022-09-25_12-28](https://user-images.githubusercontent.com/54061574/192139139-309183ee-796f-4a8a-ab84-b57d00c968c4.png)
Most likely the reason is in the data structure passed when creating the tree. When I add your simplified data structure to my code, everything works correctly. Tell me what could be the reason?

**Comment by ovolvenkov** [comment]
The error occurs in this method chart.updateNode(node);

**Comment by ZornitsaPesheva** [comment]
Could you please isolate issue in Code: https://code.balkan.app/orgchartjs/getting-started#JS

**Comment by ovolvenkov** [comment]
Thanks, but I figured out what was the reason, it was due to the fact that I had more than 200 nodes used. But I have another problem related to the layout of the tree at the deepest nodes. Tell me what could be the reason?

**Comment by ZornitsaPesheva** [comment]
The reason is that here we use an "hidden" template called **split** to make the tree view, so you will need to change the link definition of that template also.

**Comment by ovolvenkov** [comment]
Could you please show an example of redefining the relationship of the given split template

**Comment by ZornitsaPesheva** [comment]
OrgChart.templates.split.link = '<path stroke-linejoin="round" stroke="#aeaeae" stroke-width="1px" fill="none" d="{edge}" />';

**Comment by ovolvenkov** [comment]
Thank you, it turns out that in this way I can only statically override the color of the link, but I additionally need the logic to highlight the necessary links, since I cannot bind it to my custom template

**Comment by ovolvenkov** [comment]
![2022-09-27_16-06](https://user-images.githubusercontent.com/54061574/192548983-05e58b4f-e225-4b1f-8fc2-d5495c791b5a.png)

**Comment by ZornitsaPesheva** [comment]
I have created this example for you:
https://code.balkan.app/org-chart-js/highlight-parents-to-the-root-with-layout-orgchart.tree#JS
