### ISSUE TITLE
Drag & drop minimap

### ISSUE THREAD

**Issue by homko** [BALKANGraph/OrgChartJS#697]
Hi. Is it possible to apply the drag&drop feature to minimap?

**Comment by ZornitsaPesheva** [comment]
#687

**Comment by ZornitsaPesheva** [comment]
We will implement this also.

**Comment by ZornitsaPesheva** [comment]
We have implemented this in 8.06.00

**Comment by homko** [comment]
@ZornitsaPesheva , thanks a lot! Great!
