### ISSUE TITLE
Collapse all

### ISSUE THREAD

**Issue by ovolvenkov** [BALKANGraph/OrgChartJS#698]
Good afternoon. I want to implement a collapse all function so that absolutely all child elements are collapsed. Except level 1. I tried using your examples https://balkan.app/OrgChartJS-Demos/CollapseAll.html, https://balkan.app/OrgChartJS-Demos/ExpanCollapseToLevel.html. But the problem is that in all cases, the child elements remain open.
![2022-10-05_14-56](https://user-images.githubusercontent.com/54061574/194065556-f56061d9-4a99-4e1c-95b8-05c0783d333c.png)

**Comment by ZornitsaPesheva** [comment]
Try this:
https://code.balkan.app/Preview/org-chart-js/collapse-children-on-expand

**Comment by ovolvenkov** [comment]
Thanks, I'll try. Tell me more, please, can there be a method that will return the structure to its original state on the first load?

**Comment by ovolvenkov** [comment]
@ZornitsaPesheva  Thanks for the options, but in my case, all these options does not work. Tell me, can you have some kind of approach with recursion, during which all child elements were collapsed?

**Comment by ZornitsaPesheva** [comment]
You can see here how to iterate through nodes:
https://balkan.app/OrgChartJS/Docs/NodeAPI#iterate

If you are unable to do it yourself, please isolate your code and explain in steps with screenshot what you expect and why our example don't work for you.

**Comment by TOH2F** [comment]
Hello ovolvenkov what thé use ? Share IS ? Thank

**Comment by ZornitsaPesheva** [comment]
> Hello ovolvenkov what theme use ? Share here ? Thank

Here we have similar example: https://github.com/plamen-peshev/orgchartjs-templates/tree/main/Header

**Comment by TOH2F** [comment]
> > Hello ovolvenkov what theme use ? Share here ? Thank
> 
> Here we have similar example: https://github.com/plamen-peshev/orgchartjs-templates/tree/main/Header

hello, thank you but it is not complete yours seems more with the photo for example, is it possible to share?
Thanks in advance

**Comment by ZornitsaPesheva** [comment]
This is the code: https://github.com/plamen-peshev/orgchartjs-templates/blob/main/Header/template.js
