### ISSUE TITLE
Dynamically added content not present in PDF

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [BALKANGraph/OrgChartJS#699]
Hi, I'm dynamically adding some content to nodes once the chart is rendered, 
https://jsfiddle.net/vyshnav4u/kvsh5zoL/1/

In the fiddle I shared you can see, the exported PDF does not contain the dynamically added content, this is causing because my content is added inside an event (ie; after the chart is rendered I want to add additional content to the node), So is there any way we can include this dynamically added content in exported PDF?

**Comment by ZornitsaPesheva** [comment]
We have created an example on how to add your data dynamically:
https://code.balkan.app/dynamically-added-content-not-present-in-pdf#JS
Here is the doc page: https://balkan.app/OrgChartJS/Docs/Fields#link

**Comment by vyshnavmk-lumel** [comment]
Thanks
