### ISSUE TITLE
layout: BALKANGraph.mixed does not display properly nodes with same pid which don't have child nodes

### ISSUE THREAD

**Issue by mitkosoft** [BALKANGraph/OrgChartJS#7]
Within the latest release 3.7.4, nodes with the same pid which don't have child nodes are displayed vertically instead of horizontally on the same level:

`
template: "rony",
scaleInitial: BALKANGraph.match.boundary,
layout: BALKANGraph.mixed,
nodes: [{
		id: 1,
		name: "Denny Curtis",
		title: "CEO",
		img: "https://balkangraph.com/js/img/2.jpg"
	},
	{
		id: 2,
		pid: 1,
		name: "Ashley Barnett",
		title: "Sales Manager",
		img: "https://balkangraph.com/js/img/3.jpg"
	},
	{
		id: 3,
		pid: 1,
		name: "Caden Ellison",
		title: "Dev Manager",
		img: "https://balkangraph.com/js/img/4.jpg"
	},
	{
		id: 4,
		pid: 2,
		name: "Elliot Patel",
		title: "Sales",
		img: "https://balkangraph.com/js/img/5.jpg"
	},
	{
		id: 5,
		pid: 2,
		name: "Lynn Hussain",
		title: "Sales",
		img: "https://balkangraph.com/js/img/6.jpg"
	},
	{
		id: 6,
		pid: 3,
		name: "Tanner May",
		title: "Developer",
		img: "https://balkangraph.com/js/img/7.jpg"
	},
	{
		id: 7,
		pid: 3,
		name: "Fran Parsons",
		title: "Developer",
		img: "https://balkangraph.com/js/img/8.jpg"
	},
	{
		id: 8,
		pid: 1,
		name: "John Doe",
		title: "L1 Developer",
		img: ""
	},
	{
		id: 9,
		pid: 1,
		name: "Frank Black",
		title: "L1 Developer",
		img: ""
	},
	{
		id: 10,
		pid: 1,
		name: "Billy Idol",
		title: "L1 Developer",
		img: ""
	},
	{
		id: 11,
		pid: 1,
		name: "Jim Fox",
		title: "L1 Developer",
		img: ""
	},
	{
		id: 12,
		pid: 8,
		name: "Michael Bolton",
		title: "L2 Developer",
		img: ""
	}
]`

3.5.0 release:
![3 5 0](https://user-images.githubusercontent.com/16716343/50763336-3240e500-1278-11e9-9ee1-0c7d0c1d383a.png)

3.7.4 release:
![3 7 4](https://user-images.githubusercontent.com/16716343/50763348-3bca4d00-1278-11e9-8b4c-16577e55f3c7.png)

**Comment by BALKANGraph** [comment]
It is not an issue, it is feature requested by a customer 

If it is a showstopper for you we can implement a configuration setting for both layouts

**Comment by mitkosoft** [comment]
Hi,

Actually is a showstopper for us as in more complex tree the layout is not the desired one (as in 3.5.0) and actually takes more space. So it would be great to have such a setting available.

Thank you!

**Comment by mitkosoft** [comment]
Hello guys, I just want to check with you is there update/progress on this issue?

**Comment by ZornitsaSerbezova** [comment]
Hi Mitko!

Now we have OrgChart.mixed with MIXED_LAYOUT_ALL_NODES = false

The second example here: https://balkangraph.com/OrgChartJS/Docs/Layout

Regards,
Zornitsa
