### ISSUE TITLE
Disable zoom animation

### ISSUE THREAD

**Issue by mitkosoft** [BALKANGraph/OrgChartJS#70]
How can I disable completely zoom animation in order to achieve the old behaviour, like here: http://www.getorgchart.com/Demos ?

**Comment by BALKANGraph** [comment]
Will add it in the next version

```
new OrgChart(element, {
   zoom: null
});
```

**Comment by mitkosoft** [comment]
Just to clarify - I don't wanna disable the zoom completely, but just zoom animation, i.e. to be able to zoom in/out with fixed steps (as is on the demo I have provided).

**Comment by plamen-peshev** [comment]
thanks for the clarification

**Comment by mininglink** [comment]
@mitkosoft  you can zoom using  

chart.zoom([percentage as decimal to change]);

all you have to do is add the function to an event, like a button or keystrokes, I have done both

I have found that 1.2 is great for out, and 0.8 for in
