### ISSUE TITLE
UI is breaking after opening modal on onclick function

### ISSUE THREAD

**Issue by yuvrajnimje** [BALKANGraph/OrgChartJS#700]
I have to open modal or pop up on click of icon
but Ui is breaking after opening modal
and after closing modal nothing shown

I have attached screenshots and video for your reference

![Screenshot (163)](https://user-images.githubusercontent.com/92856342/196933338-b7c02a4e-54da-464e-932c-b9a6d3acacab.png)
![Screenshot (166)](https://user-images.githubusercontent.com/92856342/196933343-cdfe3789-7107-45d6-81dc-0c1fee7dc1c2.png)
![Screenshot (167)](https://user-images.githubusercontent.com/92856342/196933352-71bfd928-ede1-45c8-87cb-c5dc14e721fe.png)
[screen-recorder-thu-oct-20-2022-15-57-33.webm](https://user-images.githubusercontent.com/92856342/196933415-5a218f7a-752f-4ca7-b278-fec423cf4539.webm)

**Comment by ZornitsaPesheva** [comment]
Please isolate the issue in a simple example: https://code.balkan.app/orgchartjs/getting-started#JS

**Comment by yuvrajnimje** [comment]
[screen-recorder-thu-oct-20-2022-15-57-33.webm](https://user-images.githubusercontent.com/92856342/198993565-12391512-2d90-4397-8016-c51c76342062.webm)

**Comment by yuvrajnimje** [comment]
[screen-recorder-thu-oct-20-2022-15-57-33.webm](https://user-images.githubusercontent.com/92856342/198993662-a24d8072-6423-48fa-8d20-cb5664466a1c.webm)

**Comment by ZornitsaPesheva** [comment]
It looks like you are changing the data on clicking of this "Like" button, and the data is broken after this change.
You can log the new data this way:
```
console.log(chart.config.nodes) 
```

and create and example with it in [Code](https://code.balkan.app/orgchartjs/getting-started#JS), so we can check what is wrong with it.

**Comment by ZornitsaPesheva** [comment]
I'll close this issue as it looks inactive, Feel free to reopen if needed.
