### ISSUE TITLE
Remove Node and it's Child using Id

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [BALKANGraph/OrgChartJS#703]
Hi,
I want to remove node and all it's child nodes using Node id,
**removeNode()** can remove a single node, what I want is remove that node and all it's child nodes,

something similar like this, but on button click I want to remove node and it's child
https://balkan.app/OrgChartJS-Demos/RemoveOnNodeButtonClick.html

**Comment by ZornitsaPesheva** [comment]
Check if this is what you need: https://code.balkan.app/org-chart-js/remove-node-and-all-its-children#JS

**Comment by vyshnavmk-lumel** [comment]
Thanks @ZornitsaPesheva
