### ISSUE TITLE
Using slinks inside subtree

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [BALKANGraph/OrgChartJS#705]
Hi,
Using slink inside subtree causing overlaps issue, 
![image](https://user-images.githubusercontent.com/105709887/201289993-1796ab88-b7ef-4e0e-8cf7-c96c7bd7ec3d.png)

I saw other people having similar issue, and using clink is one possible fix for it.
So can we expect slink support inside the subtree any time soon, or is this the expected behavior?

**Comment by ZornitsaPesheva** [comment]
We don't support Slinks with subtrees, Please use Clinks.
