### ISSUE TITLE
Icon in Node based on Tag in Node

### ISSUE THREAD

**Issue by jkrische** [BALKANGraph/OrgChartJS#707]
Is it possible to show an icon in a node if an only if that node has a specific tag?  And, if that tag is present, direct the user to a calculated link?

For example:
nodes:
[
{"id": 0, "pid": "",  "title": "no-edit-box", "tags": ["template1", "noedit"]},
{"id": 1, "pid": "0", "title": "yes-edit-box", "tags": ["template1", "editable"], "path": "the.path.in.a.json"},
]

So, the goal would be that for both nodes, they use the same basic template.  However, Node ID 1 would have a small icon in the corner and, when the node is clicked, go to https://my.url.domain/?path={{path from node}}.  Node 0 would not be clickable and would not link anywhere.

Is this possible?

**Comment by ZornitsaPesheva** [comment]
It is possible, but the way to do it is to create another template (template2 for example) that inherits template1.

You should have this:
[
{"id": 0, "pid": "", "title": "no-edit-box", "tags": ["template1"]},
{"id": 1, "pid": "0", "title": "yes-edit-box", "tags": ["template2"], "path": "the.path.in.a.json"},
]

**Comment by jkrische** [comment]
I was afraid of that.  I've already got a few dozen template variations that would need alternates for the "yes edit" type.  Still, thanks!
