### ISSUE TITLE
Search Input Tag

### ISSUE THREAD

**Issue by ritik3007** [BALKANGraph/OrgChartJS#709]
![image (6)](https://user-images.githubusercontent.com/63714698/203983380-540d4d3d-b1c0-4bf6-b160-f62af1748a69.png)
Need help regarding the search input tag, I want to limit the characters to 60 characters, and also if the number of characters overflows I want to show them on the next line as it does when we use the textarea tag, but when tried using Textarea the search results were not visible.

**Comment by ZornitsaPesheva** [comment]
Hi, we will check if this is possible and will let you know.

**Comment by ihorkovalenko27** [comment]
1. In previous versions we can close search result list by click outside list, press escape, clean search input.
But now we can't do that, only with 'X' CTA. Can you fix it?
2. What stable version you recomend to use?

**Comment by ZornitsaPesheva** [comment]
We will add this option for search.
We recommend using the latest version

**Comment by plamen-peshev** [comment]
We have added OrgChart.SEARCH_CLOSE_RESULT_ON_ESCAPE_OR_CLICKOUTSIDE setting in the latest version, the default value is false if you set it to true it will work like as previous versions

Clear your browser cache and test [here](https://code.balkan.app/search-close-result-on-escape-or-clickoutside#JS)
