### ISSUE TITLE
attribute transform

### ISSUE THREAD

**Issue by wimpie3** [BALKANGraph/OrgChartJS#71]
Just upgraded to the latest version and now I'm getting Error: <g> attribute transform: Expected number, "matrix(1,0,0,1,null,null)" when expanding certain nodes. Worked fine in the past.

**Comment by wimpie3** [comment]
The error appears when I do a return true in the onExpCollClick function.

**Comment by BALKANGraph** [comment]
can you experience the same issue on [this js fiddle](https://jsfiddle.net/BALKANGraph/9cfye62w/)

**Comment by wimpie3** [comment]
That fiddle works. The problem is linked to this piece of code. When I remove it, the chart works. When I add it, I get the matrix error.

`	            onExpCollClick: function (sender, action, id) {
					var bgnode = sender.getBGNode(id);
					if (bgnode.isGroup) {
						if(action==BALKANGraph.EXPAND) {
							sender.expand(id, bgnode.childrenIds);
						}
						if(action==BALKANGraph.COLLAPSE) {		
							if (bgnode.parent) {
								ids = [];
								function collapseIds(n) {
									if (n) {
										for (var i = 0; i < n.childrenIds.length; i++) {
											ids.push(n.childrenIds[i]);
											collapseIds(sender.getBGNode(n.childrenIds[i]));
										}
									}
								}
								collapseIds(bgnode);
								sender.collapse(id, ids);
							}
						}		
					}
					chart.center(id);
				},`

**Comment by wimpie3** [comment]
@plamen-peshev The demo you created on https://balkangraph.com/JS/exp/155.html now shows the same error (see Chrome console)

**Comment by plamen-peshev** [comment]
[record_000001_New.zip](https://github.com/BALKANGraph/OrgChartJS/files/3128470/record_000001_New.zip)

I have tried to replicate the issue with https://balkangraph.com/JS/exp/155.html to no avail

I'm I missing something?

**Comment by wimpie3** [comment]
Yes you probably are missing something. Just open https://balkangraph.com/JS/exp/155.html with Chrome, press F12 to open the debugger, select Console on top. Click on the > next to Directors and you'll see the error appearing. **Error: <g> attribute transform: Expected number, "matrix(1,0,0,1,null,null)".**

**Comment by wimpie3** [comment]
Just checked, the latest version still has the problem.

**Comment by plamen-peshev** [comment]
I have modified the demo: https://balkangraph.com/JS/exp/155.html

Use
```
           onExpCollClick: function (sender, action, id) {
             var bgnode = sender.getBGNode(id);
                if (bgnode.isGroup && bgnode.collapsedChildrenIds.length > 0) {
                    sender.expand(id, bgnode.collapsedChildrenIds, function(){
                        sender.maximize(id);
                    });
                }
                return false;
            },
```


Note that the licensed version does not have this issue

**Comment by wimpie3** [comment]
Unfortunately it's not working. Once you expand the chart in the demo, there is no way to collapse the chart anymore - none of the buttons are working!

**Comment by plamen-peshev** [comment]
Yes you cannot collapse because of the onExpCollClick event handler

What exactly you want to achieve with that handler?

**Comment by wimpie3** [comment]
Close all children again. I've added
`if(action==OrgChart.COLLAPSE) {return true;}`
but that does not visually remove the children from the chart.

**Comment by ZornitsaSerbezova** [comment]
You don't need to use  onExpCollClick. There is no such error anymore.
