### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by maciejcichowskiinwedo** [BALKANGraph/OrgChartJS#710]
Hi, we have discovered that in edit form on fields that are displayed on node you can put html/script that would be executed on node click.

Example:
https://code.balkan.app/orgchartjs/gettingstarted#JS
Edit name on chosen node to: `<script>alert("hello")</script>`
Save and than click on edited node.

Best Regards
Maciej

**Comment by ZornitsaPesheva** [comment]
When I do this, I get this result:
![image](https://user-images.githubusercontent.com/19305472/205103044-019a8582-2c2d-4b77-97a3-3379b6619156.png)

**Comment by ZornitsaPesheva** [comment]
Please use this:
OrgChart.ESCAPE_HTML = true;
