### ISSUE TITLE
Search List Result

### ISSUE THREAD

**Issue by ihorkovalenko27** [BALKANGraph/OrgChartJS#712]
Hi, guys!

1. In previous versions we can close search result list by: click outside list, press escape, clean search input.
But now we can't do that, only with 'X' CTA. Can you fix it? Or how i can change this options?

2. What stable version you recommend to use?

**Comment by ZornitsaPesheva** [comment]
We will add this option for search.
We recommend using the latest version

**Comment by ihorkovalenko27** [comment]
Cool! Thanks for answers

**Comment by ihorkovalenko27** [comment]
But in ts this property has some issue: 
![image](https://user-images.githubusercontent.com/77886931/205307996-cae85d69-0e97-4437-9310-d553e56797f7.png)

**Comment by ZornitsaPesheva** [comment]
You need to update the .d.ts file also.

**Comment by ihorkovalenko27** [comment]
Thanks for help and answers!
