### ISSUE TITLE
Call Function in Custom OrgChart.template Template Literals

### ISSUE THREAD

**Issue by ninjadev118** [BALKANGraph/OrgChartJS#713]
I am using a custom template for my nodes. How can I call my own function inside the `OrgChart.template` template literals? I need to format numbers (in this case the `{val}`) a certain way before displaying them in the nodes.

```js
function formatNumber(num) {
    // Code to format number
    return result
}

// Need to call formatNumber() on the {val}
OrgChart.templates["blue"].amount= `<text style="font-size: 10px;" fill="${color}" x="100" y="30">{val}</text>`;

var chart = new OrgChart(document.getElementById("tree"), {
    template: 'blue',
    nodeBinding: {
        amount: 'amount',
    },
    // Other config options
});

chart.load(data);
```

**Comment by ZornitsaPesheva** [comment]
To change the value of the data before displaying it, you need to use the "field" event. 
Example: https://balkan.app/OrgChartJS/Docs/Fields#link

**Comment by ninjadev118** [comment]
> 

This does the trick, thanks.

**Comment by ninjadev118** [comment]
> To change the value of the data before displaying it, you need to use the "field" event. Example: https://balkan.app/OrgChartJS/Docs/Fields#link

Using the "field" event technically accomplishes what I want but is causing issues. It seems to be modifying the actual node data instead just modifying what is displayed. I am looking to only modify what is shown since I want to keep the original {val} unrounded and unformatted when used in future calculations.

**Comment by ZornitsaPesheva** [comment]
It is modifying the field data, but is is not modifying the source node data.
So you can get the original data from nodes.

**Comment by ninjadev118** [comment]
Got it, was a mistake on my part. Thanks again.
