### ISSUE TITLE
How can we manage height and width of org chart js?

### ISSUE THREAD

**Issue by viknarola21** [BALKANGraph/OrgChartJS#714]
I am unable to set height and width org chart js. I have setup the code as below.

var chart = new OrgChart(document.getElementById("tree"), {
          mouseScrool: OrgChart.action.none,
          nodeMouseClick: OrgChart.action.none,
          layout: OrgChart.layout.normal,
          orientation: OrgChart.orientation.top,
          mode: 'light',
          template: 'ula',
          enableDragDrop: false,
          enableSearch: false,
          interactive: true,
          enableTouch: false,
          zoom: {speed: 130, smooth: 10},
          keyNavigation:{
            focusId: 1
          },
          nodeBinding: {
            field_0: 'name',
          }
        });

chart.load([
    { id: 1, name: "Amber McKenzie" },
    { id: 2, pid: 1, name: "Ava Field" },
    { id: 3, pid: 1, name: "Peter Stevens" }
])

Please help me to set height and width of chart.

Thanks

**Comment by plamen-peshev** [comment]
you can easily set the width and the height with css

```
.my-chart {
    width: 700px;
    height: 500px;
}

```

Created [Code demo](https://code.balkan.app/org-chart-js/height-and-width#CSS) for you
