### ISSUE TITLE
Add Icon In Between Node Connecting Lines

### ISSUE THREAD

**Issue by ninjadev118** [BALKANGraph/OrgChartJS#715]
How can I add an icon in between the lines connecting the nodes? Attaching a screenshot of the lines I'm referring to, the red circle represents where I would like the icon.

![Capture](https://user-images.githubusercontent.com/104167707/206790354-ef8f1a1c-56b5-4812-b705-d63126163f07.PNG)

I believe the lines are defined in `["link"]` attribute in `OrgChart.templates["myTemplate"]["link"]` value. Thanks.

**Comment by ZornitsaPesheva** [comment]
Here is an example with such icon:
https://code.balkan.app/org-chart-js/custom-template-circle#JS

If this doesn't help, please give us an example of what you have in Code:
https://code.balkan.app/orgchartjs/getting-started#JS

**Comment by ninjadev118** [comment]
> Here is an example with such icon: https://code.balkan.app/org-chart-js/custom-template-circle#JS
> 
> If this doesn't help, please give us an example of what you have in Code: https://code.balkan.app/orgchartjs/getting-started#JS

I created a demo here:
https://code.balkan.app/demo-for-github#JS

How can I place an icon at the connecting point between the parent and the 3 child nodes? (Similar to the way done in your demo). Thanks.

**Comment by ZornitsaPesheva** [comment]
https://code.balkan.app/org-chart-js/icon-on-the-crossing-links#JS
