### ISSUE TITLE
save data to database once save button is clicked

### ISSUE THREAD

**Issue by aleresoftware** [BALKANGraph/OrgChartJS#717]
Hi there,
I am trying to update the changes data to database from user interface when the save button is clicked in the org chart. How can I achieve that? I am using Laravel.

Thank you. 
![balkanapp_save](https://user-images.githubusercontent.com/116687484/206957405-ba8d48bc-1665-434f-9d7a-6a890fcd8f93.PNG)

**Comment by ZornitsaPesheva** [comment]
Here we have Laravel example:
https://balkan.app/OrgChartJS/Docs/GitHub

**Comment by aleresoftware** [comment]
Thank you
