### ISSUE TITLE
Typo in documentation and source code

### ISSUE THREAD

**Issue by Panagiss** [BALKANGraph/OrgChartJS#718]
When going in the Edit form for a nod, on the bottom there is a message saying "Add more fileds" where the correct is "Add more fields". You will find it in the first picture of the section "Configure Edit Form".

Small typo there but is being displayed in the [documentation ](https://balkan.app/OrgChartJS/Docs/Edit) as well as in the source code (version=8.08.06)

**Comment by ZornitsaPesheva** [comment]
fixed
