### ISSUE TITLE
Custom group box

### ISSUE THREAD

**Issue by vmgm87** [BALKANGraph/OrgChartJS#72]
Hello Team,
How can I customize the size, position and properties of expanded and collapse group box?

Thanks!
Regards,
VG

**Comment by plamen-peshev** [comment]
If your group template is the default one, change 

`
OrgChart.templates.group_grey.size = [250, 120];`


Other properties that you can change are:

```
OrgChart.templates.group_grey.size = [250, 120];
OrgChart.templates.group_grey.groupPadding = [50, 10, 10, 10];
OrgChart.templates.group_grey.groupNodesSeparation = 10;
```

**Comment by vmgm87** [comment]
Thank you @plamen-peshev !
Do you know how can I change the color text  in the group box and edge color?
VG

**Comment by plamen-peshev** [comment]
[Here](https://balkangraph.com/OrgChartJS/Docs/CreatingCustomTemplate) is information how to customize the template

**Comment by vmgm87** [comment]
Thank you @plamen-peshev  :D
