### ISSUE TITLE
Use more than one template for a node.

### ISSUE THREAD

**Issue by ninjadev118** [BALKANGraph/OrgChartJS#722]
Is there a way to utilize more than one custom template for the same node? For example, if I wanted to separate the logic for the node background color from the field colors into different templates, is there a way to apply both to the same node? One alternative is to just create a new template with aspects of both, but that is not scalable for what I have in mind. Thank you.

In my demo [here](https://code.balkan.app/using-multiple-templates#JS), node id 2 currently has the `greenTemplate` applied, but I want to utilize `numberTemplate` too. If I have both in the `tags` array, only the first would apply.

**Comment by ZornitsaPesheva** [comment]
No, you cannot do that.
You need to create different templates for all the field colors also
You can think if it is possible to use [CSS ](https://balkan.app/OrgChartJS/Docs/CSSCustomization)in some cases.

**Comment by ninjadev118** [comment]
> No, you cannot do that. You need to create different templates for all the field colors also You can think if it is possible to use [CSS ](https://balkan.app/OrgChartJS/Docs/CSSCustomization)in some cases.

If I dynamically apply the CSS using examples in that link, the styles always gets removed as soon as the chart redraws. The redraw event seems to fire everytime I click "outside" of the chart, which I assume is intended but is there a way for me to proceed with using non-hardcoded CSS classes and have them persist (at least until the page is refreshed or some other user interventon)?

**Comment by ZornitsaPesheva** [comment]
Here is how to use CSS dynamically: https://code.balkan.app/org-chart-js/conditional-color#JS

**Comment by ninjadev118** [comment]
> Here is how to use CSS dynamically: https://code.balkan.app/org-chart-js/conditional-color#JS

Hi, as per the original title of the issue I am trying to apply CSS without having to add another template, since I have a different set of business circumstances that I'm using the templates for. At the moment, I am able to set the CSS by adding a class directly to the node, but the styling disappears as soon as the chart redraws, which happens every time I click outside of the diagram. Below is a rough idea of my current implementation.

```js

// Styling
.my-styling {
  fill: #f9423a;
  stroke: #f9423a;
}

// Custom template
OrgChart.templates[name].node = `<rect class="node-outer"></rect>

// Chart config
var chart = new OrgChart(document.getElementById("tree"), {
nodeMenu: {
        highlight: {
            onClick: this.onClickHighlightNode
        }
    },
});

// Event handler
onClickHighlightNode = (nodeId: string) => {
    let nodeE = this.chart.getNodeElement(nodeId);
    let nodeE1 = nodeE.querySelector(".node-outer");
    nodeE1.classList.add("my-styling");
```

**Comment by ZornitsaPesheva** [comment]
We have created this example for you: https://code.balkan.app/use-more-than-one-template-for-a-node#CSS
Here we don't use templates at all.
Using tags is not using templates.
