### ISSUE TITLE
PDF Offline Export issue

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [BALKANGraph/OrgChartJS#723]
Hi, When we are offline or our app does not permit external website access, PDF is not generating,
I noticed the pdf export function making some request to `https://balkan.app/export/v3`, So is it possible to generate pdf without depending external website?

**Comment by ZornitsaPesheva** [comment]
You can install your own export service following the instruction here:
https://github.com/BALKANGraph/export-service

**Comment by vyshnavmk-lumel** [comment]
Hi @ZornitsaPesheva , in above solution we need to pass `exportUrl` from a website, If our app does not support external web access, is there any way we can export pdf?

**Comment by ZornitsaPesheva** [comment]
You can install the export server on the app server.
There is no other solution.
