### ISSUE TITLE
Type for on event listener callback

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [BALKANGraph/OrgChartJS#724]
Hi can you provide the proper type for callback function's argument for `on`  event listener
https://balkan.app/OrgChartJS/API/classes/OrgChart#on-1
currently `args` have type `any`

**Comment by ZornitsaPesheva** [comment]
Please use these functions instead `on`:
https://balkan.app/OrgChartJS/API/classes/OrgChart#onAddNode
