### ISSUE TITLE
orgchart.js 8.09.24 (and 23) not listening to clicks

### ISSUE THREAD

**Issue by jkrische** [BALKANGraph/OrgChartJS#725]
We have a strange problem.  We have a bootstrap 4.5.x carousel of orgchart.js charts being displayed on a page in an iframe, which has worked fine for many months under orgchart version 7.x.  We recently updated to paid version orgchart.js 8.09.24 so we could add onNodeClick events, but all of the rest of our code is the same.

In some cases, the orgchart does not respond to any clicks at all - the zoom buttons do not work, the user cannot pan by click-dragging, and our onNodeClick event does not fire.  If I reload the iframe the charts are in, they work normally.  Sometimes the clicks work on the first load of a chart but not the second load.  Sometimes it does NOT work on the first load but does work on the second.  there is no relevant data being reported in the console.

Any ideas?

**Comment by ZornitsaPesheva** [comment]
Please isolate the issue in a simple code example:
https://code.balkan.app/orgchartjs/getting-started#JS
