### ISSUE TITLE
How can I custom expand/collapse button on the left and right of the node

### ISSUE THREAD

**Issue by guanzhuangxiaozi** [BALKANGraph/OrgChartJS#728]

**Comment by ZornitsaPesheva** [comment]
You need to move the plus/minus button on left or right?

**Comment by guanzhuangxiaozi** [comment]
I want to add one more relationship "Sibling", silmilar to Partner
https://balkan.app/OrgChartJS-Demos/Partner.html

But cannot show the plus/minus button on left or right of the node
![image](https://user-images.githubusercontent.com/10988180/220257186-720d4737-260a-4d7f-b39b-53a2eb123e49.png)

**Comment by guanzhuangxiaozi** [comment]
> You need to move the plus/minus button on left or right of the node?

yes

**Comment by ZornitsaPesheva** [comment]
We have created a Code demo for you:
https://code.balkan.app/org-chart-js/add-expand-collapse-button-for-partners#JS

**Comment by guanzhuangxiaozi** [comment]
> We have created a Code demo for you: https://code.balkan.app/org-chart-js/add-expand-collapse-button-for-partners#JS

many thanks @ZornitsaPesheva

**Comment by guanzhuangxiaozi** [comment]
> We have created a Code demo for you: https://code.balkan.app/org-chart-js/add-expand-collapse-button-for-partners#JS

for the partner node , can we also add plus/minus button on bottom?

**Comment by ZornitsaPesheva** [comment]
Here is a code demo using subtrees:
https://code.balkan.app/org-chart-js/partner-of-a-partner#JS

**Comment by guanzhuangxiaozi** [comment]
> Here is a code demo using subtrees: https://code.balkan.app/org-chart-js/partner-of-a-partner#JS

many thanks

**Comment by guanzhuangxiaozi** [comment]
> Here is a code demo using subtrees: https://code.balkan.app/org-chart-js/partner-of-a-partner#JS
excuse me ,one last question
https://code.balkan.app/org-chart-js/add-expand-collapse-button-for-partners#JS
https://code.balkan.app/org-chart-js/partner-of-a-partner#JS

shall we can combine these two demo to implement like this
![image](https://user-images.githubusercontent.com/10988180/220860375-578c9827-2468-42ff-80ff-da46463b57b9.png)

**Comment by ZornitsaPesheva** [comment]
https://code.balkan.app/org-chart-js/partner-of-a-partner#JS
With the children of the most right partner it become too complicated, because it is in a subtree.
If it is possible to be done as in the screenshot, it will be very custom solution.

**Comment by guanzhuangxiaozi** [comment]
> https://code.balkan.app/org-chart-js/partner-of-a-partner#JS With the children of the most right partner it become too complicated, because it is in a subtree. If it is possible to be done as in the screenshot, it will be very custom solution.

noted it, many thanks @ZornitsaPesheva

**Comment by guanzhuangxiaozi** [comment]
> We have created a Code demo for you: https://code.balkan.app/org-chart-js/add-expand-collapse-button-for-partners#JS

after I try revise the 
```
chart.load(
[
    { id: "1", name: "Denny Curtis" },
    // { id: "2", pid: "1", name: "Ashley Barnett" },
    // { id: "2.1", pid: "2", name: "Ashley Barnett",tags: ['left-partner','ig1'] },
    // { id: "2.5", stpid: "2.1", name: "partner node" },
    // { id: "2.3",pid:"2.5"},
    // { id: "2.4",pid:"2.5"},
    // { id: "2.10", pid: "2", name: "Ashley Barnett",tags: ['left-partner','ig1'] },
    // { id: "2.7", stpid: "2.10", name: "partner node" },
    //  { id: "2.8",pid:"2.7"},
    // { id: "2.9",pid:"2.7"},
    // { id: "3", pid: "1", name: "Caden Ellison" },
    { id: "4", pid: "1", name: "Right Partner 1", tags: ['right-partner','ig'] },
    { id: "5", pid: "1", name: "Right Partner 2", tags: ['right-partner','ig'] },
    { id: "6", pid: "1", name: "Left Partner 1", tags: ['left-partner'] },
    { id: "7", pid: "1", name: "Left Partner 2", tags: ['left-partner'] },
    { id: "14", stpid: "4", name: "partner node" },
    { id:"8",pid:"14"},
    { id:"9",pid:"14"},
    { id: "15", stpid: "5", name: "partner node" },
    { id:"10",pid:"15"},
    { id:"11",pid:"15"},
]
```
I can't see the expand/collapse button @ZornitsaPesheva 
![image](https://user-images.githubusercontent.com/10988180/234524571-ee8ffb95-07c4-48a0-b4cf-5d7ea139846d.png)

**Comment by ZornitsaPesheva** [comment]
It does not work because "Denny Curtis" does not have "regular" children.
![image](https://user-images.githubusercontent.com/19305472/234884100-52351725-f8dc-426f-a9f2-684a69c41071.png)
