### ISSUE TITLE
I want to make a node visible or not based on a value of a field that I give it

### ISSUE THREAD

**Issue by charbelnaser** [BALKANGraph/OrgChartJS#729]
I want to make a node visible or not based on the value of a field that I give him

**Comment by ZornitsaPesheva** [comment]
Did you check filters?
https://code.balkan.app/org-chart-js/filter-dot#JS

**Comment by charbelnaser** [comment]
The idea that I am importing an excel sheet and there are nodes that I want to be invisible all time not based on filter condition

**Comment by ZornitsaPesheva** [comment]
Please give a simple example of such data and a screenshot of how you'd like to see it in the chart.

**Comment by charbelnaser** [comment]
</head>
<body>
   <div id="tree"></div>

    <script>
		var chart = new OrgChart(document.getElementById("tree"), {
				nodeBinding: {
					field_0: "name"
				},
				nodes: [
					{ id: 1, name: "Amber McKenzie",visible:true },
					{ id: 2, pid: 1, name: "Ava Field" ,visible:false},
					{ id: 3, pid: 1, name: "Peter Stevens", visible:true }  
				]
			});

      
    </script>
</body>
</html>
This is a sample html , for example I want the node with id 2 To be invisible without remove it. I am putting the property visible:false but its not working

**Comment by charbelnaser** [comment]
I hope you understand me bro , if no please tell me

**Comment by charbelnaser** [comment]
I hope you did understad me bro, If no please tell me

**Comment by ZornitsaPesheva** [comment]
Hidden as collapsed or hidden as in filters?

**Comment by charbelnaser** [comment]
<img width="351" alt="Capturehhhh" src="https://user-images.githubusercontent.com/88190347/220687622-5a144d4b-4345-46a5-b9f8-66f0f70baa5f.PNG">
I onlu want to to see 2 NODES that with id =1 and id =3 where visible=True

**Comment by ZornitsaPesheva** [comment]
I have created this example for you:
https://code.balkan.app/org-chart-js/collapse-nodes-where-visible-is-false#JS

**Comment by charbelnaser** [comment]
First of All thank you for your help,much appreciate it, it very nice but there is solution to remove the cross button that give u the opportunity to expand?

**Comment by ZornitsaPesheva** [comment]
You can just delete the elements from the array

**Comment by charbelnaser** [comment]
okey but How to delete the elements after I import the csv

**Comment by ZornitsaPesheva** [comment]
https://code.balkan.app/org-chart-js/delete-nodes-when-visible-is-false#JS

**Comment by charbelnaser** [comment]
Thanx bro it work fine thank you a lot
