### ISSUE TITLE
Export service does not export foreignObjects in nodes

### ISSUE THREAD

**Issue by notarnet** [BALKANGraph/OrgChartJS#73]
Hi,
I added dynamic content to nodes as suggested in your docs example:
[Node HTML fields](https://jsfiddle.net/BALKANGraph/6uapb1yz/?utm_source=website&utm_medium=embed&utm_campaign=6uapb1yz)

If I export the graph, html content in foreign objects is not exported.

Please support this feature, we really need to export the whole node content.

**Comment by plamen-peshev** [comment]
added this issue as a bug and will be resolved in one of the following releases

**Comment by plamen-peshev** [comment]
The issue has been addressed 

https://balkangraph.com/js/exp/73.html

**Comment by notarnet** [comment]
Hi,
the issue is not fixed in our use case.
Please, see the code of the following example:
[StackBlitz: Orgchart Export](https://stackblitz.com/edit/angular-balkangraph-export-problem)

**Comment by plamen-peshev** [comment]
@notarnet the foreignObjects in your app are exported but they are empty

How you set the values in the container?

![image](https://user-images.githubusercontent.com/49443821/56220372-02705d00-6071-11e9-943b-d132857ed748.png)

**Comment by notarnet** [comment]
The code that fills containers divs is in the method **onRedraw** of the file charter.component.ts

**Comment by plamen-peshev** [comment]
onRedraw is not called on export

replace nodeBinding with:

```
       nodeBinding: {
          field_0: "name",
          field_1: "title",
          img_0: "img",
          field_number_children: "field_number_children",
          container: function(sender, node){
             var comp1 = document.getElementById("component_" + node.id);
            return '<foreignobject x="10" y="120" width="280" height="70"><div class="container" id="container_' + node.id + '">' + comp1.innerHTML+ '</div></foreignobject>';
          }
        },
```

and remove onRedraw

**Comment by notarnet** [comment]
The following example explains better our implementation with Angular components:
[Example](https://stackblitz.com/edit/angular-balkangraph-export-problem)

In the second chart, nodes embed Angular components that emit events on button click, but to do this I can't use the way you suggested in the previous answer.

**Comment by notarnet** [comment]
Any news?

**Comment by plamen-peshev** [comment]
onRedraw event is not called on export, you can use onExportStart instead 

See https://balkangraph.com/OrgChartJS-Demos/SearchAPI

**Comment by notarnet** [comment]
It works, thanks
