### ISSUE TITLE
Adding a Node SVG Field on conditional

### ISSUE THREAD

**Issue by megan-portelli** [BALKANGraph/OrgChartJS#730]
I would like to add a Node SVG Field to a node based on whether or not a field meets a certain condition. This is what I am doing so far. The actual field name has been changed to protect confidential data. Assuming that boolean is a field available in the data for the chart, is this the correct way of testing whether field1 contains a certain string and if it does the value of the field is changed and a Node SVG Field is added to just a single node in the organizational chart?

```
 var chart = new OrgChart(document.getElementById("orgchart"), {
            nodeBinding: {
                field_0: "name",
		field_1: "title",
		img_0: "img",
		boolean: field_1.includes(" TEST ")
            },
```

**Comment by ZornitsaPesheva** [comment]
You need to use the "field" event to do this:
Here is an example for using that event:
https://code.balkan.app/org-chart-js/hyperlink#JS
