### ISSUE TITLE
Horizontal Line for specific Siblings nodes

### ISSUE THREAD

**Issue by ALBPROG** [BALKANGraph/OrgChartJS#732]
Hello,

 Currently, I am working on a project for my Analytics team building a flip chart. Everything is working well, except for connecting specific siblings with a horizontal line.

I would like to achieve something similar to the screenshot below:
https://user-images.githubusercontent.com/18540115/221953659-0a5eb862-6590-4534-a32d-42e0db14156d.jpg

However, when I use the flip chart, the tags: ["assistant"] do not work. I have tried to code it myself, but unfortunately, nothing seems to work. Can anyone help me with this issue? Is there any other method, function, tag, etc. that I can use to build the chart?

I have saved the the code here: https://code.balkan.app/horizontal-lines-for-specific-siblings#JS

How can I create horizontal lines for specific siblings? Is any method, function, tag or anything else to solve this issue? 

Thank you

**Comment by ZornitsaPesheva** [comment]
I think we have fixed the issue and your code is also fixed.
