### ISSUE TITLE
Can we show multiple family tree in the same page

### ISSUE THREAD

**Issue by guanzhuangxiaozi** [BALKANGraph/OrgChartJS#733]
refer to :
https://balkan.app/OrgChartJS-Demos/RoyalFamilyTreeGroups.html

**[Expected Result]**
![image](https://user-images.githubusercontent.com/10988180/222349187-c1b658bd-11aa-4247-b783-9bd41533bb65.png)

**Comment by ZornitsaPesheva** [comment]
Here is a code demo: https://code.balkan.app/family-tree-js/two-trees-in-one-chart#JS
