### ISSUE TITLE
Exporting large Org Structure into a printable format

### ISSUE THREAD

**Issue by rvanacke** [BALKANGraph/OrgChartJS#734]
Hi there,

  We have a licensed version of OrgChart JS and are able to export our Org Chart based on the documentation.  The problem is that our org structure is so large, it becomes unusable/unprintable once exported.  Similar to this example:
[https://jsfiddle.net/BALKANGraph/sdwpeu04/3/]

What I am looking for is a way to be able export our very large org chart into a printable format, ideally a multipage format, with an individual node of each level on a discrete page, showing just the nodes of the level below them.  Is there a way to recursively do this? 

Maybe by hiding/showing nodes to produce a multipage export?

Any help is greatly appreciated.

**Comment by ZornitsaPesheva** [comment]
You can do multiple exports like this one:
https://code.balkan.app/org-chart-js/export-pdf-a4-for-a-node#JS
