### ISSUE TITLE
Can we link the same node which belong to different parent node

### ISSUE THREAD

**Issue by guanzhuangxiaozi** [BALKANGraph/OrgChartJS#735]
Like this :
https://jsfiddle.net/gh/get/library/pure/BALKANGraph/orgchartjs-demos/tree/master/ConnectiongNodesWithInvisibleRoot

if "Lynn Hussain" also belong to "Caden Ellison" and "Ashley Barnett", can we link as below :
![图片](https://user-images.githubusercontent.com/10988180/222610860-42d2e866-143d-4039-a32b-00bf7aa03116.png)

**Comment by ZornitsaPesheva** [comment]
In this case you can use slinks or clinks to connect both nodes.
Here is a more complex demo for matrix management if this is what you need to achieve:
https://code.balkan.app/org-chart-js/matrix-management#CSS
