### ISSUE TITLE
Get chart level details

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [BALKANGraph/OrgChartJS#738]
Hi, How can we get the chart level details,

eg; below chart has 5 level
![image](https://user-images.githubusercontent.com/105709887/224131941-83c4e9ce-4481-49fb-8226-e442e9961dd8.png)

We can get individual node level from chart.node.level, similar to this is there chart level info in chartIsntance?

**Comment by ZornitsaPesheva** [comment]
Here is a code demo:
https://code.balkan.app/org-chart-js/node-levels#JS

**Comment by vyshnavmk-lumel** [comment]
Thanks @ZornitsaPesheva
