### ISSUE TITLE
Dynamically change the template on export?

### ISSUE THREAD

**Issue by rvanacke** [BALKANGraph/OrgChartJS#739]
Wondering if it is possible to apply a different template to ONLY the exported chart.  Essentially, I would like to have a 'display' chart, and a 'print' chart, which are the exact same chart, just using a different template.  We are using the 'luba' template for our display/interactive org chart, however it would be ideal to be able to switch to the 'base' template on export so that when printed it is using a light theme, which is better for print.

Any idea if this is possible?  Would I have to create a 2nd chart instance with the 'base' template and then destroy it after printing, or can I dynamically change the template of the display/luba chart prior to export??

Any help is greatly appreciated!

**Comment by ZornitsaPesheva** [comment]
Here is a code demo: https://code.balkan.app/org-chart-js/change-template-on-export#JS

**Comment by rvanacke** [comment]
Excellent - thanks for all your help and support Zornitsa!
