### ISSUE TITLE
How to detect if Chart is performing redrawing or animations?

### ISSUE THREAD

**Issue by notarnet** [BALKANGraph/OrgChartJS#74]
Hi, I need to know when the chart is "idle" to perform a redrawing;
When I call chart.draw(), the chart is still executing another redrawing/animation and the result is that the chart pans in a random zone...

**Comment by plamen-peshev** [comment]
can you please share your code or create a demo in jsfiddle

**Comment by ZornitsaSerbezova** [comment]
I'll close this one. You can open it again, if you need.
