### ISSUE TITLE
How can we add custom HTML to PDF export

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [BALKANGraph/OrgChartJS#740]
Hi I'm trying to add custom html to PDF,

I was able to achieve this by appending **args.content** in **onExportStart** event
https://jsfiddle.net/b10g2prk/

but the issue is when html markup height increase it make chart disappear
https://jsfiddle.net/b10g2prk/1/

Is there any better way to add html markup to PDF or is there any fix for this issue?

**Comment by ZornitsaPesheva** [comment]
here is a code demo:
https://code.balkan.app/organizational-chart/export-custom-html-to-pdf#JS

**Comment by vyshnavmk-lumel** [comment]
@ZornitsaPesheva  In above demo the html overlap with the chart, I want to add  HTML either above the or below of the chart,
from the demo you shared if I remove the position: absolute the issue I'm initially having also occur here.
please see the demo
https://jsfiddle.net/569sv3xq/

**Comment by ZornitsaPesheva** [comment]
You can add header and footer:
https://code.balkan.app/orgchartjs/add-header-and-footer#JS

**Comment by vyshnavmk-lumel** [comment]
Hi @ZornitsaPesheva, https://code.balkan.app/org-chart-js/export-date-in-header#JS this solution partially worked for me, instead of hardcoding marginTop to create space in top I used clientHeight of the element, but the problem  some part of html is cutted of because of the lack of space,
https://jsfiddle.net/bum7h6sy/

I have added some constant TOP_OFFSET to fix that problem, but if the html content height increases same issue occur
https://jsfiddle.net/bum7h6sy/2/

**Comment by ZornitsaPesheva** [comment]
Looks like the whole HTML is exported here:
https://code.balkan.app/org-chart-js/add-html-to-pdf-export#HTML
![image](https://user-images.githubusercontent.com/19305472/225285725-66bd26b1-fcc2-4fc2-8f75-6ddd6526adec.png)

**Comment by ZornitsaPesheva** [comment]
You can try to add another page on export:
https://code.balkan.app/org-chart-js/add-page-on-export#HTML

**Comment by vyshnavmk-lumel** [comment]
Hi @ZornitsaPesheva, the last solution was also not worked for me, so I ended up adjusting margin top based on some static values, In any one future updates is it possible to add API for adding content in top and bottom of PDF like the header and footer?

**Comment by ZornitsaPesheva** [comment]
Basically we have header and footer, but they are made for adding small elements. 
We will try to figure out why it is not working with big elements

**Comment by ZornitsaPesheva** [comment]
Hi! Can you tell me why adding a page here was not working for you?
