### ISSUE TITLE
Not Importing Excel Sheet with 4000 row

### ISSUE THREAD

**Issue by charbelnaser** [BALKANGraph/OrgChartJS#744]

**Comment by charbelnaser** [comment]
Can you give me please more info how to send it to support@balkan please

**Comment by ZornitsaPesheva** [comment]
Please zip the csv file and send it as attachment in an email with information that you cannot import it.
Basically, you shouldn't have issue, as Org Chart JS works well with 100k nodes.

**Comment by charbelnaser** [comment]
Done, thank you
