### ISSUE TITLE
CORS Issue Accessing Balkan-Hosted OrgChart.js

### ISSUE THREAD

**Issue by ninjadev118** [BALKANGraph/OrgChartJS#745]
I've been using a licensed version of Balkan OrgChart for a while now and have never encountered the issues. However, today when building my solution locally, my version of OrgChart seems to be behaving like the trial version (sending a HTTP request to Balkan) and it throws a CORS error when it fails.

I've made no changes to my web server's API CORS policy or even any changes in the JavaScript code. Attaching errors.

```
Access to XMLHttpRequest at 'https://ca-balkangraph.azurewebsites.net/api/OrgChartJS' from origin 'https://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
GET https://ca-balkangraph.azurewebsites.net/api/OrgChartJS net::ERR_FAILED 500 (Internal Server Error)

Access to XMLHttpRequest at 'https://eus-2-balkangraph.azurewebsites.net/api/OrgChartJS' from origin 'https://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
GET https://eus-2-balkangraph.azurewebsites.net/api/OrgChartJS net::ERR_FAILED 500 (Internal Server Error)
```

**Comment by plamen-peshev** [comment]
Now it should work, we had temporary problem

**Comment by ZornitsaPesheva** [comment]
Also it looks like you are using the trial version.
You need to do download the licensed version from your account.

**Comment by ninjadev118** [comment]
I uninstalled the package and reinstalled via NPM, and then replaced orgchart.js with a newly downloaded licensed one from your site. I am no longer having the evaluation message come up, but `console.log(OrgChart.isTrial())` is still displaying `true` for me.

**Comment by ZornitsaPesheva** [comment]
Please use the downloaded package installation instructions:
https://balkan.app/OrgChartJS/Docs/Angular#install

**Comment by ninjadev118** [comment]
`isTrial()` still showing true for both npm installation and the local installation in assets

**Comment by ninjadev118** [comment]
It resolved itself on it's own after some time--could've been a cache issue after installing Balkan locally. Thanks
