### ISSUE TITLE
Provide link to node?

### ISSUE THREAD

**Issue by kieranparsons** [BALKANGraph/OrgChartJS#746]
I would like to be able to provide URLs to users (eg in email) that they would click and be brought to a specific highlighted node (maybe even with highlighting the reporting chain like https://balkan.app/OrgChartJS/Demos/highlight). And to provide these links in the nodes so that they can be copied by users to email to others (eg via context menu). Is there a way to do this? Thanks.

**Comment by ZornitsaPesheva** [comment]
You can pass the node id in the url and then you can do chart.center(id) on init:
https://code.balkan.app/org-chart-js/center-a-node-on-load#JS
or you can use state: https://balkan.app/OrgChartJS/Docs/State

You can add whatever you need in the node.
Here is how to add a hyperlink: https://balkan.app/OrgChartJS/Docs/Fields#link
If you are unable to achieve what you need, please send us more details on our email and we will help you.
