### ISSUE TITLE
Visual Studio Code

### ISSUE THREAD

**Issue by flyingwithit** [BALKANGraph/OrgChartJS#747]
Hi! 
Is there any way that You can make documentation how to make OrgChartJS with ActiveDirectory database in **Visual Studio Code?**

Thank You!

**Comment by ZornitsaPesheva** [comment]
This what we have for AD:
https://www.youtube.com/watch?v=iL8sqQgLy4Q&feature=em-lsb-owner
https://github.com/plamen-peshev/ActiveDirectory
You can also see the other ASP.NET server side examples that are more updated:
 https://balkan.app/OrgChartJS/Docs/GitHub
