### ISSUE TITLE
Chart moving to the right when i click anywhere on the chart(except the node)

### ISSUE THREAD

**Issue by joshuacos1977** [BALKANGraph/OrgChartJS#748]
I have created fully functional Org-chart with a database connection,but i came across an issue when i click anywhere on the chart (except the nodes) ,chart is moving to the right with every click on the browser window.

**Comment by ZornitsaPesheva** [comment]
Please isolate the issue in a simple example here:
https://code.balkan.app/org-chart-js/simple-example#JS

**Comment by joshuacos1977** [comment]
My code base is on react.I don’t think I can isolate the issue.But I can send you a screnshoots.
Is there any build-in function to prevent the issue?
Here is the issue on the UI:
https://share.vidyard.com/watch/K4yAVsWXrHNhqdy4V5QLHw?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ZornitsaPesheva** [comment]
I cannot reproduce that issue in a simple React project.

Start with following our React instruction:
https://balkan.app/OrgChartJS/Docs/React
Then add your code piece by piece and you will find what is causing the issue.

**Comment by joshuacos1977** [comment]
Okay.Thank you for your input.
