### ISSUE TITLE
Horizontal center align issue

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [BALKANGraph/OrgChartJS#750]
If graph have multiple root node, it is not horizontally center aligned
![image](https://github.com/BALKANGraph/OrgChartJS/assets/105709887/941dcf6b-c648-4e62-8c42-657cc5fbe972)

https://jsfiddle.net/46myha1L/3/

**Comment by ZornitsaPesheva** [comment]
You can try using these functions to center the chart:
[chart.center(id)](https://balkan.app/OrgChartJS/API/classes/OrgChart#center)
[chart.fit()](https://balkan.app/OrgChartJS/API/classes/OrgChart#fit)

or you can use this property:
[scaleInitial:OrgChart.match.boundary](https://balkan.app/OrgChartJS/Docs/Layout#matchboundary)

You can also try the `[align ](https://balkan.app/OrgChartJS/API/interfaces/OrgChart.options#align)`property.

**Comment by vyshnavmk-lumel** [comment]
Thanks @ZornitsaPesheva
