### ISSUE TITLE
Type for Orgchart.roots

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [BALKANGraph/OrgChartJS#752]
Hi can you please add type for chartInstance.roots?

**Comment by ZornitsaPesheva** [comment]
Where did you get this?
May be you need chart.config.roots?

**Comment by vyshnavmk-lumel** [comment]
![image](https://github.com/BALKANGraph/OrgChartJS/assets/105709887/7aa2b27d-8d98-4b01-b05c-d5ed239a0413)

**Comment by ZornitsaPesheva** [comment]
Why do you need this?

**Comment by vyshnavmk-lumel** [comment]
@ZornitsaPesheva  chart.config.roots return null not the root node

![image](https://github.com/BALKANGraph/OrgChartJS/assets/105709887/5b296b70-2aaa-46de-944f-cf75fd755130)

https://jsfiddle.net/61hypsg2/1/

**Comment by ZornitsaPesheva** [comment]
If you have only one root: https://balkan.app/OrgChartJS/Docs/NodeAPI#root

**Comment by vyshnavmk-lumel** [comment]
@ZornitsaPesheva above method is costly, I can get all active root node from that chart.roots, so is there any issue using it?

**Comment by ZornitsaPesheva** [comment]
With the above method you get the root of a specific node.
