### ISSUE TITLE
Photo not showing on node menu

### ISSUE THREAD

**Issue by adanschool** [BALKANGraph/OrgChartJS#753]
The photo is not showing on node menu, it only appears the stock gray icon to photo instead. 

I upload image to illustrate the problem.

![img](https://github.com/BALKANGraph/OrgChartJS/assets/90798963/a7e3bc65-c3f5-4f03-a4bf-542f5f170fcc)

**Comment by ZornitsaPesheva** [comment]
You need to bind it:
```
    editForm:{
        photoBinding: 'Photo'
    },
```

**Comment by adanschool** [comment]
Great, that's worked!!!

Thanks Mate!!!
