### ISSUE TITLE
conditional color

### ISSUE THREAD

**Issue by joshuacos1977** [BALKANGraph/OrgChartJS#757]
I want to apply conditional color to the chart,so I loop through the nodes as it is suggested:
for (var i = 0; i < chart.nodes.length; i++) {
            var node = chart.nodes[i];
            switch (node.title) {
                case "CTO":
                    node.tags = ["CTO"];
                    break;
                case "Marketer":
                case "Designer":
                case "Sales Manager":
                    node.tags = ["Marketing"];
                    break;
            }
        }
but i have issue to fill the node with a desired color.so i implemented like below:
  OrgChart.templates.olivia.node =
            '<rect class="CTO" fill="#F57C00"></rect>';
But didn't work out.

**Comment by ZornitsaPesheva** [comment]
I have sent you email,
Here is a code demo:
[Conditional Color - Org Chart JS (balkan.app)](https://code.balkan.app/org-chart-js/conditional-color#JS)

1.	Loop to add tags - [Conditional Color - Org Chart JS (balkan.app)](https://code.balkan.app/org-chart-js/conditional-color#JS)
2.	Add CSS - [Conditional Color - Org Chart JS (balkan.app)](https://code.balkan.app/org-chart-js/conditional-color#CSS)

**Comment by ZornitsaPesheva** [comment]
You can use different templates:
https://balkan.app/OrgChartJS/Docs/Tags

**Comment by joshuacos1977** [comment]
I don't have tags field on my JSON data.
still doesn't render based on title

**Comment by joshuacos1977** [comment]
i implemented css style  like below:
#tree{
    background-color:aqua;
}
.node.CEO rect {
    fill: #F57C00;
}

.node.CFO rect {
    fill: #039BE5;
}

.node.COO rect {
    fill: #FFCA28;
}
it changes only tree's background but doesn't style the nodes

**Comment by joshuacos1977** [comment]
Where does .nodes class defined as html  is 
<script src="https://balkan.app/js/OrgChart.js"></script>
<div id="tree"></div>

**Comment by ZornitsaPesheva** [comment]
You don't need to have tags. As you can see in the example, tags are added dynamically.
You cannot change the nodes color conditionally without using tags.

**Comment by joshuacos1977** [comment]
I have used tags it is just doesn’t work out inside  react useEffect hook which mount the UI once UI rendered.
I have css also
#tree{
    background-color:aqua;
}
.node.CTO rect {
    fill: #F57C00;
}

.node.CEO rect {
    fill: #039BE5;
}

.node.CFO rect {
    fill: #FFCA28;
}
When I remove  .CTO it fills the node desired color but not conditionally it fill out the all nodes with the same color.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ZornitsaPesheva** [comment]
We don't have React developers as we don't use frameworks.
Is it possible to not use useEffect? Why do you need it?

**Comment by joshuacos1977** [comment]
I was going to color each nodes based on the user’s title

Sent from my iPhone

On Jul 5, 2023, at 7:09 AM, ZornitsaPesheva ***@***.***> wrote:

﻿

We don't have React developers as we don't use frameworks.
Is it possible to not use useEffect? Why do you need it?

**Comment by ZornitsaPesheva** [comment]
Okay, but you don't need useEffect to do that.

**Comment by ZornitsaPesheva** [comment]
Can you give me a simple example of using useEffect for loading the chart?

**Comment by ZornitsaPesheva** [comment]
I am closing this issue as inactive. Please feel free to open it if you still need help.
