### ISSUE TITLE
Is this possible to connect any other database by ASP.NET?

### ISSUE THREAD

**Issue by flyingwithit** [BALKANGraph/OrgChartJS#758]
Hi! Is this possible to connect any other database than Active Directory, for example Microsoft Power BI or SAP? Or server implementation is only made by architecture for AD connection?

**Comment by ZornitsaPesheva** [comment]
Org Chart JS is plain JavaScript that works in the browser. You can use it with any backend you want.
Here we have some server side examples:

**Comment by flyingwithit** [comment]
@ZornitsaPesheva Is there possibility of consultation on webcall.me? Im calling and no answer :(

**Comment by ZornitsaPesheva** [comment]
Hi, currently we have an issue with webcall.me, but you can write on our email any time. We are trying to answer asap.
