### ISSUE TITLE
link web page to img_0

### ISSUE THREAD

**Issue by c3jack** [BALKANGraph/OrgChartJS#76]
Can I assign a web link like http://xxx.xxx.xxx to img_0? Or add web link like FB in menu for members respectively?

**Comment by mitkosoft** [comment]
To assign a link to a node, you can use onClick event: https://balkangraph.com/OrgChartJS/Docs/APIReference#onClick

If you want to add a link into the menu, you can see how to build/customize nodeMenu: https://balkangraph.com/OrgChartJS/Docs/NodeMenuItem
