### ISSUE TITLE
Hot to create multiple dynamic Balkan Org Chart in a single DOM

### ISSUE THREAD

**Issue by Abhishekkhh** [BALKANGraph/OrgChartJS#762]
Hi, 
    Can you please help me in how to create multiple Balkan Org Charts dynamically in a single DOM. Please provide some code snapshots for better understanding.

**Comment by ZornitsaPesheva** [comment]
Here is a code demo:
https://code.balkan.app/org-chart-js/two-charts-in-one-page-dynamically#JS

**Comment by Abhishekkhh** [comment]
Hi, Thanks for the reply. Can you please let me know that how can i export the individual org chart in separate sheets in a single PDF file.
