### ISSUE TITLE
Export Multiple Dynamic Balkan Org Chart in a Single PDF File

### ISSUE THREAD

**Issue by Abhishekkhh** [BALKANGraph/OrgChartJS#763]
Please share the code to create a single PDF file with multiple sheets containing multiple Balkan Org Charts which are created dynamically.

**Comment by ZornitsaPesheva** [comment]
Okay... You mean you need to export all the charts on separate A4 sheets?
But in case you have a big chart you will not be able to see anything in it.

**Comment by Abhishekkhh** [comment]
Kindly provide me a code sample for the same. I am not gonna create big charts so this will work.

**Comment by ZornitsaPesheva** [comment]
HI. We will create a demo for you.

**Comment by plamen-peshev** [comment]
As promised we have created a Code demo for you

https://code.balkan.app/export-multiple-org-charts-in-a-single-pdf-file#JS
