### ISSUE TITLE
Bug : When creating Balkan Org Chart left parent is not generated properly when text for some nodes is large

### ISSUE THREAD

**Issue by JohnSmith2404** [BALKANGraph/OrgChartJS#764]
Please check the URL :: https://jsfiddle.net/qo3gvrzh/
I have created a sample of the bug, please help me in getting it resolved.
![Capture](https://github.com/BALKANGraph/OrgChartJS/assets/137792797/00554bf0-0e48-400a-ba35-872ba9ea4dcf)

**Comment by ZornitsaPesheva** [comment]
Please use "node-initialized" event to create dynamic height.
https://code.balkan.app/org-chart-js/dynamic-height#JS

**Comment by JohnSmith2404** [comment]
Thanks for the help, your solution worked awesomely.
