### ISSUE TITLE
Adding filter to the node chart

### ISSUE THREAD

**Issue by joshuacos1977** [BALKANGraph/OrgChartJS#765]
I need to filter Org-chart based on the dropdown selection.
like link below:
[((https://www.youtube.com/watch?v=gqi7nHqAFww&ab_channel=ChartHop))]
on the 45 sec of the video it demonstrates the filtering

**Comment by ZornitsaPesheva** [comment]
In this video they are showing different data in the same field by selection from the drop down what to show.
You can achieve the same with different templates.
Here is a code demo: https://code.balkan.app/org-chart-js/showing-different-data-by-selecting-a-template#JS

**Comment by joshuacos1977** [comment]
Thank you very much.
This is all need. I try to implement these feature to my code as

Sent from my iPhone

On Jun 26, 2023, at 12:02 PM, ZornitsaPesheva ***@***.***> wrote:

﻿

In this video they are showing different data in the same field by selection from the drop down what to show.
You can achieve the same with different templates.
Here is a code demo: https://code.balkan.app/org-chart-js/showing-different-data-by-selecting-a-template#JS
