### ISSUE TITLE
How to Append List of n number of items one below the other on a new line in Balkan Org Chart

### ISSUE THREAD

**Issue by JohnSmith2404** [BALKANGraph/OrgChartJS#766]
![Capture2](https://github.com/BALKANGraph/OrgChartJS/assets/137792797/7d43a4e9-cb91-4aae-9930-23fb0c7dfadf)

Hi,
I am attaching a Screenshot, this is my requirement to get n Items Listed one below the other. Please help me with an example.

**Comment by ZornitsaPesheva** [comment]
Please check if this example can help you:
https://code.balkan.app/org-chart-js/chinese-vertically#JS
