### ISSUE TITLE
Handel collapse clicking to collapse specific child (EX. Need when clicking on collapse and expand button collapse and expand only childs which take "assistant" tag)

### ISSUE THREAD

**Issue by omar306** [BALKANGraph/OrgChartJS#769]
EX. Need when clicking on collapse and expand button collapse and expand only childs which take "assistant" tag

**Comment by ZornitsaPesheva** [comment]
Created a code demo for you: https://code.balkan.app/org-chart-js/collapse-assistant-node#JS
