### ISSUE TITLE
Add conditional colors to grouping

### ISSUE THREAD

**Issue by kmmcdan** [BALKANGraph/OrgChartJS#77]
Hello,

My javascript skills are minimal but I can get through with a little direction. We are using the grouping template but would also like to implement conditional colors. Can someone help me with the syntax and where to put the code so I can make that happen? Or is there a way to use css to set the box color by the group name?

Here is the code from the grouping template:

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Grouping - OrgChart JS | BALKANGraph</title>
    <style>
        html, body {
    margin: 0px;
    padding: 0px;
    width: 100%;
    height: 100%;
    overflow: hidden;
    font-family: Helvetica;
}

#tree {
    width: 100%;
    height: 100%;
}

    </style>

</head>
<body>
    
<link href="https://fonts.googleapis.com/css?family=Gochi+Hand" rel="stylesheet">

<script src="https://balkangraph.com/js/latest/OrgChart.js"></script>

<div id="tree"></div>
    <script>
    
window.onload = function () { 
    var chart = new OrgChart(document.getElementById("tree"), {
        template: "ana",
        enableDragDrop: true,
        nodeMouseClick: BALKANGraph.action.edit,
        scaleInitial: BALKANGraph.match.boundary,
        nodeMenu: {
            details: { text: "Details" },
            edit: { text: "Edit" },
            add: { text: "Add" },
            remove: { text: "Remove" }
        },
        dragDropMenu: {
            addInGroup: { text: "Add in group" },
            addAsChild: { text: "Add as child" }
        },
        nodeBinding: {
            field_0: "name",
            field_1: "title",
            img_0: "img"
        },
        tags: {
            Directors: {
                group: true,
                groupName: "Directors",
                groupState: BALKANGraph.EXPAND,
                template: "group_grey"
            },
            HRs: {
                group: true,
                groupName: "HR Team",
                groupState: BALKANGraph.COLLAPSE,

                template: "group_grey"
            },
            Sales: {
                group: true,
                groupName: "Sales Team",
                groupState: BALKANGraph.EXPAND,
                template: "group_grey"
            },
            Devs: {
                group: true,
                groupName: "Dev Team",
                groupState: BALKANGraph.EXPAND,
                template: "group_grey"
            }
        },
        nodes: [
            { id: 1, tags: ["Directors"], name: "Billy Moore", email: "billy.moore@email.com", title: "CEO", img: "https://balkangraph.com/js/img/2.jpg" },
            { id: 2, tags: ["Directors"], name: "Marley Wilson", title: "Director", img: "https://balkangraph.com/js/img/3.jpg" },
            { id: 3, tags: ["Directors"], name: "Bennie Shelton", title: "Shareholder", img: "https://balkangraph.com/js/img/4.jpg" },

            { id: 4, pid: 1, name: "Billie Rose", email: "billie.rose@email.com", title: "Dev Team Lead", img: "https://balkangraph.com/js/img/5.jpg" },

            { id: 5, pid: 1, tags: ["HRs"], name: "Glenn Bell", title: "HR", img: "https://balkangraph.com/js/img/10.jpg" },
            { id: 6, pid: 1, tags: ["HRs"], name: "Blair Francis", title: "HR", img: "https://balkangraph.com/js/img/11.jpg" },

            { id: 7, pid: 1, name: "Skye Terrell", title: "Manager", img: "https://balkangraph.com/js/img/12.jpg" },

            { id: 8, pid: 4, tags: ["Devs"], name: "Jordan Harris", title: "JS Developer", img: "https://balkangraph.com/js/img/6.jpg" },
            { id: 9, pid: 4, tags: ["Devs"], name: "Will Woods", title: "JS Developer", img: "https://balkangraph.com/js/img/7.jpg" },
            { id: 10, pid: 4, tags: ["Devs"], name: "Skylar Parrish", title: "node.js Developer", img: "https://balkangraph.com/js/img/8.jpg" },
            { id: 11, pid: 4, tags: ["Devs"], name: "Ashton Koch", title: "C# Developer", img: "https://balkangraph.com/js/img/9.jpg" },

            { id: 12, pid: 7, tags: ["Sales"], name: "Bret Fraser", title: "Sales", img: "https://balkangraph.com/js/img/13.jpg" },
            { id: 13, pid: 7, tags: ["Sales"], name: "Steff Haley", title: "Sales", img: "https://balkangraph.com/js/img/14.jpg" }
        ]
    });    
};

    </script>
</body>
</html>

And here is the code that allows you to add conditional colors, there is some css as well but I know where to place that:

 for (var i = 0; i < nodes.length; i++) {
        var node = nodes[i];
        switch (node.title) {
            case "QA":
                node.tags = ["QA"];
                break;
            case "Marketer":
            case "Designer":
            case "Sales Manager":
                node.tags = ["Marketing"];
                break;
			case "JS Team Lead":
			case "Programmer":
				node.tags = ["Dev"];
        }

How and where do I place this in the code above to implement conditional colors? Thank you!

**Comment by plamen-peshev** [comment]
Conditional color for group, node or node from group?

**Comment by kmmcdan** [comment]
Would like to specify node color by which group they are in. So all in
"marketing" blue, all in "development" red all in "hr" yellow etc. So not
the group box but the actual nodes within the group.

Thanks!

Kathleen

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/21/19,
7:28:52 PM

**Comment by plamen-peshev** [comment]
You can achieve requested functionality with CSS 

.Devs [node-id] rect{
    fill: #FFCA28;
}

Here is a demo: https://balkangraph.com/OrgChartJS-Demos/ConditionalColorGroups


![image](https://user-images.githubusercontent.com/49443821/56477728-736ca600-64b1-11e9-9f98-41e87956a28c.png)

**Comment by kmmcdan** [comment]
Thanks I'll try that tomorrow!

**Comment by kmmcdan** [comment]
Works perfectly thank you! Now I just have to figure out the CSV import and
I'll be on my way.

Kathleen

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/22/19,
8:41:34 AM
