### ISSUE TITLE
navigate throughout diagram 

### ISSUE THREAD

**Issue by kazemimorteza68** [BALKANGraph/OrgChartJS#770]
Hi.
I want to navigation throughout the diagram  when click and hold the mouse on the nodes also  in mobile device when i touch and hold  the on nodes can't navigate  . is this option available ?   
as default for navigation only click and hold outside of  a node i can navigate .
Thanks

**Comment by ZornitsaPesheva** [comment]
Yes, you need this option:
nodeMouseClick: OrgChart.action.pan,
https://balkan.app/OrgChartJS/API/interfaces/OrgChart.options#nodeMouseClick

**Comment by kazemimorteza68** [comment]
@ZornitsaPesheva 

Thanks you saved me
