### ISSUE TITLE
How Can i add SubLevel Captions ?

### ISSUE THREAD

**Issue by Abhishekkhh** [BALKANGraph/OrgChartJS#772]
![Level wise chart](https://github.com/BALKANGraph/OrgChartJS/assets/96596671/1b3ecbcc-cba5-49a9-b8ec-8ec551e27f91)
PFA, How can i add Level wise captions on the left hand side of each Levels of Balkan Org Chart ?

**Comment by ZornitsaPesheva** [comment]
You can have a background with the level captions:
https://code.balkan.app/org-chart-js/node-background-image#JS

**Comment by composercodes** [comment]
Please I need the same .
I tested the chart but I need this to complete my requirements the level title and divider as dotted line across the chart 
@ZornitsaPesheva 
Please can you help?

**Comment by ZornitsaPesheva** [comment]
> Please I need the same . I tested the chart but I need this to complete my requirements the level title and divider as dotted line across the chart [@ZornitsaPesheva](https://github.com/ZornitsaPesheva) Please can you help?

I have answered on your issue.
