### ISSUE TITLE
Layout seems working with at least 2 child nodes

### ISSUE THREAD

**Issue by gmaggiodev** [BALKANGraph/OrgChartJS#773]
We found that layouts seems applying only if a node has at least 2 child nodes. In case of 1 single node the layout is not applied so the connection exit straight from the parent node to the child node:

![image](https://github.com/BALKANGraph/OrgChartJS/assets/1485446/69756681-d2a3-4edc-9a63-ba3782c74dc6)

In this example, our customer is expecting simmetric connections between 1st, 2nd and 4th node under the root., like this:

![image](https://github.com/BALKANGraph/OrgChartJS/assets/1485446/03d3467e-db28-4591-afa6-f1a6e5bc7b20)

**Comment by ZornitsaPesheva** [comment]
Here is how you can achieve this:
https://code.balkan.app/org-chart-js/one-child-layout#JS

**Comment by gmaggiodev** [comment]
So, I need to create a "phantom" node for each node with 1 child?
A bit tricky for us. Any plan to have another option in the future?

**Comment by gmaggiodev** [comment]
I discussed with developers but your solution is not acceptable because we have structure with thousands of these situation and we cannot add phantom nodes everywhere. Moreover there is a lot of custom logic based on the number of child that should be adapted. 
Not suitable for us, sorry.

**Comment by plamen-peshev** [comment]
We have added new constant in the latest version, set it to zero 

`OrgChart.MIXED_LAYOUT_IF_NUMBER_OF_CHILDREN_IS_MORE_THEN = 0;`

you can get the latest version form [here ](https://orgchartjs.balkan.app/)

[See this Code demo](https://code.balkan.app/org-chart-js/one-child-layout#JS), clear the cache before testing
