### ISSUE TITLE
Error when generating an image in the "PDF" Header

### ISSUE THREAD

**Issue by PhysicApp** [BALKANGraph/OrgChartJS#774]
The organizational chart of the organization was developed but there is an error when generating the "PDF" in the header section, sometimes the image of the company logo is generated and sometimes not, the logo is sent through a url of the server where the project is hosted.

![Se genera el logo](https://github.com/BALKANGraph/OrgChartJS/assets/84802936/04d3f97e-0c63-475e-b6ad-fd1c8ce0d2ca)
![Se genera el logo incompleto](https://github.com/BALKANGraph/OrgChartJS/assets/84802936/d85b1ac3-76b8-453e-806a-8eee0f174e88)
![No se genera el logo](https://github.com/BALKANGraph/OrgChartJS/assets/84802936/2be96962-0aee-4b0f-a6fd-fae1956d1464)

**Comment by ZornitsaPesheva** [comment]
Hi, could you please edit this example to isolate the issue?
https://code.balkan.app/org-chart-js/export-pdf-logo#JS

**Comment by PhysicApp** [comment]
var obj_Fecha = new Date();
let sFecha = `Fecha: ` + `${(obj_Fecha.getDate()).toString().padStart(2, '0')}/${(obj_Fecha.getMonth() + 1).toString().padStart(2, '0')}/${obj_Fecha.getFullYear()}`;
let sHtml = '<div style="font-size: 2.5em;">Área: Admón. y Finanzas</div><div style="font-size: 2.3em;">Departamento:  Finanzas</div>'
var sColorSecundario = "#234f7f";

//JavaScript
var chart = new OrgChart(document.getElementById('tree'), {
    orientation: OrgChart.orientation.bottom_left,
    nodeBinding: {
        name: 'id',
        title: 'pid'
    },
    menu: {
        pdfWithTitle: {
            text: 'Export',
            icon: OrgChart.icon.pdf(24, 24),
            onClick: function () {
                   let sHeader = `<div style="text-align: left; font-family: Gotham Rounded Light !important; width: 1000px; color: ${sColorSecundario}">
                                <div style="display: flex; align-items: center; width: 100%; height: 100%;">
                                    <img src="https://portaltest.nadglobal.com/CH_Pruebas/Content/Imagenes/img_logo_nad_color.png" style="width: 300px; height: 100%;">
                                    <div style="color: #234f7f; font-size: 3.3em; height: 100%; width: 100%; margin-left: 20px;">
                                        <p>Estructura Organizacional</p>
                                    </div>
                                </div>
                                <hr color="${sColorSecundario}" style="display: inline-block; width: 870px;">
                                ${sHtml}
                                <div style="font-size: 2em; margin-top: 15px;">${sFecha}</div>
                                </div>`;

                if (10 < 5) {
                    chart.exportPDF({
                        landscape: false,
                        format: 'A2',
                        scale: 80,
                        header: sHeader,
                        margin: [300, 60, 300, 60]
                    });
                } else {
                    chart.exportPDF({
                        header: sHeader,
                        margin: [350, 60, 300, 60]
                    });
                }
            }
            }
        }
    });

chart.load([
    { id: 1 },
    { id: 2, pid: 1 },
    { id: 3, pid: 1 }
]);

**Comment by PhysicApp** [comment]
There are times when the image is generated and at other times it is not, sometimes the image is only generated in part.

![image](https://github.com/BALKANGraph/OrgChartJS/assets/84802936/65e07d7d-4730-4060-8959-4b3eb4204f08)

![image](https://github.com/BALKANGraph/OrgChartJS/assets/84802936/e667295d-be8f-41f4-b084-c5ffce28c4a6)

**Comment by ZornitsaPesheva** [comment]
Please edit the above example, save and send back the new link.

**Comment by PhysicApp** [comment]
Hello, good day. I send you the link of the sample code.

https://code.balkan.app/codigo-ejemplo-error-pdf-generar-imagen#JS

**Comment by ZornitsaPesheva** [comment]
Hi
The issue is that the image is loading too slow from your server,
We have created this example for you to show you that if the image is loading normally you will not have that issue:
https://code.balkan.app/error-when-generating-an-image-in-the-pdf-header#JS
