### ISSUE TITLE
Console error occurs for self pointing clink

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [BALKANGraph/OrgChartJS#775]
When orientation set to other than top console error occurring when self pointing clink is created

https://jsfiddle.net/qh1uom0r/6/show
https://jsfiddle.net/qh1uom0r/6/

**Comment by ZornitsaPesheva** [comment]
Why do you need self pointing clink?

**Comment by ZornitsaPesheva** [comment]
Closing the issue as inactive.
