### ISSUE TITLE
org chart price

### ISSUE THREAD

**Issue by kazemimorteza68** [BALKANGraph/OrgChartJS#777]
Hi.
Is org chart free and can i use that without paying  ? it's very expensive for me

**Comment by ZornitsaPesheva** [comment]
No, the free version is only a trial. You need to purchase a license to use it.

**Comment by xorinzor** [comment]
This should be more clearly indicated on the README. Right now it just looks like free to use.

**Comment by ZornitsaPesheva** [comment]
It is clearly indicated in our Pricing page: https://balkan.app/OrgChartJS/Pricing

**Comment by xorinzor** [comment]
Yes but it isn't in the github repo. People googling and ending up on this repo have zero indication that this is paid software.
The readme simply states install  & usage, and that's it.

**Comment by ZornitsaPesheva** [comment]
We have links to our website in this repo. Everybody who is interested can find the information.
