### ISSUE TITLE
Add Title and Legend

### ISSUE THREAD

**Issue by Dunleavy-Aaron** [BALKANGraph/OrgChartJS#78]
Hi,

Wondering if there is a way to add a Title and Legend to the chart so that they both export.

Thanks,

**Comment by plamen-peshev** [comment]
Here is a demo: https://balkangraph.com/OrgChartJS-Demos/A4ExportTitle

**Comment by Dunleavy-Aaron** [comment]
Thanks very much. Is there a way to add this to the chart before export. Also adding something to the bottom of the chart and export.

**Comment by plamen-peshev** [comment]
Yes you can, use onExportStart event

```
 var chart = new OrgChart(document.getElementById("tree"), {
            onExportStart: function (sender, options, svg) {
                  options.extraHtml = <your html>;
                //return false; to cancel the export operation
            },
        });
```

Next version will support headers and footers

**Comment by plamen-peshev** [comment]
The latest version does support headers, footers and PDF Preview

```
     OrgChart.pdfPrevUI.show(chart, {
            format: "A4",
            header: 'My Header',
            footer: 'My Footer. Page {current-page} of {total-pages}'
        });
```

extraHtml has been removed

**Comment by Dunleavy-Aaron** [comment]
Hi,

That is wonderful thanks so much. Is there any way to add html or an image to these or a link to the documentation for the new export library.

**Comment by plamen-peshev** [comment]
you can use html for the header and footer instead of text
```

     OrgChart.pdfPrevUI.show(chart, {
            format: "A4",
            header: '<h1>My Header'</h1>,
            footer: '<div style="color:red;">My Footer. Page {current-page} of {total-pages}</div>'
        });
```

**Comment by Dunleavy-Aaron** [comment]
This is great.  Using the preview I am able to adjust the Header/Footer, Margins, Laytout etc, however I cant seems to set these before hand. I would like to setup the page size to Tabloid Landscape but it always defaults to Portrait and the margins dont seem to work either. Is there a way to see what the preview is setting? Or a list of the different options. 

One of the other issues is including an image in the header. Again works fine in the preview but does not show up when using just the export.

Thanks,

Aaron

**Comment by plamen-peshev** [comment]
Tabloid page size is not supported in the current implementation

Set the absolute URL of the image

**Comment by Dunleavy-Aaron** [comment]
Thanks I will try the image. What about layout and margins, I have tried 
layout: "Landscape",
margins: "50,50,50,50"  

without any success.

**Comment by Dunleavy-Aaron** [comment]
Sorry to keep bugging you about this I am happy to pay for some support if I am missing somthing.

I figured out the layout with         landscape: 'true',  and the margins     margin: [120,50,40,50], but the image is giving me some trouble. 

It seems to work if it is included in the chart.
Working:
https://jsfiddle.net/aaron_dunleavy/nq8aoswf/7/

But not if it is only in the header:
https://jsfiddle.net/aaron_dunleavy/ph0z9ywq/

Thanks

**Comment by plamen-peshev** [comment]
Thanks for the demos

Actually both demos are working for me

See attached

[pdfs.zip](https://github.com/BALKANGraph/OrgChartJS/files/3184000/pdfs.zip)

**Comment by Dunleavy-Aaron** [comment]
Hi,

 

Sorry I forgot save the one that did not work. It still had the green dot as the pic.

 

https://jsfiddle.net/aaron_dunleavy/ph0z9ywq/2/

 

 

 

Aaron Dunleavy

Production Manager

Informanus Inc.

(416) 537-2579

 <mailto:aaron@informanus.com> aaron@informanus.com

 <http://www.informanus.com/> www.informanus.com

**Comment by plamen-peshev** [comment]
It was an issue with the export service

We have fixed it

Now it should work as expected

Please confirm

**Comment by Dunleavy-Aaron** [comment]
Hi,

 

Its working perfectly now. That’s for the quick fix.

 

 

 

Aaron Dunleavy

Production Manager

Informanus Inc.

(416) 537-2579

 <mailto:aaron@informanus.com> aaron@informanus.com

 <http://www.informanus.com/> www.informanus.com
