### ISSUE TITLE
"Slink" out of position when generating the pdf

### ISSUE THREAD

**Issue by PhysicApp** [BALKANGraph/OrgChartJS#780]
Slink moved from assumption when changing the default design when generating the organization chart in the pdf

default layout set
![image](https://github.com/BALKANGraph/OrgChartJS/assets/84802936/1a80a586-3960-4d91-9722-ef929f8b3fc5)

gap:

![image](https://github.com/BALKANGraph/OrgChartJS/assets/84802936/b4a06431-fbf3-49cf-81b9-05280f0fbae8)

![image](https://github.com/BALKANGraph/OrgChartJS/assets/84802936/d8a4bbe2-ee15-4bd5-ac33-a6e7c9b94593)

**Comment by plamen-peshev** [comment]
Thank you for reporting this problem to us 

We where able reproduce the issue https://code.balkan.app/slink-out-of-position-when-generating-the-pdf#JS

Will fix it in the next release

**Comment by PhysicApp** [comment]
When would the new version be integrated?

**Comment by PhysicApp** [comment]
Has the new version been integrated with the bug fix?

**Comment by ZornitsaPesheva** [comment]
Not yet.

**Comment by plamen-peshev** [comment]
the issue has been addressed in the latest version

you can clear your browser cache and test: https://code.balkan.app/result/slink-out-of-position-when-generating-the-pdf

get the latest version from here: https://orgchartjs.balkan.app
