### ISSUE TITLE
The export dont save the styles from the chart

### ISSUE THREAD

**Issue by Adalk033** [BALKANGraph/OrgChartJS#783]
When I export my chart to PDF or other type, my styles doesnt works

**PDF** 
![image](https://github.com/BALKANGraph/OrgChartJS/assets/37385524/4f81e9cb-7ce2-4daf-9d44-7e4a043bed2e)

**Chart in Web**
![image](https://github.com/BALKANGraph/OrgChartJS/assets/37385524/34956a82-3ec5-4aed-8f21-8065990e0374)

**Comment by Adalk033** [comment]
So, maybe I found the solution. I could solve it by changing the width, but maybe it should be directly from the source code, but I do not know how difficult it is.
![code](https://github.com/BALKANGraph/OrgChartJS/assets/37385524/83fcb018-ecc4-4cd0-8b8c-948df880862b)

**Comment by ZornitsaPesheva** [comment]
Here is how to export the styles:
https://balkan.app/OrgChartJS/Docs/Exporting#styles
