### ISSUE TITLE
Get an error "Unterminated string constant" when install BALKAN_OrgChartJS_PROFESSIONAL_8.11.06-min

### ISSUE THREAD

**Issue by muzanella11** [BALKANGraph/OrgChartJS#785]
I get this error when trying to install pro version OrgChart. I'm using VueJs
<img width="1680" alt="Screen Shot 2023-08-08 at 15 55 39" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/f4240a71-56e5-4f48-b481-017e837f4ea4">
It seems there is a bug in your `orgchart.js` so it can't be compiled.

**Comment by ZornitsaPesheva** [comment]
I just have added this at the end of the orgchart.js file:
export default OrgChart;
Then added the file in folder assests.
Imported it this way:
import OrgChart from '../assets/orgchart'
and it works like a charm.

![image](https://github.com/BALKANGraph/OrgChartJS/assets/19305472/e644305d-a59f-41e2-88b6-be94f25da545)
![image](https://github.com/BALKANGraph/OrgChartJS/assets/19305472/949c4166-c9e1-4a7b-b6a1-55e8ac35659a)

**Comment by muzanella11** [comment]
> I just have added this at the end of the orgchart.js file: export default OrgChart; Then added the file in folder assests. Imported it this way: import OrgChart from '../assets/orgchart' and it works like a charm.
> 
> ![image](https://user-images.githubusercontent.com/19305472/259088128-e644305d-a59f-41e2-88b6-be94f25da545.png) ![image](https://user-images.githubusercontent.com/19305472/259088286-949c4166-c9e1-4a7b-b6a1-55e8ac35659a.png)

This is my local:
<img width="1128" alt="Screen Shot 2023-08-09 at 07 40 25" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/5c77900b-ac53-4227-a7fe-174274713d1c">
<img width="594" alt="Screen Shot 2023-08-09 at 07 42 13" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/4ed74714-4589-4d31-a440-355e05471f3f">


I still getting this error after following your instructions
<img width="1680" alt="Screen Shot 2023-08-08 at 15 55 39" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/ebafc393-8771-4001-8a78-822b82102f43">
<img width="693" alt="Screen Shot 2023-08-09 at 07 25 00" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/8f48e312-f79e-4cb3-9564-67c8bd2a7cb2">

**Comment by ZornitsaPesheva** [comment]
Please try the exact steps.
1. Create an org chart following these steps: https://balkan.app/OrgChartJS/Docs/Vuejs
2. Download the licensed version of Org Chart JS.
3. Add **export default OrgChart**; at the end of the file
4. Copy orgchart.js to /src/assets folder
5. Import the file this way: import OrgChart from '../assets/orgchart'

**Comment by ZornitsaPesheva** [comment]
Did you manage to get it work?

**Comment by muzanella11** [comment]
> Please try the exact steps:
> 
> 1. Create an org chart following these steps: https://balkan.app/OrgChartJS/Docs/Vuejs
> 2. Download the licensed version of Org Chart JS.
> 3. Add **export default OrgChart**; at the end of the orgchart.js file
> 4. Copy orgchart.js to **/src/assets** folder
> 5. Import the file this way: **import OrgChart from '../assets/orgchart'**

I don't think the problem is that the path to the `orgchart.js` file is wrong. The `orgchart.js` file has loaded properly in my vue template and when I replace the code in `orgchart.js` with `console.log('hello')` my vue app runs normally again, but when the code is returned, the error "maximum call stack exceeded" appears.
<img width="693" alt="Screen Shot 2023-08-09 at 07 25 00" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/8f48e312-f79e-4cb3-9564-67c8bd2a7cb2">

Have you tried running vue app in your local and `orgchart.js` compiles fine in your vue app?
Do we have a different `orgchart.js` file? I am using version `8.11.06`?
Can you provide a screenshot of your vue app that is running and displays all the charts in the vue component?

**Comment by ZornitsaPesheva** [comment]
![image](https://github.com/BALKANGraph/OrgChartJS/assets/19305472/c4298a75-1556-4351-bd48-2a232c2547b8)

**Comment by muzanella11** [comment]
> ![image](https://user-images.githubusercontent.com/19305472/259643868-c4298a75-1556-4351-bd48-2a232c2547b8.png)

What if you add eslint to your vue app? Are you getting the same error?

**Comment by muzanella11** [comment]
<img width="1466" alt="Screen Shot 2023-08-10 at 13 54 14" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/6b56634b-34b6-408e-a4b3-c532728a93d5">

I tried this in jsfiddle, if `orgchart.js` is loaded without eslint the script is running, if there is eslint then the error appears

**Comment by ZornitsaPesheva** [comment]
We will check this and will let you know.

**Comment by muzanella11** [comment]
> We will check this and will let you know.

Please give me an example of how to use your pro version library in VueJs with typescript and eslint. You just provide `orgchart.js` and `orgchart.d.ts` in your zip file.
<img width="670" alt="Screen Shot 2023-08-10 at 22 05 59" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/15dd457a-eaae-4b69-8234-19aa2b4e9f21">
a little tricky to put it together. Because what you are giving right now is just an example for installing your pro library in javascript not typescript. 
Your package library in NPM is good, I need an npm package like that for the pro version too, in my opinion

**Comment by ZornitsaPesheva** [comment]
It looks like you cannot use orgchart.js with slint.

**Comment by muzanella11** [comment]
> It looks like you cannot use orgchart.js with slint.

Can you give me an example of how to use the pro version of your library in vue typescript?

**Comment by ZornitsaPesheva** [comment]
Following the above instructions I was able to create a TypeScript project and it is working.
Can you create a simple instruction of how do you create a TypeScript project with the NPM version, because we are using this one and it is working the same way with the NPM (trial) and the static (licensed).
Only the difference is that we add **export default OrgChart;** at the end. 
If the issue is that you can't use our typecsrip definition, you can try to add it in the .d.ts file too.
Also you need to add .d.ts filr in the same folder where the org.chart.js is.

**Comment by muzanella11** [comment]
> Following the above instructions I was able to create a TypeScript project and it is working. Can you create a simple instruction of how do you create a TypeScript project with the NPM version, because we are using this one and it is working the same way with the NPM (trial) and the static (licensed). Only the difference is that we add **export default OrgChart;** at the end. If the issue is that you can't use our typecsrip definition, you can try to add it in the .d.ts file too. Also you need to add .d.ts file in the same folder where the org.chart.js is.

I don't think it's how I create the typescript project, everything is according to what's in the Vue documentation.
If there is a problem when creating the project, maybe I won't be able to run the project or an error has appeared the first time I did the initial project, but that's not the problem.
I have also followed your instructions, even disabled eslint specifically for `orgchart.js`.
I see the difference is, you are using vue app with vite and I am using webpack.
This error appears if you install it on a vue app with webpack as the compiler.
Have you tried compiling `orgchart.js` in a vue app with webpack?
I think you will get an error like this

<img width="707" alt="Screen Shot 2023-08-15 at 09 16 49" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/711ab197-57a1-4604-aa69-95f7e954ddd5">

<img width="884" alt="Screen Shot 2023-08-15 at 09 10 02" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/9919b2e2-4d69-4532-8903-a22e06aa9fd5">


<img width="1180" alt="Screen Shot 2023-08-15 at 09 07 38" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/166faf09-f2cc-4399-9488-5846fa352e50">

<img width="247" alt="Screen Shot 2023-08-15 at 09 14 05" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/e042d7d9-facf-418c-81b7-3c4fb2246474">

Is there still something wrong with the way I called the `orgchart.js` file?
I think using a relative path or path alias `@` (alias path in webpack) has no effect and the contents of the `orgchart.js` file still work fine, but the error will appear when `orgchart.js` is compiled by webpack.

I have another approach too if this error still appears, maybe I'll inject the `orgchart.js` file with the script in the vue component chart and then make the `OrgChart` global
```
window. OrgChart = OrgChart
```

**Comment by ZornitsaPesheva** [comment]
Sorry, I forgot to mention that we don't use Vue nor other frontend frameworks, so I don't know how Vue works.  
So I need instruction step by step how to create a project as your one, as I cannot learn this so fast to resolve your issue.

**Comment by muzanella11** [comment]
> Sorry, I forgot to mention that we don't use Vue nor other frontend frameworks, so I don't know how Vue works. So I need instruction step by step how to create a project as your one, as I cannot learn this so fast to resolve your issue.

Thank you for your time and willingness to help me.
I've been able to install your library on my Vue typescript with my own approach.
I made npm local dependencies and saw that there were a few things missing from your pro version package and I have fixed them.
<img width="245" alt="Screen Shot 2023-08-22 at 16 24 00" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/bde937c9-a58a-4e01-a867-c3f33d7da4bc">


Some things that are missing are:
- there is no `export default OrgChart` in `orgchart.d.ts` file
<img width="706" alt="Screen Shot 2023-08-22 at 16 25 15" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/59cd7d56-2db7-400f-a6f2-ccdb89f7636f">

- no need to use `export default OrgChart` in `orgchart.js` file
<img width="959" alt="Screen Shot 2023-08-22 at 17 00 21" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/08f36e65-5168-4e19-9e01-b45a243a0615">

- Add the npm package entry point to `orgchart.js` and types to `orgchart.d.ts` in the package json npm local dependency
<img width="744" alt="Screen Shot 2023-08-22 at 16 44 58" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/ca830b93-2732-4681-ba49-353c3d7e6533">

- Add the local dependency in the main `package.json` of the project
<img width="1021" alt="Screen Shot 2023-08-22 at 16 49 39" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/fec34516-7fcf-48ec-9bde-c430900afeca">

And it's running fine now
<img width="1680" alt="Screen Shot 2023-08-22 at 16 55 48" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/6516cfdb-7538-48ac-81a9-9a067b9306a9">

And don't forget to disable eslint because `orgchart.js` can't use with eslint
<img width="1028" alt="Screen Shot 2023-08-22 at 17 07 27" src="https://github.com/BALKANGraph/OrgChartJS/assets/12839006/0b162e30-e80b-4cda-9602-b8dc2fc2f792">

It will be safer to use your pro version if you use the npm local dependency approach like that :)

**Comment by ZornitsaPesheva** [comment]
Thank you too :)
I hope this approach works well.
