### ISSUE TITLE
call a function based on field value

### ISSUE THREAD

**Issue by maryammoshtoofar** [BALKANGraph/OrgChartJS#786]
hi. I need to call a function when user clicks on a field but only if the field has a certain value. I tried [PopupOnFieldClick ](https://balkan.app/OrgChartJS-Demos/PopupOnFieldClick.html)here but it messed up my chart. Any help would be much appreciated

**Comment by ZornitsaPesheva** [comment]
Created a code demo for you:
https://code.balkan.app/org-chart-js/conditional-field-click#JS
