### ISSUE TITLE
Edit is not populating the user data

### ISSUE THREAD

**Issue by joshuacos1977** [BALKANGraph/OrgChartJS#787]
hi I have an issue with org-chart,I have edit,add,edit and add superviosr on my node menu,however,when i try to edit the user info it doesn't populates user's info.
here is the screenshoots below:
![Screenshot 2023-08-10 142224](https://github.com/BALKANGraph/OrgChartJS/assets/28411895/fdd76c04-d636-407e-8132-3cccb57e15fe)
![Screenshot 2023-08-10 142256](https://github.com/BALKANGraph/OrgChartJS/assets/28411895/6c87bb4a-d168-4926-b782-4a6c6fd94acb)

I have totally customized the menu and also based on the user's admin rights I am able to hide add/and add supervisor menu options.

**Comment by joshuacos1977** [comment]
Here is my code base which is implemented on react js:
import React from "react";
import { useSelector } from "react-redux";
import OrgChart from "../../../balkan/orgchart";

OrgChart.templates.pmTemplate = Object.assign({}, OrgChart.templates.ana);
OrgChart.templates.pmTemplate.node = "";
OrgChart.templates.pmTemplate.box_1 =
  '<rect x="0" y="0" height="120" width="250" fill="{val}" stroke-width="1" stroke="#aeaeae" rx="30" ry="30"></rect>';
OrgChart.templates.pmTemplate.box_2 =
  '<rect x="0" y="60" height="60" width="250" fill="{val}" stroke-width="1" stroke="#aeaeae" rx="30" ry="30"></rect>';
OrgChart.templates.pmTemplate.box_3 =
  '<rect x="1" y="30" height="50" width="248" fill="{val}" stroke-width="1" stroke="none"  ></rect>';
OrgChart.templates.pmTemplate.plus = "";
OrgChart.templates.pmTemplate.minus = "";
OrgChart.templates.pmTemplate.img_0 =
  '<clipPath id="{randId}"><rect x="10" y="10" width="50" height="50" rx="15" ry="15"></rect></clipPath><image preserveAspectRatio="xMidYMid slice" clip-path="url(#{randId})" xlink:href="{val}" x="10" y="10"  width="50" height="50"></image>';
OrgChart.templates.pmTemplate.name =
  '<text data-width="170" style="font-size: 16px; font-weight: bold;" fill="#000" x="70" y="30">{val}</text>';
OrgChart.templates.pmTemplate.title =
  '<text data-width="170" style="font-size: 16px;" fill="#cc6633" x="70" y="50">{val}</text>';
OrgChart.templates.pmTemplate.metric =
  '<text data-width="170" style="font-size: 10px; color:#5c5c5c"  fill="#ededf5" x="125" y="105" text-anchor="middle">{val}</text>';

const PERFORMANCE = {
  NOT_MEETING_EXPECTATIONS: 0,
  MEETING_EXPECTATIONS: 1,
  EXCEEDED_EXPECTATIONS: 2,
};

/**
 * The organization chart, which displays all nodes falling under the current logged in user's supervisor, as well as all nodes who's supervisor is the currently logged in user
 *
 * @param props - The properties of the organizational chart
 * @params props.performance - assign random perfomance to each users on the chart
 * @param props.nodes - The nodes that are pulled from the database which form a graph structure when the user enters this page
 * @param props.toggleUpdateUserSupervisorModal - The callback that fires when the user decides to update the supervisor of a user
 * @param props.handleEditOnTheNode - The callback used when the user clicks the edit option when selecting the options of a node
 * @param props.setChart - The callback used to instantiate the chart instance in index.jsx to then be passed into all other components requiring chart functionality
 * @returns The organization chart of the current user, using the balkangraph module
 */
export const OrganizationChart = ({
  handleEditOnTheNode,
  nodes,
  setChart,
  toggleAddSupervisorModal,
  toggleUpdateUserSupervisorModal,
  selectedMetric,
}) => {
  const divRef = React.useRef();
  const auth = useSelector((state) => state.auth);

  const menuEnabled = () => {
    if (
      auth?.user?.roles?.includes("SUPER_ADMIN") ||
      auth?.user?.roles?.includes("ORG_ADMIN")
    ) {
      return true;
    } else {
      return false;
    }
  };
  function lightenDarkenColor(col, amt) {
    if (amt === 0) {
      return col;
    }
    var usePound = false;
    if (col[0] == "#") {
      col = col.slice(1);
      usePound = true;
    }

    var num = parseInt(col, 16);

    var r = (num >> 16) + amt;

    if (r > 255) r = 255;
    else if (r < 0) r = 0;

    var b = ((num >> 8) & 0x00ff) + amt;

    if (b > 255) b = 255;
    else if (b < 0) b = 0;

    var g = (num & 0x0000ff) + amt;

    if (g > 255) g = 255;
    else if (g < 0) g = 0;

    return (usePound ? "#" : "") + (g | (b << 8) | (r << 16)).toString(16);
  }
  function getKeyByValue(object, value) {
    return Object.keys(object).find((key) => object[key] === value);
  }

  React.useEffect(() => {
    const mappedNodes = nodes.map((e) => ({
      email: e.email,
      id: e.id,
      name: e.name,
      pid: e.pid,
      color: e.color,
      profileImage: e.profileImage,
      title: e.title,
      metric: selectedMetric ? e.performance : e.departmentName ?? "UNASSIGNED",
    }));

    const chart = new OrgChart(divRef.current, {
      template: "pmTemplate",
      mode: "light",
      lazyLoading: true,
      layout: OrgChart.mixed,
      nodes: mappedNodes,
      enableSearch: true,
      enableDragDrop: true,
      nodeMouseClick: OrgChart.action.none,
      tags: {
        orange: {
          template: "anaOrange",
        },
      },
      nodeContextMenu: !menuEnabled()
        ? {
            editUser: {
              text: "Edit",
              onClick: handleEditOnTheNode,
              icon: OrgChart.icon.edit(18, 18, "#039BE5"),
            },
          }
        : {
            add: {
              text: "Add",
              icon: OrgChart.icon.add(18, 18, "#FF8304"),
            },
            editUser: {
              text: "Edit",
              onClick: handleEditOnTheNode,
              icon: OrgChart.icon.edit(18, 18, "#039BE5"),
            },
            updateSupervisor: {
              text: "Update Supervisor",
              onClick: toggleUpdateUserSupervisorModal,
              icon: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="16px" height="16px" viewBox="0 0 16 16" version="1.1"><g id="surface1"><path style=" stroke:none;fill-rule:nonzero;fill:rgb(0%,0%,0%);fill-opacity:1;" d="M 7.984375 11.460938 C 10.59375 11.457031 12.335938 8.070312 12.335938 6.246094 C 12.335938 4.425781 12.328125 0.160156 7.984375 0.160156 C 3.644531 0.160156 3.636719 4.421875 3.636719 6.246094 C 3.636719 8.070312 5.378906 11.464844 7.984375 11.460938 Z M 14.398438 13.203125 C 13.417969 12.550781 10.59375 11.464844 10.59375 11.464844 L 8.757812 14.523438 L 8.421875 14.074219 L 8.855469 13.203125 L 7.984375 12.335938 L 7.113281 13.203125 L 7.550781 14.074219 L 7.210938 14.523438 L 5.378906 11.464844 C 5.378906 11.464844 2.554688 12.550781 1.574219 13.203125 C 0.59375 13.859375 0.160156 15.839844 0.160156 15.839844 L 15.839844 15.839844 C 15.839844 15.839844 15.554688 13.972656 14.398438 13.203125 Z M 14.398438 13.203125 "/></g></svg>',
            },
          },

      nodeBinding: {
        box_1: "",
        box_2: "",
        box_3: "",
        metric: "metric",
        name: "name",
        title: "title",
        img_0: "profileImage",
      },
    });

    chart.onField(function (args) {
      var color = "#fff";
      var lighter = lightenDarkenColor(color, 220);
      if (args.field === "box_1") {
        args.value = lighter;
      }
      //Metric box
      else if (args.field === "box_2") {
        if (!selectedMetric) {
          args.value =
            args.data.metric === "UNASSIGNED" ? "#D30000" : args.data.color;
        } else if (selectedMetric) {
          args.value =
            args.data.metric ===
            getKeyByValue(PERFORMANCE, PERFORMANCE.NOT_MEETING_EXPECTATIONS)
              ? "#D30000"
              : args.data.metric ===
                getKeyByValue(PERFORMANCE, PERFORMANCE.MEETING_EXPECTATIONS)
              ? "#FFBF00"
              : args.data.metric ===
                getKeyByValue(PERFORMANCE, PERFORMANCE.EXCEEDED_EXPECTATIONS)
              ? "#3CB043"
              : "#828282";
        }
      } else if (args.field === "box_3") {
        args.value = lighter;
      }
    });

    //Set chart center to loggedin user
    //
    chart.on("init", function () {
      chart.center(auth.user.id);
    });

    chart.load(mappedNodes);
    setChart(chart);
  }, [
    handleEditOnTheNode,
    nodes,
    setChart,
    toggleAddSupervisorModal,
    toggleUpdateUserSupervisorModal,
    selectedMetric,
  ]);

  return <div id="tree" className="node" ref={divRef} />;
};

**Comment by ZornitsaPesheva** [comment]
Please create a running code example in plain JavaScript here: https://code.balkan.app/org-chart-js/simple-example#JS

**Comment by ZornitsaPesheva** [comment]
Closing this issue as not active.
