### ISSUE TITLE
Conditional Color - Reg

### ISSUE THREAD

**Issue by lakshmipln** [BALKANGraph/OrgChartJS#788]
Conditional Color is not working in my code when return the data from database. code is attached here. could you please help us fix this 

    <meta name="viewport" content="width=device-width" />
    <title>OrgChart</title>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <script src="https://balkangraph.com/js/orgchart.js"></script>
    <style>
        html, body {
            width: 100%;
            height: 100%;
            padding: 0;
            margin: 0;
            overflow: hidden;
        }

        #tree {
            width: 100%;
            height: 100%;
        }

        .field_0 {
            font-family: Impact;
        }
        .node.abc rect {
            fill: #ff0000;
        }

        /*partial*/
        .node.QA rect {
            fill: #F57C00;
        }

        .node.Dev rect {
            fill: #039BE5;
        }

        .node.Marketing rect {
            fill: #FFCA28;
        }
    </style>
</head>
<body>
 
    <div id="tree"></div>
   <script>
 OrgChart.templates.green = Object.assign({}, OrgChart.templates.myTemplate);
        OrgChart.templates.green.node = '<rect x="0" y="0" height="80" width="300" fill="#48af56" stroke-width="1" stroke="#aeaeae" rx="40" ry="40"></rect>' +
            '<path d="M25,54 C25,32 55,32 55,54 L24,54" stroke="#fff" stroke-width="2" fill="#48af56"></path>' +
            '<circle stroke="#fff" stroke-width="2" fill="#48af56" cx="40" cy="30" r="8"></circle> ';

        var chart = new OrgChart(document.getElementById("tree"), {
            enableDragDrop: true,
            layout: OrgChart.mixed,
            filterBy: ['title', 'unit'],
            template: 'isla',
            menu: {
                pdf: { text: "Export PDF" },
                png: { text: "Export PNG" },
                csv: { text: "Export CSV" }
            },
            nodeMenu: {
                edit: { text: "Edit" },
                add: { text: "Add" },
                remove: { text: "Remove" },
                pdf: { text: "Export PDF" },
                png: { text: "Export PNG" }
            },
            nodeBinding: {
                field_0: "fullName",
                name: "fullName",
                field_1: "title",
                img_0: "img",
                title: "title", 
                image: "img",  
                tags: 'tags'
            },
            tags: {
                QA: {
                    template: "green"
                },
                yellow: {
                    template: "yellow"
                }
            },

            toolbar: {
                layout: true,
                zoom: true,
                fit: true,
                expandAll: true
            },
        });

        chart.on('update', function (sender, oldNode, newNode) {
            $.post("@Url.Action("UpdateNode")", newNode)
                .done(function () {
                    sender.updateNode(newNode);
                });
            return false;
        });

        chart.on('add', function (sender, node) {
            node.id = 0;
            node.pid = parseInt(node.pid);
            node.fullName = "John Smith";

            $.post("@Url.Action("AddNode")", node)
                .done(function (response) {
                    node.id = response.id;
                    sender.addNode(node);
                })

            return false;
        });

        chart.on('remove', function (sender, nodeId) {
            $.post("@Url.Action("RemoveNode")", { id: nodeId })
                .done(function () {
                    sender.removeNode(nodeId);
                })
            return true;
        });
       // alert(2);
        $.get("@Url.Action("Read")").done(function (response) {
           // alert(response);
            chart.load(response.nodes);
        });
   </script>

C# Code to  Assign the data
 List<NodeModel> studentList = new List<NodeModel>(); 
            studentList = (from DataRow dr in dt.Rows
                           select new NodeModel()
                           {
                               id = (dr["id"].ToString()),
                               pid = (dr["pid"].ToString()),
                               fullName = dr["first_name"].ToString(),
                               title = dr["position_title"].ToString(),
                               tags = dr["sto_tags"].ToString(),
                           }).ToList();

            var nodes = studentList;   // entities.Employees.Select(p => new NodeModel { id = p.Id, pid = p.ReportsTo, fullName = p.FullName });
            return Json(new { nodes = nodes }, JsonRequestBehavior.AllowGet);

Sample data

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/M04438/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/M04438/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

id | pid | fullName | title | img | tags
-- | -- | -- | -- | -- | --
7707356 | 0 | ABCDNAME1 | Position1 |   | abc
7706606 | 7707356 | ABCDNAME2 | Position2 |   | abc
7701915 | 7707356 | ABCDNAME3 | Position3 |   | abc
7706875 | 7707356 | ABCDNAME4 | Position4 |   | abc
7707267 | 7707356 | ABCDNAME5 | Position5 |   | abc
7702150 | 7707356 | ABCDNAME6 | Position6 |   | abc
7704438 | 7707356 | ABCDNAME7 | Position7 |   | abc
7704191 | 7702150 | ABCDNAME8 | Position8 |   | abc
7707298 | 7706875 | ABCDNAME9 | Position9 |   | abc
7707744 | 7707356 | ABCDNAME10 | Position10 |   | abc
7707218 | 7706875 | ABCDNAME11 | Position11 |   | abc
7707638 | 7707267 | ABCDNAME12 | Position12 |   | abc
7706601 | 7702150 | ABCDNAME13 | Position13 |   | abc
7707055 | 7706875 | ABCDNAME14 | Position14 |   | abc
7707206 | 7706875 | ABCDNAME15 | Position15 |   | abc
7707333 | 7706875 | ABCDNAME16 | Position16 |   | abc
7707411 | 7706875 | ABCDNAME17 | Position17 |   | abc
7707577 | 7704438 | ABCDNAME18 | Position18 |   | abc
7707657 | 7702150 | ABCDNAME19 | Position19 |   | abc
7707746 | 7706606 | ABCDNAME20 | Position20 |   | abc
7704946 | 7704438 | ABCDNAME21 | Position21 |   | abc
7705608 | 7702150 | ABCDNAME22 | Position22 |   | abc
7707349 | 7702150 | ABCDNAME23 | Position23 |   | abc
7301806 | 7706875 | ABCDNAME24 | Position24 |   | abc
282021 | 7707356 | Vacant Position | DGMPHR |   | QA
382021 | 7706875 | Vacant Position | MGPHR |   | QA
222122 | 7707356 | Vacant Position | 7AMTRG |   | QA
681920 | 7706875 | Vacant Position | ITDM |   | QA
112324 | 7706606 | Vacant Position | DMER |   | QA

</body>

</html>

**Comment by ZornitsaPesheva** [comment]
Here is a code demo for conditional color:
https://code.balkan.app/org-chart-js/conditional-color#JS

**Comment by ZornitsaPesheva** [comment]
But in your code I don't see any for cycle for adding the tags.

**Comment by ZornitsaPesheva** [comment]
But in your code I don't see any for cycle for adding the tags.

**Comment by lakshmipln** [comment]
The tag is return from database as field or please teach me how to create tag in script after database return

**Comment by ZornitsaPesheva** [comment]
Most probably the tags are not array of string in the nodes that you load.  
You can use console.log(chart.config.nodes) to see how the tags looks like.

**Comment by lakshmipln** [comment]
this my data tags : "[QA]"
and tried with tags : "QA" 

![1](https://github.com/BALKANGraph/OrgChartJS/assets/44156030/b4834d00-f06e-4fe8-9b6b-a6a6f3040084)

**Comment by ZornitsaPesheva** [comment]
should be ["QA"]

**Comment by lakshmipln** [comment]
Thank you, Now i am table to change the color based on tags value.  but in the export to pdf file the changed color values are not reflected, How you please suggest how to set this or i missed any configuration ?

**Comment by ZornitsaPesheva** [comment]
You can read here how to export styles: https://balkan.app/OrgChartJS/Docs/Exporting#styles
