### ISSUE TITLE
Loading Nodes only on window resize

### ISSUE THREAD

**Issue by maryammoshtoofar** [BALKANGraph/OrgChartJS#789]
Hey. It's me again!
I'm generating a binary tree using a recursive function and everything works fine and the nodes are all in the right place.
The only problem I have is when I load the page I can only see the first node in the tree. At first I thought there was something wrong with my function, took me a while and then I accidentally resized my window and all the remaining nodes appeared.
I can only see the nodes(except the first one) if I resize the window (the size doesn't matter as long as i resize) and they won't disapeear afterwards if go back to the original window size
If you need me to provide the code I'd be happy to, but maybe you've encountered this before and can give me a quick fix. I'd really appreciate it because the code is for creating a binary tree for a web3 smart contract and just looking at it gives me a headache :)

**Comment by ZornitsaPesheva** [comment]
Hi Maryam
Please create an [example](https://code.balkan.app/org-chart-js/simple-example#JS) in our Code app.

**Comment by maryammoshtoofar** [comment]
I think one of my functions is the culprit and the behavior has nothing to do with the chart itself because when I created the example in your app using a static array, everything is working just fine.
Thank you for the help. at least now I know where to look for the bug

**Comment by maryammoshtoofar** [comment]
hey just wanted to let you know I fixed the issue. I couldn't find the cause of the problem but I set an interval to reload the chart and that fixed the problem
