### ISSUE TITLE
Row(level) expand Feature

### ISSUE THREAD

**Issue by sv-dev1** [BALKANGraph/OrgChartJS#79]
I'm using your graph for uni-level.Now I’m in trouble to customize the graph .
please help me.I want collapse the row and collapse user show like dot(.)  in between users,if user are more then 4 in particular row(level). On the click of dot(.),user will expand.

Please check attachment and understand what i want .

We will waiting for your answer.

![design](https://user-images.githubusercontent.com/8041662/56733308-5ec43280-677d-11e9-87f1-b2dd060f6408.png)

**Comment by plamen-peshev** [comment]
When you expand dot, which one form the same level (row) will hide?

**Comment by sv-dev1** [comment]
> When you expand dot, which one form the same level (row) will hide?

Every Dot represent the user.if we have 7 users in a row(level).4 will be show and 3 will be represent as dot .When we click on dot ,structure of that user will be expand

**Comment by nehag123** [comment]
I need to know the same customization in org chart. If you able to get it then please let me know

**Comment by plamen-peshev** [comment]
https://balkangraph.com/OrgChartJS-Demos/CustomTemplateAdvanced


![image](https://user-images.githubusercontent.com/49443821/56757511-14eb4480-679d-11e9-9904-ac9dd0221fd9.png)

**Comment by sv-dev1** [comment]
> https://balkangraph.com/OrgChartJS-Demos/CustomTemplateAdvanced
> 
> ![image](https://user-images.githubusercontent.com/49443821/56757511-14eb4480-679d-11e9-9904-ac9dd0221fd9.png)

I have no word to say Thanks.Really this is big help to me .Thank you so much.

**Comment by nehag123** [comment]
Can you tell me how to show name as tooltip on image or dots?

**Comment by ZornitsaSerbezova** [comment]
Tooltip demo:
https://balkangraph.com/OrgChartJS-Demos/Tooltip
