### ISSUE TITLE
Changing node color based on a per node basis

### ISSUE THREAD

**Issue by ashwin99** [BALKANGraph/OrgChartJS#790]
Imagine my node data having a field called fillColor. Is there anyway I can use that to change the color of the node? I cannot use tags and template because the color is data driven and I don't know these valued ahead of time. I don't think (but let me know how if I have it wrong) I can use data-node-id since that is static, and I need to do this more dynamically.

Thanks for your help and Balkan is awesome!!!

**Comment by ZornitsaPesheva** [comment]
Did you try to add tags dynamically too?
https://code.balkan.app/org-chart-js/conditional-color-simple-example#JS
