### ISSUE TITLE
Want to change the line presentation

### ISSUE THREAD

**Issue by lakshmipln** [BALKANGraph/OrgChartJS#791]
Dear team,

Want to change the line presentation follow.  kindly suggest how to map this.   

Existing!
![2](https://github.com/BALKANGraph/OrgChartJS/assets/44156030/1f3fcdc6-b4da-4f98-b114-27b0e6a2f64d)

Required  ( because  its misleading the reporting structure)

![3](https://github.com/BALKANGraph/OrgChartJS/assets/44156030/eadffe77-7397-44aa-93be-a80c0096c7a6)

**Comment by ZornitsaPesheva** [comment]
Here is a code demo:
https://code.balkan.app/org-chart-js/issue-791#JS

**Comment by lakshmipln** [comment]
its working .. Thank you for your support
