### ISSUE TITLE
generate dotted lines by levels

### ISSUE THREAD

**Issue by PhysicApp** [BALKANGraph/OrgChartJS#793]
Hello, good morning, I wanted to ask a question. I need to see how to generate those dotted lines according to the level of the employees and that the nodes fit as shown according to the level

I attach an example:

![image](https://github.com/BALKANGraph/OrgChartJS/assets/84802936/2109f8f3-dd5f-43e9-b0ae-2290edc8ddbc)

**Comment by ZornitsaPesheva** [comment]
Hi @PhysicApp 
What you can do is to put the whole chart in a subtree with such background:
https://code.balkan.app/org-chart-js/node-background-image#JS

**Comment by PhysicApp** [comment]
Is there a way that the nodes, with this indicator, are drawn at the same level, for example: Directors are displayed at the same height, Analysts are displayed at another height

Se muestra de esta manera y quiero que se muestre como en la segunda IMAGEN:
![image](https://github.com/BALKANGraph/OrgChartJS/assets/84802936/4b17690f-4eda-45ee-9cba-74d327f1d5b0)


image of what is needed:

![image](https://github.com/BALKANGraph/OrgChartJS/assets/84802936/7f2090a5-ee9a-42b1-b326-1831a6fbaf7c)

**Comment by ZornitsaPesheva** [comment]
There is no easy way. Out of the box there is no such functionality, but you can try to do it by setting levels someway.
You can try using structure level
https://balkan.app/OrgChartJS/Docs/NodeAPI
See this example here: https://code.balkan.app/complex-layout#JS

**Comment by ZornitsaPesheva** [comment]
Now you can use this code demo for the levels:
https://balkan.app/OrgChartJS/Demos/levels-background
