### ISSUE TITLE
Help : Need clink label besides arrow

### ISSUE THREAD

**Issue by Abhishekkhh** [BALKANGraph/OrgChartJS#794]
Hi Team,
PFA, I want the text to be besides the red circles (besides or near to the arrow)

![clink text](https://github.com/BALKANGraph/OrgChartJS/assets/96596671/d64c7190-ec01-4890-a30f-1e8aad7a2d20)

**Comment by ZornitsaPesheva** [comment]
Here is a code demo on how to move the clink label:
https://code.balkan.app/org-chart-js/move-clink-label#JS

**Comment by Abhishekkhh** [comment]
Hi ZornitsaPesheva, Thanks for your reply, but please find the below screenshot, I want the text to look like red color text and the text must be straight no matter the links curve.
![clink text](https://github.com/BALKANGraph/OrgChartJS/assets/96596671/9c781af8-d392-4f62-9e5f-b30830823e42)

**Comment by ZornitsaPesheva** [comment]
For that it is better to use node fields:
https://code.balkan.app/org-chart-js/node-fields-for-clinks-labels.#JS

**Comment by Abhishekkhh** [comment]
Hi ZornitsaPesheva, You have hardcoded x and y values in field template which  x="175" y="135" but in my case my C-links would connect to any block so if I keep this same values in X and Y it's becoming haywire.

Can you please suggest me anyway by which I can just mention C-link and its X and Y values would come automatically or dynamically?

**Comment by plamen-peshev** [comment]
In the latest version you can override OrgChart.clinkLabelPosition function 

See the following code demo https://code.balkan.app/clinklabelposition#JS, clear your browser cache before opining the demo

you can get the latest version from here: https://orgchartjs.balkan.app/
