### ISSUE TITLE
Photo is not exporting while doing PDF / Image export

### ISSUE THREAD

**Issue by lakshmipln** [BALKANGraph/OrgChartJS#795]
Photo is not exporting while doing PDF / Image export. 

And is it possible to display the summary count table in bottom of the page with legend, like open position, additional position

**Comment by ZornitsaPesheva** [comment]
To be able to export it, the photo needs to be public.
So you should be able to browse it in any browser in the internet, 
Here is a code demo on how to add a legend:
https://code.balkan.app/org-chart-js/html-inside-chart#JS

**Comment by lakshmipln** [comment]
sir,  1.  is there any alternative for public , reasons is the employee photo can not be made public and not good for intranet sites 

2. how to fetch box counts in legend area

**Comment by ZornitsaPesheva** [comment]
1. You can have your own export service: https://github.com/BALKANGraph/export-service
2. You can get the data from the nodes or from chart.config.nodes if needed.
