### ISSUE TITLE
Right Partner Template Text moving out of Template Box

### ISSUE THREAD

**Issue by Abhishekkhh** [BALKANGraph/OrgChartJS#796]
Hi Team,
PFA, I need the text in right-partner template to break on " , " (comma) so a new line is created for each of the records, also the right-partner box needs to have dynamic height/ width to contain the text as the text can contain many characters.

![Template](https://github.com/BALKANGraph/OrgChartJS/assets/96596671/4783d604-b404-41a4-82fc-20a48205b03d)

**Comment by ZornitsaPesheva** [comment]
Hi 
What you can do is to break the data into several fields before loading the chart.
Then you can create a dynamic template based on the number if the fields.
Here is a code demo:
https://code.balkan.app/dynamic-height#JS

**Comment by Abhishekkhh** [comment]
Hi,
I want to break text on comma so that it can be taken to a new line.
I can't keep on defining 10's / 20's of text1, text2 properties to handle new line as per your solution.

**Comment by ZornitsaPesheva** [comment]
No, mu solution is to do from this:
`data: "text1,text2,text3"`
this: 
data1: "text1", data2: "text2", data3: "text3"
