### ISSUE TITLE
Makes connection ghost with partner

### ISSUE THREAD

**Issue by AbrahamMoralesHueto** [BALKANGraph/OrgChartJS#797]
When a partner connection is made and it has a child, a line is also drawn on the parent node. In this example we can see that node 24 is related to node 30, but for some reason node 25 also draws a line to node 30, but there is no relationship between them.

`//JavaScript
OrgChart.templates.noMenuTemplate = Object.assign({}, OrgChart.templates.olivia);
OrgChart.templates.noMenuTemplate.nodeMenuButton = '';
OrgChart.templates.subLevel.link = '<path stroke-linejoin="round" stroke="#aeaeae" stroke-width="1px" fill="none" d="{rounded}" />';

var chart = new OrgChart(document.getElementById("tree"), {
    enableSearch: false,
    template: 'olivia',
    mouseScrool: OrgChart.none,    
    mode: 'dark',
    nodeBinding: {
        field_0: "namePrueba",
        field_1: "id"
    },
    nodeMenu: {
        subLevels0: { text: "Move to sub level 0", icon: OrgChart.icon.details(24, 24, "#7A7A7A"), onClick: function (nodeId) { chart._get(nodeId).tags = ["sub level 0"]; chart.draw(); } },
        subLevels1: { text: "Move to sub level 1", icon: OrgChart.icon.details(24, 24, "#7A7A7A"), onClick: function (nodeId) { chart._get(nodeId).tags = ["sub level 1"]; chart.draw(); } },
        subLevels2: { text: "Move to sub level 2", icon: OrgChart.icon.details(24, 24, "#7A7A7A"), onClick: function (nodeId) { chart._get(nodeId).tags = ["sub level 2"]; chart.draw(); } },
        subLevels3: { text: "Move to sub level 3", icon: OrgChart.icon.details(24, 24, "#7A7A7A"), onClick: function (nodeId) { chart._get(nodeId).tags = ["sub level 3"]; chart.draw(); } }
    },
    tags: {
        "lvl0": {
            subLevels: 0,
        },
        "lvl1": {
            subLevels: 1
        },
        "lvl2": {
            subLevels: 2
        },
        "lvl3": {
            subLevels: 3
        },
        "lvl4": {
            subLevels: 4
        },
        "lvl5": {
            subLevels: 5
        },
        "lvl6": {
            subLevels: 6
        },
        "lvl7": {
            subLevels: 7
        },
        "lvl8": {
            subLevels: 8
        },
        "lvl9": {
            subLevels: 9
        },
        "lvl10": {
            subLevels: 10
        },
        "lvl11": {
            subLevels: 11
        },
        "lvl12": {
            subLevels: 12
        },
        "lvl13": {
            subLevels: 13
        }
    },

});

var nodes = [
    { id: 1, tags: ["lvl0"], namePrueba: "Director" },

    //AREA EJEMPLO
    { id: 23, pid: 1, tags: ["lvl1"], namePrueba: "Director" },
    { id: 24, pid: 25, tags: ["lvl0", "left-partner"], namePrueba: "Gerente" },
    { id: 25, pid: 1, tags: ["lvl2"], namePrueba: "Gerente" },

    { id:28, pid: 25, tags: ["lvl9"], namePrueba: "Analista" },
    { id:29, pid: 28, tags: ["lvl0", "left-partner"], namePrueba: "Analista" },

    { id:30, pid: 24, tags: ["lvl9"], namePrueba: "Analista" },

    { id: 26, pid: 1, tags: ["lvl2"], namePrueba: "Gerente" },
    { id: 27, pid: 26, tags: ["lvl1"], namePrueba: "Jefe" },

    //Area prueba
    { id: 16, pid: 1, tags: ["lvl2"], namePrueba: "Gerente" },
    { id: 17, pid: 16, tags: ["lvl1"], namePrueba: "Jefe" },
    { id: 18, pid: 17, tags: ["lvl1"], namePrueba: "Lider" },
    { id: 19, pid: 18, tags: ["lvl1"], namePrueba: "Coordinador" },
    { id: 20, pid: 19, tags: ["lvl1"], namePrueba: "Consultor" },
    { id: 21, pid: 20, tags: ["lvl1"], namePrueba: "Analista" },
    { id: 22, pid: 21, tags: ["lvl1"], namePrueba: "Auxiliar" },
];

chart.on('field', function (sender, args) {
    if (args.name == "subLevel") {
        var node = sender.getNode(args.node.id);
        // if (node.tags.length) {
        //     args.value = node.tags[0];
        // }
    }
});

chart.load(nodes);`

![image](https://github.com/BALKANGraph/OrgChartJS/assets/68711634/ba88f6f3-2181-4668-9b3a-2a1cdbc1fce9)

**Comment by ZornitsaPesheva** [comment]
We don't support sublevels for partners and for the children of the partners.

**Comment by AbrahamMoralesHueto** [comment]
> We don't support sublevels for partners and for the children of the partners.

Don't they plan on fixing that?

**Comment by ZornitsaPesheva** [comment]
Not for the near future, but we are developing our products constantly, so it is not impossible to be implemented.
