### ISSUE TITLE
Cannot read properties of null

### ISSUE THREAD

**Issue by eparentrq** [BALKANGraph/OrgChartJS#799]
![image](https://github.com/BALKANGraph/OrgChartJS/assets/133912609/89a18cb4-aab6-42fb-bdc9-5ee3dd8b36c6)

Can you help me with this issue.
Thanks.

**Comment by ZornitsaPesheva** [comment]
Please isolate the issue in a simple Code example:
https://code.balkan.app/org-chart-js/simple-example#JS

**Comment by eparentrq** [comment]
`<reference path="OrgChart.d.ts" />
<!DOCTYPE html>
<html lang="en">
<head>
   

    <title>Organigramme DSFATAQ</title>
</head>
<script src="https://saaprod/soutien_tache/organigramme/orgChart/OrgChart.js"></script>
<script>
    var chart = new OrgChart(document.getElementById("chart-container"), {
    template: "ula",
    mouseScrool: OrgChart.none,
    nodeBinding: {
        field_0: "Employee Name",
        field_1: "Title",
        img_0: "Photo"
    },
    editForm:{
        photoBinding: 'Photo'
    },
    nodeMenu: {
        details: { text: "Details" },
        edit: { text: "Edit" },
        add: { text: "Add" },
        remove: { text: "Remove" }
    }
});

chart.on('init', function (sender) {
    sender.editUI.show(1);
});

chart.load([
    { id: 1, "Employee Name": "Denny Curtis", Title: "CEO", Photo: "https://cdn.balkan.app/shared/2.jpg" },
    { id: 2, pid: 1, "Employee Name": "Ashley Barnett", Title: "Sales Manager", Photo: "https://cdn.balkan.app/shared/3.jpg" },
    { id: 3, pid: 1, "Employee Name": "Caden Ellison", Title: "Dev Manager", Photo: "https://cdn.balkan.app/shared/4.jpg" },
    { id: 4, pid: 2, "Employee Name": "Elliot Patel", Title: "Sales", Photo: "https://cdn.balkan.app/shared/5.jpg" },
    { id: 5, pid: 2, "Employee Name": "Lynn Hussain", Title: "Sales", Photo: "https://cdn.balkan.app/shared/6.jpg" },
    { id: 6, pid: 3, "Employee Name": "Tanner May", Title: "Developer", Photo: "https://cdn.balkan.app/shared/7.jpg" },
    { id: 7, pid: 3, "Employee Name": "Fran Parsons", Title: "Developer", Photo: "https://cdn.balkan.app/shared/8.jpg" }
]);
</script> 
<body>

    <div id="chart-container"></div>

   
</body>
</html>`

**Comment by eparentrq** [comment]
Finaly, I found my solution.
I move my script after my body and it works.
