### ISSUE TITLE
Change orientation are a select

### ISSUE THREAD

**Issue by doarsal** [BALKANGraph/OrgChartJS#8]
Hello, I would like to know how I can change the orientation of the OrgChart dynamically with a select. Can you help me, please? I have the following script, but it does not work correctly.

document.getElementById("selectOrientation").addEventListener("change", function () {
chart.config.orientation = this.value;
chart.draw();
});

**Comment by BALKANGraph** [comment]
You are on the right direction

 ```
chart.config.orientation = BALKANGraph.orientation.left;
chart.draw();
```

I have created a demo for you: https://jsfiddle.net/BALKANGraph/8dtjpwy2/

**Comment by doarsal** [comment]
@BALKANGraph  wow excelent.
thank you
