### ISSUE TITLE
Need detailed instructions to import from CSV

### ISSUE THREAD

**Issue by kmmcdan** [BALKANGraph/OrgChartJS#80]
I need someone to detail how we can import our data from CSV. I can import but I am missing the details about how to save the changes to the server. No steps are given and I have been pointed to a demo that gives no details or instruction. I am not a programmer and we have over 200 employees that I am not prepared to enter manually. Can someone please detail the process to implement this feature?

I have been told that I need to post the data to my server and save and then import. OK post it where? In what format? How does the script then know where to pull it from? Instructions must be provided please, thank you.

**Comment by plamen-peshev** [comment]
[test.zip](https://github.com/BALKANGraph/OrgChartJS/files/3119073/test.zip)

We have added "import" event to simplify saving the data to your server


Here is the code:

```
          var chart = new OrgChart(document.getElementById("tree"), {
                nodeBinding: {
                    field_0: "id",
                    field_1: "pid",
                },
                menu:{
                    import: {
                        text: 'Import CSV',
                        icon: '',
                        onClick: function() { chart.importCSV(); }
                    }
                }    
            });

            chart.on('import', function(sender, nodes){
                var postDate = JSON.stringify(nodes);

                var url = '[your server end point]';
                var xhttp = new XMLHttpRequest();
                xhttp.onreadystatechange = function() {
                     if (this.readyState == 4 && this.status == 200) { 
                         //SUCCESS  
                     }
                };
                xhttp.open("POST", url, true);
                xhttp.setRequestHeader("Content-Type", "application/json");

                xhttp.send(postDate);

                return false; to cancel the operation
            });       

            chart.load([
                {id: 1}
            ]);
```

Where 
 - [your server end point] is a url to you server
- postDate is stringified json object of nodes that you have to save in your database
