### ISSUE TITLE
How about if trial is expired?

### ISSUE THREAD

**Issue by akbardwi** [BALKANGraph/OrgChartJS#800]
Hello, i want to ask. How about if trial is expired, can org chart is show or not?
I think is good for open source but with limited feature not in duration of use

**Comment by ZornitsaPesheva** [comment]
Hi, Org Chart JS not open source. It is [paid](https://balkan.app/OrgChartJS/Pricing).
It will stop working after the trial expiration and will not be shown,
There are other org chart tools that have less features and are free.
The purpose of this one is to have lot of features,
