### ISSUE TITLE
Grouping issue - Lost count of people in one departement

### ISSUE THREAD

**Issue by eparentrq** [BALKANGraph/OrgChartJS#803]
Hi

I have 10 persons in one departement  and when I group the departement only 5 persons are showing is there a solution to show how more person are in the department? 

Like this :

![image](https://github.com/BALKANGraph/OrgChartJS/assets/133912609/a6dae05f-ccb0-4cb9-b02b-9b3f5e516a47)

Thank you

**Comment by ZornitsaPesheva** [comment]
Hi, we have created a code demo for you:
https://code.balkan.app/org-chart-js/more-images-in-minimized-group#JS

**Comment by eparentrq** [comment]
Thank you exactly what I needed 👍
