### ISSUE TITLE
How to change the place of origin

### ISSUE THREAD

**Issue by Adalk033** [BALKANGraph/OrgChartJS#804]
Hello devs, I have a question if it is possible to change the position of the line where the origin of the people who are dependents comes from as in the image

![git](https://github.com/BALKANGraph/OrgChartJS/assets/37385524/5cd706f3-615f-469f-8d37-31bee694599a)

**Comment by ZornitsaPesheva** [comment]
Hi, changing the links as in the screenshot is not supported.

**Comment by Adalk033** [comment]
Thanks so much, I hope you can add it as an improvement
