### ISSUE TITLE
how to implement when you click a node to display only that node and it's child node

### ISSUE THREAD

**Issue by joshuacos1977** [BALKANGraph/OrgChartJS#807]
When you click a node,it excludes all of the other nodes and only highlight or display clicked node and it's child nodes

**Comment by plamen-peshev** [comment]
See the following Code demos:

- https://code.balkan.app/org-chart-js/highlight#JS
- https://code.balkan.app/org-chart-js/highlight-on-load#JS
- https://code.balkan.app/org-chart-js/highlight-on-node-click#JS
- https://code.balkan.app/organizational-chart-path-highlighting-and-selection#JS

**Comment by joshuacos1977** [comment]
The first example is the great one that i want to implement.Thank you Plemen

**Comment by joshuacos1977** [comment]
It is not working as it is expected under react application.It blur the whole org-chart.

**Comment by joshuacos1977** [comment]
Fixed the issue when implemented on a react application

**Comment by ZornitsaPesheva** [comment]
If your ids are numbers, you may need to use this:
Number(nodeElements[i].getAttribute('data-n-id'))
as in other case you compare number with string

**Comment by joshuacos1977** [comment]
that's totally what i needed to fix  the issue
