### ISSUE TITLE
Question regarding to highlighting 

### ISSUE THREAD

**Issue by joshuacos1977** [BALKANGraph/OrgChartJS#808]
[](https://code.balkan.app/organizational-chart-path-highlighting-and-selection#JS)
the link above demonstrated how to highlight child node to parent node.
Can you explain the line of the code below:
chart.onInit(() => {
  setHighlightStyle(chart.getNode(5), 5);
});
based on the documentation:
  getNode(nodeId: string | number): OrgChart.node;

5 is nodeId either string or number in that case it is number.
so why it is 5?

**Comment by joshuacos1977** [comment]
[](https://code.balkan.app/organizational-chart-path-highlighting-and-selection#JS)

**Comment by joshuacos1977** [comment]
[https://code.balkan.app/organizational-chart-path-highlighting-and-selection#JS]

**Comment by joshuacos1977** [comment]
here is the code link above

**Comment by ZornitsaPesheva** [comment]
This is just to show some highlight on initial load. We have selected 5 for the example and we highlight nodes from 5 to the root.
