### ISSUE TITLE
X scrolling doesn't work when holding down shift key

### ISSUE THREAD

**Issue by TheOfficer2303** [BALKANGraph/OrgChartJS#809]
<img width="944" alt="Screenshot 2023-11-15 at 16 31 09" src="https://github.com/BALKANGraph/OrgChartJS/assets/76702547/ee7e2c81-810b-4b9d-91ba-5122134d889b">

It says here that holding down Shift key should scroll left/right but it scrolls up/down, just like when not holding Shift.
mouseScrool property is set to OrgChart.action.scroll

**Comment by ZornitsaPesheva** [comment]
What is your browser?

**Comment by TheOfficer2303** [comment]
chrome

**Comment by ZornitsaPesheva** [comment]
Windows? What version?

**Comment by TheOfficer2303** [comment]
Mac OS 12.3
Chrome version  119.0.6045.123

**Comment by plamen-peshev** [comment]
The issue has been addressed in the latest version 8.13.14

Clear your browser cache and test [this Code demo ](https://code.balkan.app/issue-809#JS)

You can get the latest version from [here](https://orgchartjs.balkan.app)

**Comment by TheOfficer2303** [comment]
Great, it works now! Thank you for the support!
