### ISSUE TITLE
Server error (500) in response

### ISSUE THREAD

**Issue by ihorkovalenko27** [BALKANGraph/OrgChartJS#810]
Hi, guys! I need to improve the structure for my company, but I had some issue when run app locally. Your server response with error (500 server, CORS policy - https://uk-s-balkangraph.azurewebsites.net/api/OrgChartJS ). I checked my internet connections many times - it's good.  How we can fix it? Screenshots attached. Thank you!

![Screenshot from 2023-11-22 16-23-23](https://github.com/BALKANGraph/OrgChartJS/assets/77886931/7f75f6c3-ad40-49ba-983f-a33488fe278c)
![Screenshot from 2023-11-22 16-20-25](https://github.com/BALKANGraph/OrgChartJS/assets/77886931/bcf0b4e7-c53d-40a1-9413-ab46ff4658f6)
![Screenshot from 2023-11-22 16-18-46](https://github.com/BALKANGraph/OrgChartJS/assets/77886931/49af56dc-02bb-447c-b823-ddcbdfd0c3ac)

**Comment by ZornitsaPesheva** [comment]
Please get the latest version and try again.
