### ISSUE TITLE
Unable to run chart with Pro. lisence (ver7.5)

### ISSUE THREAD

**Issue by kimthach346** [BALKANGraph/OrgChartJS#811]
Dear OrgChart support team,

I need the guide on how to implement the chart online. In my case, it shows  CORS error, but when I fix it using web's plugin, then it shows another "Internal server error" 500.
I've read the Doc already but still can't find a way. 
Thanks a lot.

**Comment by ZornitsaPesheva** [comment]
Please follow this installation guide:
https://balkan.app/OrgChartJS/Docs/InstallLicensedVersion

**Comment by kimthach346** [comment]
Thank for your quick answer, i'm using React for front-end. Still get this error below
![z4910973625998_ea7c01290cb7edfc63ffe338e9cb563b](https://github.com/BALKANGraph/OrgChartJS/assets/52098040/b4150c34-7006-4fe7-a39c-e07b05467e2e)

![z4911021051993_a95e9df9586fa391e5456c53bfafce96](https://github.com/BALKANGraph/OrgChartJS/assets/52098040/f8e3b751-c401-4fee-8a2a-90fc505eb88f)

**Comment by ZornitsaPesheva** [comment]
Please try Ctrl+F5
