### ISSUE TITLE
Org-Chart: Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by I-sale7** [BALKANGraph/OrgChartJS#812]
Greetings,

During the implementation of 3000 nodes into the OrgChart library, we encountered an error:

Uncaught RangeError: Maximum call stack size exceeded

This issue is associated with the following method: OrgChart.local._getNodeHeight = function (node, config). The error manifests when attempting to connect numerous of nodes directly under a single root ID.

**Comment by ZornitsaPesheva** [comment]
I am closing this issue as inactive.
