### ISSUE TITLE
License Detail 

### ISSUE THREAD

**Issue by irenejoy15** [BALKANGraph/OrgChartJS#813]
Good day. 

I would like to ask if after 30 days will the OrgChart.js expire? 

If yes. If I buy the license, I am only planning the OrgChart.js will be deployed to our server via ip address([192.168.0.2/project/js/orgchart.js](http://192.168.0.2/project/js/orgchart.js)) or Vhost(sample/application/js/orgchart.js) which will not be accessed outside. 

Will I still need the license?

Thank you very much.

**Comment by ZornitsaPesheva** [comment]
Good day
To use Org Chart JS you need to purchase a license even if you use it offline.

**Comment by irenejoy15** [comment]
Noted on that. I am still on a development phase localhost then I am planning to upload to our server via http//webapplication(will not be access outside). I'm planning to buy the PROFESSIONAL License which is one Internet or Intranet website domain. Will transferring from localhost to Vhost affects the license?

**Comment by ZornitsaPesheva** [comment]
You can change the domain later and you can use the same license for localhost and testing, but you can have only one production domain without subdomains.

**Comment by irenejoy15** [comment]
Noted thank you very much.
