### ISSUE TITLE
When i have 1000 users on org-chart.

### ISSUE THREAD

**Issue by joshuacos1977** [BALKANGraph/OrgChartJS#814]
I have 1000 users on org-chart but when i scroll or zoom in all of the nodes empty.the screenshot is below.
![Screenshot 2024-01-08 121749](https://github.com/BALKANGraph/OrgChartJS/assets/28411895/55f7a16d-c4dc-413d-b97c-1792603f69af)
after scroll or zoom in the image is below.
![Screenshot 2024-01-08 121837](https://github.com/BALKANGraph/OrgChartJS/assets/28411895/6f1889f1-ec86-4f5f-b9a1-0c6722e9e582)

**Comment by ZornitsaPesheva** [comment]
Do you use the latest version?

**Comment by joshuacos1977** [comment]
Yes

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ZornitsaPesheva** [comment]
Please edit the above example to isolate the issue.

**Comment by joshuacos1977** [comment]
It works fine with 100-200 users but  with 1000 users issue arise

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ZornitsaPesheva** [comment]
https://code.balkan.app/org-chart-js/1000-nodes#JS

**Comment by joshuacos1977** [comment]
It seems like it works fine.Thank you very much for your quick response

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
