### ISSUE TITLE
Cannot edit custom template sublevel links

### ISSUE THREAD

**Issue by george-seed** [BALKANGraph/OrgChartJS#815]
I am building an org-chart and am having an issue with my custom template for filtered items. Specifically I want to prevent sublevel links from rendering.

I know I can change the rendering for sublevels at the templates level, but this removes sublevel links for my entire org-chart.

`OrgChart.templates.subLevel.link = '';
`

If I'm using a custom template (to remove nodes when filtering) there is access for link, no access for subLevel.link - it does not appear to be available for custom templates.

```
OrgChart.templates.filtered = Object.assign({}, OrgChart.templates.ana);
OrgChart.templates.filtered.size = [0, 0];
OrgChart.templates.filtered.node = '';
OrgChart.templates.filtered.link = '';
OrgChart.templates.filtered.subLevel.link = ''; // THIS WILL CAUSE AN ERROR
```

So when I want to filter the tree and apply my custom template to the nodes that are to be filtered out

```
tags: {
    filter: {
        template: 'filtered',
    },
```

Everything gets the custom template except for subLevel links which remain visible.

Is this a feature that is available, or is there an alternative way to do this?

It's frustrating to be able to customise links but not the sublevel links. It means when I am filtering my org chart I end up with lines remaining.

**Comment by ZornitsaPesheva** [comment]
Here isa code demo on how to hide sublevel nodes:
https://code.balkan.app/org-chart-js/hide-sublevel-links-for-filtered-nodes#JS

**Comment by george-seed** [comment]
Fantastic, this is a very nice solution. Happy to close this as resolved.
