### ISSUE TITLE
Unable to see the Icons in the Print PDF

### ISSUE THREAD

**Issue by singh-cdn** [BALKANGraph/OrgChartJS#818]
currently we can see the icons used inside the template are not coming in the PDF for printing , however it is visible in the template. I am using apex Universal icon fa-tree-org.
[MyFileName (3).pdf](https://github.com/BALKANGraph/OrgChartJS/files/14161323/MyFileName.3.pdf)

![Node template](https://github.com/BALKANGraph/OrgChartJS/assets/104981368/fe3e5d6b-6388-4a73-aa69-356bc5214400)

**Comment by ZornitsaPesheva** [comment]
Hi, check if this doc page will help:
https://balkan.app/OrgChartJS/Docs/Exporting#styles

**Comment by singh-cdn** [comment]
Hi Zornitsa,

We want to use font-awesom icon , currently we are using fa-tree-org
& fa-sitemap
Icons - Universal Theme (oracle.com)
<https://apex.oracle.com/pls/apex/f?p=42:icons>

**Comment by singh-cdn** [comment]
This is the piece of HTML that we are using - <div style="position: absolute; bottom: 0; left: 0; font-size: 10px; margin-bottom: -10px;">
    <i style="font-size: 10px; margin-top: 8px;" class="fa fa-sitemap"></i> 
    <%= TP %>,<%= TOP %>
</div>
<div style="position: absolute; bottom: 0; right: 0; font-size: 10px; margin-bottom: -10px;">
    <i style="font-size: 10px; margin-top: 8px;" class="fa fa-tree-org"></i> 
    <%= CTP %>,<%= CTOP %>
</div>

**Comment by ZornitsaPesheva** [comment]
Here is a code demo with google icons:
https://code.balkan.app/org-chart-js/google-icons#JS
