### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by naveganth** [BALKANGraph/OrgChartJS#822]
### **_My work so far_**

![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/0395050e-17b2-442c-a1e0-e38ebf18d24c)

1. How to make it so the camera is free and doesn't center on nodes?

2. How to make the text increase the size of the node according to text?
   ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/16f5c165-d916-4677-b666-b14c300559df)

3. How to make a field_0 show only the first two names of a person and not show elipsis?
   ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/c64619a2-b8f8-4822-b8ff-8ec40c380317)

4. How to make a complex layout like in the image bellow? (In the node SGP In the first image)
    ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/68b43d7b-b4a4-4585-8ee2-a0cc305250a2)

5. How to make all the "groups" minimized by default like this:
    ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/6bb31af9-7f73-4b43-93b1-7ce5c35d16ce)

6. How to make the lines coming from "secretaria" round?
   ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/ac54b673-37a8-462f-8126-ec7c66a314a6)

### The code:

```
OrgChart.VERTICAL_CHILDREN_ASSISTANT = true;
OrgChart.templates.myTemplate = Object.assign({}, OrgChart.templates.ula);
OrgChart.templates.group.min = Object.assign({}, OrgChart.templates.group);


OrgChart.templates.myTemplate.field_0 = "<text " + OrgChart.attr.width + '="150" style="font-family: Montserrat; sans-serif; font-weight: 700; font-size: 14px; text-anchor: left;" fill="#ffffff" x="90" y="45">{val}</text>';
OrgChart.templates.myTemplate.field_1 = "<text " + OrgChart.attr.width + '="145" ' + OrgChart.attr.text_overflow + '="multiline" style="font-family: Montserrat; sans-serif; font-weight: 400; font-size: 12px;" fill="#ffffff" x="90" y="60">{val}</text>';
OrgChart.templates.myTemplate.field_2 = "<text " + OrgChart.attr.width + '="145" ' + OrgChart.attr.text_overflow + '="multiline" style="font-family: Montserrat; sans-serif; font-weight: 400; font-size: 12px;" fill="#ffffff" x="90" y="75">{val}</text>';
OrgChart.templates.myTemplate.field_3 = "<text " + OrgChart.attr.width + '="145" ' + OrgChart.attr.text_overflow + '="multiline" style="font-family: Montserrat; sans-serif; font-weight: 400; font-size: 12px;" fill="#ffffff" x="91" y="90">{val}</text>';


OrgChart.templates.myTemplate.node = '<rect x="0" y="0" height="{h}" width="{w}" fill="#002580" stroke-width="1" stroke="#aeaeae"></rect><line x1="0" y1="0" x2="250" y2="0" stroke-width="5" stroke="#00994c"></line>';
OrgChart.templates.myTemplate.img_0 = '<clipPath id="{randId}"><rect width="90" height="119.5"></rect></clipPath><image preserveAspectRatio="xMidYMid slice" clip-path="url(#{randId})" xlink:href="{val}" x="0.5" y="1" width="80" height="120"></image>';
OrgChart.templates.myTemplate.nodeMenuButton = '<g style="cursor:pointer;" transform="matrix(1,0,0,1,225,105)" ' + OrgChart.attr.control_node_menu_id + '="{id}"><rect x="-4" y="-10" fill="#000000" fill-opacity="0" width="22" height="22"></rect><circle cx="0" cy="0" r="2" fill="#ffffff"></circle><circle cx="7" cy="0" r="2" fill="#ffffff"></circle><circle cx="14" cy="0" r="2" fill="#ffffff"></circle></g>'

//configuração group
OrgChart.templates.group.min.field_0 = '<text data-width="300" data-text-overflow="multiline" style="font-family: Montserrat; sans-serif; font-weight: 700; font-size: 24px;" fill="#000000" x="125" y="60" text-anchor="middle">{val}</text>';
OrgChart.templates.group.min.node = '<rect rx="20" ry="20" x="0" y="0" height="{h}" width="{w}" fill="#f2f2f2" stroke-width="0" anchor="middle"></rect>';

OrgChart.templates.group.nodeMenuButton = '';
OrgChart.templates.group.field_0 = "<text " + OrgChart.attr.width + '="700" style="font-family: Montserrat; sans-serif; font-weight: 700; font-size: 24px;" fill="#000000" x="{cw}" y="30" text-anchor="middle">{val}</text>'

//Alterar Tamanho da bolinha do assistencia
OrgChart.templates.split.node = '<circle cx="5" cy="5" r="5" fill="none" stroke-width="2" stroke="#000000"></circle>',

    //Alterar a largura e cor da linha
    OrgChart.templates.myTemplate.link = '<path stroke-linejoin="round" stroke="#000000" stroke-width="2px" fill="none" d="{rounded}" />';
OrgChart.templates.group.link = '<path stroke-linejoin="round" stroke="#000000" stroke-width="2px" fill="none" d="{rounded}"/>';

//Node preto 
OrgChart.templates.darkGrey = Object.assign({}, OrgChart.templates.ana);
OrgChart.templates.darkGrey.size = [250, 50];
OrgChart.templates.darkGrey.node = '<rect x="0" y="0" height="50" width="{w}" fill="#aeaeae"  rx="7" ry="7"></rect>';
OrgChart.templates.darkGrey.field_0 = "<text " + OrgChart.attr.width + '="145" style="font-family: Montserrat; sans-serif; font-weight: 700; font-size: 16px; text-anchor: middle;" fill="#ffffff" x="125" y="25">{val}</text>';

OrgChart.SEARCH_PLACEHOLDER = "Procurar Servidores/Secretarias";
OrgChart.templates.myTemplate.editFormHeaderColor = '#002580';

//Alterar Cantos redondos

var chart = new OrgChart(document.getElementById("tree"), {
    template: "myTemplate",
    enableSearch: true,
    assistantSeparation: 200,

    menu: {
        pdf: { text: "Export PDF" },
        png: { text: "Export PNG" },
        svg: { text: "Export SVG" },
        csv: { text: "Export CSV" },
        json: { text: "Export JSON" }
    },

    nodeMenu: {
        pdf: { text: "Export PDF" },
        png: { text: "Export PNG" },
        svg: { text: "Export SVG" },
        details: { text: "Details" },
        edit: { text: "Edit" },
        add: { text: "Add" },
        remove: { text: "Remove" }
    },

    nodeBinding: {
        field_0: "Nome",
        field_1: "Cargo",
        img_0: "Imagem",
        field_2: "Cargo 2",
        field_3: "Matricula",
    },

    tags: {
        "assistant": {
            template: "ula"
        },
        "g": {
            template: "group",
        },
        "sl0": { subLevels: 0, }, "sl1": { subLevels: 1 }, "sl2": { subLevels: 2 }, "sl3": {
            subLevels: 3
        },
        "darkGrey": {
            template: "darkGrey"
        },
    },
});

chart.load([
    { id: 0, tags: ["g"], Nome: "SECRETARIA GERAL", min: true },
    {
        "id": 0.1,
        "stpid": 0,
        "Nome": "Veridiano Ferreira Colares",
        "min": "true",



    },

    {
        "id": 0.2,
        "pid": 0.1,
        "Nome": "Francys da Silva Campos",
        "Matricula": "19.950",
        "min": ""
    },

    { id: 2, pid: 0, Nome: "GABINETE DA SECRETARIA GERAL", tags: ["g", 'assistant'] },

    {
        "id": 2.1,
        "stpid": 2,
        "Nome": "Telma do Socorro Goes Parente",
        "Matricula": "45.423",
        "min": ""
    },
    {
        "id": 2.11,
        "pid": 2.1,
        "Cargo 2": "",
        "Matricula": "981",
        "min": ""
    },
    {
        "id": 2.12,
        "pid": 2.1,
        "Nome": "Erika Costa Figueira Batista",
        "Matricula": "40.257",
        "min": ""
    },
    {
        "id": 2.13,
        "pid": 2.1,
        "Nome": "Claudia Cristina Serra dos Santos",
        "Matricula": "26.153",
        "min": ""
    },

    { id: 2.2, pid: 2, tags: ['g'], Nome: "2.2" },

    { id: 2.21, stpid: 2.2, tags: ["darkGrey"], Nome: "2.21", },
    { id: 2.211, pid: 2.21, Nome: "2.211", },
    { id: 2.22, stpid: 2.2, tags: ["darkGrey"], Nome: "2.22", },
    { id: 2.221, pid: 2.22, Nome: "2.221", },
    { id: 2.23, stpid: 2.2, tags: ["darkGrey"], Nome: "2.23", },
    { id: 2.231, pid: 2.23, Nome: "2.231", },

    { id: 3, pid: 0, tags: ["g"], Nome: "SGP" },
    { id: 3.1, stpid:3, Nome: "Eslayne"},
    { id: 3.2, stpid:3, Nome: "Glenda"},
    { id: 3.3, stpid:3, Nome: "Jorge Cardoso"},
    { id: 3.4, stpid:3, Nome: "Alessandro Domont"},
    { id: 3.5, stpid:3, Nome: "Diego Franca"},
    { id: 3.6, stpid:3, Nome: "Diana"},
    { id: 4, pid: 0, tags: ["g"], Nome: "SEFIN" },


    { id: 5, pid: 0, tags: ["g"], Nome: "STI" },


    { id: 6, pid: 0, tags: ["g"], Nome: "SEGES" },


    { id: 7, pid: 0, tags: ["g"], Nome: "SEPLAN" },


    { id: 8, pid: 0, tags: ["g"], Nome: "SEINF" },


    { id: 9, pid: 0, tags: ["g"], Nome: "SCC" },


    { id: 10, pid: 0, tags: ["g"], Nome: "SECOM" },


    { id: 11, pid: 0, tags: ["g"], Nome: "SGA" },


]);

chart.on('click', function (sender, args) {
    if (args.node.min) {
        sender.maximize(args.node.id);
    }
    else {
        sender.minimize(args.node.id);
    }
    return false;
});
```

_I appreciate any suggestions and corrections._

**Comment by ZornitsaPesheva** [comment]
1. What do you mean by "camera is free"? Here you can see if the layout doc page can help: https://balkan.app/OrgChartJS/Docs/Layout
2. You can have dynamic width, if this is what you mean: https://code.balkan.app/org-chart-js/dynamic-width#JS
3. Predefine the field and don't add the ellipsis
https://balkan.app/OrgChartJS/Docs/PredefinedTemplates - here are the filed definitions
https://balkan.app/OrgChartJS/Docs/TextOverflow - here is how the ellipsis are added
4. Not everything in the screenshot is possible, Again layout doc page is what you need: https://balkan.app/OrgChartJS/Docs/Layout
5. Read and try **min: true;**: https://balkan.app/OrgChartJS/Docs/MinMax
6. Need to predefine the links of the children template: https://balkan.app/OrgChartJS/Docs/Link#curve

Please read the doc pages. They are short and very useful.
Please also give us a link to a Code [example](https://code.balkan.app/org-chart-js/issue-822#JS) so the post can be easy readable.

**Comment by ZornitsaPesheva** [comment]
Created a code demo for you:
https://code.balkan.app/org-chart-js/issue-822#JS

**Comment by naveganth** [comment]
> Created a code demo for you: https://code.balkan.app/org-chart-js/issue-822#JS

A maximized node still doesn't have dynamic width, and how to only show the first two names of a person?
Please check the code demo i did [here.](https://code.balkan.app/court-organogram#JS)

![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/cf54ad49-6268-4052-8884-42445bbbe093) 
![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/88554f38-adf1-404c-9425-9ccdca15d07d)

**Comment by naveganth** [comment]
You are very helpful, thanks again, but will that solve the text going outside of the maximized node? and will the width in both lines be dynamically aligned (in the middle)  as: 

- ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/a2113e3a-4e81-435f-bc6c-77957ddaaa97)

**Comment by ZornitsaPesheva** [comment]
For the maximized node you should use the [text overflow](https://balkan.app/OrgChartJS/Docs/TextOverflow) functionality.

**Comment by naveganth** [comment]
So I've been trying to get the the text inside the maximized node to be the same size as the text but couldn't.
![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/fe0bdc34-7f18-456f-ba1a-441f36c59af3)

**- Expected Result (something like this):**
![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/1dda6a67-a45a-4d0a-93c3-8ac8c8510a2d)

I even tried changing the CSS with: 
```
[data-n-id='0'] rect {
width: 600px;
}
```

**For:**
![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/b7a886d8-71d4-42af-b148-0286715022a6)


But for some reason the position is fixed and I didn't manage to make the width centered. Can you help me out?
_[Code demo with example.](https://code.balkan.app/court-organogram#JS)_

**Comment by naveganth** [comment]
> For the maximized node you should use the [text overflow](https://balkan.app/OrgChartJS/Docs/TextOverflow) functionality.

I tried that too but the text would just be behind the node and not centered too.

Also for some reason when loading into the page some group nodes text overflows a little, until you click them 2 times then it gets right.

**- Text overflow:**
- ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/1e6df010-acbe-4f04-8580-a710e5094573)

**- How it's supposed to be:**
- ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/f247c178-cab2-485b-af93-065e40db72c1)

**Comment by ZornitsaPesheva** [comment]
Text-overflow:
`OrgChart.templates.group.field_0 = '<text data-width="230" data-text-overflow="ellipsis" style="font-size: 18px;font-weight:bold;" fill="black" x="10" y="90" text-anchor="start">{val}</text>';
`

**Comment by ZornitsaPesheva** [comment]
It is by default with ellipsis:
`
OrgChart.templates.group.field_0 = '<text data-width="230" style="font-size: 18px;" fill="#aeaeae" x="{cw}" y="30" text-anchor="middle">'
    + '{val}</text>';
`

**Comment by naveganth** [comment]
Thanks for the help @ZornitsaPesheva I will be coming with new questions, again. 😁😁😁
