### ISSUE TITLE
Edit details on form

### ISSUE THREAD

**Issue by naveganth** [BALKANGraph/OrgChartJS#826]
Code demo/example for testing and checking: [here!](https://code.balkan.app/court-organogram#JS)

**First, I'd rather have a 300x400 square for the images inside the details menu.**
- ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/1d0c51bc-9f5d-445c-83d2-93e9a041e653)

**Second, is it possible to check if there's any information on top? and if not send the bellow text info to the position of the top**
- ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/1bbbc3ac-d93b-4a4d-842f-91c6ddafaf4e)
(44.706 should move upwards since there's no "cargo 2")

**Third, can I change the background color? if so, is it possible to by clicking and inserting a color? or even a image that each person can choose and insert the link for.**
- ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/803d242d-9126-4413-850c-87fd05e8fe22)

**Forth, I wanna change the font and of all those fields below.**
- ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/80c351b9-2bab-4b58-9640-874c1d1ec200)
- ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/1ae5697f-1542-4ca8-8cfa-6800024d7aee)

**And the menu button color too**
- ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/2decc2ec-aab1-469f-8da0-5a5406be1dd9)
- ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/9dbad561-342e-4cf2-8496-606b9e780d4b)

**The font in search too**
- ![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/f7233833-3881-4f61-a5d6-0e634f6d14d2)

**Comment by ZornitsaPesheva** [comment]
1. I don't understand, because 300x400 is a rectangle.
2. https://balkan.app/OrgChartJS/Docs/Fields#link
3. https://code.balkan.app/org-chart-js/edit-form-css#CSS
4. Try with CSS. You can see the selectors in the dev console.

**Comment by naveganth** [comment]
> 1. I don't understand, because 300x400 is a rectangle.

Got it

> 2. https://balkan.app/OrgChartJS/Docs/Fields#link

I couldn't find anything talking about fields changing places when there's a blank space.
> 3. https://code.balkan.app/org-chart-js/edit-form-css#CSS

Got it
> 4. Try with CSS. You can see the selectors in the dev console.

Thanks

**Comment by naveganth** [comment]
How do i change the text inside edit form buttons?
![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/258eb57d-a9b5-4b19-b433-f857b22eb95d)

**Comment by ZornitsaPesheva** [comment]
About the blank space, you can check in the data if there is such value and add some before loading the chart.

Buttons localization:
https://code.balkan.app/org-chart-js/edit-form-buttons-localization#JS

**Comment by naveganth** [comment]
> About the blank space, you can check in the data if there is such value and add some before loading the chart.

I want a function to check if there anyhting on field_2 and if not substitute with field_1 values.

> Buttons localization: https://code.balkan.app/org-chart-js/edit-form-buttons-localization#JS

Exactly @ZornitsaPesheva thanks

**Comment by ZornitsaPesheva** [comment]
> > About the blank space, you can check in the data if there is such value and add some before loading the chart.
> 
> I want a function to check if there's anything on field_2 and if not substitute with field_3 values.
It would be much easier to do it with JS before loading the chart. Why not? 
If data_2 is empty or missing, data_2 = data_3

**Comment by naveganth** [comment]
Thanks, how do I make them all the same size when all minimized and be next to the main link in the tree, instead of all separated.

**Result**
![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/bba5dcef-5c51-4165-86bf-f51427f4472e)

**Expected Result:**
![Captura de tela 2024-03-11 093534](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/9a734bfd-6b53-49ca-9547-f2ebe3cc19dc)

Also, Is it possible to create a tag to make specific nodes be collapsed.

**Result;**
![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/312f1534-a9df-42d6-a65c-cfae80f052bc)

**Expected:**
![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/5103f407-34f2-4347-8e82-2c26c07011ce)

Hover brightness CSS, isn't working together in some parts 
![Captura de tela 2024-03-11 095250](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/5dccd8d9-92d2-462e-b53c-b196a2110d71)
(The hover brightness should be in the active state inside the nodes and be deactivated outside of it, not activating and deactivating when moving trough field and image.)

**Comment by naveganth** [comment]
How to remove a field from **editform**? I don't want the image link to appear when editing or details mode inside the form.
![Captura de tela 2024-03-11 110654](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/d4d33b27-5074-4163-896f-c6d5221aa3e4)

**Comment by naveganth** [comment]
> By default the nodes are all the same size. You have made them with dynamic width. You can have small separation: 

Went with regular nodes, too much trouble with dynamic width.

> https://balkan.app/OrgChartJS/Docs/ScaleAndPadding#separation 

That's for all nodes, I wanna separate only grouped nodes when minimized.

>Expand/collapse:  https://balkan.app/OrgChartJS/Docs/ExpandCollapse 

I mean't using like specific links between nodes not everyone as children nodes, also for some reason nodes on level 2 doesn't work in grouped nodes.

> Hover brightness is made by you. Just try to change the colors opposite. to 

Put the image selector in the brightness CSS thanks.

> remove image link: https://code.balkan.app/org-chart-js/hide-image-hyperlink#JS

Got it, removed the image link.

**Comment by ZornitsaPesheva** [comment]
>  That's for all nodes, I wanna separate only grouped nodes when minimized.

You can set different separation for the subtrees: https://code.balkan.app/org-chart-js/minimize-maximize-groups#JS

> I mean't using like specific links between nodes not everyone as children nodes, also for some reason nodes on level 2 doesn't work in grouped nodes.

I don't understand what is the common between expand/collapse and links in this case

**Comment by ZornitsaPesheva** [comment]
> That's is for the children inside the subtree, but not for the subtree itself
You can set a separation in the main config for the whole chart and then set different separation in the subtrees config for the nodes.

> I just think it would be easier to collapse specific children and nodes to their "father" than to use collapse all children on all the chart

I am not telling you to collapse all nodes. Read the whole page, You can also use the expandCollapse on init event to say exactly which nodes you'd like to collapse.

**Comment by naveganth** [comment]
What do you think about my [organogram](https://code.balkan.app/court-organogram#JS) so far, do you have any suggestions?

**Comment by ZornitsaPesheva** [comment]
Looks pretty nice. Good job! I don't have any suggestions.

**Comment by naveganth** [comment]
> Looks pretty nice. Good job! I don't have any suggestions.

**Thanks for everything @ZornitsaPesheva.**
