### ISSUE TITLE
Import Error when using the pro license with React Vite and Typescript

### ISSUE THREAD

**Issue by christoph-weissteiner-imprivata** [BALKANGraph/OrgChartJS#828]
I followed the instructions on how to install OrgChartJS in my React TypeScript app. And I receive the following runtime error when using the OrgChart class in my Component. 

SyntaxError: The requested module '/src/util/orgchart.js' does not provide an export named 'default'

I use the downloaded package installation and have orgchart.js and orgchart.d.ts inside src/util folder and then added
` export default OrgChart` to the end of orgchart.d.ts.

The component where I use it looks like this:
`import { Component, RefObject, createRef } from "react";
// import OrgChart from "@balkangraph/orgchart.js";
import OrgChart from "../../../util/orgchart.js";

type BalkanChartProps = {
  nodes: {
    id: number;
    pid?: number;
    name: string;
    title: string;
    img: string;
  }[];
};

export default class BalkanChart extends Component<BalkanChartProps> {
  private chart?: OrgChart;
  private divRef: RefObject<HTMLDivElement>;

  constructor(props: BalkanChartProps) {
    super(props);
    this.divRef = createRef<HTMLDivElement>();
  }

  shouldComponentUpdate() {
    return false;
  }

  componentDidMount() {
    if (this.divRef.current) {
      this.chart = new OrgChart(this.divRef.current, {
        nodes: this.props.nodes,

        nodeBinding: {
          field_0: "name",
          img_0: "img",
        },
      });
    }
  }

  render() {
    return <div id="tree" ref={this.divRef}></div>;
  }
}`

Then I want to test it with storybook. My .stories.tsx file looks like this:
`import { Meta, StoryObj } from "@storybook/react";
import BalkanChart from ".";

const meta = {
  title: "Unimate/Charts/BalkanChart",
  component: BalkanChart,
  args: {
    nodes: [
      {
        id: 1,
        name: "Denny Curtis",
        title: "CEO",
        img: "https://cdn.balkan.app/shared/2.jpg",
      },
      {
        id: 2,
        pid: 1,
        name: "Ashley Barnett",
        title: "Sales Manager",
        img: "https://cdn.balkan.app/shared/3.jpg",
      },
      {
        id: 3,
        pid: 1,
        name: "Caden Ellison",
        title: "Dev Manager",
        img: "https://cdn.balkan.app/shared/4.jpg",
      },
      {
        id: 4,
        pid: 2,
        name: "Elliot Patel",
        title: "Sales",
        img: "https://cdn.balkan.app/shared/5.jpg",
      },
      {
        id: 5,
        pid: 2,
        name: "Lynn Hussain",
        title: "Sales",
        img: "https://cdn.balkan.app/shared/6.jpg",
      },
      {
        id: 6,
        pid: 3,
        name: "Tanner May",
        title: "Developer",
        img: "https://cdn.balkan.app/shared/7.jpg",
      },
      {
        id: 7,
        pid: 3,
        name: "Fran Parsons",
        title: "Developer",
        img: "https://cdn.balkan.app/shared/8.jpg",
      },
    ],
  },
  render: (args) => {
    return <BalkanChart {...args} />;
  },
} satisfies Meta<typeof BalkanChart>;
export default meta;
type Story = StoryObj<typeof meta>;
export const Default: Story = {};
`

I then tried to use the installation via npm and it works. It also works if I replace the files of my pro license inside of node_modules.

Any help is greatly appreciated.

**Comment by ZornitsaPesheva** [comment]
Please try to create simple example following the exact instructions here:
https://balkan.app/OrgChartJS/Docs/React
then add the licensed file, following the exact instructions here:
https://balkan.app/OrgChartJS/Docs/InstallLicensedVersion#react

**Comment by christoph-weissteiner-imprivata** [comment]
I created a basic example here: https://github.com/christoph-weissteiner-imprivata/balkan-chart-vite-react-ts-storybook.

I didn't install storybook for now, because the error is also there without it. Just install all the dependencies and then run the dev script.

**Comment by ZornitsaPesheva** [comment]
Please add at the end of both files: orgchart.js and orgchart.d.ts this:
export default OrgChart
then add bot files in src folder:
![image](https://github.com/BALKANGraph/OrgChartJS/assets/19305472/acc6f096-c27e-4c77-8d4a-45198de5f1d3)
Import this way:
import OrgChart from "./orgchart.js";
and 
npm run dev

![image](https://github.com/BALKANGraph/OrgChartJS/assets/19305472/199fec0a-8ef8-47c7-9cf7-1e19fb2604d2)

**Comment by christoph-weissteiner-imprivata** [comment]
Thank you this fixed it.
