### ISSUE TITLE
Perfomance

### ISSUE THREAD

**Issue by naveganth** [BALKANGraph/OrgChartJS#829]
Let's talk about performance, is there any way to improve the pan and zooming feature in the organogram? It's very slow with a lot of nodes open and that's not ideal.

![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/21be2508-910d-45d8-8c18-524c761b6037)

**Comment by ZornitsaPesheva** [comment]
I notice that your photos are loading very slow. Please check with ours. You can compare in a simple example.

**Comment by naveganth** [comment]
I tried changing the images extension from PNG to JPG and decreased the resolution and size of each one from 400kB to 10kB each, but there's still a lot of lag. I have no clue how to fix that.

**Comment by ZornitsaPesheva** [comment]
I just checked...
this is not loading any image for example: 
https://old.tjap.jus.br/portal/images/OG0.2.nonsense

**Comment by naveganth** [comment]
Tried removing all images, but the lag still continues so it probably doesn't have to do with the photos

**Comment by ZornitsaPesheva** [comment]
Oh, this is something else, okay...

**Comment by naveganth** [comment]
> I just checked... this is not loading any image for example: https://old.tjap.jus.br/portal/images/OG0.2.nonsense

I didn't expect you to reply so soon, I was messing with the links and removing them

**Comment by naveganth** [comment]
Maybe it has to do with nodes inside groups?

When you use the toolbar buttons to zoom: ` toolbar: {zoom: true,}` , it doesn't produce any lag.

**Comment by ZornitsaPesheva** [comment]
You don't need this link to use the same templates as up to now. I don't even know what you are using if for.

**Comment by ZornitsaPesheva** [comment]
You should be able to remove it . I don't know what is this and why it is needed to render a font and why do you need this font.

**Comment by naveganth** [comment]
> You should be able to remove it . I don't know what is this and why it is needed to render a font and why do you need this font.

**I removed it from HTML but the lag continued**

> Them i tried removing all the instances of Montserrat, and it made the perfomance better but i ended with my organogram like this:

I guess it has to be with placing the font style in the `OrgChart.templates` i'll try overriding the style with montserrat in CSS, maybe that will fix the lag

**Comment by ZornitsaPesheva** [comment]
need to add it
https://balkan.app/OrgChartJS/Docs/CSSCustomization#fieldClass

**Comment by naveganth** [comment]
> need to add it https://balkan.app/OrgChartJS/Docs/CSSCustomization#fieldClass

How about for the field_0 but for other templates?

**Comment by naveganth** [comment]
> need to add it https://balkan.app/OrgChartJS/Docs/CSSCustomization#fieldClass

It didn't work
![image](https://github.com/BALKANGraph/OrgChartJS/assets/159157666/558861b3-e107-4988-9ea8-f09e546b0036)

**Comment by naveganth** [comment]
> You can use different class names for the different templates

Found out how to do that, 
question: Can i use . in the class? Tried to use the name of the template for the class which is myTemplate.field_0 but i guess i can't use dots when naming the class right?

**Comment by naveganth** [comment]
So I realized yesterday and now but there's this weird little glitch where when hovering changes the font size and position, and sometimes even blurs the phrase itself, especially when using the selector for group.

https://github.com/BALKANGraph/OrgChartJS/assets/159157666/3971be6b-db63-43fc-a9e7-3ea8522041ef

**Comment by ZornitsaPesheva** [comment]
It is coming from this transition
transition: filter 0.5s .03s ease-in-out;

**Comment by ZornitsaPesheva** [comment]
I am not sure it this is what you need to achieve, but you may need to change a style of one element when hovering on another.
[data-n-id] rect:hover ~ .banana{ fill: yellow !important; }

**Comment by naveganth** [comment]
> need to add it https://balkan.app/OrgChartJS/Docs/CSSCustomization#fieldClass

So i did add the font CSS, but the lags still exists

**Comment by ZornitsaPesheva** [comment]
You can try to add it locally on your webserver.

**Comment by naveganth** [comment]
> You can try to add it locally on your webserver when creating the local app.

I have no clue how to even start with that, but thanks for the help.

**Comment by ZornitsaPesheva** [comment]
I guess the issue is in your images. They are not public, they are loading slow or both.
Please test with one of our images. If the issue still exist, please create a simple example to isolate the issue.

**Comment by naveganth** [comment]
> I guess the issue is in your images. They are not public, they are loading slow or both. Please test with one of our images. If the issue still exist, please create a simple example to isolate the issue.

Just tested, it has to do with where my images are hosted. You are like an angel 😄
