### ISSUE TITLE
Using OrgChart JS in an Environment with Blocked External Internet Access

### ISSUE THREAD

**Issue by kowooho** [BALKANGraph/OrgChartJS#830]
Hello,

I am currently trying to use OrgChart JS in an environment where external internet access is blocked. I am aware that simply downloading the library will not be enough, and I have a few questions about this.

What do I need to use OrgChart JS without an external internet connection?
Are there any additional files or settings that I need to install besides the library?
What are the potential problems that can occur when using OrgChart JS without an external internet connection, and how can I solve them?
Is there any official documentation or guide for offline use of the OrgChart JS library?
I would appreciate it if you could answer my questions.

**Comment by ZornitsaPesheva** [comment]
Hi 

The licensed version can works without an external internet connection.
You may need to install your own [export service](https://balkan.app/OrgChartJS/Docs/Exporting#server), if you are doing PDF or PNG exports of the chart.
After purchasing a [license](https://balkan.app/OrgChartJS/Pricing), you will be able to use it offline.

**Comment by kowooho** [comment]
Thank you for your response!

I have an additional question. Would there be any issues using Gemini in a Java/JSP environment based on Spring 4.x?

**Comment by ZornitsaPesheva** [comment]
What is this Gemini that you are asking for?

**Comment by kowooho** [comment]
> What is this Gemini that you are asking for?

Ah, my bad! I didn't catch that my questions were weird because I was switching back and forth between Google Gemini and you...

**Comment by kowooho** [comment]
> What is this Gemini that you are asking for?

My questions were not about Gemini, but about ChartOrgJS. :)

**Comment by ZornitsaPesheva** [comment]
Org Chart JS is just the front-end library. To use it, you just need to get the data in JSON and load it in the chart. Then we have events that are used to send back the changed data as JSON. So It is up to you what you will use as a backend. Everything should work. 
Here we have some server side examples: https://balkan.app/OrgChartJS/Docs/GitHub
