### ISSUE TITLE
location of the node randomly changes after reload

### ISSUE THREAD

**Issue by ryanlaw** [BALKANGraph/OrgChartJS#831]
Hi team,

I have noticed the node's location when being created may be different if reload the chart after saving.

Is that normal behaviour? normally the graph would be expected to stay the way it was created.

Regards

**Comment by ZornitsaPesheva** [comment]
Could you please show us in an [example ](https://code.balkan.app/org-chart-js/simple-example#JS)what exactly you mean?

**Comment by ryanlaw** [comment]
Thanks for your reply @ZornitsaPesheva ,

Initially, the chart is as below:
![image](https://github.com/BALKANGraph/OrgChartJS/assets/563875/e5e387d5-19b9-4313-8a11-bc2ee6f8250c)
After adding a node (red circle):
![image](https://github.com/BALKANGraph/OrgChartJS/assets/563875/776808fa-2ecd-4612-946e-f4a629d34fbd)
this node will be saved to DB. and after reload:
![image](https://github.com/BALKANGraph/OrgChartJS/assets/563875/a09bd7ac-9687-4947-9de4-318bbbe5d008)
The location of the node changes compared to when it was created.

Hoping this explains my issue clearly.

Regards

**Comment by ZornitsaPesheva** [comment]
I understand the issue.
You can use the [orderBy ](https://balkan.app/OrgChartJS/API/interfaces/OrgChart.options#orderBy)property to change the order of the nodes.

**Comment by ryanlaw** [comment]
Thanks, that solved my issue.
