### ISSUE TITLE
change node circle menu button icon

### ISSUE THREAD

**Issue by andreatricoli** [BALKANGraph/OrgChartJS#832]
Hi everyone!

How can I customize the circular node menu icon? I want to change the default one with the three lines with another

![image](https://github.com/BALKANGraph/OrgChartJS/assets/53294658/0db11eb7-eb4f-4a04-a6e5-29d9ce3ce8f3)

thank you very much

**Comment by ZornitsaPesheva** [comment]
Hi Andrea
Here is a code demo: https://code.balkan.app/family-tree-js/change-the-nodecirclemenubutton-icon#JS
