### ISSUE TITLE
A lot of network call and data stored in localStorage

### ISSUE THREAD

**Issue by andreatricoli** [BALKANGraph/OrgChartJS#834]
Hi everyone,

1) I noticed that the first time the orgchart is loaded it call a lot of time the api OrgChartJS in GET and in POST. Why? How can i solve it?
 
![network](https://github.com/BALKANGraph/OrgChartJS/assets/53294658/d5e76d75-027c-4ecd-bfbc-1481a56a4f4d)

2) I noticed that every time the server send me a new nodes list, org chart create a new entry in localStorage? why? can i disable this behaviour?

![localStorage](https://github.com/BALKANGraph/OrgChartJS/assets/53294658/1ca1adbc-6eee-423b-a341-6041c2bfc859)

thank you very much

**Comment by ZornitsaPesheva** [comment]
This is the way the trial version works.
In the licensed version you will not have these calls and by default it will not write anything in the localStorage.
