### ISSUE TITLE
Auto width node

### ISSUE THREAD

**Issue by DepreesterEwoud** [BALKANGraph/OrgChartJS#837]
Hi!

I have another question. I am trying to make an auto width for each node according to the text inside the node.
Now, i encounter following issue.

I am using blazor. So when i pass my data for loading the chart like this from blazor to the js file
![image](https://github.com/BALKANGraph/OrgChartJS/assets/55786841/05d44016-197f-4bc5-a9c8-fd987c6f25d0)
And request the data in my js file like this
![image](https://github.com/BALKANGraph/OrgChartJS/assets/55786841/13124891-b930-42ab-8de2-414f5cb4f0da)
And print all the nodes (var allNodesRect = document.querySelectorAll('[data-n-id] rect');) it is all null
![image](https://github.com/BALKANGraph/OrgChartJS/assets/55786841/eaf9c391-fb63-4fef-acf1-52ed615ea877)

Now when i hardcode the data in my chart like this, it works. So i don't really know what i am doing wrong here.
![image](https://github.com/BALKANGraph/OrgChartJS/assets/55786841/d30cd372-4318-4aba-94fa-a9299716ea95)

This is my code block for the auto width of the node
![image](https://github.com/BALKANGraph/OrgChartJS/assets/55786841/8e620ec5-e13a-4757-9dd2-f8151d767c90)

Thanks in advance!

**Comment by ZornitsaPesheva** [comment]
Here is a code demo for auto width:
https://code.balkan.app/org-chart-js/dynamic-width#JS
