### ISSUE TITLE
Unable to Edit node

### ISSUE THREAD

**Issue by callmejamie** [BALKANGraph/OrgChartJS#84]
Hi,

I'm evaluating OrgChart.js for my company and I need some help.

I downloaded the OrgChart.js library via npm and I had set it up as per instructions in the "Getting Started" section https://balkangraph.com/OrgChartJS/Docs/GettingStarted. I had also enabled the `nodeMenu` option to switch on the ability to edit the node.

Here's what my script looks like:
```
var chart = new OrgChart(document.getElementById("tree"), {
        nodeBinding: {
            field_0: "name"
        },
        nodes: [
            { id: 1, name: "Amber McKenzie" },
            { id: 2, pid: 1, name: "Ava Field" },
            { id: 3, pid: 1, name: "Peter Stevens" }
        ],
        nodeMenu: {
            details: {text:"Details"},
            edit: {text: "Edit"},
            add: {text: "Add"},
            remove: {text: "Remove"}
        }
    });
```
But when I tried to edit the node in my browser, I was not able to see the changes I made get updated in the chart. I wasn't able to replicate the same behavior as the shown on the demo page (https://balkangraph.com/OrgChartJS/Docs/Edit)

In fact, the arrow on the top right hand corner of the edit form wasn't clickable for me. 

Is there something I'm missing here?

**Comment by plamen-peshev** [comment]
[test.1.html.zip](https://github.com/BALKANGraph/OrgChartJS/files/3132637/test.1.html.zip)

Created a demo with the code you posted, see attached, can you test it and tell us if it works or not for you

**Comment by callmejamie** [comment]
Hi @plamen-peshev .. I downloaded the zip file you attached but there was only 1 html file in there and no `src` folder. Was that intended?

Anyway, I updated the link to the orgchart.js script in the html file to point to the one in my local. Then I opened your html file in Chrome and was able to edit the node.. but when I opened it in firefox it didn't work.  

Seems like there's a problem on firefox side

**Comment by plamen-peshev** [comment]
It works well for me on Firefox version  66.0.3

Can you check if you have any errors in the console

**Comment by callmejamie** [comment]
![Testing Edit](https://user-images.githubusercontent.com/13810940/57082062-935d5e80-6d28-11e9-8fd3-b653d664cf95.gif)


Attaching a screengrab of me testing the javascript in both Chrome and Firefox. My Firefox version is 60.6.1.. I just can't get the edit to work properly in Firefox

**Comment by plamen-peshev** [comment]
Thanks for the screen-grab

Is it Firefox ESR edition?

What is your operating system?

**Comment by callmejamie** [comment]
I'm using Windows 10 Enterprise. And yes, my firefox version is 60.6.1esr (64-bit)
Does that make a difference?

This could be an issue since a lot of my company's users are using the same setup as me.

**Comment by plamen-peshev** [comment]
Was able to replicate the issue

Will fix it in the next version

**Comment by callmejamie** [comment]
Okok.. thank you! Btw.. is there any reason why the demo version was working ok for my firefox?
