### ISSUE TITLE
Error when highlighting results with <mark> tag

### ISSUE THREAD

**Issue by Sergi17138** [BALKANGraph/OrgChartJS#840]
How to reproduce the bug that I have detected:
If we have a node with the name: 
United Kindom

If in the search field you write
Unit Ted

The <mark> tag to highlight the result appears written on the search result.
The error with the searchUI is in the way you insert the mark tag in the args.first:

console.log (args.first);
`<mark>Uni<</mark>mark>ted</mark> Kindom`

![Captura](https://github.com/BALKANGraph/OrgChartJS/assets/66567076/9111ba5a-b4e5-4789-9b70-6f63bef5a71b)

**Comment by Sergi17138** [comment]
`OrgChart._search.searchAndComputeScore = function (t, e, r, i) {
        if (OrgChart.isNEU(e))
            return null;
        if (OrgChart.isNEU(t))
            return null;
        if (!t.length)
            return null;
        "string" != typeof e && (e = e.toString());
        var a = e.toLowerCase()
            , n = OrgChart._search.searchIndexesOf(a, t);
        if (!n.length)
            return null;
        for (var o = a.length / 100, l = 0, s = 0, h = l > 0 ? 100 : 0, d = 0, c = 0; c < t.length; c++)
            for (var g = t[c], p = 0; p < n.length; p++)
                if (-1 != g.indexOf(n[p].searchPhrase)) {
                    d++;
                    break
                }
        var u = 100 / (t.length / d);
        if (n.length) {
            s = n[0].start;
            for (p = 0; p < n.length; p++)
                if (l += n[p].length,
                    n[p].start < s && (s = n[p].start),
                    p >= 1 && n[p - 1].start > n[p].start) {
                    h = 0;
                    break
                }
        }
        var f = 0;
        0 != l && (f = l / o);
        var m = l > 0 ? 100 : 0;
        0 != s && (m = 100 - s / o);
        var C = 0;
        i && i[r] && (C = i[r]),
            u && (u = u / 100 * 50),
            f > 0 && (f = f / 100 * 10),
            m > 0 && (m = m / 100 * 10),
            h > 0 && (h = h / 100 * 10),
            C > 0 && (C = C / 100 * 20);
        var O = Math.round(1e4 * (u + f + m + h + C));
        n.sort((function (t, e) {
            return t.start < e.start ? -1 : t.start > e.start ? 1 : 0
        }
        ));
        var b = e;
        for (p = n.length - 1; p >= 0; p--)
            b = (b = b.insert(n[p].start + n[p].length, "</mark>")).insert(n[p].start, "<mark>");
        return {
            __searchMarks: b,
            __score: O
        }
    }`

**Comment by plamen-peshev** [comment]
We have fixed the issue in the latest version 8.14.41
Clear your browser cache and test [this Code demo ](https://code.balkan.app/result/840)
You can get the latest version from[ here](orgchartjs.balkan.app)

**Comment by Sergi17138** [comment]
THANK YOU SO MUCH! @plamen-peshev
