### ISSUE TITLE
Free version don't work anymore

### ISSUE THREAD

**Issue by benoit2600** [BALKANGraph/OrgChartJS#844]
Hi, 

The free trial version of OrgChartJS doens't work anymore for us.
Everything was working great until the 6 june. 
And now the call to the online API stay in pending (see attached picture) for maybe 2 minutes, and then go to a 500 internal server error. 
It seems to happen with the uk-s server, the fr server and the japan server (I've not tried the other)
Any idea why ?

![2024-06-10 10_07_52-DevTools - file____C__Users_benoit fauque_Documents_Dev_test%20orgchartjs_test h](https://github.com/BALKANGraph/OrgChartJS/assets/2320978/56c81e66-a108-4aa1-b0d6-4c275b1059d4)
![2024-06-10 10_10_50-Window](https://github.com/BALKANGraph/OrgChartJS/assets/2320978/df0a1d28-1fbe-4983-9899-f190fd75882e)

**Comment by ZornitsaPesheva** [comment]
Your trial may have expired and you need to purchase a license.

**Comment by benoit2600** [comment]
Hi, 
Thank you for your answer. 

It might be it, we planned to buy the paid professionnal version at the beginning of July.

But You may also have a bug. I tried to create a new chart with your getting started guide on a new server, new IP, new domain, fresh start, and I have the same error (you can see it here : https://bendrop.fr/test2.html).

Regards, 
Benoit

**Comment by ZornitsaPesheva** [comment]
I see this:
![image](https://github.com/BALKANGraph/OrgChartJS/assets/19305472/faa9c3a0-4edf-4fcf-9271-e51fd64db3e3)

Please get the latest version from [here ](https://balkan.app/FamilyTreeJS/Download)and clear the browser cache.
Please also test locally with this simple html example locally: https://github.com/ZornitsaPesheva/public/blob/master/base.html
Please check if the IP is really [new](https://whatismyipaddress.com/).

**Comment by ZornitsaPesheva** [comment]
Will check and let you know.

**Comment by ZornitsaPesheva** [comment]
There was an issue with the trial version. Now it is fixed. Please clear the browser cache (Ctrl+F5) and check again.

**Comment by benoit2600** [comment]
Thank you, it works again.
