### ISSUE TITLE
Disable redraw on zoom/move?

### ISSUE THREAD

**Issue by mitkosoft** [BALKANGraph/OrgChartJS#85]
Hi,

Up to version 4.1.2, when the user moves or zooms the chart, the data inside the nodes remain visible. Now, within later releases, when the user performs either zoom, mouse click or move (drag), all the nodes become blank (i.e. it looks like the chart performs a redraw). Is there an option to avoid this effect? I tried with lazyLoading: false, but this doesn't help.

Thank you!

**Comment by plamen-peshev** [comment]
It is planed behavior for performance optimization

Browsers cannot handle tons of html dom element, for that reason before the animation OrgChart JS hides some of the elements

You can tune that by changing the following constants:
- BALKANGraph.TEXT_THRESHOLD = 150;
- BALKANGraph.IMAGES_THRESHOLD = 70;
- BALKANGraph.LINKS_THRESHOLD = 150;
- BALKANGraph.EXPCOLL_THRESHOLD = 40;
- BALKANGraph.ANIM_THRESHOLD = 50;


With the default consts OrgChart JS works well on computer with 2GB RAM

**Comment by mitkosoft** [comment]
Thanks, Plamen! 
Just a question - what these numbers mean, i.e. what is the difference between:
BALKANGraph.TEXT_THRESHOLD = 150; and BALKANGraph.TEXT_THRESHOLD = 1500; for example?

**Comment by plamen-peshev** [comment]
OrgChart.TEXT_THRESHOLD = 150 - if you have more then **150** text dom elements visible on the page they will become invisible on animation start

OrgChart.TEXT_THRESHOLD = 1500 - if you have more then **1500** text dom elements visible on the page they will become invisible on animation start

**Comment by mitkosoft** [comment]
Got it, thank you!
