### ISSUE TITLE
How chang default filter " all " 

### ISSUE THREAD

**Issue by NivekStarks** [BALKANGraph/OrgChartJS#853]
I would like to replace 'all' with 'tout' to write in French

Here is the screenshot

![Capture](https://github.com/user-attachments/assets/64ddc2c2-5ba7-4612-8a98-6fc9f34406f0)

**Comment by NivekStarks** [comment]
And I would like to replace 'Filter by service' with 'Filtre par service'

**Comment by ZornitsaPesheva** [comment]
Here is a code example:
https://code.balkan.app/orgchart-js/filterui-localization#JS

**Comment by NivekStarks** [comment]
Thanks you !

**Comment by NivekStarks** [comment]
OrgChart.filterUI.all = '[Toute]' 

no it doesn't work

**Comment by NivekStarks** [comment]
OrgChart.filterUI.textFilterBy = 'Filtre par';

it work OK

**Comment by ZornitsaPesheva** [comment]
Sorry, I forgot to tell you that you need to get the latest version.

**Comment by NivekStarks** [comment]
Thanks u !
