### ISSUE TITLE
`layout` attribute ignored for large lists

### ISSUE THREAD

**Issue by wcarson** [BALKANGraph/OrgChartJS#855]
I have a configuration based on the [15K records demo](https://code.balkan.app/org-chart-js/15k-nodes-with-custom-expand,-collapse#JS). It doesn't seem to matter what value is put in for the `layout` parameter, the layout doesn't change. Additionally, selecting any layout via the layout toolbar also has no effect.

```js
let chart = new OrgChart(document.getElementById("tree"), {
    enableSearch: false,
    template: "isla",
    collapse: {
        level: 2,
        allChildren: true,
    },
    nodeMouseClick: OrgChart.action.none,
    layout: OrgChart.layout.grid, // <- has no effect
    align: OrgChart.ORIENTATION,
    mouseScrool: OrgChart.action.none,
    showXScroll: OrgChart.scroll.visible,
    nodeBinding: {
        field_0: "id",
        field_1: "pid"
    },
});
```

In the image below, the chart has been set to `mixed` or `grid` (same result) but is still in the default layout. This results in a lot of unused vertical space.
![CleanShot 2024-08-27 at 17 21 41](https://github.com/user-attachments/assets/655c3424-8ef0-41d0-abbd-da1414040570)

**Comment by ZornitsaPesheva** [comment]
Here is how to use the layouts in your case:
https://balkan.app/OrgChartJS/Docs/Layout#mixedWithCollapsedNodes
You need to set this:
```
OrgChart.MIXED_LAYOUT_FOR_NODES_WITH_COLLAPSED_CHILDREN = true;
```

**Comment by wcarson** [comment]
That's what I was missing. Thanks and sorry for the false report :)
