### ISSUE TITLE
Problem with OrgChart Images Display on the site

### ISSUE THREAD

**Issue by NivekStarks** [BALKANGraph/OrgChartJS#856]
Problem on the OrgChart site: all the images (results) only show the branches; I don't see any complete image to visualize the result. Am I the only one facing this issue?

Here are some pictures to better explain. 

![Capture](https://github.com/user-attachments/assets/9d09d1aa-a6d6-4f10-a477-e569bda58006)
![Capture1](https://github.com/user-attachments/assets/22386967-8fc6-4457-a433-1a73839309ef)
![Capture3](https://github.com/user-attachments/assets/ef961e42-d7be-40c9-8b04-309953f98c3c)

**Comment by ZornitsaPesheva** [comment]
Do you still have that issue? Did you try Ctrl+F5?

**Comment by NivekStarks** [comment]
yes and ctrl + F5 I already tried but it doesn't work

**Comment by ZornitsaPesheva** [comment]
Hi Hevin
Could you please write us on support@balkan.app what time is convenient for you to have a meeting, so we can find the reason for that issue?
