### ISSUE TITLE
Uncaught ReferenceError: that is not defined  at OrgChart.update

### ISSUE THREAD

**Issue by cha5536** [BALKANGraph/OrgChartJS#86]
![image](https://user-images.githubusercontent.com/35095565/57144607-fc5dd880-6df3-11e9-9ced-a6b49c8a8d7a.png)

![image](https://user-images.githubusercontent.com/35095565/57144782-670f1400-6df4-11e9-9f86-8ee81cb95d89.png)

**Comment by plamen-peshev** [comment]
Thanks for reporting this issue

It has been addressed in version 4.6.7

**Comment by cha5536** [comment]
Thanks for your help. 
But I found another problem with OnUpdate Event.

Using this edit form demo:
https://jsfiddle.net/BALKANGraph/vpz1rfmt/?utm_source=website&utm_medium=embed&utm_campaign=vpz1rfmt

![image](https://user-images.githubusercontent.com/35095565/57196756-690ed980-6f92-11e9-9b56-66806ab81f34.png)

Add Event is fine. (Show alert)
![image](https://user-images.githubusercontent.com/35095565/57196758-7035e780-6f92-11e9-9bf7-51da1f7bd6a7.png)

Update Event is not show alert, but Name is updated.
![image](https://user-images.githubusercontent.com/35095565/57196759-76c45f00-6f92-11e9-92c7-0369bb18029e.png) 
![image](https://user-images.githubusercontent.com/35095565/57196761-79bf4f80-6f92-11e9-84f6-e20cbf684b42.png)

**Comment by ZornitsaSerbezova** [comment]
It doesn't work, because in this case Edit form uses another function, not "Update".
