### ISSUE TITLE
Local Storage are cleared

### ISSUE THREAD

**Issue by orgaard** [BALKANGraph/OrgChartJS#861]
I have a system that stores some information in the browsers local storage. However when I create an org chart, the local storage i cleared. 

![image](https://github.com/user-attachments/assets/0edcd460-b67a-4acc-b183-de5d51726133)

When I load the org chart two new entries a made, and then all are cleared

![image](https://github.com/user-attachments/assets/fefe9616-9dd4-4685-82bc-80d5316076a7)

How can I ensure my own entries to the local storage are not being deleted by your script?

//Morten

**Comment by plamen-peshev** [comment]
The OrgChart JS won't clear the local storage with names different from state name. For example if the [state name](https://balkan.app/OrgChartJS/API/interfaces/OrgChart.options#state) is "MyStateName", the local storage item with "MyStateName" will be removed, but your local storage items will not be deleted.

**Comment by orgaard** [comment]
After more investigation, from my side, I realized the local storage was cleared due to quota exceeded. I instead started using IndexedDB. However to local storage was still cleared why I wrote an email to support. I got the following answer:

> Hi Morten 
> 
> The local storage quota can exceed only in the trial edition
> 
> In the paid version if you are using the configuration below, the quota will not exceed and your local storage items will not be deleted
> 
>   state: {
>     name: 'binaryTree',
>     readFromLocalStorage: false,
>     writeToLocalStorage: false,
>     readFromIndexedDB: true,
>     writeToIndexedDB: true,
>     readFromUrlParams: false,
>     writeToUrlParams: false,
>   },
> 
> Let me know if you have any additional question/s

I haven't tried the paid version yet, but from the sound of it, this solves my problem. 

Thanks
