### ISSUE TITLE
Example for setting a minimum of 3 letters on searchFields

### ISSUE THREAD

**Issue by NivekStarks** [BALKANGraph/OrgChartJS#863]
Hello,
Could you provide an example of how to set up a search functionality in OrgChart that only triggers after entering a minimum of 3 letters, specifically using the searchFields option?

**Comment by plamen-peshev** [comment]
Do you want to trigger after entering 3 letters in the search input, or you mean 3 letter matches from your data?

**Comment by NivekStarks** [comment]
yes i want to trigger after entering 3 letters/characters in search input

**Comment by plamen-peshev** [comment]
We have added requested functionality in the latest version 8.14.53

Clear your browser cache and test [this Code demo](https://code.balkan.app/orgchart-js/minimum-symbols-in-search-input#JS)

You can get the latest version from [here ](https://orgchartjs.balkan.app/)

**Comment by NivekStarks** [comment]
goood ! Thank u i clos
