### ISSUE TITLE
Changing the node ID

### ISSUE THREAD

**Issue by callmejamie** [BALKANGraph/OrgChartJS#87]
Hi,

I have a question..

Currently when you add a new node on the chart, the node is given a temporary varchar string as an ID (eg. `r7btmrklhpjd4le8jmn0n`). Thing is I want to set a custom ID for the node so it uses the new ID that I had set for it in my DB after I've updated the node with values and have it saved to my DB. 

Problem is, if I change the node's ID to my DB's ID and then try to call the `sender.updateNode` or `sender.update` method, it wouldn't update the newly created node on the chart since it can't find any node with the my DB ID's reference. 

Is there any way that I can set the node's ID to use my new DB ID?

**Comment by plamen-peshev** [comment]
You can use 'add' event handler to cancel the operation get the id from the server and then call 'add' method 

Use the code snippet below as starting point:

```
    var chart = new OrgChart(document.getElementById("tree"), {
        nodeBinding: {
            field_0: "id",
            field_1: "pid"
        },
        nodes: [
            { id: 1 }
        ],
        nodeMenu: {
            add: {text: "Add"}
        }
    });

    chart.on('add', function(sender, node){    
        getId(function(id){
            node.id = id;
            chart.add(node);
        });
        return false;
    });

    function getId(callback){
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                callback(this.responseText);
            }
        };
        xhttp.open("GET", "/getId", true);
        xhttp.send();
    }
```

Apparently  you have to implement '/getId' on your server

**Comment by callmejamie** [comment]
Thanks so much.. managed to get it to work!
