### ISSUE TITLE
OrgChart from List of Members, Drag/Drop From List to OrgChart

### ISSUE THREAD

**Issue by Abdulpgr** [BALKANGraph/OrgChartJS#89]
Can you tell me if I can make orgchart from the list of members? I want to add members in orgchart by dragging them from the list. I will populate the list from the database and then I will ask the user to create orgchart dynamically from that list by dragging and dropping and then save this dynamically created orgchart.
Can you help me with this?

**Comment by plamen-peshev** [comment]
See the following demo: https://balkangraph.com/OrgChartJS-Demos/DragDropItemsToChart

![image](https://user-images.githubusercontent.com/49443821/57229325-75407880-701e-11e9-99a6-b1ab53cd1a78.png)

**Comment by Abdulpgr** [comment]
Hi Planmen,

This demo works fine for me but can you tell me if I want to drag an item
on a chart and make it root node or make it assistant then what should I do?

Can I give menu strip like this, and give options for "Add as assistant" or
"set as root" ?
[image: image.png]
Your help will be very much appreciated.

Thanks

**Comment by plamen-peshev** [comment]
The demo has been modified:  https://balkangraph.com/OrgChartJS-Demos/DragDropItemsToChart


![image](https://user-images.githubusercontent.com/49443821/57686414-3cb62580-7642-11e9-9b26-7e91be2b3d7e.png)

**Comment by Abdulpgr** [comment]
Hi Plamen,

This demo works pretty good, I appreciate your help.

Would you be kind enough to tell me if I can make this chart from scratch?
I mean if there are no nodes on the chart and chart area is empty then if I
drop any node from the list of nodes by dragging it to the chart it should
become first node i.e root node, and then similarly in the other scenario
if there are existing nodes already on the chart connected to some root
node then there should be an option to add another root node if I drop any
node to the empty part of chart area.

Like this demo https://balkangraph.com/OrgChartJS-Demos/SetNodeAsRoot but I
want it after dropping node and when chart area is empty.

Thanks for you help.

**Comment by Abdulpgr** [comment]
Hi Plamen,

This demo works pretty good, I appreciate your help.

Would you be kind enough to tell me if I can make this chart from scratch? I mean if there are no nodes on the chart and chart area is empty then if I drop any node from the list of nodes by dragging it to the chart it should become first node i.e root node, and then similarly in the other scenario if there are existing nodes already on the chart connected to some root node then there should be an option to add another root node if I drop any node to the empty part of chart area.

Like this demo https://balkangraph.com/OrgChartJS-Demos/SetNodeAsRoot but I want it after dropping node and when chart area is empty.

Thanks for you help.
![Untitled](https://user-images.githubusercontent.com/25702715/57752243-e4465d00-7701-11e9-9573-ba73c55646ed.png)

**Comment by plamen-peshev** [comment]
yes, you can

just create new menu with one menu item

**Comment by Abdulpgr** [comment]
I dont quite understand, where should I create this menu item? can you
please give me little example.

**Comment by Abdulpgr** [comment]
Could you please tell me how to make chart area droppable? I want to drop nodes from list to an empty chart area. I want to drop them here where it is written "Its lonely here, add your first node" but I am not able to drop.
![image](https://user-images.githubusercontent.com/25702715/57828354-a9592d80-77c4-11e9-8c9c-d4210c7d39b4.png)

**Comment by ZornitsaSerbezova** [comment]
Here we have created an example of Drag and Drop in an empty chart:
https://github.com/ZornitsaSerbezova/OrgChartIssues/blob/master/89.html

**Comment by ZornitsaSerbezova** [comment]
I'll close this issue, but you cam reopen it again if needed.
