### ISSUE TITLE
PDF preview and PDF export not aligned

### ISSUE THREAD

**Issue by notarnet** [BALKANGraph/OrgChartJS#90]
Hi, 
the pdf preview and the exported pdf look very different:
I'm attaching my application style to export pdf as is rendered in runtime mode.

```javascript
onExportStart: (sender, options, svg) => {
                  svg.querySelector('defs').innerHTML += this.getApplicationStyle();
               }
```
![Preview](https://user-images.githubusercontent.com/5670347/57228399-02320480-7014-11e9-9d98-08084c355581.png)
![Export](https://user-images.githubusercontent.com/5670347/57228435-183fc500-7014-11e9-8586-95c778e4403c.png)

**Comment by plamen-peshev** [comment]
I have tried to replicate the issue with [this](https://balkangraph.com/OrgChartJS-Demos/ExportStyles) demo to no avail

Can you provide small html page where we can see the issue

**Comment by notarnet** [comment]
I attached the svg created after exportStart code is executed.
[test.zip](https://github.com/BALKANGraph/OrgChartJS/files/3148404/test.zip)

**Comment by notarnet** [comment]
Why svg width and height are not recalculated when the user press save button in the preview? The width and height are good to preview window but not for A4. Moreover, as you can see, I selected landscape and paper orientation in the exported chart is portrait.

**Comment by plamen-peshev** [comment]
Can you please send small html with orgchart.js library where we can see the issue, alternatively you can create a demo in js fiddle

**Comment by ZornitsaSerbezova** [comment]
Now the export should be ok. Please, use the latest version.
