### ISSUE TITLE
MS Edge only - JS Error: Unable to get property

### ISSUE THREAD

**Issue by mitkosoft** [BALKANGraph/OrgChartJS#91]
Hi,

With version 4.7.4, in Microsoft Edge browser (Microsoft Edge 42.17134.1.0) I got following JS error:

Unable to get property 'p' of undefined or null reference
orgchart.js (1,86000)

And the chart hangs and cannot be loaded. The library works fine under Chrome.

**Comment by plamen-peshev** [comment]
Hi  Mitko

I was not able to replicate reported issue with the following demo https://balkangraph.com/OrgChartJS/Demos/Tab/BasicUsage

Can you please send small html page where we can see the issue, alternatively you can create a demo in js fiddle

Regards
Plamen

**Comment by mitkosoft** [comment]
Hi Plemene,

I didn't be able to reproduce the problem in js fiddle, so I'll close the ticket and will investigate further the problem on my side. Thanks!
