### ISSUE TITLE
Export csv and then Import the same csv removes groups and tags

### ISSUE THREAD

**Issue by Abdulpgr** [BALKANGraph/OrgChartJS#92]
I am Exporting CSV from this demo,
https://balkangraph.com/OrgChartJS/Demos/ImportFromCSV

and then I import the previously exported CSV with this demo
https://balkangraph.com/OrgChartJS-Demos/ExportImportMethods

But it removes the groups and other tags,
I was exporting this,
![image](https://user-images.githubusercontent.com/25702715/57443022-9eebe080-7266-11e9-88f8-80ffe1dde871.png)

But when I import it back, it removes tags and gives me this,
![image](https://user-images.githubusercontent.com/25702715/57443197-f427f200-7266-11e9-81f2-0b91908322cd.png)

what is the issue??
Also it is giving me this error in console
![image](https://user-images.githubusercontent.com/25702715/57443368-4ec14e00-7267-11e9-819b-a0871113b8bf.png)

**Comment by plamen-peshev** [comment]
https://balkangraph.com/OrgChartJS/Demos/ImportFromCSV demo is obsolete please use only https://balkangraph.com/OrgChartJS-Demos/ExportImportMethods
