### ISSUE TITLE
Professional license 

### ISSUE THREAD

**Issue by mitkosoft** [BALKANGraph/OrgChartJS#93]
Hi,

We would like to purchase a professional license of your library because we will use it in a single web project. But, for this type of license, there is a limitation of 1 IP/domain per license. As our web site is under development, it's still unclear what the exact parameters (either IP or DNS) will be, so how we can integrate a commercial version of your library during the development phase? Is there an option to change this parameter(s) within the license in a later phase after the purchase or we have to ensure what will be they upfront? 

We cannot continue with the evaluation version because of the 200 nodes limitation.

Thank you!

**Comment by plamen-peshev** [comment]
We  provide complimentary aliases for domains used to access development versions of the website (e.g. dev.mycompany.bg; uat.mycompany.com) as long as these websites are are not separate instances. However, if the websites are significantly different in terms of design and content from the website opened by the main production domain, they would not be considered aliases and require you to purchase additional domain licenses.

In domain fields in your account add all domains separated by comma, exmaple: 
dev.mycompany.bg; uat.mycompany.com, 192.168.54.58, qa.mycompany.com, mycompany.bg

**Comment by mitkosoft** [comment]
Thank you, Plamen!

We will proceed as per your suggestion.
