### ISSUE TITLE
Uncaught TypeError: Cannot read property 'p' of undefined

### ISSUE THREAD

**Issue by chrisprabhu** [BALKANGraph/OrgChartJS#96]
Does anyone know what causes this error? I receive it when switching to a new list of dictionaries instead of the default data which was given in the example. I'm not sure what's wrong with the data. 

OrgChart.js:1 Uncaught TypeError: Cannot read property 'p' of undefined
    at Object.OrgChart.remote._fromResDTO (OrgChart.js:1)
    at Object.OrgChart.remote._proceed (OrgChart.js:1)
    at OrgChart.js:1
    at XMLHttpRequest.n.onload (OrgChart.js:1)

**Comment by plamen-peshev** [comment]
try to open in new browser, for example if you are using Chrome open in Firefox and tell us if it works

**Comment by chrisprabhu** [comment]
The error above is from Chrome. I tried in Firefox and I get the following error: 

TypeError: a is undefined[Learn More] OrgChart.js:1:86004
    _fromResDTO https://balkangraph.com/js/latest/OrgChart.js:1
    _proceed https://balkangraph.com/js/latest/OrgChart.js:1
    _walk https://balkangraph.com/js/latest/OrgChart.js:1
    onload https://balkangraph.com/js/latest/OrgChart.js:1

**Comment by plamen-peshev** [comment]
Can you please create a demo where I can see the issue, The demo could be html page, jsfiddle or codepen

**Comment by chrisprabhu** [comment]
Yes. It's part of a Google Apps Script so running it might be tricky. The spreadsheet just has 3 columns: id, pid, name

https://jsfiddle.net/chrisprabhu/mz6bcjf4/

**Comment by plamen-peshev** [comment]
Apparently  <?= nodes; ?> is not properly populated

**Comment by chrisprabhu** [comment]
Here is the JSON.stringify() printout of the data: 

[{"id":"Sun","pid":"","name":"Sun"},{"id":"Earth","pid":"Sun","name":"Earth"},{"id":"Venus","pid":"Sun","name":"Venus"},{"id":"Neptune","pid":"Sun","name":"Neptune"},{"id":"Jupiter","pid":"Sun","name":"Jupiter"},{"id":"Pluto","pid":"Sun","name":"Pluto"},{"id":"The Moon","pid":"Earth","name":"The Moon"},{"id":"Mars","pid":"Sun","name":"Mars"},{"id":"Saturn","pid":"Sun","name":"Saturn"}]

**Comment by plamen-peshev** [comment]
[Here ](https://jsfiddle.net/BALKANGraph/zptLo7ud/1/) is a demo with you OrgChart JS configuration and your data

What is different in your project?

**Comment by chrisprabhu** [comment]
Problem solved. Just had to get the data formatted correctly. This is what fixed it. Thank you for your help!

<?!= JSON.stringify(nodes); ?>
