### ISSUE TITLE
Nodes overlap in OrgChart.tree mode

### ISSUE THREAD

**Issue by mitkosoft** [BALKANGraph/OrgChartJS#97]
Hi,

In a specific case, there is an overlap (no space between them to be precise) between some of the nodes:

![orgchart_tree_overlap](https://user-images.githubusercontent.com/16716343/57773779-7f026400-7721-11e9-9166-06af90cab02a.png)

Is there an option this to be fixed and how?

**Comment by plamen-peshev** [comment]
thanks for reporting this issue

https://jsfiddle.net/tnmg7ob6/1/

It is a bug that will be fixed in one of the following releases

**Comment by ZornitsaSerbezova** [comment]
This bug is fixed and I will close this issue. Please feel free to reopen it if needed.
