### ISSUE TITLE
Rendering HTML

### ISSUE THREAD

**Issue by Mallain23** [BALKANGraph/OrgChartJS#98]
Can we render custom html inside the rectangles ? (For example I would like to render another component inside the rectangle)

**Comment by plamen-peshev** [comment]
https://balkangraph.com/OrgChartJS-Demos/CustomHTMLInsideChart

![image](https://user-images.githubusercontent.com/49443821/57926946-5f9c4000-78b5-11e9-864a-debae56582c0.png)

**Comment by Mallain23** [comment]
I think this demo is for rendering html inside the entire chart area, but is there a way to do it inside the cards themselves ?

**Comment by plamen-peshev** [comment]
See **Node HTML fields**"section from [this](https://balkangraph.com/OrgChartJS/Docs/Fields) help article
