### ISSUE TITLE
Chart with bootstrap nav

### ISSUE THREAD

**Issue by lfmn83** [BALKANGraph/OrgChartJS#99]
I'm using OrgChartJS 4.7.4.  Chart does not appear in a bootstrap nav.  See [JSFiddle](https://jsfiddle.net/lfmn83/x0ojhf8w/6/).

**Comment by plamen-peshev** [comment]
the chart is there and initialized but the size is 0 because the tabs has display none 

you need to load the chart when the tab is clicked

**Comment by lfmn83** [comment]
Thanks @plamen-peshev ,
I added a draw function:

```
$( "#pills-profile-tab" ).click(function(e) {
     setTimeout(function() {
         chart.draw();
     }, 500);
```
 });
